### ISSUE TITLE
Optional warning when unique_list throws out duplicate rows - "filter_rows_with" ?

### ISSUE THREAD

**Issue by tterrace** [sqlalchemy/sqlalchemy#4602] opened 2019-04-09 17:51 UTC
Hi, I recently ran into a situation where a query was accidentally returning 100x the number of rows it should have due to a bad join, but it slipped by for a long time because the de-duping logic in orm/loading.py:instances saved us:

```
        if filtered:
            rows = util.unique_list(rows, filter_fn)
```

I was wondering if it would be a good idea to add an optional warning to catch discrepancies between the raw row count and the unique count. If so, I'd be happy to submit a PR. 

Thanks!

**Comment by zzzeek** [comment] 2019-04-09 20:18
Please see #4395 and I'd prefer someone implement the dedupe_rows(False) method, which will default to False in SQLAlchemy 2.0.

**Comment by zzzeek** [comment] 2019-04-09 20:19
note you will be able to implement a simple event handler that turns on dedupe_rows(False) in all cases for your application so you will no longer have to deal with unique_list.   It will only cause problems if you are using joined eager loading with collections in which case you'll want to turn it on for those queries.

**Comment by tterrace** [comment] 2019-04-10 15:53
Thanks, the dedupe_rows does seem like a better option. What do you think of a third mode: `dedupe_rows('error')`, where it would throw an exception if the deduper found anything? Applying that globally with an event handler could help large codebases clean up their queries before the big change to make dedupe_rows opt-in rather than the default.

**Comment by zzzeek** [comment] 2019-04-10 17:14
Maybe one can pass in their own custom deduplication routine into this method or some other kind of results filter, there might be a desire for pluggable results filtering overall and we can leverage that at the same time.

The reason this area is tricky is because if you are querying using joined eager loading, it is expected that you'd have a lot of duplicate entities and you wouldn't want a warning to be emitted. Similarly, some explicit join() use cases are doing the same thing, either with contains_eager() or maybe they're doing something else.   So it's not that easy to just "warn" because we have to guess when we want the warning and when we don't.   

in 2.0 we're going to see if we can just make the deduping thing only occur when someone asks for it explicitly, which will also solve problems like how count() never matches up.   joined eager loading for collections will be de-emphasized as there are more loaders now for collections that are more efficient.     Also in 2.0 the whole "list of entities" result thing is not the default, you get tuples in all cases unless you ask for a list of scalar entities.

**Comment by sqla-tester** [comment] 2019-04-12 18:35
**Tom Terrace** has proposed a fix for this issue in the **master** branch:

**Add a dedupe_rows method to the Query class** https://gerrit.sqlalchemy.org/1193

**Comment by zzzeek** [comment] 2019-08-23 17:18
I've proposed some changes for the feature here:

I'm trying to think of an open-ended way this feature can be added for now in a way that doesn't conflict with that I might want to change defaults and such here.

Can we make this look like:

    query.filter_rows_with(<some callable>)  -> filters rows w given callable
    query.filter_rows_with(None)  -> turns off row filtering unconditionally

And the above would apply to *any* kind of result, that is, whether or not it has entities, or if it's just columns, etc.

this might be easier for me to allow to go in sooner while allowing me to have  flexibility in how I approach the specific notion of "deduplicating rows" in subsequent versions.

the above method I can probably backport to 1.3.x

**Comment by zzzeek** [comment] 2020-01-10 16:35
I think for now this issue is a dupe of #4395 and as for the filter stuff I'm referring to above, I don't know that that's worth it for now.  I'm attempting to gather all the "make the Query return results like this" issues under a common label so I can try to figure out a bigger strategy for something that works for the legacy Query API and can also transition smoothly to 2.0, as well as what is the 2.0 API.

**Closed by zzzeek** 2020-01-10 16:35 UTC
Labels: orm, result fetching API improvements, use case
