### ISSUE TITLE
[starting 1.4.7] Children objects are duplicated when setting backref

### ISSUE THREAD

**Issue by chaen** [sqlalchemy/sqlalchemy#6280] opened 2021-04-15 13:27 UTC
**Describe the bug**

I have `Parent` and `Child` classes, with a one-to-many relationship. The `Child` class has a `backref` to the `Parent` called `_parent`. These objects often live outside of `SQLAlchemy`, so I need to maintain this reference myself sometimes.  
If I get a family from the DB, and then try to assign myself the `backref` parameter, the children objects are duplicated 

**Expected behavior**

This behaviour is new in `1.4.7` and still happens against the master branch of the repo.
When running the example bellow with 1.4.7 and 1.4.6, the debug logs are perfectly identical.

**To Reproduce**

```py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import logging

from sqlalchemy.orm import relationship, backref, sessionmaker, joinedload, mapper
from sqlalchemy import create_engine, Table, Column, MetaData, ForeignKey, \
    Integer, String


logging.basicConfig()
logging.getLogger("sqlalchemy.engine").setLevel(logging.DEBUG)


class Parent(object):
  """ Parent class, managing children """

  def __init__(self):
    self.ParentName = None

  def _notify(self):
    for child in self.__children__:
      # PROBLEM HAPPENS HERE
      # When setting the _parent value once the
      # object was retrieved from the DB, so
      # in the del r[0] call,
      # the children ends up being duplicated
      child._parent = self

  def __contains__(self, child):
    return bool(child in self.__children__)

  def __iadd__(self, child):
    """ Add a Child to the list of children, and
        set the backref
    """
    if child not in self:
      self.__children__.append(child)
      child._parent = self
      self._notify()
    return self

  def __delitem__(self, i):
    self.__children__.__delitem__(i)
    self._notify()

  def __len__(self):
    """ nb of subParents """
    return len(self.__children__)


class Child(object):
  """ Dummy Child class, with backref to the parent """

  def __init__(self, ChildName):
    self.ChildName = ChildName
    # backref
    self._parent = None

########################################################################


metadata = MetaData()

childTable = Table('Child', metadata,
                   Column('ChildName', String(64), nullable=False),
                   Column('ChildID', Integer, primary_key=True),
                   Column('ParentID', Integer,
                          ForeignKey('Parent.ParentID', ondelete='CASCADE'),
                          nullable=False),
                   mysql_engine='InnoDB')


mapper(Child, childTable)


parentTable = Table('Parent', metadata,
                    Column('ParentName', String(255), nullable=False),
                    Column('ParentID', Integer, primary_key=True),
                    mysql_engine='InnoDB')

mapper(Parent, parentTable, properties={'__children__': relationship(Child,
                                                                     backref=backref('_parent',
                                                                                     lazy='immediate'),
                                                                     lazy='immediate',
                                                                     passive_deletes=True,
                                                                     cascade="all, delete-orphan")})


########################################################################
class FamilyDB(object):

  def __init__(self):

    self.dbHost = 'mysql'
    self.dbPort = 3306
    self.dbUser = 'root'
    self.dbPass = 'password'
    self.dbName = 'Test'

    self.engine = create_engine('mysql://root:password@mysql:3306/Test')

    metadata.bind = self.engine

    self.DBSession = sessionmaker(bind=self.engine)
    metadata.create_all(self.engine)

  def putParent(self, parent):
    """ Put a parent and children in the DB """

    session = self.DBSession(expire_on_commit=False)
    try:

      parent = session.merge(parent)
      session.add(parent)
      session.commit()
      session.expunge_all()

      return parent.ParentID

    except Exception:
      session.rollback()
      raise
    finally:
      session.close()

  def getParent(self, parentID):
    """Get a parent from the DB with its children"""

    session = self.DBSession(expire_on_commit=False)

    try:
      parent = session.query(Parent) \
          .options(joinedload('__children__')) \
          .filter(Parent.ParentID == parentID)\
          .one()

      session.expunge_all()
      return parent

    except Exception:
      session.rollback()
      raise
    finally:
      session.close()


def deathScenario():

  db = FamilyDB()

  # Create my test data, a parent with 2 children
  p = Parent()
  p.ParentName = "Father"

  ch1 = Child("Child1")
  ch2 = Child("Child2")

  p += ch1
  p += ch2

  parentID = db.putParent(p)

  # Now retrieve that family from the DB
  p = db.getParent(parentID)

  # I expect here that the parent has 2 children
  assert len(p) == 2

  # Let's kill one child :-)
  del p[0]

  # I expect the parent to have a single child left
  # But here it fails, and has 2.
  # The same one is duplicated
  assert len(p) == 1, p.__children__


if __name__ == '__main__':
  deathScenario()
```

**Error**

```
Traceback (most recent call last):
  File "/tmp/reproducer/reproducer2.py", line 181, in <module>
    deathScenario()
  File "/tmp/reproducer/reproducer2.py", line 177, in deathScenario
    assert len(p) == 1, p.__children__
AssertionError: [<__main__.Child object at 0x7fb7e541e590>, <__main__.Child object at 0x7fb7e541e590>]
```

**Versions.**
 - OS: CentOS Linux release 7.8.2003
 - Python: 2.7.13
 - SQLAlchemy: from 1.4.7 onward
 - Database: Mysql
 - DBAPI: MySQL-python 1.2.5

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-04-15 13:52
ok, you're using lazy="immediate" and we necessarily changed some things about it in #6232.  I havent deeply understood waht's happening here yet, but if we take out those "immediateload" settings, then run your script in any SQLAlchemy version, the assertion at the end fails in the same way.

the "immediateload" directive should not change any behaviors, so this suggests this script is somehow relying on the previously broken behavior of "immediateload", since now the script behaves consistently no matter what loader strategy is used.

it looks like in your operation you are essentially doing this:

```
(pdb) !p.__children__
[<__main__.Child object at 0x7fa2d92a8e50>, <__main__.Child object at 0x7fa2d92a8ee0>]
p.__children__[1]._parent = p
(Pdb) !p.__children__
[<__main__.Child object at 0x7fa2d92a8e50>, <__main__.Child object at 0x7fa2d92a8ee0>, <__main__.Child object at 0x7fa2d92a8ee0>]
(Pdb) 


```

whether or not we like what that says, that's the normal behavior. 

what I'm not getting yet is how the former "immediateload" behavior was changing this, as it seems to be, so i will do that now but at the moment it's looking like this program somehow relies upon a weird unexpected behavior.

**Comment by chaen** [comment] 2021-04-15 13:58
Thanks for the impressively fast response :-) 

I am not quite sure to understand how what you show is a normal behaviour ? Naively, I would expect that this `__children__` list is just an ORM representation of what you would get by doing `SELECT * from Child where ParentID = 123`. And I would not expect seeing duplicates there. But probably I am just misunderstanding this `relationship`

**Comment by zzzeek** [comment] 2021-04-15 14:13
when you append to a relationship collection that has a backref to a many-to-one, or you assign to a many-to-one that has a backref to a collection, there's an attribute event that will populate in the other direction.    What seems to be happening here is that the "immediateload" was previously being fired off on the other side of the Parent.__children__ joinedload, onto the Child._parent, which is not the normal eager loader behavior right now, as the eager loaders want to avoid going into recursive loops.  The fix in #6232 was to repair this recursive loop as stated in the "immediateload" loader; this was formerly not a very widely used loader so the apparent recursion issue was not apparent until 1.4 made greater use of this strategy.

So what would happen is that since Child._parent was already loaded, when you set it again, no backref event would grow the collection.   With the repaired behavior, Child._parent is not loaded so when you assign to it, the relationship mechanics don't try to guess what the old value was, the new one goes right in, which fires off the event.

the overall problem with the program here is that it is doubling the work that backref already does.    if you simply remove the whole _notify() step, which is unnecessary, as well as the redundant child._parent assignments that follow the equivalent collection operation.  you get  a much shorter script and everything works:

```python
class Parent(object):
    """ Parent class, managing children """

    def __init__(self):
        self.ParentName = None

    def _notify(self):
        pass
        # for child in self.__children__:
            # this should never be done if backrefs are in use
        #     child._parent = self

    def __contains__(self, child):
        return bool(child in self.__children__)

    def __iadd__(self, child):
        """Add a Child to the list of children, and
        set the backref
        """
        if child not in self:
            self.__children__.append(child)
            # child._parent = self  # redundant
            # self._notify()
        return self

    def __delitem__(self, i):
        self.__children__.__delitem__(i)
        # self._notify() # redundant

    def __len__(self):
        """ nb of subParents """
        return len(self.__children__)

```

**Comment by zzzeek** [comment] 2021-04-15 14:17
also if you want to avoid dupes in a collection, you would use [collection_class=set](https://docs.sqlalchemy.org/en/14/orm/collections.html#custom-collections).

**Comment by chaen** [comment] 2021-04-15 14:45
I see thanks. 
Unfortunately, the `notify` in reality does much more than what it says here, and I need to have this backref mechanism in place already before the objects are known to `SQLAlchemy`. 

So basically, what I need to make sure is that I do not set the `_parent` attribute if that object is currently managed by `SQLAlchemy`. Is there a recommended way to do that ? I've realized that funnily enough `hasattr(child, '_parent')` returns `False` if that backref is managed by SQLAlchemy, so I could rely on that, but that's sort of a hack...

**Comment by zzzeek** [comment] 2021-04-15 15:06
you are....mapping classes *after* you've used instances of those classes?

**Comment by chaen** [comment] 2021-04-16 09:01
Yep :-/ We create the instances, do whatever we have to do with them, and later on persist them with SQLAlchemy in the DB. The reason being that they are created on some machines without access to the DB (nor to SQLAlchemy in fact), used, and then serialized over the network to later be persisted. And they go the other way around too.

**Comment by zzzeek** [comment] 2021-04-16 12:00
OK but I would assume the notion is you have code that deals with objects in both states and does not know which state they are in.  this is a really dangerous pattern and I think your app should "know" whether or not classes are mapped, and have distinct codepaths for dealing with them.  

Also no database access is implied by having SQLAlchemy installed, imported, and the classes mapped.   It doesn't make sense that you have your software installed in Python environments where SQLAlchemy is not installed, you should add it to your requirements for those installations and the classes should just be mapped up front so that they behave consistently.

all of that aside, in this case if you are duplicating the behavior of a backref because your current envrionment may or may not have imported SQLAlchemy and mapped the classes or not, you should check if "child._parent is self" before setting it.

**Comment by chaen** [comment] 2021-04-16 12:54
I totally agree that it is a bad design to start with. A redesign I have on my plate is long overdue :-/ SQLAlchemy 1.4 seems to have cleaned a lot of things, so the flaws in my piece of code start showing up. 

> you should check if "child._parent is self" before setting it.

That actually raises a `DetachedInstanceError`, but that's fine, that's good enough for me to test

**Comment by zzzeek** [comment] 2021-04-16 13:09
> I totally agree that it is a bad design to start with. A redesign I have on my plate is long overdue :-/ SQLAlchemy 1.4 seems to have cleaned a lot of things, so the flaws in my piece of code start showing up.
> 
> > you should check if "child._parent is self" before setting it.
> 
> That actually raises a `DetachedInstanceError`, but that's fine, that's good enough for me to test

OK look inside `__dict__` instead , `child.__dict__.get('_parent', None) is self`

**Comment by chaen** [comment] 2021-04-16 14:11
Thanks. turns out I also need to check `child.__class__.__dict__` in case it comes from the DB (so after the get). 

Clearly, I must redesign my code... It actually comes from legacy code, before using SQLAlchemy. At the time of introducing, one requirement we had that we could still have clients without sqlalchemy installed at all. I understand that this mixed environment is clearly not something you recommend ?

**Comment by zzzeek** [comment] 2021-04-16 14:13
> Thanks. turns out I also need to check `child.__class__.__dict__` in case it comes from the DB (so after the get).
> 
> Clearly, I must redesign my code... It actually comes from legacy code, before using SQLAlchemy. At the time of introducing, one requirement we had that we could still have clients without sqlalchemy installed at all. I understand that this mixed environment is clearly not something you recommend ?

it just seems unnecessary unless this is an application running on raspberry pi's or cellphones?

**Closed** 2021-04-16 14:14 UTC
Labels: orm, question
