### ISSUE TITLE
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) Packet sequence number wrong - got 0 expected 1

### ISSUE THREAD

**Issue by Baloneo** [sqlalchemy/sqlalchemy#7586] opened 2022-01-19 02:40 UTC
### Describe the bug

Occurs when MySQl connection times out

### To Reproduce

config mysql connection wait_timeout
```sql
SET GLOBAL wait_timeout=10
```

code
```
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_scoped_session
from sqlalchemy.orm import declarative_base, sessionmaker
from asyncio import current_task

from config import current_config

engine = create_async_engine(current_config.MYSQL_DB_URL, future=True, echo=False, pool_pre_ping=True)
session_factory = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)
Session = async_scoped_session(session_factory, scopefunc=current_task)
Base = declarative_base()
```

```
async def dep_session() -> AsyncSession:
    async with Session() as session:
        yield session

```

```
@router.get("/public/{article_id}")
async def get_articles(
    article_id: int,
    session: AsyncSession = Depends(dep_session),
):
    """
    http GET ":${API_PORT}/api/v1/articles/1"
    """
    stmt = select(Article).where(Article.id == article_id, Article.status == ConstArticleStatus.PUBLIC)
    result = await session.execute(stmt)
    article = result.scalar_one_or_none()
    if not article:
        return success_json({"content": "# Article not found!"})

    return success_json({**await model2dict(article, callback=partial(parse_tag, session))})

```

### Error
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/baloneo/gitee/blog_fastapi/app/api/articles/articles.py", line 46, in get_articles
    total_count, query_set = await help_paginate(session, stmt, page=get_data.page, size=get_data.size)
  File "/home/baloneo/gitee/blog_fastapi/app/response.py", line 73, in help_paginate
    total_count = await session.scalar(sqlalchemy.func.count().select().select_from(query_stmt))
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 236, in scalar
    result = await self.execute(
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 211, in execute
    return await greenlet_spawn(
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3253, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in _checkout
    result = pool._dialect.do_ping(fairy.dbapi_connection)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 183, in do_ping
    dbapi_connection.ping(False)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 190, in ping
    return self.await_(self._connection.ping(reconnect))
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/aiomysql/connection.py", line 453, in ping
    await self._read_ok_packet()
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/aiomysql/connection.py", line 331, in _read_ok_packet
    pkt = await self._read_packet()
  File "/home/baloneo/.local/share/virtualenvs/blog_fastapi-FVtvaIKU/lib/python3.8/site-packages/aiomysql/connection.py", line 572, in _read_packet
    raise InternalError(
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) Packet sequence number wrong - got 0 expected 1
(Background on this error at: https://sqlalche.me/e/14/2j85)

``` 

### Versions

- OS: Linux
- Python: 3.8
- SQLAlchemy: 1.4.29
- Database: MySQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by CaselIT** [comment] 2022-01-19 07:26
Hi,

I would suggest using the other async dialect for mysql, since aiomysql is not very reliable.
Can you check if the issue is resolved by switching dialect?

**Comment by Baloneo** [comment] 2022-01-19 08:28
Thanks, seems like there is no problem in asyncmy

**Comment by CaselIT** [comment] 2022-01-19 08:46
Good to hear.

@zzzeek do you think it's something we can fix on out end?

**Comment by zzzeek** [comment] 2022-01-19 13:59
how would SQLAlchemy affect this?  looks like just more things in aiomysql that don't work?

**Comment by CaselIT** [comment] 2022-01-19 17:29
My guess as well. Should we just deprecate it at this point?

**Comment by zzzeek** [comment] 2022-01-19 18:19
it outright breaks in 3.10 so i would think we would get more clarity on this driver in the coming weeks if they want to maintain it again or not.  

we have a red dragon warning for it, seems to big of a name to just remove it totally yet

**Closed by zzzeek** 2022-01-19 18:19 UTC
Labels: mysql, external driver issues, asyncio
