### ISSUE TITLE
sqlalchemy.query.Query.join should enforce argument schema

### ISSUE THREAD

**Issue by dpitch40** [sqlalchemy/sqlalchemy#7037] opened 2021-09-16 17:56 UTC
### Describe the bug

I was writing a call to `Query.join` with an explicit ON clause yesterday and forgot that it doesn't work like `Query.filter` (i.e. multiple criteria are not automatically combined with `and_`. As a result, I was getting the error traceback shown below. It took a good deal of struggling to realize that I needed to combine my two join criteria with a call to `and_`.

It seems like `join` can do better. Calling `join` with multiple join criteria is not, as far as I can tell, is not one of its allowed calling forms, modern or legacy. The method should be able to determine if its arguments don't conform to any of the allowed forms and, if not, raise a more helpful exception pointing the user error out. (It did give a warning that using multiple join conditions will be deprecated in 2.0, but these warnings are hidden by default) This would match the straightforward error that gets raised when calling a built-in function or method with an incorrect signature.

Also, the 1.4 documentation on the parameters for `Query.join` appears to be missing `target`, instead starting with `props`.

### To Reproduce

```python
from sqlalchemy import Column, Integer, String, DateTime, create_engine, func, ForeignKey, and_
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.declarative import declarative_base

DB_URL = 'sqlite://'

Base = declarative_base()
engine = create_engine(DB_URL)

class Parent(Base):
    __tablename__ = 'parents'

    id_ = Column('id', Integer, primary_key=True)

class Child(Base):
    __tablename__ = 'children'

    id_ = Column('id', Integer, primary_key=True)
    parent_id = Column('parent_id', Integer, ForeignKey('parents.id'))
    parent = relationship('Parent', backref='children')
    timestamp = Column('timestamp', DateTime)
    name = Column('name', String)

def main():
    Base.metadata.create_all(engine)
    session = sessionmaker(bind=engine)()

    query = session.query(Child.id_, Child.timestamp, Child.parent_id, Child.name)
    query = query.filter(Child.parent_id == 1)
    subquery = session.query(Child.parent_id, func.max(Child.timestamp).label("timestamp")).group_by(
        Child.parent_id).subquery()

    # Works
    query = query.join(subquery, and_(Child.parent_id == subquery.c.parent_id,
            Child.timestamp == subquery.c.timestamp))
    print(query.all())

    # Doesn't work
    query = query.join(subquery, Child.parent_id == subquery.c.parent_id,
        Child.timestamp == subquery.c.timestamp)
    print(query.all())

if __name__ == '__main__':
    main()
```

### Error

```
Traceback (most recent call last):
  File "sqlalchemy_join_issue.py", line 45, in <module>
    main()
  File "sqlalchemy_join_issue.py", line 42, in main
    print(query.all())
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1444, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 518, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 553, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 765, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 454, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 489, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3105, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 500, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 659, in create_for_statement
    self._setup_for_generate()
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 690, in _setup_for_generate
    self._legacy_join(query._legacy_setup_joins, self._entities)
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 1550, in _legacy_join
    self._join_left_to_right(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 1592, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(
  File "/home/david/.local/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 1710, in _join_determine_implicit_left_side
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Don't know how to join to <sqlalchemy.sql.selectable.Subquery at 0x7f774fbcf910; anon_1>. Please use the .select_from() method to establish an explicit left side, as well as providing an explicit ON clause if not present already to help resolve the ambiguity.
```

### Versions

- OS: Ubuntu 18.04, Linux Mint 19.3
- Python: 3.7.12, 3.8.0
- SQLAlchemy: 1.4.23, 1.3.22
- Database: SQLite, PostgreSQL
- DBAPI: pysqlite, psycopg2

**Comment by zzzeek** [comment] 2021-09-16 18:04
hi there -

as you noted, the pattern is deprecated and will be removed in SQLAlchemy 2.0, and IMO there is already a deprecation warning.   to add more code to emit a *second* warning, which we would assume is trying to guess that this additional parameter is not in the expected format, otherwise would not warn and would default to the legacy behavior, would be a lot of work to implement only to be thrown away in a few months.   the usage mistake here is not common at all and I think now that you've found it you will likely not be bothered by it further, so id favor closing this as a dupe.

**Comment by dpitch40** [comment] 2021-09-16 18:09
Why are the deprecation warnings hidden by default? If I had seen the warning, it would have tipped me off that I was calling join wrong.

I don't think this pattern is deprecated, though--it simply isn't (or shouldn't be) allowed at all.

**Comment by zzzeek** [comment] 2021-09-16 18:16
> Why are the deprecation warnings hidden by default? 

2.0 deprecation warnings are hidden so that people can follow the 2.0 migration process documented at https://docs.sqlalchemy.org/en/14/changelog/migration_20.html.  There are lots of very major 2.0 deprecations and turning on this flag makes for a very noisy application.

> If I had seen the warning, it would have tipped me off that I was calling join wrong.

the join() method raises an error with that call, which led you to figure out what was wrong with it - it did not silently render the wrong SQL which would have been worse.  I apologize that we can't do better for now but that's why this poor calling style is being removed.    When more than two arguments are passed to the join() call, it moves into an entirely different mode of usage.   The most we can do is add some message to the error such as "multiple target mode selected", im not sure that would have meant much if someone is already just learning how to use the join() call.

> 
> I don't think this pattern is deprecated

sending multiple join targets is allowed, and the error checking goes through these targets one by one to see if they are valid.   in your case, you are sending three join targets, all of which will fail.  however unfortunately the first one is the one that fails first, which leads to a less clear error.  if you had sent just two binary expressions, the error would be more clear: "sqlalchemy.exc.ArgumentError: Expected mapped entity or selectable/table as join target"

as mentioned previously, adding more words to the error message is all we can do here but i dont know that this really helps anyone very much.   I doubt you will have this problem again and when 2.0 is out the problem is gone forever.

we are really trying to get issues off the table so we can get the 2.0 release happening.

**Comment by zzzeek** [comment] 2021-09-19 14:30
agree there's a less than ideal situation here but to address it we've aggressively deprecated the pattern.   adding better error messaging for the legacy pattern is not worth it as this has been the same way for at least a decade, this is not the time to destabilize legacy code that is going away in any case.

**Closed by zzzeek** 2021-09-19 14:30 UTC
Labels: duplicate, question
