### ISSUE TITLE
Move create_type argument from postgres.ENUM to generic Enum

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/sqlalchemy#5593] opened 2020-09-17 09:50 UTC
**Is your feature request related to a problem? Please describe.**
It's a quite troublesome to reuse enum type on postgresql database using alembic. Especially in case when a support of various database backends is required. The problem is discussed in https://github.com/sqlalchemy/alembic/issues/278 and other places. All solutions seem to include only postgresql specific variant. Clear database agnostic solution doesn't seem to be available.

**Describe the solution you'd like**
I suggest to move the `create_type` argument from `postgres.ENUM` to generic `Enum` type. That would allow to create a clean database agnostic migration that would work on postgres and possibly other databases.

Example of database agnostic migration:
```python
def upgrade():
    connection = op.get_bind()
    status_enum = sa.Enum('pending', 'accepted', 'canceled', name='status_enum', create_type=False)
    status_enum.create(connection)
    op.add_column('mytable', sa.Column('status', status_enum))
    op.add_column('mytable', sa.Column('other_status', status_enum))
```

**Describe alternatives you've considered**
I've spent some time browsing sqlalchemy and alembic source code and haven't found other reasonable solution.

**Comment by zzzeek** [comment] 2020-09-17 15:08
> **Is your feature request related to a problem? Please describe.**
> It's a quite troublesome to reuse enum type on postgresql database using alembic. Especially in case when a support of various database backends is required. The problem is discussed in [sqlalchemy/alembic#278](https://github.com/sqlalchemy/alembic/issues/278) and other places. All solutions seem to include only postgresql specific variant. Clear database agnostic solution doesn't seem to be available.

when you mention "variant", I'm not sure if this is what you mean but this is a built in feature of SQLAlchemy that was designed in order to accommodate for datatypes that have database-specific flags:

https://docs.sqlalchemy.org/en/13/core/type_api.html?highlight=with_variant#sqlalchemy.types.TypeEngine.with_variant

so in this case, you'd get an enum like this:

```
args = 'pending', 'accepted', 'canceled'
my_enum = sa.Enum(*args).with_variant(
   postgresql.ENUM(*args, name='status_enum', create_type=False)
)

```

the "my_enum" above is a database-agnostic type.   

> 
> **Describe the solution you'd like**
> I suggest to move the `create_type` argument from `postgres.ENUM` to generic `Enum` type. That would allow to create a clean database agnostic migration that would work on postgres and possibly other databases.

I'm -1 on this because there are many examples of datatypes with backend-specific keywords, and as we like to have as consistent of an approach to everything as possible, moving this flag here would mean that for other types like String, we'd have to move all of MySQL's flags like "charset", "collation", "ascii", "binary" into sqltypes.String(), etc., which would then be very confusing and lead to naming conflicts.    Another approach would be that we use the DDL keyword approach, like "postgresql_create_type=False", but this again implies an explosion of keywords and we are trying to move further with the variant approach as it is more flexible and maintainable as you can see in #5461. 


> 
> Example of database agnostic migration:
> 
> ```python
> def upgrade():
>     connection = op.get_bind()
>     status_enum = sa.Enum('pending', 'accepted', 'canceled', name='status_enum', create_type=False)
>     status_enum.create(connection)

I think an issue with the above is that "create()" does not apply to any database other than PostgreSQL, and the create step would need to have more explicitness that it is conditional only.

The long term plan for ENUM on alembic is to have all new alembic constructs that handle this type and all of its current quirks in a consistent way, most likely something like an op.create_enum(enums, name) kind of operation that itself works using the "variant" concept, like:

   if op.only_on("postgresql"):
        op.create_enum(*enums, name)

then within a create_table(), some kind of internal flag would ensure that the Enum() as given for PostgreSQL doesn't try to create the type twice, this would likely be a global assumption that assumes "create_enum()" is used.

however we do not have the development resources to work on this right now as SQLAlchemy 1.4 / 2.0 is the high priority.   The ENUM issue in Alembic is something I need to find time to work on long term such that I can consider a full-span solution for the entire problem, and there are already [six open issues](https://github.com/sqlalchemy/alembic/issues?q=is%3Aopen+is%3Aissue+label%3A%22autogenerate+for+enums%22) all of which are highly overlapping.  to the degree that changes will need to be made in SQLAlchemy to support this design, I will open those as well.  

For the moment, I am not prepared to make any major API changes to Enum until we've worked out a complete plan, and this plan will be worked out on the Alembic side, so there's no need to keep opening more issues here.   thanks!

**Comment by zzzeek** [comment] 2020-09-22 20:23
fully in agreement that the Alembic story for ENUM is pretty bad right now.   We have five issues opened over there, so if/when we get to this, we'll do what we have to to make it smooth.

**Closed by zzzeek** 2020-09-22 20:23 UTC
Labels: question
