### ISSUE TITLE
Incorrect Documentation for Multiple Fallback Hosts

### ISSUE THREAD

**Issue by manmedia** [sqlalchemy/sqlalchemy#8319] opened 2022-07-31 22:24 UTC
### Describe the bug

1. Multiple Fallback Hosts option described [here](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#specifying-multiple-fallback-hosts) is not correct.
2. The correct format is in the ticket - and I have tested and verified. 

### To Reproduce

```python
# please replace database name with your database
from sqlalchemy import create_engine


if __name__ == '__main__':
  try:
    engine = create_engine("postgresql+psycopg2://<uname>:<pwd>@/<db_name>?&host=<host_1>:<port>&host=<host2>")
    with engine.connect() as connection:
        result = connection.execute("SELECT * from pg_catalog.pg_tables")
        for row in result:
            print (row[:])
    print(
      f"Welcome, you have made connection!!!")
  except Exception as ex:
    print(ex)
```

### Error

(psycopg2.OperationalError) could not translate host name "XXXXXXX-1:5432" to address: Name or service not known
connection to server at "XXXXXXXX-2" (ip_addr), port 5432 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Server not found in Kerberos database
connection to server at "XXXXXXXX-2" (ip_addr) port 5432 failed: server is in hot standby mode
connection to server at "XXXXXXXX-3" (ip_addr), port 5432 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Server not found in Kerberos database
connection to server at "XXXXXXXX-3" (ip_addr), port 5432 failed: server is in hot standby mode

### Versions

- OS: CentOS 7
- Python: 3.8
- SQLAlchemy: 1.4.39
- Database: PostgreSQL 14.0
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2-binary 2.9.3

### Additional context

1. The documentation for SQLALchemy is Incorrect
2. The fix is - `postgresql+psycopg2://<uname>:<pwd>@/<db_name>?&host=<host_1>:<port>&host=<host2>&port=<port_no>&target_session_attrs=primary`

- Keeping port number separate from host address fixes the issue
- target_session_attrs=primary allows the Multiple fallback hosts to work together so that when a primary database host is available, that's take. Otherwise, the next item is take. By default `terget_session-attrs=any` which is not what the SQLAlchemy documentation clarifies

**Comment by CaselIT** [comment] 2022-08-01 07:48
Hi,

The documentation seems correct, since it's consistend with the postgresql documentation https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

> In the connection URI format, you can list multiple host:port pairs separated by commas in the host of the URI.

Then again the postgresql documentation is not very clear here, since it also says a few lines above the previous quote

> It is possible to specify multiple host components, each with an optional port component, in a single URI. A URI of the form postgresql://host1:port1,host2:port2,host3:port3/ is equivalent to a connection string of the form host=host1,host2,host3 port=port1,port2,port3.

So from here it seems that both the documented version and proposed change are correct

**Comment by manmedia** [comment] 2022-08-01 08:07
@CaselIT Thanks for your response, and I still disagree. And my reasoning is below

1. Under "Multiple Fallback Hosts Section" - https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#specifying-multiple-fallback-hosts - it says completely different thing about how the URL should be formed. I quote para directly from website below:

> psycopg2 supports multiple connection points in the connection string. When the host parameter is used multiple times in the query section of the URL, SQLAlchemy will create a single string of the host and port information provided to make the connections:
`create_engine(
    "postgresql+psycopg2://user:password@/dbname?host=HostA:port1&host=HostB&host=HostC"
)`

> A connection to each host is then attempted until either a connection is successful or all connections are unsuccessful in which case an error is raised.

it's not possible that both documentation is correct. As per my bug ticket above, if we follow what's been asked in SQLAlchemy for Multiple Fallback hosts, it doesn't work. 

Thanks,

**Comment by CaselIT** [comment] 2022-08-01 08:21
>  it has one of the host:port - where did the others go?

not sure I follow. You mean port? I guess in the example the other host have the default port. Otherwise it can be specified using the `host:port`. I guess it could be clarified

> when we specify host1:port, host2:port as part of URL (as you mentioned in your comment) ...

That's probably because sqlalchemy only allows the canonical way of specifying multiple values for the same url query param, that is repeating it multiple times in the url.
So you should be able to connect using `....?host=host1:port1&host=host2:port2&...`

**Comment by manmedia** [comment] 2022-08-01 08:28
@CaselIT I believe it's easier if I mention it like this
1. The way https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#specifying-multiple-fallback-hosts is suggesting to format the host without specifying the port for host2 and host3 - won't work. and results into error. My original ticket has steps to reproduce that.

2. What would work (and I have just tested) - is a clear example in documentation so that:
    - postgresql+psycopg2://username:password@host1,host2,host3/dbname?target_session_attrs=primary
    - postgresql+psycopg2://username:password@/dbname?host=host1&host=host2&host=host3&target_session_attrs=primary

The above only works if the port is default 5432. But my point here is - current documentation isn't clear - and should be corrected. If you don't think it's needed, then I suppose everyone who'd spend 30 minutes figuring this out, can read the ticket and get the answer. I am simply trying to save others' time in researching into it.

**Comment by CaselIT** [comment] 2022-08-01 08:45
As I mentioned before the documentation could probably be clearer.
But again sorry but it's not clear to me what the issue in your use case is.
- are you using multiple hosts that are not using the default pot?
- is each host using a different port?
- does specifying the host in the format `....?host=host1:port1&host=host2:port2&...` work?

**Comment by CaselIT** [comment] 2022-08-01 09:21
I've tried a bit, and it seems that passing `'postgresql://scott:tiger@/test?host=127.0.0.1:5432&host=127.0.0.1:5433'` will fail with the error 
```
(psycopg2.OperationalError) could not translate host name "127.0.0.1:5432" to address: Unknown host
could not translate host name "127.0.0.1:5433" to address: Unknown host
```

while this seems to work instead `'postgresql://scott:tiger@/test?host=localhost,localhost&port=5433,5432'`.

So I agree that the the documentation is wrong.

Also re-reading the pg documentation, the part:
> In the connection URI format, you can list multiple host:port pairs separated by commas in the host of the URI.

seems to refer to the host spec part of the url, not the host query parameter.

@zzzeek do you know why the documentation what written that way?

**Comment by zzzeek** [comment] 2022-08-01 13:38
> I've tried a bit, and it seems that passing `''postgresql://scott:tiger@/test?host=localhost:5432&host=localhost:5433'` will fail with the error
> 
> ```
> (psycopg2.OperationalError) could not translate host name "localhost:5432" to address: Unknown host
> could not translate host name "localhost:5433" to address: Unknown host
> ```
> 
> while this seems to work instead `'postgresql://scott:tiger@/test?host=localhost,localhost&port=5433,5432'`.
> 
> So I agree that the the documentation is wrong.

no, that would mean the feature is wrong.  that is absolutely not what this was intended to look like.   We would need to reopen #4392, declare this a dupe, and re-implement the feature correctly.     the poster's syntax of `postgresql+psycopg2://<uname>:<pwd>@/<db_name>?&host=<host_1>:<port>&host=<host2>&port=<port_no>&target_session_attrs=primary` doesn't seem to make any sense at all (why put the "port" in two different ways? ) so that likely works by accident.


> Also re-reading the pg documentation, the part:
> 
> > In the connection URI format, you can list multiple host:port pairs separated by commas in the host of the URI.
> seems to refer to the host spec part of the url, not the host query parameter. That's not overly clear on their part

yes, that's what we implemented:

```py
>>> from sqlalchemy.dialects.postgresql import psycopg2
>>> from sqlalchemy.engine import url
>>> u = url.make_url("postgresql+psycopg2://user:pass@/test?host=host1:port1&host=host2:port2&host=host3:port3")
>>> psycopg2.dialect().create_connect_args(u)
([], {'database': 'test', 'user': 'user', 'password': 'pass', 'host': 'host1:port1,host2:port2,host3:port3'})
```

we are not using libpq URLs, we are using the "host" argument passed to psycopg2.  


> @zzzeek do you know why the documentation what written that way?

because that is what we implemented.   the only issue w the docs is that we didn't put a ":port" on the other two example hosts, which leads to it being confusing, and also we didn't emphasize that users need to read the libpq docs **first** so they know about other parameters like `target_session_attrs` which are **not** required, this poster just happens to have a primary/replica setup as opposed to multiple replicas.

**Comment by zzzeek** [comment] 2022-08-01 13:39
@CaselIT please get me a psycopg2 connection example and I will fix the URL to send the arguments correctly.  the format is not changing because it is (correctly) documented.

**Comment by zzzeek** [comment] 2022-08-01 13:47
dupe of #4392

**Comment by CaselIT** [comment] 2022-08-01 13:49
> no, that would mean the feature is wrong. that is absolutely not what this was intended to look like. We would need to reopen #4392, declare this a dupe, and re-implement the feature correctly. the poster's syntax of `postgresql+psycopg2://<uname>:<pwd>@/<db_name>?&host=<host_1>:<port>&host=<host2>&port=<port_no>&target_session_attrs=primary` doesn't seem to make any sense at all (why put the "port" in two different ways? ) so that likely works by accident.

I agree, the version that worked for me is this:
```
'postgresql://scott:tiger@/test?host=localhost,localhost&port=5433,5432'
````
that looks reasonable enough to me.

> > Also re-reading the pg documentation, the part:
> > > In the connection URI format, you can list multiple host:port pairs separated by commas in the host of the URI.
> > > seems to refer to the host spec part of the url, not the host query parameter. That's not overly clear on their part
> 
> yes, that's what we implemented:

I think, and I may be wrong, that what we implemented is wrong, since the description is ambiguous. What they mean by 
> In the connection URI format, you can list multiple host:port pairs separated by commas in the host component of the URI.

is to imply that you can pass multiple host:port in place of the hostspec `postgresql://[userspec@][hostspec][/dbname][?paramspec]` part of the url, not in the `host` query parameter. 

> @CaselIT please get me a psycopg2 connection example and I will fix the URL to send the arguments correctly. the format is not changing because it is (correctly) documented.

it's definetely not working for me so I don't think it's correct

**Comment by CaselIT** [comment] 2022-08-01 13:52
The example you posted is not accepted by psyocph2
```
>>> from sqlalchemy.dialects.postgresql import psycopg2
>>> from sqlalchemy.engine import url
>>> u = url.make_url("postgresql+psycopg2://user:pass@/test?host=host1:port1&host=host2:port2&host=host3:port3")
>>> psycopg2.dialect().create_connect_args(u)
([], {'database': 'test', 'user': 'user', 'password': 'pass', 'host': 'host1:port1,host2:port2,host3:port3'})
```

This will error with something like
```
(psycopg2.OperationalError) could not translate host name "host1:port1" to address: Unknown host
could not translate host name "host2:port2" to address: Unknown host
could not translate host name "host3:port3" to address: Unknown host
```

**Comment by CaselIT** [comment] 2022-08-01 13:53
not sure if it's a windows thing or it's simply never worked (it seems strange we don't have any backed test for it though)

**Comment by CaselIT** [comment] 2022-08-01 15:00
> dupe of #4392

I guess it will be worked on in the original issue. Thanks for reporting @manmedia

**Closed by CaselIT** 2022-08-01 15:00 UTC
Labels: bug, duplicate, documentation, postgresql
