### ISSUE TITLE
Type Float inherits of type Numeric, even though doc indicates otherwise

### ISSUE THREAD

**Issue by janfrederik** [sqlalchemy/sqlalchemy#5252] opened 2020-04-12 17:02 UTC
The documentation of class Numeric says clearly "A type for fixed precision numbers, such as NUMERIC or DECIMAL." (https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Numeric)

However, `isinstance(myfloatcolumn.type, sqlalchemy.types.Numeric)` returns `True`.

The source code in sqlalchemy/sql/sqltype.py shows the reason: Float inherits directly from Numeric. Even though the documentation of both Numeric and Float seem to indicate otherwise.

Why is Float not a top-level data type?

**Comment by CaselIT** [comment] 2020-04-12 17:58
I think this is due to an implementation detail of sqlalchemy. `Float` is a top-level data type, but it shares most of the implementation with `Numeric`.

I guess a superclass of `Numeric` could be extracted so that `Float` is not a direct subclass of `Numeric`.

> Even though the documentation of both Numeric and Float seem to indicate otherwise.

The documentation list `Numeric` as the base for `Float`: https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Float

**Comment by zzzeek** [comment] 2020-04-12 22:22
it's probably possible for Float/Numeric to share a common mixin but not be subclasses of one another, but it might get tricky with weird cases like Oracle's NUMBER type is actually every type of number all at once based on the flags you give it.

this class relationship has had to be adjusted many times over the years so while I encourage folks to look into changing this relationship it might not be very easy to do.

**Comment by janfrederik** [comment] 2020-04-13 07:56
> > Even though the documentation of both Numeric and Float seem to indicate otherwise.
> 
> The documentation list `Numeric` as the base for `Float`: https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Float

I meant that the textual description (not the auto-generated text pulled from the class code) points in the direction that a Float is conceptually something else than a Numeric.

Now, to know if I have real Numeric/Decimal, I need to `isinstance(myfloatcolumn.type, sqlalchemy.types.Numeric) and not isinstance(myfloatcolumn.type, sqlalchemy.types.Float)`.

However, I am aware that changing the inheritance relationship could break other people's code...

**Comment by CaselIT** [comment] 2020-04-13 10:32
We could change how isinstance works for float, since python allows customizing it with `__subclasscheck__` and `__subclasshook__`, but it's probably clearer to use a common mixin.
Either way this could be a possible regression.

What is the use case in which you are using the isinstance check?

**Comment by zzzeek** [comment] 2020-04-13 14:24
I would not recommend changing the isinstance behavior of anything using hooks like that.     I'm not even aware of "subclasscheck" and that seems like it would lead to increased confusion when isinstance() is not honoring the `__mro__`.

one of the reasons Numeric / Float are together is that they both feature a flag that can return the value either as float or Decimal , it's just that this flag has the opposite default for each.     if you aren't changing this default you can distinguish between the two types as:

`isinstance(typ, Numeric) and typ.asdecimal
`
or 

```
import decimal
isinstance(typ.python_type, decimal.Decimal)
```

it is typical that a NUMERIC type you want to be setting the scale, and for example on Oracle setting the scale or not is in fact the only difference between numeric and float, so you may want to use:

`isinstance(typ, Numeric) and typ.scale is not None`

you can look at the visit name:

`typ.__visit_name__ == 'numeric'`

there's a lot of ways to go here though the original twin "isinstance()" check might be the most expedient.

to illustrate the current status of separating these types, a review will be posted next that has the whole thing working.  however, it required changes in a few of the dialects themselves too, which indicates that third party dialects would be hit by this also.   current "isinstance()" schemes that assume a certain relationship might be affected.  this doesn't mean we can't do this, but it could have a downstream impact.  right now 1.4 is set to be a really huge impact as it is, so I might want to hold off on this.

**Comment by sqla-tester** [comment] 2020-04-13 14:33
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Separate Numeric and Float** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1883

**Comment by CaselIT** [comment] 2020-04-13 14:48
> I would not recommend changing the isinstance behavior of anything using hooks like that. I'm not even aware of "subclasscheck" and that seems like it would lead to increased confusion when isinstance() is not honoring the __mro__.

Indeed I do not advise this, I just wanted to point out all the possibility.

Regarding the change, maybe an alternative could be to have new api that lets an user check if a particular type represents a specific sql type? Don't know something like
```py
def is_sql_type(sa_type, sql_type: str) -> bool:
    ...
```

So that it could be used as `is_sql_type(myfloatcolumn.type, 'numeric')` or `is_sql_type(myfloatcolumn.type, 'varchar')`, etc?
This would avoid relying on implementation details around the python types?

**Comment by CaselIT** [comment] 2020-04-13 14:52
maybe `represents_sql_type` is better as a name?

**Comment by zzzeek** [comment] 2020-04-13 14:58
I'm not ready to build a new type introspection system right now, that is not something we can just add on.   it would have to be well considered as far as what the use case for it is, etc., if it is truly much more superior than isinstance() or if it is just as likely to have this kind of problem.    Being able to distinguish for example between DECIMAL and REAL for example, when on some databases these are just synonyms for each other, other DBs one type or the other wont exist, etc. i dont know that there's really a "solution" here that isn't going to look idiosyncratic.

**Comment by CaselIT** [comment] 2020-04-13 15:46
Indeed it's not so simple considering all the backends and the various different implementations.

**Comment by janfrederik** [comment] 2020-04-15 17:55
Thanks for looking into this, guys!

@CaselIT You asked for my use case, so here it comes.
I export tables & views to Excel and want to apply a specific format to the Excel cells based on the data type in the DB. E.g. if it is a numeric(10, 2) field, I instruct Excel to always show 2 decimals. If it is a float or a numeric for which no scale is set, I choose the "General" cell format.
I think this challenge applies to anyone who wants to format output based on the sql data type, without having to resort to lookups in the information_schema. Because sqlalchemy is there as an abstraction layer, so I prefer to use sqlalchemy's Table and Column objects instead of resorting to db-specific code.

I'm aware that changing this could break a lot of existing user's code. So I'll resort to the double isinstance()-check, hoping that there will be no other non-numeric types that are a subclass of Numeric as well.

**Comment by zzzeek** [comment] 2022-02-11 15:27
> If it is a float or a numeric for which no scale is set, I choose the "General" cell format.

so you wouldn't need two "isinstance" checks, you would do, "if isinstance(typ, Numeric) and typ.scale is None".

I'm updating the patch for 2.0 but Im not sure if I want to push this one through as this will be backwards incompatible for:

* dialects that have types which extend Numeric, or Numeric dialect rules
* logic that does "isinstance(typ, Numeric) and scale is None" will miss all the Float types

considering 2.0 is a massive change already, this might be more of a 2.1 thing or even a wontfix, will leave it open

**Comment by sqla-tester** [comment] 2022-02-11 15:27
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Separate Numeric and Float** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3587

**Comment by zzzeek** [comment] 2022-04-14 13:48
I don't really see this architecture as changing.   as mentioned above, on some databases like Oracle, the difference between "float" and "numeric" is kind of spongy, and additionally the use case of "float or numeric" can sometimes be based on what Python type someone expects, which is also fluid between Numeric and Float.   it's true that on Oracle, even Integer is in the same NUMBER spectrum, but from a python perspective, integer is very different from numeric/float.

For 2.0 these datatypes are now pep-484 typed.  so for the use case of distinguishing between database types I think checking the "scale" parameter is the best way to do this.

**Comment by CaselIT** [comment] 2023-04-26 15:42
Turns out oracle has binary_float/binary_double that could be used for this

**Comment by zzzeek** [comment] 2024-11-19 14:34
> Turns out oracle has binary_float/binary_double that could be used for this

Reviewing, it looks like I had closed this as too risky / complicated / thorny, and it got reopened based on something that Oracle does.   

I dont understand what the proposal is.  Is it that code which currently uses `Numeric` or `Float`, when upgraded to SQLAlchemy 2.1, Oracle will suddenly use an entirely different datatype ?    I dont understand the rationale for that and it also seems like a giant backwards incompatibility.

can you expand upon what's being proposed here?     There's no reason we can't separate Numeric/Float and still use NUMBER in Oracle (as I said, Integer is already separate and that's also Oracle NUMBER)

**Comment by CaselIT** [comment] 2024-11-19 18:39
> I dont understand what the proposal is. Is it that code which currently uses `Numeric` or `Float`, when upgraded to SQLAlchemy 2.1, Oracle will suddenly use an entirely different datatype ? I dont understand the rationale for that and it also seems like a giant backwards incompatibility.

that would be https://github.com/sqlalchemy/sqlalchemy/issues/9704
as far as I know using float in oracle now requires `with_variant`, so it would keep working as it is with that change. If that's not the case then yea, it's a very big change that is likely best introduced first with a dialect flag that starts as it is now but warns kind of thing. If we want to do at all.

Note that in #9704 I wrote that that was required for this to be done, but maybe I was wrong and we can just do this change without changing the oracle behaviour at all

**Comment by zzzeek** [comment] 2024-11-19 19:15
I know it's #9704 but it doesnt really explain what the problem is or what the proposal is.

**Comment by CaselIT** [comment] 2024-11-19 19:18
I would think the proposal here is not having float inherit from numeric. Integer is not a numeric so I'm not sure why float should be

**Comment by CaselIT** [comment] 2024-11-19 19:29
oh sorry I though that was clear. wrote something over there

**Closed** 2024-12-09 21:48 UTC
Labels: bug, datatypes
