### ISSUE TITLE
MS SQL The server failed to resume the transaction.

### ISSUE THREAD

**Issue by GaniMarquez** [sqlalchemy/sqlalchemy#6073] opened 2021-03-17 05:27 UTC
**Describe the bug**
The mssql-pyodbc dialect fails to recognize the failure of the server to resume a transaction. (It doesn't expect the error-code "42000".)

**Expected behavior**
The result of a restart should be understood as an `is_disconnect`-error, e.g. to trigger a reconnect.

**To Reproduce**
```py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DXXXXXXXXX%3BUID%3DXX%3BPWD%3DXXXXXXXXX%3BAUTOTRANSLATE%3Dno",
    pool_size=30,
    max_overflow=0,
    pool_pre_ping=True,
    isolation_level="READ COMMITTED"
)
session_factory = sessionmaker(bind=engine)
session = session_factory()
session.execute('SELECT 1')  # this proves that everything was working OK
session.execute('SELECT 1')  # this yields the aforementioned error
```

**Error**

```
(Background on this error at: http://sqlalche.me/e/14/f405)Traceback (most recent call last):

  File "/opt/miniconda3/envs/idclassifier/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3043, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>>
  File "/opt/miniconda3/envs/idclassifier/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 302, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>
           │                └ <classmethod object at 0x7fdc005c8150>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/opt/miniconda3/envs/idclassifier/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 795, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
             │    │        │       │     └ <pyodbc.Connection object at 0x7fdc009cce30>
             │    │        │       └ <sqlalchemy.pool.base._ConnectionFairy object at 0x7fdc017f1350>
             │    │        └ <function DefaultDialect.do_ping at 0x7fdc01089f80>
             │    └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
             └ <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>
  File "/opt/miniconda3/envs/idclassifier/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 648, in do_ping
    cursor.execute(self._dialect_specific_select_one)
    │      │       │    └ 'SELECT 1'
    │      │       └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
    │      └ <method 'execute' of 'pyodbc.Cursor' objects>
    └ <pyodbc.Cursor object at 0x7fdc011c4030>

pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:42b00000004. (3971) (SQLExecDirectW)')

File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
return handle(*args_tuple)
        │       └ (<gevent._socket3.socket at 0x7fdc017c4520 object, fd=13, family=2, type=1, proto=0>, ('127.0.0.1', 52828))
        └ functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0x7fdc016f8ed0>>, <ge...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 139, in handle
super().handle(listener, client, addr)
                │         │       └ ('127.0.0.1', 52828)
                │         └ <gevent._socket3.socket at 0x7fdc017c4520 object, fd=13, family=2, type=1, proto=0>
                └ <gevent._socket3.socket at 0x7fdc003a82f0 object, fd=9, family=2, type=1, proto=0>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
self.handle_request(listener_name, req, client, addr)
│    │              │              │    │       └ ('127.0.0.1', 52828)
│    │              │              │    └ <gevent._socket3.socket at 0x7fdc017c4520 object, fd=13, family=2, type=1, proto=0>
│    │              │              └ <gunicorn.http.message.Request object at 0x7fdc01779950>
│    │              └ ('127.0.0.1', 8081)
│    └ <function GeventWorker.handle_request at 0x7fdc017c8170>
└ <gunicorn.workers.ggevent.GeventWorker object at 0x7fdc016f8ed0>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
super().handle_request(listener_name, req, sock, addr)
                        │              │    │     └ ('127.0.0.1', 52828)
                        │              │    └ <gevent._socket3.socket at 0x7fdc017c4520 object, fd=13, family=2, type=1, proto=0>
                        │              └ <gunicorn.http.message.Request object at 0x7fdc01779950>
                        └ ('127.0.0.1', 8081)
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
respiter = self.wsgi(environ, resp.start_response)
            │    │    │        │    └ <function Response.start_response at 0x7fdc017c09e0>
            │    │    │        └ <gunicorn.http.wsgi.Response object at 0x7fdc00a5c4d0>
            │    │    └ {'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fdbe00a7110>, 'wsgi.version': (1, 0), 'wsgi.multithread': ...
            │    └ <falcon.api.API object at 0x7fdc101fb690>
            └ <gunicorn.workers.ggevent.GeventWorker object at 0x7fdc016f8ed0>
> File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/falcon/api.py", line 269, in __call__
responder(req, resp, **params)
│         │    │       └ {}
│         │    └ <Response: 200 OK>
│         └ <Request: GET 'http://localhost:8081/healthcheck'>
└ <bound method HealthCheckHandler.on_get of <XXXXXXXXXX.handlers.healthcheck.HealthCheckHandler object at 0x7fdc016f8ad0>>

File "/Users/xn88xn/Documents/Work/XXXXXXXXXX/XXXXXXXXXX/handlers/healthcheck.py", line 15, in on_get
configs = self.get_configs_from_db()
            │    └ <function ConfigHandler.get_configs_from_db at 0x7fdc01169f80>
            └ <XXXXXXXXXX.handlers.healthcheck.HealthCheckHandler object at 0x7fdc016f8ad0>

File "/Users/xn88xn/Documents/Work/XXXXXXXXXX/XXXXXXXXXX/handlers/config.py", line 32, in get_configs_from_db
configs = transaction.session.query(Config).filter(and_(*filters)).all()
            │           │             │              │     └ [<sqlalchemy.sql.elements.BinaryExpression object at 0x7fdc01753c50>]
            │           │             │              └ <function and_ at 0x7fdbf01037a0>
            │           │             └ <class 'XXXXXXXXXX.models.config.Config'>
            │           └ None
            └ <sqlalchemy.orm.session.SessionTransaction object at 0x7fdc017c7a90>

File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2623, in all
return self._iter().all()
        │    └ <function Query._iter at 0x7fdc01500cb0>
        └ <sqlalchemy.orm.query.Query object at 0x7fdc017f1190>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2761, in _iter
execution_options={"_sa_orm_load_options": self.load_options},
                                            │    └ <class 'sqlalchemy.orm.context.QueryContext.default_load_options'>
                                            └ <sqlalchemy.orm.query.Query object at 0x7fdc017f1190>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1652, in execute
conn = self._connection_for_bind(bind, close_with_result=True)
        │    │                    └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
        │    └ <function Session._connection_for_bind at 0x7fdc01561e60>
        └ <sqlalchemy.orm.session.Session object at 0x7fdc017c7450>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1503, in _connection_for_bind
engine, execution_options
│       └ None
└ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 738, in _connection_for_bind
conn = bind.connect()
        │    └ <function Engine.connect at 0x7fdbe0291e60>
        └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2997, in connect
return self._connection_cls(self, close_with_result=close_with_result)
        │    │               │                       └ False
        │    │               └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
        │    └ <class 'sqlalchemy.engine.base.Connection'>
        └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 88, in __init__
else engine.raw_connection()
        │      └ <function Engine.raw_connection at 0x7fdbe02983b0>
        └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3076, in raw_connection
return self._wrap_pool_connect(self.pool.connect, _connection)
        │    │                  │    │             └ None
        │    │                  │    └ <property object at 0x7fdbe0294110>
        │    │                  └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
        │    └ <function Engine._wrap_pool_connect at 0x7fdbe0291ef0>
        └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3047, in _wrap_pool_connect
e, dialect, self
    │        └ Engine(mssql+pyodbc:///?odbc_connect=DRIVER%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BSERVER%3D127.0.0.1%2C1433%3BDATABASE%3DDA...
    └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1980, in _handle_dbapi_exception_noconnection
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
│                                    │                  └ ProgrammingError('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the tran...
│                                    └ (<class 'pyodbc.ProgrammingError'>, ProgrammingError('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]...
└ ProgrammingError("(pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The serv...
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
raise exception
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3043, in _wrap_pool_connect
return fn()
        └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 302, in connect
return _ConnectionFairy._checkout(self)
        │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>
        │                └ <classmethod object at 0x7fdc005c8150>
        └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 795, in _checkout
result = pool._dialect.do_ping(fairy.connection)
            │    │        │       │     └ <pyodbc.Connection object at 0x7fdc009cce30>
            │    │        │       └ <sqlalchemy.pool.base._ConnectionFairy object at 0x7fdc017f1350>
            │    │        └ <function DefaultDialect.do_ping at 0x7fdc01089f80>
            │    └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
            └ <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 648, in do_ping
cursor.execute(self._dialect_specific_select_one)
│      │       │    └ 'SELECT 1'
│      │       └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
│      └ <method 'execute' of 'pyodbc.Cursor' objects>
└ <pyodbc.Cursor object at 0x7fdc011c4030>

sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:42b00000004. (3971) (SQLExecDirectW)')
(Background on this error at: http://sqlalche.me/e/14/f405)

[2021-03-17 12:06:28.254] [ERROR   ] [XXXXXXXXXX.utils.error:error_handler:22] - Unhandled error while processing request: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:42b00000004. (3971) (SQLExecDirectW)')
(Background on this error at: http://sqlalche.me/e/14/f405)Traceback (most recent call last):

File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3043, in _wrap_pool_connect
return fn()
        └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 302, in connect
return _ConnectionFairy._checkout(self)
        │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>
        │                └ <classmethod object at 0x7fdc005c8150>
        └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 795, in _checkout
result = pool._dialect.do_ping(fairy.connection)
            │    │        │       │     └ <pyodbc.Connection object at 0x7fdc009cce30>
            │    │        │       └ <sqlalchemy.pool.base._ConnectionFairy object at 0x7fdc017f1350>
            │    │        └ <function DefaultDialect.do_ping at 0x7fdc01089f80>
            │    └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
            └ <sqlalchemy.pool.impl.QueuePool object at 0x7fdc10215c90>
File "/opt/miniconda3/envs/XXXXXXXXXX/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 648, in do_ping
cursor.execute(self._dialect_specific_select_one)
│      │       │    └ 'SELECT 1'
│      │       └ <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc object at 0x7fdc10215990>
│      └ <method 'execute' of 'pyodbc.Cursor' objects>
└ <pyodbc.Cursor object at 0x7fdc011c4030>

pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:42b00000004. (3971) (SQLExecDirectW)')
```

**Versions.**
 - OS: Mac OS 10.15.7
 - Python: 3.7.10
 - SQLAlchemy: 1.4.0b3
 - Database: Microsoft SQL Server 2017 (RTM-CU6) (KB4101464) - 14.0.3025.34 (X64)
 - DBAPI: PyODBC Version 4.0.30

**Additional context**
I followed the workaround seen [here](https://github.com/sqlalchemy/sqlalchemy/issues/5646) to whitelist the error code `42000` and it worked.

Is there another way to hopefully fix this issue?

Thanks!

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-03-17 18:35
that's quite a traceback.    this is a matter of us adding that code to the list of disconnect codes, so stick w/ hte woraroud for now and we'll try to get this in.

**Comment by gordthompson** [comment] 2021-03-17 18:53
FWIW, I am unable to reproduce this issue using several variations of the repro code. So far, regardless of how I "pull the rug out from under" the connection I've always gotten `08S01` which is already in the list of error codes:

https://github.com/sqlalchemy/sqlalchemy/blob/52cfec6434d9e0d164d823880ad8c8b8b3604077/lib/sqlalchemy/dialects/mssql/pyodbc.py#L480-L481

**Comment by GaniMarquez** [comment] 2021-03-18 02:28
Apologies for that but the reproduce steps that I presented was a simplified version of what was happening under the hood. It usually is an intermittent issue that I am experiencing wherein the error occurs erratically and not necessarily on the second request, but what I am sure of is that there is at least 1 successful transaction before I get this error:
```
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:42b00000004. (3971) (SQLExecDirectW)')
```
Not really sure if this is an isolated case catered to the SQL Server that we are using in development but using a custom dialect fixed my issue.

**Comment by zzzeek** [comment] 2021-03-18 02:33
are you using any less common transactional modes like two phase transactions ?

**Comment by GaniMarquez** [comment] 2021-03-18 02:38
@zzzeek No, I am not using any less common transactional mode like a two phase transaction.

**Comment by sqla-tester** [comment] 2021-03-18 16:45
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add error code 42000 to is_disconnect for mssql** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2648

**Comment by gordthompson** [comment] 2021-03-18 17:53
Okay, so the problem with this is that error code 42000 is not just used for 

> [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:42b00000004. (3971) (SQLExecDirectW)

It is also used for this

> [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 2 (""): The supplied value is not a valid instance of data type numeric. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecute)

which is causing a failure in this test:

https://github.com/sqlalchemy/sqlalchemy/blob/becf996e1d71b0778c1294fccc1b090b2f39a263/test/dialect/mssql/test_engine.py#L448

**Comment by zzzeek** [comment] 2021-03-18 21:53
OK then we have to add parsing of the message as well.  lots of other drivers have to do that.

**Comment by gordthompson** [comment] 2021-03-19 14:35
> OK then we have to add parsing of the message as well. lots of other drivers have to do that.

Done.

**Comment by sqla-tester** [comment] 2021-03-19 17:03
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add error code 42000 to is_disconnect() for mssql** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2658

**Comment by zzzeek** [comment] 2021-03-19 20:19
this error appears to be happening to other folks as well such as at https://github.com/mkleehammer/pyodbc/issues/736 and it's not clear to me that this is a "disconnect" error.   this is something going wrong with the connection. I looked at the list of error codes Gord posted at https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-a-odbc-error-codes?view=sql-server-ver15 and 42000 has nothing to do with the connection being unusable, it has to do with mis-use of the connection in some way.

Are you able to produce an ODBC trace file and attach it to https://github.com/mkleehammer/pyodbc/issues/736 ?

**Comment by zzzeek** [comment] 2021-03-25 14:30
Hi I just noticed you're using gevent.    that might be part of the problem here and that is very different from the test code above.   but overall we would need you to produce an [ODBC trace file](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) so that we can report this to pyodbc.    we're not able to reproduce this and the error in question does not indicate the connection is not usable.

**Comment by GaniMarquez** [comment] 2021-04-05 01:51
Hi All, 

Apologies for the late reply. I was on vacation and I'm just catching up with everything today. Thank you again for all your help so far. I'll update you once I get the chance to test out your suggestions. 👍

**Closed** 2021-08-07 05:29 UTC
Labels: SQL Server, external driver issues, awaiting info
