### ISSUE TITLE
Table modifiers in FROM clause

### ISSUE THREAD

**Issue by Myles1** [sqlalchemy/sqlalchemy#6235] opened 2021-04-09 20:02 UTC
**Is your feature request related to a problem? Please describe.**
I'm having trouble getting some db-specific functionality to work.
Snowflake has a ["time travel" feature](https://docs.snowflake.com/en/user-guide/data-time-travel.html) that uses the syntax `select ... from my_table before(timestamp => my_timestamp)`
I'm not sure of a way to get that to work in sqlalchemy without needing to go back to just using a text object.

**Describe the solution you'd like**
It would be great to have a way to modify the target table in the select clause (even just with text elements)

**Describe alternatives you've considered**
I tried using `FromClause`, `text`, `TextAsFrom`, etc.. 
The closest I got was 
```
Query([MyTable.my_col]).select_from(
  MyTable,
  func.before("timestamp => current_timestamp()"))
)
```
which adds in an extra comma to the output sql string since I'm giving it two targets:
`... from foo, before(...)`

I'm sure there's something I'm missing but I wasn't able to get it to work.

**Thank you for your time :)**

**Comment by CaselIT** [comment] 2021-04-09 21:55
Hi,

I'm not sure if this is possible, cc @zzzeek 
As a workaround you can always use `text` like so: `select_from(sa.text('my_table before(timestamp => my_timestamp)'))`

**Comment by sqla-tester** [comment] 2021-04-10 01:45
Replying by email, you can probably use .with_hint() to add elements on a per table basis.  There's a recent issue for a similar thing involving mssql temporal queries.

**Comment by zzzeek** [comment] 2021-04-10 15:22
OK so the snowflake dialect would need to support "hint" in their compiler, and then you would do something like this:

```
from sqlalchemy import table, column, select


t = table('my_table', column('q'))

stmt = select(t).with_hint(t, "AT(TIMESTAMP => 'Mon, 01 May 2015 16:20:00 -0700'::timestamp)")
print(stmt)

```

the default "stringify" shows this as:

```
SELECT my_table.q 
FROM my_table [AT(TIMESTAMP => 'Mon, 01 May 2015 16:20:00 -0700'::timestamp)]

```

but the snowflake dialect needs to support the "hint text" concept, since different backends render "table hints" in different ways.

current thinking on improving this is in #4797 (which has some recipes that might be helpful) and #6040

**Comment by zzzeek** [comment] 2021-05-14 13:06
for now this is mostly a dupe of #4797.

**Closed by zzzeek** 2021-05-14 13:06 UTC
Labels: external driver issues, question, temporal table modifiers
