### ISSUE TITLE
Cannot be processed due to @declared_attr.cascading; skipping

### ISSUE THREAD

**Issue by mmcloud** [sqlalchemy/sqlalchemy#5792] opened 2020-12-21 16:27 UTC
I am using mixin to abstract away the polymorphic properties. While the code works I'm getting the following warning. What is going on? 

**Warning**
```
SAWarning: Attribute 'id' on class <class 'app.models.account.Account'> cannot be processed due to @declared_attr.cascading; skipping
backend_1       |   "skipping" % (name, cls)
```

**Example**
```python
import enum
from sqlalchemy.ext.declarative import  declared_attr, has_inherited_table
from sqlalchemy import Column, Enum, ForeignKey, Integer


class AccountEnum(str, enum.Enum):
    lender = "lender"
    borrower = "borrower"
    broker = "broker"

class HasAccountIdMixin(object):

    account_type = Column(Enum(AccountEnum))

    @declared_attr.cascading
    def id(cls):
        if has_inherited_table(cls):
            return Column(ForeignKey('account.id'), primary_key=True)
        else:
            return Column(Integer, primary_key=True)
    
    @declared_attr
    def __mapper_args__(cls):
        args = {
            "polymorphic_identity": cls.__name__.lower()
        }
        if not has_inherited_table(cls):
            args['polymorphic_on'] = cls.account_type
        return args


class Account(Base, HasAccountIdMixin):
    pass

class Borrower(Account):
    pass

class Lender(Account):
    pass

class Broker(Account):
    pass
```
**Complete stack trace**
```/usr/local/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py:308: SAWarning: Attribute 'id' on class <class 'app.models.account.Account'> cannot be processed due to @declared_attr.cascading; skipping```

**Versions**
 - OS: "ubuntu wsd"
 - Python: "3.7"
 - SQLAlchemy: "^1.3.16"
 - Database: "postgres"

**Comment by zzzeek** [comment] 2020-12-21 16:51
hey there -

your test case is incomplete, and if I try to complete it, no warning is reproduced.

Can you provide a fully runnable MCVE please.  Your test case, if I add missing symbols like Base, first produces:

`sqlalchemy.exc.InvalidRequestError: Class <class '__main__.Account'> does not have a __table__ or __tablename__ specified and does not inherit from an existing table-mapped class.
`

if I add a table:

```
class Account(Base, HasAccountIdMixin):
    __tablename__ = 'account'

```

then:

`sqlalchemy.exc.ArgumentError: Column 'id' on class <class '__main__.Borrower'> conflicts with existing column 'account.id'
`

OK so it looks like all subclasses need ``__tablename__``, if I add that, no error.  see below.

```
import enum

from sqlalchemy import Column
from sqlalchemy import Enum
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.declarative import has_inherited_table


Base = declarative_base()


class AccountEnum(str, enum.Enum):
    lender = "lender"
    borrower = "borrower"
    broker = "broker"


class HasAccountIdMixin(object):

    account_type = Column(Enum(AccountEnum))

    @declared_attr.cascading
    def id(cls):
        if has_inherited_table(cls):
            return Column(ForeignKey("account.id"), primary_key=True)
        else:
            return Column(Integer, primary_key=True)

    @declared_attr
    def __mapper_args__(cls):
        args = {"polymorphic_identity": cls.__name__.lower()}
        if not has_inherited_table(cls):
            args["polymorphic_on"] = cls.account_type
        return args


class Account(Base, HasAccountIdMixin):
    __tablename__ = 'account'


class Borrower(Account):
    __tablename__ = "borrower"


class Lender(Account):
    __tablename__ = "lender"


class Broker(Account):
    __tablename__ = "broker"


from sqlalchemy.orm import configure_mappers
configure_mappers()

```

**Comment by mmcloud** [comment] 2020-12-21 17:09
Hi Mike,

Thank you for looking at this for me. Here it is with the base class, it contains both the id and table name. Perhaps this is the reason for the raise. Here should be the fully running MCVE.

```python
from typing import Any
from sqlalchemy.ext.declarative import as_declarative, declared_attr, has_inherited_table
from sqlalchemy import Column, Integer, ForeignKey, Integer, Enum
import re
import enum


@as_declarative()
class Base(object):    
    id = Column(Integer, primary_key=True)
    @declared_attr
    def __tablename__(cls) -> str:
        name = cls.__name__
        return ( 
            name[0].lower() + 
            re.sub(r'([A-Z])', lambda m: "_" + m.group(0).lower(), name[1:])
        )

class AccountEnum(str, enum.Enum):
    lender = "lender"
    borrower = "borrower"
    broker = "broker"

class HasAccountIdMixin(object):

    account_type = Column(Enum(AccountEnum))

    @declared_attr.cascading
    def id(cls):
        if has_inherited_table(cls):
            return Column(ForeignKey('account.id'), primary_key=True)
        else:
            return Column(Integer, primary_key=True)
    
    @declared_attr
    def __mapper_args__(cls):
        args = {
            "polymorphic_identity": cls.__name__.lower()
        }
        if not has_inherited_table(cls):
            args['polymorphic_on'] = cls.account_type
        return args


class Account(Base, HasAccountIdMixin):
    pass

class Borrower(Account):
    pass

class Lender(Account):
    pass

class Broker(Account):
    pass
```

**Comment by zzzeek** [comment] 2020-12-22 00:10
the account class is defined as:
```

class Account(Base, HasAccountIdMixin):
    pass
```


if we look to Account based on Python method resolution order what the normal identity of the "id" attribute would be, it's the Base.id column, because Base comes before HasAccountIdMixin in your MRO.  Under normal Python rules, Account.id would not make use of HasAccountIdMixin.id at all.

However, HasAccountIdMixin.id makes use of the special directive "declared_attr.cascading", which indicates that this attribute should be applied to all subclasses unconditionally.  The operation for the cascading attr comes across the "Base.id" attribute and is replacing it.   As this is not normal Python behavior and declarative is making an assumption that "cascading" should replace this down-inheriting attribute, it's emitting a warning to that effect.

The warning can be resolved by reversing the MRO for Account:

```
class Account(HasAccountIdMixin, Base):
    pass

```

the docs at https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html use "(Mixin, Base)" for most if not all of the examples, however there's no strongly marked box that would indicate that this is important, other than the paragraph "There’s no fixed convention over whether MyMixin precedes Base or not. Normal Python method resolution rules apply, and the above example would work just as well with:".    Which is accurate, one can do whatever they want, however, it makes more sense that a mixin would be in the MRO *before* the base so perhaps this should be indicated more strongly.

**Comment by mmcloud** [comment] 2020-12-27 15:08
Thank you, this fix works and makes a lot of sense!

**Closed** 2020-12-27 15:07 UTC
Labels: question
