### ISSUE TITLE
Postgres drop_all error with same sequence as server_default on two tables

### ISSUE THREAD

**Issue by dbluestein** [sqlalchemy/sqlalchemy#6071] opened 2021-03-17 04:18 UTC
Hi, first of all, thank you for all your great work on this library, we get a lot of mileage out of it.

**Describe the bug**
When using one sequence as the server_default value on columns on two different tables, issuing a drop_all fails with psycopg2.errors.DependentObjectsStillExist error.

**Expected behavior**
All objects in metadata should be dropped from the database.

**To Reproduce**

```py
from sqlalchemy import create_engine, Sequence, Column, Table, Integer, MetaData

metadata = MetaData()

common_seq = Sequence('common_sequence', metadata=metadata)

t1 = Table(
    'table_1', metadata,
    Column(
        'id',
        Integer,
        common_seq,
        server_default=common_seq.next_value(),
        primary_key=True
    )
)

t2 = Table(
    'table_2', metadata,
    Column(
        'id',
        Integer,
        common_seq,
        server_default=common_seq.next_value(),
        primary_key=True
    )
)

engine = create_engine('postgresql://test@/test')

metadata.create_all(engine)
metadata.drop_all(engine)
# sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop sequence common_sequence because other objects depend on it

```

**Error**

```
Traceback (most recent call last):
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop sequence common_sequence because other objects depend on it
DETAIL:  default value for column id of table table_1 depends on sequence common_sequence
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dblue/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/dblue/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/dblue/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/src/example.py", line 32, in <module>
    metadata.drop_all(engine)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/schema.py", line 4770, in drop_all
    bind._run_ddl_visitor(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2980, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 1020, in visit_metadata
    self.traverse_single(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 1097, in visit_table
    self.traverse_single(column.default)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 1116, in visit_sequence
    self.connection.execute(DropSequence(sequence))
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1290, in _execute_ddl
    ret = self._execute_context(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/dblue/Documents/sqla_drop_all_sequence/sqlalchemy/lib/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop sequence common_sequence because other objects depend on it
DETAIL:  default value for column id of table table_1 depends on sequence common_sequence
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: DROP SEQUENCE common_sequence]
```

**Versions.**
 - OS: Mac High Sierra
 - Python: 3.9.0
 - SQLAlchemy: 1.4.1
 - Database: Postgres 12.6 (on Ubuntu 20.04)
 - DBAPI: psycopg2 2.8.6

**Comment by zzzeek** [comment] 2021-03-17 14:05
hi -

I don't have an immediate fix for this right now and I'm hoping you can work around it, perhaps by making two separate Sequence() objects with the same name, not sure.

as we've just released SQLAlchemy 1.4.0 i have to prioritize some regressions that have to go out ASAP.      

will leave this in triaged as while I have a bit of an idea why this happens, it might need a bit of a rethink to fix.

@CaselIT feel free to check this out, the magic here would be happening in ddl.py.

**Comment by CaselIT** [comment] 2021-03-17 15:35
I would guess that the issue is in the order of the items to be removed.
I guess that a simple fix could be to move all sequence drop operations to the end.

**Comment by CaselIT** [comment] 2021-03-18 22:11
>  I guess that a simple fix could be to move all sequence drop operations to the end.

interesting, it seems to already be like this

**Comment by dbluestein** [comment] 2021-03-18 22:34
Thanks for investigating this. It seems that as part of dropping any individual table, associated sequences are also dropped:

From SchemaDropper.visit_table():

```py
        self.connection.execute(DropTable(table))

        # traverse client side defaults which may refer to server-side
        # sequences. noting that some of these client side defaults may also be
        # set up as server side defaults (see http://docs.sqlalchemy.org/en/
        # latest/core/defaults.html#associating-a-sequence-as-the-server-side-
        # default), so have to be dropped after the table is dropped.
        for column in table.columns:
            if column.default is not None:
                self.traverse_single(column.default)
```

So in this step, is it possible to inspect sequences to see if any other tables depend on them, and skip dropping them if so?

That said, we can definitely work around this, so there's no rush for a fix here. (Looking over the 1.4/2.0 migration docs I can see you've all been busy and your hard work is much appreciated).

**Comment by CaselIT** [comment] 2021-03-18 22:40
That's indeed the case, I've make it skip sequences that are in the metadata, so that they are dropped all at the end.

If a table is dropped by itself it will instead drop also the sequence.

Fix coming up. I think this can go in 1.3 since the fix is very small

**Comment by sqla-tester** [comment] 2021-03-18 22:44
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Allow dropping a schema with a sequence shared by more than one table.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2652

**Comment by sqla-tester** [comment] 2021-03-18 22:45
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Allow dropping a schema with a sequence shared by more than one table.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2653

**Closed** 2021-03-25 15:28 UTC
Labels: bug, schema
