### ISSUE TITLE
Support async dbapi for SQLite

### ISSUE THREAD

**Issue by satwell** [sqlalchemy/sqlalchemy#5920] opened 2021-02-04 17:39 UTC
**Describe the bug**
Trying to use an AsyncEngine with SQLite raises an AwaitRequired exception.  I don't see anything specifically about async support in the SQLite dialect docs, but SQLite did work with async in 1.4.0b1.

**Expected behavior**
For `create_async_engine("sqlite:///:memory:")` to provide a usable `AsyncEngine`.

**To Reproduce**
This code runs fine with 1.4.0b1 but fails with 1.4.0b2:
```py
import asyncio
import sqlalchemy
from sqlalchemy.ext.asyncio import create_async_engine

metadata = sqlalchemy.MetaData()
vals = sqlalchemy.Table(
    "vals",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
)

async def main():
    engine = create_async_engine("sqlite:///:memory:")
    async with engine.begin() as conn:
        await conn.run_sync(metadata.create_all)
        res = await conn.execute(vals.insert().values())
        print(res.inserted_primary_key)

if __name__ == "__main__":
    asyncio.run(main())
```

**Error**

```
Traceback (most recent call last):
  File "/tmp/asynctest.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/asynctest.py", line 18, in main
    res = await conn.execute(vals.insert().values())
  File "/tmp/asynctest/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 404, in execute
    result = await greenlet_spawn(
  File "/tmp/asynctest/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    raise exc.AwaitRequired(
sqlalchemy.exc.AwaitRequired: The current operation required an async execution but none was detected. This will usually happen when using a non compatible DBAPI driver. Please ensure that an async DBAPI is used. (Background on this error at: http://sqlalche.me/e/14/xd1r)
```

**Versions.**
 - OS:  Linux, Debian Bullseye
 - Python:  3.9.1
 - SQLAlchemy:  1.4.0b2
 - Database:  SQLite
 - DBAPI:  pysqlite

**Comment by CaselIT** [comment] 2021-02-04 17:48
hi,

This is by design, b1 allowed using the async interface also with not async dbapi, blocking the event loop for each io request

> This code runs fine with 1.4.0b1 but fails with 1.4.0b2:

That was actually a bug in b1, meaning that the code would work, but the event loop would be blocked by each query, much like using `time.sleep` would.

That error is meant to make people aware of this instead of silently doing the wrong thing.

**Comment by satwell** [comment] 2021-02-04 18:02
Thanks for the quick reply!  I suspected that might be the case.

Are there plans to add async support for SQLite, e.g., with [aiosqlite](https://github.com/omnilib/aiosqlite/tree/main/aiosqlite)?  (Which, IIRC, wraps `sqlite3` in a separate thread.)

Would it be feasible to make `create_async_engine` fail if the dbapi doesn't have async support?  Rather than wait until trying to use the engine?  That might make things a little clearer.

**Comment by CaselIT** [comment] 2021-02-04 18:39
The problem is that `create_async_engine` (and the normal `create_engine`) is lazy, that is it does not perform any query until it's first used, so it would need to know if a dbapi supports async or not. I'm not sure it it's feasible @zzzeek

**Comment by zzzeek** [comment] 2021-02-04 18:52
dont we have a flag on the dialect now for async?

**Comment by CaselIT** [comment] 2021-02-04 18:57
it seems so. I forgot

https://github.com/sqlalchemy/sqlalchemy/blob/9660e94e35be438b0d51cd87e6ccb4047a332c15/lib/sqlalchemy/dialects/postgresql/asyncpg.py#L874

**Comment by CaselIT** [comment] 2021-02-06 11:13
I've opened https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2537 to add the detection on engine creation.

**Comment by sqla-tester** [comment] 2021-02-06 14:17
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Try adding support for aiosqlite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2538

**Comment by zzzeek** [comment] 2021-02-06 14:40
if aiosqlite is using a thread I'm a little non-optimistic it can handle a lot of requests but let's see!

**Comment by CaselIT** [comment] 2021-02-06 14:49
It does seem to be using a thread pool of some sort

**Comment by zzzeek** [comment] 2021-02-06 14:50
i just added some of the tox elements but --dbdriver is still not working, it needs provisioning.py to be updated

**Comment by solarjoe** [comment] 2021-03-05 08:21
[Databases](https://github.com/encode/databases) states they are using [aiosqlite](https://github.com/omnilib/aiosqlite), at least to wrap support for SQLAlchemy Core.

**Comment by michael0liver** [comment] 2021-03-05 09:52
I think first class support for an async SQLite driver would be very useful. I have a fully async web application that occasionally needs to access a SQLite database. I have opted to use [asyncio.loop.run_in_executor ](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).
This [cookiecutter-aiohttp-sqlalchemy](https://github.com/aalhour/cookiecutter-aiohttp-sqlalchemy/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/database.py) repository was a good resource.

SQLAlchemy has good [documentation on sqlite threading-pooling-behavior](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#threading-pooling-behavior), if an async SQLite driver isn't feasible then I think examples or recipes of calling sync SQLAlchemy code (specifically for SQLite) safely from an async context would be a great resource to have.

**Comment by CaselIT** [comment] 2021-03-07 17:54
The wip in gerrit more or less works, but has some problems in the tests that I was not able to solve.
IIRC it seemed to leak connections what are not closed leading to the interpreter not closing, but I'm not sure if it's the sqlalchemy test suite fault and aiosqlite is simpy very sensitive to it, the integration code or aiosqlit.
I'll try to look again into it

**Closed** 2021-03-24 16:52 UTC
Labels: asyncio, sqlite
