### ISSUE TITLE
The postgres database reports an error when using the sqlalchemy reflect method

### ISSUE THREAD

**Issue by lj-1998** [sqlalchemy/sqlalchemy#10275] opened 2023-08-23 02:21 UTC
### Describe the bug

When the sqlalchemy reflect method is used in the postgres database, an error is reported when the parent tape associated with an external key has a "()"

### SQLAlchemy Version in Use

1.4.27

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL13

### Python Version

3.8

### Operating system

windows

### To Reproduce

```python
condef is FOREIGN KEY (id) REFERENCES "(2)"(id)
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` sqlalchemy.exc.NoSuchTableError

### Additional context

In this case, the get_foreign_keys method fails to obtain the regular match of foreign keys

**Comment by CaselIT** [comment] 2023-08-23 05:48
Hi,
It's not very clear how to reproduce..
You have a table called `(2)`?

**Comment by CaselIT** [comment] 2023-08-23 05:50
Also can you try in the last 1.4 release?

**Comment by lj-1998** [comment] 2023-08-23 06:52
> Hi, It's not very clear how to reproduce.. You have a table called `(2)`?

Yeah, he's tied to another off-table key
![screen_shot_1692604640377](https://github.com/sqlalchemy/sqlalchemy/assets/129364991/d751c98a-69eb-4d82-a618-8e1c65a57b59)

**Comment by lj-1998** [comment] 2023-08-23 06:55
> 



> Also can you try in the last 1.4 release?

I had the same problem with 1.4.49

**Comment by CaselIT** [comment] 2023-08-23 06:58
so the issue is the name of the table.

**Comment by lj-1998** [comment] 2023-08-23 07:03
> so the issue is the name of the table.

yes

**Comment by zzzeek** [comment] 2023-09-12 14:28
it really is just PG and just this expression, a lot of other weird names work on all backends

here's the bug

```
> /mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py(4157)get_multi_foreign_keys()
-> m = re.search(FK_REGEX, condef).groups()
(Pdb) condef
'FOREIGN KEY (ref) REFERENCES "(2)"(id)'
(Pdb) re.search(FK_REGEX, condef).groups()
('ref', None, '"', '2', None, None, None, None, None, None, None, None, None)

```

**Comment by sqla-tester** [comment] 2023-09-12 15:10
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**parse for parenthesis in referenced tablename, columnname** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4883

**Closed** 2023-09-18 20:15 UTC
Labels: bug, postgresql, mysql, sqlite, reflection
