### ISSUE TITLE
attributekeyeddict does not serialize the collectionadapter

### ISSUE THREAD

**Issue by cschroeer** [sqlalchemy/sqlalchemy#10175] opened 2023-08-02 06:01 UTC
### Describe the bug

Hello, 

I am facing an unexpected error while accessing a mapped dict field in multiprocessing context. 
The dict-field is not set when accessing. 

For example

```
class Parent:

    id: str
    childs_dict: Optional[dict[str, ChildDict]] = field(
        default_factory=dict, init=False
    )
```

The dict field is mapped with 
```
collection_class=attribute_keyed_dict("id")
```

In a multiprocess-Process, the field is accessed with the following to set a new value: 
```
parent.childs_dict = {
                id: ChildDict(id=id, attribute=f"child_dict {id}")
            }
```

At this point, the following error arises (see also StackTrace): 
TypeError: 'NoneType' object is not iterable

Thanks for your investigation!

Best

### SQLAlchemy Version in Use

2.0.19

### DBAPI (i.e. the database driver)

postgresql+psycopg

### Database Vendor and Major Version

PostgreSQL 12.15

### Python Version

3.10

### Operating system

Ubuntu

### To Reproduce

```python
from dataclasses import dataclass, field
from typing import  Optional
import multiprocessing
from sqlalchemy import Engine, select
from sqlalchemy.orm import Session, joinedload, selectinload
from sqlalchemy import URL
from sqlalchemy import (
    Column,
    Engine,
    ForeignKey,
    MetaData,
    String,
    Table,
    create_engine,
    inspection,
)
from sqlalchemy.orm import (
    attribute_keyed_dict,
    registry,
    relationship,
)
from sqlalchemy.schema import CreateSchema, DropSchema

#######################################
# Models
@dataclass
class ChildDict:
    id: str
    attribute: str

@dataclass
class ChildList:
    id: str
    attribute: str
   
@dataclass
class Child:
    id: str
    attribute: str
   

@dataclass
class Parent:

    id: str
    childs_dict: Optional[dict[str, ChildDict]] = field(
        default_factory=dict, init=False
    )
    childs_list: Optional[list[ChildList]] = field(
        default_factory=list, init=False
    )
    child: Optional[Child] = field(
        default=None, init=False
    )


#######################################
# Database

schema = "behaviour_dict_loader"
driver = "postgresql+psycopg"
username = ""
password = ""
host = ""
port = 5432
database = ""

engine: Engine = create_engine(URL.create(driver, username, password, host, port, database), echo=False)
metadata = MetaData(schema=schema)
mapper_registry: registry = registry(metadata=metadata)

if not inspection.inspect(ChildDict, False):
    child_dict_table: Table = Table(
        "child_dict",
        mapper_registry.metadata,
        Column("id", String, primary_key=True),
        Column("attribute", String),
        Column(
            "parent_id",
            String,
            ForeignKey("parent.id", ondelete="CASCADE"),
        )
    )

    mapper_registry.map_imperatively(
        ChildDict,
        child_dict_table,
    )

if not inspection.inspect(ChildList, False):
    child_list_table: Table = Table(
        "child_list",
        mapper_registry.metadata,
        Column("id", String, primary_key=True),
        Column("attribute", String),
        Column(
            "parent_id",
            String,
            ForeignKey("parent.id", ondelete="CASCADE"),
        )
    )

    mapper_registry.map_imperatively(
        ChildList,
        child_list_table,
    )

if not inspection.inspect(Child, False):
    child_table: Table = Table(
        "child",
        mapper_registry.metadata,
        Column("id", String, primary_key=True),
        Column("attribute", String),
        Column(
            "parent_id",
            String,
            ForeignKey("parent.id", ondelete="CASCADE"),
        )
    )

    mapper_registry.map_imperatively(
        Child,
        child_table,
    )


if not inspection.inspect(Parent, False):
    parent_table: Table = Table(
        "parent",
        mapper_registry.metadata,
        Column("id", String, primary_key=True),
    )

    mapper_registry.map_imperatively(
        Parent,
        parent_table,
        properties={
            "childs_dict": relationship(
                ChildDict,
                collection_class=attribute_keyed_dict("id"),
                cascade="all, delete",
                passive_deletes=True,
            ),
            "childs_list": relationship(
                ChildList,
                cascade="all, delete",
                passive_deletes=True,
            ),
            "child": relationship(
                Child,
                uselist=False,
                cascade="all, delete",
                passive_deletes=True,
            ),
        },
    )

#######################################
# Processing

def parent_select_without_joins(session_datenschmiedeai_dev):
    """
    Lead to sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Parent at 0x7fc10642d9c0> is not bound to a Session; lazy load operation of attribute 'childs_dict' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
    """
    stmt = (
        select(Parent)
        .limit(10)
        .execution_options(stream_results=True, max_row_buffer=5)
    )
    return session_datenschmiedeai_dev.scalars(stmt)

def parent_select(session_datenschmiedeai_dev):
    """
    Lead to TypeError: 'NoneType' object is not iterable while accessing childs_dict in multiprocessing
    """
    stmt = (
        select(Parent)
        .limit(10)
        .options(
            selectinload(
                Parent.childs_list
            ) ,
            selectinload(
                Parent.childs_dict
            ) ,
            joinedload(
                Parent.child
            ), 
        )
        .execution_options(stream_results=True, max_row_buffer=5)
    )
    return session_datenschmiedeai_dev.scalars(stmt)

def do_sublist_for_multiprocessing(parents_sublist: list[Parent]):
    print("do_sublist")
    with Session(engine) as session_save:
        parent_insert = []
        for parent in parents_sublist:
            print(parent)
            # here no error arises
            #parent.child = Child(id=id, attribute=f"child {id}")

            # here no error arises
            parent.childs_list = [ChildList(id=parent.id, attribute=f"child_list {id}")]

            # Here the error arises
            parent.childs_dict = {
                id: ChildDict(id=id, attribute=f"child_dict {id}")
            }
            
            parent_insert.append(parent)

        session_save.add_all(parent_insert)
        session_save.commit()


def do_multiprocessing(multiprocessing_cpu_count = 2):

    print("start do_multiprocessing")
    with Session(engine) as session_select:

        # parent_select
        # parent_select_without_joins
        parent_stmt = parent_select(
            session_select
        )

        # mulitprocesing :
        pool = multiprocessing.Pool(multiprocessing_cpu_count)
        entities_results = pool.map(do_sublist_for_multiprocessing, parent_stmt.partitions())
        pool.close()
        pool.join()

        print(f"{entities_results=}")


def do_sequentially():

    with Session(engine) as session:

        parent_stmt = parent_select(
            session
        )

        for parent_partition in parent_stmt.partitions():
            for parent in parent_partition:
                print(parent)
                # here no error arises
                parent.childs_dict = {
                    id: ChildDict(id=id, attribute=f"child_dict {id}")
                }
                

def do(multiprocessing_cpu_count = 2):

    #do_sequentially()
    do_multiprocessing(multiprocessing_cpu_count)


def insert_parents_without_childs(id="1"):
    parent = Parent(id)
    with Session(engine) as session:
        session.add(parent)
        session.commit()

with engine.connect() as connection:
    if not inspection.inspect(connection).has_schema(
        schema
    ):
        connection.execute(CreateSchema(schema))
        connection.commit()

metadata.create_all(engine)

# insert data, runs only once
for id in range(10):
    insert_parents_without_childs(str(id))

# here the error arises
do(2)
```

### Error

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/cschroeer/python-projects/minimal-examples/behaviour_dict_loader.py", line 208, in do_sublist_for_multiprocessing
    parent.childs_dict = {
  File "/home/cschroeer/python-projects/minimal-examples/.venv-minimal-examples/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 536, in __set__
    self.impl.set(
  File "/home/cschroeer/python-projects/minimal-examples/.venv-minimal-examples/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1982, in set
    state._modified_event(dict_, self, old, True)
  File "/home/cschroeer/python-projects/minimal-examples/.venv-minimal-examples/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 885, in _modified_event
    previous = attr.copy(previous)
  File "/home/cschroeer/python-projects/minimal-examples/.venv-minimal-examples/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1674, in __copy
    return [y for y in collections.collection_adapter(item)]
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cschroeer/python-projects/minimal-examples/behaviour_dict_loader.py", line 281, in <module>
    do(2)
  File "/home/cschroeer/python-projects/minimal-examples/behaviour_dict_loader.py", line 258, in do
    do_multiprocessing(multiprocessing_cpu_count)
  File "/home/cschroeer/python-projects/minimal-examples/behaviour_dict_loader.py", line 231, in do_multiprocessing
    entities_results = pool.map(do_sublist_for_multiprocessing, parent_stmt.partitions())
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: 'NoneType' object is not iterable
``` 

### Additional context

The other attributes within Parent-Class shows that the behavior does not happen while accessing not-dict fields.

**Comment by zzzeek** [comment] 2023-08-02 13:24
there's an issue with pickling that can be reproduced without multiprocessing, which is why there is something here to fix. 

however, your program's patterns are not safe and will continue to break without adjustment, since it is sending a live, unconsumed result object into multiple child processes.   The postgresql cursor can't be shared among processes safely.  it is additionally sharing the connection pool from the parent into the child process.

This would be a more correct way to do the result part:

```py
        partitions = [
            list(p) for p in parent_stmt.partitions()
        ]

        entities_results = pool.map(
            do_sublist_for_multiprocessing, partitions
        )

```

though in practice, I would not do this either, I'd do individual queries in each process.  that way the overhead of emitting the SQL and fetching ORM results (very CPU heavy) is also shuttled off to the processes and you can follow the [recommended, documented patterns for using multiprocessing](https://docs.sqlalchemy.org/en/20/core/pooling.html#pooling-multiprocessing)

additionally, you are sharing the engine over the process boundary, [which will break](https://docs.sqlalchemy.org/en/20/core/pooling.html#pooling-multiprocessing) without special steps, resetting the connection pool so that no postgresql connections are shared over the process boundary:

```py
def do_sublist_for_multiprocessing(parents_sublist: list[Parent]):
    print("do_sublist")
    engine.dispose(close=False)
    with Session(engine) as session_save:
       # ...
```

**Comment by zzzeek** [comment] 2023-08-02 14:23
ok the issue is in the keyfuncdict, need to check the others as well and add a new suite for this

```diff
diff --git a/lib/sqlalchemy/orm/mapped_collection.py b/lib/sqlalchemy/orm/mapped_collection.py
index fb6b05d78e..abf10de6ee 100644
--- a/lib/sqlalchemy/orm/mapped_collection.py
+++ b/lib/sqlalchemy/orm/mapped_collection.py
@@ -376,10 +376,11 @@ class KeyFuncDict(Dict[_KT, _VT]):
 
     @classmethod
     def _unreduce(
-        cls, keyfunc: _F, values: Dict[_KT, _KT]
+        cls, keyfunc: _F, values: Dict[_KT, _KT], adapter
     ) -> "KeyFuncDict[_KT, _KT]":
         mp: KeyFuncDict[_KT, _KT] = KeyFuncDict(keyfunc)
         mp.update(values)
+        mp._sa_adapter = adapter
         return mp
 
     def __reduce__(
@@ -388,7 +389,7 @@ class KeyFuncDict(Dict[_KT, _VT]):
         Callable[[_KT, _KT], KeyFuncDict[_KT, _KT]],
         Tuple[Any, Union[Dict[_KT, _KT], Dict[_KT, _KT]]],
     ]:
-        return (KeyFuncDict._unreduce, (self.keyfunc, dict(self)))
+        return (KeyFuncDict._unreduce, (self.keyfunc, dict(self), self._sa_adapter))
 
     @util.preload_module("sqlalchemy.orm.attributes")
     def _raise_for_unpopulated(

```

**Comment by sqla-tester** [comment] 2023-08-02 17:37
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure collection adapter is serialized** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4802

**Closed** 2023-08-03 14:13 UTC
Labels: bug, orm, near-term release
