### ISSUE TITLE
texualselect regressions due to change in how TextualSelect is treated in the compiler

### ISSUE THREAD

**Issue by cansjt** [sqlalchemy/sqlalchemy#7798] opened 2022-03-07 17:55 UTC
### Describe the bug

When compiling the `sqlalchemy.dialects.postgresql.Insert` statement with a `select_from(text("SELECT ..."))` (_cf._ MVCE below) and the `.on_conflict_do_update()` method to add the , the compilation fails with the error (_cf._ stacktrace below)

### Case 1

```python
from sqlalchemy import Column, Integer, MetaData, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect, Insert

meta = MetaData()
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )
s1 = text('SELECT bar.id, bar.attr FROM bar').columns(bar.c.id, bar.c.attr)
s2 = (Insert(bar)
      .from_select(list(s1.selected_columns), s1)
      .on_conflict_do_update(index_elements=[s1.selected_columns.id],
                             set_={'attr': s1.selected_columns.attr},
                             )
      )
print(s2)
print(str(pg_dialect.statement_compiler(pg_dialect(), s2)))
```

### Error

```
Traceback (most recent call last):
  File "/home/nicolas/src/gitco/jobteaser/jobflow-dags/bug-check.py", line 21, in <module>
    print(s2)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 562, in __str__
    return str(self.compile())
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3940, in visit_insert
    post_values_clause = self.process(
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2484, in visit_on_conflict_do_update
    cols = insert_statement.table.c
AttributeError: 'TextualSelect' object has no attribute 'table'
``` 

### Case 2

```py
from sqlalchemy import Column, insert, Integer, MetaData, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect
from sqlalchemy.dialects.mysql import dialect as mysql_dialect


meta = MetaData()
foo = Table('foo', meta, Column('id', Integer))
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )

s1 = text('SELECT id FROM foo').columns(foo.c.id)
s2 = (text('SELECT bar.id, bar.attr FROM bar WHERE br.id IN (SELECT id FROM baz)')
      .columns(bar.c.id, bar.c.attr)
      )
s3 = insert(bar).from_select(list(s2.selected_columns), s2)
s4 = s3.add_cte(s1.cte(name='baz'))

print(str(pg_dialect.statement_compiler(pg_dialect(), s4)))
print(str(mysql_dialect.statement_compiler(mysql_dialect(), s4)))
```

### Versions

- OS: Ubuntu/ Debian
- Python: 3.9.10
- SQLAlchemy: 1.4.32
- Database: postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2 2.9.3

### Additional context

The fix is pretty simple: instead of using `insert_statement.table.c` one has to use `insert_statement.selected_columns`. Though I guess this would require the addition of non-regression test for the future. Hopefully, one can be derived from the above example. 

I feel guilty as I am pretty sure those changes come from this issue #7760 I reported earlier. I didn't take the time to check the fix before the 1.4.32 release.

**Comment by zzzeek** [comment] 2022-03-07 18:13
yup we can pretty much assume #7760 is the cause of this

**Comment by cansjt** [comment] 2022-03-07 18:26
FYI I have another example that breaks in a slightly different place:
```
from sqlalchemy import __version__
from sqlalchemy import Column, Integer, MetaData, select, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect, Insert

print('SQLAlchemy v: {}'.format(__version__))
meta = MetaData()
foo = Table('foo', meta, Column('id', Integer))
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )
s1 = text('SELECT id FROM foo').columns(foo.c.id)
s2 = text('SELECT bar.id, bar.attr FROM bar').columns(bar.c.id, bar.c.attr)
s3 = s2.add_cte(s1.cte(name='baz'))
s4 = (Insert(bar)
      .from_select(list(s3.selected_columns), s3)
      .on_conflict_do_update(index_elements=[s3.selected_columns.id],
                             set_={'attr': s3.selected_columns.attr},
                             )
      )
print(s4)
print(str(pg_dialect.statement_compiler(pg_dialect(), s4)))
```
Will fail with the error:
```
Traceback (most recent call last):
  File "/home/nicolas/src/gitco/jobteaser/jobflow-dags/bug-check.py", line 24, in <module>
    print(s4)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 562, in __str__
    return str(self.compile())
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3940, in visit_insert
    post_values_clause = self.process(
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2516, in visit_on_conflict_do_update
    self.current_executable.table.name,
AttributeError: 'TextualSelect' object has no attribute 'table'
```
I indeed didn't check for other occurrences of access to the `.table` attribute in the `OnConflictDoUpdate` clause implementation. Also note that the above example is wrong: the correct version should refer to `s2` not `s3` in the `ON CONFLICT` clause. But still, the resulting error ain't that nice.

**Comment by zzzeek** [comment] 2022-03-07 21:13
can you confirm this fixes all tests, for the two above it fixes:

```py
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 6be8ae281f..7780d3782a 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -1664,6 +1664,8 @@ class SQLCompiler(Compiled):
             nesting_level = len(self.stack) if not toplevel else None
             text = self._render_cte_clause(nesting_level=nesting_level) + text
 
+        self.stack.pop(-1)
+
         return text
 
     def visit_null(self, expr, **kw):

```

**Comment by zzzeek** [comment] 2022-03-07 21:13
seems all good to me all three

**Comment by cansjt** [comment] 2022-03-08 08:16
Sorry, it was late at night here. Checking and reporting back.

**Comment by cansjt** [comment] 2022-03-08 08:25
Yes I can confirm that the above patch alone, fixes all our test cases. We had six broken over eleven, that involve variations of the above.

**Comment by zzzeek** [comment] 2022-03-08 14:51
too bad I forgot to pop from the stack :)    this will be in the next release.

**Comment by sqla-tester** [comment] 2022-03-08 18:41
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**pop the stack that we pushed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3660

**Comment by sqla-tester** [comment] 2022-03-08 18:41
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**pop the stack that we pushed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3661

**Closed** 2022-03-08 19:56 UTC
Labels: bug, easy, sql, regression

**Comment by cansjt** [comment] 2022-03-13 11:37
FYI, after removing the work around we needed because of #7760, I did manage to successfully run all our tests against the `rel_1_4` branch.

Thanks for the fix.
