### ISSUE TITLE
[BETA] Type of "mapped_column" is partially unknown

### ISSUE THREAD

**Issue by ramarivera** [sqlalchemy/sqlalchemy#8644] opened 2022-10-16 14:21 UTC
### Describe the bug

Issues with using `dataclass_transform` based Declarative mapping on Py `3.10.7`.
In this case, issues with mapped_column being partially undefined.

(note: at some point, it stopped being that error and instead was giving me an error about primary key not being a param, but couldn't repro anymore)

### To Reproduce

Full test case:

```python
# isort:skip
# pylint:disable = unused-import, too-few-public-methods, missing-class-docstring

# Inferred issues
#       Type of "mapped_column" is partially unknown
#       Type of "mapped_column" is "(__name_pos: str | Type[TypeEngine[Any]] | TypeEngine[Any] | SchemaEventTarget | None = None, __type_pos: Type[TypeEngine[Any]] | TypeEngine[Any] | SchemaEventTarget | None = None, *args: SchemaEventTarget, init: _NoArg | bool = _NoArg.NO_ARG, repr: _NoArg | bool = _NoArg.NO_ARG, default: Any | None = _NoArg.NO_ARG, default_factory: _NoArg | (() -> _T@mapped_column) = _NoArg.NO_ARG, kw_only: _NoArg | bool = _NoArg.NO_ARG, nullable: bool | Literal[SchemaConst.NULL_UNSPECIFIED] | None = SchemaConst.NULL_UNSPECIFIED, primary_key: bool | None = False, deferred: _NoArg | bool = _NoArg.NO_ARG, deferred_group: str | None = None, deferred_raiseload: bool = False, name: str | None = None, type_: Type[TypeEngine[Any]] | TypeEngine[Any] | None = None, autoincrement: bool | Literal['auto', 'ignore_fk'] = "auto", doc: str | None = None, key: str | None = None, index: bool | None = None, unique: bool | None = None, info: Dict[Any, Any] | None = None, onupdate: Any | None = None, insert_default: Any | None = _NoArg.NO_ARG, server_default: FetchedValue | str | TextClause | ColumnElement[Unknown] | None = None, server_onupdate: FetchedValue | None = None, quote: bool | None = None, system: bool = False, comment: str | None = None, **dialect_kwargs: Any) -> MappedColumn[Any]"
#       Pylance reportUnknownVariableType
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column

# Inferred issues
#   "dataclass_transform" is not accessed Pylance
from typing_extensions import dataclass_transform  # type: ignore


class BaseEntity(MappedAsDataclass, DeclarativeBase):
    id: Mapped[int] = mapped_column(init=False, primary_key=True)
    name: Mapped[str] = mapped_column(init=True)


# Inferred as by Intellisense:
#   (class) BaseEntity(name: SQLCoreOperations[str] | str)
# Inferred errors:
#   Argument missing for parameter "name" Pylance reportGeneralTypeIssues
BaseEntity()


# Inferred as by Intellisense:
#   (class) BaseEntity(name: SQLCoreOperations[str] | str)
#   non_existing: Unknown
# Inferred errors:
#   Argument missing for parameter "name" Pylance reportGeneralTypeIssues
#   No parameter named "non_existing" Pylance reportGeneralTypeIssues
BaseEntity(non_existing=42)


# Inferred as by Intellisense:
#   (class) BaseEntity(name: SQLCoreOperations[str] | str)
BaseEntity(name="Hello")
```

### Error

Errors + reports are included inline for easier reference

### Versions

- OS: Win 11
- Python: Python 3.10.7
- sqlalchemy = "2.0.0b1"
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

### Additional context

Related to Beta #8631

**Comment by ramarivera** [comment] 2022-10-16 14:24
Adding `@dataclass_transform()` to `BaseEntity` causes:

```python

# Inferred as by Intellisense:
#   (class) BaseEntity(name: SQLCoreOperations[str] | str)
# Inferred errors
#   No parameter named "name" Pylance reportGeneralTypeIssues
BaseEntity(name="Hello")
```

**Comment by zzzeek** [comment] 2022-10-16 14:37
hi -

can't reproduce any issue here using pylance.     See attached screenshot.




Please make sure you delete all stubs that are embedded in pylance's configuration.  I use this:

```
find  ~/.vscode/ ~/.npm/ -type d -path "*/stubs*sqlalchemy" -print -exec rm -fr {} \;
```

![Screenshot from 2022-10-16 10-36-31](https://user-images.githubusercontent.com/128223/196041507-7d3b0d63-e4fa-4493-85bd-d9e8a118fef1.png)

**Comment by ramarivera** [comment] 2022-10-16 14:47
Just to clarify, since I'm using windows: `~/.[vscode|npm]` means the caches from pylance are on my home folder (contrary to being like `.mypy_cache` which is in my repo folder, correct?

**Comment by ramarivera** [comment] 2022-10-16 15:03
Just tried, and now not only I have the same issue, but also one with the first example:


```python
# ==== BEFORE ======
# Inferred as by Intellisense:
#   (class) BaseEntity(name: SQLCoreOperations[str] | str)
# Inferred errors:
#   Argument missing for parameter "name" Pylance reportGeneralTypeIssues

# ===== NOW ======
# Inferred as by Intellisense:
#   (class) BaseEntity(id: SQLCoreOperations[int] | int = mapped_column(init=False, primary_key=True), name: SQLCoreOperations[str] | str = mapped_column(init=True))
BaseEntity()
```

**Comment by zzzeek** [comment] 2022-10-16 15:20
> Just to clarify, since I'm using windows: `~/.[vscode|npm]` means the caches from pylance are on my home folder (contrary to being like `.mypy_cache` which is in my repo folder, correct?

I think so.

maybe try right-clicking on "Mapped", and say "go to type definition".  see where it takes you

**Comment by ramarivera** [comment] 2022-10-16 15:58
> > Just to clarify, since I'm using windows: `~/.[vscode|npm]` means the caches from pylance are on my home folder (contrary to being like `.mypy_cache` which is in my repo folder, correct?
> 
> I think so.
> 
> maybe try right-clicking on "Mapped", and say "go to type definition". see where it takes you

`C:\Users\ramar\AppData\Local\pypoetry\Cache\virtualenvs\some-project-name-mBcAJQ45-py3.10\Lib\site-packages\sqlalchemy\orm\base.py`

**Comment by zzzeek** [comment] 2022-10-16 16:11
that's good, that's the right answer.

I dont know how these cases are going to be supported going forward because they are really vscode / pylance issues.  you can try getting help at https://github.com/microsoft/pylance-release .    I have your case working here with a separate venv and a straight install and it still works, though it *is* flaky in that the type information seems to go away sometimes, then comes back when I edit.      also you definitely need to be on a recent vscode version as the dataclass_transform stuff came in only within the last year.

**Comment by zzzeek** [comment] 2022-10-16 16:13
obvioulsy confirm the SQLAlchemy that's installed there is actually 2.0.  Try right-clicking on mapped_column and make sure it goes into those same .py files.

**Comment by ramarivera** [comment] 2022-10-16 17:01
> I have your case working here with a separate venv and a straight install and it still works, though it is flaky in that the type information seems to go away sometimes, then comes back when I edit.

Yeah, I noticed that too sometimes.

I confirmed already that I have the latest sqlalchemy by comparing the files, I updated VS Code all I could and even PyLance to prerelase

**Comment by ramarivera** [comment] 2022-10-16 21:25
See https://github.com/sqlalchemy/sqlalchemy/issues/8645#issuecomment-1280060672

At least, the mapped column issue is resolved :)

**Comment by CaselIT** [comment] 2022-10-16 21:39
I can actually reproduce. The issue seems to be due to to `_ServerDefaultType` and `_ServerDefaultType` has an issue since it uses `ColumnElement` without generic variable instead of `ColumnElement[Any]`

> Expected type arguments for generic class "ColumnElement"Pylance[reportMissingTypeArgument](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

**Comment by CaselIT** [comment] 2022-10-16 21:41
@zzzeek you need to add string or basic type support for pylance.
The default is `"python.analysis.typeCheckingMode": "off",`. Setting it "basic" or "strict" will reveal the issue

**Comment by zzzeek** [comment] 2022-10-16 22:23
I have it set to `"python.analysis.typeCheckingMode": "basic"` already.  is it possible this is a windows issue?

**Comment by zzzeek** [comment] 2022-10-16 22:24
If I set it to strict, then I get the "mapped_column is partially unknown" issue.  However the rest of the script remains fine.

**Comment by sqla-tester** [comment] 2022-10-16 22:35
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**repair type qualify in _ServerDefaultType; other pyright tweaks** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4131

**Closed** 2022-10-17 12:59 UTC
Labels: bug, typing, next release, orm - annotated declarative
