### ISSUE TITLE
AliasedClass object gets GC'ed leading to failure of wp subclass resolution if not strongly referenced outside of query

### ISSUE THREAD

**Issue by maparent** [sqlalchemy/sqlalchemy#6680] opened 2021-06-26 19:42 UTC
**Describe the bug**
 
Regression on SQLAlchemy 1.4.x:
A simple query using an explicit with_polymorphic fails.

**To Reproduce**

```py
from sqlalchemy import Column, Integer, String, ForeignKey, create_engine
from sqlalchemy.orm import declarative_base, with_polymorphic, sessionmaker

engine = create_engine('sqlite:///:memory:', echo=True)

Base = declarative_base()

class A(Base):
  __tablename__ = 'a'
  id = Column(Integer, primary_key=True)
  poly = Column(String)
  __mapper_args__ = {
      'polymorphic_identity': 'A',
      'polymorphic_on': poly
  }


class B(A):
  __tablename__ = 'b'
  id = Column(
      Integer,
      ForeignKey(A.id),
      primary_key=True
  )
  __mapper_args__ = {
      'polymorphic_identity': 'B',
  }


Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()
session.query(with_polymorphic(A, "*")).all()
```

**Error**

```2021-06-26 15:40:01,165 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-06-26 15:40:01,165 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("a")
2021-06-26 15:40:01,165 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-26 15:40:01,166 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("a")
2021-06-26 15:40:01,166 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-26 15:40:01,166 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("b")
2021-06-26 15:40:01,166 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-26 15:40:01,166 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("b")
2021-06-26 15:40:01,166 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-06-26 15:40:01,167 INFO sqlalchemy.engine.Engine
CREATE TABLE a (
	id INTEGER NOT NULL,
	poly VARCHAR,
	PRIMARY KEY (id)
)


2021-06-26 15:40:01,167 INFO sqlalchemy.engine.Engine [no key 0.00008s] ()
2021-06-26 15:40:01,167 INFO sqlalchemy.engine.Engine
CREATE TABLE b (
	id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(id) REFERENCES a (id)
)


2021-06-26 15:40:01,167 INFO sqlalchemy.engine.Engine [no key 0.00008s] ()
2021-06-26 15:40:01,167 INFO sqlalchemy.engine.Engine COMMIT
2021-06-26 15:40:01,168 INFO sqlalchemy.engine.Engine BEGIN (implicit)
Traceback (most recent call last):
  File "/Users/maparent/test/test.py", line 34, in <module>
    session.query(with_polymorphic(A, "*")).all()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return self._iter().all()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2838, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1443, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 518, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 553, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3011, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 500, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 656, in create_for_statement
    self._setup_for_generate()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 763, in _setup_for_generate
    entity.setup_compile_state(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 2470, in setup_compile_state
    loading._setup_entity_query(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 613, in _setup_entity_query
    value.setup(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 629, in setup
    loader = self._get_context_loader(context, path)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 599, in _get_context_loader
    search_path = path[self]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/path_registry.py", line 449, in __getitem__
    return PropRegistry(self, entity)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/path_registry.py", line 302, in __init__
    subclass_entity = parent[-1]._entity_for_mapper(prop.parent)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 803, in _entity_for_mapper
    return getattr(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 537, in __getattr__
    attr = getattr(target, key)
AttributeError: type object 'A' has no attribute 'B'
```

**Versions.**
 - OS: MacOS 11.4
 - Python: 3.9.5
 - SQLAlchemy: 1.4.19
 - Database: sqlite
 - DBAPI: ?

**Additional context**

The issue seems to be that we lose the weak entity reference to the `AliasedClass` in `AliasedInsp`; and `_reconstitute_from_aliased_insp` does not reconstitute the subclass attributes. Adding that back solves the issue (PR provided separately)

**Comment by zzzeek** [comment] 2021-06-26 20:10
not sure why this is happening yet but the with_polymorphic() can be declared outside which is as we do in the tests and this works fine:

```python
wp = with_polymorphic(A, "*")
session.query(wp).all()
```

the issue is likely that the with_polymorphic object itself is being garbage collected in your case, because as you may have observed we hold onto the AliasedInsp part of it.

**Comment by sqla-tester** [comment] 2021-06-26 20:55
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**ensure with poly entities are also reconstituted for GC'ed AC** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2921

**Comment by zzzeek** [comment] 2021-06-26 23:03
OK, thanks.  you were on the right track w/ the PR, pretty good for figuring that out.

**Closed** 2021-06-26 23:03 UTC
Labels: bug, orm, regression
