### ISSUE TITLE
deprecate implicit use of id() for non hashable and emit warning; make NullType hashable

### ISSUE THREAD

**Issue by lukasjuhrich** [sqlalchemy/sqlalchemy#6769] opened 2021-07-15 01:19 UTC
Not sure if Bug or question, but at least unexpected behavior.

**Describe the bug**
When querying duplicated results of the type `(User, int, datetime)`, an attempted deduplication using `.unique()` did not have any effect, and returned multiple rows containing the exact same values.

The reason is that the default identification strategy amounts to an element-wise projection using `id`, and not `hash`.
This causes the `int` and the `datetime` columns of two rows – even though having the same value – to be recognized as different.

This is in contradiction to the “comparison by value“ assumption that I personally have of such a deduplication, and also in contradiction to what the [docs](https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Result.unique) state:
>  The algorithm used to determine this uniqueness is by default the Python hashing identity of the whole tuple.

In particular, this issue is “resolved” by using an identity strategy, i.e. `.unique(lambda row: row)` .
This works because the result of the strategy is collected in a set, whose notion of equality is based on `hash`.

If this is not considered a bug, it should be a warning explicitly stated in the aforelinked section in the docs.

**To Reproduce**
_(I'm really sorry, but it's a bit late in the night, I can create an MCVE later if required.)_

I can provide context from a debugging session. I'm breaking in `ResultInternal._allrows` in [this line](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_18/lib/sqlalchemy/engine/result.py#L409).

```
>>> type(self)
<class 'sqlalchemy.engine.result.ChunkedIteratorResult'>
>>> self._metadata._unique_filters
[<built-in function id>, <built-in function id>, <built-in function id>]
>>> [tuple(id(el) for el in r) for r in made_rows[:4]]
[(140281848273408, 140281848246224, 140281848184384),
(140281848273408, 140281848267056, 140281848184480),
(140281848273552, 140281848267344, 140281848184672),
(140281848273552, 140281848267632, 140281848270896)]
>>> [tuple(hash(el) for el in r) for r in made_rows[:4]]
[(8767615517088, 13812, -7323339362369131990),
(8767615517088, 13812, -7323339362369131990),
(8767615517097, 13815, -4473479583634129130),
(8767615517097, 13815, -4473479583634129130)]
>>> [tuple(type(el) for el in r) for r in made_rows[:4]]
[(<class 'pycroft.model.user.User'>, <class 'int'>, <class 'datetime.datetime'>),
(<class 'pycroft.model.user.User'>, <class 'int'>, <class 'datetime.datetime'>),
 (<class 'pycroft.model.user.User'>, <class 'int'>, <class 'datetime.datetime'>), 
(<class 'pycroft.model.user.User'>, <class 'int'>, <class 'datetime.datetime'>)]
```

Feel free to ask for other details.

**Versions.**
 - OS:
 - Python: 3.9.1
 - SQLAlchemy:1.4.18
 - Database: Postgres

**Have a nice ~~day~~ night!**

**Comment by zzzeek** [comment] 2021-07-15 02:49
> Not sure if Bug or question, but at least unexpected behavior.
> 
> **Describe the bug**
> When querying duplicated results of the type `(User, int, datetime)`, an attempted deduplication using `.unique()` did not have any effect, and returned multiple rows containing the exact same values.
> 
> The reason is that the default identification strategy amounts to an element-wise projection using `id`, and not `hash`.

this is not accurate.  the default deduplication strategy in the ORM is this:

```
        _unique_filters=[
            _no_unique
            if context.yield_per
            else id
            if ent.use_id_for_hash
            else None
            for ent in context.compile_state._entities
        ],
```


ignoring the "yield_per" part, what this means is that for each "entity" in the ORM select, in your example User, int, and date, has a deduplication strategy of its own based on what kind of entity it is. For the ORM entity "User", it uses id(), because there's an [identity map](https://docs.sqlalchemy.org/en/14/glossary.html?highlight=identity%20map#term-identity-map) so id() is in fact uniquing.  for the other values, it uses hash().   The program below illustrates this:


```py
import datetime

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import union_all
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session, aliased

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(Integer)
    date = Column(DateTime)


e = create_engine("sqlite://", echo=False)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(id=1, data=5, date=datetime.datetime.now()))
s.commit()


def go():

    union = aliased(
        A,
        union_all(
            select(A),
            select(A),
            select(A),
        ).subquery(),
    )

    result = s.execute(select(union, union.data, union.date))
    return result


print("\n\nno deduplication:")
print(go().all())

print("\n\ndeduplication:")
print(go().unique().all())
```

the output from the program looks like:

```py
$ python test3.py 

no deduplication:
[(<__main__.A object at 0x7f598f6293a0>, 5, datetime.datetime(2021, 7, 14, 22, 36, 11, 886564)), (<__main__.A object at 0x7f598f6293a0>, 5, datetime.datetime(2021, 7, 14, 22, 36, 11, 886564)), (<__main__.A object at 0x7f598f6293a0>, 5, datetime.datetime(2021, 7, 14, 22, 36, 11, 886564))]


deduplication:
[(<__main__.A object at 0x7f598f638100>, 5, datetime.datetime(2021, 7, 14, 22, 36, 11, 886564))]
```

so we can see that unique() is in fact deduplicating the row using value for the int / date values.

> 
> I can provide context from a debugging session. I'm breaking in `ResultInternal._allrows` in [this line](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_18/lib/sqlalchemy/engine/result.py#L409).
> 
> ```
> >>> type(self)
> <class 'sqlalchemy.engine.result.ChunkedIteratorResult'>
> >>> self._metadata._unique_filters
> [<built-in function id>, <built-in function id>, <built-in function id>]

so that looks like the result you'd get from a row consisting of three ORM objects.    i dont know how you'd get this from what you describe.   try out my example to see.

```py
print("\nthe filters:")
print(go()._metadata._unique_filters)
```

returns:

```
the filters:
[<built-in function id>, None, None]
```


> >>> [tuple(id(el) for el in r) for r in made_rows[:4]]
> [(140281848273408, 140281848246224, 140281848184384),
> (140281848273408, 140281848267056, 140281848184480),
> (140281848273552, 140281848267344, 140281848184672),
> (140281848273552, 140281848267632, 140281848270896)]
> >>> [tuple(hash(el) for el in r) for r in made_rows[:4]]
> [(8767615517088, 13812, -7323339362369131990),
> (8767615517088, 13812, -7323339362369131990),
> (8767615517097, 13815, -4473479583634129130),
> (8767615517097, 13815, -4473479583634129130)]
> >>> [tuple(type(el) for el in r) for r in made_rows[:4]]
> [(<class 'pycroft.model.user.User'>, <class 'int'>, <class 'datetime.datetime'>),
> (<class 'pycroft.model.user.User'>, <class 'int'>, <class 'datetime.datetime'>),

so yeah, there's no way I can think of that this would be possible, so please take the example program above and modify it such that it produces what you are seeing.

**Comment by lukasjuhrich** [comment] 2021-07-20 20:24
Got it! I had `func`-terms in my `select`, so e.g. adding `[…], func.abs(union.date)` to your program reproduces it:

```python
import datetime
from pprint import pprint

from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import create_engine
from sqlalchemy import func
from sqlalchemy import select
from sqlalchemy import union_all
from sqlalchemy.orm import Session, aliased
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(Integer)
    date = Column(DateTime)


e = create_engine("sqlite://", echo=False)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(id=1, data=5, date=datetime.datetime.now()))
s.commit()


def go():

    union = aliased(
        A,
        union_all(
            select(A),
            select(A),
            select(A),
        ).subquery(),
    )

    result = s.execute(select(union, union.data, union.date, func.abs(union.date)))
    return result


print("\nthe filters:")
print(go()._metadata._unique_filters)

print("\n\nno deduplication:")
pprint(go().all())

print("\n\ndeduplication:")
pprint(go().unique().all())

```
Result:
```
the filters:
[<built-in function id>, None, None, <built-in function id>]


no deduplication:
[(<__main__.A object at 0x7f3c27e7bee0>, 5, datetime.datetime(2021, 7, 20, 22, 7, 45, 307522), 2021.0),
 (<__main__.A object at 0x7f3c27e7bee0>, 5, datetime.datetime(2021, 7, 20, 22, 7, 45, 307522), 2021.0),
 (<__main__.A object at 0x7f3c27e7bee0>, 5, datetime.datetime(2021, 7, 20, 22, 7, 45, 307522), 2021.0)]


deduplication:
[(<__main__.A object at 0x7f3c27e09cd0>, 5, datetime.datetime(2021, 7, 20, 22, 7, 45, 307522), 2021.0),
 (<__main__.A object at 0x7f3c27e09cd0>, 5, datetime.datetime(2021, 7, 20, 22, 7, 45, 307522), 2021.0),
 (<__main__.A object at 0x7f3c27e09cd0>, 5, datetime.datetime(2021, 7, 20, 22, 7, 45, 307522), 2021.0)]
```

**Comment by lukasjuhrich** [comment] 2021-07-20 22:19
To add to that, in my [real-world query](https://github.com/agdsn/pycroft/blob/da4864f4d9b309f511e12a6dd42c7d276e1dfa36/pycroft/lib/user_deletion.py#L32..L63) I'm using the `func`s in a CTE-select, and then the actual entities in the outer select just pass these values through.

**Comment by zzzeek** [comment] 2021-07-21 02:10
Ok that's an odd pattern that looks like it is resulting in a bug of some kind. Thats what we need in order to fix issues .  I'll have a look to see if it reproduces tomorrow.

**Comment by zzzeek** [comment] 2021-07-21 17:15
the issue is that the function being returned has no return datatype, and at the moment our own "NullType" has "hashable=False", which is incorrect as you can certainly hash None, so that's the bug.  additionally, the ORM implicitly using id() for non-hashable scalar columns seems like some old historical artifact, so I think this should be a deprecated behavior that emits a warning for now and will later raise an error if a truly non-hashable datatype is present in the row (such as JSON or ARRAY withotu using tuple).

assign a type to your function to work around for now, which seems to be "String" in this example:

    result = s.execute(select(union, union.data, union.date, func.abs(union.date, type_=String)))

**Comment by zzzeek** [comment] 2021-07-21 19:29
OK I remember why it does this now, because legacy query uniquifies in all cases it's trying to be conservative in this behavior rather than attempting to apply hash() to a datatype such as JSON that isn't typed within the Python side.   I think this behavior has to be fully separated out between legacy and new-style queries.

**Comment by sqla-tester** [comment] 2021-07-21 19:52
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Apply new uniquing rules for future ORM selects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2971

**Closed** 2021-07-21 22:52 UTC
Labels: bug, orm
