### ISSUE TITLE
Mypy 1.1 type errors with dataclasses 

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#9467] opened 2023-03-10 17:50 UTC
### Describe the typing issue

In mypy 1.1.1 we're seeing a lot of typing errors along the lines of:
```
 auth.py:136: error: Argument "email" to "User" has incompatible type
"str"; expected "Mapped[str]"  [arg-type]
        user = User(email=email, ***
```

Errors are not present in mypy 1.0.0.

I suspect it has to do with some new features around dataclasses.

### To Reproduce

```python
# Base defined like:
class Base(MappedAsDataclass, DeclarativeBase):
    ...
```

Let me know if you can't reproduce, and I'll try to look into it further.

### Versions

- SQLAlchemy: 2.0.5

**Comment by Dreamsorcerer** [comment] 2023-03-10 17:51
Not sure if a bug with mypy or sqlalchemy, I've not looked into it properly yet.

**Comment by CaselIT** [comment] 2023-03-10 18:44
Hi,

that may be solved in main by https://github.com/sqlalchemy/sqlalchemy/commit/bcbb4007bbfa5102d7e53fea8aac50e528d4d1f2

Can you try installing from git to see if solves that issue?

**Comment by zzzeek** [comment] 2023-03-10 19:03
this seems a bit ominous

**Comment by zzzeek** [comment] 2023-03-10 19:05
uh oh

**Comment by zzzeek** [comment] 2023-03-10 19:05
this is a mypy bug

**Comment by CaselIT** [comment] 2023-03-10 19:10
So the changes in main do not fix this? I guess we have to hold off that PR then

**Comment by zzzeek** [comment] 2023-03-10 19:25
this is unfortunately an issue in mypy, where they did not interpret the runtime behavior of dataclasses correctly.   I've added https://github.com/python/mypy/issues/14868 where we have to basically hope and pray they agree, because the authors of pep-681 refused to add explicit language to the spec for this (see https://github.com/microsoft/pyright/discussions/2958)

**Comment by zzzeek** [comment] 2023-03-10 19:31
here's their original bug:  https://github.com/python/mypy/issues/13856

still opened so they apparently released pep-681 with the bug.

**Comment by CaselIT** [comment] 2023-03-10 19:57
That's a bummer. I think we could pin (and leave it open? Not sure if a pinned issue can be closed) this isse and rename it to clarify better the issue, since otherwise I feel we will get multiple duplicates and SQLAlchemy cannot really do much here

**Comment by CaselIT** [comment] 2023-03-10 19:58
(closed issue can be pinned)

**Comment by Dreamsorcerer** [comment] 2023-03-11 00:17
Another error we get a lot of is:
```
models.py:181: error: Attributes without a default cannot follow
attributes with one  [misc]
        valid_from: Mapped[date]
```

But, obviously the code works at runtime. Do you think that's a bug in mypy too, part of the same issue?

e.g. With code like:
```
class Token(Base):
    ...
    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    number: Mapped[str] = mapped_column(sa.String(100))
    valid_from: Mapped[date]
```

**Comment by zzzeek** [comment] 2023-03-11 00:23
that doesnt produce any error for me

```py
from __future__ import annotations

from datetime import date

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import MappedAsDataclass



class Base(MappedAsDataclass, DeclarativeBase):
    pass

class Token(Base):
    __tablename__ = 'sgasdaf'

    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    number: Mapped[str] = mapped_column()
    valid_from: Mapped[date]
```
it's fine, no error in mypy

**Comment by Dreamsorcerer** [comment] 2023-03-11 01:21
Umm, that's weird. I just copied you exact code in:
```
> mypy test.py
test.py:21: error: Attributes without a default cannot follow attributes with one  [misc]
Found 1 error in 1 file (checked 1 source file)
```

It's also reproduced in our CI (private repo unfortunately).

**Comment by zzzeek** [comment] 2023-03-11 02:22
oh, im on sqlalchemy main, we did have some fixes that havent been released yet

**Comment by zzzeek** [comment] 2023-03-11 02:23
so yes that issue reprodcues on 2.0.5 and is now fixed

**Comment by zzzeek** [comment] 2023-03-11 15:19
Here's what we can do for a workaround for the top issue, assuming mypy devs don't have an answer for us anytime soon

```py
from __future__ import annotations
import typing

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

if typing.TYPE_CHECKING:
    class MappedAsDataclass:
        def __init__(self, *arg: typing.Any, **kw: typing.Any):
            pass
else:
    from sqlalchemy.orm import MappedAsDataclass


class Base(MappedAsDataclass, DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    data: Mapped[str]


a1 = A('some data')
```


SQLAlchemy can add a `MappedAsDataclassNoPep681` like this:


```diff
diff --git a/lib/sqlalchemy/orm/__init__.py b/lib/sqlalchemy/orm/__init__.py
index 69cd7f5985..503c6e4a9e 100644
--- a/lib/sqlalchemy/orm/__init__.py
+++ b/lib/sqlalchemy/orm/__init__.py
@@ -63,6 +63,7 @@ from .decl_api import DeclarativeMeta as DeclarativeMeta
 from .decl_api import declared_attr as declared_attr
 from .decl_api import has_inherited_table as has_inherited_table
 from .decl_api import MappedAsDataclass as MappedAsDataclass
+from .decl_api import MappedAsDataclassNoPep681 as MappedAsDataclassNoPep681
 from .decl_api import registry as registry
 from .decl_api import synonym_for as synonym_for
 from .decl_base import MappedClassProtocol as MappedClassProtocol
diff --git a/lib/sqlalchemy/orm/decl_api.py b/lib/sqlalchemy/orm/decl_api.py
index 60d2fbc2b7..50707e3a44 100644
--- a/lib/sqlalchemy/orm/decl_api.py
+++ b/lib/sqlalchemy/orm/decl_api.py
@@ -634,6 +634,13 @@ class MappedAsDataclass(metaclass=DCTransformDeclarative):
                 current_transforms, cls, new_anno
             )
 
+if typing.TYPE_CHECKING:
+    class MappedAsDataclassNoPep681:
+        def __init__(self, *arg: typing.Any, **kw: typing.Any):
+            pass
+else:
+    MappedAsDataclassNoPep681 = MappedAsDataclass
+
 
 class DeclarativeBase(
     inspection.Inspectable[InstanceState[Any]],

```

I think we're going to get more of these errors so I think I want to make a gerrit for this

**Comment by sqla-tester** [comment] 2023-03-11 15:40
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**propose no-pep681 workarounds** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4505

**Closed** 2023-03-12 18:04 UTC
Labels: dataclasses, external library/application issues, typing

**Comment by CaselIT** [comment] 2023-03-12 18:39
Ok, so you went for documentation only. I think it's the best approach, we can always add additional code later, but it's harder to remove it later, so starting small makes a lot of sense

**Comment by zzzeek** [comment] 2023-03-12 18:54
yeah, lets just wait for how big a deal this mypy thing is

**Comment by CaselIT** [comment] 2023-04-04 17:07
seems that 1.2 will fix it: https://github.com/python/mypy/issues/14868#issuecomment-1495910814 🎉

**Comment by kkirsche** [comment] 2023-04-07 11:45
Mypy 1.2 was released yesterday:
https://mypy-lang.blogspot.com/2023/04/mypy-12-released.html

In my testing, it largely fixes the issue(s), though I could still reproduce a situation where `init=False` was not being respected (such as on a dataclass's primary key). I'm unsure if that's a bug or expected but wanted to share the reproduction in case.

Details in https://gist.github.com/kkirsche/5a32d31fd62e2d955eb8f53df99bd212 to avoid clogging this thread up with example code if it's behaving as expected

**Comment by CaselIT** [comment] 2023-04-07 11:48
I'm not sure if annotated is supported by type checkers here. It may not be.

Does that happen if you also use `mapped_column` inline (even just `mapped_column(init=False)`)?

**Comment by kkirsche** [comment] 2023-04-07 12:53
Annotations work without issue on Mypy 1.0.1 with these parameters.

To your question, yes, `mapped_column(init=False)` and `mapped_column(default=None)` inline rather than in annotations address this behavior difference.

So I guess the questions become:

1. From a correctness perspective, should this have been composable originally via annotations in type checkers such as mypy?
2. For SQLAlchemy, should this be reported to Mypy as a regression, should this be documented, or does SQLAlchemy require a change of some kind (I'm not familiar with the typing concepts in SQLA2, so apologies if it's obviously not this)

**Comment by zzzeek** [comment] 2023-04-07 13:30
oh yes, putting the init=False inside the Annotated is not going to work, sorry.    pep-681 needs to see mapped_column(init=False) inline inside the body of the class.

**Comment by zzzeek** [comment] 2023-04-07 13:31
guess we have to document that

**Comment by CaselIT** [comment] 2023-04-07 14:12
> guess we have to document that

we can add it to this https://github.com/sqlalchemy/sqlalchemy/issues/9410

**Comment by zzzeek** [comment] 2023-04-07 15:12
another bug in the new mypy version #9617

**Comment by zzzeek** [comment] 2023-04-07 15:14
unfortuantely not as simply

**Comment by zzzeek** [comment] 2023-04-07 15:17
got it, pretty simple

**Comment by CaselIT** [comment] 2023-04-07 18:40
1.2 seems to surface also a few errors: https://github.com/sqlalchemy/sqlalchemy/actions/runs/4632974601/jobs/8197675058
