### ISSUE TITLE
table() fullname is missing schema

### ISSUE THREAD

**Issue by rectalogic** [sqlalchemy/sqlalchemy#7061] opened 2021-09-21 19:32 UTC
### Describe the bug

`Table().fullname` includes the schema, `table().fullname` does not

### To Reproduce

```python
>>> import sqlalchemy as sa
>>> t1 = sa.Table("x", sa.MetaData(), schema="foo")
>>> t1.fullname
'foo.x'
>>> t2 = sa.table("x", schema="foo")
>>> t2.fullname
'x'
>>> t2.schema
'foo'
```

### Error

`fullname` does not include the schema

### Versions

- OS: Ubuntu 20.04
- Python: 3.8.10
- SQLAlchemy: 1.4.23

### Additional context

`fullname` should return `foo.x` for both the above tables

**Comment by jvanasco** [comment] 2021-09-21 20:36
I don't believe this is a bug, but expected behavior.  Restating for other contributors:

User complains`sa.table.fullname` does not render the schema name as part of __str__ representation, like `sa.Table.fullname` does.  

`sa.table` is a TableClause (https://docs.sqlalchemy.org/en/14/core/selectable.html#sqlalchemy.sql.expression.table) which is the syntactical version of the schema level `sa.Table` (https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Table)

I think the docs may be misleading since "schema" was added in the 1.3.18 release to `sa.table`.  I expect many things would break if the schema were rendered on this. Perhaps a docs fix is needed, as ".fullname" doesn't seem to be documented - I only found it set in the __init__ of TableClause.

**Comment by CaselIT** [comment] 2021-09-28 21:07
I'm not sure, I think it may make sense to have fullname consistent between the `table` and `Table`.

@zzzeek do you remember if it was a conscious decision or we just forgot?

**Comment by zzzeek** [comment] 2021-09-28 21:08
oh we just forgot for sure.  adding schema to lower case table() was already some afterthought thing a specific user wanted.   it's not being done in an orderly way.

**Comment by sqla-tester** [comment] 2021-10-01 18:18
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Account for `schema` in `table()` `fullname` attribute.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3122

**Closed** 2021-10-01 22:26 UTC
Labels: bug, sql
