### ISSUE TITLE
or_ and and_() should emit a warning / someday raise an error with no arguments

### ISSUE THREAD

**Issue by dima-starosud** [sqlalchemy/sqlalchemy#5054] opened 2019-12-26 12:04 UTC
This is using `SQLAlchemy-1.3.12`.

I would expect `or_()` to produce kind of `false`, but it has truthy behaviour.
Note, `false` is neutral element for disjunction (and `true` for conjunction), so I would expect adding `false()` to it didn't change result, that's why I would expect following statements producing the same result:

    print(session.query(literal(42)).filter(or_()).first())
    # (42,)
    print(session.query(literal(42)).filter(or_(false())).first())
    # None

Note, that for `and_` everything works as expected:

    print(session.query(literal(42)).filter(and_()).first())
    # (42,)
    print(session.query(literal(42)).filter(and_(true())).first())
    # (42,)

There might some rationale behind current behaviour I am missing.

**Comment by zzzeek** [comment] 2019-12-26 15:59
Hi Dima -

Are you suggesting that "select().where(or_(false())" should produce no WHERE clause?  I don't think a lot of people would find that to be intuitive. There is no boolean logic inside of the and_() or or_() functions or any special significance to the fact that the expression happens to be boolean false.    Whatever is there renders.  What if the expression where select().where(or_(some_column != some_column)) ?   How would SQLAlchemy detect, before sending anything to the database, that it should not render this expression at all?  How could this be achieved without any round trip to the database?

**Comment by dima-starosud** [comment] 2019-12-26 17:14
Hello Mike

Sorry, I wasn't clear enough.
I just wanted `or_()` to produce `false()`.

**Comment by zzzeek** [comment] 2019-12-26 18:51
Hmmm it doesnt do that?    surprises ....

**Comment by zzzeek** [comment] 2019-12-26 18:54
oh or_() iwth nothing in it.    mmmmm   I'd rather it don't do that. and_() with nothing in it produces nothing either.    

```
>>> print(select([literal('x')]).where(and_()))
SELECT :param_1 AS anon_1
>>> print(select([literal('x')]).where(or_()))
SELECT :param_1 AS anon_1

```

if you want an or_() or and_() that has a short circuit default you should load it up w/ true or false ahead of time, the way you do with say Python sum(),which simply raises when you pass it nothing.

**Comment by zzzeek** [comment] 2019-12-26 18:56
ugh, reading your comment again, you are contradicting what you are asking for:

"I just wanted or_() to be transformed to false"

then:

"so select().where(or_(false()) would produce select ... where false"

which please?   the latter produces false already.  the former behaves consistently with and_() etc. and I'd prefer it raise if anything (non-explicit).

**Comment by dima-starosud** [comment] 2019-12-26 19:01
Oh, sorry, I meant "`select(1).where(or_())` would produce `select 1 where false`".

**Comment by dima-starosud** [comment] 2019-12-26 19:15
For me `or_` is something like Python's standard `any`, which produces `False` when is passed empty sequence.

**Comment by zzzeek** [comment] 2019-12-26 19:20
I see these as syntactical constructs and not logical ones, but also my lack of experience in perhaps FP is making it difficult for what you are asking for at the top to "click" for me. I see the "false()" in one and "true()" in the other, so for me that makes it intuitive that one returns a result and the other one doesnt.   when and_() and or_() are empty, it seems intuitive to me they should do nothing, because they are operators without any operands.    If I were looking for logical backstop behavior I'd want that to be explicit, e.g. pass in false() or true() at the end.

Mostly I'm going off of something like Python sum(), which just raises if you pass it nothing, so if you wanted, we can adapt sum()'s behavior of accepting a default, like:

    or_(default=false())

**Comment by dima-starosud** [comment] 2019-12-27 10:05
Right, thank you Mike for an explanation. Agree with this: if one treats `or_`/`and_`/etc. just as SQL building blocks the behaviour is expected. But we usually talk about what code does, not about what it's compiled/transformed to, I mean when I see `session.query(...).filter(...)` I don't really care what SQL it will be transformed to (sometimes I do, but only when this transformation contradicts with my expectations).

Let me please, give another try to explain this.
If one considers `and_`, he may observe that the behaviour of final SQL statement won't change if he adds `true()` to the list of arguments for any number of arguments, i.e:
`and_(true(), p1, ..., pN) === and_(p1, ..., pN), for any N`.

The same for `or_` except small bit:
`or_(false(), p1, ..., pN) === or_(p1, ..., pN), for any N > 0`.
Notice `> 0` at the end.

So, `and_` and `or_` from this perspective behave differently for `N = 0`.

Note, I see that probably most of the people treat those functions just as SQL building blocks, since no one has risen this before, so I am starting thinking that current behaviour is closer to people expectations.

**Comment by CaselIT** [comment] 2019-12-27 15:21
I agree with you @dima-starosud regarding the usual behavior of a logical `OR` or `AND` with no elements, but I think that the expected behavior in this case is more like a SQL building block that an logic operator.

Maybe this could be solved with a line in the documentation for the `or_` and `and_` indicating that an empty invocation is ignored in contrast with the normal logic operator behavior that produce a `false` and `true` respectively? Or maybe a warning when calling them empty?

**Comment by zzzeek** [comment] 2019-12-27 15:46
> Right, thank you Mike for an explanation. Agree with this: if one treats `or_`/`and_`/etc. just as SQL building blocks the behaviour is expected. But we usually talk about what code does, not about what it's compiled/transformed to, I mean when I see `session.query(...).filter(...)` I don't really care what SQL it will be transformed to (sometimes I do, but only when this transformation contradicts with my expectations).

right there, that's only one way of using SQLAlchemy.  the name "filter()" is going to be changing to "where()" and the thrust of the whole system is that you'd be thinking about a SQL SELECT statement as you call these methods which is how many people work with it.    I can definitely say that it is a risk when we suggest to take a construct like "or_()", which doesn't have the word "false" anywhere in it, and it would be emitting the word "FALSE" all the sudden.  Folks who work in the "its a SQL builder tool" mindset would be surprised by it and whether or not it's "correct", it will generate bug reports by people who are surprised, just as the current behavior is generating this bug report.    Behaviors that generate bug reports because some people expect one thing, and others another, are indicators for ambiguous behaviors that should be deprecated and replaced with an unambiugous API.

> 
> Let me please, give another try to explain this.
> If one considers `and_`, he may observe that the behaviour of final SQL statement won't change if he adds `true()` to the list of arguments for any number of arguments, i.e:
> `and_(true(), p1, ..., pN) === and_(p1, ..., pN), for any N`.
> 
> The same for `or_` except small bit:
> `or_(false(), p1, ..., pN) === or_(p1, ..., pN), for any N > 0`.
> Notice `> 0` at the end.
> 
> So, `and_` and `or_` from this perspective behave differently for `N = 0`.

sure.   The best we can agree on is that N=0 is ambiguous - did the caller expect it to behave as a logic operator, or a syntactical operator ?  IMO it's not clear.  if they said or_(default=false()), then it's clear, and not only that, SQLAlchemy doesn't have to make an assumption about the kind of "false" operator being requested since for example if this were Oracle, it's not valid to say "SELECT 1 FROM DUAL WHERE 0" - that is, from a "logic" perspective we can't really be very pure here.

So if this is really bugging you the most I'd feel comforable with is deprecation warning for empty or_() / and_(), add default parameter or something similar, then in 1.5 or whatever it raises for no arguments present because IMO it's ambiguous.

> 
> Note, I see that probably most of the people treat those functions just as SQL building blocks, since no one has risen this before, so I am starting thinking that current behaviour is closer to people expectations.

It's very possible that I'm the only person that sees it the way I'm seeing it.  If I put it up on twitter, there may be a plurality of folks who see it the logical way and I bet that's what would happen since tweeters tend to be more formalist than I am.    But even if I'm the only person who doesnt see it that way, the fact that it's been this way for 13 years also counts as a vote, so if it is truly ambiguous all roads lead to deprecate.

**Comment by zzzeek** [comment] 2019-12-27 15:50
here's that https://twitter.com/zzzeek/status/1210588210314776578

looking at it, my bet is that b will win with 60%, but I'm fully pleased to be completely wrong.   Any win less than 80% or so points to this being somewhat of an ambiguous case which is a bug in itself.

**Comment by CaselIT** [comment] 2019-12-27 16:03
>  I can definitely say that it is a risk when we suggest to take a construct like "or_()", which doesn't have the word "false" anywhere in it, and it would be emitting the word "FALSE" all the sudden.

Regarding this I don't it's any stranger than and empty `in_()` or `notin()` that render `1 != 1` and `1 == 1`
Still, I agree with you that is is ambiguous

**Comment by zzzeek** [comment] 2019-12-29 07:00
as the law of twos continues (the law that an issue raised regarding some feature, where no issue has been raised for said feature in many many years, will immediately be followed within a day or so by another issue regarding almost the identical behavioral area), see #5061 where someone is reminding me that `or_()` actually is doing a small degree of boolean logic.      The twitter poll makes it clear that nobody at all accepts my intuitition about `or_()`, everyone thinks if it were do anything besides raise an error, it would do what's described above.  but most people think it should raise an error.

**Comment by dima-starosud** [comment] 2019-12-29 08:31
Thank you @zzzeek a lot for doing this investigation.
I agree with the points and accept all the arguments and now I realize that raising is the best solution in this situation.

**Comment by CaselIT** [comment] 2019-12-29 12:03
I've tried opening a pr for this. 
Since empty `and_` and `or_` are used in many places in the test suite I'm not sure how to best change change the tests

**Comment by zzzeek** [comment] 2019-12-29 16:00
@CaselIT they all have to be changed to use the canonical approach :)

After looking at #5061 I think my thing with "default=False" is not necessary, the guidance would be:

1. if someone uses `and_()`, they should instead be saying `and_(true())` or `and_(True)`

2. if someone uses `and_(*args)` where args may be empty, they should instaed be using `and_(True, *args)`

3. if someone uses `or_()`, they should instead be saying `or_(false())` or`or_(False)`

4. if someone uses `or(*args)` where args may be empty, they should instead be using `or_(False, *args)`.

this all works terrifically since short circuiting was added (and which I forgot about completely) in #2804:

```
>>> print(or_(False, column('q')))
q
>>> print(or_(False, column('q'), column('p')))
q OR p
>>> print(or_(false(), column('q'), column('p')))
q OR p
>>> print(or_(False))
false

```

even databases without a true/false constant and even if they are grumpy about 0/1 as a criteria works!

```
>>> from sqlalchemy.dialects import oracle
>>> print(or_(False).compile(dialect=oracle.dialect()))
0 = 1

```

the warning here should be a deprecation warning that suggests prefixing the and_() / or_() with True / False, respectively.

**Comment by CaselIT** [comment] 2019-12-29 16:30
I'll update the warning and make the changes to the test.

Maybe this guidance should also be in the documentation for `and_` and `or_`?

**Comment by sqla-tester** [comment] 2020-01-25 19:54
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Deprecate empty or_() and and_()** https://gerrit.sqlalchemy.org/1682

**Closed** 2020-01-26 16:22 UTC
Labels: bug, sql
