### ISSUE TITLE
MSSQL dialect incorrectly detects temp tables from different sessions.

### ISSUE THREAD

**Issue by ewallace-RI** [sqlalchemy/sqlalchemy#6910] opened 2021-08-19 20:39 UTC
### Describe the bug

The MSDialect.has_table method handles temp tables with a query like
```
 select from tempdb.INFORMATION_SCHEMA.columns where table_name like '{table_name}___%'
```
If there is another active session using a temp table of the same name, this version of has_table() returns True, even though there is no such table available to this session.

### To Reproduce

```python
con1 = engine.connect()
con1.execute('create table #myveryveryuniquetemptablename (a int)')
con2 = engine.connect()
print(con2.dialect.has_table(con2, '#myveryveryuniquetemptablename'))
con1.close()
con2.close()
```

### Error

Above snippet prints True. Correct behavior would be False.

### Versions

- OS: Windows
- Python: 3.9
- SQLAlchemy: 1.4.23
- Database: MS SQL Server
- DBAPI: pyodbc 4.0.31

**Comment by ewallace-RI** [comment] 2021-08-19 20:40
Introduced by the fix for https://github.com/sqlalchemy/sqlalchemy/issues/5597.

**Comment by CaselIT** [comment] 2021-08-19 21:03
Thanks for reporting.

Do you have a suggestion regarding what's the correct query to do instead?

**Comment by CaselIT** [comment] 2021-08-19 21:04
also cc @gordthompson

**Comment by ewallace-RI** [comment] 2021-08-19 21:14
Sorry, should have included the suggested fix. I use something like this, which works for both temp tables and physical tables.
```
    db = 'tempdb.' if tname.startswith('#') else ''
    t_id, = con.execute(f"select object_id('{dbname}dbo.{tname}')").fetchone()
    return t_id is not None
```
Not sure if there's some other preferred method.

**Comment by sqla-tester** [comment] 2021-08-20 15:51
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix has_table() to exclude other sessions' temp tables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3014

**Comment by zzzeek** [comment] 2021-08-20 16:04
I noted on the gerrit that the above fix should not apply to global temporary tables that start with "##".

**Comment by ewallace-RI** [comment] 2021-08-20 17:40
@zzzeek I think the attached fix works for global temp tables. Temp tables from the current session and ##global temp tables will both have non-null object_ids, so this version of has_table will return True for both of them, as expected. And the _temp_table_name_like_pattern logic is unaffected.

@gordthompson I also noticed when looking into this that the _temp_table_name_like_pattern doesn't seem to be quite right. The unquoted underscore is a single-character wildcard in a like pattern, so '#tmp___%' will also match a table named '#tmp123'. The object_id logic should do the right thing, so I think the proposed fix also takes care of that, just something to be aware of.

**Comment by zzzeek** [comment] 2021-08-20 19:00
> @zzzeek I think the attached fix works for global temp tables. Temp tables from the current session and ##global temp tables will both have non-null object_ids, so this version of has_table will return True for both of them, as expected. And the _temp_table_name_like_pattern logic is unaffected.

oh, good idea.

**Comment by gordthompson** [comment] 2021-08-20 19:00
> The unquoted underscore is a single-character wildcard in a like pattern

Good point. Thanks for mentioning it!

**Closed** 2021-08-23 18:18 UTC
Labels: bug, SQL Server, reflection

**Comment by marzlevane** [comment] 2021-10-09 18:20
The fix for this issue results in a false negative in has_table() when there is a temp table with the same name in both the current and another session, only the first returned temp table is checked with object_id(). If this first returned result happens to be a table from another session, has_table() will return false and not check other candidates that may be in the current session.

May I suggest just returning the booled result of "SELECT OBJECT_ID('tempdb..[temp_table_name])" instead? I believe there is no use for checking information_schema for similarly named temp tables since the object_id-check works for the "raw" temp table name. Should I open a new issue for this?

**Comment by CaselIT** [comment] 2021-10-09 18:25
If you can open a new issue, we can track it better

Thanks

**Comment by marzlevane** [comment] 2021-10-09 18:34
Will do, steps to reproduce are very similar to example in this issue, just inverted (false negative instead of false positive).
