### ISSUE TITLE
apply LONG_VARBINARY rule to cx_Oracle BLOB on OUT parameters as well as outputtype handler

### ISSUE THREAD

**Issue by meshantz** [sqlalchemy/sqlalchemy#5812] opened 2021-01-04 15:12 UTC
I'm going to pose this as a question, but it's possible you may consider it a bug or feature request.

So, I'm using sql expression language with the cx_Oracle dialect, and troubleshooting an issue around returning and blob fields.

If you do: `some_model.insert(...).values(...).returning(some_model.c.blob_col)` this works fine.

However, `some_model.insert(...).values(...).returning(some_model.c.blob_col, some_model.c.id_col)` (for instance) results in:
```
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-24813: cannot send or receive an unsupported LOB
```

The reason behind this seems to be that returning approximates some aspects of oracle because cx_Oracle's dbapi doesn't "natively support" return values (reference: https://docs.sqlalchemy.org/en/14/core/dml.html#sqlalchemy.sql.expression.UpdateBase.returning)

The idea as I understand it is it uses the `RETURNING... INTO` clause with bind variables (which I'm familiar with), and the `cx_Oracle.BLOB` type supports streaming behaviour, which seems to be incompatible with whatever shim is in place.

Now if I do the built out query manually using `cx_Oracle.LONG_BINARY` as the return value type instead of BLOB (which will load the whole value into memory instead of streaming it) the query works fine.

So what I'd like to be able to do is substitute in the "correct" type when I set up the `insert(...).returning(...)`. Is there any clean way to do so short of monkey-patching the dialect? Maybe I'm coming at this from the wrong angle?

If you require a more complete example I can provide one.

**Versions**
 - OS: Debian 10 (dockerized)
 - Python: 3.7.4
 - SQLAlchemy: 1.2.30
 - Database: Oracle 10g
 - DBAPI: cx_Oracle 7.2.2

**Full Stack Trace**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-24813: cannot send or receive an unsupported LOB

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccs_utils/utils.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/srv/backend/src/crud/views.py", line 228, in post
    return self.make_post_response()
  File "/srv/backend/src/crud/views.py", line 217, in make_post_response
    out_val = self.execute_insert_query()
  File "/srv/backend/src/crud/views.py", line 195, in execute_insert_query
    result = cx.execute(insert_object).fetchone()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-24813: cannot send or receive an unsupported LOB
[SQL: INSERT INTO security.application (rid, application, client_id, client_domain, client_image, client_vault_key, client_session_key) VALUES (:rid, :application, :client_id, :client_domain, :client_image, :client_vault_key, :client_session_key) RETURNING security.application.rid, security.application.application, security.application.client_id, security.application.client_domain, security.application.client_image, security.application.client_vault_key, security.application.client_session_key, security.application.modified_at, security.application.modified_count INTO :ret_0, :ret_1, :ret_2, :ret_3, :ret_4, :ret_5, :ret_6, :ret_7, :ret_8]
[parameters: {'rid': 0, 'application': 'another', 'client_id': 'sdfaf', 'client_domain': 'another.ccs.coldstorage.com', 'client_image': b'looloolooloolooloolooloo', 'client_vault_key': 'another', 'client_session_key': 'another:sid:', 'ret_0': <cx_Oracle.STRING with value [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>, 'ret_1': <cx_Oracle.STRING with value []>, 'ret_2': <cx_Oracle.STRING with value []>, 'ret_3': <cx_Oracle.STRING with value []>, 'ret_4': <cx_Oracle.BLOB with value []>, 'ret_5': <cx_Oracle.STRING with value []>, 'ret_6': <cx_Oracle.STRING with value []>, 'ret_7': <cx_Oracle.TIMESTAMP with value []>, 'ret_8': <cx_Oracle.STRING with value [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>}]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
```

**Comment by zzzeek** [comment] 2021-01-04 17:35
hey there -

> sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-24813: cannot send or receive an unsupported LOB

I'm not familiar with this error message, haven't tried using BLOB with RETURNING before.  are you calling read() on the value right now?  as we aren't doing that in this case?

> 
> The reason behind this seems to be that returning approximates some aspects of oracle because cx_Oracle's dbapi doesn't "natively support" return values (reference: https://docs.sqlalchemy.org/en/14/core/dml.html#sqlalchemy.sql.expression.UpdateBase.returning)

to my knowledge, which might be out of date, this is correct, one must awkwardly use OUT parameters to implement RETURNING with cx_Oracle, so only one row back is supported, making the value of RETURNING fairly marginal.

i haven't checked if newer versions of cx_Oracle can actually return result sets for RETURNING however.  if it does, we should migrate to that.

> 
> The idea as I understand it is it uses the `RETURNING... INTO` clause with bind variables (which I'm familiar with), and the `cx_Oracle.BLOB` type supports streaming behaviour, which seems to be incompatible with whatever shim is in place.

OK 

> 
> Now if I do the built out query manually using `cx_Oracle.LONG_BINARY` as the return value type instead of BLOB (which will load the whole value into memory instead of streaming it) the query works fine.

one way to maybe have it work right now is to type_coerce() to a different type:

    from sqlalchemy import type_coerce
    some_model.insert(...).values(...).returning(some_model.c.blob_col, type_coerce(some_model.c.id_col, BINARY))

we don't have a type that comes out with cx_Oracle.LONG_BINARY for the moment but if it works with cx_Oracle.Binary I think that's the type that would be used.  The above might be pushing things though, not sure.


We also do seem to have LONG_BINARY associated with BLOB in our usual outputtypehandler logic, this is newer as we used to read() the var ourselves but then cx_Oracle added support for binding it to LONG_BINARY directly.   So we could just copy this logic: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/oracle/cx_oracle.py#L1069 to here:  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/oracle/cx_oracle.py#L616

here's a patch you can try (I would need complete [MCVE](http://stackoverflow.com/help/mcve) to work on this further):

```diff
diff --git a/lib/sqlalchemy/dialects/oracle/cx_oracle.py b/lib/sqlalchemy/dialects/oracle/cx_oracle.py
index 042443692..b83397597 100644
--- a/lib/sqlalchemy/dialects/oracle/cx_oracle.py
+++ b/lib/sqlalchemy/dialects/oracle/cx_oracle.py
@@ -616,19 +616,32 @@ class OracleExecutionContext_cx_oracle(OracleExecutionContext):
                 if bindparam.isoutparam:
                     name = self.compiled.bind_names[bindparam]
                     type_impl = bindparam.type.dialect_impl(self.dialect)
+
                     if hasattr(type_impl, "_cx_oracle_var"):
                         self.out_parameters[name] = type_impl._cx_oracle_var(
                             self.dialect, self.cursor
                         )
                     else:
                         dbtype = type_impl.get_dbapi_type(self.dialect.dbapi)
-                        if dbtype is None:
-                            raise exc.InvalidRequestError(
-                                "Cannot create out parameter for parameter "
-                                "%r - its type %r is not supported by"
-                                " cx_oracle" % (bindparam.key, bindparam.type)
+
+                        cx_Oracle = self.dialect.dbapi
+
+                        if (
+                            self.dialect.auto_convert_lobs
+                            and dbtype is cx_Oracle.BLOB
+                        ):
+                            self.out_parameters[name] = self.cursor.var(
+                                cx_Oracle.LONG_BINARY,
                             )
-                        self.out_parameters[name] = self.cursor.var(dbtype)
+                        else:
+                            if dbtype is None:
+                                raise exc.InvalidRequestError(
+                                    "Cannot create out parameter for parameter "
+                                    "%r - its type %r is not supported by"
+                                    " cx_oracle"
+                                    % (bindparam.key, bindparam.type)
+                                )
+                            self.out_parameters[name] = self.cursor.var(dbtype)
                     self.parameters[0][
                         quoted_bind_names.get(name, name)
                     ] = self.out_parameters[name]

```

> 
> So what I'd like to be able to do is substitute in the "correct" type when I set up the `insert(...).returning(...)`. Is there any clean way to do so short of monkey-patching the dialect? Maybe I'm coming at this from the wrong angle?

I've never considered returning a BLOB in returning so try the patch above.

> 
> If you require a more complete example I can provide one.

Please send, thanks!

**Comment by meshantz** [comment] 2021-01-04 19:10
Thanks for the speedy and detailed reply. Hopefully this qualifies as MCVE, though I've glossed over the database connection:

The table was generated from the SQL Developer GUI and resulted in the following create statements (schema can probably be replaced with whatever name you want):
```
CREATE TABLE SECURITY.EXAMPLE1 
(
  RID NUMBER NOT NULL 
, THING VARCHAR2(20 BYTE) NOT NULL 
, IMAGE_DATA BLOB NOT NULL 
, CONSTRAINT EXAMPLE1_PK PRIMARY KEY 
  (
    RID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SECURITY.EXAMPLE1_PK ON SECURITY.EXAMPLE1 (RID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (IMAGE_DATA) STORE AS SYS_LOB0000450238C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
);

--------------------------------------------------------
--  DDL for Sequence EXAMPLE1_RID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SECURITY"."EXAMPLE1_RID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
```

models.py:
```
from sqlalchemy import (
    LargeBinary,
    Column,
    Integer,
    MetaData,
    Sequence,
    String,
    Table,
)

metadata = MetaData(schema="security")

example1 = Table(
    "example1",
    metadata,
    Column("rid", Integer, Sequence("example1_rid_seq"), primary_key=True),
    Column("thing", String(20), nullable=False),
    Column("image_data", LargeBinary, nullable=False),
)
```

And then the examples:
```
>>> import models
>>> data = dict(thing="some text", image_data=b"\xde\xad\xbe\xef")
>>> ins = models.example1.insert().values(**data).returning(models.example1.c.rid)
>>> with db.connection() as cx:
...   result = cx.execute(ins).fetchone()  # works
... 
>>> result
(2,)
>>> ins = models.example1.insert().values(**data).returning(models.example1.c.rid, models.example1.c.thing)
>>> with db.connection() as cx:
...   result = cx.execute(ins).fetchone()  # also works
... 
>>> result
(3, 'some text')
>>> ins = models.example1.insert().values(**data).returning(models.example1.c.rid, models.example1.c.thing, models.example1.c.image_data)
>>> with db.connection() as cx:
...   result = cx.execute(ins).fetchone()  # cx_Oracle.DatabaseError: ORA-24813: cannot send or receive an unsupported LOB
... 
Traceback...
>>> ins = models.example1.insert().values(**data).returning(models.example1.c.image_data)
>>> with db.connection() as cx:
...   result = cx.execute(ins).fetchone()  # makes it back from database, but outputting the result is a problem...
... 
>>> result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 177, in __repr__
    return repr(sql_util._repr_row(self))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 483, in __repr__
    ", ".join(trunc(value) for value in self.row),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 946, in process
    value = bytes(value)
TypeError: cannot convert 'cx_Oracle.LOB' object to bytes
```

I will try `type_coerce` and your patch and let you know how that goes. I don't have high hopes for `type_coerce`, since none of the cx_Oracle types resolve directly to `LONG_BINARY`.

**Comment by meshantz** [comment] 2021-01-04 19:43
`type_coerce` _does_ work. Guess I didn't understand something there.
```python
>>> from sqlalchemy import type_coerce, BINARY
>>> ins = models.example1.insert().values(**data).returning(models.example1.c.thing, type_coerce(models.example1.c.image_data, BINARY))
>>> with db.connection() as cx:
...   result = cx.execute(ins).fetchone()
... 
>>> result
('some text', b'\xde\xad\xbe\xef')
```

**Comment by zzzeek** [comment] 2021-01-04 19:49
I think cx_Oracle considers  cx_Oracle.Binary and LONG_BINARY to be similar enough.  in recent years it has been a lot more forgiving about its type system.

given we are trying to minimize changes to 1.3 and especially that we just had to do an emergency release for another Oracle patch that had unintended side effects, as you have type_coerce() working as a workaround now I will target this for the 1.4 series that's still in beta.

**Comment by meshantz** [comment] 2021-01-04 19:56
I can appreciate that, and I'm glad to have the workaround.

The patch also has the desired effect.

As to your earlier comment about cx_Oracle returning actual result sets, I also don't know. I'm stuck on 10g/11g for now, which certainly won't support anything newer anyway. Maybe someday (fingers crossed).

Thanks again for your speedy assistance! Very much appreciated.

**Comment by meshantz** [comment] 2021-01-04 21:07
Hmm...

I realize I only asked about insert, but the workaround using `type_coerce` doesn't seem to work for updates. I haven't dug very far into it yet, but this happens:
```python
>>> data["thing"] = "some text 2"
>>> upd = models.example1.update().values(**data).where(models.example1.c.rid==12).returning(models.example1.c.rid, type_coerce(models.example1.c.image_data, BINARY).label("image_data"))
>>> with db.connection() as cx:
...   result = cx.execute(upd).fetchone()
... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 747, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'server_default'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/oracle/base.py", line 821, in __init__
    super(OracleCompiler, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 592, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2647, in visit_update
    update_stmt, self.returning or update_stmt._returning
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/oracle/base.py", line 945, in returning_clause
    if self.isupdate and isinstance(column.server_default, Computed):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 758, in __getattr__
    replace_context=err,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'server_default'
```

**Comment by zzzeek** [comment] 2021-01-04 21:37
that would actually be a different bug.  still fails if you remove the .label() call ?

**Comment by meshantz** [comment] 2021-01-04 21:40
Yes, it still fails that way. Only differs in the Attribute error at the end:
```python
AttributeError: Neither 'TypeCoerce' object nor 'Comparator' object has an attribute 'server_default'
```

I guess that is a different bug, though the patch you propose here side-steps it I believe.

**Comment by zzzeek** [comment] 2021-01-04 22:05
that error looks to be specific to SQLAlchemy 1.4.  Can you run on SQLAlchemy 1.3?

**Comment by zzzeek** [comment] 2021-01-04 22:08
hmm nevermind

**Comment by zzzeek** [comment] 2021-01-04 22:25
#5813 is a trivial fix so that will be merged to the 1.3 branch and master and will be next 1.3 release, so the type_coerce() workaround will be usable for you in the near term.

if you want to patch it for now, it's just this line:

```diff
diff --git a/lib/sqlalchemy/dialects/oracle/base.py b/lib/sqlalchemy/dialects/oracle/base.py
index a072376a3..c476554bd 100644
--- a/lib/sqlalchemy/dialects/oracle/base.py
+++ b/lib/sqlalchemy/dialects/oracle/base.py
@@ -976,6 +976,7 @@ class OracleCompiler(compiler.SQLCompiler):
         ):
             if (
                 self.isupdate
+                and isinstance(column, sa_schema.Column)
                 and isinstance(column.server_default, Computed)
                 and not self.dialect._supports_update_returning_computed_cols
             ):

```

**Comment by meshantz** [comment] 2021-01-05 14:14
Great! Thanks.
I was also able to monkey patch the `Label` and `TypeCoerce` objects with a `server_default` property:
```python
>>> patchit = type_coerce(models.example1.c.image_data, BINARY).label("image_data")
>>> patchit.server_default = None
>>> upd = models.example1.update().values(**data).where(models.example1.c.rid==12).returning(models.example1.c.rid, patchit)
```

So I'll definitely get by until I see another release.

**Comment by sqla-tester** [comment] 2021-01-28 16:05
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Allow Oracle CLOB/NCLOB/BLOB in returning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2518

**Comment by zzzeek** [comment] 2021-01-28 17:12
the MCVE you have at https://github.com/sqlalchemy/sqlalchemy/issues/5812#issuecomment-754219595 is not the same error you have in https://github.com/sqlalchemy/sqlalchemy/issues/5812#issue-778163195.   I can't reproduce "ORA-24813: cannot send or receive an unsupported LOB" on this side right now.

**Comment by zzzeek** [comment] 2021-01-28 17:52
OK so I can fix "TypeError: cannot convert 'cx_Oracle.LOB' object to bytes" for 1.3 and 1.4, that happens all the time here.     I have nothing at the moment for your ORA-24813 case, and also "returning" of a BLOB/CLOB fails in all cases now, so I don't get how you had "works fine" if you are doing returning for just the BLOB column.

**Comment by sqla-tester** [comment] 2021-01-28 18:26
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Allow Oracle CLOB/NCLOB/BLOB in returning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2519

**Comment by zzzeek** [comment] 2021-01-28 18:57
so I'm going to fix the easy typeerror here, that will close this issue.  IF you can provide a reproducer for ORA-24813  please open a new issue with the MCVE for that, thanks!

**Closed** 2021-01-28 22:18 UTC
Labels: external driver issues, oracle, use case
