### ISSUE TITLE
Incorrect ON Clause when joining aliased classes using a relationship defined using primaryjoin argument

### ISSUE THREAD

**Issue by gustavo-delfosim** [sqlalchemy/sqlalchemy#8575] opened 2022-09-25 18:15 UTC
### Describe the bug

Define tables `A` and `B` with a relationship defined as `A.bs = relationship("B", primaryjoin="foreign(B.a_id) == remote(A.id)")`.

Trying to query then with `aliased` classes results in a query with an incorrect join condition:
```py
a_alias = aliased(A)
b_alias = aliased(B)
query = select(a_alias, b_alias).join(a_alias.bs.of_type(b_alias))

print(query)
SELECT a_1.id, b_1.id AS id_1, b_1.a_id 
FROM a AS a_1
JOIN b AS b_1 ON b_1.a_id = a.id
```
The rendered join incorrectly references table `a` in its `ON` clause, which is the non-aliased name of the table related to class `A`. It should be `b_1.a_id = a_1.id` instead.

### To Reproduce

```python
from sqlalchemy import Column, ForeignKey, Integer, create_engine, select
from sqlalchemy.orm import Session, aliased, declarative_base, relationship

Base = declarative_base()

class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    bs = relationship(
        "B",
        primaryjoin="foreign(B.a_id) == remote(A.id)",
    )

class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))


engine = create_engine("sqlite://")
Base.metadata.create_all(engine)

session = Session(engine)

a_alias = aliased(A)
b_alias = aliased(B)

query = select(a_alias, b_alias).join(a_alias.bs.of_type(b_alias))
session.execute(query).all()
```

### Error

```
Traceback (most recent call last):
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: a.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gustavo/Gustavo/random/sqlalchemy_aliased_primaryjoin_relationship.py", line 36, in <module>
    session.scalars(query).all()
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/gustavo/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: a.id
[SQL: SELECT b_1.id, b_1.a_id 
FROM a AS a_1 JOIN b AS b_1 ON b_1.a_id = a.id]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
``` 

### Versions

- **OS:** Ubuntu 22.04.1 LTS
- **Python:** 3.10.4
- **SQLAlchemy:** 1.4.41
- **Database:** sqlite-3.38.3
- **DBAPI:** sqlite (but I also got the same problem using psycopg2)

### Additional context

Removing the `primaryjoin` clause in the `relationship` definition of `A.bs` gives the right result.

**Comment by zzzeek** [comment] 2022-09-25 18:33
the incorrect query here is not the bug, as the relationship is mis-configured.   The duplicate here is that the join condition you have should emit a warning, noting that it's wrong.   So this is a dupe of #7094.

With any A/B relationship, all relationships on "A" will by definition mark "remote" as columns that are on "B".   "remote()" as an explicit annotation is not useful for a relationship that isn't joining a table to itself.

**Closed by zzzeek** 2022-09-25 18:33 UTC
Labels: duplicate, orm

**Comment by sqla-tester** [comment] 2022-09-25 18:57
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**warn for local-only column in remote side** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4101

**Comment by sqla-tester** [comment] 2022-09-25 18:57
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**warn for local-only column in remote side** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4102

**Comment by zzzeek** [comment] 2022-09-25 19:30
that fix has shown that I made this exact same error in some very old mappings in our test suite!   Back when remote_side used to confuse me.  (and I created it).

**Comment by gustavo-delfosim** [comment] 2022-09-26 13:22
@zzzeek Thanks for explaining the correct usage of  `remote`. I will fix my code to correctly express the `relationship`.
The proposed warning will be very helpful.

> `remote()` as an explicit annotation is not useful for a relationship that isn't joining a table to itself.

I believe it would be very helpful to have something like the above added to the [docs of `remote()`](https://docs.sqlalchemy.org/en/14/orm/relationship_api.html#sqlalchemy.orm.remote), too.

**Comment by zzzeek** [comment] 2022-09-26 13:26
sure, though `remote()` is supposed to be this little used function people usually don't know about.   so why are people finding it so much?  likely because we mention it in other error messages, though if those messages only emit specifically to self-ref relationships, that's fine.

how did you come to be using `remote()` here?

**Comment by zzzeek** [comment] 2022-09-26 13:29
OK... remote is also called for, for very elaborate join conditions that refer to tables outside of that of the two mapped classes.  

so the doc is more like, "remote should never refer to columns on the parent table that are not mapped by the child table".  which is not very simple to understand.
