### ISSUE TITLE
consider restoring 1.3's "begin_nested() returns root transaction" for non-future mode

### ISSUE THREAD

**Issue by craigds** [sqlalchemy/sqlalchemy#6408] opened 2021-04-30 03:56 UTC
**Describe the bug**

If I use `Connection.begin_nested()` as a contextmanager inside an implicit transaction, I would expect that the outer implicit transaction shoudl be committed after the savepoint is released.

However, the savepoint is released as expected and then the transaction is rolled back.

This is a regression in 1.4.x - my snippet below works fine in 1.3.23.

**To Reproduce**

Here I inserted a row inside a `begin_nested` contextmanager. This is the only thing in the transaction. I would expect that the transaction is then committed.

I then use a separate connection to verify that the original transaction was committed - and it wasn't! Log output shows that the original transaction was rolled back instead.

```python
>>> import logging
>>> logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)
>>>
>>> with engine.connect() as conn:
...     with conn.begin_nested():
...         conn.execute("insert into testtable (txt) values ('it worked!');")
... with engine.connect() as conn:
...     if conn.scalar("select txt from testtable limit 1") is None:
...         print("it didn't work! no such row")
...
...
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): BEGIN (implicit)
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): SELECT 1
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): [cached since 2.302s ago] {}
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): COMMIT
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): BEGIN (implicit)
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): SAVEPOINT sa_savepoint_1
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): [no key 0.00055s] {}
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): insert into testtable (txt) values ('it worked!');
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): [raw sql] {}
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): RELEASE SAVEPOINT sa_savepoint_1
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): [no key 0.00058s] {}
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): ROLLBACK
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): BEGIN (implicit)
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): SELECT 1
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): [cached since 2.311s ago] {}
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): COMMIT
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): select txt from testtable limit 1
kx[1339.140185600350016]: INFO: sqlalchemy.engine.Engine base(132): [raw sql] {}
it didn't work! no such row
```

**Versions.**
 - OS: Ubuntu 18.04 LTS
 - Python: 2.7.17
 - SQLAlchemy: 1.4.12
 - Database: `PostgreSQL 10.16 (Debian 10.16-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`
 - DBAPI: psycopg2 `2.8.6 (dt dec pq3 ext lo64)`

**Have a nice day!**

you too! thanks for sqlalchemy, it is boss

**Comment by zzzeek** [comment] 2021-04-30 13:29
I still have to decide if I'm going to change this behavior or not, the bug is that this is a behavioral change that wasnt documented and is not emitting a warning, and additionally that the docs in 1.3 are wrong, the docs in 1.4 are wrong too.  and overall, while I have hundreds of different transactional combinations tested, none of them apparently ever tested this.   so lots of bugs all around but at the core of it, you should be calling connection.begin() before you call begin_nested() since that's what the usage model is based around.

in 1.3, your begin_nested() is not using a savepoint at all, it's just defaulting to doing the same thing as connection.begin(), which is part of 1.3's "automatically guess for everything" behavior, which is fine, but there's no tests otherwise this change wouldn't have passed silently.

1.4 is doing more of the "future" style "commit as you go" thing, which you don't have access towards if you didn't set the "future" flag, so that suggests if future isn't set we should probably have begin_nested() silently decide to return you a non-savepoint transaction but that seems like a big change now that we've released.   but there's no way for you to commit that transaction in 1.4 right now unless you use future mode, so...changing it might be safe.

So steps I see are:

1. for your side, you should use connection.begin() before calling begin_nested().
2. in 1.4, if future mode isn't set I might consider just making this do what 1.3 does but I'm going to have it emit a warning for sure that this pattern is 
3. if future mode is set, this is "commit as you go" and it's fine, you would call conn.commit() to commit the transaction.

**Comment by zzzeek** [comment] 2021-04-30 14:58
please try to see if we can do #6288 as we do this one if possible.

**Comment by sqla-tester** [comment] 2021-05-02 14:21
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**restore legacy begin_nested()->root transaction behavior** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2799

**Comment by zzzeek** [comment] 2021-05-02 14:22
OK so you were correct, this was fully a regression since the goal of engine.Connection was to remain 100% identical to 1.3's behavior and the future.Connection is where any behavioral changes were to occur.   Added a lot of docs.

**Closed** 2021-05-02 15:45 UTC
Labels: bug, engine, regression

**Comment by craigds** [comment] 2021-05-02 19:55
thanks! The fix sounds good, especially the deprecation warning you added.


I had been assuming the 1.3 behaviour was intentional - it makes `begin_nested()` behave like django's `transaction.atomic`. 

But while looking into this I realised in _most_ cases we don't really need savepoints and should be using `conn.begin()` instead (turns out it can be nested safely and the inner calls just noop 👍 )

In _some_ cases we do need savepoints and will need an equivalent for the old behaviour, but I can write that myself without much trouble.
