### ISSUE TITLE
sqlite supports UPDATE..FROM

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8356] opened 2022-08-05 16:19 UTC
https://www.sqlite.org/lang_update.html

see if we can flip this on and not spend too much time on it, lots of tests will light up if we add the method so should be quick

**Comment by CaselIT** [comment] 2022-08-12 09:34
this is a duplicate of #7185

**Closed by CaselIT** 2022-08-12 09:34 UTC
Labels: sqlite, use case
