### ISSUE TITLE
[docs.sqlalchemy.org] Search keeps crashing my browser

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#5790] opened 2020-12-20 16:34 UTC
When I use the search functionality on docs.sqlalchemy.org it typically starts displaying a huge number of results which in only a couple of seconds results in using GBs of RAM, which then results in my browser crashing when the system runs out of memory.

I guess an obvious solution would be to implement pagination, rather than loading unlimited amount of results in the page.

Firefox on Linux.

**Comment by zzzeek** [comment] 2020-12-20 17:21
hey there -

yes I have the same problem but unfortunately it's not in my control.  I recommend you open an issue with [sphinx](https://github.com/sphinx-doc/sphinx).    it's JS I have no visibility into.

**Comment by Dreamsorcerer** [comment] 2020-12-20 17:23
I see, I guess I just never encountered the issue anywhere else, because most project don't have so many results.

**Comment by CaselIT** [comment] 2020-12-20 19:20
for what it's worth, I can't reproduce with firefox (v85) on windows

**Comment by zzzeek** [comment] 2020-12-20 19:23
It happens for me on firefox linux, but not on chrome.   it is very annoying.

**Comment by zzzeek** [comment] 2020-12-20 19:24
it doesn't help that there's a totally different product called "sphinxsearch" which obliterates any googling one might do for this issue.

**Comment by CaselIT** [comment] 2020-12-20 19:30
with what search phrases does it happen?

**Comment by zzzeek** [comment] 2020-12-20 19:37
typically, any result that takes a long time to load, like "query", the "Searching..." title will have the ellipses blinking.  if i click a link while they are blinking and results are still being loaded, that's when i might have a crash.

right now, it's just being slow when i click a link but is loading.  ive been upgrading firefox and I suspect this might ultimately be a firefox issue.

**Comment by zzzeek** [comment] 2020-12-20 19:38
this is firefox 82.0.2 and it doesn't seem to have the problem very much.

**Comment by CaselIT** [comment] 2020-12-20 19:43
I think it may be a ff issue on linux

**Comment by Dreamsorcerer** [comment] 2020-12-20 20:20
I just encountered the issue when searching for 'asyncio' here, for example: https://docs.sqlalchemy.org/en/14/search.html?q=asyncio&check_keywords=yes&area=default
Though it happens on many search terms.

It basically freezes and eventually crashes due to the memory usage while the search results are loading in. I can see the memory sky-rocketing as it loads. I have <2GB of free RAM, and no swap space, which is why it completely fails so reliably for me.

I'm sure there's opportunity for Firefox to improve memory usage on something, but the fact that it just keeps loading such a massive list of results is probably not helping. I think it took a little under 5 seconds of loading search results in that example to reach 2GB of RAM usage and hit my limit.

**Comment by Dreamsorcerer** [comment] 2021-02-11 14:26
Hopefully, this has been fixed in https://github.com/sphinx-doc/sphinx/pull/8868
Thanks to a couple of Firefox developers digging through.

**Comment by CaselIT** [comment] 2021-02-11 14:39
I guess we can close this?

**Comment by zzzeek** [comment] 2021-02-11 14:45
we would have to set the min sphinx version in  conf.py and rebuild, no ?

**Comment by Dreamsorcerer** [comment] 2021-02-11 14:46
I couldn't see any direct dependency on sphinx in the sqlalchemy repo, so not sure if you'll need to manually update to the latest version, or if it'll happen automatically once there's a new release?

**Comment by zzzeek** [comment] 2021-02-11 16:15
it would go here: https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/conf.py#L28

**Comment by Dreamsorcerer** [comment] 2021-02-11 16:30
Cool, I'll keep an eye open for when a new release is out then.

**Closed** 2021-02-15 18:14 UTC
Labels: documentation, motivated volunteers requested, third party integration issues

**Comment by Dreamsorcerer** [comment] 2021-02-16 17:04
Yep, this has fixed it for me, and the search results load so much faster now.

**Comment by zzzeek** [comment] 2021-02-16 18:20
yeah I tried it and it feels snappier, glad they fixed it
