### ISSUE TITLE
Can't make do_orm_execute filter queries containing union_all/with_polymorphic

### ISSUE THREAD

**Issue by eskilandreen** [sqlalchemy/sqlalchemy#6111] opened 2021-03-22 07:06 UTC
**Describe your question**

I'm porting some 1.3 code that uses soft deletes à la https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery to 1.4 and trying to use https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html to transparently filter out objects marked `deleted=True`. This seems to work well except when using `Query.union_all` over queries that have `with_polymorphic("*")`. In those cases the filtering doesn't seem to work and objects that have been marked as deleted are still returned.

Is there anything else I need to add to `_add_filtering_criteria` to include these queries in the filter?

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**

Here is runnable example. The final assertion fails unexpectedly, apparently due to the addition of `with_polymorphic("*")`.

```python
from sqlalchemy import Column, Integer, String, Boolean, select, event, create_engine
from sqlalchemy.orm import Session, declarative_base, with_loader_criteria

engine = create_engine("sqlite+pysqlite:///:memory:", echo=True, future=True)

Base = declarative_base()

class Film(Base):
    __tablename__ = 'films'

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    deleted = Column(Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"Film(title='{self.title}')"

Base.metadata.create_all(engine)

@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if (
        not execute_state.is_column_load
        and not execute_state.is_relationship_load
        and not execute_state.execution_options.get("include_deleted", False)
    ):
        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                Film,
                lambda cls: cls.deleted == False,
                include_aliases=True,
            )
        )

with Session(engine) as session:
    film1 = Film(title="film1")
    film2 = Film(title="film2")

    session.add(film1)
    session.add(film2)
    session.commit()

    # Check that films exist
    query1 = session.query(Film).filter_by(id=film1.id)
    query2 = session.query(Film).filter_by(id=film2.id)

    assert query1.one_or_none() == film1
    assert query2.one_or_none() == film2

    # Check that films exist with a union query
    union_query = query1.union_all(query2).order_by(Film.title)
    assert union_query.all() == [film1, film2]

    # Delete both films
    film1.deleted = True
    film2.deleted = True
    session.commit()

    # Check that films no longer exist
    assert query1.one_or_none() is None
    assert query2.one_or_none() is None
    assert union_query.all() == []

    # Check that films no longer exist but add with_polymorphic
    query1_p = session.query(Film).with_polymorphic("*").filter_by(id=film1.id)
    query2_p = session.query(Film).with_polymorphic("*").filter_by(id=film2.id)
    union_query_p = query1_p.union_all(query2_p).order_by(Film.title)
    assert query1_p.one_or_none() is None
    assert query2_p.one_or_none() is None
    assert union_query_p.all() == [] # Fails!!
```

**Complete stack trace, if applicable**

```
Traceback (most recent call last):
  File "/home/eskil/code/sqlalchemy/fisk.py", line 70, in <module>
    assert union_query_p.all() == [] # Fails!!
AssertionError
```

**Versions**
 - OS: Arch Linux rolling release, kernel version 5.11.6-arch1-1
 - Python: Python 3.9.2
 - SQLAlchemy: 1.4.2 as well as current master (a1782160de)
 - Database: sqlite 3.35.1-1 as well as PostgreSQL 13.1
 - DBAPI: pysqlite 2.6.0 as well as psycopg2 2.8.6

**Have a nice day!**

Have a _wonderful_ day!

**Comment by zzzeek** [comment] 2021-03-22 16:30
hey there -

I can confirm your assertion fails at the end.    I haven't looked deeply yet, however your assertion passes if I use the [modern form of with_polymorphic](https://docs.sqlalchemy.org/en/14/orm/inheritance_loading.html?highlight=with_polymorphic#using-with-polymorphic):

```

    f1 = with_polymorphic(Film, "*")
    query1_p = session.query(f1).filter_by(id=film1.id)
    query2_p = session.query(f1).filter_by(id=film2.id)

    union_query_p = query1_p.union_all(query2_p).order_by(Film.title)
    assert query1_p.one_or_none() is None
    assert query2_p.one_or_none() is None
    assert union_query_p.all() == [] # does not fail, but i didnt check if the answer is right
```

the query.with_polymorphic() method is deprecated, which is because it is deeply complicated, so if you can do what you need with standalone with_polymorphic(), I would recommend migrating to that pattern first before with_loader_criteria().   I would look into documenting this and emitting a warning or error when with_loader_criteria() is combined with it since I'd rather not get into changing query.with_polymorphic().

**Comment by eskilandreen** [comment] 2021-03-23 11:00
Yes, using sqlalchemy.orm.with_polymorphic (and updating some of the filters accordingly) works nicely in my real-world case. I hadn't realized that Query.with_polymorphic has been deprecated. Thanks for pointing that out!

**Comment by zzzeek** [comment] 2021-03-23 14:09
this needs to be documented

**Comment by sqla-tester** [comment] 2021-03-23 14:24
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**warn / document for Query.with_polymorphic() with with_loader_criteria()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2667

**Closed** 2021-03-23 15:21 UTC
Labels: documentation, orm
