### ISSUE TITLE
Empty array of enum can not be queried

### ISSUE THREAD

**Issue by ThalusA** [sqlalchemy/sqlalchemy#7592] opened 2022-01-20 19:37 UTC
### Describe the bug

If you query a model with an empty list of enum you get an error.
I think the bug has emerged from this issue: #7418 

### To Reproduce

```python
Query an empty list of enum from a defined model
```

### Error

```
# Copy complete stack trace and error message here, including SQL log output if applicable.
Traceback (most recent call last):
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1657, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/resources/trials.py", line 160, in get
    trial: Trial | None = query_trials(session).filter(Trial.nct_id == nct_id).scalar()
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/orm/query.py", line 2879, in scalar
    ret = self.one()
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/orm/query.py", line 2856, in one
    return self._iter().one()
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/engine/result.py", line 1407, in one
    return self._only_one_row(
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/engine/result.py", line 558, in _only_one_row
    row = onerow(hard_close=True)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/engine/result.py", line 1271, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/engine/result.py", line 1674, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/engine/result.py", line 392, in <listcomp>
    return [make_row(row) for row in rows]
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/array.py", line 382, in process
    return super_rp(
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/array.py", line 361, in process
    return self._proc_array(
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/array.py", line 313, in _proc_array
    return collection(itemproc(x) for x in arr)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/dialects/postgresql/array.py", line 313, in <genexpr>
    return collection(itemproc(x) for x in arr)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1768, in process
    value = self._object_value_for_elem(value)
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1659, in _object_value_for_elem
    util.raise_(
  File "/home/thalusa/Documents/klineo/klineo-trials-migrator/venv/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
LookupError: '' is not among the defined enum values. Enum name: fields. Possible values: brief_title, criteria, minimum_age, ..., description
``` 

### Versions

- OS: Linux thalusa-pc 5.15.14-200.fc35.x86_64 #1 SMP Tue Jan 11 16:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 
- Python: Python 3.10.1
- SQLAlchemy: 1.4.30
- Database: PostgreSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

**Comment by zzzeek** [comment] 2022-01-20 19:40
likely a dupe of #7590

**Closed** 2022-01-20 20:02 UTC
Labels: duplicate, regression, requires triage, array of enums
