### ISSUE TITLE
MSSQL: Refelection of temporay table fails if collation of database is different than collation of 'master'

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [sqlalchemy/sqlalchemy#8035] opened 2022-05-18 15:21 UTC
### Describe the bug

When reflecting a _temp_ table in MSSQL where the collation of the db in the connection string is different than the collation 
 on master an error occurs.

### To Reproduce

```python
from sqlalchemy import Table, MetaData
import pandas as pd


df = pd.DataFrame({"a" : ["z", "y"], "b" : ["g", "k"]}) # used to create very simple table
table_name1 = "##mytable1"
table_name2 = "##mytable2"


# The two engines have same server define but different DBs in conn string

with engine_1.connect() as conn: # engine with collation "Latin1_General_CI_AS"
    df.to_sql(table_name1,conn)
    t = Table(table_name1,MetaData(), autoload_with = engine_1)
    
with engine_2.connect() as conn: # engine with collation "Danish_Norwegian_CI_AS"
    df.to_sql(table_name2,conn)
    t = Table(table_name2,MetaData(), autoload_with = engine_2)
```

### Error

```
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1801                 if not evt_handled:
-> 1802                     self.dialect.do_execute(
   1803                         cursor, statement, parameters, context

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
    731     def do_execute(self, cursor, statement, parameters, context=None):
--> 732         cursor.execute(statement, parameters)
    733 

ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot resolve the collation conflict between "Latin1_General_CI_AS" and "Danish_Norwegian_CI_AS" in the equal to operation. (468) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)')

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22652/4197897831.py in <module>
     13 with engine_2.connect() as conn: # engine with collation "Danish_Norwegian_CI_AS"
     14     df.to_sql(table_name2,conn)
---> 15     t = Table(table_name2,MetaData(), autoload_with = engine_2)

<string> in __new__(cls, *args, **kw)

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\util\deprecations.py in warned(fn, *args, **kwargs)
    307                         stacklevel=3,
    308                     )
--> 309             return fn(*args, **kwargs)
    310 
    311         doc = fn.__doc__ is not None and fn.__doc__ or ""

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\sql\schema.py in __new__(cls, *args, **kw)
    605             except Exception:
    606                 with util.safe_reraise():
--> 607                     metadata._remove_table(name, schema)
    608 
    609     def __init__(self, *args, **kw):

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
     68             self._exc_info = None  # remove potential circular references
     69             if not self.warn_only:
---> 70                 compat.raise_(
     71                     exc_value,
     72                     with_traceback=exc_tb,

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    205 
    206         try:
--> 207             raise exception
    208         finally:
    209             # credit to

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\sql\schema.py in __new__(cls, *args, **kw)
    600             metadata._add_table(name, schema, table)
    601             try:
--> 602                 table._init(name, metadata, *args, **kw)
    603                 table.dispatch.after_parent_attach(table, metadata)
    604                 return table

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\sql\schema.py in _init(self, name, metadata, *args, **kwargs)
    675         # circular foreign keys
    676         if autoload:
--> 677             self._autoload(
    678                 metadata,
    679                 autoload_with,

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\sql\schema.py in _autoload(self, metadata, autoload_with, include_columns, exclude_columns, resolve_fks, _extend_on)
    710         insp = inspection.inspect(autoload_with)
    711         with insp._inspection_context() as conn_insp:
--> 712             conn_insp.reflect_table(
    713                 self,
    714                 include_columns,

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\reflection.py in reflect_table(self, table, include_columns, exclude_columns, resolve_fks, _extend_on)
    772         cols_by_orig_name = {}
    773 
--> 774         for col_d in self.get_columns(
    775             table_name, schema, **table.dialect_kwargs
    776         ):

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\reflection.py in get_columns(self, table_name, schema, **kw)
    495 
    496         with self._operation_context() as conn:
--> 497             col_defs = self.dialect.get_columns(
    498                 conn, table_name, schema, info_cache=self.info_cache, **kw
    499             )

<string> in get_columns(dialect, connection, tablename, schema, **kw)

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\reflection.py in cache(fn, self, con, *args, **kw)
     53     ret = info_cache.get(key)
     54     if ret is None:
---> 55         ret = fn(self, con, *args, **kw)
     56         info_cache[key] = ret
     57     return ret

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\dialects\mssql\base.py in wrap(dialect, connection, tablename, schema, **kw)
   2583     def wrap(dialect, connection, tablename, schema=None, **kw):
   2584         dbname, owner = _owner_plus_db(dialect, schema)
-> 2585         return _switch_db(
   2586             dbname,
   2587             connection,

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\dialects\mssql\base.py in _switch_db(dbname, connection, fn, *arg, **kw)
   2607             )
   2608     try:
-> 2609         return fn(*arg, **kw)
   2610     finally:
   2611         if dbname and current_db != dbname:

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\dialects\mssql\base.py in get_columns(self, connection, tablename, dbname, owner, schema, **kw)
   3233         )
   3234 
-> 3235         c = connection.execution_options(future_result=True).execute(s)
   3236 
   3237         cols = []

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\base.py in execute(self, statement, *multiparams, **params)
   1287             )
   1288         else:
-> 1289             return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
   1290 
   1291     def _execute_function(self, func, multiparams, params, execution_options):

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\sql\elements.py in _execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    323     ):
    324         if _force or self.supports_execution:
--> 325             return connection._execute_clauseelement(
    326                 self, multiparams, params, execution_options
    327             )

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\base.py in _execute_clauseelement(self, elem, multiparams, params, execution_options)
   1479             linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1480         )
-> 1481         ret = self._execute_context(
   1482             dialect,
   1483             dialect.execution_ctx_cls._init_compiled,

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1843 
   1844         except BaseException as e:
-> 1845             self._handle_dbapi_exception(
   1846                 e, statement, parameters, cursor, context
   1847             )

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2024                 util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2025             elif should_wrap:
-> 2026                 util.raise_(
   2027                     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2028                 )

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    205 
    206         try:
--> 207             raise exception
    208         finally:
    209             # credit to

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1800                             break
   1801                 if not evt_handled:
-> 1802                     self.dialect.do_execute(
   1803                         cursor, statement, parameters, context
   1804                     )

~\Miniconda3\envs\norden_prefect\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
    730 
    731     def do_execute(self, cursor, statement, parameters, context=None):
--> 732         cursor.execute(statement, parameters)
    733 
    734     def do_execute_no_params(self, cursor, statement, context=None):

ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot resolve the collation conflict between "Latin1_General_CI_AS" and "Danish_Norwegian_CI_AS" in the equal to operation. (468) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)')
[SQL: SELECT tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], tempdb.[INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME], sys.computed_columns.definition, sys.computed_columns.is_persisted, sys.identity_columns.is_identity, CAST(sys.identity_columns.seed_value AS NUMERIC) AS seed_value, CAST(sys.identity_columns.increment_value AS NUMERIC) AS increment_value 
FROM tempdb.[INFORMATION_SCHEMA].[COLUMNS] LEFT OUTER JOIN sys.computed_columns ON sys.computed_columns.object_id = object_id(tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] + CAST(? AS NVARCHAR(max)) + tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME]) AND sys.computed_columns.name = tempdb.[INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME] LEFT OUTER JOIN sys.identity_columns ON sys.identity_columns.object_id = object_id(tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] + CAST(? AS NVARCHAR(max)) + tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME]) AND sys.identity_columns.name = tempdb.[INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME] 
WHERE tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND tempdb.[INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) ORDER BY tempdb.[INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION]]
[parameters: ('.', '.', '##mytable2', 'dbo')]
(Background on this error at: https://sqlalche.me/e/14/f405)
``` 

### Versions

- OS: Windows 10
- Python: 3.8.8
- SQLAlchemy: 1.4.31
- Database: Microsoft SQL Server Enterprise (64-bit)14.0.3356.20
- DBAPI: pyodbc==4.0.32

**Comment by jvanasco** [comment] 2022-05-18 15:41
cc @gordthompson

**Comment by zzzeek** [comment] 2022-05-18 17:24
this information is a little scattered, @thomasfrederikhoeck can you please share examples of the database URLs you are using for your demonstration, thanks

**Comment by gordthompson** [comment] 2022-05-18 18:25
FWIW, this code does **not** reproduce the error:

```python
import sqlalchemy as sa

engine_1 = sa.create_engine(
    sa.engine.URL.create(
        "mssql+pyodbc",
        username="scott",
        password="tiger^5HHH",
        host="192.168.0.199",
        database="master",
        query={"driver": "ODBC Driver 17 for SQL Server"},
    )
)
engine_2 = sa.create_engine(
    sa.engine.URL.create(
        "mssql+pyodbc",
        username="scott",
        password="tiger^5HHH",
        host="192.168.0.199",
        database="issue_8035",
        query={"driver": "ODBC Driver 17 for SQL Server"},
    )
)

with engine_1.connect() as conn:
    master_collation = conn.exec_driver_sql(
        "SELECT collation_name FROM sys.databases WHERE name='master'"
    ).scalar()
    print(master_collation)  # SQL_Latin1_General_CP1_CI_AS
    other_collation = conn.exec_driver_sql(
        "SELECT collation_name FROM sys.databases WHERE name='issue_8035'"
    ).scalar()
    print(other_collation)  # Danish_Norwegian_CI_AS

table_1 = sa.Table("table_1", sa.MetaData(), autoload_with=engine_2)
print(repr(table_1))
"""
Table('table_1', MetaData(), 
    Column('id', INTEGER(), table=<table_1>, primary_key=True, nullable=False), 
    Column('txt', VARCHAR(length=50, collation='Danish_Norwegian_CI_AS'), table=<table_1>, nullable=False), 
    schema=None
)
"""
```

**Comment by gordthompson** [comment] 2022-05-18 20:19
I am able to reproduce the issue. The problem is not with the collation of the `master` database *per se*, it is actually the collation of the `tempdb` database, but they are likely always going to be the same.

```python
import sqlalchemy as sa

engine_1 = sa.create_engine(
    sa.engine.URL.create(
        "mssql+pyodbc",
        username="scott",
        password="tiger^5HHH",
        host="192.168.0.199",
        database="tempdb",
        query={"driver": "ODBC Driver 17 for SQL Server"},
    )
)
engine_2 = sa.create_engine(
    sa.engine.URL.create(
        "mssql+pyodbc",
        username="scott",
        password="tiger^5HHH",
        host="192.168.0.199",
        database="issue_8035",
        query={"driver": "ODBC Driver 17 for SQL Server"},
    )
)

with engine_1.begin() as conn:
    tempdb_collation = conn.exec_driver_sql(
        "SELECT collation_name FROM sys.databases WHERE name='tempdb'"
    ).scalar()
    print(tempdb_collation)  # SQL_Latin1_General_CP1_CI_AS
    other_collation = conn.exec_driver_sql(
        "SELECT collation_name FROM sys.databases WHERE name='issue_8035'"
    ).scalar()
    print(other_collation)  # Danish_Norwegian_CI_AS

with engine_2.begin() as conn:
    conn.exec_driver_sql("DROP TABLE IF EXISTS ##tmp")
    conn.exec_driver_sql("CREATE TABLE ##tmp (id int primary key, txt varchar(50))")

    tmp = sa.Table("##tmp", sa.MetaData(), autoload_with=conn)
"""
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', 
'[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" 
and "Danish_Norwegian_CI_AS" in the equal to operation. (468) (SQLExecDirectW); 
[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
Statement(s) could not be prepared. (8180)')
"""
```

**Comment by sqla-tester** [comment] 2022-05-18 20:20
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Use collation in reflection in MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3848

**Comment by sqla-tester** [comment] 2022-05-20 15:18
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Use collation in reflection in MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3852

**Closed** 2022-05-21 14:04 UTC
Labels: bug, SQL Server, reflection
