### ISSUE TITLE
TypeError when calling raw_connection() on engine instance with mysql+pyodbc dialect

### ISSUE THREAD

**Issue by ramprax** [sqlalchemy/sqlalchemy#7871] opened 2022-03-29 16:13 UTC
### Describe the bug

Getting the following error when calling `raw_connection()` on engine instance when using `mysql+pyodbc` dialect:

`TypeError: MySQLDialect._fetch_setting() missing 1 required positional argument: 'setting_name'`

Looks like the `connection` parameter is not being passed in [sqlalchemy/dialects/mysql/pyodbc.py line 92](https://github.com/sqlalchemy/sqlalchemy/blob/dba480ebaf89c0b5ea787661583de9da3928920f/lib/sqlalchemy/dialects/mysql/pyodbc.py#L92).

Probable one liner fix:
In [sqlalchemy/dialects/mysql/pyodbc.py line 92](https://github.com/sqlalchemy/sqlalchemy/blob/dba480ebaf89c0b5ea787661583de9da3928920f/lib/sqlalchemy/dialects/mysql/pyodbc.py#L92) needs to be changed
from: `            value = self._fetch_setting("character_set_client")`
to: `            value = self._fetch_setting(connection, "character_set_client")`

### To Reproduce

```python
from sqlalchemy import create_engine

engine = create_engine('mysql+pyodbc://<user>:<password>@<host>/<database>?driver=MySQL+ODBC+8.0+Unicode+Driver')

engine.raw_connection()
```

### Error

```
Traceback (most recent call last):
  File "C:\Users\rampr\PycharmProjects\optimusprime\src\OptimusPrime\Tests\repro_odbc_raw_connection_issue.py", line 4, in <module>
    engine.raw_connection()
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 3289, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 3256, in _wrap_pool_connect
    return fn()
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 679, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\event\attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\event\attr.py", line 343, in __call__
    fn(*args, **kw)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1691, in go
    return once_fn(*arg, **kw)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\engine\create.py", line 686, in first_connect
    dialect.initialize(c)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2709, in initialize
    self._connection_charset = self._detect_charset(connection)
  File "C:\Users\rampr\PycharmProjects\optimusprime\.venv\lib\site-packages\sqlalchemy\dialects\mysql\pyodbc.py", line 92, in _detect_charset
    value = self._fetch_setting("character_set_client")
TypeError: MySQLDialect._fetch_setting() missing 1 required positional argument: 'setting_name'
``` 

### Versions

- OS: Windows 10
- Python: Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
- SQLAlchemy: 1.4.32 (latest)
- Database: MySQL 8.0.26
- DBAPI: pyodbc 4.0.32 (latest)
- ODBC Driver: MySQL ODBC 8.0 Unicode Driver

**Comment by zzzeek** [comment] 2022-03-29 17:37
hey there -

ODBC for mysql is not really supported right now so I would suggest using a different driver.

**Comment by eusebiomarquesbenitez** [comment] 2022-04-06 14:45
Hi.
the Problem is when extract **character_set_connection** in the
File python3.X/site-packages/sqlalchemy/dialects/mysql/**pyodbc.py**
class **MySQLDialect_pyodbc** Function **_detect_charset**
set a fixed chartset or rewrite code with previus version:

`
class MySQLDialect_pyodbc(PyODBCConnector, MySQLDialect):
    supports_statement_cache = True
    colspecs = util.update_copy(MySQLDialect.colspecs, {Time: _pyodbcTIME})
    supports_unicode_statements = True
    execution_ctx_cls = MySQLExecutionContext_pyodbc

    pyodbc_driver_name = "MySQL"

    def _detect_charset(self, connection):
        """Sniff out the character set in use for connection results."""

        # Prefer 'character_set_results' for the current connection over the
        # value in the driver.  SET NAMES or individual variable SETs will
        # change the charset without updating the driver's view of the world.
        #
        # If it's decided that issuing that sort of SQL leaves you SOL, then
        # this can prefer the driver value.
        try:
            value = self._fetch_setting("character_set_client")
            if value:
                return value
        except Exception as e:
             rs = connection.execute("SHOW VARIABLES LIKE 'character_set%%'")
             opts = {row[0]: row[1] for row in self._compat_fetchall(rs)}
             for key in ("character_set_connection", "character_set"):
                if opts.get(key, None):
                   return opts[key]

        util.warn(
            "Could not detect the connection character set.  "
            "Assuming latin1."
        )
        return "latin1" 
`

**Comment by trankillity** [comment] 2022-04-26 05:46
> hey there -
> 
> ODBC for mysql is not really supported right now so I would suggest using a different driver.

Hi @zzzeek - I've just come across this issue as well with `mariadb` dialect as we are trying to use `pyodbc` as a driver due to the built in ability to handle credentials via `Trusted_Connection=yes;` connection string with Windows auth (and `gssapi` auth plugin on MariaDB). For our applications' use-case, we need the ability to **not** store these credentials anywhere, and to provide access to users based on their domain authentication.

I understand this bug is not a high priority, which is fine, but do you have any alternative suggestions to allow us to connect without needing to provide credentials directly?

**Comment by zzzeek** [comment] 2022-04-26 12:53
to be clear, the main reason I cant just commit a one liner is that I dont have a MySQL odbc setup here to test.  so if you can try the above patch and confirm it fixes all issues and you can use the driver fully, I can commit that.

**Comment by zzzeek** [comment] 2022-04-26 19:00
this is in fact a regression in 1.4.32 so you can use 1.4.31 for the moment.

i will push a fix for this but I dont have testing set up to see if anything else is not broken.

**Comment by sqla-tester** [comment] 2022-04-26 19:03
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**repair fetch_setting call in mysql pyodbc dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3812

**Comment by sqla-tester** [comment] 2022-04-26 19:03
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**repair fetch_setting call in mysql pyodbc dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3813

**Closed** 2022-04-26 20:52 UTC
Labels: bug, mysql, engine, regression, next release
