### ISSUE TITLE
The removal of the PyMySQL from the asyncmy dialect broke handling of PickleType columns

### ISSUE THREAD

**Issue by obsidian74** [sqlalchemy/sqlalchemy#7593] opened 2022-01-20 20:08 UTC
### Describe the bug

With the removal of the PyMySQL dependency from the asyncmy dialect in the 1.4.30 release, PickleType fields (and I suspect Binary fields in general) are no longer supported.  The driver attempts to find the `Binary` attribute of `AsyncAdapt_asyncmy_dbapi` and fails to do so.  This worked previously in 1.4.29.

### To Reproduce

```python
#!/usr/bin/env python

from sqlalchemy import Column, Integer, PickleType
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
import sys
import asyncio

DBBase = declarative_base()


class TestObject(DBBase):
    __tablename__ = "TEST_OBJECT"
    __table_args__ = {"mysql_engine": "InnoDB",
                      "mysql_charset": "utf8"}

id = Column(Integer, primary_key=True)
picklecolumn = Column(PickleType, nullable=False)


async def main(db_url):
    engine = create_async_engine(db_url, future=True)

session_maker_ = sessionmaker(bind=engine,
                              expire_on_commit=False,
                              class_=AsyncSession,
                              future=True)

async with engine.begin() as conn:
    await conn.run_sync(DBBase.metadata.create_all)

session = session_maker_()

blob_data = {"foo": "bar"}

test_object = TestObject()
test_object.picklecolumn = blob_data

session.add(test_object)

await session.commit()
await session.close()


if __name__ == "__main__":
    db_url = sys.argv[1]

    asyncio.run(main(db_url))
```

### Error

Traceback (most recent call last):
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1702, in _execute_context
context = constructor(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1021, in _init_compiled
processors = compiled._bind_processors
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
obj.__dict__[self.__name__] = result = self.fget(obj)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 901, in _bind_processors
return dict(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 901, in <genexpr>
return dict(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 906, in <genexpr>
bindparam.type._cached_bind_processor(self.dialect)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 686, in _cached_bind_processor
d["bind"] = bp = d["impl"].bind_processor(dialect)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1840, in bind_processor
impl_processor = self.impl.bind_processor(dialect)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 989, in bind_processor
DBAPIBinary = dialect.dbapi.Binary
AttributeError: 'AsyncAdapt_asyncmy_dbapi' object has no attribute 'Binary'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/tmp/sqlalchemybug/./test.py", line 49, in <module>
asyncio.run(main(db_url))
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
return future.result()
File "/tmp/sqlalchemybug/./test.py", line 42, in main
await session.commit()
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 576, in commit
return await greenlet_spawn(self.sync_session.commit)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
result = context.switch(value)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
self._transaction.commit(_to_root=self.future)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
self._prepare_impl()
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
self.session.flush()
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
self._flush(objects)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3502, in _flush
with util.safe_reraise():
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
compat.raise_(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
flush_context.execute()
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
rec.execute(self)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
util.preloaded.orm_persistence.save_obj(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
_emit_insert_statements(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1221, in _emit_insert_statements
result = connection._execute_20(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
return connection._execute_clauseelement(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
ret = self._execute_context(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1708, in _execute_context
self._handle_dbapi_exception(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
util.raise_(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1702, in _execute_context
context = constructor(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1021, in _init_compiled
processors = compiled._bind_processors
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
obj.__dict__[self.__name__] = result = self.fget(obj)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 901, in _bind_processors
return dict(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 901, in <genexpr>
return dict(
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 906, in <genexpr>
bindparam.type._cached_bind_processor(self.dialect)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 686, in _cached_bind_processor
d["bind"] = bp = d["impl"].bind_processor(dialect)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1840, in bind_processor
impl_processor = self.impl.bind_processor(dialect)
File "/tmp/.pyvenv/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 989, in bind_processor
DBAPIBinary = dialect.dbapi.Binary
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'AsyncAdapt_asyncmy_dbapi' object has no attribute 'Binary'
[SQL: INSERT INTO `TEST_OBJECT` (picklecolumn) VALUES (%s)]
[parameters: [{'picklecolumn': {'foo': 'bar'}}]]

### Versions

- OS: Linux
- Python: 3.10
- SQLAlchemy: 1.4.30
- Database: MariaDB
- DBAPI: asyncmy

**Comment by CaselIT** [comment] 2022-01-20 20:15
Thanks for the report. this is caused by the fix of https://github.com/sqlalchemy/sqlalchemy/issues/7567

@zzzeek I'm sure there are test for binary, how come they don't trip this?

**Comment by zzzeek** [comment] 2022-01-20 20:15
we have a test case already, and it fails.  so how did CI miss it

**Comment by zzzeek** [comment] 2022-01-20 20:15
```
x00sl\x07 ... (20941 characters truncated) ... ', 'pickled': <sqlalchemy.testing.pickleable.Foo object at 0x7f1ee4c06920>, 'mypickle': <sqlalchemy.testing.pickleable.Foo object at 0x7f1ee4c061a0>}]]
=============================================================== short test summary info ================================================================
FAILED test/sql/test_types.py::BinaryTest_mariadb+asyncmy_async_10_5_12::test_comparison - sqlalchemy.exc.StatementError: (builtins.AttributeError) '...
FAILED test/sql/test_types.py::BinaryTest_mariadb+asyncmy_async_10_5_12::test_round_trip - sqlalchemy.exc.StatementError: (builtins.AttributeError) '...
=======================
```

has backend set

**Comment by CaselIT** [comment] 2022-01-20 20:16
does it somehow only run on the main url?

**Comment by zzzeek** [comment] 2022-01-20 20:17
theory: the tox file was wrong:


```diff
diff --git a/tox.ini b/tox.ini
index def2108260..fad0c50758 100644
--- a/tox.ini
+++ b/tox.ini
@@ -102,7 +102,7 @@ setenv=
     py2{,7}-mysql: MYSQL={env:TOX_MYSQL_PY2K:{env:TOX_MYSQL:--db mysql}}
     mysql: EXTRA_MYSQL_DRIVERS={env:EXTRA_MYSQL_DRIVERS:--dbdriver mysqldb --dbdriver pymysql}
 
-    py3-mysql: EXTRA_MYSQL_DRIVERS={env:EXTRA_MYSQL_DRIVERS:--dbdriver mysqldb --dbdriver pymysql --dbdriver mariadbconnector --dbdriver asyncmy}
+    py3{,7,8,9,10,11}-mysql: EXTRA_MYSQL_DRIVERS={env:EXTRA_MYSQL_DRIVERS:--dbdriver mysqldb --dbdriver pymysql --dbdriver mariadbconnector --dbdriver asyncmy}
 
 
     mssql: MSSQL={env:TOX_MSSQL:--db mssql}

```

**Comment by zzzeek** [comment] 2022-01-20 20:20
so this could mean asyncmy is broken all over the place.  let's find out

**Comment by sqla-tester** [comment] 2022-01-20 20:25
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**re-enable tests for asyncmy; fix Binary** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3551

**Comment by sqla-tester** [comment] 2022-01-20 20:25
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**re-enable tests for asyncmy; fix Binary** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3552

**Closed** 2022-01-21 01:26 UTC
Labels: bug, mysql, regression, asyncio
