### ISSUE TITLE
SQLite and Postgresql have conflicting operator precedence for the string concat and math operators

### ISSUE THREAD

**Issue by StefanosChaliasos** [sqlalchemy/sqlalchemy#5375] opened 2020-06-04 09:23 UTC
**Describe the bug**
SQLAlchemy (on the latest master version) does not place correct parenthesis when using the `||` operator.

**Expected behavior**
```python
expr = type_coerce(Author.id + literal(1), types.String)
f = (Author.first_name + expr).label('f')
session.query(f).select_from(Author)
```

I expect the following query:

```sql
SELECT author.first_name || (author.id + ?) AS f
FROM author
```

Producing:

```
Name1
Name2
...
```

Instead SQLAlchemy generate the following query:

```sql
SELECT author.first_name || author.id + ? AS f
FROM author
```

Leading to incorrect results:

```
1
1
...
```

Unlike the SQL operator `+`, the operator `||` has the highest precedence.
Therefore to interpret this query correctly parenthesis are needed.
For more details see [here](https://www.sqlite.org/lang_expr.html#operators)

**Versions.**
SQLAlchemy latest master version([commit](https://github.com/sqlalchemy/sqlalchemy/commit/3b2c6692bd5df6fe4a37192dfdaed408e3be5e54))

**Have a nice day!**

**Comment by CaselIT** [comment] 2020-06-04 12:44
This is a duplicate of #5344 that is already fixes but not yet published on pypi.

You can work around this by using the solution in this comment https://github.com/sqlalchemy/sqlalchemy/issues/5344#issuecomment-632140468

**Comment by CaselIT** [comment] 2020-06-04 12:47
You mentioned that you are using master. That issue should be fixed in master.

Removing duplicate

**Comment by zzzeek** [comment] 2020-06-04 14:19
this is not specifically the type_coerce thing but the workaround of setting explicit parenthesis should work.

> Unlike the SQL operator +, the operator || has the highest precedence.

you refer here to SQLite's hardcoded rules.  we have had "concat" at level 6, below that of "add" at 7 and well below the highest precedence ops for many years.    I would need to have confirmation from other databases that they all apply similar precedence rules because it's not clear at the moment where the current list is coming from.

if the precedence change can be confirmed it allows this to place the parens around the plus sign:


```
diff --git a/lib/sqlalchemy/sql/operators.py b/lib/sqlalchemy/sql/operators.py
index 1bd63f285..cd3a5a4a6 100644
--- a/lib/sqlalchemy/sql/operators.py
+++ b/lib/sqlalchemy/sql/operators.py
@@ -1445,7 +1445,7 @@ _PRECEDENCE = {
     neg: 8,
     add: 7,
     sub: 7,
-    concat_op: 6,
+    concat_op: 15,
     filter_op: 6,
     match_op: 5,
     notmatch_op: 5,

```

```
SELECT a.data || (a.id + :param_1) AS f 
FROM a

```

**Comment by zzzeek** [comment] 2020-06-04 14:23
Postgresql array access operator, which is "Getitem" for us at 15, is higher precedence than string concat:
```

test=> select 'q' || (ARRAY['x','y'])[1];
 ?column? 
----------
 qx
(1 row)


```

**Comment by zzzeek** [comment] 2020-06-04 14:27
and addition is higher precedence than concat:

```
test=> select 'q' || 1 + 2;
 ?column? 
----------
 q3
(1 row)

```
which is in contradiction to sqlite:

```
sqlite> select 'q' || 1 + 2;
2
sqlite> select 'q' || (1 + 2);
q3
sqlite> select ('q' || 1) + 2;
2

```

it is extremely unusual to be mixing string concatenation with numerical addition operators so in this case i would lean towards the user setting up explicit parenthesization with self_group():

`expr = type_coerce(A.id + literal(1), String()).self_group()
`

**Comment by theosotr** [comment] 2020-06-04 14:33
Ι wonder though why sqlalchemy does not explicitly place parenthesis since when I apply the operator `||` between two expressions `e1`, `e2` (i.e., e1 || e2) I treat `e1` and `e2` as the operands of ||, with `e` can be any expression.

So in this case, I find removing parenthesis counter-intuitive. Placing parenthesis should work in any database.

**Comment by zzzeek** [comment] 2020-06-04 14:49
all parenthesization is applied based on precedence rules.   if we applied parenthesis based on the actual Python structure of the expression, you end up with expressions like this:
`
(((((a + 2) + 3) * 5) + ((( .. etc )))))(()))(())

**Comment by theosotr** [comment] 2020-06-04 14:50
But I believe this strange behavior of `II` violates the consistency between the following operations IMO.

```python
(Author.first_name + type_coerce(Authror.id + literal(1), types.String))
(Author.first_name + cast(Authror.id + literal(1), types.String))
```

**Comment by zzzeek** [comment] 2020-06-04 14:57
type_coerce is not a SQL construct, it only sends an indication to compiler that a particular expression should be treated *on the Python side* as a specific datatype.

Again, mixing string concatenation and math operators is a really weird and unusual use case, so if we are going to hunt for inconsistencies in SQLAlchemy, there is much better game elsewhere.

**Comment by zzzeek** [comment] 2020-06-04 15:06
the proposal is to unconditionally parenthesize all type coerce expressions.  it's not that simple because cases like this now do something undesirable:

```
>>> type_coerce(column('x', Integer), String) + 'hi'
(x) || :param_1

```

a lot of databases choke when there are unnecessary parenthesis so we have to minimize our use of them.

**Comment by zzzeek** [comment] 2020-06-04 15:07
> Would a warning in the doc-string of type coerce regarding `self_group` be useful?

The type_coerce() docs should talk about self_group() just as a matter of course, maybe at most a "note", "warnings" i usually reserve for things that will go wrong and not be immediately apparent.

**Comment by CaselIT** [comment] 2020-06-04 15:10
Yes, i was thinking more of a note. No dragon here 🐉. 
Will add self_group mention to the documentation

**Comment by zzzeek** [comment] 2020-06-04 17:32
I dont think it's worth changing type_coerces() behavioral contract but if you have a code proposal please open a new issue which details the specific use cases and changes.   type_coerce() was intended for fetching result columns and was not oriented towards being embedded in SQL expressions.

**Closed** 2020-06-04 17:31 UTC
Labels: datatypes, documentation, question, sql, sqlite, use case

**Comment by theosotr** [comment] 2020-06-04 18:17
Given your comment [here](https://github.com/sqlalchemy/sqlalchemy/issues/5344#issuecomment-632143664) that the following test cases should be consistent

```python
from sqlalchemy import column, type_coerce, Integer, cast

a = column("a") / (column("b") * column("c"))
b = column("a") / cast(column("b") * column("c"), Integer)
c = column("a") / type_coerce(column("b") * column("c"), Integer)

print(a)
print(b)
print(c)
```

I propose the following change in `type_coerce()`, which is fairly simple:

```
diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index fa2888a23..17548690b 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -2957,7 +2957,7 @@ class TypeCoerce(WrapsColumnExpression, ColumnElement):
         return self.clause

     def self_group(self, against=None):
-        grouped = self.clause.self_group(against=against)
+        grouped = self.clause.self_group()
         if grouped is not self.clause:
             return TypeCoerce(grouped, self.type)
         else:
```

I ran tests and they all pass successfully on my machine.

**Comment by CaselIT** [comment] 2020-06-04 18:33
That test case is already consistent.
```
a / (b * c)
a / CAST(b * c AS INTEGER)
a / (b * c)
```

The change you propose would make type_coerce inconsistent in this case

```py
from sqlalchemy import column, type_coerce, Integer, cast

d = column("a") * (column("b") * column("c"))
e = column("a") * type_coerce(column("b") * column("c"), Integer)

print(d)
print(e)
```

**Comment by zzzeek** [comment] 2020-06-04 18:36
there are no tests against type_coerce().self_group() with a specific operator in mind, which is why nothing fails.   By omitting the operator there you are only causing it to disregard the precedence for the given operator.      

I'm not sure why type_coerce() is even in play here, if you are switching between strings and integers in a WHERE clause, which is not at all what type_coerce() was intended for, you should be using CAST().

**Comment by theosotr** [comment] 2020-06-04 18:52
OK, it seems it's meaningless anymore.

As a final note: Just a suggestion from a programmer in case you may want to consider in future SQLAlchemy:

When I write `a / (b * c)`, I *really* mean `a / (b * c)` and *not* `a / b * c`. The same applies for any expression placed inside `type_corce()`, `cast()` or whatever. Parenthesis denote precedence and in which order sub-expressions should be evaluated. That's the natural thing from a programming point of view.

**Comment by zzzeek** [comment] 2020-06-04 18:58
> OK, it seems it's meaningless anymore.
> 
> As a final note: Just a suggestion from a programmer in case you may want to consider in future SQLAlchemy:
> 
> When I write `a / (b * c)`, I _really_ mean `a / (b * c)` and _not_ `a / b * c`. The same applies for any expression placed inside `type_corce()`, `cast()` or whatever. Parenthesis denote precedence and in which order sub-expressions should be evaluated. That's the natural thing from a programming point of view.

absolutely, however as mentioned before, relying upon the Python object structure to produce appropriate parenthesization is not feasible from a technical complexity standpoint.    The Python object structure in many cases does not actually look the way one would want the parenthesis to look and there is no simple way to guess at what points parenthesis should be generated vs. when they should not.    This would be the area where a motivated developer would want to come up with some new approach to generating appropriate parenthesis in all cases, never an unnecessary parenthesis, with no negative impacts on memory use, complexity, or performance.      SQLAlchemy's current approach works in the vast majority of cases.
