### ISSUE TITLE
asyncpg terminate needs a delay

### ISSUE THREAD

**Issue by PaulWasTaken** [sqlalchemy/sqlalchemy#10717] opened 2023-11-30 11:41 UTC
### Describe the bug

Greetings, I came across a strange behavior: when you pass `command_timeout` param to asyncpg driver and the query is long enough to exceed it, there still will be an active session on PostgreSQL side

You may also check it by using `select * from pg_stat_activity;`

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
import asyncio

import sqlalchemy as sa
from sqlalchemy import URL
from sqlalchemy.ext.asyncio import create_async_engine


async def test_asyncpg_with_command_timeout():
    engine = create_async_engine(
        URL.create(
            drivername='postgresql+asyncpg',
            host='localhost',
            port=5432,
            database='test',
            username='test',
            password='test',
        ),
        connect_args={
            'command_timeout': 2,
        },
    )

    try:
        async with engine.connect() as conn:
            await conn.execute(sa.text('select pg_sleep(:time)'), parameters={'time': 30})
    except asyncio.TimeoutError:
        print('gotcha')

    finally:
        await engine.dispose(close=True)


asyncio.run(test_asyncpg_with_command_timeout())
```

### Error

```
2023-11-30 11:21:54.103 UTC [34] STATEMENT:  select pg_sleep($1)
2023-11-30 11:21:54.103 UTC [34] LOG:  execute __asyncpg_stmt_7__: select pg_sleep($1)
2023-11-30 11:21:54.103 UTC [34] DETAIL:  parameters: $1 = '30'
2023-11-30 11:22:24.115 UTC [34] LOG:  disconnection: session time: 0:00:30.126 user=test database=test host=192.168.65.1 port=25931
2023-11-30 11:22:24.115 UTC [34] DEBUG:  exit(0)
``` 

### Additional context

I made my own investigation and the problem is because here https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connect_utils.py#L1036 `CancelledError` is thrown, so asyncpg can not send CancelRequest message, but if I add a small delay here https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/asyncpg.py#L617 it will succeed. I know that it is not the solution, but maybe it will save some time

**Comment by zzzeek** [comment] 2023-11-30 13:30
hey there -

Running this locally, I can see the statement stays on the PG server side through the timeout, then is cleaned up.

regardless of how much of an issue this is and how it might be fixed, this is the asyncpg driver somehow leaving a session running in the database, *after the program exits*.   if the argument is, "SQLAlchemy should make this impossible" I would argue this is plainly in the realm of asyncpg as something that would be made impossible (if not even the postgresql server).

So far this does not seem to be SQLAlchemy's problem?  Did you report this to asyncpg first?

**Comment by PaulWasTaken** [comment] 2023-11-30 13:38
No I didn't, for me it looks like SQLAlchemy doesn't wait for asyncpg to perform a graceful connection cancelling.
If you think I should report to the asyncpg developers, let's try starting with them

**Comment by zzzeek** [comment] 2023-11-30 13:41
let me try to reproduce with the asyncpg driver directly to understand where the interaction is wrong

**Comment by zzzeek** [comment] 2023-11-30 13:52
OK the reproduction case for asyncpg, which I am assuming they would be unwilling to fix, is that for a timeouterror we no longer have a way to await new operations on the connection, so we use terminate.

Here is the reproduction case

```py
import asyncio
import asyncpg


async def test_asyncpg_with_command_timeout():
    conn = await asyncpg.connect(
            host='localhost',
            port=5432,
            database='test',
            user='scott',
            password='tiger',
            command_timeout=2
    )

    trans = conn.transaction()
    try:
        await trans.start()
        prepared = await conn.prepare('select pg_sleep($1)')
        rows = await prepared.fetch(30)

    except asyncio.TimeoutError:
        print('gotcha')
        conn.terminate()
    finally:
        await conn.close()


asyncio.run(test_asyncpg_with_command_timeout())
```

**Comment by zzzeek** [comment] 2023-11-30 14:18
need to review use case for #8419

**Comment by zzzeek** [comment] 2023-11-30 14:25
so that patch breaks the case at https://github.com/sqlalchemy/sqlalchemy/issues/8419#issuecomment-1224249396 .   however the original case at #8145 seems to still be fine since that's a GC cleanup.

so i think safer approach here might be to do a yield inside of terminate in all cases but the GC one

**Comment by sqla-tester** [comment] 2023-11-30 14:42
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**add conditional yield to asyncpg terminate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5006

**Comment by zzzeek** [comment] 2023-11-30 14:43
this patch still changes the behavior of the test at https://github.com/sqlalchemy/sqlalchemy/issues/8419#issuecomment-1224249396 .   A small delay is added now, as the yield to asyncpg seems to go back to a short timeout on the asyncpg side.   the program still exits within a few seconds.   so that issue is still resolved because it previously was an indefinite hang.

**Comment by PaulWasTaken** [comment] 2023-11-30 14:56
I think, we could rely on `Connection._cancellations` if there would be any public api

**Comment by CaselIT** [comment] 2023-11-30 15:05
Would it make sense ask for suggestion to asyncpg dev on what they think it the best approach?

**Comment by zzzeek** [comment] 2023-11-30 15:09
> Would it make sense ask for suggestion to asyncpg devs on what they think it the best approach is?

they would say, "if you call terminate, everything stops, we can't clean up anything.  do a sleep if you want to terminate but have our commands finish"

i can't imagine what else they'd say

**Comment by CaselIT** [comment] 2023-11-30 15:14
Commented on the change.
If asyncpg does things asynchronously the connection should have a way to indicate that there are things pending.

**Comment by zzzeek** [comment] 2023-11-30 15:20
OK report it to asyncpg, see if they can provide for us a terminate() that also waits for whatever was pending.  or alteranteively, we need a "close()" that doesnt try to do a full handshake and hangs on no network

**Comment by zzzeek** [comment] 2023-11-30 15:21
I was trying here to avoid having **three** forms of close.   no other DBAPI, even the async ones, need to do any of this

**Comment by zzzeek** [comment] 2023-11-30 15:22
but your proposal is that we would now have "close()", "terminate()", "close_but_less_gracefully()" essentially

**Comment by elprans** [comment] 2023-11-30 19:11
Not a public method, but you can do `if conn._stmt_exclusive_section._acquired` to check if the connection has an operation running.  We can add a public method for this, please open an issue.

**Comment by elprans** [comment] 2023-11-30 19:16
> or alteranteively, we need a "close()" that doesnt try to do a full handshake and hangs on no network

`close()` takes a timeout, so you can do `await conn.close(some_low_timeout_value)` and have it still attempt to cancel the running query, but fall back to `terminate` on a timeout.

**Comment by CaselIT** [comment] 2023-11-30 19:29
Thanks for the reply!

> > or alteranteively, we need a "close()" that doesnt try to do a full handshake and hangs on no network
> 
> `close()` takes a timeout, so you can do `await conn.close(some_low_timeout_value)` and have it still attempt to cancel the running query, but fall back to `terminate` on a timeout.

It seems that terminate is not needed since on `CancelledError` close will call `_abort` that's the same as what terminate does.

@zzzeek I guess we can just call close when not handing a gc call, and suppress any exception

**Closed** 2023-12-06 15:54 UTC
Labels: bug, postgresql, asyncio
