### ISSUE TITLE
SQLAlchemy 1.4.32 breaks `Insert.add_cte()` with `TextualSelect`

### ISSUE THREAD

**Issue by cansjt** [sqlalchemy/sqlalchemy#7800] opened 2022-03-07 19:55 UTC
### Describe the bug

With SQLAlchemy 1.4.31, the following example query can be successfully compiled, but not with 1.4.32.

### To Reproduce

```python
from sqlalchemy import Column, insert, Integer, MetaData, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect
from sqlalchemy.dialects.mysql import dialect as mysql_dialect


meta = MetaData()
foo = Table('foo', meta, Column('id', Integer))
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )

s1 = text('SELECT id FROM foo').columns(foo.c.id)
s2 = (text('SELECT bar.id, bar.attr FROM bar WHERE br.id IN (SELECT id FROM baz)')
      .columns(bar.c.id, bar.c.attr)
      )
s3 = insert(bar).from_select(list(s2.selected_columns), s2)
s4 = s3.add_cte(s1.cte(name='baz'))

print(str(pg_dialect.statement_compiler(pg_dialect(), s4)))
print(str(mysql_dialect.statement_compiler(mysql_dialect(), s4)))
```

### Error

```
Traceback (most recent call last):
  File "/home/nicolas/src/gitco/jobteaser/jobflow-dags/bug-check.py", line 27, in <module>
    print(s4)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 562, in __str__
    return str(self.compile())
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 558, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/nicolas/.virtualenvs/jobflow-dags39/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3900, in visit_insert
    self.stack[-1]["insert_from_select"], insert_into=True, **kw
KeyError: 'insert_from_select'
``` 

### Versions

- OS: Ubuntu / Debian
- Python: 3.9.10
- SQLAlchemy: 1.4.32
- Database: postgresql, mysql (though that might impact any dialect supporting CTE)
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

Relates to #7798, #7760.

A close example that can be successfully compiled:

```python
from sqlalchemy import Column, insert, Integer, MetaData, select, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect
from sqlalchemy.dialects.mysql import dialect as mysql_dialect


meta = MetaData()
foo = Table('foo', meta, Column('id', Integer))
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )

s1 = select(foo.c.id)  # `TextualSelect` replaced with a "regular" `Select`
s2 = (text('SELECT bar.id, bar.attr FROM bar WHERE br.id IN (SELECT id FROM baz)')
      .columns(bar.c.id, bar.c.attr)
      )
s3 = insert(bar).from_select(list(s2.selected_columns), s2)
s4 = s3.add_cte(s1.cte(name='baz'))

print(str(pg_dialect.statement_compiler(pg_dialect(), s4)))
print(str(mysql_dialect.statement_compiler(mysql_dialect(), s4)))
```
Which seems to point ot the fact that this is really related to the fact that the statement involves a `TextualSelect`.

Not sure if that can give a clue, but the example below, with the CTE added to the `SELECT` used in the `select_from`, compiles successfully:
```python
from sqlalchemy import __version__
from sqlalchemy import Column, Integer, insert, MetaData, select, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect
from sqlalchemy.dialects.mysql import dialect as mysql_dialect

print('SQLAlchemy v: {}'.format(__version__))
meta = MetaData()
foo = Table('foo', meta, Column('id', Integer))
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )
# s1 = select(foo.c.id)
s1 = text('SELECT id FROM foo').columns(foo.c.id)
s2 = (text('SELECT bar.id, bar.attr FROM bar WHERE br.id IN (SELECT id FROM baz)')
      .columns(bar.c.id, bar.c.attr)
      )
s3 = s2.add_cte(s1.cte(name='baz'))
s4 = insert(bar).from_select(list(s2.selected_columns), s3)

print(str(mysql_dialect.statement_compiler(mysql_dialect(), s4)))
print(str(pg_dialect.statement_compiler(pg_dialect(), s4)))
```
It outputs
```sql
-- MySQL dialect
INSERT INTO bar (id, attr) WITH baz AS 
(SELECT id FROM foo)
 SELECT bar.id, bar.attr FROM bar WHERE br.id IN (SELECT id FROM baz)

-- PostgreSQL dialect
WITH baz AS 
(SELECT id FROM foo)
 INSERT INTO bar (id, attr) SELECT bar.id, bar.attr FROM bar WHERE br.id IN (SELECT id FROM baz)
```
The code handling this does not look trivial. I am looking into refactoring the code in which we use the failing example, in order to change the order in which the queries are assembled. But I am not sure that's trivial either.

**Comment by zzzeek** [comment] 2022-03-07 21:00
OK I'm going to fix these all at once as they are all likely either the same, or closely related things, so this is dupe of #7798 will add this example, just keep adding to the one issue

**Closed by zzzeek** 2022-03-07 21:00 UTC
Labels: requires triage

**Comment by Giuzzilla** [comment] 2022-03-15 09:30
Note for anyone searching for it: 
I was having a similar issue in `compiler.py`: `KeyError: 'compile_state'`

Starts to happen with apache-superset generated queries when bumping to SQLAlchemy 1.4.32

**Comment by CaselIT** [comment] 2022-03-15 10:29
@Giuzzilla  does the fix in #7798 solves also the issue you are having?

**Comment by Giuzzilla** [comment] 2022-03-15 11:00
Yes, just tested with the 1.4.33 development version and it works correctly. Breaks only with 1.4.32. Doesn't in 1.4.31 and earlier versions

**Comment by CaselIT** [comment] 2022-03-15 11:14
ok thanks for testing it!
