### ISSUE TITLE
Bound metadata RemovedIn20Warning in debug mode

### ISSUE THREAD

**Issue by serjflint** [sqlalchemy/sqlalchemy#5717] opened 2020-11-20 05:11 UTC
**Describe the bug**
"The Executable.bind attribute is considered legacy as of the 1.x series of SQLAlchemy and will be removed in 2.0." warning in Debug Mode in PyCharm on 2.0-style statements.

**Expected behavior**
No warnings, as I follow examples in the docs.

**To Reproduce**

```py
import toml
from sqlalchemy import Column, Integer, String, select
from sqlalchemy.engine import create_engine, URL
from sqlalchemy.orm import declarative_base, Session

Base = declarative_base()

with open("config.toml") as stream:
    config = toml.load(stream)
config = config["Database"]

engine_url = URL.create(
    drivername="mysql+pymysql",
    host=config["host"],
    port=config["port"],
    username=config["username"],
    password=config["password"],
    database=config["database"],
    query={"charset": "utf8"},
)

engine = create_engine(
    engine_url,
    pool_recycle=3600,
    pool_pre_ping=True,
    encoding="utf-8",
    future=True,
)


class Source(Base):
    __tablename__ = "server"
    id = Column("id", Integer, primary_key=True)
    name = Column("server", String(255))
    host = Column("host", String(255))
    port = Column("port", Integer)
    username = Column("login", String(255))
    password = Column("password", String(255))
    database = Column("db", String(255))


with Session(engine, future=True) as session:
    stmt = select(Source).where(Source.name == "test")
    source = session.execute(stmt).scalar()
```

I put breakpoint at line with stmt (the second from the bottom) and warning appears after going at line with source.

**Error**

```
/virtualenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:489: RemovedIn20Warning: The Executable.bind attribute is considered legacy as of the 1.x series of SQLAlchemy and will be removed in 2.0. Bound metadata is being removed as of SQLAlchemy 2.0. (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  elif self.bind:
```

**Versions.**
 - OS: Manjaro 20.1
 - Python: 3.8.6
 - SQLAlchemy: 1.4.0beta1
 - Database: MariaDB 10
 - DBAPI: mysql+pymysql

**Additional context**
[Issue on StackOverflow](https://stackoverflow.com/questions/64900043/bound-metadata-removedin20warning-in-debug-mode?noredirect=1#comment114769365_64900043)

**Have a nice day!**

**Comment by zzzeek** [comment] 2020-11-20 14:52
so yeah as discussed we need to see a stack trace, which you can accomplsh by setting your Python warning level to "ERROR", something in pycharm is broken here as the line you refer towards does not have any logic that emits any deprecation warning at all.

**Comment by zzzeek** [comment] 2020-11-20 14:53
ah, a reprieve, that's a descriptor.   why does the program not generate this by itself, hmm.

**Comment by serjflint** [comment] 2020-11-20 15:05
> so yeah as discussed we need to see a stack trace, which you can accomplsh by setting your Python warning level to "ERROR"

I used "-W always::DeprecationWarning -W error" as interpreter options and the warning disappeared. Only on F9 I receive another warning:

```
Exception ignored in: <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 32994), raddr=('127.0.0.1', 37369)>
ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 32994), raddr=('127.0.0.1', 37369)>
```

**Comment by serjflint** [comment] 2020-11-20 15:15
@zzzeek PyCharm evaluates all attributes of local variables. `stmt.bind` happens to be one of them.
```py
>>> stmt.bind
Traceback (most recent call last):
  File "/pycharm/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "<string>", line 2, in bind
  File "/virtualenvs/repeater-dIy575E2-py3.8/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 368, in warned
    _warn_with_version(message, version, wtype, stacklevel=3)
  File "/virtualenvs/repeater-dIy575E2-py3.8/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 41, in _warn_with_version
    warnings.warn(warn, stacklevel=stacklevel + 1)
sqlalchemy.exc.RemovedIn20Warning: The Executable.bind attribute is considered legacy as of the 1.x series of SQLAlchemy and will be removed in 2.0. Bound metadata is being removed as of SQLAlchemy 2.0. (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
```

 I don't know why warning disappears on `-W error`, though. Some weird PyCharm magic.

**Comment by zzzeek** [comment] 2020-11-20 15:21
yeah that's where it is, also if you str() the statement, thanks.  I got it.

**Comment by zzzeek** [comment] 2020-11-20 15:30
oh does this mean pycharm unconditionally accesses all descriptors everywhere?    that's....a little tricky.   These are attributes that wont be there in 2.0 and I'd want a program that accesses them to know it.   i guess we don't have much option though.

**Comment by zzzeek** [comment] 2020-11-20 15:30
there's a warning emitted for session.transaction also.   is pycharm accessing that?

**Comment by zzzeek** [comment] 2020-11-20 15:32
I think what's maybe happening here is pycharm is calling str() on the object maybe, which also accesses stmt.bind.    I'm going to put this up while leaving the warning for session.transaction in place.    the stmt.bind accessor is handled because there are warning when you try to assign bound metadata up front.

**Comment by serjflint** [comment] 2020-11-20 15:33
> oh does this mean pycharm unconditionally accesses all descriptors everywhere?    that's....a little tricky.   These are attributes that wont be there in 2.0 and I'd want a program that accesses them to know it.   i guess we don't have much option though.

I see lots of tracebacks in attributes when I debug Django projects in PyCharm. Not sure of exact mechanisms, but seems likely.

**Comment by serjflint** [comment] 2020-11-20 15:38
> there's a warning emitted for session.transaction also.   is pycharm accessing that?

No... Very strange. Even if I write `session = Session(engine, future=True)`

**Comment by serjflint** [comment] 2020-11-20 15:40
The warning also disappears when I use one-line session.execute.

**Comment by serjflint** [comment] 2020-11-20 15:43
> yeah that's where it is, also if you str() the statement, thanks.  I got it.

Warning appears on both str(stmt) and str(session) but not on `with Session(engine, future=True) as session:`

**Comment by sqla-tester** [comment] 2020-11-20 16:02
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't emit warnings on descriptor access** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2377

**Comment by zzzeek** [comment] 2020-11-20 16:11
I can't reproduce any warning on str(Session) and I can't think of why it would be because .transaction is not internally accessed.  do you have a stack trace?

**Comment by serjflint** [comment] 2020-11-20 16:18
My bad. I receive warning on str(session), not capital 's'. But only after I've received the warning on stmt. Nothing happens until I run the line with stmt. But after the stmt's line I receive warnings on each line while stmt is in the  local stack. So Session is unrelated.

**Closed** 2020-11-20 19:42 UTC
Labels: bug
