### ISSUE TITLE
MSSQL Multiple row insert of numeric values fails with fast_executemany option in version 1.4.0

### ISSUE THREAD

**Issue by ALMP-SallaH** [sqlalchemy/sqlalchemy#6058] opened 2021-03-16 10:20 UTC
**Describe the bug**
Multiple row insert of numeric values fails with `mssql+pyodbc` dialect and `fast_executemany` option in SQLAlchemy version 1.4.0. Everything works fine without the `fast_executemany` option and with older versions of SQLAlchemy.

**To Reproduce**
The table that I wish to insert values to
```
Table('Observations', metadata,
    Column('id', Integer, nullable=False, primary_key=True),
    Column('obs1', Numeric(9,6), nullable=True),
    Column('obs2', Numeric(9,6), nullable=True),
    schema='store')
```
Code snippet to insert some numerical values:
```
from sqlalchemy import create_engine, MetaData, Table
from sqlalchemy.engine.url import URL


url = URL(
        drivername='mssql+pyodbc',
        username=uid,
        password=pw,
        host='localhost',
        port=1433,
        database=database,
        query={'driver': 'ODBC Driver 17 for SQL Server'}
        )

engine = create_engine(url, echo=True, fast_executemany=True)
reflected_table = Table('Observations', MetaData(bind=engine), schema='store', autoload=True)

records = [
    {'id': 1, 'obs1': 60.1722066045792, 'obs2': 24.929289808227466},
    {'id': 2, 'obs1': 60.16325715615476, 'obs2': 24.93886459535008},
    {'id': 3, 'obs1': 60.16445165123469, 'obs2': 24.949856300109516}
    ]

engine.execute(reflected_table.insert(), records)
```
**Error**
```
test.py:5: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  url = URL(
2021-03-16 12:06:58,565 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2021-03-16 12:06:58,565 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-03-16 12:06:58,567 INFO sqlalchemy.engine.Engine SELECT schema_name()
2021-03-16 12:06:58,568 INFO sqlalchemy.engine.Engine [generated in 0.00026s] ()
2021-03-16 12:06:58,570 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2021-03-16 12:06:58,571 INFO sqlalchemy.engine.Engine [generated in 0.00028s] ()
2021-03-16 12:06:58,585 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME], sys.computed_columns.definition, sys.computed_columns.is_persisted, sys.identity_columns.is_identity, CAST(sys.identity_columns.seed_value AS NUMERIC) AS seed_value, CAST(sys.identity_columns.increment_value AS NUMERIC) AS increment_value
FROM [INFORMATION_SCHEMA].[COLUMNS] LEFT OUTER JOIN sys.computed_columns ON sys.computed_columns.object_id = object_id([INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] + CAST(? AS NVARCHAR(max)) + [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME]) AND sys.computed_columns.name = [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME] LEFT OUTER JOIN sys.identity_columns ON sys.identity_columns.object_id = object_id([INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] + CAST(? AS NVARCHAR(max)) + [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME]) AND sys.identity_columns.name = [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME]
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION]
2021-03-16 12:06:58,586 INFO sqlalchemy.engine.Engine [generated in 0.00058s] ('.', '.', 'Observations', 'store')
2021-03-16 12:06:58,594 INFO sqlalchemy.engine.Engine SELECT [C].[COLUMN_NAME], [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS].[CONSTRAINT_TYPE], [C].[CONSTRAINT_NAME]
FROM [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] AS [C], [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS]
WHERE [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS].[CONSTRAINT_NAME] = [C].[CONSTRAINT_NAME] AND [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS].[TABLE_SCHEMA] = [C].[TABLE_SCHEMA] AND [C].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [C].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS].[CONSTRAINT_NAME], [C].[ORDINAL_POSITION]
2021-03-16 12:06:58,594 INFO sqlalchemy.engine.Engine [generated in 0.00039s] ('Observations', 'store')
2021-03-16 12:06:58,599 INFO sqlalchemy.engine.Engine SELECT [C].[COLUMN_NAME], [R].[TABLE_SCHEMA], [R].[TABLE_NAME], [R].[COLUMN_NAME] AS [COLUMN_NAME_1], [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[CONSTRAINT_NAME], [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[MATCH_OPTION], [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[UPDATE_RULE], [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[DELETE_RULE]
FROM [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] AS [C], [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] AS [R], [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS]
WHERE [C].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [C].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[CONSTRAINT_SCHEMA] = [C].[TABLE_SCHEMA] AND [C].[CONSTRAINT_NAME] = [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[CONSTRAINT_NAME] AND [R].[CONSTRAINT_NAME] = [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[UNIQUE_CONSTRAINT_NAME] AND [R].[CONSTRAINT_SCHEMA] = [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[UNIQUE_CONSTRAINT_SCHEMA] AND [C].[ORDINAL_POSITION] = [R].[ORDINAL_POSITION] ORDER BY [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS].[CONSTRAINT_NAME], [R].[ORDINAL_POSITION]
2021-03-16 12:06:58,600 INFO sqlalchemy.engine.Engine [generated in 0.00049s] ('Observations', 'store')
2021-03-16 12:06:58,605 INFO sqlalchemy.engine.Engine select ind.index_id, ind.is_unique, ind.name, ind.filter_definition from sys.indexes as ind join sys.tables as tab on ind.object_id=tab.object_id join sys.schemas as sch on sch.schema_id=tab.schema_id where tab.name = CAST(? AS NVARCHAR(max)) and sch.name=CAST(? AS NVARCHAR(max)) and ind.is_primary_key=0 and ind.type != 0
2021-03-16 12:06:58,605 INFO sqlalchemy.engine.Engine [generated in 0.00036s] ('Observations', 'store')
2021-03-16 12:06:58,610 INFO sqlalchemy.engine.Engine select ind_col.index_id, ind_col.object_id, col.name, ind_col.is_included_column from sys.columns as col join sys.tables as tab on tab.object_id=col.object_id join sys.index_columns as ind_col on (ind_col.column_id=col.column_id and ind_col.object_id=tab.object_id) join sys.schemas as sch on sch.schema_id=tab.schema_id where tab.name=CAST(? AS NVARCHAR(max)) and sch.name=CAST(? AS NVARCHAR(max))
2021-03-16 12:06:58,610 INFO sqlalchemy.engine.Engine [generated in 0.00039s] ('Observations', 'store')
2021-03-16 12:06:58,617 INFO sqlalchemy.engine.Engine SET IDENTITY_INSERT store.[Observations] ON
2021-03-16 12:06:58,617 INFO sqlalchemy.engine.Engine ()
2021-03-16 12:06:58,622 INFO sqlalchemy.engine.Engine INSERT INTO store.[Observations] (id, obs1, obs2) VALUES (?, ?, ?)
2021-03-16 12:06:58,623 INFO sqlalchemy.engine.Engine [generated in 0.00592s] ((1, 60.1722066045792, 24.929289808227466), (2, 60.16325715615476, 24.93886459535008), (3, 60.16445165123469, 24.949856300109516))
2021-03-16 12:06:58,629 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 1685, in _execute_context
    self.dialect.do_executemany(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 456, in do_executemany
    super(MSDialect_pyodbc, self).do_executemany(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\default.py", line 678, in do_executemany
    cursor.executemany(statement, parameters)
pyodbc.DataError: ('22003', '[22003] [Microsoft][ODBC Driver 17 for SQL Server]Numeric value out of range (0) (SQLExecute)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    engine.execute(reflected_table.insert(), records)
  File "<string>", line 2, in execute
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\util\deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 3008, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\sql\elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\util\compat.py", line 198, in raise_
    raise exception
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\base.py", line 1685, in _execute_context
    self.dialect.do_executemany(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 456, in do_executemany
    super(MSDialect_pyodbc, self).do_executemany(
  File "C:\Users\me\virtual_environments\py38\lib\site-packages\sqlalchemy\engine\default.py", line 678, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DataError: (pyodbc.DataError) ('22003', '[22003] [Microsoft][ODBC Driver 17 for SQL Server]Numeric value out of range (0) (SQLExecute)')
[SQL: INSERT INTO store.[Observations] (id, obs1, obs2) VALUES (?, ?, ?)]
[parameters: ((1, 60.1722066045792, 24.929289808227466), (2, 60.16325715615476, 24.93886459535008), (3, 60.16445165123469, 24.949856300109516))]
(Background on this error at: http://sqlalche.me/e/14/9h9h)
```

**Additional context**
The previous code snipped works nicely if one
- removes the `fast_executemany=True` option
- reverts to an older version of SQLAlchemy

**Versions.**
 - OS: Win10
 - Python: 3.8.3
 - SQLAlchemy: 1.4.0
 - Database: Microsoft SQL Server 14.0.3281.6 (Linux)
 - DBAPI: pyodbc (version 4.0.30)

**Comment by zzzeek** [comment] 2021-03-16 14:03
great, that's a legit regression, bisect finds it as 87c24c498cb660e7a8d7d4dd5f6 which not surprisingly is highly involved with pyodbc.   not sure what the problem is though.

**Comment by zzzeek** [comment] 2021-03-16 14:03
here's an mcve

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Numeric
from sqlalchemy import Table

metadata = MetaData()


observations = Table(
    "Observations",
    metadata,
    Column("id", Integer, nullable=False, primary_key=True),
    Column("obs1", Numeric(9, 6), nullable=True),
    Column("obs2", Numeric(9, 6), nullable=True),
    schema="test_schema",
)


engine = create_engine(
    "mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?"
    "driver=ODBC+Driver+17+for+SQL+Server",
    echo=True,
    fast_executemany=True,
)
with engine.begin() as conn:
    metadata.drop_all(conn)
    metadata.create_all(conn)


records = [
    {"id": 1, "obs1": 60.1722066045792, "obs2": 24.929289808227466},
    {"id": 2, "obs1": 60.16325715615476, "obs2": 24.93886459535008},
    {"id": 3, "obs1": 60.16445165123469, "obs2": 24.949856300109516},
]

engine.execute(observations.insert(), records)

```

**Comment by zzzeek** [comment] 2021-03-16 14:05
Here's your workaround for now, we are now calling pyodbc.setinputsizes() for some datatypes and this seems to be a problem, so do this:

```python
engine = create_engine(...)
engine.dialect.use_setinputsizes = False

```

**Comment by gordthompson** [comment] 2021-03-16 14:35
I hadn't gotten to the point of identifying `setinputsizes()` as the culprit, but an ODBC trace did show that 1.3 was correctly identifying the columns as `NUMERIC(9,6)`

```
gh_sqla_6058    12a4-193c	EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x000000BA35D03C60
        UWORD                        3 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                        8 <SQL_C_DOUBLE>
        SWORD                        2 <SQL_NUMERIC>
        SQLULEN                    9
        SWORD                        6 
        PTR                0x0000000000000030
        SQLLEN                     8
        SQLLEN *            0x0000000000000038 (BADMEM)
```

while 1.4 is incorrectly identifying them as `NUMERIC(9,9)`

```
gh_sqla_6058    1ea8-190c	EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x00000012CC903C80
        UWORD                        3 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                        8 <SQL_C_DOUBLE>
        SWORD                        2 <SQL_NUMERIC>
        SQLULEN                    9
        SWORD                        9 
        PTR                0x0000000000000030
        SQLLEN                     8
        SQLLEN *            0x0000000000000038 (BADMEM)
```

and any value ≥ 1 is not going to fit into a `NUMERIC(9,9)` column.

**Comment by sqla-tester** [comment] 2021-03-16 15:26
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Turn off pyodbc setinputsizes() by default** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2634

**Comment by zzzeek** [comment] 2021-03-16 15:28
@gordthompson our setinputsizes code is sending in "float" for all three params right now, even the integer.     so im turning off the whole thing for now unless you send a flag.

**Closed** 2021-03-16 20:39 UTC
Labels: SQL Server, bug, engine, regression

**Comment by gordthompson** [comment] 2022-06-24 23:04
Not the most elegant workaround, but it does seem to work:

```python
@event.listens_for(engine, "do_setinputsizes")
def receive_do_setinputsizes(
    inputsizes, cursor, statement, parameters, context
):
    for bind_param in [
        x for x in inputsizes if repr(x.type).startswith("Numeric(")
    ]:
        inputsizes[bind_param] = (
            pyodbc.SQL_NUMERIC,
            bind_param.type.precision,
            bind_param.type.scale,
        )
```
