### ISSUE TITLE
`MetaData.reflect()` ignores `quoted_name` flag

### ISSUE THREAD

**Issue by MarkusFraKS** [sqlalchemy/sqlalchemy#5277] opened 2020-04-23 15:53 UTC
When having a table name `My_Table` passed to 
```python
sqlalchemy.sql.schema.MetaData.reflect(only=[quoted_name("My_Table", False)])
```
I get the false error, that the table does not exist if the case does not match. For example if pandas tries to drop a table when replacing it:

```
File "***\lib\site-packages\pandas\io\sql.py", line 1366, in drop_table
    self.meta.reflect(only=[table_name], schema=schema)
  File "***\lib\site-packages\sqlalchemy\sql\schema.py", line 4268, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(****) schema 'myschema': (My_Table)
```

The cause of this is that within the `MetaData.reflect()` method `quoted_name` objects are not treated properly. Regarding the error above the error caused at:

```python
            else:
                missing = [name for name in only if name not in available]
                if missing:
                    s = schema and (" schema '%s'" % schema) or ""
                    raise exc.InvalidRequestError(
                        "Could not reflect: requested table(s) not available "
                        "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
                    )
```

The list `available` contains all the table names in lowercase since they were unquoted on the database and have been normalized to SQLAlchemys convention for case insensitive.
The table names stored in only are not normalized and a comparison between `quoted_name("My_Table", False)` and a string in the `available` list `my_table` evaluated to `False` thus causing SQLAlchemy telling me that the table is missing.

I think somewhere in there the dialects `normalize_name` needs to be called for the tables in `only` or the comparison has to be done in another way since one should not compare `quoted_name` objects and strings like that.

**Comment by zzzeek** [comment] 2020-04-23 16:03
hi there -

the "only" argument does not expect to receive "quoted name" objects as these are meaningless here, "quoted name" only refers to how the table should be rendered when a CREATE TABLE , SELECT or other statement should be rendered.  it does not indicate anything about case sensitivity, which seems to be what you are doing.

If you would like reflection to exclude the "my_table" table, and you know that this name is present in the database in a case insensitive fashion, then you would specify it as lower case.    if you are looking for a programmatic means, then "My_Table".lower() will do it.  

The SQLAlchemy documentation is currently lacking in an easily locatable description of how it approaches "case sensitivity", however the best description is at https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=table#sqlalchemy.schema.Table.params.name:

> Names which contain no upper case characters will be treated as case insensitive names, and will not be quoted unless they are a reserved word or contain special characters. A name with any number of upper case characters is considered to be case sensitive, and will be sent as quoted.  To enable unconditional quoting for the table name, specify the flag quote=True to the constructor, or use the quoted_name construct to specify the name.


now you might have actually read that document and that's how you found quoted_name, but there's a bit of a deficiency in that paragraph in that it is not properly separating the two concepts of **case insensitive** and **whether or not the name is quoted**.  these are two separate things.    the "only" parameter only cares about the first, and all-lower-case is how to send case insensitive.

**Comment by zzzeek** [comment] 2020-04-23 16:05
also please confirm which database in use, assuiming oracle

**Comment by MarkusFraKS** [comment] 2020-04-23 16:22
Hello zzzeek,

thank you very much for the fast and detailed reply. Database in use is DB2.

You are right. Apparently I misunderstood the meaning of `quoted_name` a bit. I hoped by using `quoted_name` I could make SQLAlchemy treat all cases as case-insensitive. The trick with "My_Table".lower() works for creating a table. But any idea how to get the column names for example if they are saved case insensitive on the database. Just making them uppercase via `upper()` would be no option if there is a mixture of case sensitive lowercase and case insensitive uppercase on the DB.

There also seems to be a difference if I create a Table with name "MY_TABLE" I cannot select it with the name "MY_TABLE". I have to use "my_table". I would have expected that since "MY_TABLE" is case sensitive uppercase (regarding SQLAlchemy convention) send to the database I would be able to use "MY_TABLE" again to read the table.

**Comment by zzzeek** [comment] 2020-04-23 16:47
the way name normalization works is, all case insensitive names are written as all lower case on the python side, across the board, everywhere.   Then the driver, in this case....IBM db_sa driver?   needs to "denormalize" that name whenever it queries the database for that name.  then when it returns any names, it needs to "normalize" them again, which means any name that is ALL_UPPERCASE will be lower cased.

Now the IBM db_sa driver is really old and might have bugs in this area, I'm not really sure.    I can confirm however using the Oracle driver which has the same casing and normalization behavior, there is no such issue here, I can say `only=["some_table"]` and the reflect() method works correctly.

so on your side, if the names are not quoted in the database, you use all lower case strings, and you shouldn't have to worry about it.     the moment you use a name that has any uppercase in it, like when you say "create a Table with "MY_TABLE"", now you're telling it to use case sensitivity, which is not what you want.

> There also seems to be a difference if I create a Table with name "MY_TABLE" I cannot select it with the name "MY_TABLE".

you need to provide an [MCVE](http://stackoverflow.com/help/mcve) for this as there is no known issue in SQLAlchemy in this area (again, if there's a bug in the IBM db sa driver, that is possible).  Here is a demo with Oracle:
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table


e = create_engine("oracle://scott:tiger@oracle1120", echo=True)


m = MetaData()

t = Table("MY_TABLE", m, Column("x", Integer))


m.create_all(e)


with e.connect() as conn:
    conn.execute(select([t]))


```

in the SQL output you can see the quoted MY_TABLE name used correctly throughout:

```
CREATE TABLE "MY_TABLE" (
	x INTEGER
)


2020-04-23 12:45:18,488 INFO sqlalchemy.engine.Engine {}
2020-04-23 12:45:18,500 INFO sqlalchemy.engine.Engine COMMIT
2020-04-23 12:45:18,541 INFO sqlalchemy.engine.Engine SELECT "MY_TABLE".x 
FROM "MY_TABLE"



```

but again, using case sensitive all uppercase names is not a good idea.   case insensitive names should be used across the board if you have an option here.

**Comment by zzzeek** [comment] 2020-04-23 16:51
here's the MCVE for your relfect / only issue with Oracle, which passes
```

from sqlalchemy import *


e = create_engine("oracle://scott:tiger@oracle1120", echo=True)


m = MetaData()

Table("my_table", m, Column("x", Integer))

Table("my_table_2", m, Column("x", Integer))

m.create_all(e)


# reflect with "only", we get just the one table
m2 = MetaData()

m2.reflect(e, only=["my_table_2"])

assert list(m2.tables) == ["my_table_2"]  # note my_table not present


# reflect all tables, we get both
m3 = MetaData()
m3.reflect(e)

assert set(m3.tables) == {"my_table", "my_table_2"}

m.drop_all(e)

```

**Comment by MarkusFraKS** [comment] 2020-04-23 17:28
Thanks again for the very detailed answer! I can confirm that your MCVE works with ibm_db_sa as long I do not pass table names with `quoted_name`  what - as you said - I should not do (unless I have an all lowercase case sensitive name on the db). The ibm_db_sa seems not to take `quoted_name` objects into account for denormalize_name then. Sorry for all the fuss but it is much clearer to me now!

My hope was to emulate the DB2 beviour in SQLAlchemy. Having everything case insensitive unless it is quoted. And fetch names in UPPERCASE if they are not quoted on the db.

**Comment by zzzeek** [comment] 2020-04-23 18:54
im not sure what it is you want to do exactly.     if the name comes back as all lower case, then you can assume it's case insensitive and on DB2 would be all uppercase.

are you trying to generically reflect any number of databases that may include case sensitive, all-lowercase names?

**Comment by MarkusFraKS** [comment] 2020-04-23 18:57
The problem is that I cannot distinguish between case insensitive column names on the DB2 and case sensitive lowercase column names. Since they both come back as lowercase.

**Comment by MarkusFraKS** [comment] 2020-04-23 19:04
In a perfect world there would be a company wide standard e.g. just use case insensitive notation. But since  everything is a bit historical grown I have to make sure that I cover every case and especially if I do database migration it must not happen that I accidentally change the case of column names.

**Comment by zzzeek** [comment] 2020-04-23 19:11
are you using alembic autogenerate?    The idea is that these case sensitive, lower case columns would be the exception rather than the rule, I dont think they would produce a migration in any case, and if they did you would always be reviewing your migrations and testing them out on development databases in any case.   

I know this is a little long-form but I REALLY need to know exactly what it is you are trying to do and how you are doing it.

**Comment by MarkusFraKS** [comment] 2020-04-23 19:56
The root of the problem was that some people have problems with the lowercase = case insensitive convention of SQLAlchemy. So I thought I quickly write something to mimic the behavior of the DB2

The DB2 behavior is:
Everything is case insensitive if not quoted
If it is case insensitive, it is stored UPPERCASE

SQLAlchemys behavior is:
case insensitive if lowercase, case sensitive otherwise
If it is case insensitive, it is stored lowercase.

As I read about the `quoted_name` I thought, ah nice, I can make use of this. Unfortunately that did not work.
This not only becomes a problem for readability.
When working with pandas DataFrames it can become a problem in a way that the column names of a DataFrame changed after uploading it to the database and downloading it again. (but that may rather a problem for the pandas guys). For example If I create a table with a DataFrame having the three columns ["Test", "TEST", "test"] it will become on the DB2 "Test" | TEST | TEST. If I read the table again it will become ["Test", "test", "test"] on python side. The solution will now be to enforce case insensitivity for everything with `.lower()`, but I it would have been nice just to have what I see in python and what I see on the DB consistent.

**Comment by zzzeek** [comment] 2020-04-23 21:40
> This not only becomes a problem for readability.
> When working with pandas DataFrames it can become a problem in a way that the column names of a DataFrame changed after uploading it to the database and downloading it again. (but that may rather a problem for the pandas guys). For example If I create a table with a DataFrame having the three columns ["Test", "TEST", "test"] it will become on the DB2 "Test" | TEST | TEST.

What I think should be appreciated here is that if you make those three names on DB2 with quoting for all three, the database doesn't actually record any flag that the name is case sensitive or case insensitive.   No such flag exists on any database I've worked with; instead there is only a matching rule based on how the identifier is noted in a SQL statement vs. what matches in the database's table metadata.   So when we read these names in, we don't know anything about whether they were quoted or not when they were made if they in fact appear in the normalized case for that database, which is UPPERCASE for DB2 or Oracle.

it doesn't work for SQLAlchemy to just "reverse" the rules for certain databases.  it should be apparent that this would be disastrous for most applications as they now would have UPPERCASE names hardcoded throughout their applications that are not compatible with other databases.

So the overarching answer to this general use case is that it is a very bad idea to use case sensitive identifiers with relational databases, and especially multiple synonymous names of different cases as that won't even work on every database.  However that said, of course SQLAlchemy offers explicit ways of dealing with these identifiers, if these ways are nevertheless not well documented, which again is because this is not a common issue because most people are not using intentionally confusing identifier patterns.

The Pandas community of course changes this calculus as this is a non-relational system being wielded by non-programmer types, so to accommodate for them we need to consider how to go into these areas that are generally anathema to the database programming community.     Given your example that people are in potentially making datastructures that intentionally have the same identifiers repeated with different casing conventions, my immediate impression is that while we can accommodate this, it is unlikely that this is a widespread practice; for example, it is outright rejected by MySQL which is vastly more popular than DB2 and Oracle combined:

```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1060, "Duplicate column name 'TEST'")
[SQL: 
CREATE TABLE my_table (
	`Test` INTEGER, 
	`TEST` INTEGER, 
	`test` INTEGER
)

```

MySQL has similar issues if you use duplicate table names with different casing conventions, with the added twist that its behavior is different based on the underlying OS in use.    

But let's consider that this is still a use case with real Pandas users who are not able to use reasonable naming conventions and are using a database that would support this.   We consider that Pandas "column" names are case sensitive in all cases; that's fine, we can set up our tables the same way:

```
Table(
    "my_table",
    m,
    Column(quoted_name("Test", quote=True), Integer),
    Column(quoted_name("TEST", quote=True), Integer),
    Column(quoted_name("test", quote=True), Integer),
)

```

SQLAlchemy will create the table faithfully as instructed:

```
CREATE TABLE my_table (
	"Test" INTEGER, 
	"TEST" INTEGER, 
	"test" INTEGER
)

```

we can then read back those names just as they were given, with the exception of the name normalization having converted from the remote databases casing convention to that of SQLAlchemy, noting however that column names that require quoting in order to bypass normalization *is* detected, as you can see by the quote flag:

```
from sqlalchemy import inspect
insp = inspect(my_engine)
print(insp.get_columns("my_table"))

# output (Formatted):
[
    {
        "name": "Test",
        "type": INTEGER(),
        "nullable": True,
        "default": None,
        "autoincrement": "auto",
        "comment": None,
    },
    {
        "name": "test",
        "type": INTEGER(),
        "nullable": True,
        "default": None,
        "autoincrement": "auto",
        "comment": None,
    },
    {
        "name": "test",
        "type": INTEGER(),
        "nullable": True,
        "default": None,
        "autoincrement": "auto",
        "comment": None,
        "quote": True,
    },
]

```

as we are given all the information we need, we can reverse the casing back to exactly what it is for DB2:


```

insp = inspect(e)

for col in insp.get_columns("my_table"):
    if col['name'] == col['name'].lower() and not col.get('quote', False):
        col['name'] = col['name'].upper()

    print(col['name'])

```

that "quote" flag is mirrored in the "name" object itself, which you will see is actually a quoted_name(name, quote=True).  This is how you'd get this information back when reading table names and such.   

output:

```
Test
TEST
test

```

Now to the next part, actually reflecting a whole `Table`, I have in fact identified a bug in the Oracle dialect as a result of this, which is that the above table is not reflecting properly because it is hashing those columns without looking at the quote flag, separate issue coming for that and that will be resolved in 1.3.17; the DB2 dialect may or may not have the same problem.

But the above issue doesn't prevent us from successfully reflecting the table back if we seek to restore the new Table to the same assumptions that we started with, which is, this is Pandas so all column names are case sensitive.  We can use the following event for this:

```
@event.listens_for(Table, "column_reflect")
def column_reflect(inspector, table, column_info):
    name = column_info["name"]

    # denormalize name and quote
    if name == name.lower() and not column_info.get("quote", False):
        name = name.upper()

    column_info["name"] = quoted_name(name, quote=True)


m2 = MetaData()
t2 = Table("my_table", m2, autoload_with=e)

print(t2.c.keys())

```

and we get them right back just like that:

`['Test', 'TEST', 'test']
`

and a full CreateTable round trip:

```
from sqlalchemy.dialects import oracle
from sqlalchemy.schema import CreateTable
print(CreateTable(t2).compile(dialect=oracle.dialect()))

```

output:

```
CREATE TABLE my_table (
	"Test" INTEGER, 
	"TEST" INTEGER, 
	"test" INTEGER
)


```

now what is not supported in the same way are the names of the tables themselves.   if a database had `CREATE TABLE "TEST"` and `CREATE TABLE "test"`, I'm not really sure what databases even support that.  The inspector.get_table_names() method will give you the two separate names using the quoted_name() object as necessary, so the information is available and you can convert all of these names to quoted_name again if you wanted.   However I don't know that these two tables can co-exist in the same MetaData object because the quoted name and the regular name still hash the same, so if you were trying to do something in that regard, something special might have to happen.

This all again hinges on what you *actually* want to do.   You gave me the example of a Pandas dataframe with the same column name repeated, and I showed you how to get it back exactly as given.

**Comment by zzzeek** [comment] 2020-04-23 22:36
OK actually I've closed #5281 as a wontfix for now.   There's no way to make this behavior automatic as it breaks the widely understood assumptions of SQLAlchemy's casing model.   Making it an option is doable but would be a massive amount of effort for a case I'm not really sure exists.   The recipe above is the current workaround for the multiple, same-named column case.

**Comment by zzzeek** [comment] 2020-04-23 22:38
the same-name-different-case identifier pattern is also rejected by SQLite and MS SQL Server.    SQLite is likely the most popular database used with pandas so I am still leaning towards this not being a realistic use case.

**Comment by zzzeek** [comment] 2020-05-11 14:44
closing this as while name normalize does cause some confusion, it would be much worse if we weren't doing it, and the reflection process can be affected so that the behavior is reversed.   same-named columns are not supported by most databases and if someone truly wanted to use that case, they can use quoted columns.

**Closed by zzzeek** 2020-05-11 14:44 UTC
Labels: external driver issues, question
