### ISSUE TITLE
session.commit cause error in version 1.3.1

### ISSUE THREAD

**Issue by foolcage** [sqlalchemy/sqlalchemy#4579] opened 2019-03-28 03:47 UTC
File /ve/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1293, in delete_stmt
    return table.delete(1, clause)
TypeError: <lambda>() takes from 1 to 2 positional arguments but 3 were given

**Comment by foolcage** [comment] 2019-03-28 03:59
when changing to SQLAlchemy == 1.2.14,it's ok

**Comment by zzzeek** [comment] 2019-03-28 12:53
hi there -

did you change that file locally?   that's not what line 1293 of persistence.py says, there is no "1" argument.   try reinstalling.

**Comment by foolcage** [comment] 2019-03-29 01:51
Hi

I didn't changed it locally,I used flask-sqlalchemy 2.3.2 and it depends on sqlalchemy 1.3.1.

**Comment by zzzeek** [comment] 2019-03-29 12:52
OK, here is the information given:

> File /ve/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1293, in delete_stmt
return table.delete(1, clause)

that's not the right information:

https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_1/lib/sqlalchemy/orm/persistence.py#L1293


so that's all I can do here.   Should I close this as "Can't reproduce" ?

**Comment by foolcage** [comment] 2019-03-31 02:33
It's really strange,I compare the files and it's the same..I would give more details latter,thanks a lot.

**Comment by zzzeek** [comment] 2019-04-02 13:56
please reopen if you can figure out what went wrong thanks!

**Closed by zzzeek** 2019-04-02 13:56 UTC
Labels: question
