### ISSUE TITLE
`get_check_constraints` result changed in SQLAlchemy 2.0.33-34

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/sqlalchemy#11840] opened 2024-09-05 08:20 UTC
### Describe the bug

I encountered problems noted in #11832, but I found a case not handled by the fix.

```python
from sqlalchemy import create_engine, Column, Integer, inspect, CheckConstraint, MetaData
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped, mapped_column
from typing import Optional


METADATA = MetaData()

class BaseModel(DeclarativeBase):
    metadata = METADATA

    id = Column(Integer, primary_key=True)


class Example(BaseModel):
    __tablename__ = 'example'
    value: Mapped[Optional[str]] = mapped_column(doc="Name of the HTML body template.")
    value_2: Mapped[Optional[str]] = mapped_column(
        CheckConstraint('value_2 IS NULL OR value IS NOT NULL',
                        name='value_2_check'))

    next_value: Mapped[str]


# Create an in-memory SQLite database and create the table
engine = create_engine('sqlite:////tmp/test.db')
BaseModel.metadata.create_all(engine)

inspector = inspect(engine)
print(inspector.get_check_constraints("example"))
# 2.0.32 correct
# [{'sqltext': 'value_2 IS NULL OR value IS NOT NULL', 'name': 'value_2_check'}]
# 2.0.33, 2.0.34 incorrect
# [{'sqltext': 'value_2 IS NULL OR value IS NOT NULL), \n\tnext_value VARCHAR NOT NULL, \n\tid INTEGER NOT NULL, \n\tPRIMARY KEY (id', 'name': 'value_2_check'}]
```

Schema from the sqlite:
```
CREATE TABLE example (
	value VARCHAR,
	value_2 VARCHAR CONSTRAINT value_2_check CHECK (value_2 IS NULL OR value IS NOT NULL),
	next_value VARCHAR NOT NULL,
	id INTEGER NOT NULL,
	PRIMARY KEY (id)
);
```

### SQLAlchemy Version in Use

2.0.34

### DBAPI (i.e. the database driver)

sqlite

### Database Vendor and Major Version

sqlite

### Python Version

3.11.9

### Operating system

Linux

### To Reproduce

```python
See above
```

### Error

N/A

### Additional context

* #11678
* #11832

**Comment by CaselIT** [comment] 2024-09-05 08:44
Hi,

Thanks for reporting.

@zzzeek since the new system is based on the assumption that the constraints are always at the end, I'm not sure it can be adapted to support the fact that constraints can appear also between column definitions. Maybe it's causes less issues reverting it, at least until we have a better system that's not based on regexp?

**Comment by ziima** [comment] 2024-09-05 09:35
I was able to make a test, but I can't quite figure out, how to fix the code :-/

So, here's the test at least:
```diff
diff --git a/test/dialect/test_sqlite.py b/test/dialect/test_sqlite.py
index d2fb752fa..bc9ac3a99 100644
--- a/test/dialect/test_sqlite.py
+++ b/test/dialect/test_sqlite.py
@@ -1795,6 +1795,15 @@ class ConstraintReflectionTest(fixtures.TestBase):
                 "conSTRAINT my_fk FOreiGN KEY (  q  , p  )   "
                 "REFERENCes   i    (  x ,   y ))"
             )
+            # Column-inline check constraint
+            conn.exec_driver_sql(
+                "CREATE TABLE column_constr (\n"
+                "value INTEGER CONSTRAINT value_ck CHECK (value > 10),\n"
+                "another VARCHAR,\n"
+                "id INTEGER NOT NULL,\n"
+                "PRIMARY KEY (id)\n"
+                ")"
+            )

             meta = MetaData()
             Table("l", meta, Column("bar", String, index=True), schema="main")
@@ -2516,6 +2525,10 @@ class ConstraintReflectionTest(fixtures.TestBase):
                 {"sqltext": "prefix NOT GLOB '*[^-. /#,]*'", "name": None},
             ],
         )
+        eq_(
+            inspector.get_check_constraints("column_constr"),
+            [{"sqltext": "(value > 10)"}]
+        )

     @testing.combinations(
         ("plain_name", "plain_name"),
```

**Comment by CaselIT** [comment] 2024-09-05 09:42
The change was done to support newlines inside contraint text. The issue is that now the regexp includes subsequent columns inside the constraint value. I don't know if we can parse this using regexp. A parser may be needed to properly support this use case

**Comment by zzzeek** [comment] 2024-09-05 13:28
@CaselIT i just spent an hour with the regex, trying to use two regexes, agree we need to revert the regex for  #11832 as well as #11677, however we also need to add the test above as well as maintain the tests that were added for #11832 and #11677 but mark them as failing

SQLite documentation here if it does not already needs to include notes that constraint reflection can only handle constraints that are either on a full newline by themselves or are inline with a column definition but include no newlines of their own

cc @jeffh92 unfortunately we need to fully revert the code changes you made in efa344b as the regular expression approach here still fails to handle simple scenarios

**Comment by zzzeek** [comment] 2024-09-05 13:28
this is 2.0.35 however I'm not sure I can do this today or even tomorrow, I've run out of time this week, if people want to chip in with the above we can try to get a third release out

**Comment by CaselIT** [comment] 2024-09-05 14:47
@zzzeek sounds like the best option.

Maybe we can retry once we have a parser, since I was working on one for alembic in any case.

**Comment by sqla-tester** [comment] 2024-09-05 17:22
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**WIP: revert SQLite CHECK constraint changes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5495

**Comment by sqla-tester** [comment] 2024-09-05 19:46
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**revert SQLite CHECK constraint changes and add new tests** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5496

**Comment by CaselIT** [comment] 2024-09-06 06:26
@zzzeek we could maybe re-open the first issue https://github.com/sqlalchemy/sqlalchemy/issues/11677 since after this change it's still not supported

**Closed** 2024-09-08 00:54 UTC
Labels: bug, sqlite, blocker, reflection, regression
