### ISSUE TITLE
sslmode query param does not work for asyncpg DBAPI

### ISSUE THREAD

**Issue by igortg** [sqlalchemy/sqlalchemy#6275] opened 2021-04-15 01:50 UTC
**Describe the bug**
SQLAlchemy does not translate SSL query params to asyncpg drver, so the URL query params `sslmode` does not work (`ssl` should be used instead).

**Expected behavior**
I'd expect `sslmode` query param to be translated to `ssl` param of `asyncpg.connect` method. Seems that the `PGDialect` class already provides a hook for that here: https://github.com/sqlalchemy/sqlalchemy/blob/5e416bfa91e7dcba5a0adb5f275341ac9f83fe81/lib/sqlalchemy/dialects/postgresql/asyncpg.py#L957

**To Reproduce**
Just use and URL with `sslmode=required`.

```py
engine = create_async_engine('postgresql+asyncpg://postgres:masterkey@localhost/gqueue?sslmode=required')
async with engine.connect() as conn:
    result = await conn.execute(text(f"SELECT 1 FROM pg_database WHERE datname='{database_name}'")))
```

**Error**

```
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 558, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 747, in connect
    await_only(self.asyncpg.connect(*arg, **kw)),
TypeError: connect() got an unexpected keyword argument 'sslmode'
```

**Versions.**
 - OS: Windows
 - Python: 3.8.9
 - SQLAlchemy:
 - Database: Postgres
 - DBAPI: asyncpg

**Context**
Seems a minor issue but some Cloud services (e.g., DigitalOcean Apps Platform) provides the URL database as environment variables and uses the "standard" `sslmode`.

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-04-15 02:30
hey there -

the additional query string arguments as well as those passed to [connect_args](https://docs.sqlalchemy.org/en/14/core/engines.html#use-the-connect-args-dictionary-parameter) are DBAPI specific.   To know what these parameters are you would consult the usual reference documentation for that DBAPI in this case [asyncpg](https://magicstack.github.io/asyncpg/current/api/index.html) which illustrates the "ssl" argument.   "sslmode" happens to be the name of the argument that psycopg2 accepts, which does not apply here.

It's out of scope for SQLAlchemy to try to translate driver-specific arguments between different drivers as these drivers may add or change their APIs independently of SQLAlchemy itself nor is it a given that there is a reasonable way to translate every kind of parameter.

**Comment by CaselIT** [comment] 2021-04-15 08:24
>  Seems a minor issue but some Cloud services (e.g., DigitalOcean Apps Platform) provides the URL database as environment variables and uses the "standard" `sslmode`.

For this you can create an [URL](https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=create%20engine#sqlalchemy.engine.URL) using the `make_url` function, update the parameters to asyncpg liking and pass this url to `create_async_engine`.

Another alternative is to use a custom [creator function](https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=create%20engine#sqlalchemy.create_engine.params.creator)

**Comment by zzzeek** [comment] 2021-04-15 16:44
we had this same problem with the "postgres://" URL issue in heroku.    IMO these are issues on their end, DO should provide a version of their URL creator that works for different drivers such as asyncpg.

**Comment by igortg** [comment] 2021-04-15 17:17
FYI, asyncpg uses `sslmode` when you connect using a DSN with query params: https://github.com/MagicStack/asyncpg/blob/075114c195e9eb4e81c8365d81540beefb46065c/asyncpg/connection.py#L1747 ... So I think it was their intent to keep in sync with the psycopg2 standard.

Anyway... thanks for the attention. I'll probably go with @CaselIT solution.

**Closed** 2021-05-06 14:30 UTC
Labels: external driver issues, question

**Comment by karolzlot** [comment] 2021-10-02 03:29
@zzzeek the problem is currently no way exists to supply `sslrootcert` to asyncpg via sqlalchemy.

I am getting:

```
connect() got an unexpected keyword argument 'sslrootcert'
```

**Comment by CaselIT** [comment] 2021-10-02 12:56
I think you can pass custom arguments to  connect_args. You need to refer to asyncpg documentation regarding how to pass them though. From here, it seem it sequires a ssq context passed to the ssl parameter https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.connect

**Comment by karolzlot** [comment] 2021-10-02 16:47
Thank you, your are right, thanks to your advice I was able to found this example code:

https://github.com/cossacklabs/acra/blob/e8ca8203dfe92566762cb1638667a62c204e4263/tests/test.py#L228

**Comment by davidp1404** [comment] 2023-02-09 06:57
Hello, I faced this issue connecting Prefect 2.0 to an existing PG instance using auth with ssl certificates. 
An easy solution that worked for me was just mounting the certificate and key files in Prefect's pod under the "~/.postgresql/postgresql.{crt,key}" of the running user, as it is a default setting they were picked and problem solved. 
https://www.postgresql.org/docs/current/libpq-ssl.html

**Comment by MrCoffey** [comment] 2023-07-13 20:44
> Hello, I faced this issue connecting Prefect 2.0 to an existing PG instance using auth with ssl certificates. An easy solution that worked for me was just mounting the certificate and key files in Prefect's pod under the "~/.postgresql/postgresql.{crt,key}" of the running user, as it is a default setting they were picked and problem solved. https://www.postgresql.org/docs/current/libpq-ssl.html

Hey @davidp1404, I'm facing this issue trying to connect Prefect 2.0 to RDS and CloudSQL. I read your post [here](https://discourse.prefect.io/t/postgres-auth-with-certificates/2338) but cannot do this.

RDS and CloudSQL only provide me a `server-ca.pem` file, I'm placing that file under `~/.postgresql/` in a volumeMount inside my pod and I'm passing to prefect a connection string with the following format: `postgresql+asyncpg://user:pass@mydb-host.us-west-2.rds.amazonaws.com/dbname?sslmode=require&sslrootcert=~/.postgresql/server-ca.pem` which results in:

```
TypeError: connect() got an unexpected keyword argument 'sslmode'
```

when I change the parameter from `sslmode=require` to `ssl=require` then the error changes to:

```
TypeError: connect() got an unexpected keyword argument 'sslrootcert'

```

Should the name of the cert be called `postgresql.pem` or something?

For reference, I've installed Prefect using the [helm chart which only receives the configuration to the database using the string](https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-server/values.yaml#L268).

**Comment by CaselIT** [comment] 2023-07-16 09:14
@MrCoffey can you open a discussion with an example of what are you trying to set in the asyncpg connect?

**Comment by MrCoffey** [comment] 2023-07-17 15:24
@CaselIT, not sure if it's necessary. I resolved my issue. [Here](https://github.com/PrefectHQ/prefect-helm/issues/199) is my solution if there is someone else facing the same problem.

**Comment by CaselIT** [comment] 2023-07-17 16:41
Very well then!
