### ISSUE TITLE
Regression in lambda behavior between 1.4 and 2.0

### ISSUE THREAD

**Issue by bdraco** [sqlalchemy/sqlalchemy#9461] opened 2023-03-09 16:59 UTC
### Describe the bug

After upgrading to 2.x the race/thread-safety with the lambdas appears to have returned https://github.com/home-assistant/core/issues/89170

Previous issue https://github.com/sqlalchemy/sqlalchemy/issues/8098

`git diff -w rel_1_4_46..rel_2_0_5_post1 -- lib/sqlalchemy/sql/lambdas.py`

It looks like the lock was removed here

1.4.x: https://github.com/sqlalchemy/sqlalchemy/blob/b3bb55aaea9ee94e50f8db594d65c2bfcdb314ef/lib/sqlalchemy/sql/lambdas.py#L222

2.x:
https://github.com/sqlalchemy/sqlalchemy/blob/9c0715181de6f03543c7ac9038c481f57f773d49/lib/sqlalchemy/sql/lambdas.py#L274

```
         if rec is None:
-            if cache_key is not traversals.NO_CACHE:
-
-                with AnalyzedCode._generation_mutex:
-                    key = tracker_key + cache_key
-                    if key not in lambda_cache:
+            if cache_key is not _cache_key.NO_CACHE:
                 rec = AnalyzedFunction(
                     tracker, self, apply_propagate_attrs, fn
                 )
                 rec.closure_bindparams = bindparams
-                        lambda_cache[key] = rec
-                    else:
-                        rec = lambda_cache[key]
+                lambda_cache[tracker_key + cache_key] = rec
             else:
                 rec = NonAnalyzedFunction(self._invoke_user_fn(fn))
```

### SQLAlchemy Version in Use

2.0.5.post1

### DBAPI (i.e. the database driver)

all

### Database Vendor and Major Version

all

### Python Version

3.10/3.11

### Operating system

Linux

### To Reproduce

The ones from the previous issue should still be valid

### Error

Data is mixed up as before

**Comment by zzzeek** [comment] 2023-03-09 17:08
thanks for reporting, will try to look when i next have time

**Comment by zzzeek** [comment] 2023-03-09 18:44
OK wow we sure spent a lot of time on this !      what a long thread.   Im not sure if i had a self contained test case for the whole thing, it looks like we added some more mutexes as we went along.  

quite simply I forgot to add some of the changes to the "main" branch that were in the 1.4 version.   I'm still trying to figure out how i missed that and what the origin of each change was but likely i will just finish the patch and taht would be it.

**Comment by sqla-tester** [comment] 2023-03-09 18:57
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**repair broken lambda patch** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4502

**Comment by zzzeek** [comment] 2023-03-09 18:58
OK so I dont have your test env setup, the above patch adds the missing mutex code which also appears to change the lookup scheme used by AnalyzedCode.   if you can run the above gerrit through your environment again and make sure this fixes the issue (again), we will know we got it this time.  thanks!

**Comment by bdraco** [comment] 2023-03-09 19:47
99% sure that will do it. Working up a test case now

**Comment by bdraco** [comment] 2023-03-09 20:09
I have a reproducer.  Testing the change now

The key to making it happen again was

```
from sqlalchemy.sql import lambdas
from sqlalchemy import util

lambdas._closure_per_cache_key = util.LRUCache(1)
```

**Comment by zzzeek** [comment] 2023-03-09 20:09
hey it turns out your reproducer at https://github.com/bdraco/issue_8098/tree/version2 still works too

**Comment by bdraco** [comment] 2023-03-09 20:43
It appears to pass now with the lock

..but still fails even with the lock with https://github.com/bdraco/issue_8098/tree/issue_9461 which has the LRUCache cache size lowered to 1 https://github.com/bdraco/issue_8098/blob/55825a821eff35c6c336e0e3ed4e0eb27ca4d1cf/repro.py#L11

**Comment by zzzeek** [comment] 2023-03-09 21:31
well we are looking only for regressions since 1.4 right now, so if your test case fails on 1.4 also, that's something different

these implementations should be the same now

**Comment by bdraco** [comment] 2023-03-09 21:44
I'm still experimenting with the LRU issue and will open a new issue for that if I find something helpful.

I agree that a different issue.  I think your fix is good to go and it would be great to get a release with it soon.

Thanks!

**Comment by zzzeek** [comment] 2023-03-09 21:52
great thanks!

**Closed** 2023-03-10 21:05 UTC
Labels: bug, regression, lambda sql, next release

**Comment by bdraco** [comment] 2023-03-13 12:48
Thanks again for fixing this. Is there any chance we could get a 2.0.6 release soon?

Thank you

**Comment by zzzeek** [comment] 2023-03-13 12:51
I am hoping for today.   We had a problem with our last release so with this release I needed @CaselIT to be around in case there are problems with wheel builds, hence I didnt release over the weekend

**Comment by CaselIT** [comment] 2023-03-13 14:00
That wheel issue should be fixed, still a bit of work to be done on the wheel pipeline, but we should be good to release also without waiting for it

**Comment by zzzeek** [comment] 2023-03-13 17:51
2.0.6 is released, wheels will build in the upcoming hours
