### ISSUE TITLE
Wrong variable names for column valued/table valued function parameters on Oracle

### ISSUE THREAD

**Issue by sm-Fifteen** [sqlalchemy/sqlalchemy#8944] opened 2022-12-07 19:58 UTC
### Describe the bug

When using table-valued or column-valued functions in Oracle specifically, if the same function is used more than once, there is a collision in the parameter names being used. In the example below, `:ODCIVARCHAR2LIST_1, :ODCIVARCHAR2LIST_2, :ODCIVARCHAR2LIST_3` is rendered for both calls, even though the parameters are different. All 6 parameters are correctly passed with unique names, but the query fails because it cannot bind the leftover ones.

### To Reproduce

```python
foobar_col = func.SYS.ODCIVARCHAR2LIST("foo", "bar", "baz").column_valued("foobar")
snap_col = func.SYS.ODCIVARCHAR2LIST("snap", "crackle", "pop").column_valued("snap")
numbers_col = func.SYS.ODCINUMBERLIST(1, 2, 3).column_valued("numbers")

my_query = select(foobar_col, snap_col)

print(my_query) # Parameter names are unique
print(my_query.compile(dialect=oracle.dialect())) # Parameter names are repeated!!

with oci_engine.begin() as conn:
    res = conn.execute(my_query)
    print(res.fetchall())
```

### Error

```
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-01036: illegal variable name/number
[SQL: SELECT COLUMN_VALUE foobar, COLUMN_VALUE snap 
FROM TABLE (SYS.ODCIVARCHAR2LIST(:ODCIVARCHAR2LIST_1, :ODCIVARCHAR2LIST_2, :ODCIVARCHAR2LIST_3)) foobar, TABLE (SYS.ODCIVARCHAR2LIST(:ODCIVARCHAR2LIST_1, :ODCIVARCHAR2LIST_2, :ODCIVARCHAR2LIST_3)) snap]
[parameters: {'ODCIVARCHAR2LIST_1': 'foo', 'ODCIVARCHAR2LIST_2': 'bar', 'ODCIVARCHAR2LIST_3': 'baz', 'ODCIVARCHAR2LIST_4': 'snap', 'ODCIVARCHAR2LIST_5': 'crackle', 'ODCIVARCHAR2LIST_6': 'pop'}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
``` 

### Versions

- OS: Windows 10
- Python: 3.10.7
- SQLAlchemy: 1.4.44
- Database: Oracle 19c
- DBAPI : cx_oracle 8.3

### Additional context

Aditionnally, `COLUMN_VALUE` is always unqualified, meaning the above test query would fail even if the parameter numbering was correct. Below, the same example using two differently-named table-valued functions.

```py
>>> my_query2 = select(foobar_col, numbers_col)

>>> print(my_query2.compile(dialect=oracle.dialect()))
SELECT COLUMN_VALUE foobar, COLUMN_VALUE numbers 
FROM TABLE (SYS.ODCIVARCHAR2LIST(:ODCIVARCHAR2LIST_1, :ODCIVARCHAR2LIST_2, :ODCIVARCHAR2LIST_3)) foobar, TABLE (SYS.ODCINUMBERLIST(:ODCINUMBERLIST_1, :ODCINUMBERLIST_2, :ODCINUMBERLIST_3)) numbers


>>> with oci_engine.begin() as conn:
...     res = conn.execute(my_query2)
...     print(res.fetchall())

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00918: column ambiguously defined
[SQL: SELECT COLUMN_VALUE foobar, COLUMN_VALUE numbers 
FROM TABLE (SYS.ODCIVARCHAR2LIST(:ODCIVARCHAR2LIST_1, :ODCIVARCHAR2LIST_2, :ODCIVARCHAR2LIST_3)) foobar, TABLE (SYS.ODCINUMBERLIST(:ODCINUMBERLIST_1, :ODCINUMBERLIST_2, :ODCINUMBERLIST_3)) numbers]
[parameters: {'ODCIVARCHAR2LIST_1': 'foo', 'ODCIVARCHAR2LIST_2': 'bar', 'ODCIVARCHAR2LIST_3': 'baz', 'ODCINUMBERLIST_1': 1, 'ODCINUMBERLIST_2': 2, 'ODCINUMBERLIST_3': 3}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

**Comment by zzzeek** [comment] 2022-12-07 20:09
can confirm the first part of this is a dupe of #8827, and is fixed for the next 1.4 release.

for the second part, I'm not familiar with what syntax Oracle expects.

**Comment by zzzeek** [comment] 2022-12-07 20:16
for the second part it seems like it wants this:

```diff
diff --git a/lib/sqlalchemy/dialects/oracle/base.py b/lib/sqlalchemy/dialects/oracle/base.py
index 417ab84b7b..8e4d91e512 100644
--- a/lib/sqlalchemy/dialects/oracle/base.py
+++ b/lib/sqlalchemy/dialects/oracle/base.py
@@ -948,7 +948,8 @@ class OracleCompiler(compiler.SQLCompiler):
         text = super(OracleCompiler, self).visit_table_valued_column(
             element, **kw
         )
-        text = "COLUMN_VALUE " + text
+        text = text + ".COLUMN_VALUE "# + text
+        #text = "COLUMN_VALUE " + text
         return text
 
     def default_from(self):
```

so the Q is why was it the other way

**Comment by sm-Fifteen** [comment] 2022-12-07 20:16
> for the second part, I'm not familiar with what syntax Oracle expects.

Only something to disambiguate the `COLUMN_VALUE` column returned by all `TABLE(...)` expressions.

```sql
SELECT foobar.COLUMN_VALUE foobar, numbers.COLUMN_VALUE numbers 
FROM TABLE (SYS.ODCIVARCHAR2LIST('foo', 'bar', 'baz')) foobar, TABLE (SYS.ODCINUMBERLIST(1, 2, 3)) numbers
```

**Comment by zzzeek** [comment] 2022-12-07 20:17
that would be a label, and that alone doesnt fix it, nor is it needed.  the COLUMN_VALUE keyword preceding the table name seems to be the problem.

**Comment by sm-Fifteen** [comment] 2022-12-07 20:21
> that would be a label, and that alone doesnt fix it, nor is it needed. the COLUMN_VALUE keyword preceding the table name seems to be the problem.

`COLUMN_VALUE` isn't a keyword, it's just the name of the single column returned by `TABLE()`, much like how DUAL only has one column called DUMMY.

**Comment by zzzeek** [comment] 2022-12-07 20:30
oh, Oracle allows column labels without AS, so this "COLUMN_VALUE foobar" means "COLUMN_VALUE AS foobar".    I still dont know the origin of this syntax.

**Comment by CaselIT** [comment] 2022-12-07 20:33
> can confirm the first part of this is a dupe of #8827, and is fixed for the next 1.4 release (use the [1.4 branch](https://github.com/sqlalchemy/sqlalchemy/tree/rel_1_4) to resolve)

ah yes, the issue was that `% func` instead of `% text`. Well we were wondering how no - one reported it :D

**Comment by sm-Fifteen** [comment] 2022-12-07 20:34
> oh, Oracle allows column labels without AS, so this "COLUMN_VALUE foobar" means "COLUMN_VALUE AS foobar". I still dont know the origin of this syntax.

No doubt the same terrible place that gave us `FROM foo, bar WHERE foo.col(+) = bar.col` outer join syntax. I should have added it in my example query, but I left it out to keep it close to what SQLA originally gave me. The `AS` definitely makes it more readily understandable.

**Comment by zzzeek** [comment] 2022-12-07 20:36
well this is two issues, so this one is a dupe, the second part is an issue which is at #8945.

**Closed by zzzeek** 2022-12-07 20:36 UTC
Labels: bug, duplicate, oracle

**Comment by sm-Fifteen** [comment] 2022-12-07 21:04
> btw pg also allows select aliases without `AS`

Huh, yeah, look at that! The `AS` keyword is defined as optionnal for `<table reference>` clauses and `<query specification>`/`<as clause>` according to the SQL standard, so it's not actually required for tables nor aliases.

...and then Oracle doesn't mind if it's there or not for column names but throws an error if it's used for table aliases. Gotta love vendor uniformity!

Still, though, it's interesting that SQLA uses `AS` for column labels in Postgres but leaves it out for Oracle.

**Comment by zzzeek** [comment] 2022-12-07 22:41
> Still, though, it's interesting that SQLA uses `AS` for column labels in Postgres but leaves it out for Oracle.

I'm pretty sure very old Oracle versions would fail if you had "AS" in there.  We started with Oracle 8, and we still have the "(+) =" thing buried in there if oracle 8 is detected.
