### ISSUE TITLE
`poetry update` broken with 1.4.23

### ISSUE THREAD

**Issue by teucer** [sqlalchemy/sqlalchemy#6907] opened 2021-08-19 14:15 UTC
### Describe the bug

I have tried to update my dependencies with `poetry update`, getting `'EmptyConstraint' object has no attribute 'allows'` issue.

Pinning down the version of sqlalchemy to 1.4,22 fixes the issue.

I think recent changes in setup.cfg might cause the issue, more specifically the below line:

` greenlet != 0.4.17;python_version>="3" and platform_machine in 'x86_64 X86_64 aarch64 AARCH64 ppc64le PPC64LE amd64 AMD64 win32 WIN32'`

### To Reproduce

```shell
`poetry update`  # from an environment with e.g. version 1.4.22
```

### Error

`'EmptyConstraint' object has no attribute 'allows'`

### Versions

- OS: Windows 11
- Python: 3.9.6
- SQLAlchemy: 1.4.23

**Comment by CaselIT** [comment] 2021-08-19 14:26
Hi,

duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/6903

**Closed by CaselIT** 2021-08-19 14:26 UTC
Labels: requires triage
