### ISSUE TITLE
sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "datetime.datetime(2022, 12, 17, 9, 52, 18, 807939)" with datatype DATETIME

### ISSUE THREAD

**Issue by mzebrak** [sqlalchemy/sqlalchemy#8998] opened 2022-12-17 12:30 UTC
### Describe the bug

We got not locked version of sqlalchemy in project setup files. There is `sqlalchemy~=1.4.27`  specified in the setup.cfg and previously there were no issues while working with `sqlalchemy==1.4.44`, but  when our CI fetched `sqlalchemy==1.4.45`, this error appears.

### To Reproduce

```python
Just try to insert a python datetime object into a database. It goes something like this:


async def insert_something(database: Db, args: argparse.Namespace, timestamp: datetime.datetime):
    await insert_row(
        database=database,
        table='public.something',
        cols_args={
            'job_id': args.job_id,
            'description': args.desc,
            'execution_environment_description': args.exec_env_desc,
            'timestamp': timestamp,
            'server_name': args.server_name,
            'app_version': args.app_version,
            'testsuite_version': args.testsuite_version,
            'runner': socket.gethostname(),
        },
        additional=' ON CONFLICT (job_id) DO NOTHING',
    )

async def insert_row(database: Db, table: str, cols_args: dict, additional: str = '') -> None:
    cols, params = retrieve_cols_and_params(cols_args)
    sql = f'INSERT INTO {table} ({cols}) VALUES ({params}) {additional};'
    await database.query(sql, **cols_args)

def retrieve_cols_and_params(cols_args: dict[str, Any]) -> tuple[str, str]:
    fields = list(cols_args.keys())
    cols = ', '.join(fields)
    params = ', '.join([f':{k}' for k in fields])
    return cols, params


if __name__ == "__main__":
    timestamp = datetime.datetime.now()
    await insert_something(database=database, args=args, timestamp=timestamp)
```

### Error

```
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py:503: in compile
    return self._compiler(dialect, **kw)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py:567: in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:807: in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:464: in __init__
    self.string = self.process(self.statement, **compile_kwargs)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:499: in process
    return obj._compiler_dispatch(self, **kwargs)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py:82: in _compiler_dispatch
    return meth(self, **kw)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:1650: in visit_textclause
    BIND_PARAMS.sub(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:1634: in do_bindparam
    return self.process(textclause._bindparams[name], **kw)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:499: in process
    return obj._compiler_dispatch(self, **kwargs)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py:82: in _compiler_dispatch
    return meth(self, **kw)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:2485: in visit_bindparam
    ret = self.render_literal_bindparam(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:2593: in render_literal_bindparam
    return self.render_literal_value(value, bindparam.type)
/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:2436: in render_literal_value
    value = super(PGCompiler, self).render_literal_value(value, type_)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <sqlalchemy.dialects.postgresql.psycopg2.PGCompiler_psycopg2 object at 0x7f73844cd940>
value = datetime.datetime(2022, 12, 17, 9, 52, 18, 807939), type_ = DateTime()
    def render_literal_value(self, value, type_):
        """Render the value of a bind parameter as a quoted literal.
    
        This is used for statement sections that do not accept bind parameters
        on the target driver/database.
    
        This should be implemented by subclasses using the quoting services
        of the DBAPI.
    
        """
    
        processor = type_._cached_literal_processor(self.dialect)
        if processor:
            try:
                return processor(value)
            except Exception as e:
                util.raise_(
                    exc.CompileError(
                        "Could not render literal value "
                        '"%s" '
                        "with datatype "
                        "%s; see parent stack trace for "
                        "more detail."
                        % (
                            sql_util._repr_single_value(value),
                            type_,
                        )
                    ),
                    from_=e,
                )
    
        else:
>           raise exc.CompileError(
                "No literal value renderer is available for literal value "
                '"%s" with datatype %s'
                % (sql_util._repr_single_value(value), type_)
            )
E           sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "datetime.datetime(2022, 12, 17, 9, 52, 18, 807939)" with datatype DATETIME
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/compiler.py:2627: CompileError
``` 

### Versions

- OS: ubuntu:20.04
- Python: 3.8
- SQLAlchemy: 1.4.45
- Database: PostgreSQL 12
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):     aiopg==1.3.5

**Comment by zzzeek** [comment] 2022-12-17 15:25
we saw this on a chat.   The above case is not reproducible since it is only out-of-context fragments of code, however, what you are doing might look something like this:

```py
from sqlalchemy import DATETIME
from sqlalchemy.dialects import postgresql
from sqlalchemy import literal
import datetime

x = literal(datetime.datetime.now(), DATETIME)

print(x.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
```

in 1.4.45 this raises:

```
 File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py", line 2436, in render_literal_value
    value = super(PGCompiler, self).render_literal_value(value, type_)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 2678, in render_literal_value
    raise exc.CompileError(
sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "datetime.datetime(2022, 12, 17, 10, 23, 56, 506811)" with datatype DATETIME

```

in 1.4.44 this raises:

```
 File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py", line 2441, in render_literal_value
    value = super(PGCompiler, self).render_literal_value(value, type_)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 2595, in render_literal_value
    raise NotImplementedError(
NotImplementedError: Don't know how to literal-quote value datetime.datetime(2022, 12, 17, 10, 24, 52, 249186)

```

so nothing is really different here except the exception being raised, which is from #8800.

you want to look in your actual code for where you are catching NotImplementedError and update it.

**Comment by zzzeek** [comment] 2022-12-17 15:26
if you can provide a complete [MCVE](http://stackoverflow.com/help/mcve) that I can run, single file, no dependencies, no external data, I just run it, shows the problem, I can help further with adjustments that may be needed.   closing this for now.

**Closed by zzzeek** 2022-12-17 15:26 UTC
Labels: sql, expected behavior

**Comment by mzebrak** [comment] 2022-12-17 15:30
Like i said, there were no issues in 1.4.44, so it's a dependency of going into 1.4.45

**Comment by zzzeek** [comment] 2022-12-17 15:31
that tells me nothing about what you'd like me to do.

**Comment by mzebrak** [comment] 2022-12-17 15:49
You're right, I found it. It comes from this piece of code:

```
            try:
                sql = str(
                    sqlalchemy.text(sql)
                    .bindparams(**kwargs)
                    .compile(dialect=sqlalchemy.dialects.postgresql.dialect(), compile_kwargs={"literal_binds": True})
                )
                result = await conn.execute(sql)
            except NotImplementedErrorr:
                sql = str(sqlalchemy.text(sql).bindparams(**kwargs).compile(compile_kwargs={"literal_binds": True}))
                result = await conn.execute(sql)
 ```
 
 Updating the caught exception will do the case here. But are there any plans to make such a renderer for PostgreSQL dialect?

**Comment by zzzeek** [comment] 2022-12-17 15:55
yes it's in 2.0, see https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-206ec1f2af3a0c93785758c723ba356f  / #5052, the changelog here seems to be mis-classified

**Comment by mzebrak** [comment] 2022-12-17 16:04
thanks, I appreciate

**Comment by zzzeek** [comment] 2022-12-17 16:12
FYI you should really modify your code to not use literal_binds for statements that are being executed.   SQLAlchemy's literal rendering functions are not security audited.  Please see https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#rendering-bound-parameters-inline for guidelines.
