### ISSUE TITLE
Intermittent "test_update_to_expression_two" failures

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5509] opened 2020-08-12 22:19 UTC
My first patchset for [Gerrit 2143](https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2143) had a single failure in

[sqlalchemy_gerrit/cext=cext,db=mysql,pyv=py27](https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=cext,db=mysql,pyv=py27/5459/)

specifically [this](https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=cext,db=mysql,pyv=py27/5459/testReport/junit/test.sql.test_update/UpdateTest/test_update_to_expression_two/):

``` none
Traceback (most recent call last):
  File "/home/jenkins/workspace/sqlalchemy_gerrit/20384d2e/test/sql/test_update.py", line 886, in test_update_to_expression_two
    checkpositional=(5, 7, 10, 18),
  File "/home/jenkins/workspace/sqlalchemy_gerrit/20384d2e/.tox/py27-cext-mysql/lib/python2.7/site-packages/sqlalchemy/testing/assertions.py", line 439, in assert_compile
    eq_(cc, result, "%r != %r on dialect %r" % (cc, result, dialect))
  File "/home/jenkins/workspace/sqlalchemy_gerrit/20384d2e/.tox/py27-cext-mysql/lib/python2.7/site-packages/sqlalchemy/testing/assertions.py", line 207, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: u'UPDATE foo SET data2[?]=?, data1[?]=?' != 'UPDATE foo SET data1[?]=?, data2[?]=?' on dialect <sqlalchemy.engine.default.StrCompileDialect object at 0x7f35acce5c10>
assert 'UPDATE foo S...?, data1[?]=?' == 'UPDATE foo SE...?, data2[?]=?'
  - UPDATE foo SET data2[?]=?, data1[?]=?
  + UPDATE foo SET data1[?]=?, data2[?]=?
```

I seemed to recall having seen a failure like that before, so I did a `recheck` and CI failed again, but this time it wasn't "db=mysql,pyv=py27" that failed, it was

[sqlalchemy_gerrit/cext=nocext,db=sqlite-postgresql,pyv=py27](https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=nocext,db=sqlite-postgresql,pyv=py27/5460/)

Same test failing, both py27, but the first time it was mysql that failed and postgresql that passed, while on `recheck` it was the other way around.

I wonder if this is somehow similar to the recent behaviour seen in #5411 where "the order of things" can be non-deterministic based on [hash randomization](https://github.com/sqlalchemy/sqlalchemy/issues/5411#issuecomment-646969210)?

**Comment by zzzeek** [comment] 2020-08-12 23:00
I've altered this test to be sorted in 180ae7c1a53385f72b0047496ac001ec5099cc3e so if you rebase on that it should work now.

**Comment by gordthompson** [comment] 2020-08-12 23:15
Current Gerrit_2143 is based on ea16e3f8 which I *think* is a descendant of 180ae7c1 (if I'm reading this correctly):

``` none
Gord@GORD-HP MINGW64 ~/git/sqla-gerrit (mssql_temp_reflect)
$ git log --graph --oneline --all
* ea16e3f84 (HEAD -> mssql_temp_reflect) Improve reflection for mssql temporary tables
*   c7cf63d64 (origin/master, master) Merge "Break scalars() and mappings() into separate objects"
|\
| * 6d4dcbb40 Break scalars() and mappings() into separate objects
* |   cf3a2a991 Merge "Fix mysql CREATE TABLE / COLLATE issue"
|\ \
| |/
|/|
| * 32e0b128f Fix mysql CREATE TABLE / COLLATE issue
* | 180ae7c1a Correct for update.ordered_values() and use in new test
* | 5b44be7a1 update deterministic sort ordering doc
|/
* 71f14f6de Fix typos
...
```

**Comment by zzzeek** [comment] 2020-08-12 23:22
it is but I can't make this test fail under python 2 with hashseed=random, the values are ordered.  I dont see any way they can come out as unordered, can you do a recheck?

**Comment by zzzeek** [comment] 2020-08-12 23:30
well it's still not doing the right thing anyway though it is deterministically ordered, ill push another change

**Comment by zzzeek** [comment] 2020-08-12 23:37
alrighty ordered paramerters seem to be 100% broken

**Comment by zzzeek** [comment] 2020-08-12 23:42
dupe of #5510

**Closed by zzzeek** 2020-08-12 23:42 UTC
Labels: bug, tests
