### ISSUE TITLE
Is raiseload the correct way to prevent perfomance regressions?

### ISSUE THREAD

**Issue by fschulze** [sqlalchemy/sqlalchemy#5724] opened 2020-11-24 11:50 UTC
I was bitten by #5208 today. I thought that raiseload only applies per query not per object lifetime in a transaction. For optimization purposes and to prevent further regressions I left raiseload in my application. A totally unrelated query now raised.

What is the best practice to use raiseload to prevent performance regressions? Do I have to add it conditionally somehow to only apply it in tests and during development? Is there a better way to achieve the same?

**Comment by zzzeek** [comment] 2020-11-24 15:00
hey there, this is a dupe of said #5208.  I've added information about the populate_existing() method which is what you should do in the case that you want to change the options applied to objects during a query.

**Closed by zzzeek** 2020-11-24 15:00 UTC
Labels: duplicate, question

**Comment by zzzeek** [comment] 2020-11-24 15:56
also note that if you've applied raiseload() to a collection, then another query wants this collection to be present, the best approach is to apply an eager loader which will load the collection for that object, leaving the "raiseload" option in place if the object is later expired.  populate_existing is not needed.
