### ISSUE TITLE
 offset not working

### ISSUE THREAD

**Issue by wanglong001** [sqlalchemy/sqlalchemy#6279] opened 2021-04-15 10:03 UTC
**Describe the bug**

```py
db.session.query(***) \
            .outerjoin(***, and_(***.model_type_id == ***.id)).filter(
            ***.model_type_id == model_type_id).order_by(
            ***.create_time.desc()).limit(size).offset((page-1)*size).all()
# Same with paginate() 
```
The parameters of the first run are limit=20, offset=0, no matter what value is passed in limit and offset later, it will not take effect.
![image](https://user-images.githubusercontent.com/14817376/114850569-7fc33980-9e13-11eb-8468-1a63e7ed8ab3.png)
![image](https://user-images.githubusercontent.com/14817376/114853180-1f81c700-9e16-11eb-9567-8368954974f9.png)
![image](https://user-images.githubusercontent.com/14817376/114853279-345e5a80-9e16-11eb-9019-e5c24db947c9.png)

_But as long as the first offset is not 0, it can take effect_

**Expected behavior**

Expect limit and offset to take effect no matter what value is passed
![image](https://user-images.githubusercontent.com/14817376/114850452-5acec680-9e13-11eb-8033-f06a93dd2110.png)

**Versions.**
 - OS: ubuntu18.04
 - Python: python3.8.5
 - SQLAlchemy:  Flask-SQLAlchemy         2.4.4
 - Database: sql server(Microsoft SQL Azure (RTM) - 12.0.2000.8 Feb 20 2021 17:51:58 Copyright (C) 2019 Microsoft Corporation)
 - DBAPI: {ODBC Driver 17 for SQL Server}

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment] 2021-04-15 10:53
Hi,

I think this a duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/6265. It will be fixed in the next release.
For now you can work-around it by doing `offset(None if size is 0 else (page-1)*size)`

**Closed** 2021-04-15 10:53 UTC
Labels: SQL Server, bug, duplicate, regression

**Comment by wanglong001** [comment] 2021-04-15 11:33
@CaselIT  thanks
