### ISSUE TITLE
SQLAlchemy doesn't respect `prepared_statement_name_func` for calls to `set_type_codec` in asyncpg

### ISSUE THREAD

**Issue by CobaltCause** [sqlalchemy/sqlalchemy#11141] opened 2024-03-11 23:31 UTC
### Describe the bug

`prepared_statement_name_func` isn't respected for all database queries issued via asyncpg, in particular I noticed this for calls to the `set_type_codec` function.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#prepared-statement-name

### SQLAlchemy Version in Use

2.0.27

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PgBouncer/PostgreSQL 14

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
engine = create_async_engine(
    url="postgresql+asyncpg://...",
    connect_args={
        "prepared_statement_name_func": lambda: "",
    },
)

async with engine.connect() as conn:
    print("boom")
```

### Error

I added a call to `traceback.print_stack()` in asyncpg's `_get_statement` function (called by `set_type_codec` to generate the name of the prepared statement) that triggers when a prepared statement is created that doesn't have the name configured by `prepared_statement_name_func` and this is the relevant section of the traceback I got:

```
  [my own code]
    async with self._engine.connect() as conn:
  File "/virtualenv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/virtualenv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 270, in start
    await greenlet_spawn(self.sync_engine.connect)
  File "/virtualenv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    value = await result
  File "/virtualenv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 1174, in setup_asyncpg_json_codec
    await asyncpg_connection.set_type_codec(
  File "/virtualenv/lib/python3.11/site-packages/asyncpg/connection.py", line 1347, in set_type_codec
    typeinfo = await self._introspect_type(typename, schema)
  File "/virtualenv/lib/python3.11/site-packages/asyncpg/connection.py", line 551, in _introspect_type
    rows = await self._execute(
  File "/virtualenv/lib/python3.11/site-packages/asyncpg/connection.py", line 1802, in _execute
    result, _ = await self.__execute(
  File "/virtualenv/lib/python3.11/site-packages/asyncpg/connection.py", line 1900, in __execute
    result, stmt = await self._do_execute(
  File "/virtualenv/lib/python3.11/site-packages/asyncpg/connection.py", line 1933, in _do_execute
    stmt = await self._get_statement(
  File "/virtualenv/lib/python3.11/site-packages/asyncpg/connection.py", line 438, in _get_statement
    traceback.print_stack()
``` 

### Additional context

To be fair to SQLAlchemy, asyncpg doesn't currently (version 0.29.0) expose the functionality required to fix this. However, https://github.com/MagicStack/asyncpg/pull/1131 should make this problem possible to solve.

**Comment by zzzeek** [comment] 2024-03-11 23:56
hi -

This is a passthrough to asyncpg and I dont see any error in any case, returning a blank string seems to behave the same as returning None, the whole thing is ignored.  If you return a fixed non-blank string, asyncpg raises an error since we use more than one statement just at connect time and you get `prepared statement "x" already exists`.   

It seems nonsensical to have a prepared_statement_name_func that returns a fixed string in any case so I dont see what is unexpected here nor what action SQLAlchemy would take.

**Comment by zzzeek** [comment] 2024-03-12 00:06
OK it looks like in #11142 you are claiming the set_type_codec function has a problem, your test case and stack trace dont show this so I would need to see what the problem is.

**Comment by zzzeek** [comment] 2024-03-12 00:20
stack trace please?  error message ?    send a pgbouncer file I can run pgb with, run a py script, and see it happen?

also it still makes no sense to send a fixed string, or a blank string for prepared staement func, and these codec names are not prepared statements

part of the problem here is that "possible solution that looks wrong" is being mixed with "problem, poorly described"

lets get the problem fully communciated first

**Comment by zzzeek** [comment] 2024-03-12 00:21
cc @CaselIT

**Comment by CaselIT** [comment] 2024-03-12 06:49
Looking at the asyncpg code it doesn't seem to use prepared statements for these introspection queries. I may be wrong though.

And even if it did nothing can be done on sqlalchemy until that parameters is added by asyncpg, of that pr is merged.

What is the error raises by postgresql here? Do you have an example stack trace that led you to open this issue?

**Comment by CaselIT** [comment] 2024-04-28 06:52
The issue is of asyncpg, so there is nothing sqlalchemy can do until that's fixed on the driver side

**Closed by CaselIT** 2024-04-28 06:52 UTC
Labels: postgresql, expected behavior, awaiting info, asyncio
