### ISSUE TITLE
[BUG] Regression password with `@` character fails to connect

### ISSUE THREAD

**Issue by gbmarc1** [sqlalchemy/sqlalchemy#6574] opened 2021-06-03 01:05 UTC
**Describe the bug**
When a password contains a `@` character.  Sqlalchemy with a string url cannot connect to the database.

I greatly suspect that it was induced by #6482.

Was working fine in 1.4.15.

**To Reproduce**

```py
    url = (
        "mssql+pyodbc://"
        "SA:P@my_password@127.0.0.1:1433/master"
        "?driver=ODBC Driver 17 for SQL Server"
    )
``` 

**Error**
``
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

``

**Versions.**
 - OS:
 - Python: 3.8
 - SQLAlchemy: 1.4.17
 - Database: mssql
 - DBAPI: pyodbc

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-06-03 02:13
hi there -

you have to URL escape special characters in passwords such as @ signs, see https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls for details.

your password happened to be allowed previously due to a bug which was #6567.  This fix has affected some projects who were erroneously using @ signs in their passwords without escaping them however there are no plans to revert this fix.

**Comment by zzzeek** [comment] 2021-06-03 02:15
issue here is a full dupe of #6567

**Closed by zzzeek** 2021-06-03 02:15 UTC
Labels: duplicate, question

**Comment by gbmarc1** [comment] 2021-06-03 12:15
You are right to close this! hehe thanks for the like to the doc
