### ISSUE TITLE
Using `select(Model).from_statement(stmt)` no longer works when `stmt` contains a labeled column

### ISSUE THREAD

**Issue by bryanforbes** [sqlalchemy/sqlalchemy#9217] opened 2023-02-01 22:02 UTC
### Describe the bug

When attempting to use `select(Model).from_statement(stmt)` where `stmt` is selecting from a subquery, running a function on one of the subquery's columns, and labeling the result of that function, the ORM sets the labeled column as deferred and tries to refresh.

### To Reproduce

```python
from __future__ import annotations

import asyncio

from sqlalchemy import Computed, Text, func, select, text as _sa_text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(MappedAsDataclass, DeclarativeBase):
    ...


class Section(Base):
    __tablename__ = 'sections'

    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    text: Mapped[str] = mapped_column(Text)
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR, Computed(func.to_tsvector(_sa_text("'english'"), func.trim(text))), init=False
    )


engine = create_async_engine(
    "postgresql+asyncpg://user:xxxxxx@localhost/dbname", echo=True
)


async def main() -> None:
    async with AsyncSession(engine) as session:
        session.add(Section(text='faith'))
        await session.flush()
        tsquery = func.plainto_tsquery(_sa_text("'english'"), 'faith')
        section_query = (
            select(Section)
            .filter(
                Section.search_vector.bool_op('@@')(tsquery),
            )
            .subquery()
        )
        headline_query = select(
            section_query.c.id,
            func.ts_headline(
                _sa_text("'english'"),
                section_query.c.text,
                tsquery,
                _sa_text("'StartSel=**, StopSel=**'"),
            ).label('text'),
            section_query.c.search_vector,
        )
        aliased_query = select(Section).from_statement(headline_query)

        result = await session.scalars(aliased_query)

        print(list(result))


asyncio.run(main())
```

### Error

```
2023-02-01 16:00:49,166 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-02-01 16:00:49,166 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-02-01 16:00:49,167 INFO sqlalchemy.engine.Engine select current_schema()
2023-02-01 16:00:49,167 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-02-01 16:00:49,169 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-02-01 16:00:49,169 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-02-01 16:00:49,170 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-02-01 16:00:49,172 INFO sqlalchemy.engine.Engine SELECT anon_1.id, ts_headline('english', anon_1.text, plainto_tsquery('english', $1::VARCHAR), 'StartSel=**, StopSel=**') AS text, anon_1.search_vector 
FROM (SELECT confession_sections.id AS id, confession_sections.text AS text, confession_sections.search_vector AS search_vector 
FROM confession_sections 
WHERE confession_sections.search_vector @@ plainto_tsquery('english', $1::VARCHAR)) AS anon_1
2023-02-01 16:00:49,172 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ('faith',)
2023-02-01 16:00:49,195 INFO sqlalchemy.engine.Engine SELECT confession_sections.text AS confession_sections_text 
FROM confession_sections 
WHERE confession_sections.id = $1::INTEGER
2023-02-01 16:00:49,195 INFO sqlalchemy.engine.Engine [generated in 0.00010s] (1,)
2023-02-01 16:00:49,195 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):                                              
  File "/Users/bryan/Projects/Erasmus/experiments/ts_headline.py", line 57, in <module>
    asyncio.run(main())                                                         
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()                                                      
  File "/Users/bryan/Projects/Erasmus/experiments/ts_headline.py", line 54, in main
    print(list(result))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/dataclasses.py", line 405, in wrapper
    result = user_function(self)
  File "<string>", line 3, in __repr__
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 561, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1074, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1104, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 807, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1591, in load_scalar_attributes
    result = load_on_ident(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 480, in load_on_ident
    return load_on_pk_identity(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 252, in orm_execute_statement
    result = conn.execute(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2328, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 515, in execute
    self._adapt_connection.await_(
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 93, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
Exception ignored in: <function Connection.__del__ at 0x1024e9b40>
Traceback (most recent call last):
  File "/Users/bryan/Projects/Erasmus/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 130, in __del__
ResourceWarning: unclosed connection <asyncpg.connection.Connection object at 0x1024a6500>; run in asyncio debug mode to show the traceback of connection origin
Exception ignored in: <function _SelectorTransport.__del__ at 0x100fea0e0>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 710, in __del__
ResourceWarning: unclosed transport <_SelectorSocketTransport fd=8>
Exception ignored in: <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58781, 0, 0), raddr=('::1', 5432, 0, 0)>
ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58781, 0, 0), raddr=('::1', 5432, 0, 0)>
Exception ignored in: <coroutine object AsyncAdapt_asyncpg_cursor._prepare_and_execute at 0x1027505f0>
RuntimeWarning: coroutine 'AsyncAdapt_asyncpg_cursor._prepare_and_execute' was never awaited
``` 

### Versions

- OS: macOS 13.1
- Python: 3.10.9
- SQLAlchemy: 2.0.1
- Database: PostgreSQL 15.1
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg

**Comment by CaselIT** [comment] 2023-02-01 22:23
This seems a regression. This is runnable in both 1.4 and 2.0 and works correctly in 1.4 but not on v2
```py
from __future__ import annotations

from sqlalchemy import (
    Computed,
    Text,
    func,
    select,
    text as _sa_text,
    create_engine,
    Column,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Session, declarative_base
from sqlalchemy.sql.sqltypes import Integer

Base = declarative_base()

class Section(Base):
    __tablename__ = "sections"

    id = Column(Integer, primary_key=True)
    text = Column(Text)
    search_vector = Column(
        TSVECTOR,
        Computed(func.to_tsvector(_sa_text("'english'"), func.trim(text))),
    )

    def __repr__(self) -> str:
        return f"Section({self.id=}, {self.text=}, {self.search_vector=})"

engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

def main(conn) -> None:
    with Session(conn) as session:
        session.add(Section(text="faith"))
        session.flush()
        tsquery = func.plainto_tsquery(_sa_text("'english'"), "faith")
        section_query = (
            select(Section)
            .filter(
                Section.search_vector.bool_op("@@")(tsquery),
            )
            .subquery()
        )
        headline_query = select(
            section_query.c.id,
            func.ts_headline(
                _sa_text("'english'"),
                section_query.c.text,
                tsquery,
                _sa_text("'StartSel=**, StopSel=**'"),
            ).label("text"),
            section_query.c.search_vector,
        )
        aliased_query = select(Section).from_statement(headline_query)
        result = session.scalars(aliased_query)

        print("----------")
        print(vv := list(result))
        assert vv[0].text == "**faith**"

with engine.connect() as conn:
    Base.metadata.create_all(conn)
    main(conn)
```

**Comment by zzzeek** [comment] 2023-02-01 23:00
well we would assume it's not matching up the column "text" here so it's just not getting loaded.

i dont think we quite expected from_statement() to do the text matching thing in this specific case, this would usually be from an `aliased()` that include `adapt_on_names=True`.   or `from_statement(text().columns(...))`.   it seems like `from_statement(select(foo.label('a_column')))` might need more hints that we are matching on name.   or we figure out what was in 1.4; in 1.4 it likely figured out that the "text" expression derived from the Section.text column originally.

**Comment by zzzeek** [comment] 2023-02-01 23:03
here, this works instead, which should be good enough for now (it makes an extra subquery but should not be that big of  a deal unless this query is at the core of your high speed trading system)

```py
        ent = aliased(Section, headline_query.subquery(), adapt_on_names=True)
        aliased_query = select(ent)

```

**Comment by bryanforbes** [comment] 2023-02-01 23:05
> it makes an extra subquery

I had already confirmed that `aliased()` works (I probably should have added that to the additional info). I was trying to avoid the extra sub-query.

**Comment by zzzeek** [comment] 2023-02-01 23:07
well now this is funny.

if i convert the program to 1.4 style w/o the dataclass thing and using Column, it *works* in 2.0

**Comment by zzzeek** [comment] 2023-02-01 23:08
OH, because it's not a dataclss and has no ``__Repr__()``, got it

**Comment by zzzeek** [comment] 2023-02-01 23:11
this seems to be the commit... 2acc9ec1281b2818bd44804f040d94ec

im still a little suspicious here

**Comment by CaselIT** [comment] 2023-02-01 23:19
Not sure if it makes sense have the ability to specify that adapt_on_names flag in from_statement

**Comment by sqla-tester** [comment] 2023-02-01 23:19
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**consider impact of adapt_on_names for all fromstatements** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4414

**Comment by zzzeek** [comment] 2023-02-01 23:20
yeah it's an ORM thing so having it be a kw in from_statement() would be awkward

**Comment by bryanforbes** [comment] 2023-02-02 00:06
> but of course people are putting anything.label("mycolumn") in statements so..

😂

**Comment by zzzeek** [comment] 2023-02-02 14:15
everything passed so I will just revert this parameter change and add a new test for this case.

**Comment by CaselIT** [comment] 2023-02-02 18:47
so the plan is to make it work like 1.4, not adding a configuration option, light?

**Comment by zzzeek** [comment] 2023-02-02 19:22
yes

**Comment by CaselIT** [comment] 2023-02-02 19:25
I would add the tests for this, but I'm not sure how to make it meaningful (ie ensure that with that option to False it would fail)

**Comment by zzzeek** [comment] 2023-02-02 19:40
it would be an ORM test in test/orm/test_froms.py that includes a select() statement that has a funciton like `func.lower('foo').label("colname")` inside of it, which is expected to match an attribute name on the class being loaded.  then you look in `item.__dict__['colname']` to see that it loaded.

**Comment by CaselIT** [comment] 2023-02-02 21:30
added a test for that

**Closed** 2023-02-03 19:39 UTC
Labels: bug, orm, regression, next release
