### ISSUE TITLE
Recreating a CTE with the same name uses the original version.

### ISSUE THREAD

**Issue by baarney** [sqlalchemy/sqlalchemy#11471] opened 2024-06-11 01:03 UTC
### Describe the bug

If I have a dynamic CTE that is created each time with different filters, only the first one is ever used.

Recreated this example using sqlite but I am, using mysql+pymysql in my real code.

### SQLAlchemy Version in Use

2.0.27

### DBAPI (i.e. the database driver)

mysql+pymysql

### Database Vendor and Major Version

MySQL 8

### Python Version

3.12

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import String, create_engine, select, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Session


class Base(DeclarativeBase):
    pass


class Widget(Base):
    __tablename__ = 'widget'

    id: Mapped[int] = mapped_column(primary_key=True)
    color: Mapped[str] = mapped_column(String(8))
    name: Mapped[str] = mapped_column(String(30))

    def __repr__(self):
        return f"<Widget(id={self.id}, name={self.name})>"


engine = create_engine("sqlite://", echo=True)


def create_data():
    Base.metadata.create_all(engine)
    with Session(engine) as session:
        session.add_all([
            Widget(color="red", name="Red test"),
            Widget(color="green", name="Green test"),
            Widget(color="blue", name="Blue test")
        ])
        session.commit()


def select_data(color=None, name=None):
    vw = select(Widget)
    if color:
        vw = vw.filter(Widget.color == color)
    if name:
        vw = vw.filter(Widget.name.ilike(name + "%"))

    with Session(engine) as session:
        cte_name = "widget_vw"
        sel_from_cte = (
            text(f"select * from {cte_name}")
            .columns(Widget.id, Widget.color, Widget.name)
            .add_cte(vw.cte(cte_name))
        )
        sel = select(Widget).from_statement(sel_from_cte)

        print(f"==== {sel}")
        vals = session.execute(sel).scalars().all()

        print(f"==== {vals}")


if __name__ == "__main__":
    create_data()
    select_data(color="red")
    select_data(name="Blue")
```

### Error

The second call to `select_data` prints the red widget not the blue one. On the second call, the SQL emitted from the print statement correctly uses the name filter:

```
==== WITH widget_vw AS 
(SELECT widget.id AS id, widget.color AS color, widget.name AS name 
FROM widget 
WHERE lower(widget.name) LIKE lower(:name_1))
 select * from widget_vw
```

But the SQL emitted from the trace shows it is still using the first CTE with the colour filter:

```
INFO sqlalchemy.engine.Engine WITH widget_vw AS 
(SELECT widget.id AS id, widget.color AS color, widget.name AS name 
FROM widget 
WHERE widget.color = ?)
 select * from widget_vw
```

Full log:
```
2024-06-11 11:01:24,061 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-06-11 11:01:24,061 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("widget")
2024-06-11 11:01:24,061 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-06-11 11:01:24,061 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("widget")
2024-06-11 11:01:24,061 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-06-11 11:01:24,062 INFO sqlalchemy.engine.Engine 
CREATE TABLE widget (
	id INTEGER NOT NULL, 
	color VARCHAR(8) NOT NULL, 
	name VARCHAR(30) NOT NULL, 
	PRIMARY KEY (id)
)


2024-06-11 11:01:24,062 INFO sqlalchemy.engine.Engine [no key 0.00004s] ()
2024-06-11 11:01:24,062 INFO sqlalchemy.engine.Engine COMMIT
2024-06-11 11:01:24,063 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine INSERT INTO widget (color, name) VALUES (?, ?) RETURNING id
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine [generated in 0.00007s (insertmanyvalues) 1/3 (ordered; batch not supported)] ('red', 'Red test')
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine INSERT INTO widget (color, name) VALUES (?, ?) RETURNING id
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/3 (ordered; batch not supported)] ('green', 'Green test')
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine INSERT INTO widget (color, name) VALUES (?, ?) RETURNING id
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine [insertmanyvalues 3/3 (ordered; batch not supported)] ('blue', 'Blue test')
2024-06-11 11:01:24,064 INFO sqlalchemy.engine.Engine COMMIT
==== WITH widget_vw AS 
(SELECT widget.id AS id, widget.color AS color, widget.name AS name 
FROM widget 
WHERE widget.color = :color_1)
 select * from widget_vw
2024-06-11 11:01:24,065 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-06-11 11:01:24,066 INFO sqlalchemy.engine.Engine WITH widget_vw AS 
(SELECT widget.id AS id, widget.color AS color, widget.name AS name 
FROM widget 
WHERE widget.color = ?)
 select * from widget_vw
2024-06-11 11:01:24,066 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ('red',)
==== [<Widget(id=1, name=Red test)>]
2024-06-11 11:01:24,066 INFO sqlalchemy.engine.Engine ROLLBACK
==== WITH widget_vw AS 
(SELECT widget.id AS id, widget.color AS color, widget.name AS name 
FROM widget 
WHERE lower(widget.name) LIKE lower(:name_1))
 select * from widget_vw
2024-06-11 11:01:24,067 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-06-11 11:01:24,067 INFO sqlalchemy.engine.Engine WITH widget_vw AS 
(SELECT widget.id AS id, widget.color AS color, widget.name AS name 
FROM widget 
WHERE widget.color = ?)
 select * from widget_vw
2024-06-11 11:01:24,067 INFO sqlalchemy.engine.Engine [cached since 0.001091s ago] ('red',)
==== [<Widget(id=1, name=Red test)>]
2024-06-11 11:01:24,067 INFO sqlalchemy.engine.Engine ROLLBACK

Process finished with exit code 0
```

### Additional context

Simple workaround is to create a dynamic, unique name for the CTE each time.

**Comment by zzzeek** [comment] 2024-06-11 02:21
Can you set query_cache_size=0 on your create_engine and see if that resolves.   This looks like cache key issue

**Comment by zzzeek** [comment] 2024-06-11 02:23
This would be a backport to 1.4 if caching issue is confirmed

**Comment by baarney** [comment] 2024-06-11 02:39
Yep - adding `query_cache_size=0` does resolve the problem.

**Comment by sqla-tester** [comment] 2024-06-11 03:04
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include HasCTE traversal elements in TextualSelect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5314

**Comment by sqla-tester** [comment] 2024-06-11 03:04
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**include HasCTE traversal elements in TextualSelect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5315

**Comment by sqla-tester** [comment] 2024-06-11 03:05
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**include HasCTE traversal elements in TextualSelect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5316

**Closed** 2024-06-13 13:26 UTC
Labels: bug, sql, statement caching, near-term release

**Comment by sqla-tester** [comment] 2024-07-31 15:10
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**add CTE cache elements for CompoundSelect, more verify tests** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5335

**Comment by sqla-tester** [comment] 2024-07-31 15:10
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**add CTE cache elements for CompoundSelect, more verify tests** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5347
