### ISSUE TITLE
Async connections not returned to pool if task is cancelled

### ISSUE THREAD

**Issue by camlee** [sqlalchemy/sqlalchemy#8145] opened 2022-06-16 21:00 UTC
### Describe the bug

The AsyncConnection context manager does not reliably close the connection when exiting due to a **cancellation**. This results in resources leaking, which is clearly surfaced by the warning during garbage collection. Garbage collection can't perform the cleanup itself, but tells us that something was missed earlier.

### To Reproduce

```python
import anyio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.sql import text

async def main():
    engine = create_async_engine(
        "postgresql+asyncpg://username:password@localhost/db_name",
        echo=True,
        connect_args={"timeout": 5}
        )

    async def sleep_in_db():
        print(engine.pool.status()) # 0 connections
        async with engine.connect() as connection:
            print(engine.pool.status()) # 1 connections
            while True:
                await connection.execute(text("select now();"))
                await anyio.sleep(1)

    async with anyio.create_task_group() as db_tasks:
        db_tasks.start_soon(sleep_in_db)

        await anyio.sleep(2.5)

        db_tasks.cancel_scope.cancel() # Will raise a CancelledError under the hood


    print(engine.pool.status()) # 1 connection????

    await engine.dispose()

anyio.run(main)
```

### Error

```
The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7f1cf4760660>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
sys:1: SAWarning: The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7f1cf4760660>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
``` 

### Versions

- OS: Ubuntu on WSL2 in Windows 10
- Python: 3.10.4
- SQLAlchemy: 1.4.37
- Database: Postgres 14
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg 0.25.0

### Additional context

I think the problem is that the way cancellation works is that the event loop (asyncio in this case) raises CancelledError when you do `await`, so if any `await` is needed while actually processing a cancellation (ex. to cleanup), that needs to be "shielded" from the cancellation we're trying to process. We can see in `AsyncConnection` that on `__aexit__()` it's trying to await `self.close()`, but it's unable to (`self.close()` is never run) because of the cancellation: https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/ext/asyncio/engine.py#L700

```python
    async def __aexit__(self, type_: Any, value: Any, traceback: Any) -> None:
        await self.close()
```

Here's a good description of this concept in the [trio](https://trio.readthedocs.io/en/stable/index.html) docs: https://trio.readthedocs.io/en/stable/reference-core.html?highlight=shield#cancellation-semantics (it takes a bit to get to the relevant part, but read the whole block).

I don't know asyncio well enough to code up a robust solution but I believe these are the relevant docs: https://docs.python.org/3/library/asyncio-task.html#shielding-from-cancellation

Using [anyio](https://anyio.readthedocs.io/en/stable/index.html) to achieve trio-like structured concurrency on top of asyncio, I am able to patch this `__aexit__()` method and then the connection is properly closed. I'm not sure if you'd consider using anyio in sqlalchemy. Could be used in just this one place, throughout the codebase in order to add compatibility with trio, or piecemeal to get the advantages of structured concurrency without a big refactor. Here's the anyio docs for shielding: https://anyio.readthedocs.io/en/stable/cancellation.html?highlight=shield#shielding

```python
import anyio

class PatchedAsyncConnection(AsyncConnection):
    async def __aexit__(self, type_, value, traceback):
        with anyio.open_cancel_scope(shield=True):
            await self.close()
```

**Comment by zzzeek** [comment] 2022-06-16 21:12
hi -

I dont really see where this "shield" could be on the SQLAlhcemy side.   if you check out a connection from the pool, everything you do with that connection is fine, but as long as you are checked out, that entire operation needs to be shielded to prevent this issue.  that is above, everything that happens in sleep_in_db() after engine.connect().  if anything is cancelled in that block, there's no longer a context in which to close the connection.  

as far as anyio, looking at https://anyio.readthedocs.io/en/stable/cancellation.html#shielding I dont see this really being changed much, they just give you a context manager to do the same thing which is fine.  

but if we just shield in our ``__aexit__()`` method, that's not going to work IIUC, because if the task is cancelled before we get to ``__aexit__()``, then we're already cancelled and aexit isnt' called from within the event loop, right?  or no?

**Comment by CaselIT** [comment] 2022-06-17 09:19
The issue here seems only when using anyio.
If I create the same example using asyncio there is no issue since the aexits get a chance of cleaning up correctly
```py
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.sql import text

async def main():
    engine = create_async_engine(
        "postgresql+asyncpg://mamba:mamba-password@localhost/mamba",
        echo=True,
        connect_args={"timeout": 5}
        )

    async def sleep_in_db():
        print(engine.pool.status()) # 0 connections
        async with engine.connect() as connection:
            print(engine.pool.status()) # 1 connections
            while True:
                await connection.execute(text("select now();"))
                await asyncio.sleep(1)

    t = asyncio.create_task(sleep_in_db())
    await asyncio.sleep(2.5)
    t.cancel()


    await asyncio.sleep(1)
    print(engine.pool.status()) # 1 connection????
    await engine.dispose()

asyncio.run(main())
```

also from my understating the leaked connection here is because asyncpg does not use shield.
If I wrap the asyncpg connection in a proxy that uses `shield` on the close the connection is closed from the db side. There is still the garbage connection message, but that's a false positive, caused by the not execution of the other cleanup logic sqlalchemy

If I read the problem correctly is how anyio works, that prevents any normal use of aexit.

**Comment by CaselIT** [comment] 2022-06-17 09:27
By strange behaviour I mean this:

```py
import asyncio

async def go():
    print("go")

    async def task():
        try:
            print("before sleep 1")
            await asyncio.sleep(1)
            print("after sleep 1, sleep 2")
        finally:
            print("finally")
            await asyncio.sleep(1)
            print("end sleep 2")

    t = asyncio.create_task(task())
    print("sleep go")
    await asyncio.sleep(0.1)
    t.cancel()
    await asyncio.sleep(2)
    print("end")

asyncio.run(go())
```

here finally has a change of properly clean up after itself

Using anyio instead
```py
import anyio

async def go():
    print("go")

    async def task():
        try:
            print("before sleep 1")
            await anyio.sleep(1)
            print("after sleep 1, sleep 2")
        finally:
            print("finally")
            await anyio.sleep(1)
            print("end sleep 2")

    async with anyio.create_task_group() as tasks:
        tasks.start_soon(task)
        print("sleep go")
        await anyio.sleep(0.1)
        tasks.cancel_scope.cancel()
    await anyio.sleep(2)
    print("end")

anyio.run(go)
```
any await in finally does not run, `"end sleep 2"` is never executed. This seems to be quite broken on their part.

**Comment by zzzeek** [comment] 2022-06-17 12:08
does asyncpg include any context manager functionalty and if so what do they do here?  they are after all authors of asyncio itself

**Comment by CaselIT** [comment] 2022-06-17 12:26
they do have context manager functionality and no they do not seem to use shield.
- https://github.com/MagicStack/asyncpg/blob/f2a937d2f25d1f997a066e6ba02acc3c4de676a4/asyncpg/pool.py#L985-L986
- https://github.com/MagicStack/asyncpg/blob/f2a937d2f25d1f997a066e6ba02acc3c4de676a4/asyncpg/pool.py#L885-L928
but from a quick look I can't say if the close method is safe from a cancel prospective

Regarding the issue here, I think the issue here could also happen (with a less probability) also when using asyncio, since it could happen that cancel is called on a task that's executing the close operation. I'll try to experiment on that.

If that's the case then I guess we may need to investigate where and how to use shield of equivalent functionality

**Comment by graingert** [comment] 2022-06-17 14:39
but generally an engine should try do some something like:

```
try:
    await self.drain()  # or flush or etc
finally:
    self._sock.close()
```

**Comment by sqla-tester** [comment] 2022-06-17 21:12
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Tried adding shield where close cleanup is done** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3933

**Comment by graingert** [comment] 2022-06-17 21:19
You probably don't want to shield this, you should instead synchronously invalidate the unwrapped socket (close the underlying file descriptor) on a BaseException

> **Federico Caselli** has proposed a fix for this issue in the **main** branch:
> 
> **Tried adding shield where close cleanup is done** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3933

**Comment by CaselIT** [comment] 2022-06-17 21:34
In general closing a sqlalchemy connection will not close the driver connection, but return it to the pool, so it would not be appropriate to close the driver connection (even if possible, since sqlalchemy uses drivers not socket directly).

**Comment by graingert** [comment] 2022-06-17 21:55
Is it possible to synchronously return the socket to the pool instead, and then have the `pool.__axeit__` issue the synchronous close?

**Comment by CaselIT** [comment] 2022-06-17 22:00
Can't rollback in that case.

**Comment by graingert** [comment] 2022-06-17 22:01
```python
try:
    async with Pool() as pool:
        try:
            async with pool.transaction() as tx:
                try:
                    async with subtransaction(tx):
                        raise BaseException
                except BaseException:
                    # what about here?
        except BaseException:
            # what state should the transaction be here?
            raise
except BaseException:
     # what state should the encrypted connections in the pool be here?
    raise
```

**Comment by CaselIT** [comment] 2022-06-17 22:05
not sure what that snipped is but it's not how sqlalchemy is used

**Comment by CaselIT** [comment] 2022-06-17 22:17
thanks for the update. But I don't think it applies. The shield is only on connection close.
I'm not 100% sure we need on the session close I've added (would need to check if the one in connection is sufficient).

Again that usage pattern does not map to sqlalchemy, so it's hard to answer. If I try to translate this is what would happen

```py
try:
    async with engine,connect() as conn
        try:
            async with conn.begin():
                try:
                    async with conn.begin_nested():
                        raise BaseException
                except BaseException:
                    # no shiled
                    raise
        except BaseException:
            # no shield
            raise
except BaseException:
     # connection rolled back end in the pool. close called using shield
    raise
```

**Comment by graingert** [comment] 2022-06-17 22:33
```
try:
    async with engine.connect() as conn:
        try:
            async with conn.begin():
                try:
                    async with conn.begin_nested():
                        raise BaseException
                except BaseException:
                    # what happens if you issue an update here?
                    # what happens if the server stops responding?
                    raise
        except BaseException:
            # what happens if you issue an update here?
            # what happens if the server stops responding?
            raise
except BaseException:
     # connection rolled back end in the pool. close called using shield
    # what happens if you issue an update here?
    # what happens if the server stops responding?
    raise
```

**Comment by camlee** [comment] 2022-06-17 22:46
The shielded call to close should be wrapped in a timeout. Cause ya, you
wouldn't want the server to stop responding and hang everything.

**Comment by CaselIT** [comment] 2022-06-17 22:57
what does `"what happens if the server stops responding?"` mean. what server??? and how should it be sqlalchemy problem?

> what happens if you issue an update here?

apparently it depends. On anyio nothing happen. on asyncio it would run correctly.

**Comment by CaselIT** [comment] 2022-06-17 23:13
> The shielded call to close should be wrapped in a timeout. Cause ya, you wouldn't want the server to stop responding and hang everything.

That should be the caller job, not the library job to add a `wait_for`

**Comment by CaselIT** [comment] 2022-06-17 23:22
> When `engine.dispose()` is cancelled does it correctly close the underlying sockets?

No, currently no, since there is no shield added there

**Comment by zzzeek** [comment] 2022-06-24 21:26
so I've run both test cases.      At the moment, it seems the issue cannot be reproduced with asyncio directly, and it seems like asyncio allows `__aexit__` to run and continues to allow awaitables to work in there before propagating out the CancelledError.  Which seems entirely great to me and I dont know why anyio doesn't do this, I agree with @CaselIT  this behaves like a bug in anyio.  I get the impression this is somehow intentional in anyio but it certainly does not seem correct.

ive updated the patch to only use shield in the `__aexit__` method of connection / session as this appears to be a flow control feature.

some better examples of how this might apply to regular asyncio would be helpful, as it is I'm -1 on this without a better understanding as well as why dont libraries like asyncpg use shield() in the way that's being proposed here.

**Comment by graingert** [comment] 2022-06-24 21:31
`shield` doesn't prevent cancellation, it just allows the child task to continue with no parent and no way of recovering a correct connection state

**Comment by zzzeek** [comment] 2022-06-24 21:35
@graingert that tells me absolutely nothing about next steps or even what it means

**Comment by graingert** [comment] 2022-06-24 21:39
The connection pool should be responsible for cleaning up connections returned to it, there should be a synchronous method to return connections to it

**Comment by CaselIT** [comment] 2022-06-24 21:45
From the interaction here, I'm not sure you are familiar with sqlalchemy. To communicate with the network it uses a 3rd party library, so there is bo reader writer or fd exposed to sqlalchemy

**Comment by zzzeek** [comment] 2022-06-24 22:00
> The connection pool should be responsible for cleaning up connections returned to it, there should be a synchronous method to return connections to it.

we have that.   however not every connection returned to the pool gets "returned", many have to be closed either because the pool is full or the connection itself was invalidated, which is very likely when a CancelledError is encountered as the connection may be in an undefined state.

> 
> If the connection pool close is cancelled it should synchronously remove_reader/remove_writer and os.close the handles/fds it opened

we don't have that.   if you can show me [here](https://magicstack.github.io/asyncpg/current/api/index.html#connection) how we'd do that, we can add it for asyncpg; same for other drivers like aiomysql, asyncmy, psycopg3.



we dont have an os.close(fd) API for the database driver

**Comment by graingert** [comment] 2022-06-24 22:15
Ah yes for example here, with TLS:


```python
import asyncpg
import asyncio
import ssl

async def main():
    sslctx = ssl.create_default_context(
        ssl.Purpose.SERVER_AUTH)
    sslctx.check_hostname = False
    sslctx.verify_mode = ssl.CERT_NONE
    con = await asyncpg.connect(user='postgres', ssl=sslctx)
    asyncio.current_task().cancel() # cancel the close 
    await con.close()

asyncio.run(run())
```

Should result in a ragged EOF being detected on the server and the main task returning immediately after the cancel. If this isn't happening it's a bug in asyncpg

**Comment by igoras1993** [comment] 2022-07-07 08:09
Hi!

I would like to join the discussion, because we have recently encountered exactly the same issue, but with plain `asyncio` (well, `asyncio` with `uvloop` (`uvicorn`) loop implementation). Currently, we have deployed one of our `fastapi` application, which uses `SQLAlchemy`, to the environment that introduces moderately high traffic (application aggregates spatial coordinates from multiple mobile agents on `timescaledb` postgres plugin).

As the application encouners high traffic, the connection leaks are happening frequently. On the recent days, I've done some investigations on this, trying to amplify the effect of leaked connections. And now is actually quite obvious that they **are** happening. I am currently working on minimal example, but even now I want to share the setup - it is really straightforward, everythink-like-in-the-documentation:

1. Module level engine and session maker. Pool size and max overflow are reduced to minimum to amplify the effect of connection leaks.
  
   ```python
   from sqlalchemy.orm import sessionmaker
   from sqlalchemy.ext.asyncio import (
       AsyncSession,
       create_async_engine
   )
   
   engine = create_async_engine(
       settings.SQLALCHEMY_DATABASE_URI,
       pool_size=2,
       max_overflow=0
   )
  
   SessionLocal = sessionmaker(
       class_=AsyncSession,
       autocommit=False,
       autoflush=False,
       expire_on_commit=False,
       bind=engine
   )
   ```
  
   Here are the variables which are building the URL:
   ```
   POSTGRES_SCHEMA=postgresql+asyncpg
   POSTGRES_HOST=db
   POSTGRES_USER=rdummy
   POSTGRES_PASSWORD=summy
   POSTGRES_DB=dummy
   ```

2. Then, the so-called dependency for `fastapi`. If You are not familiar, it is evaluated and consumed upon incoming request, context manager will enter when request arrives, and exit after request is handled - very similar to the fixtures with `yeild` in pytest.

   ```python
   async def get_db_session() -> t.AsyncGenerator[AsyncSession, None]:
       async with SessionLocal() as session:
           yield session
   ```

And that's all. Take it, put in into some `asgi` application, fire the high traffic and you **will** encounter the leaks. In our case, application is imported and started by a uvicorn:

```
$ exec uvicorn "$APP_MODULE" "--host" "0.0.0.0" "--port" "80" "--reload" "--proxy-headers" "--forwarded-allow-ips" "*"
```

Which should be equivalent to `asyncio.run()` with setting equivalent loop policy to the one provided by ``uvloop``.

## Traceback
The same as OP above, many times, from many places. Examplary log tail:
```
app-backend_1  | /usr/local/lib/python3.9/asyncio/base_events.py:433: SAWarning: The garbage collector is trying to clean up connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x7f9fdd0ffc40>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.

app-backend_1  | sys:1: SAWarning: The garbage collector is trying to clean up connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x7f9fdd002040>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.

app-backend_1  | /usr/local/lib/python3.9/site-packages/fastapi/routing.py:451: SAWarning: The garbage collector is trying to clean up connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x7f9fdcfed240>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
```

## Envioronment 

### python libs (important ones):
```
fastapi==0.75.0
asyncpg==0.24.0
psycopg2==2.9.1  # for alembic migrations only
SQLAlchemy==1.4.22
uvicorn==0.15.0
```

### python version
```
Python 3.9.6
```

## Additional context

So, of course, I have done some investigation so far. I have tried to adapt the shielding on `AsyncConnection.__exit__` patch like @camlee  suggested. Since we do not rely on `anyio` or `trio`, I've done the most basic thing described actually in standard [python docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.shield):

```python
from sqlalchemy.ext.asyncio import AsyncConnection
from asyncio import shield

async def conn_exit(self, type_, value, traceback):
    await shield(self.close())

# patch async connection
AsyncConnection.__aexit__ = conn_exit

```

But it does not help at all. Now I will try to implement minimal example, preferably without need of exposure to high trafic, that ill reproduce the leaking. Any advises are welcome (this bug actually makes SQLAlchemy+asyncpg unusable in production environment). Thank You for all Your work :)

**Comment by igoras1993** [comment] 2022-07-07 12:47
Ok, small update here.

I am unable to induce the leaks, even on the target production, by simply firing lot of requests from my local machine. Don't get me wrong - **the number of leaked connections are still slowly increasing**, but not due to my requests artillery. The event of leaking connection just don't correlates with my tests, leaks are happening due traffic from external clients. With the testing artillery, I am able to introduce more traffic than our production application normally encounters and still, this does not introduces a leak.

This drives me crazy, but also points to the small conclusion that this is not the amount traffic that implies the leaks, but maybe natural occurrences of http connection drops from the client side (they are mobile clients, connection drops can occur frequently), which may correlate with the task cancellation You guys are pointing above.

Additionally, I have missed the @CaselIT proposal of placing shield not only on connection, but also on a session context exit. I will try such approach and patch our production server to include shield also on session context exit. 

I will let the server running for several hours and check if any leaks are still the case. Will report the result. Cheers.

**Comment by zzzeek** [comment] 2022-07-07 14:00
also yes, dropped connections are the usual cause for this kind of thing.  use a simulation that cuts off requests in the middle before the response is received, will help you to isolate the sequence of events.

**Comment by zzzeek** [comment] 2022-07-07 19:56
yes if this works just within `__aexit__` and nowhere else, I'd vastly prefer that because `__aexit__` is already doing control flow

**Comment by igoras1993** [comment] 2022-07-08 08:10
@CaselIT  It looks like everything is stable, no leaks observed:
```
 datid |  datname  | numbackends | deadlocks |          stats_reset          
-------+-----------+-------------+-----------+-------------------------------
     0 |           |           0 |         0 | 2022-05-30 22:49:06.227759+00
 13455 | postgres  |           1 |         0 | 2022-05-31 04:00:09.250463+00
 16384 | gps       |           4 |         0 | 2022-05-30 22:49:06.227661+00
     1 | template1 |           0 |         0 | 
 13454 | template0 |           0 |         0 | 

```

Also, searching for word `"garbage"` in logs reports nothing:
```
$ docker-compose -f docker-compose.yml -f docker-compose.prod.yml logs | grep "garbage"
$
```

The patch applied:

```python
async def conn_exit(self, type_, value, traceback):
    await shield(self.close())


# async def sess_close(self):
#     await greenlet_spawn(self.sync_session.close)


async def sess_exit(self, type_, value, traceback):
    await shield(self.close())


# monkey patch
AsyncConnection.__aexit__ = conn_exit
# AsyncSession.close = sess_close
AsyncSession.__aexit__ = sess_exit
```

So I think that this should solve all cases, over all, `trio` and `anyio` must be compatible with standard library, `asyncio.shield()` is the standard solution for this.

**Comment by CaselIT** [comment] 2022-07-08 14:10
@igoras1993 thanks for testing this!

**Comment by zzzeek** [comment] 2022-07-11 14:54
hi can we move on this?  sheild just in `__aexit__` right?  can we finalize the gerrit and backport to 1.4 ?

**Comment by sqla-tester** [comment] 2022-07-18 15:37
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**add shield() in aexit** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3999

**Closed** 2022-07-18 22:45 UTC
Labels: third party integration issues, asyncio, next release

**Comment by zikphil** [comment] 2022-08-31 17:08
@zzzeek Desperately needing this for some issues I am having right now. When can we expect a release for 1.4.41?

**Comment by zzzeek** [comment] 2022-08-31 17:15
> @zzzeek Desperately needing this for some issues I am having right now. When can we expect a release for 1.4.41?

this issue's fix, add shield(), was released in 1.4.40, it's already out.

maybe you are looking for #8419 ?

**Comment by zikphil** [comment] 2022-08-31 17:17
@zzzeek Yes you are correct. Apologies.

**Comment by zzzeek** [comment] 2022-08-31 17:38
oh OK so you are still desperate then?  We usually have a 30 day gap between releases if there were not regressions.   #8419 is certainly a useful fix though

**Comment by zikphil** [comment] 2022-08-31 18:01
@zzzeek Yes, I am having some unresolved issues relating to this: [](https://github.com/sqlalchemy/sqlalchemy/discussions/8349#discussioncomment-3478278).

In some error cases where asyncio exits or closes for whatever API-related reasons the Connections are not going back to the pool, they just error out and gets re-used. This is causing issues for me since I need them to expire so I can grab fresh credentials for them.

Therapy moment:
Introducing dynamic credentials have been a nightmare for me. I wish there would be a more "bullet proof" way to make sure a connections never NEVER EVER gets used if it's past a certain age. Even if the connection is currently used, it should just die and get refreshed gracefully. Im using Hashicorp Vault to generate 1 hour-long credentials, im plugging it in  "do_connect" event. But Im finding more and more that under certain circumstances Im starting to have a bunch of connections with expired credentials even though my pool_recycle is 50m. It's very hard to troubleshoot because there is no clear way to identify where things went wrong within my 1.2 Million API calls during that timeframe. I was almost thinking I should write my own custom logic where when a session gets created I should force-check connection TTL and kill it right away if it's over 50m and get the session a new one. I just need to play with internal APIs and it's making me nervous.

**Comment by zzzeek** [comment] 2022-08-31 18:17
the pool doesnt have a background thread that's culling old connections.   so if you have a pool that isn't being used, the connection stays there until someone goes to get a new connection from it.   if the pool is only lightly used, then there still can be connections in there that may be any level of "old", they could be days old if the application has not seen any periods of high concurrency.  

with the fix to just terminate them, there shouldn't be any problem.

**Comment by zzzeek** [comment] 2022-08-31 18:18
also your LB here is not being friendly.  there's ways to close connections that is more quickly detectable

**Comment by zikphil** [comment] 2022-08-31 18:23
> with the fix to just terminate them, there shouldn't be any problem.

Are you referring to #8419? I really hope so. I will be glued to my chair and wait to test it out :)

> also your LB here is not being friendly. there's ways to close connections that is more quickly detectable

I agree. Im sure Sanic has something to do with the whole process as well. I am still investigating those issues through my APM software. It's keeping me busy :)

**Comment by CaselIT** [comment] 2022-08-31 18:31
> Even if the connection is currently used, it should just die and get refreshed gracefully

that's not really possible to refresh a connection gracefully since if it's in a transaction you would lose everything since the last commit

considering the number of api calls, that's strange the connection would be left in the pool for more than the hour. maybe try setting a shorter pool recycle? like 30min for 1h of credential validity?

**Comment by zzzeek** [comment] 2022-08-31 18:39
> considering the number of api calls, that's strange the connection would be left in the pool for more than the hour. maybe try setting a shorter pool recycle? like 30min for 1h of credential validity?

if the pool is configured for 50 connections, and their web container is configured for only 45 concurrent requests, then no matter what load you have, you will be subject to potentially 5 connections that might not get used for a long time.

**Comment by CaselIT** [comment] 2022-08-31 18:41
> > considering the number of api calls, that's strange the connection would be left in the pool for more than the hour. maybe try setting a shorter pool recycle? like 30min for 1h of credential validity?
> 
> if the pool is configured for 50 connections, and their web container is configured for only 45 concurrent requests, then no matter what load you have, you will be subject to potentially 5 connections that might not get used for a long time.

sure, but usually you would have just 45 connections in the pool, since at no point 45+ would be checked out.
still that may be a reason

**Comment by zzzeek** [comment] 2022-08-31 18:49
> > > considering the number of api calls, that's strange the connection would be left in the pool for more than the hour. maybe try setting a shorter pool recycle? like 30min for 1h of credential validity?
> > 
> > 
> > if the pool is configured for 50 connections, and their web container is configured for only 45 concurrent requests, then no matter what load you have, you will be subject to potentially 5 connections that might not get used for a long time.
> 
> sure, but usually you would have just 45 connections in the pool, since at no point 45+ would be checked out. still that may be a reason

OK so, here's another weird fact about that, we are [fifo by default](https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=use_lifo#sqlalchemy.create_engine.params.pool_use_lifo), which as you can see in that docstring that I think the contributor there wrote for us, setting LIFO can indeed get you more to that 45 connection goal.  otherwise it's going

**Comment by graingert** [comment] 2022-09-13 07:03
this is invalid asyncio, see https://docs.python.org/3.11/library/asyncio-task.html?highlight=important%20weak%20references%20disappearing%20mid-execution#asyncio.shield

**Comment by CaselIT** [comment] 2022-09-13 08:01
how would you improve the existing code?

**Comment by graingert** [comment] 2022-09-13 08:09
Keep a reference to a group of tasks on the connection pool

eg:

```python
task = asyncio.create_task(close)
pool._tasks.add(task)
task.add_done_callback(pool._tasks.discard)
await asyncio.shield(task)
```

Then your connection pool can wait for `self._tasks`

Even better is using an anyio TaskGroup in your pool

**Comment by CaselIT** [comment] 2022-09-13 10:45
Thanks for the example, I'll open a new issue to improve this.
