### ISSUE TITLE
session after close still allows actions to be ran

### ISSUE THREAD

**Issue by oridistor** [sqlalchemy/sqlalchemy#7787] opened 2022-03-03 11:07 UTC
### Describe the bug

When a session does `close` because of a context manager, the session can still be used, causing unexpected behavior.
For example: hung connections that never get closed.

### To Reproduce

```python
from sqlalchemy.orm import session

curr_session = session.Session()

print(session.transaction)
print(session.transaction.state)

curr_session.close()

print(session.transaction)
print(session.transaction.state)
```

### Error

```
# Copy complete stack trace and error message here, including SQL log output if applicable.
``` 

### Versions

- OS: macOS (irrelevant)
- Python: 3.7.3 
- SQLAlchemy: 1.3.24, also occurs on 1.4.31, didn't test if leaky connections.
- Database: irrelevant
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): postgresql (irrelevant)

### Additional context

We saw this issue when we found sessions hung in production for over an hour.

This occurred in our code because we passed session to a generator, closed the session and only then we iterated the generator.

Expected behavior would be an error for doing execute on a closed session.

**Comment by CaselIT** [comment] 2022-03-03 12:03
Hi,

I believe this is the expected behaviour, since the session (or a connection) will be reopened after a close if additional operations are performed allowing its reuse.

I'm not sure of the feasibility of changing this behaviour or of providing a parameter, something like `single_use` to control this. @zzzeek what do you think?

**Comment by oridistor** [comment] 2022-03-03 14:05
@CaselIT the main issue here is in context usage, because we do not assume that a function receiving the session as a parameter we would consider closing it, as it just received it and is not the owner of the object

**Comment by zzzeek** [comment] 2022-03-07 16:14
this has been the Session's expected behavior since the object was introduced.   There are some ways to enforce a close and we can also add options to make this happen, but generally the best practice is that outside of a context manager that closes the session, the session should not be used.    I'm not following the issue with "a function receiving the session as a parameter" - using a context manager we would assume this function has completed its operation before the external context manager is finished.  There's only an issue if the session is added to some internal state within the function that continues to exist outside the context which doesnt seem like it would be that common (indeed it hasnt as people don't really bring up this particular Session behavior as an issue).  

we can add some flag "close_final=True" to the constructor that can also be accepted by sessionmaker.

**Comment by PabloEmidio** [comment] 2022-12-18 12:59
Hey @zzzeek. I believe would be better add an optional parameter to Session.close method to inform that after the call, the session object should not run any operation. This behavior could be assured using an _Session__is_closed attribute that would be always checked before ran anything (maybe through a middleware put using a decorator).

**Comment by zzzeek** [comment] 2022-12-18 14:54
> Hey @zzzeek. I believe would be better add an optional parameter to Session.close method to inform that after the call, the session object should not run any operation. This behavior could be assured using an _Session__is_closed attribute that would be always checked before ran anything (maybe through a middleware put using a decorator).

sure but that doesn't accommodate for context manager use.

**Comment by PabloEmidio** [comment] 2022-12-18 15:24
> sure but that doesn't accommodate for context manager use.


well, as the dunder exit call `Session.close`, we could create a kwarg that indicate the `close_final` when instance the Session, using the dunder exit to pass it along.
https://github.com/sqlalchemy/sqlalchemy/blob/ac6f98a95cf9f65fec582a93cd168ce91402f5b4/lib/sqlalchemy/orm/session.py#L1556-L1557



The difference to your initial suggestion would be that now it will be possible using the `close_final` even when did not instance the session informing the `close_final`

**Comment by zzzeek** [comment] 2022-12-18 15:28
so, you want to add *two* keyword arguments (or the same kw argument in two different places), is that correct?

**Comment by zzzeek** [comment] 2022-12-18 15:29
what do we do with the likely common use case (that I can see even using myself) of an application that wants to prevent *all* sessions from being used beyond the .close(), which is likely how `.close()` should have been created in the first place?   Who really wants .close() to not be final?

**Comment by zzzeek** [comment] 2022-12-18 15:31
like, why not have a constructor arguemnt close_final=True, then .close() is automatiaclly final, then if someone wants the *old* close behavior, which IMO is mostly broken, they can do a new method like session.empty() ?

that is, .close() that is not final really is a bug in the first place.  Adding options to make .close() optionally un-broken, but broken by default, seems like the wrong API here.

**Comment by PabloEmidio** [comment] 2022-12-18 15:39
If the "close that is not final" is a bug, so why will be needed a flag to assure final close as suggest? I'd considering a scenario where the old behavior is expected.

**Comment by zzzeek** [comment] 2022-12-18 15:41
> If the "close that is not final" is a bug, so why will be needed a flag to assure final close as suggest? I'd considering a scenario where the old behavior is expected.

we want to move .close() to be final by default.    So we add a parameter to the Session() that is basically, "use this new behavior here".   An application can set it just once to have a future-facing behavior in their application.   

if OTOH we said, "everyone use .close(final=True) in all your .close() calls, everywhere", that is very burdensome and verbose just to get what would be a default behavior someday

**Comment by PabloEmidio** [comment] 2022-12-18 15:45
Understood!

**Comment by dankrzeminski32** [comment] 2023-07-22 19:58
@zzzeek I'm interested in working on this and would appreciate some guidance.

Will there be an `is_closed` property on the `Session` to keep track of the session's state? What's the best route of ensuring that the `Session` object can't be used again?

**Comment by zzzeek** [comment] 2023-07-24 12:59
> @zzzeek I'm interested in working on this and would appreciate some guidance.
> 
> Will there be an `is_closed` property on the `Session` to keep track of the session's state? What's the best route of ensuring that the `Session` object can't be used again?

the property as mentioned in https://github.com/sqlalchemy/sqlalchemy/issues/7787#issuecomment-1060864241 would be called `close_final=True` and two ways that can check are:

1. a check in [_autobegin_t()](https://github.com/sqlalchemy/sqlalchemy/blob/45b45619e75cb51bf1c3549a122edf8151a5d818/lib/sqlalchemy/orm/session.py#L1765)
2. a check when `SessionTransaction` is constructed: https://github.com/sqlalchemy/sqlalchemy/blob/45b45619e75cb51bf1c3549a122edf8151a5d818/lib/sqlalchemy/orm/session.py#L867   (this is likely the better place)

**Comment by dankrzeminski32** [comment] 2023-07-24 17:05
@zzzeek I'm working on implementing the test cases and am noticing lots of old tests failing due to the new default (`close_final=True`). Will I have to update the old tests to be able to handle the new default parameter?

Here is a snippet of my test results ran using `tox`, 

![image](https://github.com/sqlalchemy/sqlalchemy/assets/76189617/5534c674-8dae-4cf4-b967-fc8b6ec7ea36)

**Comment by CaselIT** [comment] 2023-07-24 17:18
I think the default will have to be false for this, since it will otherwise break a lot of code

**Comment by zzzeek** [comment] 2023-07-24 19:41
Yes this defaults to false. We would have to slowly (VERY slowly, and maybe never) flip this to default to True.

**Comment by CaselIT** [comment] 2023-07-24 20:03
Not sure if it makes nore sense calling this `close_final` instead of `closed_final`. Or `close_is_final`

**Comment by zzzeek** [comment] 2023-07-24 20:05
Among those choices `close_final` is the best

**Comment by CaselIT** [comment] 2023-07-24 20:07
Additional suggestions are welcome if you have any mike

**Comment by sqla-tester** [comment] 2023-09-20 21:42
**Daniel Krzeminski** has proposed a fix for this issue in the **main** branch:

**Added an option to permanently close objects.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4824

**Closed** 2023-10-04 15:03 UTC
Labels: orm, fairly easy, PRs (with tests!) welcome, use case
