### ISSUE TITLE
'Sequence' object has no attribute '_execution_options' in 1.4

### ISSUE THREAD

**Issue by na-ka-na** [sqlalchemy/sqlalchemy#6668] opened 2021-06-23 18:40 UTC
**Describe the bug**
Sequence next val is throwing an error with 1.4. Works just fine with 1.3.20

**To Reproduce**
Note sure of the minimal way to reproduce, but here's what we have in our `models.py`

```
WorkOrderSequence = Sequence(name='seq_work_order',
                             start=1,
                             schema=SCHEMA_NAME,
                             metadata=ModelBase.metadata)
```

and then the line that throws the error: `session.execute(WorkOrderSequence)`

**Error**
```
  File "............../models.py", line 924, in __init__
    session.execute(WorkOrderSequence)
  File "<string>", line 2, in execute
  File "..../.pyenv/versions/venv/lib/python3.7/site-packages/SQLAlchemy-1.4.19.dev0-py3.7-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1666, in execute
    events_todo,
  File "..../.pyenv/versions/venv/lib/python3.7/site-packages/SQLAlchemy-1.4.19.dev0-py3.7-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 151, in __init__
    self.execution_options = statement._execution_options.union(
AttributeError: 'Sequence' object has no attribute '_execution_options'
```

**Versions.**
 - OS: MacOS
 - Python: 3.7
 - SQLAlchemy: 1.4.19.dev0 @73573a6fda1c3ebde27a169199b1f33fccb1e415
 - Database: Postgres
 - DBAPI:

**Have a nice day!**

**Comment by CaselIT** [comment] 2021-06-23 19:30
> `session.execute(WorkOrderSequence)`

I think you need to use `session.execute(WorkOrderSequence.next_value())` to execute a next value

**Comment by CaselIT** [comment] 2021-06-23 19:31
@zzzeek marking as expected behavior, feel free to change it it's not

**Comment by zzzeek** [comment] 2021-06-23 20:13
connection.execute() can run Sequence and also Sequence is StatementRole.  so really all DefaultGenerator should be Executable:
```diff
iff --git a/lib/sqlalchemy/sql/schema.py b/lib/sqlalchemy/sql/schema.py
index 221d49db9a..484cdddc88 100644
--- a/lib/sqlalchemy/sql/schema.py
+++ b/lib/sqlalchemy/sql/schema.py
@@ -41,6 +41,7 @@ from . import visitors
 from .base import _bind_or_error
 from .base import DedupeColumnCollection
 from .base import DialectKWArgs
+from .base import Executable
 from .base import SchemaEventTarget
 from .coercions import _document_text_coercion
 from .elements import ClauseElement
@@ -2464,7 +2465,7 @@ class ForeignKey(DialectKWArgs, SchemaItem):
             self._set_target_column(_column)
 
 
-class DefaultGenerator(SchemaItem):
+class DefaultGenerator(Executable, SchemaItem):
     """Base class for column *default* values."""
 
     __visit_name__ = "default_generator"
@@ -2678,7 +2679,7 @@ class IdentityOptions(object):
         self.order = order
 
 
-class Sequence(IdentityOptions, roles.StatementRole, DefaultGenerator):
+class Sequence(IdentityOptions, DefaultGenerator):
     """Represents a named database sequence.
 
     The :class:`.Sequence` object represents the name and configurational
```

**Comment by zzzeek** [comment] 2021-06-23 20:19
OK that would be the fix for this, however, right now, the first unit test in test_session is:

```python
    @testing.requires.sequences
    def test_sequence_execute(self, connection):
        seq = Sequence("some_sequence")
        seq.create(connection)
        try:
            sess = Session(connection)
            eq_(sess.execute(seq), connection.dialect.default_sequence_base)
        finally:
            seq.drop(connection)
```

so...I guess you have do_orm_execute() event set up?

**Comment by zzzeek** [comment] 2021-06-23 20:32
not a regression since it requires a new feature is in use to trigger it.

**Comment by sqla-tester** [comment] 2021-06-23 20:42
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add Executable to DefaultGenerator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2890

**Closed** 2021-06-24 13:17 UTC
Labels: bug, sql
