### ISSUE TITLE
support three-part SQL Server schema names / auto-aliasing again (or just document synyonyms ?)

### ISSUE THREAD

**Issue by sruthi4155** [sqlalchemy/sqlalchemy#5364] opened 2020-05-30 21:45 UTC
Hi,

Can we join two tables from two different SQL servers (linked servers) using SQLAlchemy ORM? I tried passing in the server name to 'schema' argument in __table_args__ that didn't work? I am wondering if there is any other way to achieve this task?

Thanks,
Sruthi

**Comment by CaselIT** [comment] 2020-05-31 19:38
Hi,
I think it would help if you could you provide an example of the sql you are trying to generate.
thanks

**Comment by sruthi4155** [comment] 2020-05-31 20:04
I have two linked SQL servers Server1 and Server2. I am creating a session using Server 1. And I'm trying to specify Server2.Database.owner as an argument for schema in table_args. 
__table_args__ = {'schema': 'Server2.DB_name.owner'}. This is automatically getting converted to 'Server2.DB_nameowner'...... the '.' between db_name and owner is getting omitted automatically. Instead of passing 'Server2' to the schema argument. I am trying to see if there is any other way of using SQLAlchemy ORM to specify server name of a table.

**Comment by zzzeek** [comment] 2020-05-31 22:53
hi there -

Per the documentation at https://docs.sqlalchemy.org/en/13/dialects/mssql.html#multipart-schema-names, SQLAlchemy currently supports two tokens at most which may be demarcated via brackets, such as `__table_args__ = {'schema': '[Server2.DB_name].[owner]'}`.     So we can render `[Server2.DB_name].owner` here.  Not sure if that's sufficient.      The "database" portion, when reflection is run, will result in an execution like "use [Server2.DB_name]".

if three individual tokens are required then we would have to implement a new feature in the SQL server dialect.

**Comment by zzzeek** [comment] 2020-06-01 00:03
the missing dot thing is also a bug.   added #5366 for that.

**Comment by sqla-tester** [comment] 2020-06-01 00:34
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support multiple dotted sections in mssql schema names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2020

**Comment by sqla-tester** [comment] 2020-06-01 00:34
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Support multiple dotted sections in mssql schema names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2021

**Comment by zzzeek** [comment] 2020-06-01 00:36
that patch should improve things but I dont have a way to test a joined-server SQL server environment, if someone knows how to do that we can test if the syntax works.

**Comment by sruthi4155** [comment] 2020-06-01 02:14
You can try https://www.sqlshack.com/how-to-create-and-configure-a-linked-server-in-sql-server-management-studio/

**Comment by sruthi4155** [comment] 2020-06-01 10:35
By when can we expect this bug to be fixed?

**Comment by CaselIT** [comment] 2020-06-01 10:38
Like any open source project, when someone has time to work on it :)

Does the patch here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2021 solves this for you? If you could test it would speed things up.

**Comment by sruthi4155** [comment] 2020-06-01 14:41
I am a newbie to open source projects. Can you please provide me some guidance on how to test this patch?

**Comment by gordthompson** [comment] 2020-06-01 14:43
If the idea is to be able to do this ...

```python
tbl = sa.Table(
    "hello", sa.MetaData(), schema="DOCKER199.mydb.dbo", autoload_with=engine
)
with engine.connect() as conn:
    result = conn.execute(tbl.select()).fetchall()
    print(result)
```

... then we're not quite there yet. PS3 in the Gerrit fails with

> sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08004', "[08004] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'DOCKER199.mydb' does not exist. Make sure that the name is entered correctly. (911) (SQLExecDirectW)")
> 
> [SQL: use [DOCKER199.mydb]]

And, unfortunately, it's not just the square brackets. SQL Server apparently does not let us change the database context (USE ...) to a database on a linked server:

```text
1> USE myDb
2> go
Changed database context to 'myDb'.
1> SELECT * FROM DOCKER199.mydb.dbo.hello;
2> go
txt
--------------------------------------------------
Hello from MSSQL on 192.168.0.199!

(1 rows affected)
1> USE DOCKER199.mydb
2> go
Msg 911, Level 16, State 1, Server GORD-HP\SQLEXPRESS, Line 1
Database 'DOCKER199' does not exist. Make sure that the name is entered correctly.
```

**Comment by zzzeek** [comment] 2020-06-01 16:54
@gordthompson  propose everywhere in sql server dialect where we have "dbname, owner" we break it into three for "server, dbname, owner", then all the reflection queries would have to be altered to select for the alternate server if given.

however, can we confirm that *queries* will work with my changes.  For reflection, we can have it raise notimplemented for now when "server" is detected.

**Comment by zzzeek** [comment] 2020-06-01 16:56
> By when can we expect this bug to be fixed?

as this is a very complex change, full support will be delayed.

you can solve your problem right now by creating synonyms to refer to the schemas and tables in this alternate database, then use those names in your SQLAlchemy models:

https://docs.microsoft.com/en-us/sql/relational-databases/synonyms/synonyms-database-engine?view=sql-server-ver15

**Comment by gordthompson** [comment] 2020-06-01 18:02
> can we confirm that _queries_ will work with my changes

For ORM queries the square brackets as currently rendered are problematic:

```python
engine = sa.create_engine(
    r"mssql+pyodbc://@localhost:49242/myDb?driver=ODBC+Driver+17+for+SQL+Server",
    echo=True,
)

Base = declarative_base()


class Hello(Base):
    __tablename__ = "hello"
    __table_args__ = {"schema": "DOCKER199.mydb.dbo"}
    txt = sa.Column(sa.String(50), primary_key=True)

    def __repr__(self):
        return f"<Hello(txt={self.txt})>"


Session = sessionmaker(bind=engine)
session = Session()

for instance in session.query(Hello):
    print(instance)
```

> sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'DOCKER199.mydb.dbo.hello'. (208) (SQLExecDirectW)")
>
> [SQL: SELECT [DOCKER199.mydb].dbo.hello.txt AS [DOCKER199_mydb_dbo_hello_txt] 
FROM [DOCKER199.mydb].dbo.hello]

That is,

```text
1> SELECT [DOCKER199.mydb].dbo.hello.txt AS [DOCKER199_mydb_dbo_hello_txt] FROM [DOCKER199.mydb].dbo.hello
2> go
Msg 208, Level 16, State 1, Server GORD-HP\SQLEXPRESS, Line 1
Invalid object name 'DOCKER199.mydb.dbo.hello'.
```

Sadly, "fixing" the square brackets causes another issue

```text
1> SELECT [DOCKER199].[mydb].dbo.hello.txt AS [DOCKER199_mydb_dbo_hello_txt] FROM [DOCKER199].[mydb].dbo.hello
2> go
Msg 4104, Level 16, State 1, Server GORD-HP\SQLEXPRESS, Line 1
The multi-part identifier "DOCKER199.mydb.dbo.hello.txt" could not be bound.
```

so it looks like we might have to resort to generating a table alias if one is not specified

```text
1> SELECT alias1.txt AS [DOCKER199_mydb_dbo_hello_txt] FROM [DOCKER199].[mydb].dbo.hello AS alias1
2> go
DOCKER199_mydb_dbo_hello_txt
--------------------------------------------------
Hello from MSSQL on 192.168.0.199!
```

**Comment by zzzeek** [comment] 2020-06-01 18:39
@gordthompson , can you try to use the patch in the above gerrit and set the schema name as:  `[DOCKER199].[mydb].[dbo]`  ? that's how it should work

**Comment by zzzeek** [comment] 2020-06-01 18:40
also if this is truly not workable then we should recommend synonyms as the way to go for this case.   wont support reflection

**Comment by gordthompson** [comment] 2020-06-01 19:08
Still with PS3 in Gerrit_2020:

```Python
engine = sa.create_engine(
    r"mssql+pyodbc://@localhost:49242/myDb?driver=ODBC+Driver+17+for+SQL+Server",
    echo=True,
)

Base = declarative_base()


class Hello(Base):
    __tablename__ = "hello"
    __table_args__ = {"schema": "[DOCKER199].[mydb].[dbo]"}
    txt = sa.Column(sa.String(50), primary_key=True)

    def __repr__(self):
        return f"<Hello(txt='{self.txt}')>"


Session = sessionmaker(bind=engine)
session = Session()

for instance in session.query(Hello):
    print(instance)
```

> sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '_'. (102) (SQLExecDirectW)")

```text 
[SQL: SELECT [DOCKER199].[mydb].dbo.hello.txt AS [[DOCKER199]_[mydb]_[dbo]_hello_txt] 
FROM [DOCKER199].[mydb].dbo.hello]
```

The square brackets are not escaped inside the (square-bracketed) table name. T-SQL requires that the *closing* square brackets be doubled-up, i.e.,

```text
1> SELECT QUOTENAME('[DOCKER199]_[mydb]_[dbo]_hello_txt') AS quoted;
2> go
quoted
----------------------------------------------------------
[[DOCKER199]]_[mydb]]_[dbo]]_hello_txt]
```

**Comment by sqla-tester** [comment] 2020-06-01 19:38
**Mike Bayer** referenced this issue:

**Support multiple dotted sections in mssql schema names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2020

**Comment by sqla-tester** [comment] 2020-06-01 19:39
**Mike Bayer** referenced this issue:

**Support multiple dotted sections in mssql schema names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2021

**Comment by zzzeek** [comment] 2020-06-01 19:39
I'll commit the above gerrit but it will only "Fix" #5366 , it will leave this one open.

**Comment by zzzeek** [comment] 2020-06-01 19:50
well I hope #5356 didn't make it worse, at least.

the "tablename_colname" style labeling is no longer necessary in 1.4 and if you use future style queries it doesn't do it anymore.   it's certainly not doing the "right thing" here, though.

**Comment by gordthompson** [comment] 2020-06-04 17:40
Preliminary testing indicates that creating a SYNONYM for the table on the linked server is a viable workaround. After executing ...

``` sql
CREATE SYNONYM [dbo].[hello_199] FOR [DOCKER199].[myDb].[dbo].[hello]
```

on the currently-connected server, the code

``` python
engine = sa.create_engine(
    r"mssql+pyodbc://@localhost:49242/myDb?driver=ODBC+Driver+17+for+SQL+Server",
    echo=True,
)

Base = declarative_base()


class Hello(Base):
    __tablename__ = "hello_199"
    txt = sa.Column(sa.String(50), primary_key=True)

    def __repr__(self):
        return f"<Hello(txt='{self.txt}')>"


Session = sessionmaker(bind=engine)
session = Session()

for instance in session.query(Hello):
    print(instance)
```

successfully completed and printed 

``` text
<Hello(txt='Hello from MSSQL on 192.168.0.199!')>
```

**Comment by zzzeek** [comment] 2020-06-04 20:52
to the reporter, I think for now we are leaning towards not implementing this for now and instead documenting to use synonyms.  it's not that the feature wouldn't be useful or that it couldn't work, it's just it would be a very large change reuqiring a lot of testing for a use case that we're not sure is very common, as this has not been requested before.   the workaround unfortunately does not allow reflection of tables from the remote server, that would be nice to have.   The Oracle dialect does reflect tables over so-called "dblinks" so this feature does have precedent.

**Comment by zzzeek** [comment] 2023-01-27 14:07
hey @gordthompson  -

does this work?   

```py
from sqlalchemy import Column
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.dialects import mssql
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class Hello(Base):
    __tablename__ = "hello"
    __table_args__ = {"schema": "[DOCKER199].[mydb].[dbo]"}
    txt = Column(String(50), primary_key=True)

    def __repr__(self):
        return f"<Hello(txt='{self.txt}')>"

# bad way
print(select(Hello).compile(dialect=mssql.dialect()))

# good way?   We can modernize this feature and make it apply
# to specific tables / schemas / etc
print(select(Hello).compile(dialect=mssql.dialect(legacy_schema_aliasing=True)))

```

the second one produces the query:

```
SELECT hello_1.txt 
FROM [DOCKER199].[mydb].dbo.hello AS hello_1
```

we also have this kind of functionality in the compiler itself from #7471.

that is, we have functionality to "auto alias" tables that have a certain kind of schema, and old SQL Server versions required it in all cases.   If that's what we need here, I can certainly take SQL Server's legacy feature and modernize it into #7471's approach and make this a supported thing.

**Comment by zzzeek** [comment] 2023-01-27 14:08
also to confirm, this issue is about rendering SELECT statements and other SQL only.  reflection of tables like these is a wontfix.

**Comment by gordthompson** [comment] 2023-01-27 17:21
> the second one produces the query:
> 
> SELECT hello_1.txt 
> FROM [DOCKER199].[mydb].dbo.hello AS hello_1

Yes, that will work, provided that it doesn't arbitrarily remove the square brackets from the last part. If so, then `{"schema": "[DOCKER199].[mydb].[dbo schema]"}` would be problematic.

**Comment by axellpadilla** [comment] 2024-07-03 23:02
Ended here looking if this was possible, I could suggest to add a different param for this that can be implemented on more ways (that wouldn't have changes to existing implementations).
For example, add this template where schema and table continue to work as expected:
param name example : path_prefix: list[str]
then build the path as user suggested with that prefix:
for example, if the list is ['linked_server']
then it should return [linked_server].[database].[schema].[table] or "linked_server"."database"."schema"."table"

**Comment by zzzeek** [comment] 2024-07-04 15:57
hi all -

I dont understand this bug nor what I was talking about in 2020.   There is no "two token" limitation on the SQL Server dialect.  [the docs](https://docs.sqlalchemy.org/en/20/dialects/mssql.html#multipart-schema-names) indicate you can use brackets to set up individual tokens as much as you'd like.  Here is a demonstration:

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.dialects import mssql
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    __table_args__ = {'schema': '[Earth].[USA].[yourtown].[Server2].[DB_name].[owner]'}


print(select(A).compile(dialect=mssql.dialect()))

```

you get:

```
SELECT [Earth].[USA].[yourtown].[Server2].[DB_name].owner.a.id, [Earth].[USA].[yourtown].[Server2].[DB_name].owner.a.data 
FROM [Earth].[USA].[yourtown].[Server2].[DB_name].owner.a
```


now if what's being asked in some of the comments here is **reflecting tables from remote databases**, that's a totally different thing that I dont know we can support.  However, that would please be stated **clearly** in a new bug of its own.  As far as I can tell here, this issue looks like a dupe of #5366 since I cannot see what else I'm supposed to be doing here.

Closing this, so that if someone still has a problem, please make a **new** bug that **clearly and succinctly demonstrates what is wanted using complete Python code**, thanks.

**Closed by zzzeek** 2024-07-04 15:57 UTC
Labels: sql, SQL Server, cant reproduce, use case
