### ISSUE TITLE
insert().from_select ignores column_expression

### ISSUE THREAD

**Issue by notzippy** [sqlalchemy/sqlalchemy#5625] opened 2020-10-02 22:30 UTC
**Describe the bug**
When converting the select object to text the `column_expression` values are ignored

**Expected behavior**
When converting the select statement the `column_expression` is respected

**To Reproduce**

```py

class WrapColumn(TypeDecorator):
  impl = VARCHAR

  def column_expression(self, col):
    return func.WRAP_ME(col)

metadata = MetaData()
t1 = Table('t1',metadata, Column('a'), Column('b', WrapColumn))
print("aaaa*** ",t1.insert().from_select(t1.columns,t1.select()))
print("bbbb*** ",t1.select())
```

**Output**

```
aaaa***  INSERT INTO t1 (a, b) SELECT t1.a, t1.b 
FROM t1
bbbb***  SELECT t1.a, WRAP_ME(t1.b) AS b 
FROM t1
```

**Versions.**
 - OS: Linux
 - Python: 3 
 - SQLAlchemy: Latest
 - Database: NA
 - DBAPI: NA

**Comment by zzzeek** [comment] 2020-10-03 00:52
hi there -

this is by design.   column_expression() is intended for SQL coercions that are to assist in the data actually being passed to the application.   it doesnt take effect for subqueries.   if you want an INSERT..FROM SELECT with casting you would apply that manually within the select() you create.

**Comment by zzzeek** [comment] 2020-10-10 15:50
closing this for now.

**Closed by zzzeek** 2020-10-10 15:50 UTC
Labels: question
