### ISSUE TITLE
ValueError: not enough values to unpack expected 5, got 4

### ISSUE THREAD

**Issue by chenqiang19** [sqlalchemy/sqlalchemy#8722] opened 2022-10-27 07:31 UTC
### Describe the bug

when i execute db.fetch_all(query), then ValueError: not enough values to unpack expected 5, got 4 is existed

### To Reproduce

```python
Settings = Table(
    "settings",
    METADATA,
    Column("key", String(length=128), nullable=False, index=True, unique=True),
    Column("value", JSON, nullable=True),
)

query = select([Settings])
    db = DB.get()
    async with db.transaction():
        result = await db.fetch_all(query)
```

### Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xxx/api/v1/setting.py", line 114, in list_settings
    db_settings = await db_api.list_settings()
  File "/usr/local/lib/python3.8/dist-packages/xxx/db/api.py", line 35, in wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/xxx/db/api.py", line 84, in list_settings
    result = await db.fetch_all(sql)
  File "/usr/local/lib/python3.8/dist-packages/databases/core.py", line 149, in fetch_all
    return await connection.fetch_all(query, values)
  File "/usr/local/lib/python3.8/dist-packages/databases/core.py", line 271, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/usr/local/lib/python3.8/dist-packages/databases/backends/sqlite.py", line 95, in fetch_all
    metadata = CursorResultMetaData(context, cursor.description)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/cursor.py", line 190, in __init__

### Versions

- OS: Centos 8
- Python: 3.8
- SQLAlchemy: 1.4.42
- Database: sqlite3
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

### Additional context

I modified /usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/cursor.py 
 _compile():
            execution_context.result_column_struct = (
                compiled._result_columns,
                compiled._ordered_columns,
                compiled._textual_ordered_columns,
                None,  # add
                compiled._loose_column_name_matching,
            )
when I add None in excution_context.result_column_struct，the error disappeared.

**Comment by CaselIT** [comment] 2022-10-27 07:35
Hi,

this is a duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/8697
The issue is not in sqlalchemy. Please report to the external library you are using

**Closed by CaselIT** 2022-10-27 07:35 UTC
Labels: duplicate, external library issues

**Comment by chenqiang19** [comment] 2022-10-27 07:36
> Hi,
> 
> this is a duplicate of #8697 The issue is not in sqlalchemy. Please report to the external library you are using

thank you

**Comment by m986883511** [comment] 2023-10-20 02:21
skyline apiserver 的代码，哈哈哈 我也是这个问题
