### ISSUE TITLE
New python breaks sqlalchemy

### ISSUE THREAD

**Issue by shailoantz** [sqlalchemy/sqlalchemy#5458] opened 2020-07-14 14:18 UTC
**Describe the bug**
Failure in declarative base creation (see *error* section)

**Expected behavior**
successfully create a declarative base...

**To Reproduce**
Update to python 3.8.4 and run sqlalchemy with this code

```py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
db = SQLAlchemy(app)
```

**Error**

   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 715, in __init__
     self.Model = self.make_declarative_base(model_class, metadata)
   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 797, in make_declarative_base
     model.query_class = self.Query
   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
     _add_attribute(cls, key, value)
   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/declarative/base.py", line 802, in _add_attribute
     type.__setattr__(cls, key, value)
 TypeError: can't apply this __setattr__ to DefaultMeta object

**Versions.**
 - OS: Debian slim-buster
 - Python: 3.8.4
 - SQLAlchemy: 1.3.18
 - Database: postgres
 - DBAPI: psycopg2

**Have a nice day!**

**Comment by potiuk** [comment] 2020-07-14 14:41
I confirm the same problem in Apache Airflow.

https://github.com/apache/airflow/runs/869380117?check_suite_focus=true#step:6:225

We temporarily pinned to 3.8.3 but It awfully looks like sqlalchemy error not Python's

**Comment by hmvp** [comment] 2020-07-14 15:27
Can confirm this issue.

Probably related to: https://bugs.python.org/issue39960 which was fixed in 3.8.4

**Comment by zzzeek** [comment] 2020-07-14 16:14
AFAICT this is https://github.com/pallets/flask-sqlalchemy/issues/852 which is fixed on the flask side please confirm

**Comment by davidism** [comment] 2020-07-14 16:17
This is specifically an issue with something Flask-SQLAlchemy was doing. It was never clear that it was wrong until this change in cpython, although flake8 did catch it in our development version a few months ago. I am working on a bugfix release.

**Comment by davidism** [comment] 2020-07-14 16:48
Flask-SQLAlchemy 2.4.4 released: https://pypi.org/project/Flask-SQLAlchemy/2.4.4/

**Comment by CaselIT** [comment] 2020-07-14 17:19
I guess we can close?

**Closed by CaselIT** 2020-07-14 17:19 UTC
Labels: external extension issues

**Comment by potiuk** [comment] 2020-07-14 17:34
Confirmed it works. Thanks for super-fast fix!
