### ISSUE TITLE
create_async_engine creator should support async functions

### ISSUE THREAD

**Issue by BlackDereker** [sqlalchemy/sqlalchemy#9732] opened 2023-05-02 17:30 UTC
### Describe the use case

One potential use case for supporting async functions in the `creator` parameter is to allow for the creation of database connections asynchronously. This is especially useful when an application needs to perform long-running database operations that would block the event loop if executed synchronously.

By allowing the `creator` parameter to support async functions, developers can create new connections asynchronously, which can help to improve the overall performance and responsiveness of the application. This is because the event loop can continue processing other tasks while the database operation is being executed in the background.

For example, imagine an application that needs to fetch data from multiple database tables and then perform some complex data processing on that data. By using an async function as the `creator` parameter in the `create_async_engine` function, the application can create new connections asynchronously and fetch data from multiple tables in parallel, thereby reducing the overall time it takes to fetch and process the data.

In summary, supporting async functions in the `creator` parameter can help to improve the performance and responsiveness of applications that use SQLAlchemy or other ORM libraries, especially when dealing with long-running database operations.

### Databases / Backends / Drivers targeted

This is specially target CloudSQL GCP service, using PostgreSQL and asyncpg driver.

### Example Use

```python
from google.cloud.sql.connector import Connector
import sqlalchemy

# function to return the database connection
async def getconn() -> pymysql.connections.Connection:
    async with Connector() as connector:
        conn: pymysql.connections.Connection = await connector.connect_async(
            "project:region:instance",
            "asyncpg",
            user="my-user",
            password="my-password",
            db="my-db-name"
        )
    return conn

# create connection pool
pool = sqlalchemy.create_async_engine(
    "postgresql+asyncpg://",
    creator=getconn,
)
```

**Comment by BlackDereker** [comment] 2023-05-02 17:36
This has been mentioned on `cloud-sql-python-connector`

Issue: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector

**Comment by zzzeek** [comment] 2023-05-02 17:38
hi -

this is a dupe of #8215.  We are accepting PRs with tests for this feature.

**Closed by zzzeek** 2023-05-02 17:38 UTC
Labels: duplicate, use case
