### ISSUE TITLE
update...values expressions are lost due to differences in how insert/update handle these keys

### ISSUE THREAD

**Issue by mhwaage** [sqlalchemy/sqlalchemy#9075] opened 2023-01-10 11:47 UTC
### Describe the bug

I have been trying to perform a bulk update using `connection.execute` and values added as a connection parameter. The update is conditional, some of the values are nullable and can either be null in the update value _or_ in the existing value, in which case I want to choose the non-NULL value, using `func.COALESCE`. Unfortunately, the coalesce statement appears to be dropped when passing the update `stmt` to `connection.execute`.

I am able to work around the issue by passing `text(str(stmt))` instead of `stmt`.

### To Reproduce

```python
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import create_engine, insert, update, select, bindparam, func, text


class Base(DeclarativeBase):
    pass

class Foo(Base):
    __tablename__ = "Foo"
    id: Mapped[int] = mapped_column(primary_key=True)
    number: Mapped[int]
    optional_number: Mapped[int | None] = mapped_column(default=None)


engine=create_engine('sqlite://',echo=True)

Base.metadata.create_all(engine)

with engine.connect() as connection:
    connection.execute(
        insert(Foo),
        [
            {"id":1, "number": 1, "optional_number": 1},
            {"id":2, "number": 2, "optional_number": None},
            {"id":3, "number": 3, "optional_number": 3},
        ]
    )
    connection.commit()
    

with engine.connect() as connection:
    vals = connection.execute(
        select(Foo.id, Foo.number, Foo.optional_number).order_by(Foo.id)
    ).tuples().all()

    assert vals == [(1, 1, 1), (2, 2, None), (3, 3, 3)]


updated_values = [
    {"u_id":1, "number": 1, "optional_number": None},
    {"u_id":2, "number": 2, "optional_number": 2},
]

with engine.connect() as connection:
    stmt = update(Foo).where(
            Foo.id == bindparam("u_id")
        ).values(
            number=bindparam("number"),
            optional_number=func.COALESCE(bindparam("optional_number"), Foo.optional_number)
        )

    connection.execute(
        stmt,  # Works: text(str(stmt))
        updated_values
    )
    connection.commit()

with engine.connect() as connection:
    vals = connection.execute(
        select(Foo.id, Foo.number, Foo.optional_number).order_by(Foo.id)
    ).tuples().all()

    assert vals == [(1, 1, 1), (2, 2, 2), (3, 3, 3)]  # Fails, as vals == [(1, 1, None), (2, 2, 2), (3, 3, 3)]
```

### Error

```
(connection-execute-update-func-py3.10) python repro.py
2023-01-10 12:45:12,148 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-10 12:45:12,148 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Foo")
2023-01-10 12:45:12,148 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-10 12:45:12,156 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("Foo")
2023-01-10 12:45:12,156 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-10 12:45:12,159 INFO sqlalchemy.engine.Engine
CREATE TABLE "Foo" (
        id INTEGER NOT NULL,
        number INTEGER NOT NULL,
        optional_number INTEGER,
        PRIMARY KEY (id)
)


2023-01-10 12:45:12,171 INFO sqlalchemy.engine.Engine [no key 0.01113s] ()
2023-01-10 12:45:12,174 INFO sqlalchemy.engine.Engine COMMIT
2023-01-10 12:45:12,179 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-10 12:45:12,180 INFO sqlalchemy.engine.Engine INSERT INTO "Foo" (id, number, optional_number) VALUES (?, ?, ?)
2023-01-10 12:45:12,182 INFO sqlalchemy.engine.Engine [generated in 0.00290s] [(1, 1, 1), (2, 2, None), (3, 3, 3)]
2023-01-10 12:45:12,184 INFO sqlalchemy.engine.Engine COMMIT
2023-01-10 12:45:12,188 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-10 12:45:12,189 INFO sqlalchemy.engine.Engine SELECT "Foo".id, "Foo".number, "Foo".optional_number 
FROM "Foo" ORDER BY "Foo".id
2023-01-10 12:45:12,190 INFO sqlalchemy.engine.Engine [generated in 0.00192s] ()
2023-01-10 12:45:12,191 INFO sqlalchemy.engine.Engine ROLLBACK
2023-01-10 12:45:12,196 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-10 12:45:12,197 INFO sqlalchemy.engine.Engine UPDATE "Foo" SET number=?, optional_number=? WHERE "Foo".id = ?
2023-01-10 12:45:12,198 INFO sqlalchemy.engine.Engine [generated in 0.00177s] [(1, None, 1), (2, 2, 2)]
2023-01-10 12:45:12,200 INFO sqlalchemy.engine.Engine COMMIT
2023-01-10 12:45:12,201 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-10 12:45:12,202 INFO sqlalchemy.engine.Engine SELECT "Foo".id, "Foo".number, "Foo".optional_number
FROM "Foo" ORDER BY "Foo".id
2023-01-10 12:45:12,203 INFO sqlalchemy.engine.Engine [cached since 0.01488s ago] ()
2023-01-10 12:45:12,204 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "C:\Appl\repos\sqlalchemy_beta_issues_repro\connection_execute_update_func\repro.py", line 63, in <module>
    assert vals == [(1, 1, 1), (2, 2, 2), (3, 3, 3)]
AssertionError
``` 

### Versions

- OS: Windows 10
- Python: 3.10, 3.11
- SQLAlchemy: 2.0.0rc1, 2.0.0rc2
- Database: sqlite, postgresql
- DBAPI: psycopg2, sqlite

**Comment by zzzeek** [comment] 2023-01-10 13:39
This is expected behavior but probably should not pass silently without a warning.  

Here's a 1.4 case, since a warning here would be nice for a backport, if one is possible:

```py
from sqlalchemy import bindparam
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import func
from sqlalchemy import insert
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import update
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Mapped

Base = declarative_base()



class Foo(Base):
    __tablename__ = "Foo"
    id: Mapped[int] = Column(Integer, primary_key=True)
    number: Mapped[int] = Column(Integer)
    optional_number: Mapped[int | None] = Column(Integer)


engine = create_engine("sqlite://", echo=True, future=True)

Base.metadata.create_all(engine)

with engine.connect() as connection:
    connection.execute(
        insert(Foo),
        [
            {"id": 1, "number": 1, "optional_number": 1},
            {"id": 2, "number": 2, "optional_number": None},
            {"id": 3, "number": 3, "optional_number": 3},
        ],
    )
    connection.commit()


with engine.connect() as connection:
    vals = (
        connection.execute(
            select(Foo.id, Foo.number, Foo.optional_number).order_by(Foo.id)
        )
        .all()
    )

    assert vals == [(1, 1, 1), (2, 2, None), (3, 3, 3)]


updated_values = [
    {"u_id": 1, "number": 1, "optional_number": None},
    {"u_id": 2, "number": 2, "optional_number": 2},
]

with engine.connect() as connection:
    stmt = (
        update(Foo)
        .where(Foo.id == bindparam("u_id"))
        .values(
            number=bindparam("number"),
            optional_number=func.COALESCE(
                bindparam("optional_number"), Foo.optional_number
            ),
        )
    )

    connection.execute(stmt, updated_values)  # Works: text(str(stmt))
    connection.commit()

with engine.connect() as connection:
    vals = (
        connection.execute(
            select(Foo.id, Foo.number, Foo.optional_number).order_by(Foo.id)
        )
        .all()
    )

    assert vals == [
        (1, 1, 1),
        (2, 2, 2),
        (3, 3, 3),
    ]  # Fails, as vals == [(1, 1, None), (2, 2, 2), (3, 3, 3)]

```

use bound parameter names that are distinct from the column names:

```py
updated_values = [
    {"u_id": 1, "number_": 1, "optional_number_": None},
    {"u_id": 2, "number_": 2, "optional_number_": 2},
]

with engine.connect() as connection:
    stmt = (
        update(Foo)
        .where(Foo.id == bindparam("u_id"))
        .values(
            number=bindparam("number_"),
            optional_number=func.COALESCE(
                bindparam("optional_number_"), Foo.optional_number
            ),
        )
    )

```


for an INSERT, an error is raised if you use a bound parameter name with the same name as a column.  not sure why one is not happening here for UPDATE.

**Comment by zzzeek** [comment] 2023-01-10 13:42
Hmm OK the error is if you use a bindparam with that name in the WHERE clause:

```py
sqlalchemy.exc.CompileError: bindparam() name 'id' is reserved for automatic usage in the VALUES or SET clause of this insert/update statement.   Please use a name other than column name when using bindparam() with insert() or update() (for example, 'b_id').
```

for the VALUES / SET clause, both insert/update let it pass, an expression within insert seems to work.  which suggests insert is doing the right thing here, update is not.

**Comment by zzzeek** [comment] 2023-01-10 13:55
OK, it's a bug at least back to 1.4, likely not in 1.3, the difference between update/insert can be fixed with a patch like this:

```diff
diff --git a/lib/sqlalchemy/sql/crud.py b/lib/sqlalchemy/sql/crud.py
index 48ab721286..95e6d67348 100644
--- a/lib/sqlalchemy/sql/crud.py
+++ b/lib/sqlalchemy/sql/crud.py
@@ -75,14 +75,14 @@ def _get_crud_params(compiler, stmt, compile_state, **kw):
         ]
 
     if compile_state._has_multi_parameters:
-        spd = compile_state._multi_parameters[0]
-        stmt_parameter_tuples = list(spd.items())
+        spd = {_column_as_key(key) for key in compile_state._multi_parameters[0]}
+        stmt_parameter_tuples = list(compile_state._multi_parameters[0].items())
     elif compile_state._ordered_values:
-        spd = compile_state._dict_parameters
+        spd = {_column_as_key(key) for key in compile_state._dict_parameters}
         stmt_parameter_tuples = compile_state._ordered_values
     elif compile_state._dict_parameters:
-        spd = compile_state._dict_parameters
-        stmt_parameter_tuples = list(spd.items())
+        spd = {_column_as_key(key) for key in compile_state._dict_parameters}
+        stmt_parameter_tuples = list(compile_state._dict_parameters.items())
     else:
         stmt_parameter_tuples = spd = None
 
@@ -496,6 +496,7 @@ def _append_param_parameter(
         c, use_table=compile_state.include_table_with_column_exprs
     )
 
+
     if coercions._is_literal(value):
         value = _create_bind_param(
             compiler,

```

**Comment by zzzeek** [comment] 2023-01-10 14:06
breaks for INSERTs in main, not in 1.4.  wow

**Comment by zzzeek** [comment] 2023-01-10 14:34
and it's only for ORM entities, not Table, that is it's interacting with the ORM compiler constructs here.

overall an all-day issue to try to test and explain

**Comment by mhwaage** [comment] 2023-01-11 07:12
Oh, I was not aware that the restriction was generally on bindparam - I had noticed the errror raising on the `where` clause when making the example, but didn't think to check if that would be an issue within the update statement. Thanks alot for the fast response!

**Comment by zzzeek** [comment] 2023-01-11 13:09
it's a pretty gray area but hopefully the changes im pushing will at least provide adequate guardrails

**Closed** 2023-01-11 17:49 UTC
Labels: bug, sql

**Comment by zzzeek** [comment] 2023-01-11 17:51
this wasn't actually a gray area, there were already tests in place for the correct behavior, the use case you have above.  it just wasn't working for ORM entities.
