### ISSUE TITLE
Duplicate `with_loader_criteria` injected in queries

### ISSUE THREAD

**Issue by Kaelten** [sqlalchemy/sqlalchemy#7955] opened 2022-04-22 00:18 UTC
### Describe the bug

Using the below code I ended up with many copies of the resulting where clause being injected into queries.  Each select during the same session had an additional `cls.deleted_at IS NULL` attached to it.

It's very possible that I'm using this feature incorrectly.  It appears to be a fairly advanced one.  

### To Reproduce

```python
@declarative_mixin
class SoftDeleteMixin:
    deleted_at: Mapped[datetime.datetime | None] = Column(DateTime, nullable=True)

@event.listens_for(Session, 'do_orm_execute')
def _add_soft_delete_filter(state: ORMExecuteState) -> None:
    if not state.is_select:
        return

    state.statement = state.statement.options(
        with_loader_criteria(
            SoftDeleteMixin,
            lambda cls: cls.deleted_at.is_(None),
            include_aliases=True,
        )
    )
```

### Error

```sql
WHERE cls.deleted_at IS NULL AND cls.deleted_at IS NULL AND cls.deleted_at IS NULL
``` 

### Versions

- OS: macos
- Python: 3.10
- SQLAlchemy: 1.4
- Database: postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pg8000

### Additional context

I was able to get the behavior to stop by adding `propagate_to_loaders=False,` to the loader criteria.  Then they all have a single one.

**Comment by zzzeek** [comment] 2022-04-22 13:47
hey there -

I need **way** more informaion than this to do anything here.  Please provide complete mappings and example queries in [MVCE](http://stackoverflow.com/help/mcve) format so that I can run the script and see what's going on.

thanks!

**Comment by zzzeek** [comment] 2022-04-22 13:55
here's an MCVE you can start with.  I tried many combinations of using the same statement repeatedly, turning off the cache, can't reproduce.  if you can alter this example to reproduce your issue we can get started.

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import DateTime
from sqlalchemy import event
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import declarative_mixin
from sqlalchemy.orm import ORMExecuteState
from sqlalchemy.orm import Session
from sqlalchemy.orm import with_loader_criteria

Base = declarative_base()




@declarative_mixin
class SoftDeleteMixin:
    deleted_at = Column(DateTime, nullable=True)

@event.listens_for(Session, 'do_orm_execute')
def _add_soft_delete_filter(state: ORMExecuteState) -> None:
    if not state.is_select:
        return

    state.statement = state.statement.options(
        with_loader_criteria(
            SoftDeleteMixin,
            lambda cls: cls.deleted_at.is_(None),
            include_aliases=True,
        )
    )


class A(SoftDeleteMixin, Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.query(A).filter(A.id > 5).all()

s.execute(select(A).filter(A.id > 5)).all()

s.query(A).filter(A.id < 5).all()

stmt = select(A).filter(A.id < 5)
s.execute(stmt).all()

s.execute(stmt).all()

# try not using the cache, same statement each time
s.execute(stmt, execution_options={"compiled_cache": None}).all()
s.execute(stmt, execution_options={"compiled_cache": None}).all()
s.execute(stmt, execution_options={"compiled_cache": None}).all()

s.execute(stmt).all()

s.query(A).filter(A.data == 'hi').all()
```

**Comment by zzzeek** [comment] 2022-04-25 22:05
reopen if you can provide more details. thanks!

**Comment by Kaelten** [comment] 2022-04-26 17:30
sorry, I've been heads down and haven't had the time to try to make a sharable reproduction case yet.  

I think the missing piece from your example is likely having multiple models with the mixin.  In my case they are used in relationships between each other as well.

**Comment by zzzeek** [comment] 2022-04-26 17:35
OK but in `WHERE cls.deleted_at IS NULL AND cls.deleted_at IS NULL AND cls.deleted_at IS NULL`, "cls" is the same each time?  this is single-table inheritance maybe?

**Comment by Kaelten** [comment] 2022-04-26 20:54
> OK but in `WHERE cls.deleted_at IS NULL AND cls.deleted_at IS NULL AND cls.deleted_at IS NULL`, "cls" is the same each time? this is single-table inheritance maybe?

Yes it's the same class each time.  Right now I don't have any inheritance on my models, just a common base class with a few helpers on it and mixins for my common fields/patterns (id, dates, soft deletes).  Is it worth noting that I'd actually have multiple mixins at play here?  Since I'd have one for the Id and another adding `created_at` and `updated_at` as well?

While I'm not doing anything special/directly with mappers, I did find it pretty interesting that adding `propagate_to_loaders=False,` to the `with_loader_criteria` call  eliminated the behavior.

```python
engine = create_engine(
    get_settings().database_dsn,
    future=True,
    pool_size=20,
    pool_pre_ping=True,
    pool_use_lifo=True,
    echo=get_settings().debug_mode,
)

session_maker: Callable[[], Session] = sessionmaker(
    future=True,
    bind=engine,
)
```

The above shows how I'm defining my engine and sessions and this is the code I have for my base class.

```python
class _Base:  # noqa: PIE798

    @declared_attr
    def __tablename__(self: Type['_Model']) -> str:
        return snakecase(self.__name__)


_SQLBase = declarative_base(cls=_Base)


class SQLBase(_SQLBase):
    __abstract__ = True

    @classmethod
    def objects(cls: Type['_Model'], session: Session) -> 'Objects[Type[_Model]]':
        return Objects[cls](cls, session)
```

I do want to get to working out a reproduction case for you, I'm just under some deadlines :(

**Comment by zzzeek** [comment] 2022-04-26 21:13
> Since I'd have one for the Id and another adding created_at and updated_at as well?

that certainly seems like it might be involved.  this might be something you need to detect on your end if it's something like that but we'd want to document that and make sure the right APIs are available if that's the case.

**Comment by Kaelten** [comment] 2022-04-27 19:13
Took me a little while to whittle things down to a good reproduction case. 

```python
from sqlalchemy import Column, ForeignKey, DateTime, Integer, create_engine, event, select
from sqlalchemy.orm import ORMExecuteState, Session, declarative_base, sessionmaker, relationship, declarative_mixin, \
    with_loader_criteria

engine = create_engine(
    'sqlite://',
    echo=True,
)

session_maker = sessionmaker(
    bind=engine,
)

SQLBase = declarative_base()


@declarative_mixin
class SoftDeleteMixin:
    deleted_at = Column(DateTime, nullable=True)


@event.listens_for(Session, 'do_orm_execute')
def _add_soft_delete_filter(state: ORMExecuteState) -> None:
    if not state.is_select:
        return

    state.statement = state.statement.options(
        with_loader_criteria(
            SoftDeleteMixin,
            lambda cls: cls.deleted_at.is_(None),
            include_aliases=True,
        )
    )


class Parent(SQLBase, SoftDeleteMixin):
    __tablename__ = 'parent'

    id = Column(Integer, primary_key=True)
    children = relationship('Child')


class Child(SQLBase, SoftDeleteMixin):
    __tablename__ = 'child'

    id = Column(Integer, primary_key=True)
    order = Column(Integer)

    parent_id = Column(Integer, ForeignKey('parent.id'))
    parent = relationship('Parent', back_populates='children')


SQLBase.metadata.create_all(engine)

with session_maker() as session:
    parent = Parent(id=1)
    child_a = Child(order=1, parent=parent)
    child_b = Child(order=2, parent=parent)

    session.add_all([parent, child_a, child_b])
    session.commit()

with session_maker() as session:
    parent = session.execute(select(Parent).where(Parent.id == 1)).one_or_none()[0]
    children = parent.children
```

It appears related to how relationships work.  I've removed as many options and configs as I could and still seeing it happen on the very last line. 

```
22-04-27 12:11:56,857 INFO sqlalchemy.engine.Engine SELECT child.deleted_at AS child_deleted_at, child.id AS child_id, child."order" AS child_order, child.parent_id AS child_parent_id 
FROM child 
WHERE ? = child.parent_id AND child.deleted_at IS NULL AND child.deleted_at IS NULL
```

**Comment by zzzeek** [comment] 2022-04-27 19:52
alrighty, with_loader_criteria applies to relationship loaders automatically, so you have to exclude them:

```py
@event.listens_for(Session, 'do_orm_execute')
def _add_soft_delete_filter(state: ORMExecuteState) -> None:
    if (
            state.is_select
            and not state.is_column_load
            and not state.is_relationship_load
        ):
        state.statement = state.statement.options(
            with_loader_criteria(
                SoftDeleteMixin,
                lambda cls: cls.deleted_at.is_(None),
                include_aliases=True,
            )
        )

```

this is copied from the example at https://docs.sqlalchemy.org/en/14/orm/query.html?highlight=with_loader_criteria#sqlalchemy.orm.with_loader_criteria but it's also in the main example at https://docs.sqlalchemy.org/en/14/orm/session_events.html#do-orm-execute-global-criteria

**Comment by Kaelten** [comment] 2022-04-27 19:58
Gotcha.  I read over those docs multiple times while I was trying to get this working and for some reason the purpose of the `is_column_load` and `is_relationship_load` checks didn't compute with me each time.  I tried to find documentation around the state object itself to understand what each field signified, but completely failed to. 

I'm also struggling to remember where, but it seemed like sone joins didn't get the filter when I had them in, but that might have just been me not putting two and two together properly.

**Comment by zzzeek** [comment] 2022-04-27 20:18
so my notion for the docs is that you'd probably see this:

https://docs.sqlalchemy.org/en/14/orm/events.html#sqlalchemy.orm.SessionEvents.do_orm_execute

or this:

https://docs.sqlalchemy.org/en/14/orm/session_events.html#execute-events

then we assume, maybe this is not enough, that people would click on any of the highlighted ORMExecuteState names in those docs, which takes you to https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.ORMExecuteState which has all the attributes.    You can also search for ORMExecuteState in the sidebar.   how can we make that more apparent?

**Comment by Kaelten** [comment] 2022-04-27 20:30
Hrm, I think part of it was finding this page originally. 

https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html

I don't recall exactly how I ended up on that page, but I believe it was either linked to from a blog post or maybe an issue.  I think it was talking about making an exception to the global application using a query option.  So that you could do some form of `with_deleted` flag on the query and opt-out of the filtering.

As far as this page: https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.ORMExecuteState

This does break it down more, I don't know why I failed to find it before, probably because I didn't think to look it up by class name and instead just tried searching for "execution state" or similar.  

As far as my failure to grock some of this. I think it's a bit of jargon related issue.  Reading the details on `is_column_load` and `is_relationship_load ` now I can understand roughly why we'd want to exclude those.  Specifically the `is_relationship_load`.  

However, I'm not certain that I'd actually want to add them to the event handler.

For example, if I had a foreign key over to another table and the target of the relationship is soft-deleted I'd want it to be a null result on the relation even though it'd be a straight get.  It's maybe not ideal in it's own way, but soft-deletes as a whole are a bit of a necessary  pain as well.

**Comment by Kaelten** [comment] 2022-04-27 20:31
Sidenote @zzzeek, I truly appreciate your high level of engagement and civility as I'm stumbling through this report.  Thank you.

**Comment by zzzeek** [comment] 2022-05-10 02:32
anyway no issue here, so closing

**Closed by zzzeek** 2022-05-10 02:32 UTC
Labels: question, documentation, orm, expected behavior
