### ISSUE TITLE
don't mutate attributes on get(), have it work for collections as well

### ISSUE THREAD

**Issue by adithepnarula** [sqlalchemy/sqlalchemy#4519] opened 2019-02-28 22:11 UTC
**Problem:**
1-to-many (e.g., "videos" below) fields of transient/detached objects automatically load empty lists as values after they've been accessed. As shown in the example below, an unbound user object gets created. The first set of asserts show that none of the fields have values loaded, except for `first_name`. After we access the fields through print statements, the last test fails because `mapper.attrs.videos.loaded_value == []`. I would expect videos' value to remain unloaded after the print statement. 

This could lead to problems… for example, if you access a transient object's 1-to-many field, merge the object (using session.merge(obj)) and commit,  the existing relationship values, if exist, gets replaced with an empty list, thus removes the children.

```python
def test_sqlalchemy_loaded_relationships():
    import sqlalchemy as sa
    from sqlalchemy.orm.base import NO_VALUE
    from sqlalchemy.ext.declarative import declarative_base
    Base = declarative_base()

    class User(Base):
        __tablename__ = 'user'

        id = sa.Column(sa.Integer, primary_key=True)
        first_name = sa.Column(sa.Text)
        last_name = sa.Column(sa.Text)
        profile = sa.orm.relationship(
            'Profile',
            uselist=False,
            single_parent=True,
            cascade='all, delete-orphan',
        )
        videos = sa.orm.relationship(
            'Video',
            cascade='all, delete-orphan',
        )

    class Profile(Base):
        __tablename__ = 'profile'

        id = sa.Column(sa.Integer, primary_key=True)
        phone_number = sa.Column(sa.Text)
        user_id = sa.Column(
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey('user.id', name='fk_profile_user_id'),
            nullable=False,
        )

    class Video(Base):
        __tablename__ = 'video'

        id = sa.Column(sa.Integer, primary_key=True)
        name = sa.Column(sa.Text)
        url = sa.Column(sa.Text)
        user_id = sa.Column(
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey('user.id', name='fk_video_user_id'),
            nullable=False,
        )

    john = User(first_name='John')

    # values are not loaded
    mapper = sa.inspect(john)
    assert mapper.attrs.first_name.loaded_value == 'John'
    assert mapper.attrs.last_name.loaded_value == NO_VALUE
    assert mapper.attrs.profile.loaded_value == NO_VALUE
    assert mapper.attrs.videos.loaded_value == NO_VALUE

    # when values are accessed, videos values gets loaded to empty list
    print(john.first_name)  # John
    print(john.last_name)   # None
    print(john.profile)     # None
    print(john.videos)      # []

    assert mapper.attrs.first_name.loaded_value == 'John'
    assert mapper.attrs.last_name.loaded_value == NO_VALUE
    assert mapper.attrs.profile.loaded_value == NO_VALUE
    assert mapper.attrs.videos.loaded_value == NO_VALUE  # FAILS!`

**Comment by zzzeek** [comment] 2019-03-01 14:00
unfortunately this behavior as a default cannot be changed until SQLAlchemy 2.0 at best for which there is not currently timeline.   we can only pursue options which would allow the behavior to be modified if this is actually getting in your way.

The canonical pattern for ORM objects as has been in tutorials for years is:

```
u1 = User()
u1.addresses.append(u1)
```

this would not be possible if the initializer for collections did not both return an empty collection and also establish it as the state on the attribute.

In theory, had SQLAlchemy had a completely new start, the whole concept of "initializers" might not have happened at all, and we'd simply be getting AttributeErrors for any of these operations across scalars or collections, like a regular Python object where an attribute was not set.   That would be the most correct approach and remains an option for SQLAlchemy 2.0 (adding that to the 2.0 document now).

the behavior of state change upon "get" was refined in https://docs.sqlalchemy.org/en/latest/changelog/migration_10.html#changes-to-attribute-events-and-other-operations-regarding-attributes-that-have-no-pre-existing-value to remove this behavior for all scalar values.   This was an easy change which is why you see the `NO_VALUE` for scalars, however this change could not be made for collections.   It is also less critical for collections because relationally, an empty collection is the same database representation as no collection at all.   

So the merge() case which you bring up is the only use case that continues to not function 
optimally, and in most cases people usually merge a new object immediately without scanning through the values of attributes, but certainly it's still not great that it does this.

 Additionally, in version 1.1 a new event hook [init_scalar](https://docs.sqlalchemy.org/en/latest/orm/events.html?highlight=init_scalar#sqlalchemy.orm.events.AttributeEvents.init_scalar) was added that among other things allows the old behavior of populating `__dict__` to be possible again.

no such hook has yet been implemented for collections, and it presents these challenges:

1. naming - we already have [init_collection](https://docs.sqlalchemy.org/en/latest/orm/events.html?highlight=init_collection#sqlalchemy.orm.events.AttributeEvents.init_collection), which does something different, so we'd already have to pick an inconsistent name

2. default behavior - in the init_scalar case, setting the key in the dict is the positive behavior that can be added.  in the case of "init_collection_dict" for lack of a better name, the event would need to function that setting the key in the dict is the negative behavior that can be removed.   

Looking at the code, a more expedient approach would be that the existing init_collection hook can itself return `None` or `NO_VALUE` and this would be taken to mean that the collection should not be initialized.

Also it might be nice if both `init_collection` and `init_scalar` could support raising AttributeError(), that probably can be done now but there could be more well-supported methods of achieving this.

I would ask whether or not you think it's even reasonble that "object.id" returns None.  Would you prefer this raise AttributeError, and if not why not ?

**Comment by timc13** [comment] 2019-03-18 17:00
I'm leaning towards raising an AttributeError.  If we are talking about detached objects and/or un-initialized fields - i think it's reasonable to expect an error if you haven't explicitly set or initialized a value.

**Comment by zzzeek** [comment] 2019-04-27 15:52
the deliverable here will be to remove the auto-initialize by default.   *maybe* we would like to continue to have a flag in `__mapper_args__` that turn on the old behavior.    #4640 will address forwards compatibility for 1.4.

**Comment by zzzeek** [comment] 2019-05-13 18:51
major important thing noticed in #4676:

do NOT raise attribute error if the object is persistent or detached.  the natural default value of a Column is NULL, and while there is no server default to fetch, there shouldn't have to be. there needs to be a separate concept of the implicit NULL default for all persistent columns.   might make this more complicated.

**Comment by zzzeek** [comment] 2019-05-25 21:50
> I'm leaning towards raising an AttributeError. If we are talking about detached objects and/or un-initialized fields - i think it's reasonable to expect an error if you haven't explicitly set or initialized a value.

I agree this "seems" correct but this is not what users are expecting; if this change were made, and an option were added to keep it working the "old" way, everyone would be turning that option on.   The argument can be made that the transient object represents an empty database row, so it is normal that the columns would all be NULL and collections would be empty; there's no "null collection" in SQL.  I'd imagine you can argue this all the other way too, but the idea is, it's OK that the ORM object is a little different than a raw Python object and switching this would be enormously difficult for users to adjust towards.

The example at the top is looking at an attribute called "loaded_value", and actually that's kind of a bug as well because the object is transient, nothing is "loaded", technically it should be NO_VALUE all the way, but that accessor wasn't intended to be used on transient objects.  But in any case, it would be nice if it behaved consistently and especially if we no longer mutated anything when we access attributes but dont set or mutate anything.  The change in #3061 years ago did this for scalar attributes but for collections there didn't seem to be an easy path.

Anyway I came up with a way to not mutate `__dict__` on collection get while still having everything work, so that's coming in and it will include tests for the merge case mentioned here.

**Comment by sqla-tester** [comment] 2019-05-25 22:18
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Hold implicitly created collections in a pending area** https://gerrit.sqlalchemy.org/1283

**Comment by zzzeek** [comment] 2019-08-21 23:03
untested regression:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    bs = relationship("B")

class B(Base):
    __tablename__ = 'b'

    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey('a.id'))

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

a1 = A(bs=[B(), B(), B()])

s = Session(e)
s.add(a1)
s.commit()

a1 = s.query(A).options(joinedload(A.bs)).first()

```

```
Traceback (most recent call last):
  File "test3.py", line 30, in <module>
    a1 = s.query(A).options(joinedload(A.bs)).first()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3229, in first
    ret = list(self[0:1])
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 3019, in __getitem__
    return list(res)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 85, in instances
    rows = [proc(row) for row in fetch]
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 615, in _instance
    populators,
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/loading.py", line 757, in _populate_partial
    populator(state, dict_, row)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/strategies.py", line 1983, in load_collection_from_joined_new_row
    collection = attributes.init_state_collection(state, dict_, key)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/attributes.py", line 1898, in init_state_collection
    adapter._reset_empty()
AttributeError: 'NoneType' object has no attribute '_reset_empty'

```

**Comment by sqla-tester** [comment] 2019-08-22 00:20
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure discarded collection removed from empty collections** https://gerrit.sqlalchemy.org/1427

**Closed** 2019-08-22 22:01 UTC
Labels: alchemy 2, big job, bug, orm
