### ISSUE TITLE
has_mapper_entities must update for with_entities calls so that uniqifying is applied appropriately

### ISSUE THREAD

**Issue by jessehersch** [sqlalchemy/sqlalchemy#6924] opened 2021-08-21 17:44 UTC
### Describe the bug

TypeError is raised when running a query that joins two tables and has a with_entities() clause, if the with_entities contains a column that is of type sqlalchemy_utils.JSONType. That comes from the SQLAlchemy-Utils library.

I don't think this is a bug in SQLAlchemy-Utils since it worked in previous versions of SQLAlchemy? I could be wrong though, maybe it's a latent bug that some change in SQLAlchemy 1.4.19 has only now exposed.

This worked in SQLAlchemy 1.4.18, error started with SQLAlchemy 1.4.19 and persists in all versions above that. 

I found that it works in 1.4.18 because `self._unique_filter_state` is None in call to `ResultInternal._iterator_getter()` in sqlalchemy/engine/result.py. In versions greater than that, `self._unique_filter_state` is set to a 2-tuple with value `(set(), None)`. A different code path is walked down when it's not null, which is what raises the error:
https://github.com/sqlalchemy/sqlalchemy/blob/680baea6b83c497e862f3f0ade28e11940cfd895/lib/sqlalchemy/engine/result.py#L364

### To Reproduce

```python
"""
pip install SQLAlchemy-Utils==0.37.8

pip install SQLAlchemy==1.4.23

-- code below works on SQLAlchemy==1.4.18. fails on 1.4.19. so it was introduced with 1.4.19

In [2]: print(sys.version, sys.platform)
3.6.9 (default, Apr 20 2021, 10:15:16) [GCC 9.3.0] linux
"""


import sqlalchemy_utils
from sqlalchemy import Column, ForeignKey, Integer, JSON, create_engine
from sqlalchemy.orm import declarative_base, relationship, Session

Base = declarative_base()


class AAA(Base):
    __tablename__ = 'aaa'
    id = Column(Integer, primary_key=True)
    json_column = Column(sqlalchemy_utils.JSONType, nullable=False)


class BBB(Base):
    __tablename__ = 'bbb'
    id = Column(Integer, primary_key=True)
    aaa_id = Column(Integer, ForeignKey('aaa.id'), nullable=True)
    parent = relationship('AAA', backref='children')


class CCC(Base):
    __tablename__ = 'ccc'
    id = Column(Integer, primary_key=True)
    json_column = Column(JSON, nullable=False)


class DDD(Base):
    __tablename__ = 'ddd'
    id = Column(Integer, primary_key=True)
    ccc_id = Column(Integer, ForeignKey('ccc.id'), nullable=True)
    parent = relationship('CCC', backref='children')


def main():
    eng = create_engine('postgresql://postgres@localhost/mcve', echo=False)
    Base.metadata.drop_all(eng)
    Base.metadata.create_all(eng)
    db_session = Session(eng)

    db_session.add(AAA(id=13, json_column=[1, 2, 3]))
    db_session.add(BBB(id=333, aaa_id=13))

    db_session.add(CCC(id=13, json_column=[1, 2, 3]))
    db_session.add(DDD(id=333, ccc_id=13))
    db_session.commit()

    print('\nthis works')
    query = db_session.query(AAA).with_entities(AAA.id, AAA.json_column)
    for (parent_id, json_column) in query:
        print(parent_id, json_column)

    print('\nthis works also')
    query = db_session.query(AAA).join(BBB).with_entities(AAA.id)
    for (parent_id,) in query:
        print(parent_id)

    print('\nthis works also. using the JSON type instead of sqlalchemy_utils.JSONType')
    query = db_session.query(CCC).join(DDD).with_entities(CCC.id, CCC.json_column)
    for (parent_id, json_column) in query:
        print(parent_id, json_column)

    print('\nbut this fails with TypeError: unhashable type: list. '
          'Problem comes from having AAA.json_column in the with_entities() clause, then iterating over the query:')
    query = db_session.query(AAA).join(BBB).with_entities(AAA.id, AAA.json_column)
    for (parent_id, json_column) in query:
        print(parent_id, json_column)


if __name__ == '__main__':
    main()
```

### Error

```
$ python mcve.py

this works
13 [1, 2, 3]

this works also
13

this works also. using the JSON type instead of sqlalchemy_utils.JSONType
13 [1, 2, 3]

but this fails with TypeError: unhashable type: list. Problem comes from having AAA.json_column in the with_entities() clause, then iterating over the query:
Traceback (most recent call last):
  File "mcve.py", line 82, in <module>
    main()
  File "mcve.py", line 77, in main
    for (parent_id, json_column) in query:
  File "/home/jhersch/.virtualenvs/gemini3.6.9/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 371, in iterrows
    if hashed in uniques:
TypeError: unhashable type: 'list'
```

### Versions

- OS: linux
- Python: 3.6.9
- SQLAlchemy: reproduces in 1.4.19 through 1.4.23. does NOT reproduce in 1.4.18
- Database: postgresql
- DBAPI: psycopg2

### Additional context

If I look in postgres for the definitions of the relevant tables with JSON columns, I find their schemas are identical up to renames. So problem is certainly not in at the db level. I suppose it's in the ORM, when the json_column value is used. In one case it is converted to something that can be hashed (maybe a JSON string?) and in the other it's left as a list, which cannot be hashed.
```
mcve=# \d aaa
                               Table "public.aaa"
   Column    |  Type   | Collation | Nullable |             Default             
-------------+---------+-----------+----------+---------------------------------
 id          | integer |           | not null | nextval('aaa_id_seq'::regclass)
 json_column | json    |           | not null | 
Indexes:
    "aaa_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "bbb" CONSTRAINT "bbb_aaa_id_fkey" FOREIGN KEY (aaa_id) REFERENCES aaa(id)

mcve=# \d ccc
                               Table "public.ccc"
   Column    |  Type   | Collation | Nullable |             Default             
-------------+---------+-----------+----------+---------------------------------
 id          | integer |           | not null | nextval('ccc_id_seq'::regclass)
 json_column | json    |           | not null | 
Indexes:
    "ccc_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "ddd" CONSTRAINT "ddd_ccc_id_fkey" FOREIGN KEY (ccc_id) REFERENCES ccc(id)
```

**Comment by CaselIT** [comment] 2021-08-21 20:39
Hi,

I think the issue here is of the external library. Any reason for using SQLAlchemy-Utils JSONType instead of the builtin one?
As a side note, on postgres you will probably want to use jsonb instead of json as column type

**Comment by CaselIT** [comment] 2021-08-21 21:05
I think this may be due to the missing `hashable` marker in the external type:
https://github.com/sqlalchemy/sqlalchemy/blob/680baea6b83c497e862f3f0ade28e11940cfd895/lib/sqlalchemy/sql/sqltypes.py#L2312

@zzzeek any other insight?

**Comment by jessehersch** [comment] 2021-08-22 15:36
> Hi,
> 
> I think the issue here is of the external library. Any reason for using SQLAlchemy-Utils JSONType instead of the builtin one?
> As a side note, on postgres you will probably want to use jsonb instead of json as column type

main reason for using JSONType is that we run unit tests using in-memory sqlite, and JSON/JSONB does not exist there. JSONType degrades to a text column for plaforms like sqlite that don't support JSON directly. It's nicer for unit test purposes to not depend on a database server running externally.

I will look at working around this by not using JSONType and just adding our own type that has hashable=false. And file a ticket against SQLAlchemy-Utils if indeed the bug is there and not here.

**Comment by CaselIT** [comment] 2021-08-22 16:13
> main reason for using JSONType is that we run unit tests using in-memory sqlite, and JSON/JSONB does not exist there. JSONType degrades to a text column for platforms like sqlite that don't support JSON directly

You can use `with_variant` to specify a different type for a particular db.

> It's nicer for unit test purposes to not depend on a database server running externally.

Not sure I agree, since you would then not test on the actual stack that's deployed. But to each its own :)

> I will look at working around this by not using JSONType and just adding our own type that has hashable=false. And file a ticket against SQLAlchemy-Utils if indeed the bug is there and not here.

Ok. Let's also wait for mike's input

**Comment by jessehersch** [comment] 2021-08-23 00:24
I guess I don't understand why the code branch `if self._unique_filter_state` is getting stepped into in the first place. the query is not asking for unique rows only as in `SELECT DISTINCT`. If duplicates are possible then they should be returned seems to me, but this code would exclude dups I think:
```
                    if hashed in uniques:
                        continue
```
In this particular case dups are not possible due to the PK but seems that could be a coincidence.

I am not an expert in the SQLAlchemy code base however! :)

**Comment by zzzeek** [comment] 2021-08-23 00:56
did your code work in 1.3?   the with_entities() feature had a regression in 1.4 that was fixed in 1.4.19 or thereabouts, which also involved a good deal of new code to make it work the old way.   but functionally it started acting like that of 1.3.x around this version.

**Comment by jessehersch** [comment] 2021-08-23 01:32
> did your code work in 1.3? the with_entities() feature had a regression in 1.4 that was fixed in 1.4.19 or thereabouts, which also involved a good deal of new code to make it work the old way. but functionally it started acting like that of 1.3.x around this version.

Looks like the MCVE does work in 1.3.24:
```
$ pip install SQLAlchemy==1.3.24
Installing collected packages: SQLAlchemy
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 1.4.18
    Uninstalling SQLAlchemy-1.4.18:
      Successfully uninstalled SQLAlchemy-1.4.18
Successfully installed SQLAlchemy-1.3.24

$ python mcve.py 

this works
13 [1, 2, 3]

this works also
13

this works also. using the JSON type instead of sqlalchemy_utils.JSONType
13 [1, 2, 3]

but this fails with TypeError: unhashable type: list. Problem comes from having AAA.json_column in the with_entities() clause, then iterating over the query:
13 [1, 2, 3]
```

**Comment by jessehersch** [comment] 2021-08-23 02:30
I have verified that if I create my own type with hashable=false then it works. that is, if the MCVE above uses this type instead of the one in SQLAlchemy-Utils, then it passes even in 1.4.23:
```
class JSONType(sqlalchemy.types.TypeDecorator):
    """
    this is used as a workaround for sqlalchemy_utils.types.JSONType because it's not compatible with SQLAlchemy 1.4.23.
    what they are missing is a hashable=False flag on the class, because a generic chunk of JSON (e.g. a list) is not hashable
    """
    impl = sqlalchemy.UnicodeText
    cache_ok = True
    hashable = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def load_dialect_impl(self, dialect):
        if dialect.name == 'postgresql':
            return dialect.type_descriptor(sqlalchemy.dialects.postgresql.JSON())
        return dialect.type_descriptor(self.impl)

    def process_bind_param(self, value, dialect):
        if dialect.name == 'postgresql':
            return value
        if value is not None:
            return json.dumps(value)
        return value

    def process_result_value(self, value, dialect):
        if dialect.name == 'postgresql':
            return value
        if value is not None:
            return json.loads(value)
        return value
```

So all that remains here is to figure whether the underlying issue is a bug in SQLAlchemy-Utils or in SQLAlchemy itself. I don't have the experience to say for certain, but my instinct now is that the bug is in SQLAlchemy-Utils as Federico wrote earlier.

**Comment by zzzeek** [comment] 2021-08-23 14:57
it's important to note that **sqlalchemy_utils still has a bug here**, their code is wrong.  

however, SQLAlchemy's bug can be illustrated as follows:

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data="a1", bs=[B(data="b1"), B(data="b1"), B(data="b2")]))
s.commit()


r1 = s.query(A.data, B.data).select_from(A).join(B).all()

r2 = s.query(A).select_from(A).join(B).with_entities(A.data, B.data).all()


assert r1 == r2
```

with_entities needs to update the _has_mapper_entities flag.

**Comment by sqla-tester** [comment] 2021-08-23 15:30
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**qualify compile_state updates for non-current entities** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3016

**Closed** 2021-08-23 16:30 UTC
Labels: bug, orm, external library issues

**Comment by jessehersch** [comment] 2021-08-23 16:40
Thanks for identifying the real issue @zzzeek.

I will file a new one against the the utils lib.
