### ISSUE TITLE
Reflecting database with SQL server may cause "ambiguous column name" error

### ISSUE THREAD

**Issue by Lin-Your** [sqlalchemy/sqlalchemy#7812] opened 2022-03-11 09:45 UTC
### Describe the bug

My English is poor.

I want to reflect a table object in sql server 2008. But, I got this error.

### To Reproduce

```python
from sqlalchemy import MetaData, Table, create_engine

url = "mssql+pymssql://username:password@address:port/db"

engine = create_engine(url)

meta_data = MetaData()

tablename = "user"

table = Table(tablename, meta_data, autoload_with=engine)
```

### Error
```
MSSQLDatabaseException                    Traceback (most recent call last)
File src\pymssql\_pymssql.pyx:460, in pymssql._pymssql.Cursor.execute()

File src\pymssql\_mssql.pyx:1084, in pymssql._mssql.MSSQLConnection.execute_query()

File src\pymssql\_mssql.pyx:1115, in pymssql._mssql.MSSQLConnection.execute_query()

File src\pymssql\_mssql.pyx:1248, in pymssql._mssql.MSSQLConnection.format_and_run_query()

File src\pymssql\_mssql.pyx:1786, in pymssql._mssql.check_cancel_and_raise()

File src\pymssql\_mssql.pyx:1832, in pymssql._mssql.raise_MSSQLDatabaseException()

MSSQLDatabaseException: (209, b"Ambiguous column name 'constraint_schema'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

OperationalError                          Traceback (most recent call last)
File d:\test\venv\lib\site-packages\sqlalchemy\engine\base.py:1808, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1807     if not evt_handled:
-> 1808         self.dialect.do_execute(
   1809             cursor, statement, parameters, context
   1810         )
   1812 if self._has_events or self.engine._has_events:

File d:\test\venv\lib\site-packages\sqlalchemy\engine\default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

File src\pymssql\_pymssql.pyx:478, in pymssql._pymssql.Cursor.execute()

OperationalError: (209, b"Ambiguous column name 'constraint_schema'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 table = Table("goods", meta_data, autoload=True, autoload_with=engine.connect())

File <string>:2, in __new__(cls, *args, **kw)

File d:\test\venv\lib\site-packages\sqlalchemy\util\deprecations.py:309, in deprecated_params.<locals>.decorate.<locals>.warned(fn, *args, **kwargs)
    302     if m in kwargs:
    303         _warn_with_version(
    304             messages[m],
    305             versions[m],
    306             version_warnings[m],
    307             stacklevel=3,
    308         )
--> 309 return fn(*args, **kwargs)

File d:\test\venv\lib\site-packages\sqlalchemy\sql\schema.py:607, in Table.__new__(cls, *args, **kw)
    605 except Exception:
    606     with util.safe_reraise():
--> 607         metadata._remove_table(name, schema)

File d:\test\venv\lib\site-packages\sqlalchemy\util\langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     68     self._exc_info = None  # remove potential circular references
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:
     75     if not compat.py3k and self._exc_info and self._exc_info[1]:
     76         # emulate Py3K's behavior of telling us when an exception
     77         # occurs in an exception handler.

File d:\test\venv\lib\site-packages\sqlalchemy\util\compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File d:\test\venv\lib\site-packages\sqlalchemy\sql\schema.py:602, in Table.__new__(cls, *args, **kw)
    600 metadata._add_table(name, schema, table)
    601 try:
--> 602     table._init(name, metadata, *args, **kw)
    603     table.dispatch.after_parent_attach(table, metadata)
    604     return table

File d:\test\venv\lib\site-packages\sqlalchemy\sql\schema.py:677, in Table._init(self, name, metadata, *args, **kwargs)
    673 # load column definitions from the database if 'autoload' is defined
    674 # we do it after the table is in the singleton dictionary to support
    675 # circular foreign keys
    676 if autoload:
--> 677     self._autoload(
    678         metadata,
    679         autoload_with,
    680         include_columns,
    681         _extend_on=_extend_on,
    682         resolve_fks=resolve_fks,
    683     )
    685 # initialize all the column, etc. objects.  done after reflection to
    686 # allow user-overrides
    688 self._init_items(
    689     *args,
    690     allow_replacements=extend_existing or keep_existing or autoload
    691 )

File d:\test\venv\lib\site-packages\sqlalchemy\sql\schema.py:712, in Table._autoload(self, metadata, autoload_with, include_columns, exclude_columns, resolve_fks, _extend_on)
    710 insp = inspection.inspect(autoload_with)
    711 with insp._inspection_context() as conn_insp:
--> 712     conn_insp.reflect_table(
    713         self,
    714         include_columns,
    715         exclude_columns,
    716         resolve_fks,
    717         _extend_on=_extend_on,
    718     )

File d:\test\venv\lib\site-packages\sqlalchemy\engine\reflection.py:795, in Inspector.reflect_table(self, table, include_columns, exclude_columns, resolve_fks, _extend_on)
    789     raise exc.NoSuchTableError(table_name)
    791 self._reflect_pk(
    792     table_name, schema, table, cols_by_orig_name, exclude_columns
    793 )
--> 795 self._reflect_fk(
    796     table_name,
    797     schema,
    798     table,
    799     cols_by_orig_name,
    800     exclude_columns,
    801     resolve_fks,
    802     _extend_on,
    803     reflection_options,
    804 )
    806 self._reflect_indexes(
    807     table_name,
    808     schema,
   (...)
    813     reflection_options,
    814 )
    816 self._reflect_unique_constraints(
    817     table_name,
    818     schema,
   (...)
    823     reflection_options,
    824 )

File d:\test\venv\lib\site-packages\sqlalchemy\engine\reflection.py:948, in Inspector._reflect_fk(self, table_name, schema, table, cols_by_orig_name, exclude_columns, resolve_fks, _extend_on, reflection_options)
    937 def _reflect_fk(
    938     self,
    939     table_name,
   (...)
    946     reflection_options,
    947 ):
--> 948     fkeys = self.get_foreign_keys(
    949         table_name, schema, **table.dialect_kwargs
    950     )
    951     for fkey_d in fkeys:
    952         conname = fkey_d["name"]

File d:\test\venv\lib\site-packages\sqlalchemy\engine\reflection.py:564, in Inspector.get_foreign_keys(self, table_name, schema, **kw)
    533 """Return information about foreign_keys in `table_name`.
    534 
    535 Given a string `table_name`, and an optional string `schema`, return
   (...)
    560 
    561 """
    563 with self._operation_context() as conn:
--> 564     return self.dialect.get_foreign_keys(
    565         conn, table_name, schema, info_cache=self.info_cache, **kw
    566     )

File <string>:2, in get_foreign_keys(dialect, connection, tablename, schema, **kw)

File d:\test\venv\lib\site-packages\sqlalchemy\engine\reflection.py:55, in cache(fn, self, con, *args, **kw)
     53 ret = info_cache.get(key)
     54 if ret is None:
---> 55     ret = fn(self, con, *args, **kw)
     56     info_cache[key] = ret
     57 return ret

File d:\test\venv\lib\site-packages\sqlalchemy\dialects\mssql\base.py:2576, in _db_plus_owner.<locals>.wrap(dialect, connection, tablename, schema, **kw)
   2574 def wrap(dialect, connection, tablename, schema=None, **kw):
   2575     dbname, owner = _owner_plus_db(dialect, schema)
-> 2576     return _switch_db(
   2577         dbname,
   2578         connection,
   2579         fn,
   2580         dialect,
   2581         connection,
   2582         tablename,
   2583         dbname,
   2584         owner,
   2585         schema,
   2586         **kw
   2587     )

File d:\test\venv\lib\site-packages\sqlalchemy\dialects\mssql\base.py:2600, in _switch_db(dbname, connection, fn, *arg, **kw)
   2596         connection.exec_driver_sql(
   2597             "use %s" % connection.dialect.identifier_preparer.quote(dbname)
   2598         )
   2599 try:
-> 2600     return fn(*arg, **kw)
   2601 finally:
   2602     if dbname and current_db != dbname:

File d:\test\venv\lib\site-packages\sqlalchemy\dialects\mssql\base.py:3487, in MSDialect.get_foreign_keys(self, connection, tablename, dbname, owner, schema, **kw)
   3476     return {
   3477         "name": None,
   3478         "constrained_columns": [],
   (...)
   3482         "options": {},
   3483     }
   3485 fkeys = util.defaultdict(fkey_rec)
-> 3487 for r in connection.execute(s).fetchall():
   3488     (
   3489         _,  # constraint schema
   3490         rfknm,
   (...)
   3501         fkdelrule,
   3502     ) = r
   3504     rec = fkeys[rfknm]

File d:\test\venv\lib\site-packages\sqlalchemy\engine\base.py:1295, in Connection.execute(self, statement, *multiparams, **params)
   1291     util.raise_(
   1292         exc.ObjectNotExecutableError(statement), replace_context=err
   1293     )
   1294 else:
-> 1295     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)

File d:\test\venv\lib\site-packages\sqlalchemy\sql\elements.py:325, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    321 def _execute_on_connection(
    322     self, connection, multiparams, params, execution_options, _force=False
    323 ):
    324     if _force or self.supports_execution:
--> 325         return connection._execute_clauseelement(
    326             self, multiparams, params, execution_options
    327         )
    328     else:
    329         raise exc.ObjectNotExecutableError(self)

File d:\test\venv\lib\site-packages\sqlalchemy\engine\base.py:1487, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1475 compiled_cache = execution_options.get(
   1476     "compiled_cache", self.engine._compiled_cache
   1477 )
   1479 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1480     dialect=dialect,
   1481     compiled_cache=compiled_cache,
   (...)
   1485     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1486 )
-> 1487 ret = self._execute_context(
   1488     dialect,
   1489     dialect.execution_ctx_cls._init_compiled,
   1490     compiled_sql,
   1491     distilled_params,
   1492     execution_options,
   1493     compiled_sql,
   1494     distilled_params,
   1495     elem,
   1496     extracted_params,
   1497     cache_hit=cache_hit,
   1498 )
   1499 if has_events:
   1500     self.dispatch.after_execute(
   1501         self,
   1502         elem,
   (...)
   1506         ret,
   1507     )

File d:\test\venv\lib\site-packages\sqlalchemy\engine\base.py:1851, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1848             branched.close()
   1850 except BaseException as e:
-> 1851     self._handle_dbapi_exception(
   1852         e, statement, parameters, cursor, context
   1853     )
   1855 return result

File d:\test\venv\lib\site-packages\sqlalchemy\engine\base.py:2032, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2030     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2031 elif should_wrap:
-> 2032     util.raise_(
   2033         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2034     )
   2035 else:
   2036     util.raise_(exc_info[1], with_traceback=exc_info[2])

File d:\test\venv\lib\site-packages\sqlalchemy\util\compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File d:\test\venv\lib\site-packages\sqlalchemy\engine\base.py:1808, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1806                 break
   1807     if not evt_handled:
-> 1808         self.dialect.do_execute(
   1809             cursor, statement, parameters, context
   1810         )
   1812 if self._has_events or self.engine._has_events:
   1813     self.dispatch.after_cursor_execute(
   1814         self,
   1815         cursor,
   (...)
   1819         context.executemany,
   1820     )

File d:\test\venv\lib\site-packages\sqlalchemy\engine\default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

File src\pymssql\_pymssql.pyx:478, in pymssql._pymssql.Cursor.execute()

OperationalError: (pymssql._pymssql.OperationalError) (209, b"Ambiguous column name 'constraint_schema'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: WITH fk_info AS (
    SELECT
        ischema_ref_con.constraint_schema,
        ischema_ref_con.constraint_name,
        ischema_key_col.ordinal_position,
        ischema_key_col.table_schema,
        ischema_key_col.table_name,
        ischema_ref_con.unique_constraint_schema,
        ischema_ref_con.unique_constraint_name,
        ischema_ref_con.match_option,
        ischema_ref_con.update_rule,
        ischema_ref_con.delete_rule,
        ischema_key_col.column_name AS constrained_column
    FROM
        INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS ischema_ref_con
        INNER JOIN
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE ischema_key_col ON
            ischema_key_col.table_schema = ischema_ref_con.constraint_schema
            AND ischema_key_col.constraint_name =
            ischema_ref_con.constraint_name
    WHERE ischema_key_col.table_name = CAST(%(tablename)s AS NVARCHAR(max))
        AND ischema_key_col.table_schema = CAST(%(owner)s AS NVARCHAR(max))
),
constraint_info AS (
    SELECT
        ischema_key_col.constraint_schema,
        ischema_key_col.constraint_name,
        ischema_key_col.ordinal_position,
        ischema_key_col.table_schema,
        ischema_key_col.table_name,
        ischema_key_col.column_name
    FROM
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE ischema_key_col
),
index_info AS (
    SELECT
        sys.schemas.name AS index_schema,
        sys.indexes.name AS index_name,
        sys.index_columns.key_ordinal AS ordinal_position,
        sys.schemas.name AS table_schema,
        sys.objects.name AS table_name,
        sys.columns.name AS column_name
    FROM
        sys.indexes
        INNER JOIN
        sys.objects ON
            sys.objects.object_id = sys.indexes.object_id
        INNER JOIN
        sys.schemas ON
            sys.schemas.schema_id = sys.objects.schema_id
        INNER JOIN
        sys.index_columns ON
            sys.index_columns.object_id = sys.objects.object_id
            AND sys.index_columns.index_id = sys.indexes.index_id
        INNER JOIN
        sys.columns ON
            sys.columns.object_id = sys.indexes.object_id
            AND sys.columns.column_id = sys.index_columns.column_id
)
    SELECT
        fk_info.constraint_schema,
        fk_info.constraint_name,
        fk_info.ordinal_position,
        fk_info.constrained_column,
        constraint_info.table_schema AS referred_table_schema,
        constraint_info.table_name AS referred_table_name,
        constraint_info.column_name AS referred_column,
        fk_info.match_option,
        fk_info.update_rule,
        fk_info.delete_rule
    FROM
        fk_info INNER JOIN constraint_info ON
            constraint_info.constraint_schema =
                fk_info.unique_constraint_schema
            AND constraint_info.constraint_name =
                fk_info.unique_constraint_name
            AND constraint_info.ordinal_position = fk_info.ordinal_position
    UNION
    SELECT
        fk_info.constraint_schema,
        fk_info.constraint_name,
        fk_info.ordinal_position,
        fk_info.constrained_column,
        index_info.table_schema AS referred_table_schema,
        index_info.table_name AS referred_table_name,
        index_info.column_name AS referred_column,
        fk_info.match_option,
        fk_info.update_rule,
        fk_info.delete_rule
    FROM
        fk_info INNER JOIN index_info ON
            index_info.index_schema = fk_info.unique_constraint_schema
            AND index_info.index_name = fk_info.unique_constraint_name
            AND index_info.ordinal_position = fk_info.ordinal_position

    ORDER BY constraint_schema, constraint_name, ordinal_position
]
[parameters: {'tablename': 'user', 'owner': 'dbo'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
### Versions

- OS: Windows 10
- Python: 3.8.12
- SQLAlchemy: 1.4.32
- Database: 
        Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 
	Apr  2 2010 15:48:46 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymssql

### Additional context

Moreover, I tried to modify the code on line 3453 (sqlalchemy\dialects\mssql\base.py),

from  `ORDER BY constraint_schema, constraint_name, ordinal_position`,

to  `ORDER BY fk_info.constraint_schema, fk_info.constraint_name, fk_info.ordinal_position`.

It seems to be working properly. It seems that the mistake is caused by it.

If there is anything wrong, please let me know.

**Comment by CaselIT** [comment] 2022-03-11 14:01
Hi,

thanks for reporting. @gordthompson it seems that's the updated query to obtain additional info for the fk?

**Comment by zzzeek** [comment] 2022-03-11 16:34
lets make sure we get this in ASAP.   Also if we can confirm this is only on older SQL server , I guess we have a conditional that picks a different query for older version ?

**Comment by gordthompson** [comment] 2022-03-11 17:59
I am unable to reproduce the issue. I don't have a copy of SQL Server 2008 R2, only SQL Server 2008 "classic", i.e.,

```
Microsoft SQL Server 2008 (RTM) - 10.0.1600.22 (Intel X86) 
	Jul  9 2008 14:43:34 
	Copyright (c) 1988-2008 Microsoft Corporation
	Express Edition on Windows NT 5.1 <X86> (Build 2600: Service Pack 3)
```

My normal test backend is

```
Microsoft SQL Server 2019 (RTM-CU3) (KB4538853) - 15.0.4023.6 (X64) 
	Mar  4 2020 00:59:26 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.4 LTS) <X64>
```

This code runs fine on both:

```python
import sqlalchemy as sa

connection_url = (
    "mssql+pyodbc://scott:tiger^5HHH@192.168.0.198/test"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
engine = sa.create_engine(
    connection_url,
    echo=True,
)

tbl = sa.Table("user", sa.MetaData(), autoload_with=engine)
```

If I use

```python
connection_url = "mssql+pymssql://scott:tiger^5HHH@192.168.0.198/test"
```

then it works fine with SQL Server 2019 but hangs while trying to connect to SQL Server 2008.

> I guess we have a conditional that picks a different query for older version ?

Not at the moment. The same CTE-based query is used in all cases.

If @Lin-Your says that the ORDER BY patch fixes their issue then we could apply it and run it through CI to ensure that it doesn't break non-ancient versions of SQL Server using pyodbc. (CI does not test pymssql, however.)

**Comment by Lin-Your** [comment] 2022-03-11 19:30
Actually, my test backend is also sql server 2019. It works well.

But today, when I was running my code, it made an error.

I tried to execute that query directly in cli and failed.

But, when I delete the ORDER BY, it works as expected.

So I guess it may not work on some older versions.

**Comment by gordthompson** [comment] 2022-03-11 19:45
> But today, when I was running my code, it made an error.

By "my code" you mean the modified version with the `fk_info.` prefixes in the ORDER BY clause?

**Comment by Lin-Your** [comment] 2022-03-11 20:16
Oh, sorry, there may be something wrong with my expression.

The "my code" refers to the script I wrote. It will load the table information and save the table creation statement.

It used to work, but today I was surprised to find that it didn't work.

So I tried to find the location of the problem according to the error message and tried to fix it.

For me, adding the `fk_info.` prefixes is ​​just an attempt.

**Comment by zzzeek** [comment] 2022-03-11 21:13
it's a strange error because the column should not be ambiguous.   are you using freetds ?  i wonder if this is related to the "tds version" you have in your file?

**Comment by gordthompson** [comment] 2022-03-11 22:28
@zzzeek - Yes, pymssql is built on top of FreeTDS.

**Comment by zzzeek** [comment] 2022-03-11 22:32
I was asking @Lin-Your  what TDS version they are using.

**Comment by gordthompson** [comment] 2022-03-11 22:44
If the current version of pymssql is linked to a reasonably current version of FreeTDS then the default TDS protocol version should be "auto". Earlier versions of FreeTDS set the default protocol version (e.g., 4.2) at build time.

However, the *requested* protocol version and the *actual* protocol version are not always the same. They could find out the actual protocol version by hacking

https://github.com/gordthompson/check_tds_protocol_version

to use pymssql instead of pyodbc. (I'd try it myself, but as I said I cannot get pymssql to connect to my instance of SQL Server 2008.)

**Comment by gordthompson** [comment] 2022-03-12 01:58
Unfortunately, we're still talking about really old versions of things. I don't have `ODBC+Driver+13+for+SQL+Server` but the following works for me with my SQL Server 2008 SP1 instance:

```python
import sqlalchemy as sa

connection_url = (
    "mssql+pyodbc://scott:tiger^5HHH@192.168.0.198/test"
    "?driver=SQL+Server+Native+Client+11.0"
)
engine = sa.create_engine(
    connection_url,
    echo=True,
)

tbl = sa.Table("user", sa.MetaData(), autoload_with=engine)
```

And yes, it's still invoking the same CTE-based query for the reflection.

**Comment by gordthompson** [comment] 2022-03-12 17:03
I installed SQL Server 2008 Express SP1 on a different VM (Windows 7 instead of Windows XP), i.e., 

```
Microsoft SQL Server 2008 (SP1) - 10.0.2531.0 (X64) 
	Mar 29 2009 10:11:52 
	Copyright (c) 1988-2008 Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

and now my test code [above](https://github.com/sqlalchemy/sqlalchemy/issues/7812#issuecomment-1065351177) runs successfully for all three scenarios:

```python
connection_url = (
    "mssql+pyodbc://scott:tiger^5HHH@192.168.0.100/test"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

connection_url = "mssql+pymssql://scott:tiger^5HHH@192.168.0.100/test"

connection_url = (
    "mssql+pyodbc://scott:tiger^5HHH@192.168.0.100/test"
    "?driver=SQL+Server+Native+Client+11.0"
)
```

pymssql version is 2.2.4

**Comment by gordthompson** [comment] 2022-03-12 23:13
For the record, pymssql 2.2.4 connecting to SQL Server 2008 Express SP1 results in

```
Actual TDS protocol version in use: 7.3
```

using the following hack of check_tds_protocol_version.py

```python
import pymssql

"""check_tds_protocol_version

Queries the SQL Server to determine the actual TDS protocol version in use.
"""


def tds_version(cnxn):
    """
    Get the TDS protocol version from the SQL Server system view.

    :param cnxn: a currently open Connection
    :return: the active TDS protocol version as string
    """
    protocol_versions = {
        67239936: '4.2',  # b'\x04\x02\x00\x00'
        117440512: '7.0',  # b'\x07\x00\x00\x00'
        1895825409: '7.1',  # b'q\x00\x00\x01'
        1913192450: '7.2',  # b'r\t\x00\x02'
        1930100739: '7.3',  # b's\x0b\x00\x03'
        1946157060: '7.4',  # b't\x00\x00\x04'
    }
    sql = "SELECT protocol_version FROM sys.dm_exec_connections WHERE session_id=@@SPID"
    crsr = cnxn.cursor()
    crsr.execute(sql)
    result = crsr.fetchone()[0]
    return protocol_versions.get(result, 'unknown ({})'.format(result))


if __name__ == '__main__':
    cnxn = pymssql.connect(
        server="192.168.0.100",
        user="scott",
        password="tiger^5HHH",
        database="test",
    )
    print('Actual TDS protocol version in use: {}'.format(tds_version(cnxn)))
    cnxn.close()
```

**Comment by Lin-Your** [comment] 2022-03-12 23:49
I installed SQL Server 2008 on my operation system (Windows 10), i.e.,
```
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 
	Apr  2 2010 15:48:46 
	Copyright (c) Microsoft Corporation
	Express Edition with Advanced Services (64-bit) on Windows NT 6.2 <X64> (Build 9200: )
```
But, I can't reproduce this error too.

The difference may be that one is "Standard Edition" and the other is "Express Edition" ( or something i don't know ).

So I'm trying to download an identical version to reproduce it.

**Comment by Lin-Your** [comment] 2022-03-13 03:15
Ok, I installed SQL Server 2008 R2 (RTM) on a VM ( Windows 7 6.1.7601 Service Pack 1 Build 7601).
```
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)
Apr 2 2010 15:48:46
Copyright (c) Microsoft Corporation
Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor) 
```
However, I still can't reproduce this mistake.
Maybe I should try the database I used on friday again tomorrow.

**Comment by Lin-Your** [comment] 2022-03-14 01:39
Well, maybe I know why we can't reproduce it.
I carefully checked the settings of the database with this problem.
And I found the "Compatibility Level" was 80 instead of 100.

Here is the same question.
https://stackoverflow.com/questions/2788342/ambiguous-column-name-error-on-one-particular-server

**Comment by zzzeek** [comment] 2022-03-14 01:56
OK! that's amazing!  we can act on this.  we can check that access level at dialect init and warn on it.  what say ye @gordthompson  ?

**Comment by sqla-tester** [comment] 2022-03-14 17:27
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Fix "Ambiguous column name" error on FK reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3704

**Comment by sqla-tester** [comment] 2022-03-14 20:05
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix "Ambiguous column name" error on FK reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3707

**Closed** 2022-03-17 18:21 UTC
Labels: bug, SQL Server, reflection, regression
