### ISSUE TITLE
engine.url comparison broken

### ISSUE THREAD

**Issue by mgdelmonte** [sqlalchemy/sqlalchemy#4406] opened 2018-12-11 18:32 UTC
Comparing two engines yields inconsistent and unusable results.  Easy test case, on v1.2.8 through v1.2.14, in Python2:

```
>>> import sqlalchemy
>>> a = sqlalchemy.create_engine("postgresql://localhost:5432")
>>> b = sqlalchemy.create_engine("postgresql://localhost:5432")
>>> a.engine.url == b.engine.url
True
>>> a.engine.url != b.engine.url
True

>>> c = sqlalchemy.create_engine("postgresql://localhost:5433")
>>> a.engine.url == c.engine.url
True
>>> a.engine.url != c.engine.url
True
```

**Comment by zzzeek** [comment] 2018-12-11 21:55
it's only `!=` that is missing:

```
diff --git a/lib/sqlalchemy/engine/url.py b/lib/sqlalchemy/engine/url.py
index 1662efe209..69bc222801 100644
--- a/lib/sqlalchemy/engine/url.py
+++ b/lib/sqlalchemy/engine/url.py
@@ -110,6 +110,9 @@ class URL(object):
             self.database == other.database and \
             self.query == other.query
 
+    def __ne__(self, other):
+        return not self.__eq__(other)
+
     @property
     def password(self):
         if self.password_original is None:

```

fix here needs to include a test in `test/engine/test_parseconnect.py`

**Comment by huntcsg** [comment] 2018-12-22 15:45
@zzzeek I was going to take a stab at this. 

The cause of this issue is not the lack of  `__ne__` (as the `object` implementation does what you described above).

The cause is that `port` is not contained in the comparisons made in `sqlalchemy.engine.url.URL.__eq__`.

I can add it (and some relevant tests), but since the cause was different than originally suggested I wanted to make sure you would accept such a PR.

Would you also want a PR to backport a deprecation warning if users are calling `__eq__` on two urls that differ in `port` and would now end up being not equal?

**Comment by zzzeek** [comment] 2018-12-22 17:42
@huntcsg OK the lack of port comparison is another issue then, because the first two URLs compared above have the same port number but `!=` still fails, can you confirm I'm not reading that wrong?  I tried it out to verify as well.    Can you PR both fixes at once?

**Comment by sqla-tester** [comment] 2019-01-25 16:20
**Daniel Lister** has proposed a fix for this issue in the **master** branch:

**Add getters for all execution_options** https://gerrit.sqlalchemy.org/1112

**Comment by zzzeek** [comment] 2019-02-03 17:47
ugh this was closed by accident, incorrect issue number

**Comment by sqla-tester** [comment] 2019-02-28 15:16
**Sanjana** has proposed a fix for this issue in the **master** branch:

**Fixes: #4406 Added port comparison in __eq__() and __ne__() method to…** https://gerrit.sqlalchemy.org/1145

**Comment by sqla-tester** [comment] 2019-02-28 19:35
**Sanjana** has proposed a fix for this issue in the **master** branch:

**Add port comparison in __eq__() and __ne__() method to URL** https://gerrit.sqlalchemy.org/1145

**Comment by sqla-tester** [comment] 2019-02-28 19:35
**Sanjana** has proposed a fix for this issue in the **rel_1_2** branch:

**Add port comparison in __eq__() and __ne__() method to URL** https://gerrit.sqlalchemy.org/1147

**Closed** 2019-03-04 15:46 UTC
Labels: bug, easy, engine
