### ISSUE TITLE
The password and server are interpreted wrongly when password contains @

### ISSUE THREAD

**Issue by lijun-hanson** [sqlalchemy/sqlalchemy#6688] opened 2021-06-29 01:49 UTC
**Describe the bug**
Use MSSQL, the password contains @, the error shows `Failed to execute migrations to revision 12685bc9edf4. (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')` when using sqlalchemy; while the connection is successful by using sql client.

**To Reproduce**
Configure password contains @

**Error**
After checked recent commits, the issue should be introduced by this commit: https://github.com/sqlalchemy/sqlalchemy/commit/2ab67552a097522a82fd250b8b36995a9bc2cd80#diff-f54587482b075b6a76ecbf10620b5183d65f9449639606d8fa88a103d88a95b6L705-R705

```
# Log output.
Failed to execute migrations to revision 12685bc9edf4. (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
```

**Versions.**
 - OS: ubuntu 20.04
 - Python: 3.7.4
 - SQLAlchemy: 1.4.18
 - Database: MSSQL
 - DBAPI: pyodbc

**Additional context**
E.g. use password Abcdef1@, the server parameter is @<host>, while password is Abcdef1

**Have a nice day!**

**Comment by CaselIT** [comment] 2021-06-29 07:32
Hi,

This is a duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/6574, https://github.com/sqlalchemy/sqlalchemy/issues/6567, https://github.com/sqlalchemy/sqlalchemy/discussions/6568

This is the expected behaviour. See https://github.com/sqlalchemy/sqlalchemy/discussions/6568#discussioncomment-811863

**Closed by CaselIT** 2021-06-29 07:32 UTC
Labels: requires triage
