### ISSUE TITLE
new selectinload does not tolerate failing primary join conditions

### ISSUE THREAD

**Issue by ljos** [sqlalchemy/sqlalchemy#4777] opened 2019-07-23 11:54 UTC
If a foreign key column contains an empty string and there are no corresponding empty string key in the other tables primary key column, sqlalchemy fails with the confusing error `KeyError: ('missing_key',)`:

```
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    list(session.query(Bar))
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 93, in instances
    post_load.invoke(context, path)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 877, in invoke
    loader(context, path, states, self.load_keys, *arg, **kw)
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 2361, in _load_for_path
    self._load_via_child(our_states, query_info, q, context)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 2384, in _load_via_child
    related_obj = data[key]
KeyError: ('missing_key',)
```

The following python code demonstrates the error:
```python
from sqlalchemy import Column, String, create_engine, ForeignKey
from sqlalchemy.orm import sessionmaker, relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Foo(Base):
    __tablename__ = "Foo"
    foo_id = Column(String(), primary_key=True)


class Bar(Base):
    __tablename__ = "Bar"

    bar_id = Column(String, primary_key=True)
    foo_id = Column(ForeignKey(Foo.foo_id))
    foo = relationship(Foo, lazy="selectin", uselist=False)


engine = create_engine("sqlite://")
Session = sessionmaker(bind=engine)

if __name__ == "__main__":
    engine.execute('CREATE TABLE Bar (bar_id VARCHAR, foo_id VARCHAR, PRIMARY KEY (bar_id));')
    engine.execute('CREATE TABLE Foo (foo_id VARCHAR, PRIMARY KEY (foo_id));')
    engine.execute('INSERT INTO Foo (foo_id) VALUES ("one"), ("two");')
    engine.execute('INSERT INTO Bar (bar_id, foo_id) VALUES ("1", "one"), ("2", "missing_key");')

    session = Session()
    list(session.query(Bar))
```

**Comment by zzzeek** [comment] 2019-07-23 13:04
this is a regression new in 1.3.6 caused by #4775.  please downgrade to 1.3.5 if this issue is problematic for now.

**Comment by zzzeek** [comment] 2019-07-23 13:06
oh you can also force the old logic like this:

```
class Bar(Base):
    __tablename__ = "Bar"

    bar_id = Column(String, primary_key=True)
    foo_id = Column(ForeignKey(Foo.foo_id))
    foo = relationship(Foo, lazy="selectin", uselist=False, omit_join=False)

```

**Comment by ljos** [comment] 2019-07-23 13:15
I also found that chaging the line at "/sqlalchemy/orm/strategies.py", line 2384, in `_load_via_child` to:
```
    related_obj = data.get(key, None)
```
fixed the problem as well. I just couldn't figure out how to write a test for it.

**Comment by sqla-tester** [comment] 2019-07-23 13:25
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't assume m2o key is present in the dictionary** https://gerrit.sqlalchemy.org/1373

**Comment by sqla-tester** [comment] 2019-07-23 13:26
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Don't assume m2o key is present in the dictionary** https://gerrit.sqlalchemy.org/1374

**Closed** 2019-07-23 22:02 UTC
Labels: loader options, orm, regression
