### ISSUE TITLE
new m2o relationship compare logic needs to allow for persistent NULL that was implicitly inserted

### ISSUE THREAD

**Issue by maparent** [sqlalchemy/sqlalchemy#4676] opened 2019-05-12 18:07 UTC
Good day!
Here is an simplified version of my model:
```python
class A(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)
    deleted_when = Column(DateTime, server_default=None, default=None)

class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(Integer, ForeignKey(A.id))
    a = relationship(
        A,
        primaryjoin="and_(A.id==B.a_id, "
                    "A.deleted_when == None)")
```
and here is a snippet of code:
```python
a = A()
# OR take an existing a=db.query(A).first() with empty deleted_when
db.query(B).filter_by(a=a).all()
```
This worked fine in 1.2.x, but now crashes in 1.3.3
Basically I'm running in this exception:
https://github.com/sqlalchemy/sqlalchemy/blob/b26642e2364836fe9a8ee25c1cf4551901ce0c37/lib/sqlalchemy/orm/relationships.py#L1584

I think that, when the column has a default or server_default, that value should be returned instead of `NEVER_SET`.

**Comment by zzzeek** [comment] 2019-05-13 17:00
hey there, and thanks for the clear issue report.

There's a lot to say on this as there are many different behaviors intersecting here.

Regarding the column defaults, those are not consulted by the ORM, so whether or not you apply a column default, the value of the deleted_when attribute at the Python level will return None until the object is persisted.   This None is not part of the object's state, however, and in fact the whole idea of "None" magically appearing will be going away in SQLAlchemy 2 and it will instead raise an AttributeError like normal Python does, that's #4519.   The column-level defaults are part of the object's persistent state, so if the object you have is not persistent, as is the case here where the object is transient, you should not expect the persistence defaults to be present.   (see [here](https://docs.sqlalchemy.org/en/13/orm/session_state_management.html#quickie-intro-to-object-states) for these terms).

if you do want to explicitly set column level defaults  when you instantiate an object, there's an example that illustrates how to use the attribute-level default behavior event to do this [here](https://docs.sqlalchemy.org/en/13/_modules/examples/custom_attributes/active_column_defaults.html).       so for the thing you said "should" happen, you can use this recipe.

I also noticed you have a funny situation going on with that comparison, where you will get the warning:

```

/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/relationships.py:1504: SAWarning: Got None for value of column a.deleted_when; this is unsupported for a relationship comparison and will not currently produce an IS comparison (but may in a future release)
  "(but may in a future release)" % column

```

normally this would emit broken SQL but because your "deleted_when" comparison is already against None, it already generated the "IS".   So this warning is not affecting you, and this situation is a little odd and it would be nice if that warning wasn't happening here, but I don't have any immediate solution for that. 

So finally to the inconsistency that at the attribute level, the transient object returns None but then used in a comparison it raises.  This is the change documented at https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#improvement-to-the-behavior-of-many-to-one-query-expressions, the spirit of which was to better handle comparisons to objects in the detached state.     The change to make this "work" looks like:

```
diff --git a/lib/sqlalchemy/orm/relationships.py b/lib/sqlalchemy/orm/relationships.py
index 008cfcd2a8..59d2289ce2 100644
--- a/lib/sqlalchemy/orm/relationships.py
+++ b/lib/sqlalchemy/orm/relationships.py
@@ -1576,7 +1576,8 @@ class RelationshipProperty(StrategizedProperty):
                 column,
                 passive=attributes.PASSIVE_RETURN_NEVER_SET
                 if state.persistent
-                else attributes.PASSIVE_NO_FETCH ^ attributes.INIT_OK,
+                else attributes.PASSIVE_NO_FETCH ^ attributes.INIT_OK
+                if state.detached else attributes.PASSIVE_OFF
             )
 
             if current_value is attributes.NEVER_SET:

```
that is, if the object is transient, don't do anything special, just make it behave like it does when accessed directly.     However, this basically means the whole ambiguous use case I added here no longer applies, and I'm not ready to do that.      The "None" that you get when you say "a_object.deleted_when" is essentially a (soon to be deprecated) convenience that saves you having to catch an AttributeError, and I think re-applying this "None" as meaningful is not the right direction to go.    Especially given that you've been assuming this is the column-level default generator you're seeing.  It means if your default generator returned a non-None value, and then a transient object were used in the comparison, it would again do the wrong thing.  

so three takeaways:

1. the column level defaults don't apply to transient objects unless you add events to do that

2. the change in question is so that the ORM isn't making possibly broken assumptions about objects

3. the longer term plan is to make even fewer assumptions about un-set attributes

My main suggestion would be to not be using transient objects in comparisons like this, in fact, because semantically they don't make sense.  ORM instances are not value objects, they are proxies for a database row, so the transient object doesn't actually have meaning when used in a database context.

**Comment by maparent** [comment] 2019-05-13 17:04
Good day! Thank you for the detailed answer, which I will study further, but for the record, I'm quite sure this has also happened to me with a non-transient object. (I will recheck that...)

**Comment by maparent** [comment] 2019-05-13 17:46
Sorry for the last comment, it seems I was wrong about this.

**Comment by maparent** [comment] 2019-05-13 17:54
Ah! It's really a corner case; the object was flushed, but not committed. Your explanations helped, and I'm willing to work around it, but I think the case can be made that flushed objects should have the server_default value.

**Comment by zzzeek** [comment] 2019-05-13 18:01
flushed objects definitely do have a value for the attribute, and the only failure case is if the attribute has not been refreshed from the DB and you're trying to run the expression while the object is detached.    There are strategies to handle that case as well, e.g. expire_on_commit=False and eager_defaults=True so that they are loaded up front.   Do you have a stack trace and /or reproduction case?

**Comment by maparent** [comment] 2019-05-13 18:08
The reproduction case with my pseudo-case above would be
```python
a = A()
db.add(a)
db.flush()
db.query(B).filter_by(a=a).first()
```
I did almost exactly that to obtain this stack trace. (real class names: `A` is `Idea`, `B` is `IdeaLink`, `deleted_when` is `tombstone_date`.)
I tried adding `eager_defaults=True, expire_on_commit=False` to the tombstone_date column definition, to no avail.

```python

In [9]: db.query(models.IdeaLink).filter_by(source=i).first()
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
~/OpenSource/VirtualPythons/idealoom/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1178
-> 1179             context = constructor(dialect, self, conn, *args)
   1180         except BaseException as e:

~/OpenSource/VirtualPythons/idealoom/lib/python3.6/site-packages/sqlalchemy/engine/default.py in _init_compiled(cls, dialect, connection, dbapi_connection, compiled, parameters)
    682                 compiled.construct_params(m, _group_number=grp)
--> 683                 for grp, m in enumerate(parameters)
    684             ]

~/OpenSource/VirtualPythons/idealoom/lib/python3.6/site-packages/sqlalchemy/engine/default.py in <listcomp>(.0)
    682                 compiled.construct_params(m, _group_number=grp)
--> 683                 for grp, m in enumerate(parameters)
    684             ]

~/OpenSource/VirtualPythons/idealoom/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py in construct_params(self, params, _group_number, _check)
    691                 if bindparam.callable:
--> 692                     pd[self.bind_names[bindparam]] = bindparam.effective_value
    693                 else:

~/OpenSource/VirtualPythons/idealoom/lib/python3.6/site-packages/sqlalchemy/sql/elements.py in effective_value(self)
   1212         if self.callable:
-> 1213             return self.callable()
   1214         else:

~/OpenSource/VirtualPythons/idealoom/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py in _go()
   1586                         "%s; no value has been set for this column"
-> 1587                         % (column, state_str(state))
   1588                     )

InvalidRequestError: Can't resolve value for column idea.tombstone_date on object <Idea at 0x117e1c9e8>; no value has been set for this column
```

**Comment by maparent** [comment] 2019-05-13 18:18
P.S. my `tombstone_date` column comes from a mixin class, in case that matters... though I don't see how.

**Comment by zzzeek** [comment] 2019-05-13 18:28
OK, just realized,  "server_default=None" means you didn't set a default, so none of the default-fetching logic works as long as it's like that.   So the attribute is not marked as expired and it just remains not set to anything, and apparently...this is how it's always worked.   it's just the new logic again doesn't want to assume for that None.    so this does seem more wrong.   but also I'm just surprised that the NULL that's in a column like this has always just been assumed.    

In any case, you can make this default active just like this:

```
class A(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)
    deleted_when = Column(DateTime,  server_default=FetchedValue())

```

let me see if I can add test cases to add for this

**Comment by maparent** [comment] 2019-05-13 18:33
Ah! that does the trick. Thank you very much!

**Comment by sqla-tester** [comment] 2019-05-13 19:17
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Continue to assume None for un-accessed attribute on persistent** https://gerrit.sqlalchemy.org/1265

**Comment by sqla-tester** [comment] 2019-05-13 19:17
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Continue to assume None for un-accessed attribute on persistent** https://gerrit.sqlalchemy.org/1266

**Closed** 2019-05-14 14:49 UTC
Labels: orm, question, regression

**Comment by maparent** [comment] 2019-05-14 14:55
Thank you very much!
