### ISSUE TITLE
determine if we can restore cx_Oracle.DATETIME for date parameters in setinputsizes

### ISSUE THREAD

**Issue by orutherfurd** [sqlalchemy/sqlalchemy#4886] opened 2019-10-03 15:05 UTC
We have a query that's running fine on 1.1.14 and while trying to upgrade to 1.3.8, found it's breaking with the oracle type system overhaul done for 1.2.0b3. Below is the error and attached is a file used to produce the error below.  The code includes two custom functions (month and add_months) with implementations for both oracle and sqlite, but have only included the oracle bits.

[error_script.txt](https://github.com/sqlalchemy/sqlalchemy/files/3686730/error_script.txt)

> sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00932: inconsistent datatypes: expected DATE got CHAR [SQL: "SELECT spend_track.track_id AS spend_track_track_id, spend_track.campaign_id AS spend_track_campaign_id, spend_track.start_date AS spend_track_start_date, spend_track.end_date AS spend_track_end_date, spend_track.through_date AS spend_track_through_date
> FROM spend_track
> WHERE :param_1 = spend_track.campaign_id AND CASE WHEN (:param_2 != :type_1) THEN CASE WHEN (CASE WHEN (:param_3 IS NOT NULL) THEN (SELECT bill.invoice_date
> FROM bill
> WHERE bill.bill_id = :param_3) ELSE :param_4 END IS NOT NULL) THEN TRUNC(CASE WHEN (:param_3 IS NOT NULL) THEN (SELECT bill.invoice_date
> FROM bill
> WHERE bill.bill_id = :param_3) ELSE :param_4 END, 'MONTH') ELSE TRUNC(ADD_MONTHS(:param_5, (SELECT division.bill_month_offset
> FROM division, insertion_order, campaign
> WHERE division.division_id = insertion_order.division_id AND insertion_order.order_id = campaign.order_id AND campaign.campaign_id = :param_1)), 'MONTH') END ELSE TRUNC(:param_5, 'MONTH') END = TRUNC(spend_track.through_date, 'MONTH') AND :param_2 = :type_2 ORDER BY spend_track.through_date"] [parameters: {'param_1': 16807, 'param_2': 'D', 'type_1': 'D', 'param_3': None, 'param_4': None, 'param_5': datetime.date(2019, 10, 7), 'type_2': 'D'}]

**Comment by zzzeek** [comment] 2019-10-03 15:58
hi there -

can you please produce an [MCVE](http://stackoverflow.com/help/mcve) that reproduces the error?    The script you have attached is not only very long and complicated but I also cannot run it because I do not have access to your "import settings" environment nor does your script create any data to be tested.

**Comment by zzzeek** [comment] 2019-10-03 16:00
If I put a database URL in and run your script I get:
```

Traceback (most recent call last):
  File "test3.py", line 230, in <module>
    spend.tracks  # boom
AttributeError: 'NoneType' object has no attribute 'tracks'

```

because there's no data.

**Comment by zzzeek** [comment] 2019-10-03 16:08
Here's a script that makes use of both of your functions within a CASE statement, trying to mimic the general form you have above.    As it reproduces no error, have you also ensured you are on the most recent cx_Oracle version?     Newer SQLAlchemy versions require more recent cx_Oracle versions.

```
import datetime

from sqlalchemy import case
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Date
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.sql import expression


class add_months(expression.FunctionElement):
    """function to add `n` months to a date.

    Implemented for oracle and sqlite.
    """

    type = Date()
    name = "add_months"


@compiles(add_months)
def add_months_default(element, compiler, **kw):
    return compiler.visit_function(element)


@compiles(add_months, "oracle")
def add_months_oracle(element, compiler, **kw):
    # oracle implementation of "add_months"
    (date, number) = list(element.clauses)
    return "ADD_MONTHS(%s, %s)" % (
        compiler.process(date),
        compiler.process(number),
    )


class month(expression.FunctionElement):
    """function returns first of month of given date.

    Implemented for oracle and sqlite.
    """

    type = Date()
    name = "month"


@compiles(month)
def month_default(element, compiler, **kw):
    return compiler.visit_function(element)


@compiles(month, "oracle")
def month_oracle(element, compiler, **kw):
    # oracle implementation of `month`
    (arg,) = list(element.clauses)
    return "TRUNC(%s, 'MONTH')" % (compiler.process(arg),)


Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    date = Column(DateTime)


e = create_engine("oracle://scott:tiger@oracle1120", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(id=1, date=datetime.datetime(2019, 10, 5, 12, 47, 18)))
s.commit()

print(s.query(month(case([(A.id == 1, add_months(A.date, 3))]))).all())

```

output:

```
BEGIN (implicit)
2019-10-03 12:06:42,198 INFO sqlalchemy.engine.base.Engine INSERT INTO a (id, "date") VALUES (:id, :"date")
2019-10-03 12:06:42,198 INFO sqlalchemy.engine.base.Engine {'id': 1, '"date"': datetime.datetime(2019, 10, 5, 12, 47, 18)}
2019-10-03 12:06:42,209 INFO sqlalchemy.engine.base.Engine COMMIT
2019-10-03 12:06:42,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-10-03 12:06:42,224 INFO sqlalchemy.engine.base.Engine SELECT TRUNC(CASE WHEN (a.id = :id_1) THEN ADD_MONTHS(a."date", :add_months_1) END, 'MONTH') AS month_1 
FROM a
2019-10-03 12:06:42,224 INFO sqlalchemy.engine.base.Engine {'id_1': 1, 'add_months_1': 3}
[(datetime.date(2020, 1, 1),)]

```

**Comment by orutherfurd** [comment] 2019-10-03 17:24
Hi, sorry the example script wasn't runnable.  I've attached a version that can be run and demonstrates the issue.  We got the error with SQLAlchemy 1.3.8 and cx_Oracle 7.2.3 and did some bisecting to figure out that 1.2.0b3 is where it stopped working. Simpler examples of using the functions haven't been an issue, so we extracted this bit from our app.

[error_script2.txt](https://github.com/sqlalchemy/sqlalchemy/files/3687302/error_script2.txt)

**Comment by zzzeek** [comment] 2019-10-03 18:04
ok this is just the DATETIME inputsize, see the docs at https://docs.sqlalchemy.org/en/13/dialects/oracle.html#fine-grained-control-over-cx-oracle-data-binding-performance-with-setinputsizes where to make your app work for now, we will do this:
```

    engine = create_engine(dburi, echo=True)


    @event.listens_for(engine, "do_setinputsizes")
    def _add_datetime(inputsizes, cursor, statement, parameters, context):
        for bindparam in inputsizes:
            if isinstance(bindparam.type, Date):
                inputsizes[bindparam] = cx_Oracle.DATETIME

```

newer cx_Oracle also lets you put a Python type in there, which might be better, I'll see if I can check with them:

```
    @event.listens_for(engine, "do_setinputsizes")
    def _add_datetime(inputsizes, cursor, statement, parameters, context):
        for bindparam in inputsizes:
            if isinstance(bindparam.type, Date):
                inputsizes[bindparam] = datetime.date

```

I'll have to run the tests to see why DATETIME was not part of the included types.

**Comment by sqla-tester** [comment] 2019-10-03 18:10
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**call setinputsizes for cx_Oracle.DATETIME** https://gerrit.sqlalchemy.org/1494

**Comment by zzzeek** [comment] 2019-10-03 18:47
so the problem you're having has to do with an issue in lazy loading ( I can't find the issue) which is that your comparison is against "None", which is being passed in as a bound parameter and that's why oracle is confused.  this is nothing that can be fixed for the moment but that's what's unusual about this case.

**Comment by sqla-tester** [comment] 2019-10-03 19:03
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**call setinputsizes for cx_Oracle.DATETIME** https://gerrit.sqlalchemy.org/1495

**Comment by orutherfurd** [comment] 2019-10-03 19:37
Thank you, am using your fix from above and will keep an eye on the repos.

**Closed** 2019-10-03 21:41 UTC
Labels: bug, oracle
