### ISSUE TITLE
Improve loader documentation to better clarify which are "eager" and with are "lazy"

### ISSUE THREAD

**Issue by Omnia6975** [sqlalchemy/sqlalchemy#6156] opened 2021-03-30 09:47 UTC
**Describe the bug**
If I set-up a relationship with the lazy='noload' property then doing a basic query, the relationship will not be listed in the sqlalchemy.orm.InstanceState.unloaded property of the query result. 

By doing the same request and replacing the lazy='noload' property by the default one lazy='select' then this relationship is listed in sqlalchemy.orm.InstanceState.unloaded query result.

**Expected behavior**
For me, when it is set up as a 'noload' loading technique relationship it should be listed in sqlalchemy.orm.InstanceState.unloaded as well. It is particularly annoying while playing with different loading techniques (at query level only) across a whole project.

**To Reproduce**
```
class User(Base):
    id= Column(INTEGER(10), primary_key=True)
    symbols = relationship('Symbol', lazy="noload")
```

Then doing a basic query to retrieve the unload properties: 
```
query_res= self.session.query(User).all()
unload_list= object_state(query_res[0]).unloaded
```
The 'symbols' relationship won't be added in the unload_list list as I think it should.

**Versions.**
 - OS: Windows 10 64bits
 - Python: 3.8.7
 - SQLAlchemy: 1.4.3
 - Database: SQL
 - DBAPI: mysql

**Comment by CaselIT** [comment] 2021-03-30 10:29
Hi,

This is also in 1.3, so it's not a regression. 
@zzzeek is there a way to know from the instance state how a particular relationship/field was loaded?

**Comment by zzzeek** [comment] 2021-03-30 13:10
the way we do these things is:

1. move .unloaded to ._unloaded, the ORM uses that
2. build an all new .unloaded property that does something entirely user specific, ORM no longer cares about it
3. add a test


but i need rationale

**Comment by CaselIT** [comment] 2021-03-30 13:12
On gitter the op mentioned that it used it while serializing the object, to avoid loading unloaded fields

**Comment by zzzeek** [comment] 2021-03-30 13:21
a "noload" field won't load ever, so technically it doesn't matter.

most of the work here is adding new tests for "unloaded" and other attrs here in terms of them being prepared for end-user consumption.

**Comment by zzzeek** [comment] 2021-03-30 13:28
OK also it looks like the reason the attribute isn't in "unloaded" is because it's loaded, with an empty list.   it's in dict.    So I don't see a bug here other than the name "noload" is misleading.  It means, "noload_from_database"; the attribute has an empty collection present.   If you want there to be nothing at all there, you should use "raiseload":


```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", lazy="noload", collection_class=set)


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs={B()}))
s.commit()

a1 = s.query(A).first()

print("A1 KEYS: %s" % (a1.__dict__.keys(),))
print("A1 UNLOADED: %s" % (inspect(a1).unloaded))
assert not inspect(a1).unloaded.intersection(a1.__dict__)

s.expire(a1)


print("AFTER EXPIRE A1 KEYS: %s" % (a1.__dict__.keys(),))
print("AFTER EXPIRE A1 UNLOADED: %s" % (inspect(a1).unloaded))
assert not inspect(a1).unloaded.intersection(a1.__dict__)

```

**Comment by Omnia6975** [comment] 2021-03-30 14:42
hello, 
Thanks for having time to reply. 

It is then probably not a bug and just a question of understanding.
However, even if I understood your explanation from A to Z, I definitely squander something as I don't get the final point. 
For me, the conclusion still doesn't match to what 'I' could expect : "It is then right to write the 'noload' relationship into the 'unloaded' list in this case".

1/ Could you please then explain me in other words why the result  in the 'unload' list is different when you setup a relationship as the default lazy='select' (and not using it on a query finally) and lazy='noload' (and not using it a query too per definition). Both will not be used/query from the database ('noload_from_database') but in the last case it will still be displayed in the 'unloaded' list.

2/ As you said, I could consider that when the value is empty (one-to-many) or none (one-to-one) in the unloaded 'list' then I simply tag it as 'noload'. It is what I actually used at that time in fact. However, I think, there is definitely a lost of information. Indeed , and it is not to play on words, but 'empty' is not the same thing that 'nothing' as in my case I won't be able to know if the field does not exist in the 'unloaded' list because the relationship would have been removed previously (at the model level or dynamically at the query level) or simply because there is no matching result.

**Comment by zzzeek** [comment] 2021-03-30 14:56
> For me, the conclusion still doesn't match to what 'I' could expect : "It is then right to write the 'noload' relationship into the 'unloaded' list in this case".

based on my experiment in my last answer, if the "noload" relationship is in fact, not loaded, which means, "not in obj.__dict__", then the name is in fact present in the .unloaded collection.  so .unloaded is behaving consistently here.


> 
> 1/ Could you please then explain me in other words why the result in the 'unload' list is different when you setup a relationship as the default lazy='select' (and not using it on a query finally) and lazy='noload' (and not using it a query too per definition). 

because the ``NoLoader`` loader strategy, which is invoked for the relationship in question when the object is loaded, currently has the behavior that it places an empty collection into the ``__dict__`` of the target object when rows are first loaded, so that the attribute on the object is "loaded", it is just not "loaded" from the database.

The ``LazyLoader`` loader strategy does **not** put anything into ``__dict__`` of the target object when rows are first loaded.   it waits for attribute access and then queries the database at that time.

> Both will not be used/query from the database ('noload_from_database') but in the last case it will still be displayed in the 'unloaded' list.

look inside of ``obj.__dict__`` for which attributes are "loaded" and this will match.


> 
> 2/ As you said, I could consider that when the value is empty (one-to-many) or none (one-to-one) in the unloaded 'list' then I simply tag it as 'noload'. It is what I actually used at that time in fact. However, I think, there is definitely a lost of information. Indeed , and it is not to play on words, but 'empty' is not the same thing that 'nothing' as in my case 

For the attribute to be absolutely "nothing", means that when you attempt to access the attribute, as nothing is there, and there is no loader available, the expectation would be that it raises an error, because there's no other option.   This is available using the [raiseload](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html?highlight=raiseload#preventing-unwanted-lazy-loads-using-raiseload) loader strategy which is usually what people want here and is much more popular than "noload", the latter of which is kind of a quasi-legacy artifact that isn't generally useful for most things.

> I won't be able to know if the field does not exist in the 'unloaded' list because the relationship would have been removed previously (at the model level or dynamically at the query level) or simply because there is no matching result.

it sounds like "noload" is not what you actually want then, because it places an empty collection in place so that the attribute returns a value, but this value is mostly useless so I would advise using "raiseload" which is much more mainstream.

**Comment by zzzeek** [comment] 2021-03-30 14:58
here's lazy="raise", the attribue appears in unloaded consistently, because this attribute is in fact not loaded in any sense:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", lazy="raise", collection_class=set)


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs={B()}))
s.commit()

a1 = s.query(A).first()

# it's unloaded
assert 'bs' in inspect(a1).unloaded

# it's unloaded
assert 'bs' not in a1.__dict__

s.expire(a1)

assert 'bs' in inspect(a1).unloaded
assert 'bs' not in a1.__dict__


```

**Comment by CaselIT** [comment] 2021-03-30 15:48
I think the documentation could be improved a bit in this sense, giving the loader a category:
- eager load: the loader will populate the attribute by default
- lazy load: the loader will populate the attribute at first access.

the 'noload' NoLoader loader strategy is an eager load, meaning that it populates the attributes, but not from data in the db.
'raise' or the default 'select' are lazy lead, meaning that they will raise or populate the attribute at first access

**Comment by Omnia6975** [comment] 2021-03-30 16:56
> because the NoLoader loader strategy, which is invoked for the relationship in question when the object is loaded, currently has the behavior that it places an empty collection into the __dict__ of the target object when rows are first loaded, so that the attribute on the object is "loaded", it is just not "loaded" from the database.
> 
> The LazyLoader loader strategy does not put anything into __dict__ of the target object when rows are first loaded. it waits for attribute access and then queries the database at that time.

'+'


>     eager load: the loader will populate the attribute by default
>     lazy load: the loader will populate the attribute at first access.


OK, finally got the big picture, thanks, it is now crystal clear with these 2 last explanations.

Hard to say if I am just the only one who misunderstand it but from me, I am agree, that it could be interesting to have this precision in the documentation.

Thanks to both of you and for this extremely powerfull ORM you 've done.

**Comment by CaselIT** [comment] 2021-03-31 14:46
I'll try to look at the documentation, to maybe improve a bit that part. I'll reopen this as reminder.

**Comment by sqla-tester** [comment] 2021-04-01 17:36
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve noload documentation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2703

**Closed** 2021-04-02 15:26 UTC
Labels: documentation, orm
