### ISSUE TITLE
SQL Server JSON type using SQL Server 2016 json functions

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4384] opened 2018-11-28 19:49 UTC
SQL Server's official JSON story seems to be based on JSON functions:

https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017

the JSON_VALUE function doesn't look too different for what we're doing with MySQL and SQLite.

**Comment by hhsissi** [comment] 2019-03-26 19:55
up

**Comment by zzzeek** [comment] 2019-05-18 21:00
see 62d59088dfe for an overview of how this PR should look

**Comment by sqla-tester** [comment] 2020-08-01 21:57
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add JSON support for mssql.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2118

**Comment by gordthompson** [comment] 2020-08-01 22:13
Okay, so I had a bash at this and despite the superficial similarities there are two significant differences:

1. JSON results are always returned as strings (nvarchar(max)), even if the value being returned is stored in the JSON object as a scalar (like `int`).
2. We need to call two different functions depending on what we're trying to retrieve. If we want to retrieve a scalar we need to call `JSON_VALUE`, whereas if we want to retrieve an array or object we need to call `JSON_QUERY`.

``` python
import pyodbc

cnxn = pyodbc.connect("DSN=mssqlLocal64")
crsr = cnxn.cursor()


def recreate_table():
    jsn = '{"myint": 1}'
    crsr.execute("DROP TABLE IF EXISTS github_sa_4384")
    crsr.execute(
        "CREATE TABLE github_sa_4384 (id int primary key, jsn nvarchar(max))"
    )
    crsr.execute("INSERT INTO github_sa_4384 (id, jsn) VALUES (1, ?)", jsn)


# issue 1: int returned as str
recreate_table()
result = crsr.execute(
    "SELECT JSON_VALUE(jsn, 'strict $.myint') AS myint FROM github_sa_4384 WHERE id = 1"
).fetchval()
print(f"{type(result)}: {repr(result)}")
"""console output:
<class 'str'>: '1'
"""

# issue 2: different functions for objects and scalars
#
# 2.1 - retrieving an object/array
recreate_table()
try:
    result = crsr.execute(
        "SELECT JSON_VALUE(jsn, 'strict $') AS myint FROM github_sa_4384 WHERE id = 1"
    ).fetchval()
    print(f"{type(result)}: {repr(result)}")
except pyodbc.ProgrammingError as e:
    print(e.args[1])
    """console output:
    [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
    Scalar value cannot be found in the specified JSON path. 
    (13623) (SQLExecDirectW)
    """
recreate_table()
try:
    result = crsr.execute(
        "SELECT JSON_QUERY(jsn, 'strict $') AS thing FROM github_sa_4384 WHERE id = 1"
    ).fetchval()
    print(f"{type(result)}: {repr(result)}")
    """console output:
    <class 'str'>: '{"myint": 1}'
    """
except pyodbc.ProgrammingError as e:
    print(e.args[1])
#
# 2.2 - retrieving a scalar
recreate_table()
try:
    result = crsr.execute(
        "SELECT JSON_QUERY(jsn, 'strict $.myint') AS thing FROM github_sa_4384 WHERE id = 1"
    ).fetchval()
    print(f"{type(result)}: {repr(result)}")
except pyodbc.ProgrammingError as e:
    print(e.args[1])
    """console output:
    [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
    Object or array cannot be found in the specified JSON path. 
    (13624) (SQLExecDirectW)
    """
recreate_table()
try:
    result = crsr.execute(
        "SELECT JSON_VALUE(jsn, 'strict $.myint') AS myint FROM github_sa_4384 WHERE id = 1"
    ).fetchval()
    print(f"{type(result)}: {repr(result)}")
    """console output:
    <class 'str'>: '1'
    """
except pyodbc.ProgrammingError as e:
    print(e.args[1])
```

**Comment by zzzeek** [comment] 2020-08-02 00:04
the JSON returned as a string is typical and we use a result_processor() to turn that into a JSON object.  the default JSON type should be doing this.

for the scalar / array issue I think the other backends have similar complexities going on.     MySQL has about as bad as it gets:  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/base.py#L1338

**Comment by gordthompson** [comment] 2020-08-02 19:02
Thanks for the pointers. I tried adding a `result_processor` based on the MySQL one but after several rounds of "jiggling the wires" it still has no effect. 

I just updated the Gerrit with what I have done so far. Even after hard-coding an unconditional return value I still get `None` back from many of the queries in lib/sqlalchemy/testing/suite/test_types.py. Probably missing something silly, but I'm at a loss atm.

**Comment by zzzeek** [comment] 2020-08-02 19:23
I can take a run at it but there might be a long wait

**Comment by gordthompson** [comment] 2020-08-02 20:36
No worries. I'll keep chipping away at it as I get crazy new ideas. ;)

**Comment by gordthompson** [comment] 2020-08-02 21:33
One puzzling observation: Since my `result_processor` is not being invoked I added

``` python
import pdb; pdb.set_trace()
```

as the very first thing in the default `result_processor` function (`def process`)

https://github.com/sqlalchemy/sqlalchemy/blob/0afa28ee3a9699f7a03fbcc8baf01ea873d0c425/lib/sqlalchemy/sql/sqltypes.py#L2489-L2493

but when I run

``` none
pytest --db=mssql -k test_crit_against_string_coerce_type C:\Users\Gord\git\sqla-gerrit\test\dialect\test_suite.py
```

pdb does not kick in, suggesting that the default `result_processor` for JSON is not happening, either. 😕

**Comment by gordthompson** [comment] 2020-08-02 21:53
Ah, but pdb *does* kick in for some tests if I omit the `-k test_crit_against_string_coerce_type` and run the entire test suite. The adventure continues....

**Comment by zzzeek** [comment] 2020-08-02 23:41
yeah it sounds like your type is not being used.  it has to be registered in the dialect.colspecs dictionary for this part to happen, haven't checked if you did that part.

**Comment by gordthompson** [comment] 2020-08-03 13:09
No, my type is indeed being used. It's just that some tests don't invoke the `result_processor` and in my first example I happened to pick one that didn't. I have since confirmed that the tests that *do* invoke the `result_processor` are actually using mine.

After a bit more fiddling the remaining tests that are failing all seem to have a common issue:

``` python
    def test_string_cast_crit_mixed_path(self):
        col = self.tables.data_table.c["data"]
        self._test_index_criteria(
            cast(col[("key3", 1, "six")], String) == '"seven"', "r3"
        )
```

renders

``` none
[SQL: SELECT data_table.name
FROM data_table
WHERE CAST(JSON_VALUE(data_table.data, ?) AS VARCHAR(max)) = ?]
[parameters: ('strict $."key3"[1]."six"', '"seven"')]
```

but T-SQL's `JSON_VALUE` function returns `'seven'`, not `'"seven"'`, so the test fails (returns `None` instead of `'r3'`). The test passes if I simply modify it to use

``` python
        self._test_index_criteria(
            cast(col[("key3", 1, "six")], String) == 'seven', "r3"
```

but that would presumably break it for the other dialects.

**Comment by gordthompson** [comment] 2020-08-03 18:13
Mmm-kay, I managed to eliminate all but one of the fails in `JSONStringCastIndexTest` by adding the function

``` python
    def _quote_json_string(self, s):
        if config.db.engine.dialect.name == "mssql":
            return s
        else:
            return '"' + s.replace('"', '\\"') + '"'
```

and changing the tests to use it, e.g.,

``` python
    def test_string_cast_crit_mixed_path(self):
        col = self.tables.data_table.c["data"]
        self._test_index_criteria(
            cast(col[("key3", 1, "six")], String)
            == self._quote_json_string("seven"),
            "r3",
        )
```

The last holdout is `test_crit_against_string_coerce_type`, which uses `type_coerce("some value", JSON)`, so it appears I need to override that for mssql so it won't wrap the string in double-quotes. I've been digging through the source looking for where that might be accomplished but I haven't found it yet; it disappears behind a layer of abstraction here:

https://github.com/sqlalchemy/sqlalchemy/blob/0afa28ee3a9699f7a03fbcc8baf01ea873d0c425/lib/sqlalchemy/sql/expression.py#L229

**Comment by gordthompson** [comment] 2020-08-04 18:22
So in the end I just skipped that test. Gerrit passes CI now.

**Comment by zzzeek** [comment] 2020-08-04 18:32
OK yes I think actually I am removing that test anyway :)  b.c. it is failing for me on the pg8000 / asyncpg work I'm doing.    im not sure why that test is there and I think it was to support some older documented technique.

**Comment by gordthompson** [comment] 2020-08-04 21:45
I can delete that test from the Gerrit if you like, although this is milestoned for 1.4 so if you want it to go away for 1.3 as well then maybe it should be a separate change.

**Closed** 2020-08-19 17:25 UTC
Labels: SQL Server, datatypes, feature, motivated volunteers requested

**Comment by atellier** [comment] 2020-12-17 14:50
Hello!

I have a MSSQL database with "JSON" data in it (varchar(max)), and it would be very useful to use: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2118

It says merged, but I do not see it in the latest 1.3.20. Do I need to upgrade to 1.4 or should I just fork and cherry-pick this change in 1.3 for now?

Would be awesome to merge to 1.3 as well as in the meantime as the migration to 1.4 may take a bit of time;)

Thanks!

**Comment by gordthompson** [comment] 2020-12-17 16:32
@atellier - The `master` branch is (currently) what becomes 1.4, so those changes are included in [1.4.0b1](https://pypi.org/project/SQLAlchemy/1.4.0b1/).

We have no plans to back-port significant new features to 1.3 now that 1.4 is "a thing".

**Comment by atellier** [comment] 2020-12-19 20:12
Is there any reason to use `DECIMAL(10, 6)` versus a more simple `DECIMAL` cast?

I have some JSON data with more precision that that, and when fetching a value in that json (and using `.as_float()`), I am getting a lot of _Overflow Arithmetic Conversion_ errors from MSSQL because of that implicit limitation. 

My solution for now if to use  `@compiles(Select, "mssql")` statement and regexp change all `DECIMAL(10, 6)` into `DECIMAL`, but it is not optimal.

Thanks

**Comment by zzzeek** [comment] 2020-12-19 20:17
hi @atellier , this appears to be an arbitrary SQL Server question, would you care to post on the [mailing list](https://groups.google.com/forum/#!forum/sqlalchemy) or perhaps start a new [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions) ?

**Comment by gordthompson** [comment] 2020-12-19 21:01
@atellier - … and when you do, please include a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

**Comment by atellier** [comment] 2020-12-19 21:37
Will do. But just to give more context here, I was referring to the MSSQL implementation decribed in this thread, and this line in particular: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2118/19/lib/sqlalchemy/dialects/mssql/base.py#2045

It will cause an arbitrary cast to `DECIMAL(10, 6)` when using a `Numeric` field (such as when using `as_float()`). And it will break on MSSQL easily. For instance, to show how that cast can break, the following SQL code mimics what sqlalchemy would output and it gives me an error using Microsoft SQL Server 2017:

```
SELECT CASE JSON_VALUE(test.value, '$.test.value') WHEN NULL THEN NULL 
    ELSE CAST(JSON_VALUE(test.value, '$.test.value') AS DECIMAL(10, 6)) END
FROM (SELECT '{"test": {"value": 1234567.89}}' as value) as test
```

with error: `SQL Error [8115] [S0008]: Arithmetic overflow error converting nvarchar to data type numeric.`

Using `FLOAT` instead of `DECIMAL(10, 6)` fixes the issue at the expense of some conversion and potential loss of precision - but it does not cause an error. 

*Note:* Having a `as_numeric(p,s)` in the JSON implementation would be nice. So that we could generate a cast as `FLOAT` or as `DECIMAL(p, s)` depending on what `as_xxxx` as used. But that is probably a separate feature request.

In this light, should I create a new ticket, or a new discussion?

Thanks a lot again!

**Comment by zzzeek** [comment] 2020-12-19 21:42
if you have an [MCVE](http://stackoverflow.com/help/mcve) for me to run that will illustrate the issue, then open a ticket with that script I can run.   thanks!
