### ISSUE TITLE
Bad precendence grouping when calling BinaryExpression.is_not()

### ISSUE THREAD

**Issue by matthewgdv** [sqlalchemy/sqlalchemy#6908] opened 2021-08-19 15:24 UTC
### Describe the bug

So I spent about an hour today debugging a query I was writing and the issue turned out to be a missing set of parentheses that the compiler *should* be inserting, but isn't. Details follow:

### To Reproduce

```python
print(
    select(some_table).where(
        (some_table.some_column + '.some_suffix').is_not(None)
    )
)
```

### Error

The generated SQL (on postgresql) looks like this:

```
SELECT * 
FROM some_schema.some_table
WHERE some_schema.some_table.some_column || %(some_column_1)s IS NOT NULL
```

However, this will raise an error that the textual column `some_schema.some_table.some_column` cannot be concatenated to a boolean. This is because the attempted concatenation is:

`some_table.some_column || ('.some_suffix' IS NOT NULL)`

rather than:

`(some_table.some_column || '.some_suffix') IS NOT NULL`

The correct SQL would therefore be:

```
SELECT * 
FROM some_schema.some_table
WHERE (some_schema.some_table.some_column || %(some_column_1)s) IS NOT NULL
```

### Versions

- OS: Windows 10
- Python: 3.9
- SQLAlchemy: 2.0
- Database: redshift
- DBAPI: psycopg2

### Additional context

I wonder if this issue is more broad than just `BinaryExpression.is_not()`. For one, I would imagine `BinaryExpression.is_()` would also be affected, but perhaps there are other methods that also suffer from the same problem? Or other clause elements besides BinaryExpression which support methods like this?

**Comment by zzzeek** [comment] 2021-08-19 15:31
work around this like this:

`(some_table.some_column + '.some_suffix').self_group().is_not(None)`

**Comment by zzzeek** [comment] 2021-08-19 15:34
crap, workaround update:

```py
from sqlalchemy.sql.elements import Grouping
Grouping(some_table.some_column + '.some_suffix').is_not(None)
```

**Comment by matthewgdv** [comment] 2021-08-19 15:38
Thanks for the quick response. I'll use an explicit `Grouping` element for now until this eventually gets fixed :)

**Comment by zzzeek** [comment] 2021-08-19 15:39
Hi i can't reproduce your issue, can you provide the exact failing SQL?  this works in Postgresql, sqlite, etc:

```
test=> select 'x' || 'y'  is not null;
 ?column? 
----------
 t
(1 row)

```

**Comment by jvanasco** [comment] 2021-08-19 15:41
also please share the PostgreSQL version this fails on.  the PG team may have identified this as a bug on their end and fixed it in a more recent version.

**Comment by zzzeek** [comment] 2021-08-19 15:44
also good news I mis-read the code, the self_group() method **will** work to force the parenthesis :)

**Comment by matthewgdv** [comment] 2021-08-19 15:48
Oh wow, I'm so sorry.

It's easy to forget sometimes that Redshift isn't actually postgresql and has tiny differences here and there since it's so similar and 99.99% of the time everything just works.

So yeah, I'm using psycopg2 but the backend I'm connected to is actually a Redshift data warehouse. If you think it makes sense to drop close this bug report as a result (since I don't think sqlalchemy explicitly supports Redshift) that's cool, I'll just use explicit grouping for this particular edge-case.

If you think it's still worth making this change to incidentally support Redshift then that'd be much appreciated though! :)

The error for the block of code in the original report (after having anonymized the schema/table/column names) is as follows:

```
ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character varying || boolean
HINT:  No operator matches the given name and argument type(s). You may need to add explicit type casts.

[SQL: SELECT * 
FROM some_schema.some_table
WHERE some_schema.some_table.some_column || %(some_column_1)s IS NOT NULL]
[parameters: {'some_column_1': '.some_suffix'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by zzzeek** [comment] 2021-08-19 15:59
so we would prefer redshift users at least use the dedicated dialect for redshift which still uses psycopg2 and is https://github.com/sqlalchemy-redshift/sqlalchemy-redshift , this builds on the existing psycopg2 dialect in SQLAlchemy.

however I'm not sure they are able to accommodate this issue, they could do it using a rule in the compiler to add parenthesis around the "concat" operator in all cases. but the precedence rules are currently database-agnostic and decided before the expression is compiled.

**Comment by matthewgdv** [comment] 2021-08-19 16:07
That's fair, the reason I'm not actually using the dedicated redshift dialect is because I've migrated my department's sqlalchemy codebase to be 2.0 compliant and sqlalchemy-redshift has not yet caught up to that. Here's an issue I opened with them some time ago:

https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/222

For most dialects these extra parentheses are unnecessary but they wouldn't actually break anything (would they?), whereas for Redshift it would help to prevent this scenario. I don't know how worth it it would be to special-case this just to cater to a single dialect though. Your choice to make :)

**Comment by jvanasco** [comment] 2021-08-19 16:16
> For most dialects these extra parentheses are unnecessary but they wouldn't actually break anything (would they?)

You would be surprised.

**Comment by zzzeek** [comment] 2021-08-19 16:27
the precedence stuff is not easy to just change unfortunately since it's an ordered list of precedences.   we would have to someday move the entire concept of "operator precedence" into the compiler so that it can be a dialect-specific thing to better handle problems like this.

**Comment by CaselIT** [comment] 2021-08-19 16:54
I thinks we could mark this as won't fix?

**Comment by zzzeek** [comment] 2021-08-19 17:06
that's where we are at for the moment yes.  longer term we should think if we can move precedence rules to the compiler, which means we wouldnt call self_group() anymore.  but clearly that's a super big deal, not on any roadmap right now.

**Closed** 2021-08-19 17:11 UTC
Labels: bug, wontfix, sql, dialects
