### ISSUE TITLE
sqlalchemy.exc.noinspectionavailable

### ISSUE THREAD

**Issue by optiona1** [sqlalchemy/sqlalchemy#5260] opened 2020-04-17 01:48 UTC
When I put `func.count (1)` in the first position of the `query` statement, and then used the `filter_by` statement, I got an` sqlalchemy.exc.noinspectionavailable: no inspection system is available for object of type < class' nonetype '>` error, but I did not put it in the first position, or did not use the `filter_by`, or in `count` using the primary key field in will not cause this problem.
System environment：
```
os: Linux archlinux 5.4.31-1-lts #1 SMP Wed, 08 Apr 2020 08:29:49 +0000 x86_64 GNU/Linux
Python: Python 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0] on linux
sqlalchemy: 1.3.3
```

**Comment by CaselIT** [comment] 2020-04-17 15:18
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) illustrating your example. 
Here are some example issues https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22

**Comment by zzzeek** [comment] 2020-04-23 15:54
please reopen with further detail.

**Comment by optiona1** [comment] 2020-04-28 10:57
```python
from flask import Flask

from sqlalchemy import create_engine, Column, Integer, func
from sqlalchemy.ext.declarative import declarative_base, declared_attr
from sqlalchemy.orm import sessionmaker, scoped_session

from app.config import Config

engine = create_engine(
    Config.SQLALCHEMY_DATABASE_URI,
    pool_size=Config.SQLALCHEMY_POOL_SIZE,
    max_overflow=Config.SQLALCHEMY_MAX_OVERFLOW,
    pool_recycle=Config.SQLALCHEMY_POOL_RECYCLE,
)

db_session = scoped_session(sessionmaker(autocommit=True, autoflush=False, bind=engine))


class Base:
    @declared_attr
    def __tablename__(cls):
        return (
            "".join("_%s" % c if c.isupper() else c for c in cls.__name__)
            .strip("_")
            .lower()
        )


Base = declarative_base(cls=Base)


class TestModel(Base):
    """test model"""

    id = Column(Integer, comment="primary_key", primary_key=True)
    money = Column(Integer, comment="test field")
    num = Column(Integer, comment="test field")


app = Flask(__name__)


@app.route("/")
def hello():
    res = db_session.query(
        func.count(1).label("test"),
        func.sum(TestModel.money).label("order_amount"),
        func.count(TestModel.num).label("order_num"),
    ).filter_by(vdate=1588070891)
    data = parse_result(res)
    return data

```
This is the sample code. I use postgres and psycopg2-binary driver

**Comment by CaselIT** [comment] 2020-04-28 11:29
Thanks, I'll reopen it

**Comment by CaselIT** [comment] 2020-04-28 17:33
This is the stack trace:
```
  File "\sqlalchemy\lib\sqlalchemy\orm\query.py", line 1798, in filter_by
    for key, value in kwargs.items()
  File "\sqlalchemy\lib\sqlalchemy\orm\query.py", line 1798, in <listcomp>
    for key, value in kwargs.items()
  File "\sqlalchemy\lib\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    insp = inspection.inspect(entity)
  File "\sqlalchemy\lib\sqlalchemy\inspection.py", line 73, in inspect
    "available for object of type %s" % type_
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'NoneType'>
```

This seems to happen because the orm cannot infer the entity on the first column. It needs it to apply the filter_by. 

To solve this you can use either
- use another column as the fist one, instead of `func.count(1).label("test")`
- use `filter` instead of `filter_by`

@zzzeek I'm not sure if this case should be fixed. Maybe a better error could be provided?

**Comment by zzzeek** [comment] 2020-04-28 18:18
this needs a better error message, yes.    if we can get that plus test coverage, as I am rewriting pretty much the whole Query I will need the test case to make sure I re-implement.

**Comment by CaselIT** [comment] 2020-04-28 19:24
should we only check in filter by? I guess this type of error may be possible in other methods?

**Comment by zzzeek** [comment] 2020-04-29 00:40
it is actually a pretty specific case that is only on filter_by(), and perhaps with_parent() which is to be deprecated.   filter_by() is getting a very major rewrite for 1.4 however.

**Comment by sqla-tester** [comment] 2020-05-14 19:52
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve error message when using :meth:`_query.Query.filter_by` in** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1972

**Comment by sqla-tester** [comment] 2020-05-15 16:44
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Improve error message when using :meth:`_query.Query.filter_by` in** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1978

**Closed** 2020-05-23 21:12 UTC
Labels: orm, use case

**Comment by ncastrohub** [comment] 2020-12-20 20:52
Hi, i am having this issue when trying to do a session.merge() 

This merge is done with values that correspond to foreign keys.

Also this were working fine but I am trying to upgrade from raw sqlalchemy to flask-sqalchemy because I am having some errors.

There is any reason why merge() fails with this error ?

**Comment by CaselIT** [comment] 2020-12-20 21:03
if you can provide a reproduction script, please open another issue so we can better track it.
