### ISSUE TITLE
unexpected error prevent DELETE when using mssql+pyodbc

### ISSUE THREAD

**Issue by ling7334** [sqlalchemy/sqlalchemy#5068] opened 2019-12-31 09:40 UTC
I can not perform delete operation when using pyodbc.

# Log
```log
Traceback (most recent call last):
  File "D:\Work\amc\itnb\views\mail.py", line 113, in delete
    db.session.commit()
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\session.py", line 1027, in commit
    self.transaction.commit()
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\session.py", line 494, in commit
    self._prepare_impl()
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
    self.session.flush()
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\session.py", line 2470, in flush
    self._flush(objects)
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\session.py", line 2568, in _flush
    flush_context.execute()
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 624, in execute
    uow,
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\persistence.py", line 348, in delete_obj
    delete,
  File "d:\users\zfling\.virtualenvs\amc-tsr_9pbu\lib\site-packages\sqlalchemy\orm\persistence.py", line 1338, in _emit_delete_statements
    stacklevel=12,
TypeError: warn() got an unexpected keyword argument 'stacklevel'
```

# Investigation
After some investigation, I follow down to `orm/persistence.py`, it seems that an exeception occured  when `warn` function which only accept one parameter is called, however `stacklevel` is provided.

https://github.com/sqlalchemy/sqlalchemy/blob/431f655b407cd3b266b5dfed5a5f3822e2c6b032/lib/sqlalchemy/orm/persistence.py#L1340

because i use pyodbc, it want to display some warning for not support `deleted rowcount`, however the `warn` function was called mistakenly and throw an unexpected error.

# Temporary solution
comment out the use of `warn`. 👍

**Can you fix this, please.**

**Comment by zzzeek** [comment] 2019-12-31 16:40
hi there -

the "supports_sane_rowcount" flag is True for all SQL Server dialects and there is no logic that sets this to False for any driver.   Can you explain how this flag is being set to False?  Are you manually setting it to False ?

**Comment by sqla-tester** [comment] 2019-12-31 16:54
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Repair uncovered warning in persistnce.py; update versioning tests** https://gerrit.sqlalchemy.org/1639

**Comment by sqla-tester** [comment] 2019-12-31 16:54
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Repair uncovered warning in persistnce.py; update versioning tests** https://gerrit.sqlalchemy.org/1640

**Closed** 2019-12-31 22:09 UTC
Labels: bug, orm

**Comment by ling7334** [comment] 2020-01-02 08:41
Yes, I disabled "supports_sane_rowcount". It failed when UPDATE if "supports_sane_rowcount" is set to **True**
In fact, it is common to disable "supports_sane_rowcount" as a workaround for `pyodbc` and `Microsoft ODBC Driver` does not support rowcount.

**Comment by zzzeek** [comment] 2020-01-02 15:34
> Yes, I disabled "supports_sane_rowcount". It failed when UPDATE if "supports_sane_rowcount" is set to **True**

Hi can you define "failed" please?   Are you getting the same error as described in #5005 ?

> In fact, it is common to disable "supports_sane_rowcount" as a workaround for `pyodbc` and `Microsoft ODBC Driver` does not support rowcount.

As in #5005 we cannot reproduce this.   MS ODBC driver supports rowcount in all environments we have access to (linux, windows) and always has.   Can you please indicate the exact ODBC driver version, eg.. the full .so filename and configuration used if on linux, etc. , over on #5005 ?  thanks.
