### ISSUE TITLE
mypy report incompatible type on initialization of optional fields of a MappedAsDataclass Class

### ISSUE THREAD

**Issue by benoit74** [sqlalchemy/sqlalchemy#9919] opened 2023-06-09 07:40 UTC
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

mypy report the following error when I try to create an ORM object with an optional field set as None. Looks like the checker does not realize that the field is optional.

### To Reproduce

```python
from typing import Optional

from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(MappedAsDataclass, DeclarativeBase):
    """subclasses will be converted to dataclasses"""


class User(Base):
    __tablename__ = "user_account"

    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    name: Mapped[Optional[str]]


aUser = User(None)
```

### Error

```
(main.py:17: error: Argument 1 to "User" has incompatible type "None"; expected "Union[SQLCoreOperations[Optional[str]], str]"  [arg-type])
``` 

### Versions

- OS: Mac OS Montery (12.6.5)
- Python: 3.11.2
- SQLAlchemy: SQLAlchemy-2.0.15
- Type checker : mypy 1.3.0 (compiled: yes)

### Additional context

Using `aUser = User(literal(None))` instead of `aUser = User(None)` is sufficient to work around the issue, mypy does not complains anymore.

**Comment by CaselIT** [comment] 2023-06-09 10:15
Hi,

This a mypy issue.
Duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/9855 and https://github.com/sqlalchemy/sqlalchemy/issues/9617

**Closed by CaselIT** 2023-06-09 10:15 UTC
Labels: requires triage, typing
