### ISSUE TITLE
Redshift: FATAL:  unrecognized configuration parameter "standard_conforming_strings"

### ISSUE THREAD

**Issue by tfrokt** [sqlalchemy/sqlalchemy#9494] opened 2023-03-16 04:40 UTC
### Describe the bug

Using SQLAlchemy with AWS Redshift ([1.0.47357](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html)).

After upgrading to:

```
SQLAlchemy==2.0.6
psycopg2-binary==2.9.5
```

I am getting:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) unrecognized configuration parameter "standard_conforming_strings"
```

Tried connecting with:

```
connect_args = {'options': '-c standard_conforming_strings=off'}
create_engine(self.connection_string, pool_pre_ping=True, connect_args=connect_args)
```

as ChatGPT suggested, getting a different, but similar error message:

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "<redshift-host>" (<redshift-ip>), port 5439 failed: FATAL:  unrecognized configuration parameter "standard_conforming_strings"
```

```
python --version
Python 3.9.16
```

### SQLAlchemy Version in Use

SQLAlchemy==2.0.6

### DBAPI (i.e. the database driver)

psycopg2-binary==2.9.5

### Database Vendor and Major Version

Redshift 1.0.47357

### Python Version

Python 3.9.16

### Operating system

OSX

### To Reproduce

```python
create_engine(connection_string, pool_pre_ping=True)

# or 

connect_args = {'options': '-cstandard_conforming_strings=off'}
# or
# connect_args = {'options': '-c standard_conforming_strings=off'}
create_engine(connection_string, pool_pre_ping=True, connect_args=connect_args)
```

### Error

```
Traceback (most recent call last):
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: unrecognized configuration parameter "standard_conforming_strings"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/.ve/lib/python3.9/site-packages/lru/decorators.py", line 132, in _lazy_cache_wrapper
    result = function(*args, **kwargs)
  File "/src/mypackage/redshift.py", line 164, in tier1_partners
    rs.connect()
  File "/src/.ve/lib/python3.9/site-packages/maa/db.py", line 69, in connect
    self._connection = self._engine.connect()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
    return self._connection_cls(self)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    self._dec_overflow()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 917, in __connect
    pool.dispatch.connect.for_modify(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1912, in go
    return once_fn(*arg, **kw)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 747, in first_connect
    dialect.initialize(c)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 654, in initialize
    super().initialize(connection)
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3033, in initialize
    std_string = connection.exec_driver_sql(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1772, in exec_driver_sql
    ret = self._execute_context(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/src/.ve/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) unrecognized configuration parameter "standard_conforming_strings"
``` 

### Additional context

thx for checking

**Comment by tfrokt** [comment] 2023-03-16 04:42
@matt-del-valle-outplay

**Comment by tfrokt** [comment] 2023-03-16 05:25
Tried a few of the version `2.0.X`, but none worked. Maybe it's a non-backwards compatible change? Going back to `1.4.46` looks ok.

**Comment by CaselIT** [comment] 2023-03-16 06:48
Hi,
This is a duplicate of #9442

**Closed by CaselIT** 2023-03-16 06:48 UTC
Labels: requires triage

**Comment by jonasddev** [comment] 2025-02-27 08:35
I solved it by creating a custom Dialect extending the psycopg2 dialect, overriding the method that used to call the unavailable statement in Redshift:

```
from sqlalchemy.dialects import registry
from sqlalchemy.dialects.postgresql.psycopg2 import PGDialect_psycopg2
class RedshiftPostgresDialect(PGDialect_psycopg2):
    def _set_backslash_escapes(self, connection):
        self._backslash_escapes = "off"
registry.register("redshift_custom", __name__, "RedshiftPostgresDialect")



from sqlalchemy import create_engine
db = create_engine("redshift_custom://user:password@redshifthost:5439/dev")

```

Hope this helps
