### ISSUE TITLE
Inheriting from DeclarativeMeta overriding __getattr__ doesn't work with aliased

### ISSUE THREAD

**Issue by dima-starosud** [sqlalchemy/sqlalchemy#4694] opened 2019-05-23 13:07 UTC
This is using `SQLAlchemy-1.3.3`.
I am implementing custom fields on entities inheriting from `DeclarativeMeta` and overriding `__getattr__`, please see the code below:

    from sqlalchemy import Column, Integer, JSON
    from sqlalchemy.ext.declarative import DeclarativeMeta, declarative_base
    from sqlalchemy.orm import aliased, configure_mappers
    
    
    class MyDeclarativeMeta(DeclarativeMeta):
        FIELDS = frozenset()
    
        def __getattr__(cls, key):
            if key in cls.FIELDS:
                return cls.fields[key]
            return getattr(super(), key)
    
    
    Base = declarative_base(metaclass=MyDeclarativeMeta)
    
    
    class A(Base):
        __tablename__ = 'a'
        id = Column(Integer, primary_key=True)
        fields = Column(JSON)
    
        def __getattr__(self, key):
            ...
    
        def __setattr__(self, key, value):
            ...
    
    
    configure_mappers()
    
    A.FIELDS |= {'name'}
    
    print(A.name)
    # a.fields[:fields_1]
    
    print(aliased(A).name)
    # Traceback (most recent call last):
    #   File "main.py", line 38, in <module>
    #     print(aliased(A).name)
    #   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/util.py", line 506, in __getattr__
    #     raise AttributeError(key)
    # AttributeError: name

So `A.name` works, but `aliased(A).name` fails.
Am I doing it wrong?
I see `AliasedClass.__getattr__` uses `object.__getattribute__` which doesn't call my method...

**Comment by zzzeek** [comment] 2019-05-23 13:19
Hi there -

This is simply not a use case that's ever been attempted so it is likely that for your use case to work there would need to be some kind of modifications to the library made.   I'm not sure what kinds of issues might arise.

That said, it would be better if you could find a way to do what you need without this level of class magic, but if you have interest in proposing changes to AliasedClass where you can also provide tests feel free.

**Comment by dima-starosud** [comment] 2019-05-23 13:27
I am going to replace part of the `AliasedClass.__getattr__`

        for base in _aliased_insp._target.__mro__:
            try:
                attr = object.__getattribute__(base, key)
            except AttributeError:
                continue
            else:
                break
        else:
            raise AttributeError(key)

with `attr = getattr(base, key)`.

**Comment by zzzeek** [comment] 2019-05-23 13:28
OK and then will you run the orm test suite to see if that breaks things?  I'd have to look at that code again but it is likely the `__getattribute__` there is intentional

**Comment by dima-starosud** [comment] 2019-05-23 13:36
I think that might be for speed, as `object. __getattribute__` doesn't do full `getattr` machinery...

I'll try on my application first.
Also I would like to run ORM test suite, but I will have to setup sqlalchemy dev environment for this. Can you point me to the doc/wiki describing this?

**Comment by zzzeek** [comment] 2019-05-23 13:52
an overview of how to run the test suite is at https://github.com/sqlalchemy/sqlalchemy/blob/master/README.unittests.rst 

here's how to run the tests en masse, assuming you have tox:

```
git clone https://github.com/sqlalchemy/sqlalchemy.git
cd sqlalchemy
tox -e py37 -- test/orm
```

if you want to run the tests more surgically, here's more of that, assuming you have nothing else set up but virtualenv:

```
git clone https://github.com/sqlalchemy/sqlalchemy.git
cd sqlalchemy
virtualenv .venv
.venv/bin/pip install pytest
.venv/bin/pip install -e .
.venv/bin/py.test test/orm/test_query.py
```

basically for us to make this change means we are officially supporting aliased() of an ORM class that defines its own `__getattr__()` so there needs to be tests that ensure this, otherwise it will just change back someday

**Comment by dima-starosud** [comment] 2019-05-23 15:31
OK, looks like I that loop over `__mro__` cannot be replaced by simple `getattr`. I had to do this (kind of last resort) to make tests pass:

            for base in _aliased_insp._target.__mro__:
                try:
                    attr = object.__getattribute__(base, key)
                except AttributeError:
                    continue
                else:
                    break
            else:
                try:
                    attr = getattr(_aliased_insp._target, key)
                except AttributeError:
                    raise AttributeError(key)

**Comment by zzzeek** [comment] 2019-05-23 16:02
OK, so that's a fallback, that might be reasonable since it isn't used unless there would be an exception anyway.       We would need to find an appropriate place to put a test for this in test/orm somewhere.   I'm not sure if there's a suite of plain "AliasedClass" unit tests.

**Comment by dima-starosud** [comment] 2019-05-24 09:15
1. I found `test/orm/test_utils.py::AliasedClassTest`, so probably will add tests there.
2. Also I wanted to clarify if it's possible to target this fix onto 1.2?
    Should I branch from 1.2 and then back merge 1.2 to master?
3. Should I fork this repo to be able to do PR to it?

**Comment by zzzeek** [comment] 2019-05-24 13:15
> (sorry for questions bloat)
> 
>     1. I found `test/orm/test_utils.py::AliasedClassTest`, so probably will add tests there.

perfect!   that's exactly right

> 
>     2. Also I wanted to clarify if it's possible to target this fix onto 1.2?

I'm done releasing 1.2 releases we are well into 1.3 at this point, the upgrade path should be mostly effortless.   This is already a bit of a destabilizing change depending on how it goes.

>        Should I branch from 1.2 and then back merge 1.2 to master?

always work in master, we always backport

> 
>     3. Should I fork this repo to be able to do PR to it?

yes so you can just work with a normal github PR against master here, and I have an elaborate integration with a code review system called Gerrit that you don't have to deal with at all, you will see code review comments and whatnot on your pull request.

> 
>     4. Also I am going to investigate the difference between `object.__getattribute___` and `getattr` here, as it looks like sometimes they produce different results (at least for `hybrid_method`).

That stuff is extremely sensitive because there are tons of use cases packed into the attribute mechanics at this point, all of which should be tested and all of which have to continue working.   None of these attribute systems started out this complicated, it's new behavioral requests like this one over the years that has made everything so packed such that if you change anything, tests break.


> 
>     5. BTW, I am considering using `_aliased_insp._target.__class__.__getattr__` instead of `getattr` - in this case previous item about difference will gone.

sure I thought the same thing.

**Comment by dima-starosud** [comment] 2019-05-29 14:25
@zzzeek, calling `__getattr__`  doesn't work for me for `hybrid_property` - it doesn't respect aliasing:

    from sqlalchemy import Column, Integer, MetaData, Table
    from sqlalchemy.ext.hybrid import hybrid_property
    from sqlalchemy.orm import aliased, mapper
    
    table = Table(
        "point",
        MetaData(),
        Column("id", Integer(), primary_key=True),
        Column("x", Integer),
    )
    
    class MetaPoint(type):
        def __getattr__(cls, key):
            if key == "double_x":
                return cls.impl_double_x
            raise AttributeError(key)
    
    class Point(object, metaclass=MetaPoint):
        @hybrid_property
        def impl_double_x(self):
            return self.x * 2
    
    mapper(Point, table)
    alias = aliased(Point)
    
    print(alias.impl_double_x.__clause_element__())
    # point_1.x * :x_1
    
    print(alias.double_x.__clause_element__())
    # point.x * :x_1

What I see `object.__getattribute__` doesn't apply descriptor, it just returns it as is, whereas `__getattr__` does. But I am not sure this is an issue.
Note `__getattr__` cannot return raw descriptor as it wouldn't work for non-aliased case.

Could you suggest me the ways for further investigation?
1. I see there `adapt_to_entity` is called, but it doesn't adapt for some reason.
2. I was thinking about some special method which would return plain descriptor, but that's too ad-hoc.

**Comment by zzzeek** [comment] 2019-05-29 14:39
should i run that with your proposed change?   I have no experience using `__getattr__()` on type objects.

**Comment by dima-starosud** [comment] 2019-05-29 15:13
Yes, here is my implementation with tests https://github.com/dima-starosud/sqlalchemy/tree/AliasedClass-is-aware-of-__getattr__-of-underlying
And e.g. `test_meta_getattr_two` fails:

    eq_(str(alias.double_x.__clause_element__()), "point_1.x * :x_1")
    # AssertionError: 'point.x * :x_1' != 'point_1.x * :x_1'

**Comment by zzzeek** [comment] 2019-05-29 16:04
I think the "return cls._impl_double_x" you are doing inside the metaclass is causing the hybrid to create the proxy that the `__getattribute__()` logic is trying to avoid.  so we will have to detect that and unwrap it.  that might even be a generalized way the whole thing could work but im not sure we'd want to do that (needless creation and throwaway of proxy objects).

**Comment by zzzeek** [comment] 2019-05-29 16:10
I can get test_meta_getattr_two to work.  test_meta_getattr_three looks crazy and that doesn't work at all.   You can't need it to do *that*.

**Comment by zzzeek** [comment] 2019-05-29 16:23
I'd really have to fully reopen all the use cases for this and fully re-understand the whole thing to write this such that it can expect sub-callables the way it's doing.  The quick hack to make test two work is:

```
diff --git a/lib/sqlalchemy/orm/util.py b/lib/sqlalchemy/orm/util.py
index 08ffb784d4..fa9af7a7cb 100644
--- a/lib/sqlalchemy/orm/util.py
+++ b/lib/sqlalchemy/orm/util.py
@@ -504,10 +504,9 @@ class AliasedClass(object):
                 else:
                     break
             else:
-                try:
-                    attr = target.__class__.__getattr__(target, key)
-                except AttributeError:
-                    raise AttributeError(key)
+                attr = getattr(target, key)
+                if attr._is_internal_proxy:
+                    attr = attr.descriptor
 
         if isinstance(attr, PropComparator):
             ret = attr.adapt_to_entity(_aliased_insp)

```

but this is too hacky, it's very specific to that one test.   There also seems to be some uncovered code in here as well, the "func_code" path, there's no "util.types.MethodType()" so that code is not even used, coverage at https://jenkins.sqlalchemy.org/job/sqlalchemy_coverage/758/cobertura/lib_sqlalchemy_orm/util_py/ confirms it.   needs cleanup

**Comment by zzzeek** [comment] 2019-05-29 16:27
basically we need to go through every test and document every kind of object that comes through this method and what the usage contract should be.    then we can try changing it to call getattr() and *unwrap* what it gets, rather than trying to bypass the attribute mechanics.  the change above is one example of getting the full object and unwrapping it, for a very specific case of "unwrap".   

that is, the code should look like:

```
    def __getattr__(self, key):
        try:
            _aliased_insp = self.__dict__["_aliased_insp"]
        except KeyError:
            raise AttributeError()
        else:
            # maintain all getattr mechanics, let user do anything
            attr = getattr(target, key)

        # now post-unwrap the thing we need so we can adapt it to our
        # SQL expression
        if attr.is_wrapped_like_this:
            attr = attr.get_this_thing
        elif attr.is_wrapped_like_that:
            attr = attr.get_that_thing

        if isinstance(attr, PropComparator):
            ret = attr.adapt_to_entity(_aliased_insp)
            setattr(self, key, ret)
            return ret
        elif hasattr(attr, "func_code"):
            # why?
            return None
        elif hasattr(attr, "__get__"):
            ret = attr.__get__(None, self)
            if isinstance(ret, PropComparator):
                return ret.adapt_to_entity(_aliased_insp)
            else:
                return ret
        else:
            return attr

```

**Comment by dima-starosud** [comment] 2019-05-29 16:47
Thank you @zzzeek will try to adopt your suggestions.

**Comment by zzzeek** [comment] 2019-05-29 17:36
@dima-starosud this is not an easy change , so perhaps try to print out everything it receives there while running the tests and for each case we can try to figure out what to do.

also we might want to add a method to sqlalhcemy.orm.attributes.Proxy.adapt_to_entity(),so that we can just say:

```
if hasattr(attr, "adapt_to_entity"):
  attr = attr.adapt_to_entity(_aliased_insp)

```

basically the steps are:

1. get the thing from the wrapped class

2. make the SQL part of it look like us

**Comment by zzzeek** [comment] 2019-05-29 17:47
that doesn't really work.     this is really a lot of history from my own hackings it's going to be really near impossible for this to make sense let me try to work it a bit

**Comment by zzzeek** [comment] 2019-05-29 18:17
propose test_three is written like this:

```
    def test_meta_getattr_three(self):
        class MetaPoint(type):
            def __getattr__(cls, key):
                @hybrid_property
                def double_x(me):
                    return me.x * 2

                if key == "double_x":
                    return double_x.__get__(None, cls)
                raise AttributeError(key)

        class Point(object, metaclass=MetaPoint):
            pass

        self._fixture(Point)

        alias = aliased(Point)

        eq_(str(Point.double_x.__clause_element__()), "point.x * :x_1")
        eq_(str(alias.double_x.__clause_element__()), "point_1.x * :x_1")

```


otherwise, you are not fulfilling the contract of `__getattr__` correctly, you must invoke the descriptor here.

Then I can get all tests to pass like this:

```
    def __getattr__(self, key):
        try:
            _aliased_insp = self.__dict__["_aliased_insp"]
        except KeyError:
            raise AttributeError()
        else:
            target = _aliased_insp._target
            # maintain all getattr mechanics, let user do anything
            attr = getattr(target, key)

        # attribute is a method, that will be invoked against a
        # "self"; so just return a new method with the same function and
        # new self
        if hasattr(attr, '__call__') and hasattr(attr, '__self__'):
            return types.MethodType(attr.__func__, self)

        # attribute is a descriptor, that will be invoked against a
        # "self"; so invoke the descriptor against this self
        if hasattr(attr, '__get__'):
            attr = attr.__get__(None, self)

        # attributes within the QueryableAttribute system will want this
        # to be invoked so the object can be adapted
        if hasattr(attr, 'adapt_to_entity'):
            attr = attr.adapt_to_entity(_aliased_insp)

        return attr

```

**Comment by sqla-tester** [comment] 2019-05-29 18:32
**Dmytro Starosud** has proposed a fix for this issue in the **master** branch:

**Rework AliasedClass __getattr__ to use top-level getattr()** https://gerrit.sqlalchemy.org/1285

**Comment by zzzeek** [comment] 2019-05-29 18:46
so, that added 30K calls to the build_query test.   I might need to still scale this back to do the `__getattribute__` thing, but at least we can document more clearly what's going on.

**Comment by zzzeek** [comment] 2019-05-29 22:22
@dima-starosud everything is passing now.  Are you OK with the above change to test_meta_getattr_three ?

**Comment by dima-starosud** [comment] 2019-05-30 09:37
@zzzeek 
I agree with changes to `test_meta_getattr_three` - I definitielly don't want `__getattr__` returning plain descriptor.
As I understand you did everything for me in scope of this task? So, I don't have to do additional investigations?

**Comment by zzzeek** [comment] 2019-05-30 17:07
yes, sorry this was not a simple change but you did write the tests which I am grateful for

**Comment by sqla-tester** [comment] 2019-05-30 17:08
**Dmytro Starosud** has proposed a fix for this issue in the **rel_1_3** branch:

**Rework AliasedClass __getattr__ to use top-level getattr()** https://gerrit.sqlalchemy.org/1292

**Comment by zzzeek** [comment] 2019-05-30 17:08
once that passes I will merge both

**Comment by dima-starosud** [comment] 2019-05-30 18:37
Thanks a lot @zzzeek for your job!
But how that works without unwrapping? Did you fix `adapt_to_entity`?

**Comment by zzzeek** [comment] 2019-05-31 00:48
so it unwraps if the result is  a method, e.g. like a @hybrid_method, and in that case returns a new method. otherwise, it unwraps if it's a descriptor by using the `__get__()` method, for this to work in all cases I had to make an adjustment to the `Proxy` descriptor such that it tries to treat its proxied descriptor as a "class level" descriptor, the way a hybrid does, and then checks it it's i fact a regular `@property` which does not.    That seemed to be the main missing piece.  Then it does the adapt_to_entity() that's there now, if it's present.

**Comment by zzzeek** [comment] 2019-05-31 00:49
I kind of bet this is going to cause a regression for someone too.  but that will give us some more test cases to add and we'll fix that too.

**Closed** 2019-05-31 00:50 UTC
Labels: novel use case, orm

**Comment by dima-starosud** [comment] 2019-05-31 09:50
Thanks a lot @zzzeek for assistance and quick fix!
