### ISSUE TITLE
Missing legacy flag when calling `querycontext.ORMSelectCompileState._create_entities_collection` 

### ISSUE THREAD

**Issue by sluipmoord** [sqlalchemy/sqlalchemy#6211] opened 2021-04-07 09:16 UTC
**Describe the bug**
When implementing the the caching_query._do_orm_execute function from the provided examples it calls a function from the loading package  `loading.merge_frozen_result`

I wasn't able to reproduce the error using the examples 

```py
class ORMCache(object):

    """An add-on for an ORM :class:`.Session` optionally loads full results
    from a dogpile cache region.


    """

    def __init__(self, regions):
        self.cache_regions = regions
        self._statement_cache = {}

    def listen_on_session(self, session_factory):
        event.listen(session_factory, "do_orm_execute", self._do_orm_execute)

    def _do_orm_execute(self, orm_context):
        
        for opt in orm_context.user_defined_options:
            if isinstance(opt, RelationshipCache):
                opt = opt._process_orm_context(orm_context)
                if opt is None:
                    continue

            if isinstance(opt, FromCache):
                dogpile_region = self.cache_regions[opt.region]

                our_cache_key = opt._generate_cache_key(
                    orm_context.statement, orm_context.parameters, self
                )

                if opt.ignore_expiration:
                    cached_value = dogpile_region.get(
                        our_cache_key,
                        expiration_time=opt.expiration_time,
                        ignore_expiration=opt.ignore_expiration,
                    )
                else:

                    def createfunc():
                        return orm_context.invoke_statement().freeze()

                    cached_value = dogpile_region.get_or_create(
                        our_cache_key,
                        createfunc,
                        expiration_time=opt.expiration_time,
                    )

                if cached_value is NO_VALUE:
                    # keyerror?   this is bigger than a keyerror...
                    raise KeyError()

                orm_result = loading.merge_frozen_result(
                    orm_context.session,
                    orm_context.statement,
                    cached_value,
                    load=False,
                )
                return orm_result()

        else:
            return None
    

```

**Error**

```
  File ".../src/wlife_service/tasks/imports.py", line 223, in find_provida_member
    .filter(ProvidaMember.provida_member_number == provida_member_number)
  File "../sqlalchemy/lib/sqlalchemy/orm/query.py", line 2782, in one
    return self._iter().one()
  File "../sqlalchemy/lib/sqlalchemy/orm/query.py", line 2823, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "../sqlalchemy/lib/sqlalchemy/orm/session.py", line 1652, in execute
    result = fn(orm_exec_state)
  File "../src/dogpile_caching/caching_query.py", line 83, in _do_orm_execute
    load=False,
  File "../sqlalchemy/lib/sqlalchemy/orm/loading.py", line 204, in merge_frozen_result
    statement

TypeError: _create_entities_collection() missing 1 required positional argument: 'legacy'
```

**Versions.**
 - OS: macOs Big Sur
 - Python: 3.6.2
 - SQLAlchemy: 1.4.6
 - Database: MySql 8
 - DBAPI: -

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-04-07 14:31
looks like we forgot to add a test for merge_frozen_result, the examples reproduce the problem.

99% of the work here is adding a test so thanks for the PR but I need to just push this up w/ a test /cahngelog notes etc.

**Comment by sqla-tester** [comment] 2021-04-07 14:41
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add test support for merge_frozen_result** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2719

**Comment by sluipmoord** [comment] 2021-04-07 15:32
@sqla-tester and @zzzeek looks like https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2719 should fix it.. I knew I should have added a test case because I could not find one specifically

**Closed** 2021-04-07 16:07 UTC
Labels: bug, orm, regression
