### ISSUE TITLE
SYBASE: Get ID of last inserted row returns 0

### ISSUE THREAD

**Issue by snowman2** [sqlalchemy/sqlalchemy#5311] opened 2020-05-06 13:48 UTC
Ref: #5294 - currently driver is deprecated, but may accept patch for now :crossed_fingers: 

**Describe the bug**
When inserting a new row into an IDENTITY column, the ID of the new row incorrectly returns 0 when using ORM.  This also makes it impossible to refresh the model.

This could definitely be something that I am doing wrong, so I will provide as much detail as possible.

**Expected behavior**
It is very important to get the correct ID of the model inserted from the database.

**To Reproduce**

Model definition:
```py
class Table(Base):
    __tablename__ = "mytable"

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True, nullable=True)  # Note: I have tried removing autoincrement
    type = sa.Column(sa.CHAR(4))
    description = sa.Column(sa.VARCHAR(255))
    create_date = sa.Column(sa.DATETIME)
````
Create session:
```py
from datetime import datetime

import pyodbc
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

connect_args = {"autoconnect": True}
creator = pyodbc.connect(
    database=database,
    user=username,
    password=password,
    driver="FreeTDS",
    host=host,
    port=port,
    **connect_args,
)
engine = create_engine(
    "sybase+pyodbc://",
    creator=creator,
    connect_args=connect_args,
)
session = Session(bind=engine)
```
Direct SQL execute works:
```python
session.execute(
    "INSERT INTO mytable (type, description, create_date) "
    f"VALUES ('TEST', 'TEST', '{datetime.utcnow().isoformat()}')"
)
print(session.scalar("SELECT @@identity"))
```
```
5436789  # example of number returned
```

Fails using execute with model:
```python
    result = session.execute(
        sa.insert(Table),
        dict(
            type="TEST",
            description="TEST",
            create_date=datetime.utcnow().isoformat(),
        )
    )
    print(result.inserted_primary_key[0])
    print(session.scalar("SELECT @@identity"))
```
```
2020-05-06 08:22:44,456 INFO sqlalchemy.engine.base.Engine SELECT user_name() as user_name
2020-05-06 08:22:44,460 INFO sqlalchemy.engine.base.Engine ()
2020-05-06 08:22:44,506 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-05-06 08:22:44,507 INFO sqlalchemy.engine.base.Engine ()
2020-05-06 08:22:44,548 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS NVARCHAR(60)) AS anon_1
2020-05-06 08:22:44,551 INFO sqlalchemy.engine.base.Engine ()
2020-05-06 08:22:44,613 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-05-06 08:22:44,617 INFO sqlalchemy.engine.base.Engine INSERT INTO mytable (type, description, create_date) VALUES (?, ?, ?)
2020-05-06 08:22:44,620 INFO sqlalchemy.engine.base.Engine ('TEST', 'TEST', '2020-05-06T13:22:43.923404')
0
2020-05-06 08:22:44,727 INFO sqlalchemy.engine.base.Engine SELECT @@identity
2020-05-06 08:22:44,729 INFO sqlalchemy.engine.base.Engine ()
0
```

Fails using add with model:
```py
    tbl = Table(
        type="TEST",
        description="TEST",
        create_date=datetime.utcnow().isoformat(),
    )
    session.add(tbl)
    session.flush()
    print(tbl.id)
```
```
2020-05-06 08:24:45,736 INFO sqlalchemy.engine.base.Engine SELECT user_name() as user_name
2020-05-06 08:24:45,740 INFO sqlalchemy.engine.base.Engine ()
2020-05-06 08:24:45,789 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-05-06 08:24:45,794 INFO sqlalchemy.engine.base.Engine ()
2020-05-06 08:24:45,839 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS NVARCHAR(60)) AS anon_1
2020-05-06 08:24:45,841 INFO sqlalchemy.engine.base.Engine ()
2020-05-06 08:24:45,901 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-05-06 08:24:45,902 INFO sqlalchemy.engine.base.Engine INSERT INTO mytable (type, description, create_date) VALUES (?, ?, ?)
2020-05-06 08:24:45,903 INFO sqlalchemy.engine.base.Engine ('TEST', 'TEST', '2020-05-06T13:24:45.580975')
0
```

**Versions.**
 - OS: Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
 - Python: 3.7.5
 - SQLAlchemy: 1.3.16
 - Database: sybase (Adaptive Server Enterprise/16.0 SP02)
 - DBAPI: pyodbc

**Comment by snowman2** [comment] 2020-05-06 15:07
Upgraded to master and see this warning (not sure if it is related):
```
/home/snowal/scripts/sqlalchemy/lib/sqlalchemy/sql/base.py:388: SAWarning: Can't validate argument 'implicit_returning'; can't locate any SQLAlchemy dialect named 'implicit'
  % (k, dialect_name)
```

**Comment by snowman2** [comment] 2020-05-06 15:13
Problem still persists on master:
```
Name: SQLAlchemy
Version: 1.4.0b1.dev0
```

**Comment by snowman2** [comment] 2020-05-06 15:39
If I do:
```py
with connector.get_session(verbose=True) as session:
    aoi = Table(
        type="TEST",
        description="TEST",
        create_date=datetime.utcnow().isoformat(),
    )
    session.add(aoi)
    session.commit()
    print(session.scalar("SELECT @@identity"))
    session.flush()
    print(aoi.id)
```
```
2020-05-06 10:34:33,656 INFO sqlalchemy.engine.Engine SELECT user_name() as user_name
2020-05-06 10:34:33,663 INFO sqlalchemy.engine.Engine ()
2020-05-06 10:34:33,710 INFO sqlalchemy.engine.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS "'test plain returns'"
2020-05-06 10:34:33,713 INFO sqlalchemy.engine.Engine ()
2020-05-06 10:34:33,755 INFO sqlalchemy.engine.Engine SELECT CAST('test unicode returns' AS NVARCHAR(60)) AS "'test unicode returns'"
2020-05-06 10:34:33,756 INFO sqlalchemy.engine.Engine ()
2020-05-06 10:34:33,831 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2020-05-06 10:34:33,833 INFO sqlalchemy.engine.Engine INSERT INTO area_of_interest (aoi_type, aoi_description, grouper, actual_type, create_date) VALUES (?, ?, ?, ?, ?)
2020-05-06 10:34:33,834 INFO sqlalchemy.engine.Engine ('TEST', 'TEST', ' ', ' ', '2020-05-06T15:34:33.494653')
2020-05-06 10:34:33,938 INFO sqlalchemy.engine.Engine COMMIT
2020-05-06 10:34:33,982 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2020-05-06 10:34:33,988 INFO sqlalchemy.engine.Engine SELECT @@identity
2020-05-06 10:34:33,992 INFO sqlalchemy.engine.Engine ()
0
2020-05-06 10:34:34,043 INFO sqlalchemy.engine.Engine SELECT mytable.id AS mytable_id, mytable.type AS mytable_type, mytable.description AS mytable_description, mytable.create_date AS mytable_create_date 
FROM mytable 
WHERE mytable.id = ?
2020-05-06 10:34:34,045 INFO sqlalchemy.engine.Engine (Decimal('0'),)
---------------------------------------------------------------------------
ObjectDeletedError                        Traceback (most recent call last)
<ipython-input-6-1956cb1a6f7c> in <module>
     11     print(session.scalar("SELECT @@identity"))
     12     session.flush()
---> 13     print(aoi.id)
~/scripts/sqlalchemy/lib/sqlalchemy/orm/attributes.py in __get__(self, instance, owner)
    291             return dict_[self.key]
    292         else:
--> 293             return self.impl.get(instance_state(instance), dict_)
    294 
    295 

~/scripts/sqlalchemy/lib/sqlalchemy/orm/attributes.py in get(self, state, dict_, passive)
    713                     and key in state.expired_attributes
    714                 ):
--> 715                     value = state._load_expired(state, passive)
    716                 elif key in state.callables:
    717                     callable_ = state.callables[key]

~/scripts/sqlalchemy/lib/sqlalchemy/orm/state.py in _load_expired(self, state, passive)
    665         )
    666 
--> 667         self.manager.expired_attribute_loader(self, toload, passive)
    668 
    669         # if the loader failed, or this

~/scripts/sqlalchemy/lib/sqlalchemy/orm/loading.py in load_scalar_attributes(mapper, state, attribute_names, passive)
   1110     # may not complete (even if PK attributes are assigned)
   1111     if has_key and result is None:
-> 1112         raise orm_exc.ObjectDeletedError(state)

ObjectDeletedError: Instance '<AreaOfInterest at 0x7f92efef1890>' has been deleted, or its row is otherwise not present.
```

**Comment by CaselIT** [comment] 2020-05-06 18:46
The problem is quite strange.
The sql emitted is the same as the sql string that works, so from the logs it should be working.
The only difference I can see, it that it is parametric.

Does it work if you execute a parametric sql using the pyodbc cursor directly?

**Comment by snowman2** [comment] 2020-05-06 19:11
Looks like it does not work:
```python
cnxn = connector.connect()
cursor = cnxn.cursor()
cursor.execute("INSERT INTO mytable (type, description, create_date) VALUES (?, ?, ?)", 'TEST', 'TEST', '2020-05-06T13:22:43.923404')
cursor.execute("SELECT @@identity AS lastrowid")
print(cursor.fetchone()[0])
```
```
0
```

**Comment by snowman2** [comment] 2020-05-06 19:13
But this does work:
```
cnxn = connector.connect()
cursor = cnxn.cursor()
cursor.execute(
    "INSERT INTO mytable (type, description, create_date) "
    f"VALUES ('TEST', 'TEST', '{datetime.utcnow().isoformat()}')
)
cursor.execute("SELECT @@identity AS lastrowid")
print(cursor.fetchone()[0])
```
This returns a large number ...

**Comment by snowman2** [comment] 2020-05-06 19:17
Sounds like something I should raise upstream. Thanks @CaselIT!

**Comment by CaselIT** [comment] 2020-05-06 19:29
I believe that as a workaround you can use the the [core events](https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.ConnectionEvents) to embed the arguments in the sql string.

You may also make use of the  literal compile argument and manually compile the query. 
I don't think there is a way to tell sqlalchemy to embed all the argument

**Comment by snowman2** [comment] 2020-05-06 19:40
> I believe that as a workaround you can use the the core events to embed the arguments in the sql string.

Interesting. Is there a recommended method for doing so or an internal sqlalchemy method that does this?

**Comment by CaselIT** [comment] 2020-05-06 19:42
I'm not sure, let's ping @zzzeek

**Comment by zzzeek** [comment] 2020-05-06 20:03
embedding the arguments first and foremost is something you need to be **very careful** with. if you cannot trust this input, then it needs to be quoted correctly.     

As far as rendering that way, the compiler includes an option where it can embed the bound values directly in the statement, but only for a small set of datatypes, and additionally there is not a straightforward hook that can easily enable this flag for the compiler when invoking statements; it also involves having access to the parameter dictionary and finally the ORM will often make use of "executemany()" which by nature requires the use of bound parameters, so this would have to be worked around also.

Since you need to work around not just the parameters but also the "executemany" issue, you probably need to reimplement the do_execute() and do_executemany() behaviors of the dialect which can be achieved using the events described at :

https://docs.sqlalchemy.org/en/13/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_execute
https://docs.sqlalchemy.org/en/13/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_executemany

set these events with "retval=True", then return True from your handler, to indicate that you've run the cursor.execute() yourself:

```
@event.listens_for(engine, "do_execute", retval=True)
def receive_do_execute(cursor, statement, parameters, context):
    statement = statement.replace("?", "%s") % (safe_string(param) for param in parameters)
    cursor.execute(statement)
    return True
 

```

**Comment by snowman2** [comment] 2020-05-06 20:25
Thanks for the tips. The data will go through schema validation beforehand, so it should be relatively safe.

This seems to do the trick for now:
```python
from sqlalchemy.engine import Engine
from sqlalchemy import event

def safe_string(param):
    if isinstance(param, str):
        return f"'{param}'"
    return param

@event.listens_for(Engine, "do_execute", retval=True)
def receive_do_execute(cursor, statement, parameters, context):
    statement = statement.replace("?", "{}").format(
        *(safe_string(param) for param in parameters)
    )
    cursor.execute(statement)
    return True
```

Note: I didn't find `safe_string` anywhere, so I made one up based on what I thought it needed to do. If there is an actual method for that, please let me know.

**Comment by zzzeek** [comment] 2020-05-06 20:50
I purposely didn't give you one so that you would be responsible for it :)

however, may I recommend you do it like this:

    param = param.replace("'", "''")
    return f"'{param}'"

**Comment by snowman2** [comment] 2020-06-08 14:27
Based on responses:
- https://github.com/mkleehammer/pyodbc/issues/757
- https://github.com/FreeTDS/freetds/issues/337

It seems like this is behaving as expected and is not a bug. As such, I believe a solution can exists within the sybase driver.

**Comment by CaselIT** [comment] 2020-06-08 14:34
Since @gordthompson is now maintaining the external dialect at https://github.com/gordthompson/sqlalchemy-sybase, I think it would be best to move it there?

**Comment by snowman2** [comment] 2020-06-08 14:38
> I think it would be best to move it there?

Does this mean no more sybase bugfixes will be accepted?

**Comment by snowman2** [comment] 2020-06-08 14:57
I am hoping to get this bugfix in the main `sqlalchemy` repo for now :crossed_fingers:. I have a working version [here](https://github.com/corteva/sqlalchemy/commit/fd858749cbeadfc78cfcb3ded3b36bdd9fd06212). If you would like to see a PR in sqlalchemy, just let me know and I would be happy to do so. I am not sure how to add tests for the change, so I would need pointers for how you would like to see that.

However, if `sqlalchemy` is no longer accepting bugfixes for sybase, just let me know and I will move this and future bugfixes to the external repo.

**Comment by CaselIT** [comment] 2020-06-08 18:30
> 
> 
> > I think it would be best to move it there?
> 
> Does this mean no more sybase bugfixes will be accepted?

I think it would be better to add new features or fixes to the external dialect, but I'm fine either way. Let's wait for gord :)

**Comment by gordthompson** [comment] 2020-06-08 21:21
PR merged into external dialect. [Version 1.0.3](https://github.com/gordthompson/sqlalchemy-sybase/releases/tag/1.0.3) released.

Thanks again, @snowman2 !

**Closed by gordthompson** 2020-06-08 21:21 UTC
Labels: question, sybase
