### ISSUE TITLE
catch for str() in column proxy is not catching unsupported custom SQL constructs

### ISSUE THREAD

**Issue by kaijm** [sqlalchemy/sqlalchemy#5836] opened 2021-01-13 09:04 UTC
**Describe the bug**
We have update to sqlalchemy version 1.3.22 but now a custom compile function doesn't work anymore. Before it worked fine in 1.2.14.

I already debugged the issue and it seems while compiling the custom function, the dialect and/or bind get's lost and therefore sqlalchemy falls back to the default SQL string compiler which cannot compile the function (by purpose on my side).

**Expected behavior**
The custom compile function should work again.

```sql
SELECT anon_1."TableA_create_date" AS "anon_1_TableA_create_date", anon_1."TableA_create_time" AS "anon_1_TableA_create_time", anon_1."TableA_id" AS "anon_1_TableA_id", anon_1.create_timestamp AS anon_1_create_timestamp, "MappingTable_1".id AS "MappingTable_1_id", "MappingTable_1".value_a AS "MappingTable_1_value_a", "MappingTable_1".value_b AS "MappingTable_1_value_b" 
FROM (SELECT "TableA".create_date AS "TableA_create_date", "TableA".create_time AS "TableA_create_time", "TableA".id AS "TableA_id", datetime("TableA".create_date, "TableA".create_time) AS create_timestamp 
FROM "TableA" JOIN "MappingTable" ON "TableA".id = "MappingTable".value_a JOIN "TableB" ON "TableB".id = "MappingTable".value_b 
WHERE "TableB".base_value = ? AND "MappingTable".value_b = ? ORDER BY create_timestamp DESC
 LIMIT ? OFFSET ?) AS anon_1 LEFT OUTER JOIN "MappingTable" AS "MappingTable_1" ON anon_1."TableA_id" = "MappingTable_1".value_a ORDER BY anon_1.create_timestamp DESC
```

**To Reproduce**
```py
# pylint: disable=no-member

from datetime import datetime

import pytz

from sqlalchemy.engine import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Date, Time, Unicode, ForeignKey, DateTime
from sqlalchemy.sql import expression
from sqlalchemy.orm import sessionmaker, joinedload, relationship
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.ext.compiler import compiles


Base = declarative_base()


class BaseTable(Base):
    __tablename__ = "BaseTable"

    id = Column(Integer, primary_key=True,)


class TableA(Base):
    __tablename__ = "TableA"

    id = Column(Integer, unique=True, primary_key=True)
    problem_mappings = relationship("MappingTable")

    _create_date = Column("create_date", Date)
    _create_time = Column("create_time", Time)

    @hybrid_property
    def create_time(self):
        return datetime.combine(self._create_date, self._create_time, tzinfo=pytz.UTC)

    @create_time.expression
    def create_time(self):
        return combine_date_time(self._create_date, self._create_time).label(
            "create_timestamp"
        )


class TableB(Base):
    __tablename__ = "TableB"

    id = Column(Integer, primary_key=True)
    base_value = Column(Integer, ForeignKey(BaseTable.id))


class MappingTable(Base):
    __tablename__ = "MappingTable"

    id = Column(Integer, primary_key=True)
    value_a = Column(Integer, ForeignKey(TableA.id))
    value_b = Column(Integer, ForeignKey(TableB.id))


class combine_date_time(expression.FunctionElement):
    name = "datetime"
    type = DateTime()


@compiles(combine_date_time, "sqlite")
def sqlite_combine_date_time(element, compiler, **kw):
    return "datetime(%s)" % compiler.process(element.clauses, **kw)


def main():
    engine = create_engine("sqlite://", echo=True)
    Base.metadata.create_all(engine)
    session = sessionmaker(bind=engine)()

    result = (
        session.query(TableA)
        .join(MappingTable)
        .join(TableB)
        .filter(TableB.base_value == 1, MappingTable.value_b == 1,)
        .order_by(TableA.create_time.desc())
        .limit(50)
        .options(joinedload(TableA.problem_mappings))
    )

    print(result)


if __name__ == "__main__":
    main()
```

**Error**

```
Traceback (most recent call last):
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 89, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'StrSQLCompiler' object has no attribute 'visit_column_element'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 425, in _wrap_existing_dispatch
    return existing_dispatch(element, compiler, **kw)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 93, in _compiler_dispatch
    replace_context=err,
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.StrSQLCompiler object at 0x7f01d84cf8d0> can't render element of type <class 'sqlalchemy.sql.elements.ColumnElement'> (Background on this error at: http://sqlalche.me/e/13/l7de)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "repro.py", line 89, in <module>
    main()
  File "repro.py", line 85, in main
    print(result)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3538, in __str__
    context = self._compile_context()
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 4114, in _compile_context
    context.statement = self._compound_eager_statement(context)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 4180, in _compound_eager_statement
    from_clause, eager_join, eager_join.stop_on
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 621, in splice_joins
    right.onclause = adapter.traverse(right.onclause)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 240, in traverse
    return replacement_traverse(obj, self.__traverse_options__, replace)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 484, in replacement_traverse
    obj = clone(obj, **opts)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 473, in clone
    newelem = replace(elem)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 236, in replace
    e = v.replace(elem)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 848, in replace
    return self._corresponding_column(col, True)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 821, in _corresponding_column
    col, require_embedded=require_embedded
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 560, in corresponding_column
    if self.c.contains_column(column):
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 647, in columns
    self._populate_column_collection()
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 1392, in _populate_column_collection
    for col in self.element.columns._all_columns:
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 647, in columns
    self._populate_column_collection()
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 3903, in _populate_column_collection
    c._make_proxy(self, key=key, name=name, name_is_truncatable=True)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 844, in _make_proxy
    key = str(self)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 491, in __str__
    return str(self.compile())
  File "<string>", line 1, in <lambda>
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 592, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 441, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 486, in __call__
    return fn(element, compiler, **kw)
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 432, in _wrap_existing_dispatch
    from_=uce,
  File "/root/git/feed_test_results/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.CompileError: <class '__main__.combine_date_time'> construct has no default compilation handler.
```

**Versions.**
 - OS: SUSE Linux Enterprise Server 15 SP1
 - Python: 3.7.1
 - SQLAlchemy: 13.22
 - Database: sqlite
 - DBAPI: default sqlite driver of sqlalchemy

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-01-13 18:11
hi there -

your partial code is missing several dependencies that I'm unfamiliar with, utc_time(), UTCDateTime, nor does it illustrate what usage of the custom constuct is failing.   The [MCVE](http://stackoverflow.com/help/mcve) below runs without failure on 1.3 so please provide complete information, thanks!

```python
import datetime

import pytz

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Date
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import Time
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import Session
from sqlalchemy.sql import expression

Base = declarative_base()


class SplittedCreateTimeMixin:
    """Mixin for a splitted create time"""

    _create_date = Column(
        "create_date",
        Date,
        nullable=False,
        # server_default=utc_date()  # don't have this
    )
    _create_time = Column(
        "create_time",
        Time,
        nullable=False,
        # server_default=utc_time()  # don't have this
    )

    @hybrid_property
    def create_time(self):
        """create time property"""
        return datetime.combine(
            self._create_date, self._create_time, tzinfo=pytz.UTC
        )

    @create_time.setter
    def create_time(self, value):
        """create time setter"""
        self._create_date = value.date()
        self._create_time = value.time()

    @create_time.expression
    def create_time(self):
        """create time expression"""
        # use a label to allow the usage in sub-selects
        return combine_date_time(self._create_date, self._create_time).label(
            "create_timestamp"
        )


class A(SplittedCreateTimeMixin, Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)


class combine_date_time(expression.FunctionElement):
    """Concat of date and time."""

    name = "datetime"
    type = DateTime()  # don't have UTCDateTime


@compiles(combine_date_time, "sqlite")
def sqlite_combine_date_time(element, compiler, **kw):
    """sqlite compile of combine_date_time"""

    return "datetime(%s)" % compiler.process(element.clauses, **kw)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)
s = Session(e)

s.query(A.create_time).all()

```

output

```
CREATE TABLE a (
	create_date DATE NOT NULL, 
	create_time TIME NOT NULL, 
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2021-01-13 13:09:04,415 INFO sqlalchemy.engine.base.Engine ()
2021-01-13 13:09:04,415 INFO sqlalchemy.engine.base.Engine COMMIT
2021-01-13 13:09:04,416 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-01-13 13:09:04,416 INFO sqlalchemy.engine.base.Engine SELECT datetime(a.create_date, a.create_time) AS create_timestamp 
FROM a
2021-01-13 13:09:04,416 INFO sqlalchemy.engine.base.Engine ()

```

**Comment by kaijm** [comment] 2021-01-14 07:07
Hello all,

I was no finally able to extract all code which is needed and to simply it in less than 100 lines :-). I updates my initial comment with the new example and error stack.

Best regards, Kai

**Comment by zzzeek** [comment] 2021-01-14 14:28
hey there -
 
this is the error:

   sqlalchemy.exc.CompileError: <class '__main__.combine_date_time'> construct has no default compilation handler.

So this error does mean what it says, and at first we think that because you are saying "print(stmt)" without a dialect specified, that's why it's raising.  in fact that's not the reason in this specific case, but overall, to fix the error, place a default compilation rule on the statement:

```
@compiles(combine_date_time)
@compiles(combine_date_time, "sqlite")
def sqlite_combine_date_time(element, compiler, **kw):
    return "datetime(%s)" % compiler.process(element.clauses, **kw)

```

that's your fix.  **however**, the actual situation is a lot more complex, as evidenced by, "why does it work in 1.2?"    Your Session is bound to a specific engine and the ORM ``Query`` actually will use this engine for stringification even if one calls ``str()``, and that is still working here.   What is going wrong is something in the eager loading work of ``Query`` that is trying to create a column label for your construct, and in order to create that label it seems to be falling back onto the case where it stringifies the construct directly and that's where it's failing, and in fact this is new as of 1.3.19, so next step is to see what change in the SQL expression language has caused this and if it should be treating this case in a different way.    so possible regression, unsure yet.

**Comment by zzzeek** [comment] 2021-01-14 14:32
the change is as of 2303c46087a6a2e49058ae71b

**Comment by kaijm** [comment] 2021-01-14 14:40
Hi,
thanks for the explanation. 
When we started with our application. we didn't specify by purpose a default clause but always related to a dialect. We support two databases and there is just no default. So in reality, combine_date_time has two implementations: one for sqlite and one for SAP HANA. As you can see, I can't choose a default. 
In addition, while creating this example, I played with the code, as far as I can remember removing e.g. the top clause also prevents the error.

Therefore it would be good to know if this is intended or not and if yes, when you support multiple dialects which one should be the default.

Thanks a lot, Kai

**Comment by zzzeek** [comment] 2021-01-14 15:15
I can confirm that this default compilation is absolutely unimportant and it's likely that it's thrown away completely, at least in 1.4.   I'm looking to see how much we can scale back the invocation of this string, but suffice to say if you provide a default compilation handler that returns a conspicuous non-value, you should never see it:

```
@compiles(combine_date_time)
def default_combine_date_time(element, compiler, **kw):
    return "UNUSED"

```

**Comment by zzzeek** [comment] 2021-01-14 15:17
this is the current test case

```python
from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql import expression


class combine_date_time(expression.FunctionElement):
    name = "datetime"
    type = DateTime()


# @compiles(combine_date_time)
# def combine_date_time(element, compiler, **kw):
#    return "DEFINITELY NOT USED"


@compiles(combine_date_time, "sqlite")
def sqlite_combine_date_time(element, compiler, **kw):
    return "datetime(%s)" % compiler.process(element.clauses, **kw)


t1 = Table("t1", MetaData(), Column("q", Integer))

a1 = t1.alias()

stmt = select([combine_date_time(t1.c.q)])
stmt = select([stmt.alias()])

cols = stmt.c


```

**Comment by zzzeek** [comment] 2021-01-14 15:33
So there's a few angles to this at the same time:

1. the bug itself is that we should be catching compilation exception when we call str().  it is currently catching UnsupportedCompilation so I think the compiles extension simply needs to raise the right exception subclas.

2. the fact that we call str() at all is a little bit frivolous but this is not worth changing in 1.3.   in 1.4 it might be, this is how it's used:

```python
from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql import expression
from sqlalchemy.dialects import sqlite
from sqlalchemy import __version__


class combine_date_time(expression.FunctionElement):
    name = "datetime"
    type = DateTime()


@compiles(combine_date_time)
def _combine_date_time(element, compiler, **kw):
    return "DEFINITELY_NOT_USED"


@compiles(combine_date_time, "sqlite")
def sqlite_combine_date_time(element, compiler, **kw):
    return "datetime(%s)" % compiler.process(element.clauses, **kw)


t1 = Table("t1", MetaData(), Column("q", Integer))

stmt = select([combine_date_time(t1.c.q)])

if "1.4" in __version__:
    stmt = stmt.alias()

# if we don't use the stringify, then this label isn't here
print(
    select([stmt.c["DEFINITELY_NOT_USED"]]).compile(dialect=sqlite.dialect())
)

```

but for here we will just address the exception being thrown.

**Comment by sqla-tester** [comment] 2021-01-14 16:30
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use UnsupportedCompilationError for no default compiler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2474

**Comment by sqla-tester** [comment] 2021-01-14 16:30
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use UnsupportedCompilationError for no default compiler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2475

**Closed** 2021-01-14 18:56 UTC
Labels: bug, sql

**Comment by kaijm** [comment] 2021-01-15 06:29
Thanks a lot!
