### ISSUE TITLE
deprecate / remove in 2.0 magic "add order by cols when distinct is used"

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5134] opened 2020-02-04 21:29 UTC
need to emit a 2.0 warning for this, no magic SQL things like this should happen

```
    def distinct(self, *expr):
        r"""Apply a ``DISTINCT`` to the query and return the newly resulting
        ``Query``.


        .. note::

            The :meth:`.distinct` call includes logic that will automatically
            add columns from the ORDER BY of the query to the columns
            clause of the SELECT statement, to satisfy the common need
            of the database backend that ORDER BY columns be part of the
            SELECT list when DISTINCT is used.   These columns *are not*
            added to the list of columns actually fetched by the
            :class:`.Query`, however, so would not affect results.
            The columns are passed through when using the
            :attr:`.Query.statement` accessor, however.

```

**Comment by CaselIT** [comment] 2020-02-04 21:49
Is it this code that should be removed?

https://github.com/sqlalchemy/sqlalchemy/blob/2df647cd7590ae31b542256a5036d2ff49f321aa/lib/sqlalchemy/orm/query.py#L4019-L4022

**Comment by zzzeek** [comment] 2020-02-04 21:53
it is, however, we need to do a deprecation path on it first, meaning, when it changes a query due to the above logic, it has to emit a warning.  then we need tests in test/orm/test_deprecation.py that test it.

this is another tedious one since technically those coulmns might already be present in context.primary_columns and then in that case it should not emit a warning.   if you want to do this one, it's going to be another one with lots of back and forth / nitpicking :)

**Comment by CaselIT** [comment] 2020-02-04 21:59
I may try. 

> this is another tedious one since technically those coulmns might already be present in context.primary_columns and then in that case it should not emit a warning. if you want to do this one, it's going to be another one with lots of back and forth / nitpicking :)

we should check if the return of `expand_column_list_from_order_by ` is not empty, ie it is adding something to `primary_columns `

**Comment by CaselIT** [comment] 2020-02-15 11:03
I'm not sure how the new pattern should be. I've found a couple that work, but I'm not sure what is the best one

Say that I have a query like this
```py
q = sess.query(User).join("addresses").distinct().order_by(desc(Address.email_address))
```

- An alternative is to use `select_entity_from`
```py
q_dist = sess.query(User, Address.email_address).join("addresses").distinct()
q_dist= q_dist.order_by(desc(Address.email_address))
q = sess.query(User).select_entity_from(q_dist)
```
- Another is to use `from_self`
```py
q = (
    sess.query(User, Address.email_address)
    .join("addresses")
    .distinct()
    .order_by(desc(Address.email_address))
    .from_self(User)
)
```

The sql is the same in the both cases
```sql
SELECT anon_1.users_id, anon_1.users_name
FROM (SELECT DISTINCT users.id AS users_id, users.name AS users_name, addresses.email_address AS addresses_email_address
FROM users JOIN addresses ON users.id = addresses.user_id ORDER BY addresses.email_address DESC) AS anon_1
```
Both of these cases use a subquery, while the current solution does not.

- There is third case that seems to work, using `with_entities`
```py
q = (
    sess.query(User, Address.email_address)
    .join("addresses")
    .distinct()
    .order_by(desc(Address.email_address))
    .with_entities(User)
)
```

This uses the same sql as the current "magic":
```sql
SELECT DISTINCT users.id, users.name, addresses.email_address
FROM users JOIN addresses ON users.id = addresses.user_id ORDER BY addresses.email_address DESC
```

My guess is that the new way of doing this should be `with_entities`, but probably its documentation should be changed, since at first I discarded it, since it seems to imply that it changes the column selected, while it does now. This is the documentation: https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=query#sqlalchemy.orm.query.Query.with_entities

> Return a new Query replacing the SELECT list with the given entities.

@zzzeek could you provide some guidance?

**Comment by sqla-tester** [comment] 2020-02-15 11:46
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Deprecate add of columns in order by with distinct** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1724

**Comment by zzzeek** [comment] 2020-02-15 18:09
my immediate thought is that this whole pattern is not really a thing people should want to do:

   query(User).distinct()

if you are using distinct() you really should be listing out individual columns.     it's never a good idea to DISTINCT on a whole table like that and it doesn't actually make any sense, because each User has a unique primary key so you get nothing special above.

next is with the join:

   query(User).join(User.addresses).distinct()

again, User and Address rows here both have primary keys.   The query makes no sense.

The only kind of query that makes sense is if you are querying for a set of columns that otherwise have duplicates.   one should really be writing them out in the SELECT list, and then if you want to ORDER BY, do that too.   The goal in SQLAlchemy 2.0 is to make the rules of construction the same as that of SQL.  so if i wanted distinct name/email address pairs ordered by email address (2.0 style):

   stmt = select(User.name, Address.email_address).distinct().order_by(Address.email_address)
  rows = session.execute(stmt).all()

then if i only want the "name":

   rows = session.execute(stmt).columns(User.name).all()
   rows = session.execute(stmt)[0].all()
   rows = session.execute(stmt).scalars().all()

that is, this has to do with what we are fetching *after* the statement is executed.  it happens after the execute() call and is at the result-interpretation level.

this is at the core of why I'm adding this execute() phase that everyone is going to complain about.   it's for clarity.

**Comment by CaselIT** [comment] 2020-02-15 18:40
This makes a lot of sense for v2.
But I'm not sure how it's achievable while keeping the current implementation of the query. I mean that the current version would return `User` objects, with the new v2 example would return tuples.

I guess something like this would be needed:
```py
users = session.execute(stmt).entitis(User).all()
```
to specify that from the selected columns I only want to return `User` objects. This would avoid the current alternative of creating a subquery.

Am I on the right track?

**Comment by zzzeek** [comment] 2020-02-15 19:16
the plan in 1.x is that the behavior just remains with a warning.   in 1.4 they can start using sqlalchemy.orm.future for the new behavior.

**Comment by CaselIT** [comment] 2020-02-15 19:26
I forgot about the `future` package. It makes sense.

I'll update the tests in the gerrit changeset to use the from_self sintax for now. Or should this wait until the future package is added?

**Comment by zzzeek** [comment] 2020-02-15 19:27
well we want to emit the "Removedin20" warning thing, so I'd want to build on that.  as far as building the "future" pattern, that's many more weeks down the road and i dont think it impacts what we are testing here.

**Comment by CaselIT** [comment] 2020-02-15 19:31
I'm not sure how to refactor the tests that raise the new warning so that they do not raise it anymore. I've updated all but one in the gerrit changeset if you want to take a look

**Comment by zzzeek** [comment] 2020-02-15 19:36
so it should not raise a warning if I do this:

    q = s.query(User.name, Address.email_address).distinct().order_by(Address.email_address)

that is, the warning needs to be based on the fact that the column was actually implicitly added, if that makes sense.

**Comment by CaselIT** [comment] 2020-02-15 19:51
Yes, that query would not warn. But I would like to make it return a list of users so that the rest of the test does not need to change.
I'm using `.from_self(User)` for this, but I'm not sure if it's the best solution. Maybe we should change the whole test?

**Comment by zzzeek** [comment] 2020-02-15 21:11
well the most 2.0-ish way would be an interpretation of row, "[user for user, address in query]".

**Comment by CaselIT** [comment] 2020-02-15 21:16
The users would need to be manually deduplicated, since multiple copies are returned if some have more than one address.

I guess I could modify the tests to do this

**Comment by CaselIT** [comment] 2020-02-18 07:00
I'll update the code to use the sa2 deprecation

**Comment by CaselIT** [comment] 2020-02-19 19:22
I've updated the code to use sa2 deprecation.

I'm not sure how to remove the warning from this test (currently it passes because the sa2 warning are ignored by a filter)
https://github.com/sqlalchemy/sqlalchemy/blob/d030cfed6a87e1cccd80ef1ef500cd4cb2c1f766/test/orm/test_subquery_relations.py#L1900

The problem is that even if I add `wp.Engineer.primary_language` to the query, the subquery load logic will use the original query as the internal one, so the warning is raised
https://github.com/sqlalchemy/sqlalchemy/blob/615ec3e640373bcb10311ba1d5cfc72e570b6534/lib/sqlalchemy/orm/strategies.py#L1235-L1236

**Comment by zzzeek** [comment] 2020-02-19 19:46
subqueryload is using it.   well, that means subqueryload has to be fixed too.   an unenviable task.    subqueryload is sort of obsolete too which makes it more frustrating.

**Comment by CaselIT** [comment] 2020-02-19 20:14
I'll try to have a look at it. It seems that the entity of the original query is not ported correctly to the outer query. The context primary_keys of the outer query does not have the wp.Engineer.primary_language even if it was added to the orginal query.
Any pointers at what may cause it?

**Comment by zzzeek** [comment] 2020-02-19 21:22
I'd have to read and understand subqueryload  again.  That code falls into this category of code that I can't easily follow later on, which is in itself a bug. 

 I think the approach here should be to port what the Query is doing into the subqueryload strategy itself, that is, you can take those lines of code that say "context.primary_columns += sql_util.expand_column_list_from_order_by(...)" and port them to where subqueryload is builidng up that query.

**Comment by CaselIT** [comment] 2020-02-19 22:17
Thanks, I'll try that.

I've added between the points for tomorrow meeting the deprecation of subqueryload, since it advised against everywhere

**Comment by CaselIT** [comment] 2020-02-23 13:24
Ok I should have fixed the subqueryload warning, by adding the logic to add the order by columns, so that the one in the query does not executes.

I think it should be done

**Closed** 2020-03-25 15:37 UTC
Labels: alchemy 2, bug, orm
