### ISSUE TITLE
Error while using automap: nvarchar and ntext are incompatible

### ISSUE THREAD

**Issue by chaplin89** [sqlalchemy/sqlalchemy#4745] opened 2019-06-28 10:50 UTC
Environment:
- SQLAlchemy==1.3.5
- Windows 10
- Python 3.7
- Driver = SQL Server
- mssql+pyodbc

This is not an issue with sqlalchemy but rather with pyodbc (I guess). 
I'm writing this here because I want a feedback from you before opening the issue into pyodbc.

I'm trying to use the automap feature of sqlalchemy.
After calling `Base.prepare(db, reflect=True)` sqlalchemy crashes with the following exception:

> pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The data types nvarchar and ntext are incompatible in the equal to operator. (402) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. (8180)')

The incriminated query is at line 2419 of sqlalchemy\dialects\mssql\base.py:

```sql
select ind.index_id, ind.is_unique, ind.name
from sys.indexes as ind join sys.tables as tab on
ind.object_id=tab.object_id
join sys.schemas as sch on sch.schema_id=tab.schema_id
where tab.name = :tabname
and sch.name= :schname
and ind.is_primary_key=0 and ind.type != 0
```

After digging a little bit, I was able to reproduce the issue in pyodbc:
```python
import pyodbc
CONNECTION_STRING_TEMPLATE = 'DRIVER={DRIVER};Server={SERVER};Database={DATABASE};Integrated Security=True;'  

connection_string = CONNECTION_STRING_TEMPLATE.format(SERVER = 'servername', DATABASE = 'dbname', DRIVER = '{SQL Server}') 

connection = pyodbc.connect(connection_string) 
query = """\
   select ind.index_id, ind.is_unique, ind.name 
   from sys.indexes as ind 
   join sys.tables as tab 
      on ind.object_id=tab.object_id 
   join sys.schemas as sch 
       on sch.schema_id=tab.schema_id 
   where tab.name = ? 
   and sch.name = ? 
   and ind.is_primary_key=0 
   and ind.type != 0
"""
cursor.execute(query, ('AAAAAAAAAAAAAAA', 'dbo')) 
```

For some reason if tab.name is more than 16 chars, is treated like ntext by pyodbc. If it's less is treated like nvarchar.

The problem can be solved in sqlalchemy changing the query above into this:
```sql
select ind.index_id, ind.is_unique, ind.name
from sys.indexes as ind join sys.tables as tab on 
ind.object_id=tab.object_id
join sys.schemas as sch on sch.schema_id=tab.schema_id
where tab.name = convert(nvarchar(max), :tabname)
and sch.name= convert(nvarchar(max), :schname)
and ind.is_primary_key=0 and ind.type != 0
```

Hence forcing the conversion to nvarchar.

I don't know if this is acceptable as I have literally zero clues about pyodbc is doing this (and if it's an acceptable behavior or not from the pyodbc)

**Comment by zzzeek** [comment] 2019-06-28 14:27
Hi there -

very well known problem with SQL Server and I don't know that pyodbc is going to help here.

I'm not able to reproduce so missing from your bug report is exact pyodbc version in use, ODBC driver in use, and version of SQL Server in use as well as if it's some special cloud edition or whatever.   

Likely patch which I can commit, though again I can't reproduce the bug locally, is to use the coercing datatype:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index 99abba2c6d..b6f15bec38 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2426,8 +2426,8 @@ class MSDialect(default.DefaultDialect):
                 "and ind.is_primary_key=0 and ind.type != 0"
             )
             .bindparams(
-                sql.bindparam("tabname", tablename, sqltypes.String()),
-                sql.bindparam("schname", owner, sqltypes.String()),
+                sql.bindparam("tabname", tablename, ischema.CoerceUnicode()),
+                sql.bindparam("schname", owner, ischema.CoerceUnicode()),
             )
             .columns(name=sqltypes.Unicode())
         )

```

can you please try the above patch and let me know if it solves your problem, along with all the detailed version info of all drivers / databases ?  thanks

**Comment by zzzeek** [comment] 2019-06-28 14:31
so yeah I'm on the linux version of SQL Server these days and it looks like my environment can't reproduce the NTEXT/NVARCHAR issue anywhere there, however, this was definitely a huge problem back when I used different ODBC drivers so it's surprising there is not a coercion on that particular set of parameters.

**Comment by zzzeek** [comment] 2019-06-28 14:33
I missed a few:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index 99abba2c6d..b2bcc280c5 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2426,8 +2426,8 @@ class MSDialect(default.DefaultDialect):
                 "and ind.is_primary_key=0 and ind.type != 0"
             )
             .bindparams(
-                sql.bindparam("tabname", tablename, sqltypes.String()),
-                sql.bindparam("schname", owner, sqltypes.String()),
+                sql.bindparam("tabname", tablename, ischema.CoerceUnicode()),
+                sql.bindparam("schname", owner, ischema.CoerceUnicode()),
             )
             .columns(name=sqltypes.Unicode())
         )
@@ -2451,8 +2451,8 @@ class MSDialect(default.DefaultDialect):
                 "and sch.name=:schname"
             )
             .bindparams(
-                sql.bindparam("tabname", tablename, sqltypes.String()),
-                sql.bindparam("schname", owner, sqltypes.String()),
+                sql.bindparam("tabname", tablename, ischema.CoerceUnicode()),
+                sql.bindparam("schname", owner, ischema.CoerceUnicode()),
             )
             .columns(name=sqltypes.Unicode())
         )
@@ -2477,8 +2477,8 @@ class MSDialect(default.DefaultDialect):
                 "views.schema_id=sch.schema_id and "
                 "views.name=:viewname and sch.name=:schname"
             ).bindparams(
-                sql.bindparam("viewname", viewname, sqltypes.String()),
-                sql.bindparam("schname", owner, sqltypes.String()),
+                sql.bindparam("viewname", viewname, ischema.CoerceUnicode()),
+                sql.bindparam("schname", owner, ischema.CoerceUnicode()),
             )
         )
 

```

**Comment by sqla-tester** [comment] 2019-06-28 14:42
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**CAST bind values against SQL Server sys into NVARCHAR** https://gerrit.sqlalchemy.org/1333

**Comment by sqla-tester** [comment] 2019-06-28 15:17
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**CAST bind values against SQL Server sys into NVARCHAR** https://gerrit.sqlalchemy.org/1334

**Comment by zzzeek** [comment] 2019-06-28 17:24
well it's in, since it only makes things better, but still would want to know your versions of everything as it's odd this has not been reported so far

**Closed** 2019-06-28 17:24 UTC
Labels: SQL Server, bug, reflection

**Comment by chaplin89** [comment] 2019-06-28 18:17
I'll tell you version of everything as soon as I turn on the pc. Still I don't get the logic of the commit: aren't ntext and nvarchar both unicode types?

Anyway, I should have mention that this is not an issue with SQL server as if I try the query in SQL studio everything run smoothly.

**Comment by zzzeek** [comment] 2019-06-28 18:41
it has to do with how ODBC works when bound parameters are used with a SQL query, the driver has to specify a datatype so it sees TEXT, then some mysterious aspect of the database decides it can't perform comparisons against a VARCHAR in these cases.  it can only be reproduced using ODBC system calls.
