### ISSUE TITLE
SQLite ORM `datetime` conversion interprets milliseconds as microseconds on reads

### ISSUE THREAD

**Issue by posita** [sqlalchemy/sqlalchemy#7029] opened 2021-09-15 04:03 UTC
### Describe the bug

Reopening #7027 as requested in [@zzzeek's comment](/sqlalchemy/sqlalchemy/issues/7027#issuecomment-919556206), hopefully without ruining his or anyone else's day. (Not sure how that happened. It certainly wasn't my intention.) I'm sad that #7027 was (mis?)interpreted as "combative" or "sarcastic". (I certainly didn't perceive any of that.) I'm also sad that @zzzeek felt that forcibly shutting down discourse was the best option under those circumstances, but this is his rodeo. Finally, I'm sad my attempts to contribute were not valuable here.

Thanks the work and the effort. No hard feelings.

### To Reproduce

```python
# See #7027
```

### Error

See #7027.

### Versions

- OS:
- Python:
- SQLAlchemy:
- Database:
- DBAPI:

Same as #7027.

**Comment by posita** [comment] 2021-09-15 04:14
Without `Decimal`:

``` python
>>> import re
>>> import datetime
>>> DATETIME_RE = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(?:\.(\d+))?")
>>> m = DATETIME_RE.match("2021-09-14 02:44:30.81")  # with fractional component
>>> args = [int(m[i]) for i in range(1, 7)] ; args.append(int(m[7]) * 1000000 // (10 ** len(m[7])) if m[7] else 0)
>>> datetime.datetime(*args)
datetime.datetime(2021, 9, 14, 2, 44, 30, 810000)
>>> _.microsecond
810000
>>> m = DATETIME_RE.match("2021-09-14 02:44:30.8134")  # with fractional component
>>> args = [int(m[i]) for i in range(1, 7)] ; args.append(int(m[7]) * 1000000 // (10 ** len(m[7])) if m[7] else 0)
>>> datetime.datetime(*args)
datetime.datetime(2021, 9, 14, 2, 44, 30, 813400)
>>> _.microsecond
813400
>>> m = DATETIME_RE.match("2021-09-14 02:44:30")  # without fractional component
>>> args = [int(m[i]) for i in range(1, 7)] ; args.append(int(m[7]) * 1000000 // (10 ** len(m[7])) if m[7] else 0)
>>> datetime.datetime(*args)
datetime.datetime(2021, 9, 14, 2, 44, 30)
>>> _.microsecond
0
```

**Comment by CaselIT** [comment] 2021-09-15 05:47
Hi,

I'm not sure what you are proposing we do here. Could you be more specific?.
The default behaviour works correctly when used by itself, and changing it as you propose would be backward incapable for existing database.

As mentioned in the other issue there are multiple solution to make your usage work.

That said probably a flag "use_isoformat" in the sqlite date and datetime types may make sense since we could use `datetime.fromisoformat` on py37+ to parse it back speeding up parsing significantly

**Comment by zzzeek** [comment] 2021-09-15 11:50
> That said probably a flag "use_isoformat" in the sqlite date and datetime types may make sense since we could use `datetime.fromisoformat` on py37+ to parse it back speeding up parsing significantly

+1

**Comment by zzzeek** [comment] 2021-09-15 11:59
> ### Describe the bug
> 
> Reopening #7027 as requested in [@zzzeek's comment](/sqlalchemy/sqlalchemy/issues/7027#issuecomment-919556206), hopefully without ruining his or anyone else's day. (Not sure how that happened. It certainly wasn't my intention.) I'm sad that #7027 was (mis?)interpreted as "combative" or "sarcastic". (I certainly didn't perceive any of that.) I'm also sad that @zzzeek felt that forcibly shutting down discourse was the best option under those circumstances, but this is his rodeo. Finally, I'm sad my attempts to contribute were not valuable here.

the github issue tracker is not the appropriate forum to litigate this aspect of our interaction.  there's lots of other ways / forums / mediums to talk about those things, but not here.  this is why github actually offers a "lock discussion / too heated" dropdown option.  take it offline with your colleagues or whomever.


> 
> Thanks the work and the effort. No hard feelings.

anytime

**Comment by posita** [comment] 2021-09-15 13:02
> the github issue tracker is not the appropriate forum to litigate this aspect of our interaction. there's lots of other ways / forums / mediums to talk about those things, but not here

Honestly, I'm not trying to litigate. I don't understand what when wrong over in #7027, but I'm trying (hence my lead-in on this issue). I'm not aware of any other way to reach you to discuss what you perceived as "combative and sarcastic", but let me know how and where to have that conversation, and I will make time for it. I too prefer to keep bug reports about bugs. (Honestly, that's what I thought we were doing in #7027. Again, not my intention to trigger you.)

**Comment by posita** [comment] 2021-09-15 13:49
> I'm not sure what you are proposing we do here.

Are you referring to [my follow-on comment here](https://github.com/sqlalchemy/sqlalchemy/issues/7029#issuecomment-919684970)? I was responding to a thread in #7027. I added a reference to that comment.

> The default behaviour works correctly when used by itself, and changing it as you propose would be backward incompatible for existing database.
> 
> As mentioned in the other issue there are multiple solution to make your usage work.
> 
> That said probably a flag "use_isoformat" in the sqlite date and datetime types may make sense since we could use `datetime.fromisoformat` on py37+ to parse it back speeding up parsing significantly

Apologies for not following most of this, and, again, apologies for being dense. I don't understand what this means:

> The default behaviour works correctly when used by itself

Are you talking about limiting timestamp creation/manipulation to Python? If so, I guess that works if you don't have any triggers that need to create timestamps that you might want to read back later, and if you're limited to Python as the access layer, I suppose, and probably a host of other constraints.

If your answer is that y'all don't think this is a bug, it's your show.

FWIW, it took me awhile to track this down. Also, there's a lot of material out there on how to deal with fractional seconds in SQLite that nudges one closer to this sharp edge. See, e.g.:

- https://stackoverflow.com/questions/17574784/sqlite-current-timestamp-with-milliseconds
- https://stackoverflow.com/questions/47885011/sqlite-add-milliseconds-to-time
- https://stackoverflow.com/questions/5956215/how-can-i-store-the-current-timestamp-in-sqlite-as-ticks

Maybe prominently clarify that the default behavior is incompatible with ISO 8601 dates?

Again, sorry to ruffle any feathers.

**Comment by posita** [comment] 2021-09-15 13:58
> I'm not sure what you are proposing we do here.

Are you referring to [my follow-on comment here](https://github.com/sqlalchemy/sqlalchemy/issues/7029#issuecomment-919684970)? I was responding to a thread in #7027. I added a reference to that comment.

My understanding of @zzzeek's original comments was:

1. It's hard to fix using the current code
2. It's hard to conceive of a way to fix this in a performant way (not sure how much this matters for SQLite use cases)
3. Fixing it is not backward compatible
4. Fixing it is a low priority

I'm not sure how much weight I'd put on no. 1, unless I'm using that in assessing no. 4. @zzzeek presented some code (which I think was adapted from [`lib/sqlalchemy/processors.py`](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/processors.py)) on how things work today and invited(?) alternatives? I presented one using `Decimal`, which worked against no. 2 (performance). #7020 was shut down before I had an opportunity to present a non-`Decimal` solution. It sounds like y'all got a good mind to handle no. 3. (I don't have any story around that, other than if no one's complained so far, as @zzzeek points out, maybe that's not as big an issue as it sounds? Obviously you'd be able to draw on more experience here than I could.)

> The default behaviour works correctly when used by itself, and changing it as you propose would be backward incompatible for existing database.
> 
> As mentioned in the other issue there are multiple solution to make your usage work.
> 
> That said probably a flag "use_isoformat" in the sqlite date and datetime types may make sense since we could use `datetime.fromisoformat` on py37+ to parse it back speeding up parsing significantly

Apologies for not following most of this, and, again, apologies for being dense. I don't understand what this means:

> The default behaviour works correctly when used by itself

Are you talking about limiting timestamp creation/manipulation to Python? If so, I guess that works if you don't have any triggers that need to create timestamps that you might want to read back later, and if you're limited to Python as the access layer, I suppose, and probably a host of other constraints.

If your answer is that y'all don't think this is a bug, it's your show.

FWIW, it took me awhile to track this down. Also, there's a lot of material out there on how to deal with fractional seconds in SQLite that nudges one closer to this sharp edge. See, e.g.:

- https://stackoverflow.com/questions/17574784/sqlite-current-timestamp-with-milliseconds
- https://stackoverflow.com/questions/47885011/sqlite-add-milliseconds-to-time
- https://stackoverflow.com/questions/5956215/how-can-i-store-the-current-timestamp-in-sqlite-as-ticks

Maybe prominently clarify that the default behavior is incompatible with ISO 8601 dates?

Again, I didn't mean to ruffle any feathers.

**Comment by CaselIT** [comment] 2021-09-15 14:09
> Apologies for not following most of this, and, again, apologies for being dense. I don't understand what this means:
> 
> > The default behaviour works correctly when used by itself

That it works correctly when not using your default that causes problem.

The issue here is that you are trying to use an default value in an incompatible format end complaining it does not work.
Taking your initial example and using a compatible default, everything works as expected.

```py
# test_case.py
from datetime import datetime
from sqlalchemy import Column, DateTime, Integer, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

Base = declarative_base()

class Example(Base):
    __tablename__ = "app_examples"
    id = Column(Integer, primary_key=True)
    created_at = Column(
        DateTime,
        # default=func.STRFTIME("%Y-%m-%d %H:%M:%f", "NOW"),
        default=datetime.utcnow,
        nullable=False,
    )

engine = create_engine("sqlite://", connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base.metadata.create_all(bind=engine)

db = SessionLocal()
job = Example()
db.add(job)
db.commit()
db.refresh(job)

raw_created_at = db.execute("SELECT created_at FROM app_examples").first()[0]
dt_created_at = datetime.fromisoformat(raw_created_at)

assert (
    job.created_at.microsecond == dt_created_at.microsecond
), f"{job.created_at.microsecond!r} µs (from ORM) != {dt_created_at.microsecond!r} µs (from {raw_created_at!r})"
```


> > I'm not sure what you are proposing we do here.
> 
> Are you referring to [my follow-on comment here](https://github.com/sqlalchemy/sqlalchemy/issues/7029#issuecomment-919684970)? I was responding to a thread in #7027. I added a reference to that comment.

That's not a proposal, it's a way of parsing the value, but the issue is not how to write a piece of code that parses '123' as 123000.
You were presented with multiple suggestions on how to change your code to make it work with the current behaviour of sqlalchemy, but a new issue was open, so evidently that was not what you were looking for.
So again what would you want us do?

**Comment by posita** [comment] 2021-09-15 14:19
Like I said, this is your show. Again, I'm sad if my contributions were not valuable to you. I don't know whether you want to close this as `WONTFIX` or `INVALID`, but maybe highlight this sharp edge [here](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#date-and-time-types) so others don't spin their wheels like I did?

**Comment by posita** [comment] 2021-09-15 14:33
@zzzeek, are you down-voting making `fromisoformat` the default, my documentation suggestion, both, or something else? (Apologies for the edits. That probably muddied things. I'm doing my best to follow along.)

**Comment by CaselIT** [comment] 2021-09-15 14:36
>  I'm sad if my contributions were not valuable to you

Sorry but I really can't understand the contributions you are trying to make...

The issue is caused because an incompatible default format was passed to the datetime. I don't think we can detect this in a feasible manner, so if this is the bug, I would judge as hard to fix.
Other than that I don't know what you are proposing.

As suggested in the comment above, adding a flag `use_isoformat` may be something that makes so that we can use `fromisoformat` where available.

**Comment by zzzeek** [comment] 2021-09-15 14:37
i would want to get a general idea of fromisoformat performance just to be aware of it

**Comment by posita** [comment] 2021-09-15 14:48
> That it works correctly when not using your default that causes problem.
> 
> The issue here is that you are trying to use an default value in an incompatible format end complaining it does not work.
> Taking your initial example and using a compatible default, everything works as expected.

Okay, I think I see part of the misunderstanding. I didn't pick that default out of thin air. It's what I found when researching how to get SQLite to expose fractional seconds on its own. (See, e.g., those stack exchange posts I cited.) That approach also appeared reasonable, since it created reasonable-looking timestamps. I was surprised at SQLAlchemy's default interpretation of `"2021-09-14 02:44:30.813"` to mean `"2021-09-14 02:44:30.000813"` and raised that as the issue.

I also think I introduced confusion by using `default` instead of `server_default`, which is what I really intended. Obviously, Python primitives aren't going to help me in that case.

Again, thanks for the work-arounds.

**Comment by CaselIT** [comment] 2021-09-15 15:07
> 
> 
> i would want to get a general idea of fromisoformat performance just to be aware of it

```py
In [1]: import re
   ...: import datetime
   ...: from decimal import Decimal
   ...:
   ...: DATETIME_RE_CURRENT = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(?:\.(\d+))?")
   ...: def current(data):
   ...:     m = DATETIME_RE_CURRENT.match(data)
   ...:     return datetime.datetime(*[int(x) for x in m.groups(0)])
   ...:
   ...: DATETIME_RE_DECIMAL = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(\.\d+)?")
   ...: def with_decimal(data):
   ...:     m = DATETIME_RE_DECIMAL.match(data)  # with fractional component
   ...:     return datetime.datetime(*[int(m[i]) for i in range(1, 7)], int(Decimal(m[7]) * 1000000) if m[7] else 0)
   ...:
   ...: DATETIME_RE_INT = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(?:\.(\d+))?")
   ...: def with_int(data):
   ...:     m = DATETIME_RE_INT.match(data)  # with fractional component
   ...:     return datetime.datetime(*[int(m[i]) for i in range(1, 7)], int(m[7]) * 1000000 // 10 ** len(m[7]) if m[7] else 0)
   ...:
   ...: def with_fromisoformat(data):
   ...:     return datetime.datetime.fromisoformat(data)
   ...:

In [2]: %timeit current("2021-09-14 02:44:30.810")
2.31 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [3]: %timeit with_decimal("2021-09-14 02:44:30.810")
3.46 µs ± 247 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit with_int("2021-09-14 02:44:30.810")
3.03 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]: %timeit with_fromisoformat("2021-09-14 02:44:30.810")
238 ns ± 4.31 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by CaselIT** [comment] 2021-09-15 15:29
I'm not sure changing the current format by default to isoformat parsing would be backward incompatible, since the existing data would be parsed correctly.
The only change would be when default that are not compatible with the current implementation are used, but then again they were not working correctly in any case.

@zzzeek can you think of a case where this change would be incompatible with data already in the db saved by the current default?

**Comment by zzzeek** [comment] 2021-09-15 15:57
is that on windows?   i dont remember Decimal being that fast even when they went to cdecimal.  just the constructor used to be a beast.

**Comment by zzzeek** [comment] 2021-09-15 15:59
we can certainly switch this to isoformat for python 3.7, we just have to make it such that if someone does present either a storage format or a reg, that we then fall back on those.  

id also like to add strptime to the profiling tests there.   many years ago, it was very slow.

**Comment by zzzeek** [comment] 2021-09-15 16:26
all of these functions perform better since python 2, here's some python 2:

```
In [38]: timeit strptime(data)
The slowest run took 8.47 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.1 µs per loop

In [39]: timeit with_decimal(data)
The slowest run took 17.54 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 14.6 µs per loop

In [40]: timeit current(data)
The slowest run took 17.09 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.11 µs per loop
```

here's 3.9

```
In [20]: timeit with_fromisoformat("2021-09-14 02:44:30.810")
175 ns ± 0.14 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [21]:  timeit strptime("2021-09-14 02:44:30.810")
7.07 µs ± 15.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [22]:  timeit current("2021-09-14 02:44:30.810")
1.75 µs ± 7.19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [24]:  timeit with_decimal("2021-09-14 02:44:30.810")
2.41 µs ± 15.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

so it's a new day and we can do whatever now, fromisoformat certainly the best.

**Comment by CaselIT** [comment] 2021-09-15 17:41
I think we could also avoid the c version all together, since I think a python only fallback is fine for 2.7 and 3.6

**Comment by sqla-tester** [comment] 2022-04-03 17:49
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use .fromisoformat() for sqlite datetime, date, time parsing** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3767

**Closed** 2022-04-03 19:20 UTC
Labels: sqlite, datatypes, use case, code review in progress
