### ISSUE TITLE
Empty Array of Enum field fails to be parsed (PSQL ARRAY backend)

### ISSUE THREAD

**Issue by Disruption** [sqlalchemy/sqlalchemy#7590] opened 2022-01-20 10:27 UTC
### Describe the bug

When you have a column being an array of enums, and that column is empty, it incorrectly parses to an array with a single value of an empty string '' instead of parsing to an empty array [], this causes the engine to try and retrieve the enum with value '' which fails and raises an exception.
Offending commit causing this issue seems to be this recent change:
https://github.com/sqlalchemy/sqlalchemy/commit/94afc4f5fc842160468cf7175552125eebf7a510

### To Reproduce

```python
STR:
- Have a table with an id column and an ARRAY(Enum(xxxx)) column
- Create a row in that table with an empty {} set of enums for the ARRAY column
- Try to get that row by id with a simple query. Engine will raise an exception when parsing the row into an object
```

### Error

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src\user\infrastructure\user\sqlalchemy_user_repository.py:98: in get_by_id
    SQLAlchemyUser.query.filter_by(id=user_id, dt_deleted=None)
venv\lib\site-packages\sqlalchemy\orm\query.py:2810: in first
    return self.limit(1)._iter().first()
venv\lib\site-packages\sqlalchemy\engine\result.py:1383: in first
    return self._only_one_row(
venv\lib\site-packages\sqlalchemy\engine\result.py:558: in _only_one_row
    row = onerow(hard_close=True)
venv\lib\site-packages\sqlalchemy\engine\result.py:1271: in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
venv\lib\site-packages\sqlalchemy\engine\result.py:1674: in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
venv\lib\site-packages\sqlalchemy\orm\loading.py:147: in chunks
    fetch = cursor._raw_all_rows()
venv\lib\site-packages\sqlalchemy\engine\result.py:392: in _raw_all_rows
    return [make_row(row) for row in rows]
venv\lib\site-packages\sqlalchemy\engine\result.py:392: in <listcomp>
    return [make_row(row) for row in rows]
venv\lib\site-packages\sqlalchemy\dialects\postgresql\array.py:382: in process
    return super_rp(
venv\lib\site-packages\sqlalchemy\dialects\postgresql\array.py:361: in process
    return self._proc_array(
venv\lib\site-packages\sqlalchemy\dialects\postgresql\array.py:313: in _proc_array
    return collection(itemproc(x) for x in arr)
venv\lib\site-packages\sqlalchemy\dialects\postgresql\array.py:313: in <genexpr>
    return collection(itemproc(x) for x in arr)
venv\lib\site-packages\sqlalchemy\sql\sqltypes.py:1768: in process
    value = self._object_value_for_elem(value)
venv\lib\site-packages\sqlalchemy\sql\sqltypes.py:1659: in _object_value_for_elem
    util.raise_(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def raise_(
        exception, with_traceback=None, replace_context=None, from_=False
    ):
        r"""implement "raise" with cause support.
    
        :param exception: exception to raise
        :param with_traceback: will call exception.with_traceback()
        :param replace_context: an as-yet-unsupported feature.  This is
         an exception object which we are "replacing", e.g., it's our
         "cause" but we don't want it printed.    Basically just what
         ``__suppress_context__`` does but we don't want to suppress
         the enclosing context, if any.  So for now we make it the
         cause.
        :param from\_: the cause.  this actually sets the cause and doesn't
         hope to hide it someday.
    
        """
        if with_traceback is not None:
            exception = exception.with_traceback(with_traceback)
    
        if from_ is not False:
            exception.__cause__ = from_
        elif replace_context is not None:
            # no good solution here, we would like to have the exception
            # have only the context of replace_context.__context__ so that the
            # intermediary exception does not change, but we can't figure
            # that out.
            exception.__cause__ = replace_context
    
        try:
>           raise exception
E           LookupError: '' is not among the defined enum values. Enum name: rolesenum. Possible values: SUPER_ADMIN, ACCOUNT_ADM.., COMPANY_ADM.., ..., USER
```

venv\lib\site-packages\sqlalchemy\util\compat.py:207: LookupError

### Versions

- OS: Docker Image alpine3.13
- Python: 3.9
- SQLAlchemy: 1.4.30 (Issue wasn't present on 1.4.20 we started getting it upon update)
- Database: PSQL 12-6
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

### Additional context

Error unfolding in images with debug for clarity:

First: Process value receives a value of '{}' (empty set) which is correct as this column is empty
![image](https://user-images.githubusercontent.com/7140499/150320134-36091ce7-a3c5-4f1b-b92e-d2beef1a5724.png)

Second (Actual issue), pattern matcher receives the empty set {} and generates as inner value the empty quoted string '':
![image](https://user-images.githubusercontent.com/7140499/150320410-2aa376b1-3f1c-4342-8369-c39d1c84d4a9.png)

Third: This causes us to get an array containing a single item which is the empty string '' being processed
![image](https://user-images.githubusercontent.com/7140499/150320727-8e0b721f-58ee-44c0-bfa8-d84c0e3d4264.png)

Fourth and last: When we iterate throught the elements in the array, we try to lookup for the enum with value empty string '' which fails raising the reported exception
![image](https://user-images.githubusercontent.com/7140499/150320979-e41e58c5-7a40-4649-a2b5-35b7f8026ec8.png)

**Comment by zzzeek** [comment] 2022-01-20 13:26
someone will triage this later but noting this now the *seventeenth* bug with ARRAY of ENUM, so I've made a new label to celebrate the worst datatype we've ever had :)

**Comment by Disruption** [comment] 2022-01-20 13:28
@zzzeek Yaaaay! *cries in spanish* 

From my research I tried to point to the commit I think caused this issue, but I don't think I can help much further, hope the report is enough and saves some pain!

**Comment by CaselIT** [comment] 2022-01-20 13:39
how strange. the new logic should be invoked only if there is a quote in the array, and an empty array should not have it, since it should be reported as `{}`.

**Comment by zzzeek** [comment] 2022-01-20 13:43
we do need to get an MCVE here

**Comment by zzzeek** [comment] 2022-01-20 20:03
the bug is here:     Fixed regression where the change in :ticket:`7148` to repair ENUM handling
    in PostgreSQL broke the use case of an empty ARRAY of ENUM, preventing rows
    that contained an empty array from being handled correctly when fetching
    results.

**Comment by sqla-tester** [comment] 2022-01-20 20:04
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**restore empty list logic to ARRAY of ENUM parsing** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3549

**Comment by sqla-tester** [comment] 2022-01-20 20:05
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**restore empty list logic to ARRAY of ENUM parsing** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3550

**Closed** 2022-01-20 22:41 UTC
Labels: postgresql, regression, array of enums
