### ISSUE TITLE
"CREATE TABLE" statement doesn't provide COLLATE correctly with MySQL

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#5411] opened 2020-06-20 09:22 UTC
**Describe the bug**
The syntax to define a collation and charset when creating a table has to follow the following grammar rule ([relevant documentation](https://dev.mysql.com/doc/refman/8.0/en/charset-table.html)):
```
CREATE TABLE tbl_name (column_list)
    [[DEFAULT] CHARACTER SET charset_name]
    [COLLATE collation_name]]
```

Sqlalchemy seems to not respect the order of CHARACTER SET and COLLATION, resulting in the wrong collation being used for the created table.

**Expected behavior**
I expect Sqlalchemy to emit a CREATE TABLE statement that correctly sets the COLLATION and CHARACTER SET.

**To Reproduce**
The following snippet reproduces the issue, but not consistently. You may need to run this multiple times before it fails on the assertion.
EDIT: See the comment below to get it consistently failing. TL;DR set PYTHONHASHSEED=1.
My guess here is that the compile for the CREATE TABLE statement does not define the order of the "post table parenthesis" options, (like CHARACTER SET, COLLATION, ENGINE, etc.), and the for some reason the order of these options is randomized at every run.

```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base


class _Base(object):
    __table_args__ = {
        "mysql_engine": "InnoDB",
        "mysql_collate": "utf8_unicode_ci",
        "mysql_charset": "utf8",
    }


Base = declarative_base(cls=_Base)


class User(Base):
    __tablename__ = "test_table"
    id = Column(Integer, primary_key=True)


engine = create_engine("mysql://root@localhost:3306/test", echo=True)


engine.execute("DROP TABLE IF EXISTS test_table")

Base.metadata.create_all(engine)

result = engine.execute(
    "select TABLE_COLLATION from information_schema.TABLES where table_name = 'test_table'",
).fetchone()

print(f"Table collation is {result.TABLE_COLLATION}")

# This is the line that breaks. Commenting it will show that changing the order of CHARSET/COLLATE fixes the issue
# In my test, the resulting collation is "utf8_general_ci"
assert result.TABLE_COLLATION == "utf8_unicode_ci"



# Correct statement
engine.execute("DROP TABLE IF EXISTS test_table")
engine.execute(
    """
CREATE TABLE test_table (
    id INTEGER NOT NULL AUTO_INCREMENT, 
    PRIMARY KEY (id)
) CHARSET=utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB 
"""
)

result = engine.execute(
    "select TABLE_COLLATION, ENGINE from information_schema.TABLES where table_name = 'test_table'",
).fetchone()

# As expected
assert result.TABLE_COLLATION == "utf8_unicode_ci"


```

**Error**

```
/tmp/sqlalchemybug/env/bin/python /tmp/sqlalchemybug/test_bug.py
2020-06-20 11:18:15,850 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2020-06-20 11:18:15,850 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,851 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2020-06-20 11:18:15,851 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,852 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2020-06-20 11:18:15,852 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,852 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
2020-06-20 11:18:15,852 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,854 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2020-06-20 11:18:15,854 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,854 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2020-06-20 11:18:15,854 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,855 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
2020-06-20 11:18:15,855 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,856 INFO sqlalchemy.engine.base.Engine DROP TABLE IF EXISTS test_table
2020-06-20 11:18:15,856 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,859 INFO sqlalchemy.engine.base.Engine COMMIT
2020-06-20 11:18:15,860 INFO sqlalchemy.engine.base.Engine DESCRIBE `test_table`
2020-06-20 11:18:15,860 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,863 INFO sqlalchemy.engine.base.Engine ROLLBACK
2020-06-20 11:18:15,863 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE test_table (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY (id)
)COLLATE utf8_unicode_ci ENGINE=InnoDB CHARSET=utf8


2020-06-20 11:18:15,863 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:18:15,875 INFO sqlalchemy.engine.base.Engine COMMIT
2020-06-20 11:18:15,876 INFO sqlalchemy.engine.base.Engine select TABLE_COLLATION from information_schema.TABLES where table_name = 'test_table'
2020-06-20 11:18:15,876 INFO sqlalchemy.engine.base.Engine ()
Table collation is utf8_general_ci
Traceback (most recent call last):
  File "/tmp/sqlalchemybug/test_bug.py", line 36, in <module>
    assert result.TABLE_COLLATION == "utf8_unicode_ci"
AssertionError

```

**Versions.**
 - OS: Mac OS 10.15 (but tested also on Ubuntu Bionic)
 - Python: 3.6.9
 - SQLAlchemy: 1.3.17
 - Database: MySQL 5.6.47
 - DBAPI: mysqlclient 1.4.6

**Have a nice day!**

**Comment by youtux** [comment] 2020-06-20 09:35
The fact that the script sometimes reproduces the issue and some times not is likely due to [hash randomization](https://docs.python.org/3/reference/datamodel.html#object.__hash__) of the python interpreter.
Using a PYTHONHASHSEED=0 makes the script always succeed; using PYTHONHASHSEED=1 makes it always fail:
```
$ PYTHONHASHSEED=1 python test_bug.py
2020-06-20 11:33:56,128 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2020-06-20 11:33:56,128 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,129 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2020-06-20 11:33:56,129 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,130 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2020-06-20 11:33:56,130 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,131 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
2020-06-20 11:33:56,131 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,132 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2020-06-20 11:33:56,132 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,132 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2020-06-20 11:33:56,132 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,133 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
2020-06-20 11:33:56,133 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,134 INFO sqlalchemy.engine.base.Engine DROP TABLE IF EXISTS test_table
2020-06-20 11:33:56,134 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,138 INFO sqlalchemy.engine.base.Engine COMMIT
2020-06-20 11:33:56,138 INFO sqlalchemy.engine.base.Engine DESCRIBE `test_table`
2020-06-20 11:33:56,138 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,140 INFO sqlalchemy.engine.base.Engine ROLLBACK
2020-06-20 11:33:56,141 INFO sqlalchemy.engine.base.Engine
CREATE TABLE test_table (
	id INTEGER NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
)COLLATE utf8_unicode_ci CHARSET=utf8 ENGINE=InnoDB


2020-06-20 11:33:56,141 INFO sqlalchemy.engine.base.Engine ()
2020-06-20 11:33:56,157 INFO sqlalchemy.engine.base.Engine COMMIT
2020-06-20 11:33:56,157 INFO sqlalchemy.engine.base.Engine select TABLE_COLLATION from information_schema.TABLES where table_name = 'test_table'
2020-06-20 11:33:56,157 INFO sqlalchemy.engine.base.Engine ()
Table collation is utf8_general_ci
Traceback (most recent call last):
  File "test_bug.py", line 36, in <module>
    assert result.TABLE_COLLATION == "utf8_unicode_ci"
AssertionError
```

**Comment by zzzeek** [comment] 2020-06-20 18:11
im not sure COLLATE works on mariadb at all.  trying mysql

**Comment by zzzeek** [comment] 2020-06-20 18:12
also, please confirm you are using either python 2 or an older 3.x version , I think preceding 3.6.  can't reproduce on 3.7

**Comment by zzzeek** [comment] 2020-06-20 18:13
oh i got it, OK

**Comment by zzzeek** [comment] 2020-06-20 18:18
here's the patch, ENGINE does not seem to matter
```

diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index d009d656e..d219918fc 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1697,6 +1697,8 @@ class MySQLDDLCompiler(compiler.DDLCompiler):
             [
                 ("DEFAULT_CHARSET", "COLLATE"),
                 ("DEFAULT_CHARACTER_SET", "COLLATE"),
+                ("CHARSET", "COLLATE"),
+                ("CHARACTER_SET", "COLLATE"),
             ],
             nonpart_options,
         ):

```

needs PR w/ tests or someone will get to it

**Comment by gordthompson** [comment] 2020-06-20 23:16
It does look like CI fiddles with PYTHONHASHSEED before starting the tests:

``` text
py38-cext-sqlite-postgresql run-test-pre: PYTHONHASHSEED='2491140407'
```

I guess we'll have to see if the tests for this particular issue require a specific value in order to pass or fail consistently.

**Comment by youtux** [comment] 2020-08-06 18:37
Any update on this?

**Comment by sqla-tester** [comment] 2020-08-06 23:20
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix mysql CREATE TABLE / COLLATE issue** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2133

**Comment by sqla-tester** [comment] 2020-08-07 12:55
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix mysql CREATE TABLE / COLLATE issue** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2134

**Comment by gordthompson** [comment] 2020-08-09 17:11
Okay, not sure how far down the rabbit hole we want to go with this. My original test — shamelessly cribbed from the repro code above — actually tested that the table was created with the proper collation, not whether the trailing options were rendered in the exact same order every time. That's not particularly important; what *is* important is that the `COLLATE` option appears last:

``` none
mysql> SHOW VARIABLES LIKE 'collation_database';
+--------------------+--------------------+
| Variable_name      | Value              |
+--------------------+--------------------+
| collation_database | utf8mb4_general_ci |
+--------------------+--------------------+
1 row in set (0.00 sec)

mysql> CREATE TABLE test_table (id INT PRIMARY KEY) COLLATE utf8_icelandic_ci ENGINE=InnoDB CHARSET=utf8;
Query OK, 0 rows affected (0.14 sec)

mysql> select TABLE_COLLATION, ENGINE from information_schema.TABLES where table_name = 'test_table';
+-----------------+--------+
| TABLE_COLLATION | ENGINE |
+-----------------+--------+
| utf8_general_ci | InnoDB |
+-----------------+--------+
1 row in set (0.00 sec)

mysql> DROP TABLE test_table;
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE test_table (id INT PRIMARY KEY) ENGINE=InnoDB CHARSET=utf8 COLLATE utf8_icelandic_ci;
Query OK, 0 rows affected (0.07 sec)

mysql> select TABLE_COLLATION, ENGINE from information_schema.TABLES where table_name = 'test_table';
+-------------------+--------+
| TABLE_COLLATION   | ENGINE |
+-------------------+--------+
| utf8_icelandic_ci | InnoDB |
+-------------------+--------+
1 row in set (0.01 sec)

mysql> DROP TABLE test_table;
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE test_table (id INT PRIMARY KEY) CHARSET=utf8 ENGINE=InnoDB COLLATE utf8_icelandic_ci;
Query OK, 0 rows affected (0.07 sec)

mysql> select TABLE_COLLATION, ENGINE from information_schema.TABLES where table_name = 'test_table';
+-------------------+--------+
| TABLE_COLLATION   | ENGINE |
+-------------------+--------+
| utf8_icelandic_ci | InnoDB |
+-------------------+--------+
1 row in set (0.00 sec)
```

The current test code fails because sometimes the DDL is rendered as ENGINE/CHARSET/COLLATE and other times it is rendered as CHARSET/ENGINE/COLLATE, and both of those are "correct" in terms of their ultimate effect.

**Comment by zzzeek** [comment] 2020-08-10 13:45
you can always add another dependency tuple like I did above just to get the test to work.

**Comment by gordthompson** [comment] 2020-08-10 14:00
Tried that, but simply adding `("ENGINE", "COLLATE"),` was insufficient, and adding 4 more for `("ENGINE", "CHARSET"),` et al. seemed to be unnecessarily tedious. I just modified the test to check for both variations.

**Comment by zzzeek** [comment] 2020-08-10 14:08
that's fine

**Comment by zzzeek** [comment] 2020-08-12 15:03
mariadb at least seems to actually ignore the collate if the order is wrong.  no error or nothing.   wow

**Comment by zzzeek** [comment] 2020-08-12 15:03
```
MariaDB [test]> create table foo (id varchar(20)) CHARSET=utf8 ENGINE=InnoDB COLLATE utf8_icelandic_ci;
Query OK, 0 rows affected (0.019 sec)

MariaDB [test]> create table bar (id varchar(20)) ENGINE=InnoDB COLLATE utf8_icelandic_ci CHARSET=utf8;
Query OK, 0 rows affected (0.022 sec)

MariaDB [test]> show create table foo;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                  |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| foo   | CREATE TABLE `foo` (
  `id` varchar(20) COLLATE utf8_icelandic_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_icelandic_ci |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.002 sec)

MariaDB [test]> show create table bar;
+-------+-------------------------------------------------------------------------------------------+
| Table | Create Table                                                                              |
+-------+-------------------------------------------------------------------------------------------+
| bar   | CREATE TABLE `bar` (
  `id` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------+-------------------------------------------------------------------------------------------+
1 row in set (0.002 sec)

MariaDB [test]> 

```

**Closed** 2020-08-12 15:04 UTC
Labels: bug, mysql

**Comment by youtux** [comment] 2020-08-12 15:07
Thanks for the fix!

**Comment by demospace** [comment] 2020-09-20 05:37
>mariadb at least seems to actually ignore the collate if the order is wrong. no error or nothing. wow

Yes, I've just run into this behavior. MariaDB will ignore the collation if it doesn't appear last and then pickup the default from the SCHEMA -- ignoring the explicitly provided one if it comes prior to a CHARSET.

For future searchers: this can then break FKs to string fields with further cryptic 105 errors that were difficult to debug in production and pipelines.

For example, the SQL emitted from Alembic migration CreateTable() that reads:
```COLLATE utf8mb4_unicode_ci CHARSET=utf8mb4 ENGINE=InnoDB``` would in my case cause the columns to pick up utf8mb4_general_ci (SCHEMA default) which would then fail on FK creation with mismatched FK definitions.
