### ISSUE TITLE
Why is "None" not a literal "NULL" ?

### ISSUE THREAD

**Issue by jakebrinkmann** [sqlalchemy/sqlalchemy#5888] opened 2021-01-28 17:19 UTC
**Describe your question**

I do not understand how a `None` value for a String column doesn't mean a `NULL` constant in the DB. 

```python
>>> import sqlalchemy as sa

>>> data = {"a": None}
>>> # data = { k: v if v is not None else sa.null() for k,v in data.items() }

>>> table = sa.Table("a", sa.MetaData(),  sa.Column("a", sa.String, nullable=True))
>>> sql = sa.dialects.postgresql.insert(table).values(**data)

>>> print(sql.compile(dialect=sa.dialects.postgresql.dialect(), compile_kwargs={'literal_binds': True}))
# *** sqlalchemy.exc.CompileError: Bind parameter 'a' without a renderable value not allowed here.
```

How am I supposed to print the compiled SQL statement? Notice, I commented out the line that will make this work... but is there some other way to avoid having to transform all my data before I can compile a query?

**Versions**
 - OS: Windows
 - Python: 3.8
 - SQLAlchemy: '1.3.19'
 - Database: postgresql
 - DBAPI: psycopg2 '2.8.6 (dt dec pq3 ext lo64)'

**Additional context**

> NULL is not a value, it's a constant that essentially represents "unknown"

* https://github.com/sqlalchemy/sqlalchemy/issues/4591 
* https://github.com/sqlalchemy/sqlalchemy/issues/5758

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-01-28 19:17
hi there -

The issue you are having is not that it refuses to consider None as "NULL", it considers None to be "nothing was specified" within the context of the BindParameter object.

your test case, specific to DML like insert(), does not reproduce any error in 1.4:

```

>>> import sqlalchemy as sa
>>> from sqlalchemy.dialects import postgresql
>>> 
>>> data = {"a": None}
>>> 
>>> table = sa.Table("a", sa.MetaData(),  sa.Column("a", sa.String, nullable=True))
>>> sql = sa.dialects.postgresql.insert(table).values(**data)
>>> 
>>> print(sql.compile(dialect=sa.dialects.postgresql.dialect(), compile_kwargs={'literal_binds': True}))
INSERT INTO a (a) VALUES (NULL)

```

I'm not completely sure but I have a feeling that Insert() and other DML are not using bindparameter() in the same way in 1.4, the refactor that was done in 851fb8f5a661c66ee763081811 has changed this behavior.   So I have this open as a "bug" because i want to add a test suite for this so that it doesn't change (or check if there already is one that I forgot about).

This still wont change the behavior you're seeing in a generalized way, as the bindparam() construct still refuses to render if you pass None to it:


```
>>> import sqlalchemy as sa
>>> from sqlalchemy.dialects import postgresql
>>> 
>>> table = sa.Table("a", sa.MetaData(),  sa.Column("a", sa.String, nullable=True))
>>> sql = sa.select(table).where(table.c.a == sa.bindparam("x", value=None))
>>> 
>>> print(sql.compile(dialect=sa.dialects.postgresql.dialect(), compile_kwargs={'literal_binds': True}))
sqlalchemy.exc.CompileError: Bind parameter 'x' without a renderable value not allowed here.

```

"None" can't be rendered as a bound value because it isn't generally useful; the above statement would render "SELECT a FROM table WHERE a=NULL" which is wrong from a SQL point of view.    

Essentially there's a difference between a bound value passed as a VALUES / SET type of thing vs. one that's used in an expression.   I'm not sure there's too strong of a wall between these two decisions.   We could make it just print out the bad SQL in this case, and see what happens.  Definitely not for 1.3 though.

**Comment by jakebrinkmann** [comment] 2021-01-28 19:30
Ok, that sounds great, thank you for the insight and I will look forward to using 1.4 once it is flagged as stable.

**Comment by zzzeek** [comment] 2021-01-28 19:44
so can confirm in 1.4 the codepath takes your None in insert.values() and considers it to be a SQL expression immediately.   The 1.3 behavior does seem to be a bug since this None is being passed straight in as an expression, you aren't telling it to make a bound parameter out of it.

**Comment by zzzeek** [comment] 2021-01-28 19:46
in 1.4 I'm going to have these render NULL at all times, and it will detect if the NULL is inside of a comparison expression not using IS/IS NOT; in those cases it will emit a warning.

**Comment by sqla-tester** [comment] 2021-01-28 19:53
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Render NULL for bindparam w/ None value/literal_binds, warn** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2520

**Closed** 2021-01-28 22:19 UTC
Labels: sql, use case
