### ISSUE TITLE
problem with empty list in notin_

### ISSUE THREAD

**Issue by Rogalek** [sqlalchemy/sqlalchemy#6428] opened 2021-05-05 07:02 UTC
Hello,

I have a problem with my query because sometimes one of my variables is an empty list and when this happens my query gave me back all objects in the database.

Query:
```
dbsession.query(User.id)\
        .filter(User.facebook_id.in_(['123123123']))\
        .filter(User.id.notin_([]))
```

on 1.3.20 worked as expected:
```
SELECT users.id AS users_id 
FROM users 
WHERE users.facebook_id IN ('123123123') AND 1 = 1
```

on 1.4.13 produced:
```
SELECT users.id AS users_id 
FROM users 
WHERE users.facebook_id IN ('123123123') AND users.id NOT IN (NULL) OR (1 = 1)
```
and that returned all rows from db, but it should be just one. (I think because of last statement OR (1=1))

Thank you for your help.

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.0
 - SQLAlchemy: 1.4.13
 - Database: postgres

**Comment by CaselIT** [comment] 2021-05-05 07:40
Hi,

This is a regression caused by this fix https://github.com/sqlalchemy/sqlalchemy/commit/aba308868544b21bafa0b3435701ddc908654b0a. @zzzeek I think we will need to make not_in (and also in) to require a parents in all cases

Can you try using ` .filter(User.id.notin_([]).self_group())` to see if it correctly renders a parents?

**Comment by Rogalek** [comment] 2021-05-05 09:33
hello,

query works when I add this `self_group`

**Comment by zzzeek** [comment] 2021-05-05 12:21
I had thought we kind of needed that but i was looking at the IN / AND case where I dont think we do (but we will add it anyway)

**Comment by zzzeek** [comment] 2021-05-05 12:27
this actually kind of sucks because we need to change the SQL surrounding now, it will look crappy

**Comment by CaselIT** [comment] 2021-05-05 12:32
We always change the sql, not only if there is an empty list, I mean this is also correct:
`WHERE users.facebook_id IN ('123123123') AND (users.id NOT IN ('123'))`

**Comment by zzzeek** [comment] 2021-05-05 12:38
yes I know, just lamenting it affected the outer SQL

im doing it just for "NOT IN", I dont think this can impact the "IN" case.

**Comment by sqla-tester** [comment] 2021-05-05 12:39
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Parenthesize for empty not in** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2806

**Comment by CaselIT** [comment] 2021-05-05 12:40
ok.

yes, the `IN` case is not impacted since the `AND` has the highest precedence among the binary conditions

**Closed** 2021-05-05 16:36 UTC
Labels: bug, regression, sql
