### ISSUE TITLE
SQLAlchemy generates invalid query

### ISSUE THREAD

**Issue by StefanosChaliasos** [sqlalchemy/sqlalchemy#5443] opened 2020-07-07 12:58 UTC
**Describe the bug**
When using a labeled field in a query with `join`s and `distinct`, SQLAlchemy generates an `SQL` query with a syntax error.

**To Reproduce**

* Query

```py
from sqlalchemy import (create_engine, desc)
from sqlalchemy.orm import sessionmaker
from models import *


engine = create_engine('sqlite:////home/example.db')
Session = sessionmaker(bind=engine)
session = Session()


col = Table1.price.label('col')
q1 = session.query(Table3.id).select_from(Table3)
q2 = q1.join(Table2, Table3.table2).join(Table1, Table2.table1).distinct().order_by(desc(col))
for r in q2:
    print(r)
```

* Models

```py
from sqlalchemy import Column, ForeignKey, Integer, Numeric, String
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class Table1(Base):
    __tablename__ = 'table1'

    id = Column(Integer, primary_key=True)
    price = Column(Numeric(10, 2))


class Table2(Base):
    __tablename__ = 'table2'

    id = Column(Integer, primary_key=True)
    table1_id = Column(ForeignKey('table1.id', ondelete='CASCADE'))

    table1 = relationship('Table1')


class Table3(Base):
    __tablename__ = 'table3'

    id = Column(Integer, primary_key=True)
    table2_id = Column(ForeignKey('table2.id', ondelete='CASCADE'))

    table2 = relationship('Table2')
```

* SQL script to generate the tables

```sql
DROP TABLE IF EXISTS table1;
DROP TABLE IF EXISTS table2;
DROP TABLE IF EXISTS table3;
CREATE TABLE table1 (
id integer,
price numeric(10, 2),
PRIMARY KEY (id)
);
INSERT INTO table1(id,price) VALUES (1,-7);
INSERT INTO table1(id,price) VALUES (2,6);
INSERT INTO table1(id,price) VALUES (3,3);
INSERT INTO table1(id,price) VALUES (4,7);

CREATE TABLE table2 (
id integer,
table1_id integer,
PRIMARY KEY (id),
FOREIGN KEY (table1_id) REFERENCES table1(id) ON DELETE CASCADE
);
INSERT INTO table2(id,table1_id) VALUES (1,1);
INSERT INTO table2(id,table1_id) VALUES (2,3);
INSERT INTO table2(id,table1_id) VALUES (3,2);
INSERT INTO table2(id,table1_id) VALUES (4,2);

CREATE TABLE table3 (
id integer,
table2_id integer,
PRIMARY KEY (id),
FOREIGN KEY (table2_id) REFERENCES table2(id) ON DELETE CASCADE
);
INSERT INTO table3(id,table2_id) VALUES (1,1);
INSERT INTO table3(id,table2_id) VALUES (2,3);
INSERT INTO table3(id,table2_id) VALUES (3,4);
INSERT INTO table3(id,table2_id) VALUES (4,2);
```

**Error**

```
Traceback (most recent call last):
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1514, in _execute_context
    self.dialect.do_execute(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/default.py", line 592, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DESC": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "driver_sqlite.py", line 14, in <module>
    for r in q2:
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2807, in __iter__
    return self._iter().__iter__()
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2813, in _iter
    result = self.session.execute(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1490, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1328, in _execute_20
    return meth(self, multiparams, params, execution_options)
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 308, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1218, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1558, in _execute_context
    self._handle_dbapi_exception(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1739, in _handle_dbapi_exception
    util.raise_(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/util/compat.py", line 169, in raise_
    raise exception
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1514, in _execute_context
    self.dialect.do_execute(
  File "/home/.env/lib/python3.8/site-packages/SQLAlchemy-1.4.0b1.dev0-py3.8-linux-x86_64.egg/sqlalchemy/engine/default.py", line 592, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DESC": syntax error
[SQL: SELECT DISTINCT table3.id AS table3_id, table1.price AS col DESC
FROM table3 JOIN table2 ON table2.id = table3.table2_id JOIN table1 ON table1.id = table2.table1_id ORDER BY table1.price DESC]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Versions.**
 - SQLAlchemy: 1.4.0b1.dev0
 - Database: sqlite3, mysql, postgresql

**Have a nice day!**

**Comment by zzzeek** [comment] 2020-07-07 14:31
hi there, before I even look I notice you're using 1.4 dev, is this reproducible on 1.3 as well or is this a regression?

**Comment by StefanosChaliasos** [comment] 2020-07-07 14:38
I checked it in version 1.3.18, and it works as expected.

**Comment by zzzeek** [comment] 2020-07-07 14:39
regression in 1.4, OK

**Comment by zzzeek** [comment] 2020-07-07 14:41
OK so this is deprecated behavior in any case, that it adds the column to the columns clause emits a warning here because in 2.0 that part won't happen.   but the logic has to be fixed for now anyway.

**Comment by sqla-tester** [comment] 2020-07-07 15:29
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**ensure we unwrap desc() /label() all the way w/ order by** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2074

**Closed** 2020-07-07 18:58 UTC
Labels: bug, sql
