### ISSUE TITLE
SQLAlchemy 2 casts string columns to their length, even when using ColumnOperators such as `ilike`

### ISSUE THREAD

**Issue by waderoberts123** [sqlalchemy/sqlalchemy#9541] opened 2023-03-24 21:01 UTC
### Describe the bug

After upgrading to SQLAlchemy 2.0, one of our queries broke because in the new version, using the `.ilike()` column operator doesn't do what it used to do. 

We are using database reflection to load the models, but this is the basis of the column definitions:

```python
class Address(Base):
    state = Column(ForeignKey("states.code", ondelete="SET DEFAULT", onupdate="CASCADE"), nullable=False)

class State(Base):
    code = Column(CHAR(2), primary_key=True)
```

If you notice in the code to reproduce section, casting the string to VARCHAR(2) completely changes the where condition of the query.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column.ilike

### SQLAlchemy Version in Use

2.0.7

### DBAPI (i.e. the database driver)

psycopg (async)

### Database Vendor and Major Version

PostgreSQL

### Python Version

3.8

### Operating system

Linux and Windows

### To Reproduce

```python
async def main():
    async with AsyncSession() as session:
        stmt = sa.select(public.Address.street).where(public.Address.state.ilike("%sd%"))
        results = (await session.execute(stmt)).all()
        print(results)

await main()
```

### Error

2023-03-24 14:59:31,632 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-24 14:59:31,664 INFO sqlalchemy.engine.Engine SELECT addresses.street 
FROM addresses 
WHERE addresses.state ILIKE %(state_1)s::VARCHAR(2)
2023-03-24 14:59:31,671 INFO sqlalchemy.engine.Engine [generated in 0.00980s] {'state_1': '%sd%'}
[]
2023-03-24 14:59:31,882 INFO sqlalchemy.engine.Engine ROLLBACK

**Comment by zzzeek** [comment] 2023-03-24 21:08
dupe of #9511, fixed in 2.0.8

**Closed by zzzeek** 2023-03-24 21:08 UTC
Labels: duplicate, postgresql
