### ISSUE TITLE
add SQL values recipe as a feature

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4868] opened 2019-09-29 13:48 UTC
as discussed in #4864, the recipe in https://github.com/sqlalchemy/sqlalchemy/wiki/PGValues would become a feature.   Even though only Postgresql uses it, apparently it is SQL standard (confirm the syntax completely) so it can be in Core.

**Comment by gordthompson** [comment] 2019-11-23 00:09
> Even though only Postgresql uses it, apparently it is SQL standard

My understanding is that Microsoft has put quite a bit of effort into improving ANSI SQL support, so I was curious if such a construct was supported by T-SQL. Apparently, it is:

```
1> SELECT @@VERSION AS ver;
2> go
ver
----------------------------------------------------------------------------
Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64)
        Jun 15 2019 00:26:19
        Copyright (C) 2017 Microsoft Corporation
        Express Edition (64-bit) on Windows 8.1 Pro 6.3 <X64> (Build 9600: )

(1 rows affected)
1> SELECT * FROM (VALUES(1,2,3)) AS foo (x,y,z);
2> go
x           y           z
----------- ----------- -----------
          1           2           3

(1 rows affected)
```

My next thought was whether there was any way to leverage the existing `values()` code for INSERT INTO, but by the way it behaves it looks like it is a rather different animal:

```python
from sqlalchemy import MetaData, Table, Column, Integer

tbl = Table('table1',
            MetaData(),
            Column('foo', Integer),
            Column('bar', Integer),
            )
ins = tbl.insert().values([123, 456])
print(ins)
# INSERT INTO table1 (foo, bar) VALUES (:foo, :bar)
print(ins.parameters)
# {'foo': 123, 'bar': 456}
print(ins.values)
# <bound method ValuesBase.values of <sqlalchemy.sql.dml.Insert object at 0x008ED058>>
```

So to incorporate the recipe into the core code my first question would be where to define the `values` class? In lib/sqlalchemy/sql/schema.py where `Table` and `Column` are defined?

**Comment by gordthompson** [comment] 2019-11-23 12:53
And, just to keep things interesting, MariaDB 10.3 supports it as long as you don't name the columns ...

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2150
Server version: 10.3.20-MariaDB-0ubuntu0.19.10.1 Ubuntu 19.10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT * FROM (VALUES(1,2,3),(4,5,6)) AS foo (x,y,z);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(x,y,z)' at line 1
MariaDB [(none)]> SELECT * FROM (VALUES(1,2,3),(4,5,6)) AS foo;
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 1 | 2 | 3 |
| 4 | 5 | 6 |
+---+---+---+
2 rows in set (0.044 sec)
```

... while MySQL 5.7 doesn't seem to support it at all:

```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.28-0ubuntu0.18.04.4 (Ubuntu)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT * FROM (VALUES(1,2,3),(4,5,6)) AS foo (x,y,z);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VALUES(1,2,3),(4,5,6)) AS foo (x,y,z)' at line 1
mysql> SELECT * FROM (VALUES(1,2,3),(4,5,6)) AS foo;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VALUES(1,2,3),(4,5,6)) AS foo' at line 1
```

**Comment by zzzeek** [comment] 2019-11-26 00:43
So "VALUES" is first off a SQL construct that we use when we are making queries, so that means it's not part of the SchemaItem / DDLElement hierarchy. Next, it's a thing we select FROM, so it's part of the FromClause hierarchy (which we see in the wiki recipe).   The FromClause classes are defined in lib/sqlalchemy/sql/selectable.py, so that's where it should go.

this will be a great one!

**Comment by gordthompson** [comment] 2019-11-26 22:53
Okay, I tacked the following onto the very bottom of `lib/sqlalchemy/sql/selectable.py`:

```python
class Values(FromClause):
    named_with_column = True

    def __init__(self, columns, *args, **kw):
        self._column_args = columns
        self.list = args
        self.alias_name = self.name = kw.pop("alias_name", None)

    def _populate_column_collection(self):
        for c in self._column_args:
            c._make_proxy(self)

    @property
    def _from_objects(self):
        return [self]


@compiles(Values)
def compile_values(element, compiler, asfrom=False, **kw):
    columns = element.columns
    v = "VALUES %s" % ", ".join(
        "(%s)"
        % ", ".join(
            compiler.render_literal_value(elem, column.type)
            for elem, column in zip(tup, columns)
        )
        for tup in element.list
    )
    if asfrom:
        if element.alias_name:
            v = "(%s) AS %s (%s)" % (
                v,
                element.alias_name,
                (", ".join(c.name for c in element.columns)),
            )
        else:
            v = "(%s)" % v
    return v
```

and I added a line in `lib/sqlalchemy/sql/__init__.py`

```python
from .selectable import Values  # noqa
```

so the following little stand-alone test script could import `Values` from `sqlalchemy.sql`.

```python
# gord_test.py
from sqlalchemy import create_engine, Integer, String
from sqlalchemy.orm import Session
from sqlalchemy.sql import column, select, Values

e = create_engine("postgresql+psycopg2://postgres:(whatever)@192.168.0.161/sqla_test", echo=True)
sess = Session(e)

v = Values(
        [
            column("mykey", Integer),
            column("mytext", String),
            column("myint", Integer),
        ],
        (1, "textA", 99),
        (2, "textB", 88),
        alias_name="myvalues",
    )
print(v)  # VALUES (), ()

s = select([v])
print(s)  # SELECT FROM (VALUES (), ()) AS myvalues ()

result = e.execute(s)
# 2019-11-26 15:29:02,184 INFO sqlalchemy.engine.base.Engine SELECT
# FROM (VALUES (), ()) AS myvalues ()
# 2019-11-26 15:29:02,184 INFO sqlalchemy.engine.base.Engine {}
# 2019-11-26 15:29:02,187 INFO sqlalchemy.engine.base.Engine ROLLBACK
#
# Traceback (most recent call last):
#   File "C:\Users\Gord\git\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1259, in _execute_context
#     self.dialect.do_execute(
#   File "C:\Users\Gord\git\sqlalchemy\lib\sqlalchemy\engine\default.py", line 570, in do_execute
#     cursor.execute(statement, parameters)
# psycopg2.errors.SyntaxError: syntax error at or near ")"
# LINE 2: FROM (VALUES (), ()) AS myvalues ()
#                       ^
```

The shell of the `Values` object is there — a breakpoint confirmed that `compile_values` is getting called — but it's not being populated because `element.columns` is an empty list.

**Comment by zzzeek** [comment] 2019-11-27 15:51
the FromClause mechanics in 1.4 / master are entirely different than they are in current released versions and I will have to write a different implementation.

**Comment by zzzeek** [comment] 2019-11-27 16:04
here you go

```diff
diff --git a/lib/sqlalchemy/sql/__init__.py b/lib/sqlalchemy/sql/__init__.py
index bf5468aa5..3c40b80d5 100644
--- a/lib/sqlalchemy/sql/__init__.py
+++ b/lib/sqlalchemy/sql/__init__.py
@@ -73,6 +73,7 @@ from .expression import union  # noqa
 from .expression import union_all  # noqa
 from .expression import Update  # noqa
 from .expression import update  # noqa
+from .expression import Values  # noqa
 from .expression import within_group  # noqa
 from .visitors import ClauseVisitor  # noqa
 
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 85c1750b7..b8842d5c6 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -1954,6 +1954,27 @@ class SQLCompiler(Compiled):
 
         return text
 
+    def visit_values(self, element, asfrom=False, **kw):
+        columns = element.columns
+        v = "VALUES %s" % ", ".join(
+            "(%s)"
+            % ", ".join(
+                self.render_literal_value(elem, column.type)
+                for elem, column in zip(tup, columns)
+            )
+            for tup in element.list
+        )
+        if asfrom:
+            if element.alias_name:
+                v = "(%s) AS %s (%s)" % (
+                    v,
+                    element.alias_name,
+                    (", ".join(c.name for c in element.columns)),
+                )
+            else:
+                v = "(%s)" % v
+        return v
+
     def get_render_as_alias_suffix(self, alias_name_text):
         return " AS " + alias_name_text
 
diff --git a/lib/sqlalchemy/sql/expression.py b/lib/sqlalchemy/sql/expression.py
index 08e69f075..c560e96e8 100644
--- a/lib/sqlalchemy/sql/expression.py
+++ b/lib/sqlalchemy/sql/expression.py
@@ -156,6 +156,7 @@ from .selectable import TableClause  # noqa
 from .selectable import TableSample  # noqa
 from .selectable import TextAsFrom  # noqa
 from .selectable import TextualSelect  # noqa
+from .selectable import Values  # noqa
 from .visitors import Visitable  # noqa
 from ..util.langhelpers import public_factory  # noqa
 
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index 4b3844eec..77a49fa50 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -2057,6 +2057,25 @@ class ForUpdateArg(ClauseElement):
             self.of = None
 
 
+class Values(FromClause):
+    named_with_column = True
+    __visit_name__ = "values"
+
+    def __init__(self, columns, *args, **kw):
+        super(Values, self).__init__()
+        self._column_args = columns
+        self.list = args
+        self.alias_name = self.name = kw.pop("alias_name", None)
+
+    def _populate_column_collection(self):
+        for c in self._column_args:
+            self._columns.add(c)
+
+    @property
+    def _from_objects(self):
+        return [self]
+
+
 class SelectBase(
     roles.SelectStatementRole,
     roles.DMLSelectRole,

```

**Comment by gordthompson** [comment] 2019-11-27 17:46
Works great, thanks!

```python
v = Values(
        [
            column("mykey", Integer),
            column("mytext", String),
            column("myint", Integer),
        ],
        (1, "textA", 99),
        (2, "textB", 88),
        alias_name="myvalues",
    )
print(v)  # VALUES (1, 'textA', 99), (2, 'textB', 88)

s = select([v])
print(s)  # SELECT mykey, mytext, myint FROM (VALUES (1, 'textA', 99), (2, 'textB', 88)) AS myvalues (mykey, mytext, myint)

result = e.execute(s)

print(result.fetchall())  # [(1, 'textA', 99), (2, 'textB', 88)]
```

**Comment by gordthompson** [comment] 2019-11-27 23:52
Okay, so I did a bit of cleanup and added a test. When I threw the whole thing at tox I got one failure:

```
============================================================== FAILURES ===============================================================
_________________________________________________ CompareAndCopyTest.test_all_present _________________________________________________
[gw2] linux -- Python 3.6.8 /home/gord/git/sqlalchemy/.tox/py36-mssql/bin/python
Traceback (most recent call last):
  File "/home/gord/git/sqlalchemy/test/sql/test_compare.py", line 610, in test_all_present
    is_false(bool(need), "%d Remaining classes: %r" % (len(need), need))
  File "/home/gord/git/sqlalchemy/.tox/py36-mssql/lib/python3.6/site-packages/sqlalchemy/testing/assertions.py", line 259, in is_false
    is_(a, False, msg=msg)
  File "/home/gord/git/sqlalchemy/.tox/py36-mssql/lib/python3.6/site-packages/sqlalchemy/testing/assertions.py", line 264, in is_
    assert a is b, msg or "%r is not %r" % (a, b)
AssertionError: 1 Remaining classes: {<class 'sqlalchemy.sql.selectable.Values'>}
assert True is False
======================================================= short test summary info =======================================================
```

Our new `Values` class is "remaining" somewhere, but I must confess I have no idea what that actually means.

**Comment by zzzeek** [comment] 2019-11-28 00:29
that's the test I was hoping would fail because it is checking that every ClauseElement has a cache key definition set up, which this class needs.    ill add a patch here to illustrate soon.

**Comment by gordthompson** [comment] 2019-12-07 23:08
I had a look at the test code. Is the failure telling us that we need to add an item to `CoreFixtures` that will cover our new `Values` class?

**Comment by zzzeek** [comment] 2019-12-07 23:59
oh hey.  totally forgot about this.   i cant look now so maybe ping me during the week again.

**Comment by zzzeek** [comment] 2019-12-08 00:01
oh as far as waht the issue is, there's a new system in 1.4 / master where you have to set up a list of internal traversal objects for every ClauseElement, examples: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/selectable.py#L673  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/selectable.py#L1465  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/selectable.py#L1843   I don't know that this system is necessarily very intuitive right now so i can help devise it for Values.

**Comment by gordthompson** [comment] 2019-12-08 12:58
Based on the existing `_traverse_internals` declaration for `class TableClause` and the way a `Values` object is created

```python
v = Values(
    [
        column("mykey", Integer),
        column("mytext", String),
        column("myint", Integer),
    ],
    (1, "textA", 99),
    (2, "textB", 88),
    alias_name="myvalues",
)
```

it looks like we'll need at least

```python
_traverse_internals = [
    (
        "columns",
        InternalTraversal.dp_fromclause_canonical_column_collection,
    ),
    ("alias_name", InternalTraversal.dp_string),
]
```

but do we also need something in there to represent the tuples containing the row values (which could contain any number of things like strings, numbers, datetime objects, etc.)?

**Comment by zzzeek** [comment] 2019-12-08 15:22
yes we need something to represent the values also.  basically all the state within the object that affects what the SQL output would be.  for a literal value, SQLAlchemy uses a bindparam() to represent these, with the value contained inside, and the InternalTraversal.dp_clauseelement* symbols handle this, like if it is a list of bindparam() objects you would use InternalTraversal.dp_clauseelement_list.

**Comment by gordthompson** [comment] 2019-12-08 17:43
So if I'm correctly reading the `__init__`  method of our `Values` class

```python
def __init__(self, columns, *args, **kw):
```

`args` will be a tuple containing one tuple for each row of data. I see that there is an `InternalTraversal.dp_clauseelement_tuples` which will "Visit a list of tuples which contain `.ClauseElement` objects.", so if it's not put off by a tuple of tuples (as opposed to a list of tuples), then could we do this?

```python
_traverse_internals = [
    (
        "columns",
        InternalTraversal.dp_fromclause_canonical_column_collection,
    ),
    (
        "args",
        InternalTraversal.dp_clauseelement_tuples,
    ),
    ("alias_name", InternalTraversal.dp_string),
]
```

**Comment by zzzeek** [comment] 2019-12-08 23:30
whatever the attributes on the class are named which store the important state.  in my example above it would be "_column_args", "list", "alias_name", although there is also ".columns" and "name" we can use those.

**Comment by gordthompson** [comment] 2019-12-08 23:46
Email notification of your post arrived just as I started to test this

```diff
Index: lib/sqlalchemy/sql/selectable.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/sqlalchemy/sql/selectable.py	(revision c5a61b03b634284e0940ffdaf550d5d10007f0ca)
+++ lib/sqlalchemy/sql/selectable.py	(date 1575846912311)
@@ -2064,6 +2064,18 @@
     named_with_column = True
     __visit_name__ = "values"
 
+    _traverse_internals = [
+        (
+            "columns",
+            InternalTraversal.dp_fromclause_canonical_column_collection,
+        ),
+        (
+            "args",
+            InternalTraversal.dp_clauseelement_tuples,
+        ),
+        ("alias_name", InternalTraversal.dp_string),
+    ]
+
     def __init__(self, columns, *args, **kw):
         super(Values, self).__init__()
         self._column_args = columns
```

It didn't introduce any new failures, but it also didn't prevent `test_all_present` from failing, either.

**Comment by zzzeek** [comment] 2019-12-08 23:49
forgive me if I should be seeing this somewhere is the PR available ?

**Comment by gordthompson** [comment] 2019-12-09 00:06
My branch is here:

https://github.com/gordthompson/sqlalchemy/tree/aaa-from-values

I could submit a PR if you like. I just didn't want to put it in the queue prematurely.

**Comment by sqla-tester** [comment] 2019-12-10 20:47
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Implement SQL VALUES in core.** https://gerrit.sqlalchemy.org/1608

**Comment by gordthompson** [comment] 2019-12-19 19:20
This issue is currently tagged with the 1.5 milestone. Should we revise that, seeing as it is essentially complete?

**Comment by zzzeek** [comment] 2019-12-19 23:57
yes the milestone becomes 1.4

**Comment by sqla-tester** [comment] 2020-03-07 15:01
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Implement SQL VALUES in core.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1608

**Closed** 2020-03-24 19:56 UTC
Labels: fairly easy, motivated volunteers requested, postgresql, use case
