### ISSUE TITLE
Microsoft SQL: Query with OFFSET does not work after running the same query without OFFSET until restart

### ISSUE THREAD

**Issue by f1nality** [sqlalchemy/sqlalchemy#6265] opened 2021-04-14 18:09 UTC
**Describe the bug**
When using **Microsoft SQL (12.0.2000.8)** `OFFSET ? ROWS FETCH FIRST ? ROWS ONLY` is wrongly cached.
- If I make query without OFFSET first, and then make query with OFFSET -> i continue to receive results without applying OFFSET.
- If I make query with OFFSET first, and then make query without OFFSET -> i receive correct results with correct OFFSET.

**Expected behavior**
No matter in which order I perform queries - queries with and without OFFSET should respect OFFSET.

**To Reproduce**

```
session.query(Model).offset(0).limit(25).all() # will return [0;24] items
session.query(Model).offset(25).limit(25).all() # will return [0;24] items again
```

but this will work fine after restart

```
session.query(Model).offset(25).limit(25).all() # will return [25;49] items
session.query(Model).offset(0).limit(25).all() # will return [0;24] items
```

**Workaround**

Disabling sql cache fixes the issue

![image](https://user-images.githubusercontent.com/1628232/114757934-18e74700-9d65-11eb-81f2-14369474f61f.png)

**Versions.**
 - OS: MacOS
 - Python: 3.7
 - SQLAlchemy: 1.4.7
 - Database: MicrosoftSQL

**Comment by zzzeek** [comment] 2021-04-14 19:53
so we had related fixes in #6184, and this one is slipping through due to the "0" triggering it to use TOP.     We should not be using TOP if offset() is present at all.

thanks for the report!  this will be in 1.4.8.      you might be able to work around by specifying offset(literal(value)) for now.

**Comment by CaselIT** [comment] 2021-04-14 19:57
Another workaround is to use `fetch` instead of limit. that will force fetch/offset even when `offest=0`

**Comment by zzzeek** [comment] 2021-04-14 20:00
it's going to use FETCH yes, the issue is that when theres' no offset it uses TOP which we had the impression was more efficient when available.

**Comment by CaselIT** [comment] 2021-04-14 20:06
iirc it was preferred when `offset=0` since top supports the percent or with ties with fetch / offset do not. But I agree that if `offset is not None` it should use fetch/offset

**Comment by zzzeek** [comment] 2021-04-14 20:12
Yeah if you use with_ties/ percent then you need to not have an offset() now.  this is a slightly breaking change, did we introduce those featrues in 1.4 ?

**Comment by CaselIT** [comment] 2021-04-14 20:14
yes. fetch offset was a 1.4 feature. I don't remember if we supported offset on mssql before

**Comment by sqla-tester** [comment] 2021-04-14 20:17
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**don't base compilation off the int value of offset/limit part II** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2742

**Comment by zzzeek** [comment] 2021-04-14 20:17
we supported offset using window functions

**Comment by CaselIT** [comment] 2021-04-14 20:20
btw locked at oracle and it does not change what sql it creates based on the values of the limit/offset. so it should be ok there

**Comment by zzzeek** [comment] 2021-04-14 20:25
I spent a lot more time w/ oracle in #6184

**Comment by zzzeek** [comment] 2021-04-14 20:26
correction #6173 was where most of the work was done

**Comment by CaselIT** [comment] 2021-04-14 20:29
yes I remember. IIRC in oracle we don't render fetch/offset by default, but use the subquery version

**Closed** 2021-04-14 23:36 UTC
Labels: SQL Server, bug, regression

**Comment by scd75** [comment] 2021-04-19 09:28
hello, just checking:
was this expected as part of the bug fix?
When I run
```
my_session.query(my_model).offset(0).limit(100).all()
```
I now obtain this error:

\lib\site-packages\sqlalchemy\dialects\mssql\base.py", line 1786, in _check_can_use_fetch_limit
    "MSSQL requires an order_by when "
sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause

**Comment by CaselIT** [comment] 2021-04-19 11:15
Yes, that's expected, since mssql requires an order by when using an offset, even if the offset is 0.

**Comment by zzzeek** [comment] 2021-04-19 13:20
it is, the previous behavior of "guessing" for the offset(0) was something we should not have done.   SQLAlchemy going forward is trying to be a lot more 1-1 , like you said "oiffset(0)", so we're going to put the equivalent of OFFSET 0 in there.  if your offset is 0 then just omit the .offset() call, though when using LIMIT you really should always have an ORDER BY.
