### ISSUE TITLE
Inspector do not returns functional indexes

### ISSUE THREAD

**Issue by adrien-berchet** [sqlalchemy/sqlalchemy#7554] opened 2022-01-10 11:15 UTC
### Describe the bug

In order to fix https://github.com/geoalchemy/geoalchemy2/issues/137 I would like to check that indexes are properly created in the unit tests. For this I use `from sqlalchemy import inspect` but it does not return the functional indexes, only the regular ones (note that the two indexes properly appear in the `table.indexes` entry). While when I check with `pgcli` the indexes are properly displayed:

```sql
\d gis.test_table_with_indexes                                                                                                                                                               
+----------+-------------------+---------------------------------------------------------------------------+
| Column   | Type              | Modifiers                                                                 |
|----------+-------------------+---------------------------------------------------------------------------|
| id       | integer           |  not null default nextval('gis.test_table_with_indexes_id_seq'::regclass) |
| test     | character varying |                                                                           |
+----------+-------------------+---------------------------------------------------------------------------+
Indexes:
    "test_table_with_indexes_pkey" PRIMARY KEY, btree (id)
    "test_functional_index" btree (lower(test::text))
    "test_index" btree (test)

```

I tried several combinations of regular and functional indexes and the functional ones are always missing.
I also note that the primary key index is not displayed, I don't know if it is intended?

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Index
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func


engine = create_engine('postgresql://****************', echo=True)
metadata = MetaData(engine)
Base = declarative_base(metadata=metadata)


def test_functional_indexes():
    Base = declarative_base(metadata=metadata)

    class TestTableWithIndexes(Base):
        __tablename__ = 'test_table_with_indexes'
        __table_args__ = {'schema': 'gis'}
        id = Column(Integer, primary_key=True)
        test_col = Column(String)
        test_functional_col = Column(String)

    Index("test_functional_index", func.lower(TestTableWithIndexes.__table__.c.test_functional_col))
    Index("test_index", TestTableWithIndexes.__table__.c.test_col)

    TestTableWithIndexes.__table__.drop(engine)
    TestTableWithIndexes.__table__.create(engine)

    inspector = inspect(engine)
    indices = inspector.get_indexes(TestTableWithIndexes.__tablename__)

    print(indices)  # <= ONLY "test_index" IN THE LIST
    assert len(indices) == 2  # FAILS
```

### Error

```
________________________ test_functional_indexes ________________________

    def test_functional_indexes():
        Base = declarative_base(metadata=metadata)
    
        class TestTableWithIndexes(Base):
            __tablename__ = 'test_table_with_indexes'
            __table_args__ = {'schema': 'gis'}
            id = Column(Integer, primary_key=True)
            test = Column(String)
    
        Index("test_functional_index", func.lower(TestTableWithIndexes.__table__.c.test))
        Index("test_index", TestTableWithIndexes.__table__.c.test)
    
        TestTableWithIndexes.__table__.drop(engine)
        TestTableWithIndexes.__table__.create(engine)
    
        inspector = get_inspector(engine)
        indices = inspector.get_indexes(TestTableWithIndexes.__tablename__)
    
        print(indices)
>       assert len(indices) == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = len([{'column_names': ['test'], 'include_columns': [], 'name': 'test_index', 'unique': False}])

tests/test_functional_index.py:36: AssertionError
``` 

### Versions

- OS: Linux
- Python: 3.8.10
- SQLAlchemy: 1.4.29
- Database: PostgreSQL 12.9
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2==2.9.3

**Comment by CaselIT** [comment] 2022-01-10 13:08
Hi,

I think this is a duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/7442

**Comment by CaselIT** [comment] 2022-01-19 21:18
closing in favour of the other one. please follow up in https://github.com/sqlalchemy/sqlalchemy/issues/7442

**Closed by CaselIT** 2022-01-19 21:18 UTC
Labels: duplicate, postgresql, reflection

**Comment by adrien-berchet** [comment] 2022-01-19 21:55
Ok, thanks!
