### ISSUE TITLE
sqlite+pysqlite on_connect create_function kwarg deterministic usage logic reversed

### ISSUE THREAD

**Issue by msftcangoblowm** [sqlalchemy/sqlalchemy#9430] opened 2023-03-06 07:53 UTC
### Describe the bug

sqlite3.Connection.create_function
- py38>=: no longer supports kwarg, deterministic
- py38<, sqlite3.Connection.create_function requires kwarg, deterministic

[sqlite create_function docs](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function)

> `[NotSupportedError](https://docs.python.org/3/library/sqlite3.html#sqlite3.NotSupportedError) – If deterministic is used with SQLite versions **older than** 3.8.3.
> 

In [pysqlite.py](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/sqlite/pysqlite.py),

SQLiteDialect_pysqlite.on_connect, attempts to register two user-defined functions: regexp and floor.

Affects all python versions cuz the logic is reversed, kwargs deterministic:
-  is provided when it shouldn't
- is missing when it's needed

### Separate issue

The exact cutoff version is py383, but the code only handles py[major][minor], not py[major][minor][patch]. So that is dodgy and should be a separate issue. The suggested changes does not address that issue. One issue at a time

### SQLAlchemy Version in Use

2.0.5.post1

### DBAPI (i.e. the database driver)

sqlite+pysqlite, sqlite+pycipher

### Database Vendor and Major Version

sqlite3

### Python Version

3.9.16

### Operating system

Void Linux amd64

#### Affected code segment

```
        if util.py38 and self._get_server_version_info(None) >= (3, 9):
            # sqlite must be **greater than** 3.8.3 for deterministic=True
            # https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function
            # the check is more conservative since there were still issues
            # with following 3.8 sqlite versions
            create_func_kw = {"deterministic": True}
        else:
            create_func_kw = {}
```

#### Suggested changes
```
        if util.py38 and self._get_server_version_info(None) >= (3, 9):
            create_func_kw = {}
        else:
            # sqlite must be **less than** 3.8.3 for deterministic=True
            # https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function
            # the check is more conservative since there were still issues
            # with following 3.8 sqlite versions
            create_func_kw = {"deterministic": True}
```
Lets review the changed code to see if it follows the docs

> `[NotSupportedError](https://docs.python.org/3/library/sqlite3.html#sqlite3.NotSupportedError) – If deterministic is used with SQLite versions **older than** 3.8.3.
> 

```if util.py38 and self._get_server_version_info(None) >= (3, 9)```

util.py38 means py38 and greater. So if py38+ would trigger NotSupportedError exception if kwarg deterministic is used. In the suggested code kwarg deterministic is not provided, ```create_func_kw = {}```

In the else condition, meaning prior to py38, kwarg deterministic is supported and should be provided ```create_func_kw = {"deterministic": True}```

### Error

Install sqlalchemy package into a virtual environment py39

Attempting to connect, using sqlalchemy2.0 Core connect(), to a sqlite+pysqlite or sqlite+pycipher database, irregardless persistent or in-memory, results in ```sqlalchemy.exc.DatabaseError```

Sorry don't have the traceback

Locally, have had to fix this three times. So safe assumption, really had to report this bug. Looked for pysqlite issues and none addressed this issue

**Comment by CaselIT** [comment] 2023-03-06 11:19
Hi,

I find this very strange, since before 2.0.5 it was applying `deterministic=True` for `python>=3.8` regardless of the sqlite version.
The change added in 2.0.5 is more conservative than the one in previous v2 versions.

Also you are reading the python docs as the opposite of what they are. From https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function
> NotSupportedError – If deterministic is used with SQLite versions older than 3.8.3.

meaning sqlite before 3.8.3 does not support deterministic

> New in version 3.8: The deterministic parameter.

meaning prior to python 3.8 there was no determinist

So I don't see how the condition is wrong. The proposed change breaks both of these condition

> Install sqlalchemy package into a virtual environment py39
> 
> Attempting to connect, using sqlalchemy2.0 Core connect(), to a sqlite+pysqlite or sqlite+pycipher database, irregardless persistent or in-memory, results in `sqlalchemy.exc.DatabaseError`
> 
> Sorry don't have the traceback
> 
> Locally, have had to fix this three times. So safe assumption, really had to report this bug. Looked for pysqlite issues and none addressed this issue

this is tested by multiple pipeline, none of which report any error, so this is not actionable until you provide a stack trace.

**Comment by CaselIT** [comment] 2023-03-06 11:20
> sqlite3.Connection.create_function
> 
>     * py38>=: no longer supports kwarg, deterministic
> 
>     * py38<, sqlite3.Connection.create_function requires kwarg, deterministic

this is litterally the opposite of how the create_function behavew

**Comment by zzzeek** [comment] 2023-03-06 13:53
> sqlite must be **less than** 3.8.3 for deterministic=True

this is incorrect.   SQLite 3.8.3 is the release for which the concept of "determinstic" was first introduced:

https://sqlite.org/releaselog/3_8_3.html

> Added [SQLITE_DETERMINISTIC](https://sqlite.org/c3ref/c_deterministic.html#sqlitedeterministic) as an optional bit in the 4th argument to the [sqlite3_create_function()](https://sqlite.org/c3ref/create_function.html) and related interfaces, providing applications with the ability to create new functions that can be factored out of inner loops when they have constant arguments.

Therefore, sqlite must be **equal to or greater than** 3.8.3 for deterministic=True


> ### Error
> 
> Install sqlalchemy package into a virtual environment py39

Let's start with that

```bash
$ /opt/python-3.9.16/bin/python3 -m virtualenv .venv
created virtual environment CPython3.9.16.final.0-64 in 292ms
  creator CPython3Posix(dest=/home/classic/tmp/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/classic/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==66.0.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[classic@photon3 tmp]$ source .venv/bin/activate
(.venv) [classic@photon3 tmp]$ pip install sqlalchemy
Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.5.post1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 12.4 MB/s eta 0:00:00
Collecting greenlet!=0.4.17
  Downloading greenlet-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (610 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 13.2 MB/s eta 0:00:00
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy
Successfully installed greenlet-2.0.2 sqlalchemy-2.0.5.post1 typing-extensions-4.5.0

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
```

> Attempting to connect, using sqlalchemy2.0 Core connect(), to a sqlite+pysqlite or sqlite+pycipher database, irregardless persistent or in-memory, results in `sqlalchemy.exc.DatabaseError`

```bash
(.venv) [classic@photon3 tmp]$ python
Python 3.9.16 (main, Jan 17 2023, 14:28:07) 
[GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> sa.__version__
'2.0.5.post1'
>>> e = sa.create_engine("sqlite://", echo=True)
>>> c = e.connect()
>>> c.exec_driver_sql("select 'sqlite works fine'").all()
2023-03-06 08:46:20,791 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-06 08:46:20,792 INFO sqlalchemy.engine.Engine select 'sqlite works fine'
2023-03-06 08:46:20,792 INFO sqlalchemy.engine.Engine [raw sql] ()
[('sqlite works fine',)]
```

closing this as no stack trace or MCVE was provided, can't reproduce with instructions given.

**Closed by zzzeek** 2023-03-06 13:53 UTC
Labels: sqlite, cant reproduce

**Comment by msftcangoblowm** [comment] 2023-03-07 01:16
### traceback
Python: py39
dialect: sqlite+pysqlcipher

Call to method to create all database objects

```Base.metadata.create_all(bind=engine)```



../lib/python3.9/site-packages/sqlalchemy/sql/schema.py:5581: in create_all
    bind._run_ddl_visitor(
../lib/python3.9/site-packages/sqlalchemy/engine/base.py:3225: in _run_ddl_visitor
    with self.begin() as conn:
/home/msftcanblowm/.pyenv/versions/3.9.16/lib/python3.9/contextlib.py:119: in __enter__
    return next(self.gen)
../lib/python3.9/site-packages/sqlalchemy/engine/base.py:3215: in begin
    with self.connect() as conn:
../lib/python3.9/site-packages/sqlalchemy/engine/base.py:3251: in connect
    return self._connection_cls(self)
../lib/python3.9/site-packages/sqlalchemy/engine/base.py:145: in __init__
    self._dbapi_connection = engine.raw_connection()
../lib/python3.9/site-packages/sqlalchemy/engine/base.py:3275: in raw_connection
    return self.pool.connect()
../lib/python3.9/site-packages/sqlalchemy/pool/impl.py:420: in connect
    return _ConnectionFairy._checkout(self, self._fairy)
../lib/python3.9/site-packages/sqlalchemy/pool/base.py:1271: in _checkout
    fairy = _ConnectionRecord.checkout(pool)
../lib/python3.9/site-packages/sqlalchemy/pool/base.py:719: in checkout
    rec = pool._do_get()
../lib/python3.9/site-packages/sqlalchemy/pool/impl.py:402: in _do_get
    c = self._create_connection()
../lib/python3.9/site-packages/sqlalchemy/pool/base.py:396: in _create_connection
    return _ConnectionRecord(self)
../lib/python3.9/site-packages/sqlalchemy/pool/base.py:681: in __init__
    self.__connect()
../lib/python3.9/site-packages/sqlalchemy/pool/base.py:917: in __connect
    pool.dispatch.connect.for_modify(
../lib/python3.9/site-packages/sqlalchemy/event/attr.py:473: in _exec_w_sync_on_first_run
    self(*args, **kw)
../lib/python3.9/site-packages/sqlalchemy/event/attr.py:487: in __call__
    fn(*args, **kw)
../lib/python3.9/site-packages/sqlalchemy/engine/create.py:718: in on_connect
    do_on_connect(dbapi_connection)
../lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlcipher.py:145: in on_connect
    super_on_connect(conn)
../lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py:574: in connect
    fn(conn)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dbapi_connection = <pysqlcipher3.dbapi2.Connection object at 0x7f3a37c13c70>

    def set_regexp(dbapi_connection):
>       dbapi_connection.create_function(
            "regexp", 2, regexp, **create_func_kw
        )
E       TypeError: function takes at most 3 arguments (4 given)

../lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py:557: TypeError

**Comment by zzzeek** [comment] 2023-03-07 01:47
I think what's happening on your end depends very much on how you are getting sqlcipher.  sqlcipher is extremely all over the place with different versions of it and different builds and it's just a mess.   if your build of sqlcipher is reporting the wrong sqlite version, that may be involved.  would need to know **exactly** where you are acquiring sqlcipher from, **exactly** what version, **exactly** what sqlite libraries you used to build, and how you built /  installed it

Can't reproduce on this end using sqlcipher3_binary.  See below.  Try running through the exact same steps

```bash
$ /opt/python-3.9.16/bin/python3 -m virtualenv .venv
created virtual environment CPython3.9.16.final.0-64 in 247ms
  creator CPython3Posix(dest=/home/classic/tmp/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/classic/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.1.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[classic@photon3 tmp]$ .venv/bin/pip install sqlcipher3-binary
Collecting sqlcipher3-binary
  Downloading sqlcipher3_binary-0.5.0-cp39-cp39-manylinux_2_24_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 10.7 MB/s eta 0:00:00
Installing collected packages: sqlcipher3-binary
Successfully installed sqlcipher3-binary-0.5.0
[classic@photon3 tmp]$ .venv/bin/pip install sqlalchemy
Collecting sqlalchemy
  Using cached SQLAlchemy-2.0.5.post1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
Collecting greenlet!=0.4.17
  Using cached greenlet-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (610 kB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy
Successfully installed greenlet-2.0.2 sqlalchemy-2.0.5.post1 typing-extensions-4.5.0
[classic@photon3 tmp]$ .venv/bin/python
Python 3.9.16 (main, Jan 17 2023, 14:28:07) 
[GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> import sqlcipher3
>>> e = sa.create_engine("sqlite+pysqlcipher://:password@/dbname.db", module=sqlcipher3, echo=True)
>>> c = e.connect()
>>> c.exec_driver_sql("select 'it works'").all()
2023-03-06 20:44:23,374 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-06 20:44:23,374 INFO sqlalchemy.engine.Engine select 'it works'
2023-03-06 20:44:23,374 INFO sqlalchemy.engine.Engine [raw sql] ()
[('it works',)]
>>> 
```

**Comment by msftcangoblowm** [comment] 2023-03-07 02:10
[msftcangoblowm@(none) Documents]$ /usr/local/bin/wallet_usb/myproject/bin/python
Python 3.9.16 (main, Dec 21 2022, 04:19:42) 
[GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlcipher3 as sqlcipher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sqlcipher3'
>>> from pysqlcipher3 import dbapi2 as sqlcipher
>>> 
>>> quit()

builtin cd ~/Documents
[msftcangoblowm@(none) Documents]$ /usr/local/bin/wallet_usb/myproject/bin/python -V
Python 3.9.16
[msftcangoblowm@(none) Documents]$ /usr/local/bin/wallet_usb/myproject/bin/python
Python 3.9.16 (main, Dec 21 2022, 04:19:42) 
[GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> from pysqlcipher3 import dbapi2 as sqlcipher3
>>> e = sa.create_engine("sqlite+pysqlcipher://:password@/dbname.db", module=sqlcipher3, echo=True)
>>> c = e.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
    return self._connection_cls(self)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 420, in connect
    return _ConnectionFairy._checkout(self, self._fairy)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 402, in _do_get
    c = self._create_connection()
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 917, in __connect
    pool.dispatch.connect.for_modify(
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 718, in on_connect
    do_on_connect(dbapi_connection)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlcipher.py", line 145, in on_connect
    super_on_connect(conn)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 574, in connect
    fn(conn)
  File "/usr/local/bin/wallet_usb/myproject/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 557, in set_regexp
    dbapi_connection.create_function(
TypeError: function takes at most 3 arguments (4 given)

**Comment by msftcangoblowm** [comment] 2023-03-07 02:13
https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/sqlite/pysqlcipher.py

```
@classmethod
    def import_dbapi(cls):
        try:
            import sqlcipher3 as sqlcipher
        except ImportError:
            pass
        else:
            return sqlcipher

        from pysqlcipher3 import dbapi2 as sqlcipher

        return sqlcipher
```

So ```from pysqlcipher3 import dbapi2 as sqlcipher``` is the fallback driver

**Comment by msftcangoblowm** [comment] 2023-03-07 02:15
./python3 -m pip list
pysqlcipher3      1.2.0
...

**Comment by msftcangoblowm** [comment] 2023-03-07 02:32
https://github.com/coleifer/sqlcipher3/blob/master/src/connection.c#L997

static char *kwlist[] = {"name", "narg", "func", "deterministic", NULL};

https://github.com/rigglemania/pysqlcipher3/blob/master/src/python3/connection.c#L835

static char *kwlist[] = {"name", "narg", "func", NULL, NULL};

So the pysqlcipher3 driver lacks kwargs deterministic

https://github.com/rigglemania/pysqlcipher3/blob/master/src/python3/connection.c#L846
```
if (!PyArg_ParseTupleAndKeywords(args, kwargs, "siO", kwlist,
                                     &name, &narg, &func))
    {
        return NULL;
    }
```
Probably this check is failing

How should to proceed. Ask upstream (pysqlcipher3) to fix it or mitigate within sqlalchemy sqlite+pycipher driver?

**Comment by msftcangoblowm** [comment] 2023-03-07 02:52
[pysqlcipher3](https://github.com/rigglemania/pysqlcipher3/blob/master/src/python3/connection.c#L852)

`rc = sqlite3_create_function(self->db, name, n_arg, SQLITE_UTF8, (void*)aggregate_class, 0, &_pysqlite_step_callback, &_pysqlite_final_callback);`

Passes in flag *SQLITE_UTF8*. So pysqlcipher3 *DOES NOT* support the deterministic flag and will error if provided

[sqlcipher3](https://github.com/coleifer/sqlcipher3/blob/master/src/connection.c#L1003)
```
int deterministic = 0;
int flags = SQLITE_UTF8;
if (deterministic) {
#if SQLITE_VERSION_NUMBER < 3008003
        PyErr_SetString(pysqlite_NotSupportedError,
                        "deterministic=True requires SQLite 3.8.3 or higher");
        return NULL;
#else
        if (sqlite3_libversion_number() < 3008003) {
            PyErr_SetString(pysqlite_NotSupportedError,
                            "deterministic=True requires SQLite 3.8.3 or higher");
            return NULL;
        }
        flags |= SQLITE_DETERMINISTIC;
#endif
    }
rc = sqlite3_create_function_v2(self->db,
                                    name,
                                    narg,
                                    flags,
                                    (void*)func,
                                    _pysqlite_func_callback,
                                    NULL,
                                    NULL,
                                    &_destructor);
```

So sqlcipher3 supports the deterministic flag

**Comment by zzzeek** [comment] 2023-03-07 03:31
I'm not able to install pysqlcipher3 at all and have never been able to.  This is why the note at https://docs.sqlalchemy.org/en/20/dialects/sqlite.html#id8 suggests using sqlcipher3.

When I install any of these drivers I get a big error message from pip that it failed to build.   sqlcipher3 I got to install using sqlcipher3-binary.   

if you can show me how you get pysqlcipher3 installed

**Comment by zzzeek** [comment] 2023-03-07 03:41
OK it looks like pysqlcipher3 just had a recent release, I got it to install, and yes this is a bug on their end, report it to them.

there is no regression in SQLAlchemy as I get the same stack trace with SQLAlchemy 2.0.4.   This error will occur with all SQLAlchemy 2.0 versions because they are not honoring the pysqlite API appropriately.    sqlcipher3 works right now.

**Comment by msftcangoblowm** [comment] 2023-03-07 03:51
This is embarassing, From package manager, installed sqlcipher sqlcipher-devel. From from pip installed pysqlcipher3

Followed the *in production* instructions:

[build-against-libsqlcipher](https://github.com/rigglemania/pysqlcipher3#build-against-libsqlcipher)

```
[msftcangoblowm@(none) /]$ lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void

[msftcangoblowm@(none) /]$ sudo find -name "libsqlcipher*.so" -print
Password: 
./usr/lib/libsqlcipher.so

[msftcangoblowm@(none) /]$ xbps-query -Rs sqlcipher
[*] sqlcipher-4.3.0_3       SQLite extension that provides transparent 256-bit AES encryption
[*] sqlcipher-devel-4.3.0_3 SQLite extension that provides transparent 256-bit AES encryption - development files

[msftcangoblowm@(none) bin]$ sudo ./python3 -m pip install --force-reinstall --no-cache-dir pysqlcipher3
Collecting pysqlcipher3
  Downloading pysqlcipher3-1.2.0.tar.gz (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.8/102.8 kB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pysqlcipher3
  Building wheel for pysqlcipher3 (setup.py) ... done
  Created wheel for pysqlcipher3: filename=pysqlcipher3-1.2.0-cp39-cp39-linux_x86_64.whl size=150524 sha256=cca11798be4009466bdf917b921af64d419eaa7e07667c34f7bd7cfa3b82f734
  Stored in directory: /tmp/pip-ephem-wheel-cache-soxk_maa/wheels/3b/96/6e/dc8484b6202ddaa9c82850b4321fc34816c206a23f6179cf68
Successfully built pysqlcipher3
Installing collected packages: pysqlcipher3
  Attempting uninstall: pysqlcipher3
    Found existing installation: pysqlcipher3 1.2.0
    Uninstalling pysqlcipher3-1.2.0:
      Successfully uninstalled pysqlcipher3-1.2.0
Successfully installed pysqlcipher3-1.2.0
```

**Comment by msftcangoblowm** [comment] 2023-03-07 04:21
Submitted the bug report

[pysqlcipher3 Issue 33](https://github.com/rigglemania/pysqlcipher3/issues/33)
