### ISSUE TITLE
postgresql.psycopg2 dialect should support empty connection string for libpq to use PG… env vars

### ISSUE THREAD

**Issue by jmehnle** [sqlalchemy/sqlalchemy#4562] opened 2019-03-21 17:43 UTC
The `postgresql.psycopg2` dialect fails to connect if no connection parameters are specified in the connection URL, even though the official `libpq` Pg client library that underlies `psycopg2` is perfectly capable of [reading all connection parameters from `PG…` environment variables](https://www.postgresql.org/docs/current/libpq-envars.html), [provided an empty connection string is supplied](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQCONNECTDB).

This problem exists in all versions of SQLAlchemy including 1.3.2 (the latest as of writing):

Explicit passing of connection parameters in connection URL:

```
$ python
Python 3.6.5 (default, Mar 29 2018, 15:37:32)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.2'
>>> from sqlalchemy import create_engine
>>> engine = create_engine('postgresql://localhost/sqlalchemy-test')
>>> conn = engine.connect()
>>> result = conn.execute('SELECT 42')
>>> result.scalar()
42
```

Connection URL without connection parameters but with `PGHOST` and `PGDATABASE` env vars specified:

```
$ PGHOST=localhost PGDATABASE=sqlalchemy-test python
Python 3.6.5 (default, Mar 29 2018, 15:37:32)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.2'
>>> from sqlalchemy import create_engine
>>> engine = create_engine('postgresql://')
>>> conn = engine.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/engine/base.py", line 2193, in connect
    return self._connection_cls(self, **kwargs)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/engine/base.py", line 2293, in raw_connection
    self.pool.unique_connection, _connection
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/base.py", line 294, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/base.py", line 483, in checkout
    rec = pool._do_get()
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/impl.py", line 138, in _do_get
    self._dec_overflow()
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/impl.py", line 135, in _do_get
    return self._create_connection()
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/pool/base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/SQLAlchemy-1.3.2.dev0-py3.6-macosx-10.13-x86_64.egg/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/julian/pyvenv/sqlalchemy-py3.6/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    raise TypeError('missing dsn and no parameters')
TypeError: missing dsn and no parameters
```

However, with a trivial change to the `postgresql.psycopg2` dialect, this could work flawlessly:

```
$ PGHOST=localhost PGDATABASE=sqlalchemy-test python
Python 3.6.5 (default, Mar 29 2018, 15:37:32)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.2'
>>> from sqlalchemy import create_engine
>>> engine = create_engine('postgresql://')
>>> conn = engine.connect()
>>> result = conn.execute('SELECT 42')
>>> result.scalar()
42
```

**Comment by sqla-tester** [comment] 2019-03-21 18:06
**Julian Mehnle** has proposed a fix for this issue in the **master** branch:

**postgresql.psycopg2 dialect: Correctly handle complete absence of connection parameters** https://gerrit.sqlalchemy.org/1174

**Comment by jvanasco** [comment] 2019-03-21 20:09
Two comments:

1. not specifying a connection string with the `sqllite` dialect will use an in-memory database.  see https://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite  I think the PR should include a similar notice on the PostgreSQL docs for this behavior.

2. with the sqlite behavior in mind, i'm a bit concerned with an empty connection string having a different behavior across dialects as it complicates code reviews and I see a future potential of users getting confused by the empty string behaving differently in each context.  i don't think there's a real solution to address this, but I did want to point this out because I really prefer looking at code that hints at what is going on.

**Comment by zzzeek** [comment] 2019-03-21 20:19
> Two comments:
> 
>     2. with the sqlite behavior in mind, i'm a bit concerned with an empty connection string having a different behavior across dialects as it complicates code reviews and I see a future potential of users getting confused by the empty string behaving differently in each context.  i don't think there's a real solution to address this, but I did want to point this out because I really prefer looking at code that hints at what is going on.

I have a slight concern that we are sending blank string `''` for an argument that wasnt there but considering it only raises an error now, it might be the right thing to do.  I'd compare it to MySQL's behavior which I think does the local unix socket connection by default.   If it works with MySQL like that it probably can go that way for Postgresql. SQLite is a given that it's very different from any other database.

**Comment by jvanasco** [comment] 2019-03-21 20:35
If it's consistent with a current behavior for mysql, then sqlite being an outlier does sound like the right approach. I was mainly worried about developers switching between the mysql variants and postgres and causing lots of emails/github tickets.

**Comment by jmehnle** [comment] 2019-03-21 21:09
I'm with @zzzeek. This merely turns one case with undefined behavior into a case with well-defined behavior. I'd be more than happy to add a note to the docs that makes this explicit.

**Comment by jvanasco** [comment] 2019-03-21 21:15
might be best to leave this as-is and make a new ticket to document the behavior of null connection strings for postgres + mysql, since that isn't documented either.  i can generate a PR for the docs after this gets merged.

**Comment by jmehnle** [comment] 2019-03-21 21:30
Oops, already updated the docs. Feel free to remove the doc bits if you prefer them to go in separately.

**Comment by jvanasco** [comment] 2019-03-21 21:38
i just wanted to make things easier for you and @zzzeek, in case he's already got it testing in gerrit

**Comment by zzzeek** [comment] 2019-03-21 21:53
i need to figure out how people can know this quickly, just do everything in the PR and I sync to gerrit automatically each change

**Comment by jvanasco** [comment] 2019-03-21 22:01
@zzzeek i didn't realize gerrit auto-updates against the open PR. is the comment from sqla-tester above templatable?  if so you could tweak that?  maybe use a github label to denote this has begun testing?

i hate how my trying to simplify your workflow has complicated it.

**Comment by zzzeek** [comment] 2019-03-21 22:46
oh on the issue, that might be a good idea, "Fix proposed" type of thing?

**Comment by zzzeek** [comment] 2019-03-22 20:50
hi, we should be addressing #4392 either here or if you have some ability to send a PR for it, that would be helpful.  I'm opposed to SQLAlchemy URLs translating directly to libpq URLs but we could use multiple host format.  As you might see in #4392 I have a lot of resistance to changing things left of the question mark, but nonetheless if we can keep it to the right of the question mark, it means the URL format does not need to be changed.

I'll likely be merging the PR here soon in any case, just organizing the docs for it.

**Comment by zzzeek** [comment] 2019-03-22 20:52
there was no contract that an empty URL meant anything so I consider this a "feature" (I'm pretty conservative about labeling things "bugs").

**Comment by jvanasco** [comment] 2019-03-22 21:00
is there a concern or use-case for supporting both an empty connection string AND multiple hosts at the same time? it doesn't look like the two are compatible to me.

**Comment by zzzeek** [comment] 2019-03-22 21:15
after reviewing the PR I can see the use case here is more of using PG environment variables to connect, so I think per https://www.postgresql.org/docs/current/libpq-envars.html and https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING naming the "host" as where the multiple hosts go, you could put the multiple hosts in the PG_HOST env var.

**Comment by jvanasco** [comment] 2019-03-22 21:40
i totally agree with that approach. It didn't seem like connecting via both is even possible within libpq, but wanted to avoid potential future complaints.

**Closed** 2019-03-25 19:09 UTC
Labels: engine, feature, postgresql

**Comment by jmehnle** [comment] 2019-04-03 15:09
Thanks folks for picking this up so quickly! Much appreciated.

**Comment by zzzeek** [comment] 2019-04-09 12:53
and #4601 is our first regression, so hopefully this can stay in while also fixing that issue

**Comment by zzzeek** [comment] 2019-04-09 13:12
it seems like if we send *any* parameters of any kind to psycopg2, even things that have nothing to do with where to connect, like "connect_timeout" or an unused argument like "tty", psycopg2 no longer needs the blank "dsn" name.  So I think we will adjust this that if there are any query parameters at all, we still send no blank string for host like we did before.   Please comment on #4601 if there are issues with this.
