### ISSUE TITLE
support postgresql host forms that have a colon in them but are not multihost format

### ISSUE THREAD

**Issue by aebrahim** [sqlalchemy/sqlalchemy#10069] opened 2023-07-05 23:03 UTC
### Describe the bug

We use the [Cloud SQL Proxy](https://cloud.google.com/sql/docs/postgres/connect-auth-proxy#unix-sockets) to mount a connection on the local socket `/cloudsql/my-gcp-project:us-central1:mydbisnstance`. Per the docs, we specify the socket using the host parameter. However, it looks like point release 2.0.18 (I suspect in 6d5cdd1f59415ea8f08efe0f40126b8c384d1125) added a new feature for multiple hosts which breaks the existing connection string.

From semantic versioning, I would expect that 2.0.17 -> 2.0.18 to not break existing parsing.

Thank you for your time and consideration.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#unix-domain-connections

### SQLAlchemy Version in Use

2.0.18

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

Postgresql

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
# This code works in 2.0.17 and fails in 2.0.18
sqlalchemy.create_engine("postgresql://username@password/mydb?host=/cloudsql/my-gcp-project:us-central1:mydbisnstance")
```

### Error

```
File ~/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py:617, in create_engine(url, **kwargs)
    614 dialect = dialect_cls(**dialect_args)
    616 # assemble connection arguments
--> 617 (cargs_tup, cparams) = dialect.create_connect_args(u)
    618 cparams.update(pop_kwarg("connect_args", {}))
    619 cargs = list(cargs_tup)  # allow mutability

File ~/.local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/_psycopg_common.py:134, in _PGDialect_common_psycopg.create_connect_args(self, url)
    131 def create_connect_args(self, url):
    132     opts = url.translate_connect_args(username="user", database="dbname")
--> 134     multihosts, multiports = self._split_multihost_from_url(url)
    136     if opts or url.query:
    137         if not opts:

File ~/.local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py:3124, in PGDialect._split_multihost_from_url(self, url)
   3118 if (
   3119     "port" not in url.query
   3120     and len(hosts) == 1
   3121     and ":" in hosts[0]
   3122 ):
   3123     integrated_multihost = True
-> 3124     h, p = hosts[0].split(":")
   3125     hosts = (h,)
   3126     ports = (p,) if p else (None,)
```

**Comment by zzzeek** [comment] 2023-07-06 13:53
the problem is the colon which was not expected

**Comment by sqla-tester** [comment] 2023-07-06 14:26
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**match on single host/port only for integer port** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4766

**Comment by zzzeek** [comment] 2023-07-06 14:49
hi - 

can I get clarification on the URL that you posted?

``sqlalchemy.create_engine("postgresql://username@password/mydb?host=/cloudsql/my-gcp-project:us-central1:mydbisnstance")``

This is still ambiguous, did you intend for the "password" to be the "hostname"?   This URL won't "work" on SQLAlhcemy 2.0.17 either:

```py
>>> from sqlalchemy import create_engine
>>> e = create_engine("postgresql://username@password/mydb?host=/cloudsql/my-gcp-project:us-central1:mydbisnstance")
>>> e.dialect.create_connect_args(e.url)
([], {'host': '/cloudsql/my-gcp-project:us-central1:mydbisnstance', 'dbname': 'mydb', 'user': 'username'})

```

as you can see, the "password" is silently ignored as it is taken as the "host" and then overwritten from the host argument.

Is this your live production URL scheme?  This will continue to raise an error going forward:

```py
>>> from sqlalchemy import create_engine
>>> e = create_engine("postgresql://username@password/mydb?host=/cloudsql/my-gcp-project:us-central1:mydbisnstance")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in create_engine
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/create.py", line 617, in create_engine
    (cargs_tup, cparams) = dialect.create_connect_args(u)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/_psycopg_common.py", line 134, in create_connect_args
    multihosts, multiports = self._split_multihost_from_url(url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/photon_home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py", line 3157, in _split_multihost_from_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Can't combine fixed host and multihost URL formats

```

AFAICT the above is the correct behavior since there are two hostnames.  

if OTOH you meant for "password" to be an actual password, the URL format would be (as [documented](https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#unix-domain-connections)):

```
>>> e = create_engine("postgresql://username:password@/mydb?host=/cloudsql/my-gcp-project:us-central1:mydbisnstance")
>>> e.dialect.create_connect_args(e.url)
([], {'dbname': 'mydb', 'user': 'username', 'password': 'password', 'host': '/cloudsql/my-gcp-project:us-central1:mydbisnstance'})

```

We will proceed with the current patch if we don't hear from you.

**Comment by cofin** [comment] 2023-07-06 18:26
I too am faced with issues authenticating with the Cloud SQL proxy connection for Google's Cloud SQL databases after upgrading to the latest release.

Here's my connect string:
`postgresql+asyncpg://the_user:the_password@/db-name?host=/cloudsql/google-project-id:google-region:instance-name`

**Comment by cofin** [comment] 2023-07-06 20:17
@zzzeek @aebrahim @sqla-tester should we re-open this?  I tried to run from `main` and I am getting the following error now:

```python
Step #5 - "apply migrations":   File "/workspace/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 1098, in create_connect_args
Step #5 - "apply migrations":     raise exc.ArgumentError(
Step #5 - "apply migrations": sqlalchemy.exc.ArgumentError: All ports are required to be present for asyncpg multiple host URL
```

Should this be a separate issue since it's for `asyncpg` instead of `psycopg2`?  I appears these issues are related.

**Comment by CaselIT** [comment] 2023-07-06 20:25
I can't reproduce. using main your url works correctly
```py
import sqlalchemy as sa
e = sa.create_engine('postgresql+asyncpg://the_user:the_password@/db-name?host=/cloudsql/google-project-id:google-region:instance-name')
print(e.dialect.create_connect_args(e.url))
```
```
([], {'database': 'db-name', 'user': 'the_user', 'password': 'the_password', 'host': '/cloudsql/google-project-id:google-region:instance-name'})
```

**Comment by CaselIT** [comment] 2023-07-06 20:31
nevermind, I was in the wrong main

@zzzeek any reason for supporting this only on psycopg?

**Comment by cofin** [comment] 2023-07-06 20:34
Thanks @CaselIT 

If it would be helpful, I can submit a PR with the same fix that was done for `psycopg2`.  I suspect we need to address this on all pg drivers, though.

**Comment by CaselIT** [comment] 2023-07-06 20:42
sure go ahead

in 6d5cdd1f59415ea8f08efe0f40126b8c384d1125 part the logic was centralized, so it may makes sense handlit it there

**Comment by zzzeek** [comment] 2023-07-06 21:33
> nevermind, I was in the wrong main
> 
> @zzzeek any reason for supporting this only on psycopg?

this is a regression I was fixing.   not sure why the test coverage didnt light up for asyncpg

**Comment by zzzeek** [comment] 2023-07-06 21:33
FYI no PRS please I am fixing this

**Comment by zzzeek** [comment] 2023-07-06 21:33
> sure go ahead
> 
> in [6d5cdd1](https://github.com/sqlalchemy/sqlalchemy/commit/6d5cdd1f59415ea8f08efe0f40126b8c384d1125) part the logic was centralized, so it may makes sense handling it there

hold off please

**Comment by sqla-tester** [comment] 2023-07-06 22:02
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure unix path syntax works for asyncpg as well** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4767

**Closed** 2023-07-07 00:16 UTC
Labels: bug, postgresql, regression, near-term release

**Comment by cofin** [comment] 2023-07-07 00:25
Will do, @zzzeek.  Thanks for the quick work here.

**Comment by zzzeek** [comment] 2023-07-07 00:31
try out the latest main make sure everything is good now

**Comment by cofin** [comment] 2023-07-07 21:14
Everything is working perfectly now.  Thanks again!
