### ISSUE TITLE
Domain name issue while generating alembic revision with Postgres 13

### ISSUE THREAD

**Issue by maxence-corexpert** [sqlalchemy/sqlalchemy#9838] opened 2023-05-25 10:08 UTC
### Describe the bug

While initiating a new database on AWS RDS using Postgres 13.9.
We encountered a weird issue creating a new revision autogeneration with alembic 1.11.1 and sqlalchemy 2.0.15.
The first migration (initiation) is working fine, but as soon as we update our ORM schema and try to generate a new revision  it running `alembic revision --autogenerate -m 'message'` it exit with a DatabaseError after trying to execute the query from the function `_domain_query` in file [postgres base dialect](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/base.py)

The following error state 
`An error occurred (BadRequestException) when calling the ExecuteStatement operation: Array of type 'name' is not supported`

Error seems to come from line 4612 of file [postgres base dialect](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/base.py) where it try to generate an array of postgres custom type "name"

### SQLAlchemy Version in Use

2.0.15

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 13

### Python Version

3.9

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import Column, Integer, String, ARRAY, Date
from sqlalchemy import ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
Base = declarative_base()

def create_db_schema(engine):
    Base.metadata.create_all(engine)

class regions(Base):
    """
    Region either AWS Region or TLZ Regions
    """
    __tablename__ = "regions"
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)

class services(Base):
    __tablename__ = "services"
    id = Column(String(100), primary_key=True)
    name = Column(String, nullable=False)

class accounts(Base):
    __tablename__ = "accounts"
    id = Column(String, primary_key=True)
    owner = Column(String, nullable=False)
    name = Column(String, nullable=False)
    standards = Column(ARRAY(String), nullable=False)

    def __init__(self, id, owner, name, standards):
        self.id = id
        self.owner = owner
        self.name = name
        self.standards = standards


Then update the model an generate a new revision with alembic 1.11
```

### Error

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.9/site-packages/aurora_data_api/__init__.py", line 248, in execute
    res = self._client.execute_statement(**execute_statement_args)
  File "/home/vscode/.local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/vscode/.local/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Array of type 'name' is not supported

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File "/home/vscode/.local/lib/python3.9/site-packages/aurora_data_api/__init__.py", line 258, in execute
    raise self._get_database_error(e) from e
aurora_data_api.exceptions.DatabaseError: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Array of type 'name' is not supported

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/vscode/.local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/command.py", line 236, in revision
    script_directory.run_env()
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "alembic/env.py", line 82, in <module>
    run_migrations_online()
  File "alembic/env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/command.py", line 212, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 562, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 609, in _run_environment
    compare._populate_migration_script(
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 59, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 93, in _produce_net_changes
    comparators.dispatch("schema", autogen_context.dialect.name)(
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/util/langhelpers.py", line 269, in go
    fn(*arg, **kw)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 132, in _autogen_for_tables
    _compare_tables(
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 246, in _compare_tables
    sqla_compat._reflect_table(inspector, t)
  File "/home/vscode/.local/lib/python3.9/site-packages/alembic/util/sqla_compat.py", line 308, in _reflect_table
    return inspector.reflect_table(table, None)
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 1527, in reflect_table
    _reflect_info = self._get_reflection_info(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 2006, in _get_reflection_info
    columns=run(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 1992, in run
    res = meth(filter_names=_fn, **kw)
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 923, in get_multi_columns
    self.dialect.get_multi_columns(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3503, in get_multi_columns
    for d in self._load_domains(
  File "<string>", line 2, in _load_domains
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 97, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 4657, in _load_domains
    result = connection.execute(self._domain_query(schema))
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File "/home/vscode/.local/lib/python3.9/site-packages/aurora_data_api/__init__.py", line 258, in execute
    raise self._get_database_error(e) from e
sqlalchemy.exc.DatabaseError: (aurora_data_api.exceptions.DatabaseError) An error occurred (BadRequestException) when calling the ExecuteStatement operation: Array of type 'name' is not supported
[SQL: SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, pg_catalog.pg_type.typtypmod) AS attype, NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, domain_constraints.condefs, domain_constraints.connames 
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN (SELECT pg_catalog.pg_constraint.contypid AS contypid, array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, :pg_get_constraintdef_1)) AS condefs, array_agg(pg_catalog.pg_constraint.conname) AS connames 
FROM pg_catalog.pg_constraint 
WHERE pg_catalog.pg_constraint.contypid != :contypid_1 GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid 
WHERE pg_catalog.pg_type.typtype = :typtype_1 ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname]
[parameters: {'pg_get_constraintdef_1': True, 'contypid_1': 0, 'typtype_1': 'd'}]``` 

### Additional context

_No response_

**Comment by CaselIT** [comment] 2023-05-25 11:19
Hi

This seems an aws incantation of postgresql, since the normal install has no such error.
Also looking at what `aurora_data_api` is it seems that's used to connect to custom aws things.

What is the actual DB in use here?

I may need to use an appropriate dialect for the driver in use, such as the redshift one if it's indeed using the redshift dialect.

**Comment by maxence-corexpert** [comment] 2023-05-25 11:29
Hi,

Thanks for your quick answer, we use an RDS Aurora Postgres which is indeed a custom AWS engine compatible with Posqtges 13 and more. 
We use it in the available serverless mode provided by AWS which is one of the reason we use the aurora_data_api, which allow us to interact with the DB using http endpoint API.

By the way rolling back to SqlAclhemy 1.4.48 seems to avoid the issue above

Hope I answered your question

**Comment by CaselIT** [comment] 2023-05-25 11:35
Ok, it seems it's not 100% compatible with PG. Try looking if aws offers a driver for sqlalchemy that can be used with it and/or reporting this case if they claim 100% compatibility.

I'll have a query for you to try later to see if we can work around this on sqlalchemy side, by using a cast.

**Comment by CaselIT** [comment] 2023-05-25 12:08
Can you try running the following?

```py

sql = '''
SELECT
    pg_catalog.pg_type.typname AS name,
    pg_catalog.format_type(pg_catalog.pg_type.typbasetype,
    pg_catalog.pg_type.typtypmod) AS attype,
    NOT pg_catalog.pg_type.typnotnull AS nullable,
    pg_catalog.pg_type.typdefault AS "default",
    pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible,
    pg_catalog.pg_namespace.nspname AS schema,
    domain_constraints.condefs,
    domain_constraints.connames 
FROM pg_catalog.pg_type
JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace
LEFT OUTER JOIN (
    SELECT 
        pg_catalog.pg_constraint.contypid AS contypid,
        array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, true)) AS condefs,
        array_agg(pg_catalog.pg_constraint.conname::text) AS connames
    FROM pg_catalog.pg_constraint 
    WHERE pg_catalog.pg_constraint.contypid != 0
    GROUP BY pg_catalog.pg_constraint.contypid
) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid 
WHERE pg_catalog.pg_type.typtype = 'd'
ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
'''

conn = engine.connect()
print(conn.exec_driver_sql(sql).all())
```

Basically it's casing conname to text before doing an array agg. 
If that's enough then I don't think there would be problem adding this change (and looking of there are other similar instances).

**Comment by maxence-corexpert** [comment] 2023-05-25 12:25
Thanks,

I just tried, and everything's working fine with the above query

**Comment by CaselIT** [comment] 2023-05-25 13:02
Ok, thanks for the test

**Comment by sqla-tester** [comment] 2023-05-25 22:17
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve PG reflection compat.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4631

**Comment by CaselIT** [comment] 2023-05-25 22:22
Can you try the above patch to see if there are other issues? You can download the diff from gerrit.

It should be fine to run since it will run all reflection logic
```py
    meta = sa.MetaData()
    meta.reflect(engine)
    print(meta.tables.keys())
```

Thanks!

**Closed** 2023-05-27 13:07 UTC
Labels: postgresql, reflection, use case

**Comment by AndySemenov** [comment] 2023-05-31 17:42
@CaselIT we've had multiple issues with Aurora Data API until we've found out that https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.Data_API.html only officially supports PostgreSQL versions up to 11.16. That might be the cause of all the issues like `ALTER TYPE {enum_name} ADD VALUE {new_enum_label}` queries do not work (there was no such a syntax in those versions). The same for multiple other DDL queries, as well as those versions have a great lack of support of DML functions and types (intersections, ranges, etc...). And, of course, after switching back to `psycopg2` and upgrading our Aurora DB instances to 14.x we've had all the queries running without having them adjusted, rewritten or modified in any other way.

@maxence-corexpert are you sure you have reported the environment correctly since the drawback of such a fix could affect the engines which actually support PostgreSQL 13.x, 14.x and newer versions.

**Comment by maxence-corexpert** [comment] 2023-05-31 17:57
@AndySemenov I confirm that we're using postgres 13.9 along with data API as Aurora Serverless V1 only support Postgres 13, 11 and 10.
Therefore I did not check the limitation for a full support version by Data API. I'll test using a v11.16 to ensure it's working, if yes, we'll consider using 11.16 if not drawback on the project

**Comment by CaselIT** [comment] 2023-05-31 19:27
Hi @AndySemenov, before this issue I had no knowledge of the aurora aws service, so can't really offer any suggestion there. 

Regarding the changes done here they should not affect any PG version, since we are basically transforming a `name` type, that's roughly equivalent to `varchar(64)` into a `text` that's basically `varchar(max)`.
