### ISSUE TITLE
add typed version of to_tsvector and related, as well as REGCONFIG datatype; update docs to show use of REGCONFIG when necessary

### ISSUE THREAD

**Issue by decaz** [sqlalchemy/sqlalchemy#6833] opened 2021-07-30 10:15 UTC
### Describe the bug

FTS functions (`to_tsvector` for instance) doesn't work with asyncpg driver out of the box.

### To Reproduce

```python
import asyncio

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import create_async_engine

engine = create_async_engine('postgresql+asyncpg://...')


async def main():
    async with engine.connect() as conn:
        query = select(func.to_tsvector('english', 'test'))
        await conn.execute(query)


asyncio.run(main())
```

### Error

```
Traceback (most recent call last):                                                                                                                                                                               
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 388, in _prepare_and_execute
    prepared_stmt, attributes = await adapt_connection._prepare(                                                                                                                                                 
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 630, in _prepare
    prepared_stmt = await self._connection.prepare(operation)                                                                                                                                                    
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/asyncpg/connection.py", line 530, in prepare
    return await self._prepare(                                                                                                   
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/asyncpg/connection.py", line 546, in _prepare
    stmt = await self._get_statement(                                                                                                        
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/asyncpg/connection.py", line 375, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedFunctionError: function to_tsvector(character varying, character varying) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 424, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError: <class 'asyncpg.exceptions.UndefinedFunctionError'>: function to_tsvector(character varying, character varying) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/decaz/workspace/tests/asyncpg_fts.py", line 15, in <module>
    asyncio.run(main())
  File "/home/decaz/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/decaz/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/decaz/workspace/tests/asyncpg_fts.py", line 12, in main
    await conn.execute(query)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 405, in execute
    result = await greenlet_spawn(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 424, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: function to_tsvector(character varying, character varying) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT to_tsvector(%s, %s) AS to_tsvector_1]
[parameters: ('english', 'test')]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

### Versions

- OS: Linux
- Python: 3.9.6
- SQLAlchemy: 1.4.22
- Database: PostgreSQL 13.3
- DBAPI: asyncpg 0.23.0

**Comment by CaselIT** [comment] 2021-07-30 10:48
Hi,

Thanks for the report. This is because in general sqlalchemy has to add casts with asyncpg, so the query that gets sent is actually `SELECT to_tsvector($1::varchar, $2::varchar) AS to_tsvector_1` that's clearly wrong in this case.

An (ugly) workaround for now is to use
```py
async def main():
    async with engine.connect() as conn:
        conn.dialect.use_setinputsizes = False
        try:
            query = select(func.to_tsvector('english', 'test'))
            print(await conn.execute(query))
        finally:
            conn.dialect.use_setinputsizes = True
```

@zzzeek is there a way of disabling setinputsizes for a single execution / connection? Ideally this would be automatic.
would creating a  `to_tsvector` with the proper types fix this?

**Comment by decaz** [comment] 2021-07-30 15:46
There is similar problem with `setweight` function too. As it's impossible to call `func.to_tsvector` directly (due to the issue mentioned above) here is example with `TSVECTOR` data already stored in database table:
```python
import asyncio

from sqlalchemy import Column, MetaData, Table, func, select
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.ext.asyncio import create_async_engine

metadata = MetaData()
table = Table('test', metadata, Column('v', TSVECTOR))
engine = create_async_engine('postgresql+asyncpg://...')


async def main():
    async with engine.connect() as conn, conn.begin():
        await conn.run_sync(metadata.drop_all)
        await conn.run_sync(metadata.create_all)
        await conn.execute(table.insert().values({'v': 'test'}))

        query = select(func.setweight(table.c.v, 'A'))
        await conn.execute(query)


asyncio.run(main())
```

Error:
```
Traceback (most recent call last):                                                                                                                                                                               
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 388, in _prepare_and_execute                                                 
    prepared_stmt, attributes = await adapt_connection._prepare(                                                                                                                                                 
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 630, in _prepare                                                             
    prepared_stmt = await self._connection.prepare(operation)                                                                                                                                                    
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/asyncpg/connection.py", line 530, in prepare                                                                                  
    return await self._prepare(                                                                                                                                                                                  
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/asyncpg/connection.py", line 546, in _prepare                                                                                 
    stmt = await self._get_statement(                                                                                                                                                                            
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/asyncpg/connection.py", line 375, in _get_statement                                                                           
    statement = await self._protocol.prepare(                                                                                                                                                                    
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedFunctionError: function setweight(tsvector, character varying) does not exist                                                                                                        
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
                                                                                                                                                                                                                 
The above exception was the direct cause of the following exception:
                                                                                                                                                                                                                 
Traceback (most recent call last):
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context                                                                    
    self.dialect.do_execute(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute                                                                        
    cursor.execute(statement, parameters)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute                                                              
    self._adapt_connection.await_(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only                                                                 
    return current.driver.switch(awaitable)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn                                                            
    value = await result
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 424, in _prepare_and_execute                                                 
    self._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception                                                    
    self._adapt_connection._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError: <class 'asyncpg.exceptions.UndefinedFunctionError'>: function setweight(tsvector, character varying) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/decaz/workspace/tests/asyncpg_fts.py", line 22, in <module>
    asyncio.run(main())
  File "/home/decaz/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/decaz/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/decaz/workspace/tests/asyncpg_fts.py", line 19, in main
    await conn.execute(query)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 405, in execute
    result = await greenlet_spawn(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 424, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 358, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/decaz/workspace/tests/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: function setweight(tsvector, character varying) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT setweight(test.v, %s) AS setweight_1
FROM test]
[parameters: ('A',)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

Also I have to mention that there are no problems with psycopg2 driver.

**Comment by CaselIT** [comment] 2021-07-30 15:57
The issue is the same, and the workaround is as above

> Also I have to mention that there are no problems with psycopg2 driver.

for psycopg2 sqlalchemy don't have to use casting, so it does erroneously casts the query

**Comment by sqla-tester** [comment] 2021-08-04 13:58
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**consider omitting casting for asyncpg STRING** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2991

**Comment by zzzeek** [comment] 2021-08-04 17:37
so within the test suite the failures seem to be all related to `select count('*')`, where the datatype of the asterisk is failing.

A really silly miss of the datatype for that is why we have the `::varchar` in there.   i dont really know of a good way to keep this straight if the driver / database is going to be this fickle, and there will be a lot more misses if i make this change.  

therefore I think solution here is that very specific functions like these are rendered with the correct types.     we can add new to_tsvector calls as we have a lot of [docs](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#full-text-search) for these already, or at least add the "REGCONFIG" datatype and provide code examples as is in the following, which works for asyncpg:

```py
import asyncio

from sqlalchemy import func, select, cast, type_coerce
from sqlalchemy.types import UserDefinedType

from sqlalchemy.ext.asyncio import create_async_engine

engine = create_async_engine('postgresql+asyncpg://scott:tiger@localhost/test', echo=True)

class REGCONFIG(UserDefinedType):
    def get_col_spec(self, **kw):
        return "regconfig"

async def main():
    async with engine.connect() as conn:
        query = select(func.to_tsvector(type_coerce('english', REGCONFIG), 'test'))
        await conn.execute(query)


asyncio.run(main())
```

**Comment by decaz** [comment] 2021-08-04 17:48
Currently I have the following workaround for this:
```python
class RegConfig(UserDefinedType):
    """regconfig type for FTS.

    https://www.postgresql.org/docs/13/datatype-oid.html#DATATYPE-OID-TABLE
    """

    def get_col_spec(self, **kwargs: Any) -> str:
        return 'regconfig'


class SingleByteChar(UserDefinedType):
    """1 byte "char" type.

    https://www.postgresql.org/docs/current/datatype-character.html
    #DATATYPE-CHARACTER-SPECIAL-TABLE
    """

    def get_col_spec(self, **kwargs: Any) -> str:
        return '"char"'

    def bind_processor(
        self, dialect: PGDialect
    ) -> Callable[[str], Union[str, bytes]]:

        def process(value: str) -> Union[str, bytes]:
            if dialect.driver == 'asyncpg':
                return value.encode()
            return value

        return process
```

And use them in the following way:
```python
tsvector = func.to_tsvector(cast('english', RegConfig), 'test')
weight = func.setweight(tsvector, cast('A', SingleByteChar))
```

**Comment by zzzeek** [comment] 2021-08-12 14:23
asyncpg needs it that specifically huh?  then yes we need all of that.

if we can make #3160 part of this as well that would be helpful.

**Comment by CaselIT** [comment] 2021-08-12 14:29
> asyncpg needs it that specifically huh? then yes we need all of that.

as mentioned, I think psycopg3 will also be very similar here, since it will use prepared statements by default

**Comment by zzzeek** [comment] 2021-08-12 14:31
does pg8000 have all these limitations right now?

**Comment by CaselIT** [comment] 2021-08-12 14:32
Don't know, I've not tried it

**Comment by CaselIT** [comment] 2021-08-12 14:34
> 
> 
> > asyncpg needs it that specifically huh? then yes we need all of that.
> 
> as mentioned, I think psycopg3 will also be very similar here, since it will use prepared statements by default

Sorry I meant server side binding of parameters. I don't know regarding prepared statements or not, but it should be the ss binding that's causing the problem here

**Comment by tlocke** [comment] 2023-06-15 08:27
I tried to reproduce the initial bug:

```
import asyncio

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import create_async_engine

engine = create_async_engine("postgresql+asyncpg://...")
    
    
async def main():
    async with engine.connect() as conn:
        query = select(func.to_tsvector("english", "test"))
        await conn.execute(query)


asyncio.run(main())
```

with versions:

asyncpg==0.27.0
SQLAlchemy==2.0.16
PostgreSQL 14.8

but it worked fine, so presumably it's been fixed? I also tried it with pg8000:

```
from sqlalchemy import create_engine, func, select

engine = create_engine("postgresql+pg8000://...")

with engine.connect() as conn:
    query = select(func.to_tsvector("english", "test"))
    conn.execute(query)
```

and again it worked okay.

**Comment by CaselIT** [comment] 2023-06-15 09:16
Thanks for the test.
I think this was fixed in version 2 since it will render cast in almost every case for PG in these dialects (iirc not psycopg2 since it does not need them)

I think it can be closed then

**Comment by CaselIT** [comment] 2023-06-15 22:12
Indeed the casting fixed id:
```sql
-- psycopg3
SELECT to_tsvector(%(to_tsvector_2)s::REGCONFIG, %(to_tsvector_3)s::VARCHAR) AS to_tsvector_1
-- asyncpg
SELECT to_tsvector($1::REGCONFIG, $2::VARCHAR) AS to_tsvector_1
-- pg8000
SELECT to_tsvector(%s, %s::VARCHAR) AS to_tsvector_1
```

**Comment by CaselIT** [comment] 2023-06-15 22:12
thanks again for checking @tlocke

**Closed by CaselIT** 2023-06-15 22:12 UTC
Labels: bug, postgresql, full text search

**Comment by AgarwalPragy** [comment] 2023-11-21 18:52
> Currently I have the following workaround for this:
> 
> ```python
> class RegConfig(UserDefinedType):
>     """regconfig type for FTS.
> 
>     https://www.postgresql.org/docs/current/datatype-oid.html
>     #DATATYPE-OID-TABLE
>     """
> 
>     def get_col_spec(self, **kwargs: Any) -> str:
>         return 'regconfig'
> 
> 
> class SingleByteChar(UserDefinedType):
>     """1 byte "char" type.
> 
>     https://www.postgresql.org/docs/current/datatype-character.html
>     #DATATYPE-CHARACTER-SPECIAL-TABLE
>     """
> 
>     def get_col_spec(self, **kwargs: Any) -> str:
>         return '"char"'
> 
>     def bind_processor(
>         self, dialect: PGDialect
>     ) -> Callable[[str], Union[str, bytes]]:
> 
>         def process(value: str) -> Union[str, bytes]:
>             if dialect.driver == 'asyncpg':
>                 return value.encode()
>             return value
> 
>         return process
> ```
> 
> And use them in the following way:
> 
> ```python
> tsvector = func.to_tsvector(cast('english', RegConfig), 'test')
> weight = func.setweight(tsvector, cast('A', SingleByteChar))
> ```
> 
> @zzzeek what do you think about this?

Is this the recommended solution for setting weights?

**Comment by decaz** [comment] 2024-01-26 11:33
`regconfig` is now supported by the latest version (2.0) out of the box.

Custom 1 byte "char" type (`SingleByteChar` class above) is still needed to use `setweight` function.

@zzzeek @CaselIT am I right?

**Comment by CaselIT** [comment] 2024-01-26 15:37
In a way yes, since `to_tsvector` and some other popular function have the correct casting to regconfig. For unsupported functions the `type_coerce` solution is still available https://github.com/sqlalchemy/sqlalchemy/issues/6833#issuecomment-892844560, but the regconfig from sqlalchemy can be used.
