### ISSUE TITLE
repair unusual ColumnArgumentRole used in case(), this is only meant for ORM cases 

### ISSUE THREAD

**Issue by denisahearn** [sqlalchemy/sqlalchemy#7287] opened 2021-11-03 16:49 UTC
### Describe the bug

A `TypeDecorator` class that is working correctly with sqlalchemy 1.3.x is crashing with sqlalchemy 1.4.x with a `sqlalchemy.exc.ArgumentError: Column expression expected, got <sqlalchemy.sql.elements.TextClause object at 0x10702aad0>` exception.

### To Reproduce

```python
from sqlalchemy import Column, String, Integer, case, func, text, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.orm import sessionmaker
from sqlalchemy.types import TypeDecorator

WIDGET_CASES = ['lower', 'upper']

Base = declarative_base()

class DecoratedName(TypeDecorator):
    impl = String

    def column_expression(self, colexpr):
        return case(
            [
                (text(":case = 'upper'"), func.upper(colexpr))
            ],
            else_=func.lower(colexpr)
        )


class Widget(Base):
    __tablename__ = 'widgets'

    id = Column(Integer, primary_key=True)
    name = Column(DecoratedName(255), nullable=False)
    case = Column(ENUM(*WIDGET_CASES))


db_string = "postgresql:///sqlalchemy-bug"
engine = create_engine(db_string, connect_args={'connect_timeout': 10}, echo=False)
session = sessionmaker(bind=engine)()

# Insert a widget into the database
widget_id = 1
widget = Widget(id=widget_id, name='widget 1', case='lower')
session.query(Widget).filter_by(id=widget_id).delete()
session.add(widget)
session.flush()
session.commit()

# Extract the widget from the database.
# This code works with sqlalchemy 1.3, crashes with sqlalchemy 1.4.
widget_out = session.\
    query(Widget).\
    params(case='upper').\
    filter_by(id=widget_id).\
    one()

print(f'Widget name = {widget_out.name}')
```

### Error

```
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    filter_by(id=widget_id).\
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2808, in one
    return self._iter().one()
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2849, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 526, in _compile_w_cache
    **kw
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 555, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 761, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3290, in visit_select
    ) in compile_state.columns_plus_names
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3289, in <listcomp>
    repeated,
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2965, in _label_select_column
    col_expr = impl.column_expression(column)
  File "main.py", line 19, in column_expression
    else_=func.lower(colexpr)
  File "<string>", line 2, in case
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 2975, in __init__
    for (c, r) in whens
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 2975, in <listcomp>
    for (c, r) in whens
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/coercions.py", line 212, in expect
    original_element, resolved, argname=argname, **kw
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/coercions.py", line 254, in _implicit_coercions
    self._raise_for_expected(element, argname, resolved)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/sql/coercions.py", line 282, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "/Users/denisahearn/Library/Caches/pypoetry/virtualenvs/sqlalchemy-bug-xulG5YFe-py3.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression expected, got <sqlalchemy.sql.elements.TextClause object at 0x10702aad0>.
``` 

### Versions

- OS: macOS 11.6
- Python: 3.7.4
- SQLAlchemy: 1.4.26
- Database: PostgreSQL 10.2.5
- DBAPI: psycopg2

### Additional context

The attached zip file contains a small sample python app that demonstrates the issue:

[sqlalchemy-bug.zip](https://github.com/sqlalchemy/sqlalchemy/files/7469305/sqlalchemy-bug.zip)

The README.md in the zip file explains how to set up and run the sample app to demonstrate the issue. The README also describes different bash scripts you can use to run the same version of PostgreSQL that we are using (via Docker) and for creating a database for the sample app to use.

If you edit `pyproject.toml` and change `sqlalchemy = "1.3.24"` then the app should run successfully. If sqlalchemy = "1.4.26" then the app should crash as described above. Make sure to run `poetry update` after editing `pyproject.toml`.

**Comment by zzzeek** [comment] 2021-11-03 16:54
hey there -

the error message describes the problem, which is that it's looking for a column expression, not text(), the latter of which describes a SQL statement.   For textual column expressions, use `literal_column()`, this is mentioned in the docs for case:

```py
from sqlalchemy import case
from sqlalchemy import func
from sqlalchemy import literal_column

colexpr = literal_column('asdf')
expr = case(
    [
        (literal_column(":case = 'upper'"), func.upper(colexpr))
    ], else_=func.lower(colexpr)
)

print(expr)
```

**Comment by CaselIT** [comment] 2021-11-03 20:34
Hi,

I think you may replace it with
```py
case(
            [
                (sa.bindparam('case') == 'upper'), func.upper(colexpr))
            ],
            else_=func.lower(colexpr)
)
```

but I'm not 100% sure it will work

**Comment by denisahearn** [comment] 2021-11-03 22:18
@CaselIT `bindparam` did indeed work for us, thanks so much for the suggestion!

One suggestion - it would be nice if the documentation for the `case` method showed an example with a bind parameter using `bindparam`. Had there been an example like this I think I may have been able to find this solution myself. Might save the next developer a little time.

**Comment by CaselIT** [comment] 2021-11-03 22:28
If you want to try opening a pr i think it would be appreciated!

**Comment by zzzeek** [comment] 2021-11-04 01:02
`select()` accepts `text()` in the columns clause, so text() should work in any expression element role location as there is no other way to have a textual phrase with bound parameters inside of it.

**Comment by zzzeek** [comment] 2021-11-04 01:11
nevermind, it is actually the wrong role used in exactly this one place inside of case() for some reason, a regression indeed.

**Comment by zzzeek** [comment] 2021-11-04 01:19
it looks like it's trying to guard against some other kind of input taht otherwise becomes a bound parameter.  but i think we just have to open it up again.

**Comment by sqla-tester** [comment] 2021-11-04 01:32
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use ExpressionElementRole for case targets in case()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3269

**Comment by sqla-tester** [comment] 2021-11-04 01:32
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**use ExpressionElementRole for case targets in case()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3270

**Comment by zzzeek** [comment] 2021-11-04 01:36
the case statement had some special thing happening there trying to guard against perhaps tuples where it maybe was trying to guess if the programmer was misunderstanding the API.   it seems like a really unique and specific exception case and im not sure of the rationale for it, so let's try not having it for awhile.

**Comment by zzzeek** [comment] 2021-11-04 02:01
OK the history of it raising an error for `case([("x", "y")])` goes back to the beginning of time, at least as far back as 0.4, which means it isn't based on any modern use case, it was likely just a guess on my part that such a case should raise an error.   the recent change that prevented it from accepting text() was my porting this logic and trying to maintain the old behavior, so i used an unusual role that "seemed to work", but there's no reason any of this should be here.

**Closed** 2021-11-04 15:03 UTC
Labels: bug, sql, regression

**Comment by zzzeek** [comment] 2021-11-04 15:05
so anyway, yes, it was a regression, there was a very unusual parsing element used just in case() and nowhere else, so when I saw the error I had assumed this was just how all column expression constructs had been locked down, but I was mistaken. it was just case().
