### ISSUE TITLE
Many-to-many relationship returning nonsense for dynamic relationships of polymorphic classes

### ISSUE THREAD

**Issue by mjr129** [sqlalchemy/sqlalchemy#4405] opened 2018-12-11 16:30 UTC
### Problem
I am getting odd results when querying `lazy = "dynamic"` relationships within polymorphic classes.

Setting `lazy = "select"` or removing the polymorphism results in the expected results.

I have included a complete minimal working example below, which fails for the fourth test case.

### My output
```
TEST POLYMORPHIC = False DYNAMIC = False
a = 3: Road1, Road2, Road3
b = 3: Car1, Car2, Car3
TEST POLYMORPHIC = True DYNAMIC = False
a = 3: Road1, Road2, Road3
b = 3: Car1, Car2, Car3
TEST POLYMORPHIC = False DYNAMIC = True
a = 3: Road1, Road2, Road3
b = 3: Car1, Car2, Car3
TEST POLYMORPHIC = True DYNAMIC = True
a = 6: Car1, Car1, Car1, Road1, Road1, Road1
b = 6: Car1, Car1, Car1, Road1, Road1, Road1
AssertionError
```

### Code
```
def test( polymorphic = True, dynamic = True ):
    print( "TEST POLYMORPHIC = {} DYNAMIC = {}".format( polymorphic, dynamic ) )
    
    from sqlalchemy import create_engine, Column, Integer, ForeignKey
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy.orm import relationship, sessionmaker
    
    lazy = "dynamic" if dynamic else "select"
    Base = declarative_base()
    
    if polymorphic:
        class Entity( Base ):
            __tablename__ = "entity"
            entity_id = Column( Integer, primary_key = True )
            type = Column( Integer )
            
            __mapper_args__ = { "polymorphic_identity": 0, "polymorphic_on": type }
    else:
        Entity = Base
    
    
    class Car( Entity ):
        __tablename__ = "car"
        
        if polymorphic:
            parent_id = Column( Integer, ForeignKey( Entity.entity_id ) )
            __mapper_args__ = { "polymorphic_identity": 1 }
        
        car_id = Column( Integer, primary_key = True )
        roads = relationship( "Road", foreign_keys = lambda: (Travel.car_id, Travel.road_id), back_populates = "cars", secondary = "travel", lazy = lazy )
        
        
        def __str__( self ):
            return "Car{}".format( self.car_id )
    
    
    class Road( Entity ):
        __tablename__ = "road"
        
        if polymorphic:
            parent_id = Column( Integer, ForeignKey( Entity.entity_id ) )
            __mapper_args__ = { "polymorphic_identity": 2 }
        
        road_id = Column( Integer, primary_key = True )
        cars = relationship( Car, foreign_keys = lambda: (Travel.car_id, Travel.road_id), back_populates = "roads", secondary = "travel", lazy = lazy )
        
        
        def __str__( self ):
            return "Road{}".format( self.road_id )
    
    
    class Travel( Base ):
        __tablename__ = "travel"
        
        if polymorphic:
            parent_id = Column( Integer, ForeignKey( Entity.entity_id ) )
            __mapper_args__ = { "polymorphic_identity": 3, 'inherit_condition': parent_id == Entity.entity_id }
        
        travel_id = Column( Integer, primary_key = True )
        car_id = Column( Integer, ForeignKey( Car.car_id ) )
        road_id = Column( Integer, ForeignKey( Road.road_id ) )
        
        
        def __str__( self ):
            return "Travel{}".format( self.travel_id )
    
    
    engine = create_engine( 'sqlite:///:memory:' )
    Base.metadata.create_all( engine )
    Session = sessionmaker( bind = engine )
    session = Session()
    
    car1 = Car( car_id = 1 )
    car2 = Car( car_id = 2 )
    car3 = Car( car_id = 3 )
    road1 = Road( road_id = 1 )
    road2 = Road( road_id = 2 )
    road3 = Road( road_id = 3 )
    travels1 = Travel( travel_id = 1, car_id = 1, road_id = 1 )
    travels2 = Travel( travel_id = 2, car_id = 1, road_id = 2 )
    travels3 = Travel( travel_id = 3, car_id = 1, road_id = 3 )
    travels4 = Travel( travel_id = 4, car_id = 2, road_id = 1 )
    travels5 = Travel( travel_id = 5, car_id = 2, road_id = 2 )
    travels6 = Travel( travel_id = 6, car_id = 3, road_id = 1 )
    session.add( car1 )
    session.add( car2 )
    session.add( car3 )
    session.add( road1 )
    session.add( road2 )
    session.add( road3 )
    session.add( travels1 )
    session.add( travels2 )
    session.add( travels3 )
    session.add( travels4 )
    session.add( travels5 )
    session.add( travels6 )
    session.commit()
    
    a = session.query( Car ).filter( Car.car_id == 1 ).first().roads
    b = session.query( Road ).filter( Road.road_id == 1 ).first().cars
    
    if dynamic:
        a = a.all()
        b = b.all()
    
    message1 = "a = {}: {}".format( len( a ), ", ".join( str( x ) for x in a ) )
    message2 = "b = {}: {}".format( len( b ), ", ".join( str( x ) for x in b ) )
    
    print( message1 )
    print( message2 )
    
    assert "Road1" in message1 and "Road2" in message1 and "Road3" in message1
    assert "Car1" in message2 and "Car2" in message2 and "Car3" in message2


test( polymorphic = False, dynamic = False )
test( polymorphic = True, dynamic = False )
test( polymorphic = False, dynamic = True )
test( polymorphic = True, dynamic = True )
```

**Comment by zzzeek** [comment] 2018-12-11 21:45
thanks for the complete test case.   this appears the issue that was just fixed in #4363, your test case fails on rel_1_2_14 and passes on rel_1_2 for 1.2.15 that hasn't been released yet.   Please use 1.2.12 until 1.2.15 is relased, thanks

**Comment by zzzeek** [comment] 2018-12-11 21:47
dupe of #4363, test case falis in rel_1_2_13 and rel_1_14 only

**Closed by zzzeek** 2018-12-11 21:47 UTC
Labels: bug, duplicate, orm

**Comment by zzzeek** [comment] 2018-12-11 22:09
1.2.15 is now released.
