### ISSUE TITLE
Sequence not executed for MSSQL

### ISSUE THREAD

**Issue by Lakshay-Awasthi** [sqlalchemy/sqlalchemy#4627] opened 2019-04-24 10:17 UTC
seq = Sequence('COUNTER_VAL')
seqValue = db.session.execute( seq, bind=db.get_engine(app, 'test_db'))

while executing above statement for mssql db getting below error (it is working fine for postgresql)

File "D:\FAQ_PROJECT\TFS_REPO\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
return getattr(self.registry(), name)(*args, **kwargs)
File "D:\FAQ_PROJECT\TFS_REPO\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1170, in execute
bind, close_with_result=True).execute(clause, params or {})
File "D:\FAQ_PROJECT\TFS_REPO\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
return meth(self, multiparams, params)
File "D:\FAQ_PROJECT\TFS_REPO\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 2003, in _execute_on_connection
return connection._execute_default(self, multiparams, params)
File "D:\FAQ_PROJECT\TFS_REPO\venv\lib\site-packages\sqlalchemy\engine\base.py", line 980, in _execute_default
ret = ctx._exec_default(None, default, None)
File "D:\FAQ_PROJECT\TFS_REPO\venv\lib\site-packages\sqlalchemy\engine\default.py", line 1182, in exec_default
return self.fire_sequence(default, type)
AttributeError: 'MSExecutionContext' object has no attribute 'fire_sequence'

**Comment by zzzeek** [comment] 2019-04-25 00:22
ok

**Comment by zzzeek** [comment] 2019-04-25 00:28
oh.  sorry, this is an unimplemented feature as there is no supports_sequences flag on the MSSQL dialect, which means there is no test support, which means this is not ready to go yet.   Issue #4325 is for full sequence support in SQL server and it can only be in 1.4, becuase we had to deprecated the use of "sequence" for IDENTITY column control in 1.3.

so for the PR I would need the "supports_sequences" flag on the MSSQL dialect, and then all the tests that come online as a result would need to pass.

**Comment by zzzeek** [comment] 2019-04-25 00:28
dupe of #4235

**Closed by zzzeek** 2019-04-25 00:28 UTC
Labels: SQL Server, bug, duplicate
