### ISSUE TITLE
In 1.4, invalid SQL is generated when using `.with_entities` to get a `.join`ed model

### ISSUE THREAD

**Issue by dbanty** [sqlalchemy/sqlalchemy#6503] opened 2021-05-18 15:56 UTC
If you query a model (e.g. with `session.query`) and filter on it, then join to a second model with `.join`, then use `.with_entities` to select that second model (the one you just joined to), SQLAlchemy will include the _second_ model in the `FROM` clause. This can cause issues later in the query. Version 1.3 did not include that second model in `FROM`.

## Example
If you run this code:

```python
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

DeclarativeBase = declarative_base()
Session = sessionmaker()
session = Session()


class First(DeclarativeBase):
    __tablename__ = "first"

    pk = sa.Column(sa.Integer, primary_key=True)


class Mapper(DeclarativeBase):
    __tablename__ = "mapper"

    pk = sa.Column(sa.Integer, primary_key=True)
    first_pk = sa.Column(sa.Integer, sa.ForeignKey("first.pk"), nullable=False)
    second_pk = sa.Column(sa.Integer, sa.ForeignKey("second.pk"), nullable=False)


class Second(DeclarativeBase):
    __tablename__ = "second"

    pk = sa.Column(sa.Integer, primary_key=True)


query = session.query(First).filter(First.pk != 1).join(
    Mapper,
    Mapper.first_pk == First.pk,
).join(
    Second,
    Second.pk == Mapper.second_pk,
).with_entities(Second)

if __name__ == "__main__":
    print(query.statement)
```

You get an output of:

```sql
SELECT second.pk 
FROM first, second JOIN mapper ON mapper.first_pk = first.pk JOIN second ON second.pk = mapper.second_pk 
WHERE first.pk != :pk_1
```

This is invalid, as the first `JOIN` references the table in the first `FROM`. Running this query in Postgresql gives an error message like:

`invalid reference to FROM-clause entry for table "first" Hint: There is an entry for table "first", but it cannot be referenced from this part of the query.`

In SQLAlchemy 1.3.23 I get this perfectly valid SQL output instead:

```sql
SELECT second.pk 
FROM first JOIN mapper ON mapper.first_pk = first.pk JOIN second ON second.pk = mapper.second_pk 
WHERE first.pk != :pk_1
```

In my case I think I can pretty easily work around the issue by rewriting the query but I figured I should report it since a straight upgrade caused a test to fail 😅. Thanks!

**Versions.**
 - OS: macOS 11.3.1
 - Python: 3.8.9
 - SQLAlchemy: 1.4.15
 - Database: Postgres 10.12
 - DBAPI: psycopg2

**Comment by zzzeek** [comment] 2021-05-18 16:31
this is essentially a duplicate of #6253.   as noted, you should do query(First).select_from(First).join(...) to do what you need.       unlike #6253 though there at least is a chance this can be improved by storing the "joinpoint" along with the join info when join() is called, so I will add this to our current list but long term I see Query and with_entities overall as legacy.

**Comment by zzzeek** [comment] 2021-05-18 16:32
this is an exact dupblicate of #6089, in that case I just closed it.

**Comment by dbanty** [comment] 2021-05-18 16:36
Great, thanks for responding so promptly!

**Comment by na-ka-na** [comment] 2021-06-15 05:57
Also trying to upgrade from 1.3 to 1.4 and many of our tests are failing due to this issue.

Is this expected to resolve any time soon?

**Comment by zzzeek** [comment] 2021-06-15 13:27
it's on the short list for sure as I've formulated a way to work it out, it's more than a one-liner though.

are your issues related to either eager load options and/or .join()?  those are the two areas of functionality that I seek to add explicit structures for.

**Comment by na-ka-na** [comment] 2021-06-15 16:49
It's related to the join - exactly similar issue as reported in this ticket - where an extra table gets added in the FROM clause

**Comment by sqla-tester** [comment] 2021-06-15 20:14
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**memoize current options and joins w with_entities/with_only_cols** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2871

**Comment by zzzeek** [comment] 2021-06-18 14:39
hi @na-ka-na and @dbanty  - this is merged to SQLAlchemy master.  if you can test with the master branch ASAP to make sure this solves your issue that would be very helpful.

**Closed** 2021-06-18 14:38 UTC
Labels: bug, orm, regression, with_entities change

**Comment by na-ka-na** [comment] 2021-06-20 22:03
@zzzeek Yes! confirmed that the tests pass now

**Comment by na-ka-na** [comment] 2021-06-23 01:03
@zzzeek I'm facing this error now:

'Sequence' object has no attribute '_execution_options'

I built from hash `73573a6fda1c3ebde27a169199b1f33fccb1e415`. Is there a ticket for this already, or is this fixed?

**Comment by zzzeek** [comment] 2021-06-23 01:06
> @zzzeek I'm facing this error now:
> 
> 'Sequence' object has no attribute '_execution_options'
> 
> I built from hash `73573a6fda1c3ebde27a169199b1f33fccb1e415`. Is there a ticket for this already, or is this fixed?

I know nothing about that error.

**Comment by na-ka-na** [comment] 2021-06-23 18:40
https://github.com/sqlalchemy/sqlalchemy/issues/6668
