### ISSUE TITLE
Now I have encountered a more confused problem

### ISSUE THREAD

**Issue by psqjgsw45** [sqlalchemy/sqlalchemy#10241] opened 2023-08-16 03:08 UTC
Now I have encountered a more confused problem
My code is below
SQLAlchemy  1.4.48
```
SQLALCHEMY_DATABASE_URI: str = f"mysql+pymysql://{mysql_user}:{mysql_pwd}@{mysql_ip}:3306/{mysql_database}?charset=utf8"
engine = create_engine(SQLALCHEMY_DATABASE_URI,pool_pre_ping=True, max_overflow=16300, pool_recycle=300)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
session = scoped_session(SessionLocal)
# Sends a heartbeat every 30 seconds like mysql
def task_mysql_keep_alive():
    logger.debug ('task_mysql_keep_alive', datetime.now())
    pool = SessionLocal().bind.pool
    active_connections = pool.checkedin()  
    session.execute(text('SELECT 1'))
    session.close()

```
After about 10 hours or so, once again request interface will be submitted to the pymysql. Err. OperationalError: (2013, 'Lost connection to MySQL server during query ")
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
```@router.get("/test/async")
async def test(session=Depends(get_db)):
    session.query(Organization).filter()
    return dict(code=200, msg='success')
def get_db():
    connect_control = settings.CONNECT_CONTROL

    try:

        yield session
    
        session.commit()
    except HTTPException_Error:
        session.rollback()
    except Exception as e:
        logger.exception(e)
        session.rollback()
    finally:
        session.close()
  ```

_Originally posted by @psqjgsw45 in https://github.com/sqlalchemy/sqlalchemy/discussions/10240_

**Comment by CaselIT** [comment] 2023-08-16 06:37
Duplicate of the discussion.

**Closed by CaselIT** 2023-08-16 06:37 UTC

**Comment by psqjgsw45** [comment] 2023-08-16 07:44
What do you mean by that? @CaselIT

**Comment by psqjgsw45** [comment] 2023-08-16 08:51
Which version solves this problem? I was hoping you could tell me @psqjgsw45

**Comment by psqjgsw45** [comment] 2023-08-16 08:51
Which version solves this problem? I was hoping you could tell me @CaselIT

**Comment by CaselIT** [comment] 2023-08-16 09:13
I closed since you opened also a discussion with the same description. There is no need to duplicate things

**Comment by psqjgsw45** [comment] 2023-08-16 09:23
Okay. I'll look again. Thank you very much
