### ISSUE TITLE
Table Already Exists Error With sqlite + metadata.create_all(checkfirst=True) 

### ISSUE THREAD

**Issue by DavidMuller** [sqlalchemy/sqlalchemy#4936] opened 2019-10-22 18:07 UTC
Hello - thanks for all the hard work on sqlalchemy!

I have an application where a handful of processes all interact with a single sqlite DB: `foo.db`. `foo.db` starts with 0 tables, and each process "lazily" bootstraps `foo.db` with a table named `"some_table"`. 

I notice, however, that when multiple processes call `metadata.create_all(checkfirst=True)` to try and create `"some_table"` in `foo.db`...sqlalchemy winds up raising an `OperationalError` "table already exists" error.

In other words, running this script...

```python
import concurrent.futures

from sqlalchemy import create_engine, Table, Column, Integer, MetaData


def make_db():
    engine = create_engine("sqlite:///foo.db")
    metadata = MetaData()
    Table(
        "some_table",
        metadata,
        Column("id", Integer, primary_key=True),
    )
    metadata.create_all(bind=engine, checkfirst=True)


def main():
    n = 3
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = [executor.submit(make_db) for _ in range(n)]
        for future in concurrent.futures.as_completed(futures):
            future.result()


if __name__ == "__main__":
    main()
```

... yields the following error:

```python
Traceback (most recent call last):
  File "sqlite_multiprocessing_create.py", line 26, in <module>
    main()
  File "sqlite_multiprocessing_create.py", line 22, in main
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table some_table already exists
[SQL: 
CREATE TABLE some_table (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Of course, an obvious workaround would be to have, "the parent process bootstrap tables in `foo.db`. Is it possible, however, to instruct sqlalchemy to use the [`if not exists` clause that sqlite supports](https://www.sqlite.org/lang_createtable.html)? 

I've read [through the notes on sqlite / `pysqlite` 's DDL semantics](https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#pysqlite-serializable), but hadn't found a nice workaround.

**Comment by zzzeek** [comment] 2019-10-22 22:51
this is a dupe of #2843.      Adding the constructs to ``CreateTable``, ``DropTable``, ``CreateIndex``, ``DropIndex``, ``CreateSequence``, ``DropSequence``, implementing for all dialects that support it, and tests is the basic job.  also note people there are doing the same thing (which I don't recommend), creating duplicate SQLite tables in multiple processes.

**Comment by zzzeek** [comment] 2019-10-22 22:53
for now I'd either use a ``@compiles`` recipe around ``CreateTable``, see https://docs.sqlalchemy.org/en/13/core/compiler.html#synopsis, or just use a lockfile (or the sqlite database itself as a lock file.   I would think sqlite has some concurrency options as well for this use case).

**Comment by zzzeek** [comment] 2019-10-22 22:53
we can keep discussion going on #2843.

**Closed by zzzeek** 2019-10-22 22:53 UTC
Labels: duplicate

**Comment by DavidMuller** [comment] 2019-10-23 17:43
> [for now I'd either use a @compiles recipe around CreateTable, see https://docs.sqlalchemy.org/en/13/core/compiler.html#synopsis](https://github.com/sqlalchemy/sqlalchemy/issues/4936#issuecomment-545189643)

This is a `@compiles` recipe I came up with to inject `IF NOT EXISTS` into sqlite `CREATE TABLE` DDL statements (based on @zzzeek 's above pointer):

```python
import re

from sqlalchemy.ext.compiler import compiles
from sqlalchemy.schema import CreateTable
from sqlalchemy import create_engine, Table, Column, Integer, MetaData


class CreateTableIfNotExists(CreateTable):
    pass


@compiles(CreateTableIfNotExists)
def compile_create_table_if_not_exists(element, ddlcompiler, **kw):
    default_create_ddl = ddlcompiler.visit_create_table(element, **kw)
    default_create_ddl = default_create_ddl.lstrip()
    create_if_not_exists = re.sub(
        r"^CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", default_create_ddl, flags=re.IGNORECASE
    )
    return create_if_not_exists


engine = create_engine("sqlite:///" + "foo.db")
metadata = MetaData()
table = Table(
    "some_table",
    metadata,
    Column("id", Integer, primary_key=True),
)
engine.execute(CreateTableIfNotExists(table))
```

Regex is obviously not the greatest, but wanted to share the code in case its useful to others as an example

(Can move this comment over to #2843 too @zzzeek , but didn't want to sidetrack that issue)

**Comment by zzzeek** [comment] 2019-10-23 17:48
yes regex is kind of how it goes for the recipes right now, I think this is fine.
