### ISSUE TITLE
Attempting to set a second `OnConflictClause` on an `Insert` object should fail (Postgres dialect only)

### ISSUE THREAD

**Issue by EricBorczuk** [sqlalchemy/sqlalchemy#5169] opened 2020-02-26 06:27 UTC
Edit: ~Note: This suggestion is only a change meant for the Postgres dialect!~

Hi there,

This is admittedly a nice-to-have for those (like me) who didn't know that an `insert` statement in Postgres could not have more than one `on conflict` clause.  If I were to try and perform an insert such as:

```
insert into table (col1, col2) values (val1, val2)
on conflict (col1) do update set col1 = 'something'
on conflict (col2) do update set col2 = 'something_else';
```

This would fail with a syntax error in Postgres, even though the intent of the query seems kind of sound (do one kind of update if some constraint is violated, and do another kind of update if some other constraint is violated)

With SQLAlchemy, when executing a query such as:

```
query = (
    insert(ModelClass.__table__)
    .values(...)
    .on_conflict_do_update(...some_args)
    .on_conflict_do_update(...some_args2)
)
```

The query builds valid SQL, but what is sent to the database is a statement of the form
```
insert into model_table (...) values (...)
on conflict (...) do update set something = 'some_args2'; -- only the second on_conflict statement is present
```

I personally think it's a bit unintuitive to be able to build what you might think is a query with many on conflict statements without error, but silently it is executing the wrong SQL and is choosing to keep only one `on conflict` clause. 

So, my request is, when building a query such as:

```
query = (
    insert(ModelClass.__table__)
    .values(...)
    .on_conflict_do_update(...some_args)
    .on_conflict_do_update(...some_args2)
)
```

I would really like to see an InvalidRequestError raised (much like the example in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/dml.py#L419, where calling values() with some kwargs when the query is already inserting from a select is deemed illegal) that states something like: "This construct already has an on_conflict behavior set"

More than happy to make a PR for this! I'd imagine it's a pretty simple change since it only affects the postgres dialect/DML, but I'd love to hear your thoughts on whether the change is merited (and also what the error message should be). Also, if the change is merited, perhaps `on_conflict_do_nothing` should also raise when it is trying to overwrite an on_conflict behavior that's already set.

Thanks!

**Comment by zzzeek** [comment] 2020-02-26 18:07
hi there -

So I agree that setting on_conflict() multiple times should not silently overwrite the previous value.  

However, I disagree that this change is only for PostgreSQL / DML and instead the issue is that the Insert.values() construct has ad-hoc logic that is not part of a more consistent pattern such that the many methods for which an implicit state change like this can be surprising are not able to participate in the same behavior.

For Insert.values() specifically, the state change involves the addition of state that is in conflict with other state already present.     In the case of the on conflict clause, the issue is simpler in that the method is replacing state that is already present.  I can immediately think of half a dozen other places where the same issue exists, including MySQL's "on duplicate key update", the distinct() method on select() and Query when an "ON" condition is present,  the limit() / offset() methods on select() / Query, to some extent the select().with_only_columns() method, maybe others.

in ORM Query, there is another ad-hoc decorator pattern in use to try to apply some checks to things, like "@_no_statement_condition" meaning a certain method should not be allowed if the query already has .statement.   i think at the moment it might be feasible to create such a decorator in Core that applies to the "single attribute being replaced" issue, so that all methods that have this kind of behavior can just be marked and a pre-configured exception or warning can come out.   that way future occurrences of this issue don't require a new conditional, new exception text, new test, they just require a decorator be present and then can likely be tested through a common fixture.

The Query pattern is probably the simplest approach here, here's what this would look like for MySQL (looks exactly the same for PG):

```
diff --git a/lib/sqlalchemy/dialects/mysql/dml.py b/lib/sqlalchemy/dialects/mysql/dml.py
index 531b31bc3..a812438fe 100644
--- a/lib/sqlalchemy/dialects/mysql/dml.py
+++ b/lib/sqlalchemy/dialects/mysql/dml.py
@@ -1,6 +1,8 @@
 from ... import exc
 from ... import util
+from ...sql.base import _assertions
 from ...sql.base import _generative
+from ...sql.base import check_attribute
 from ...sql.dml import Insert as StandardInsert
 from ...sql.elements import ClauseElement
 from ...sql.expression import alias
@@ -46,6 +48,7 @@ class Insert(StandardInsert):
         return alias(self.table, name="inserted")
 
     @_generative
+    @_assertions(check_attribute("_post_values_clause"))
     def on_duplicate_key_update(self, *args, **kw):
         r"""
         Specifies the ON DUPLICATE KEY UPDATE clause.
diff --git a/lib/sqlalchemy/sql/base.py b/lib/sqlalchemy/sql/base.py
index a7324c45f..8aed75f30 100644
--- a/lib/sqlalchemy/sql/base.py
+++ b/lib/sqlalchemy/sql/base.py
@@ -84,6 +84,28 @@ def _generative(fn):
     return decorated
 
 
+def _assertions(*assertions):
+    @util.decorator
+    def generate(fn, *args, **kw):
+        self = args[0]
+        for assertion in assertions:
+            assertion(self, fn.__name__)
+        fn(self, *args[1:], **kw)
+
+    return generate
+
+
+def check_attribute(attribute):
+    def check(self, decorated_fn):
+        if attribute in self.__dict__:
+            raise exc.InvalidRequestError(
+                "Method %s has already been called on this %r"
+                % (decorated_fn, self)
+            )
+
+    return check
+
+
 def _clone(element, **kw):
     return element._clone()
 
diff --git a/test/dialect/mysql/test_compiler.py b/test/dialect/mysql/test_compiler.py
index d59c0549f..cae0ab794 100644
--- a/test/dialect/mysql/test_compiler.py
+++ b/test/dialect/mysql/test_compiler.py
@@ -928,3 +928,17 @@ class InsertOnDuplicateTest(fixtures.TestBase, AssertsCompiledSQL):
             "ON DUPLICATE KEY UPDATE bar = %s"
         )
         self.assert_compile(stmt, expected_sql)
+
+    def test_no_repeat(self):
+        stmt = insert(self.table).values(
+            [{"id": 1, "bar": "ab"}, {"id": 2, "bar": "b"}]
+        )
+        stmt = stmt.on_duplicate_key_update(bar="foobar")
+
+        assert_raises_message(
+            exc.InvalidRequestError,
+            "Method on_duplicate_key_update has already been called "
+            "on this .*Insert ",
+            stmt.on_duplicate_key_update,
+            bar="hoho",
+        )

```

so this needs a lot of polish, like, I've copied the ORM's _assertions() decorator without moving it out of ORM, the error message is a little clumsy, and I didn't come up with pre-made test fixture.  but I think we should be checking for methods that silently replace the old value in the general case.

**Comment by zzzeek** [comment] 2020-02-26 18:10
also, we need to think about which methods for which silently replacing the old value is intuitive, vs. which is not.  limit() and offset(), I would argue are intuitive in that they replace the old value.   the two "on conflict  / duplicate" constructs we're talking about here, i agree they are not.   I think disitnct(ON=) is also a non-intuitive replacement.

**Comment by EricBorczuk** [comment] 2020-02-26 21:09
I totally didn't think about the more general case - thanks for weighing in on that.  Abstracting a decorator that restricts replacement makes perfect sense to me, from a perspective of testability and consistency, too.

I also agree that by virtue of having a builder-like API, the method(s) that we feel should throw an error are the exception to the general rule, which is that all these builder methods should allow being called multiple times (i.e. query.limit(1).limit(5) should become LIMIT 5)

While it's not necessarily an exhaustive list, I think that your proposal of not allowing replacement for "on conflict / duplicate" and "distinct on" is a totally reasonable starting point, and with that reusable decorator it would probably be simple to just add the decorator to other builder methods in the future should it make more sense for them to not be overwritten.

**Comment by EricBorczuk** [comment] 2020-02-26 21:11
Oh but also, just perusing the repo a bit, I noticed that the `where()` builder actually appends whatever WHERE clause was already built to the args you send (so query.where(X).where(Y) would be X and Y, rather than replacing X with Y).  So my statement above about `query.limit(1).limit(5) should become LIMIT 5` isn't _always_ strictly true.

So it seems like there are actually at least 3 kinds of builder methods:
1) Those that append to the previous (like `where`, even `distinct` with an expr, there are a lot of these)
2) Those that replace the previous (like `returning`)
3) Those that have bespoke cases where they should error (like `values`, as discussed above)

And I had initially thought that `on_conflict_do_update` was of type 1), when in reality it's implemented as type 2), and we agree that it should be type 3)

I don't think any of this would change your strategy above though, I still think a decorator that restricts overwriting is a good choice.

Should I take a stab at it? I'm glad I brought this up, but I don't want to impose more work for you if I can try to approach it as well. (Would also give me some exposure to the repo should I want to contribute down the line :) )

**Comment by zzzeek** [comment] 2020-02-27 18:29
feel free to give it a shot.   don't go too crazy, there's a lot of patches / issues going through the pipeline all day these days so please be patient.

**Comment by sqla-tester** [comment] 2021-01-16 17:55
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**introduce generalized decorator to prevent invalid method calls** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2483

**Closed** 2021-01-17 01:28 UTC
Labels: bug, sql
