### ISSUE TITLE
Rows not serializeable between restarts on SQLALchemy>=2

### ISSUE THREAD

**Issue by rsundqvist** [sqlalchemy/sqlalchemy#9423] opened 2023-03-04 18:22 UTC
### Describe the bug

Since the switch from `LegacyRow` to `Row` in 2.0.0, deserialization is no longer possible between sessions (it IS possible if you don't restart the kernel).

### SQLAlchemy Version in Use

1.4.42 and 2.0.4

### DBAPI (i.e. the database driver)

pg8000

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.11.2

### Operating system

Ubuntu 20.04.5 LTS (Focal Fossa)

### To Reproduce

```python
# mre.py

import os.path
import sqlalchemy
import pickle

data_path = "data.pkl"
if os.path.exists(data_path):
    with open(data_path, "rb") as f:
        data = pickle.load(f)
    print(f"Deserialized {type(data)=}.")
else:
    engine = sqlalchemy.create_engine("postgresql+pg8000://postgres:Sofia123!@localhost:5002/sakila")

    with engine.connect() as conn:
        data = conn.execute(sqlalchemy.text("SELECT store_id FROM store")).fetchone()

    with open(data_path, "wb") as f:
        pickle.dump(data, f)
    print(f"Serialized {type(data)=} using {sqlalchemy.__version__=}.")
```

### Error

```
Traceback (most recent call last):
  File "/home/dev/mre/mre.py", line 16, in <module>
    data = pickle.load(f)
           ^^^^^^^^^^^^^^
  File "/home/dev/mre/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 1636, in __new__
    raise TypeError(
TypeError: Can't replace canonical symbol for unpickled with new int value 6015043212151762847
``` 

### Additional context

The exact dialect + driver don't seem to matter as far as I can tell (I've tested more variants). The issue seems to be `Row` vs `LegacyRow`.

This does NOT appear if you do not allow the python process to exit before deserialization.

Exact steps that I used for the MRE:
```bash
pip install pg8000
docker run -p 5002:5432 -d rsundqvist/sakila-preload:postgres

rm -f data.pkl && pip install 'sqlalchemy==1.4.46' --quiet && python mre.py && python mre.py
# Serialized type(data)=<class 'sqlalchemy.engine.row.LegacyRow'> using sqlalchemy.__version__='1.4.46'.
# Deserialized type(data)=<class 'sqlalchemy.engine.row.LegacyRow'>.
rm -f data.pkl && pip install 'sqlalchemy==2.0.4' --quiet && python mre.py && python mre.py
# Serialized type(data)=<class 'sqlalchemy.engine.row.Row'> using sqlalchemy.__version__='2.0.4'.
# <Stack trace>
# TypeError: Can't replace canonical symbol for unpickled with new int value 1856181069431459150
rm -f data.pkl && pip install 'git+https://github.com/sqlalchemy/sqlalchemy.git' --quiet && python mre.py && python mre.py
# Serialized type(data)=<class 'sqlalchemy.engine.row.Row'> using sqlalchemy.__version__='2.0.5'.
# <Stack trace>
# TypeError: Can't replace canonical symbol for unpickled with new int value 6015043212151762847
```

Maybe I missed something and this isn't permitted anymore?

// RS

**Comment by CaselIT** [comment] 2023-03-04 18:32
Hi,

This may be a bug. Does setting the env variable 'DISABLE_SQLALCHEMY_CEXT_RUNTIME' changes anything?

**Comment by CaselIT** [comment] 2023-03-04 18:36
No id does not seem to change anything.

This seems like a bug

**Comment by rsundqvist** [comment] 2023-03-04 18:36
>  Does setting the env variable 'DISABLE_SQLALCHEMY_CEXT_RUNTIME' changes anything?
No, same error.

**Comment by zzzeek** [comment] 2023-03-04 18:37
@CaselIT If you feel like working through the docker image above to get us a proper test case that would be helpful

**Comment by CaselIT** [comment] 2023-03-04 18:41
oh ok. Understood what's happening. the issue is that Row seems to serialize a symbol, and symbol uses `hash(name)`, and of course hash is radnom.

If you set the env variable `PYTHONHASHSEED=42` (or any value) the error goes away

**Comment by CaselIT** [comment] 2023-03-04 18:45
Here where it's used:
https://github.com/sqlalchemy/sqlalchemy/blob/15a9aad96232dd3353084453a8789dbd714c33b7/lib/sqlalchemy/engine/cursor.py#L899

somehow CursorResultMetaData is serialized along with Row

**Comment by CaselIT** [comment] 2023-03-04 18:51
I don't think we actually need that. we could just serialize `...` (ellipsis) here or any other default python value

**Comment by CaselIT** [comment] 2023-03-04 18:56
> Here where it's used:
> 
> https://github.com/sqlalchemy/sqlalchemy/blob/15a9aad96232dd3353084453a8789dbd714c33b7/lib/sqlalchemy/engine/cursor.py#L899
> 
> somehow CursorResultMetaData is serialized along with Row

also this serialization seems broken. It serializes a 4 tuple, but otherwise it expect a 7 tuple.

**Comment by CaselIT** [comment] 2023-03-04 20:07
I feel like we should serialized cursor result metadata as something else, like `SimpleResultMetaData`
Most of its method will break in various ways if called on a de-serialized result

**Comment by zzzeek** [comment] 2023-03-04 20:35
we have tests for serialized results and there are very specific behaviors that have been carefully tested for many years, see below.    I'm not really sure how this exception is being produced or why the test below is not illustrating the failure.

if you can get me an MCVE I can fix this

https://github.com/sqlalchemy/sqlalchemy/blob/15a9aad96232dd3353084453a8789dbd714c33b7/test/sql/test_resultset.py#L423-L499

**Comment by CaselIT** [comment] 2023-03-04 20:53
the issue here mike is that python `hash()` is not stable, since every time python process it has a different random state, unless `PYTHONHASHSEED` is set to a specific value.

symbol does internally `hash(name)` to create its int value, so each time the interpreter starts `symbol('unpickled')` has a different int value, breaking the check and tripping the exception.

What I don't understand is by `CursorResultMetaData` serializes itself as a kind of broken state (loads as 4 tuple in key map, instead of 7 tuple as expected).
It seems to me it could just serialized as `SimpleResultMetaData`

**Comment by zzzeek** [comment] 2023-03-04 21:06
> What I don't understand is by `CursorResultMetaData` serializes itself as a kind of broken state (loads as 4 tuple in key map, instead of 7 tuple as expected). It seems to me it could just serialized as `SimpleResultMetaData`

all of those broken states have specific exception raises which would be gone if we used `SimpleResultMetaData`

**Comment by zzzeek** [comment] 2023-03-04 21:08
PYTHONHASHSEED should be random I think when using tox, but in any case, the below doesnt fail:

```
$ PYTHONHASHSEED=random pytest test/sql/test_resultset.py -k pickle
```

so I need that test to be improved to show what's failing.    the test here is the bug

**Comment by zzzeek** [comment] 2023-03-04 21:09
like, `symbol()` itself, we have no need for `symbol()` anymore.   it was pickleable in 1.4 but I might have broken it here.  we dont need it.  but bigger bug, the test suite isn't reproducing the problem.

**Comment by CaselIT** [comment] 2023-03-04 21:10
the test above fails all-right. You can't test it in a single run on python, you need to create a pickle, save it, then load it from another interpreter. Otherwise loading it in the pickle in the same interpreter leads to the same hash

**Comment by zzzeek** [comment] 2023-03-04 21:11
oh, I see.   then that's the problem, OK

**Comment by zzzeek** [comment] 2023-03-04 21:13
no, that's not the problem.

I dont see how symbol() uses hash() for pickling.  it has a ``__reduce__()`` method.   Can you please show me a simple example?

**Comment by zzzeek** [comment] 2023-03-04 21:17
is this the problem?

```diff
diff --git a/lib/sqlalchemy/engine/cursor.py b/lib/sqlalchemy/engine/cursor.py
index c65c4a058c..4ee4fdede3 100644
--- a/lib/sqlalchemy/engine/cursor.py
+++ b/lib/sqlalchemy/engine/cursor.py
@@ -53,7 +53,7 @@ from ..util import compat
 from ..util.typing import Literal
 from ..util.typing import Self
 
-_UNPICKLED = util.symbol("unpickled")
+_UNPICKLED = util.symbol("unpickled", canonical=1)
 
 
 if typing.TYPE_CHECKING:

```

**Comment by zzzeek** [comment] 2023-03-04 21:18
I'm all for going into cursor.py and tightening up these structures and maybe cythonizing more.  that's great.

for 2.0.x though, not at all.    2.0.1

**Comment by CaselIT** [comment] 2023-03-04 21:24
> I'm all for going into cursor.py and tightening up these structures and maybe cythonizing more. that's great.
> 
> for 2.0.x though, not at all. 2.1.0

not sure if keeping as is is any better.

I'm pushing a change

**Comment by zzzeek** [comment] 2023-03-04 21:36
right, add a simple canonical value, fixed:

    x = symbol("x", canonical=1)

**Comment by zzzeek** [comment] 2023-03-04 21:37
that error message is actually intentional there to check for this case

**Comment by CaselIT** [comment] 2023-03-04 21:44
> I'm all for going into cursor.py and tightening up these structures and maybe cythonizing more. that's great.
> 
> for 2.0.x though, not at all. 2.1.0

ok I see that SimpleResultMetaData misses all kind of logic, like raise for duplicate key.
I guess that's something that can be done for 2.1 (unless we consider it a bug, since `result.freeze().first()._mapping['duplica_col']` does not raise)

**Comment by zzzeek** [comment] 2023-03-04 22:12
the quickest way to just be done here is to add a canonical to the symbol() in question, or just replace it with object() or an Enum.    If it's the UNPICKLED symbol, just replace it with object().   that thing is not used anywhere else.

**Comment by sqla-tester** [comment] 2023-03-04 22:33
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fixed bug where :meth:`_engine.Row`s could not be** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4490

**Comment by CaselIT** [comment] 2023-03-06 11:24
The tests added for this one broke the wheel creation pipeline (and only it) for some reason

**Comment by CaselIT** [comment] 2023-03-06 11:25
Failed message is this

```
   =================================== FAILURES ===================================
  _ CursorResultTest_sqlite+pysqlite_3_40_1.test_pickle_rows_other_process[not_use_labels] _
  [gw1] linux -- Python 3.7.16 /tmp/tmp.bPJfig2A9I/venv/bin/python
  Traceback (most recent call last):
    File "/project/test/sql/test_resultset.py", line 525, in test_pickle_rows_other_process
      eq_(proc.returncode, 0)
    File "/project/lib/sqlalchemy/testing/assertions.py", line 258, in eq_
      assert a == b, msg or "%r != %r" % (a, b)
  AssertionError: 1 != 0
  assert 1 == 0
  ----------------------------- Captured stderr call -----------------------------
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/tmp.bPJfig2A9I/venv/lib/python3.7/site-packages/sqlalchemy/engine/_py_row.py", line 142, in rowproxy_reconstructor
      obj.__setstate__(state)
    File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 53, in sqlalchemy.cyextension.resultproxy.BaseRow.__setstate__
  TypeError: an integer is required
  _ CursorResultTest_sqlite+pysqlite_3_40_1.test_pickle_rows_other_process[use_labels] _
  [gw1] linux -- Python 3.7.16 /tmp/tmp.bPJfig2A9I/venv/bin/python
  Traceback (most recent call last):
    File "/project/test/sql/test_resultset.py", line 525, in test_pickle_rows_other_process
      eq_(proc.returncode, 0)
    File "/project/lib/sqlalchemy/testing/assertions.py", line 258, in eq_
      assert a == b, msg or "%r != %r" % (a, b)
  AssertionError: 1 != 0
  assert 1 == 0
  ----------------------------- Captured stderr call -----------------------------
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/tmp.bPJfig2A9I/venv/lib/python3.7/site-packages/sqlalchemy/engine/_py_row.py", line 142, in rowproxy_reconstructor
      obj.__setstate__(state)
    File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 53, in sqlalchemy.cyextension.resultproxy.BaseRow.__setstate__
  TypeError: an integer is required
```

from https://github.com/sqlalchemy/sqlalchemy/actions/runs/4339180666/jobs/7577028763

**Comment by CaselIT** [comment] 2023-03-06 23:07
and here's why the test did not catch this
https://github.com/sqlalchemy/sqlalchemy/blob/5ed17e01b10ffcacdc0c7930d3241dcfa656eadc/test/base/test_result.py#L211

they use 0 insead of the constant from the module

**Comment by CaselIT** [comment] 2023-03-06 23:10
also interestingly we only test in one direction cython -> python, never the opposite, so event without the problem above the test would not have caught it

**Comment by sqla-tester** [comment] 2023-03-06 23:28
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix regression when deserializing python rows into cython** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4494

**Comment by zzzeek** [comment] 2023-03-06 23:49
good stuff, thanks for looking into it

**Closed** 2023-03-10 21:06 UTC
Labels: bug, engine, cextensions
