### ISSUE TITLE
Support limit using with_dialect_options in delete in Mysql 

### ISSUE THREAD

**Issue by awtkns** [sqlalchemy/sqlalchemy#11764] opened 2024-08-20 02:16 UTC
When trying to do a delete with limit (supported with mysql), `delete(...).with_dialect_options` incorrectly throws a validation error although the docs say this should be supported.

```python
    @_generative
    def with_dialect_options(self, **opt: Any) -> Self:
        """Add dialect options to this INSERT/UPDATE/DELETE object.

        e.g.::

            upd = table.update().dialect_options(mysql_limit=10)

        .. versionadded: 1.4 - this method supersedes the dialect options
           associated with the constructor.


        """
        self._validate_dialect_kwargs(opt)
        return self
 ```       
        
        

Docs: https://docs.sqlalchemy.org/en/20/dialects/mysql.html#mysql-mariadb-sql-extensions
Version: 2.0.31
DBAPI: aiomysql (others fail too)
Database version: mysql 8
Python version: 3.11
OS: osx

### To Reproduce
```python
import sqlalchemy as sa
from sqlalchemy import orm

BASE = orm.declarative_base()


class Message(BASE):
    __tablename__ = 'messages'
    id = sa.Column(sa.Integer, primary_key=True)


def main():
    engine = sa.create_engine("mysql+pymysql://127.0.0.1:3306/test")
    BASE.metadata.create_all(engine)
    sa.delete(Message).with_dialect_options(mysql_limit=100_000)

if __name__ == '__main__':
    main()
```

### Error

```
sqlalchemy.exc.ArgumentError: Argument 'mysql_limit' is not accepted by dialect 'mysql' on behalf of <class 'sqlalchemy.sql.dml.Delete'>
```

**Comment by zzzeek** [comment] 2024-08-20 02:36
as stated in the linked document, mysql_limit is supported with update() only, this error message is by design at the moment

**Comment by CaselIT** [comment] 2024-08-20 06:08
I guess we can keep this issue open as an use case.

**Comment by zzzeek** [comment] 2024-12-13 16:46
this is a very clean add and should be backported to 2.0 as I am including some doc fixes and security features

**Comment by sqla-tester** [comment] 2024-12-13 17:08
**Pablo Nicolas Estevez** has proposed a fix for this issue in the **main** branch:

**add delete limit to mysql; ensure int for update/delete limits** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5607

**Comment by sqla-tester** [comment] 2024-12-13 17:08
**Pablo Nicolas Estevez** has proposed a fix for this issue in the **rel_2_0** branch:

**add delete limit to mysql; ensure int for update/delete limits** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5627

**Closed** 2024-12-15 02:43 UTC
Labels: mysql, sql, use case, mariadb
