### ISSUE TITLE
Intermittent "When initializing mapper ..., expression ... failed to locate a name"

### ISSUE THREAD

**Issue by mephi42** [sqlalchemy/sqlalchemy#4995] opened 2019-11-20 21:25 UTC
Consider the following code, adapted from a somewhat larger program for convenience:

```
#!/usr/bin/env python3
import os

import sqlalchemy
import sqlalchemy.orm
import sqlalchemy.ext.declarative

for i in range(100):
    try:
        os.unlink('test.db')
    except FileNotFoundError:
        pass
    engine = sqlalchemy.create_engine('sqlite:///test.db')
    metadata = sqlalchemy.MetaData()
    base = sqlalchemy.ext.declarative.declarative_base(
        bind=engine,
        metadata=metadata)


    class Table1(base):
        __tablename__ = 'table1'
        id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)
        table2_id = sqlalchemy.Column(
            'table2_id',
            sqlalchemy.Integer,
            sqlalchemy.ForeignKey('table2.id'),
        )
        table2 = sqlalchemy.orm.relationship('Table2')


    class Table2(base):
        __tablename__ = 'table2'
        id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)


    metadata.create_all(engine)

    if i % 2 == 0:
        continue

    sessionmaker = sqlalchemy.orm.sessionmaker(bind=engine)
    session = sessionmaker()
    try:
        session.add(Table1())
    finally:
        session.close()
```

This loop fails on a random interation with the following exception:

```
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper|Table1|table1, expression 'Table2' failed to locate a name ("name 'Table2' is not defined"). If this is a class name, consider adding this relationship() to the <class '__main__.Table1'> class after both dependent classes have been defined.
```

This code has the following features:
* `Table1.table2` relationship is initialized using `str`
* On iterations with even indices we just create models
* On iterations with odd indices we also do a simple query

Internally, weak references to mappers from both kinds of iterations end up being stored in the global `_mapper_registry` variable. However, mappers from even iterations are (lazily) initialized on odd iterations, which, when GC is not favorable, leads to `Table1` being there, while `Table2` is already gone.

**Comment by zzzeek** [comment] 2019-11-20 22:16
hi there -

call clear_mappers() after each loop iteration.  otherwise as you noted you are relying upon garbage collection.

**Comment by mephi42** [comment] 2019-11-21 14:56
Hi @zzzeek!

clear_mappers() should be fine as a workaround, but is there a possibility for a fix in sqlalchemy? In particular, right now the manual says:

clear_mappers() is not for normal use, as there is literally no valid usage for it outside of very specific testing scenarios.

Of course, the snippet above can be considered "a specific testing scenario", but I made it this way only for illustrative purposes - the real program instantiated two different groups of models in different places, and under certain conditions did not use models from the first group. The resulting failure was quite difficult to track down.

**Comment by zzzeek** [comment] 2019-11-21 16:39
I've stepped through the issue, including attaching the iterator count to each mapper, and the issue is that when the mapper system is configuring all known mappers, the old ones are still present in the registry, but in some cases only partially.  because you aren't using the mappers on every iteration, they are only configured on half the calls.  There is no call to configure_mappers() on each iteration, so unconfigured mappers are left in the queue, and then are partially garbage collected leading to failures.

So while your test case is confusing, it is doing exactly what it's being told and there's not any kind of bug here, there are uninitialized mappers and then some of their dependencies are being erased, there's nothing SQLAlchemy can do to guess what you're doing and especially that there are not one but two separate API features that resolve the ambiguity, you should just use one or both of those.

```
(Pdb) !list(mapperlib._mapper_registry.keys())
[<Mapper at 0x7f2a9fb893d0; Table1>, <Mapper at 0x7f2a9fb89a10; Table2>, <Mapper at 0x7f2a9fa48290; Table1>, <Mapper at 0x7f2a9fa48510; Table2>, <Mapper at 0x7f2a9f9fccd0; Table1>, <Mapper at 0x7f2a9fa0eb90; Table1>, <Mapper at 0x7f2a9f99f0d0; Table2>]
(Pdb) [m.class_.generation for m in mapperlib._mapper_registry]
[0, 0, 1, 1, 2, 3, 3]
(Pdb) self
<RelationshipProperty at 0x7f2a9fa070e0; table2>
(Pdb) self.parent.class_.generation
2

```

if it helps, you can just call configure_mappers() when the mappers are created, rather than clear_mappers() when you are done with them.

clear_mappers() is documented as only for tests because there's not really a use case where a normal application should be setting up mappers and then garbage collecting them.   but if that's what you really want to do then at least call configure mappers() so they aren't sitting around in a semi-initialized state.   but I'd probably ask why is your program doing that if it's not a test suite.

**Comment by zzzeek** [comment] 2019-11-28 00:39
no bug is illustrated here so closing.

**Closed by zzzeek** 2019-11-28 00:39 UTC
Labels: question
