### ISSUE TITLE
Teach `mypy` to consinder `relationship` fields to "parent" tables to be non-`None`.

### ISSUE THREAD

**Issue by zuckerruebe** [sqlalchemy/sqlalchemy#7280] opened 2021-11-02 20:50 UTC
### Describe the bug

Is there a way - besides marking the field with an annotation directly - to make `mypy` interpret a model's relationship field to its parent class as non-`None`able/non-`Optional`? I've tried the following two - admittedly quite "dynamic" - approaches to no avail:
1. Pass `innerjoin=True` to `relationship` in child.
2. Pass `ondelete="RESTRICT"` to `ForeignKey` column in parent.

### To Reproduce

```python
"""Accommodate measurements from any endpoint.

Revision ID: 22964e2b9c5b
Revises: 640fd90533f0
Create Date: 2021-10-19 11:41:46.791621

"""
import typing as tp
import logging as log

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "22964e2b9c5b"
down_revision = "aa3a6dd24d0c"
branch_labels = None
depends_on = None

from sqlalchemy import Boolean, CHAR, Column, DateTime, Float, ForeignKey, Identity, Integer, String
from sqlalchemy.orm import declarative_base, relationship

import rest_api as _api

logger = log.getLogger(f"migration-{revision}")

Base = declarative_base()


class Building(Base):
    __tablename__ = "buildings"

    _id = Column(CHAR(24), primary_key=True)
    name = Column(String(64))
    created_at = Column(DateTime)
    street = Column(String(64))
    street_nr = Column(String(64))
    city = Column(String(64))
    postal = Column(Integer)
    floors = Column(Integer)

    apartments: tp.Sequence["Apartment"] = relationship("Apartment", back_populates="building")


class Apartment(Base):
    __tablename__ = "apartments"

    _id = Column(CHAR(24), primary_key=True)
    building_id: str = Column(ForeignKey(Building._id), nullable=False)
    name = Column(String(128))
    created_at = Column(DateTime)
    occ_state = Column(String(64))
    apartment_type = Column(String(64))
    active = Column(Boolean)

    building = relationship(Building, back_populates="apartments", uselist=False)
    rooms: tp.Sequence["Room"] = relationship("Room", back_populates="apartment")


class Room(Base):
    __tablename__ = "rooms"

    _id = Column(CHAR(24), primary_key=True)
    apartment_id: str = Column(ForeignKey(Apartment._id), nullable=False)
    name = Column(String(128))
    created_at = Column(DateTime)

    apartment = relationship(Apartment, back_populates="rooms", uselist=False)
    devices: tp.Sequence["Device"] = relationship("Device", back_populates="room")


class Device(Base):
    __tablename__ = "devices"

    _id = Column(CHAR(24), primary_key=True)
    room_id: str = Column(ForeignKey(Room._id), nullable=False)
    name = Column(String(128))
    code = Column(CHAR(7))
    created_at = Column(DateTime)

    room = relationship(Room, back_populates="devices", uselist=False)
    measurements: tp.Sequence["OldMeasurement"] = relationship("OldMeasurement", back_populates="dev")


class OldMeasurement(Base):
    __tablename__ = "measurements"

    _id = Column(
        Integer,
        Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
        primary_key=True,
    )
    dev_id: str = Column(ForeignKey(Device._id, ondelete="RESTRICT"), nullable=False)
    tstamp = Column(DateTime)
    temperature_current = Column(Float(53))
    temperature_target = Column(Float(53))

    dev = relationship(Device, back_populates="measurements", uselist=False, innerjoin=True)


class NewMeasurement(Base):
    __tablename__ = "new_measurement"

    _id = Column(
        Integer,
        Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
        primary_key=True,
    )
    dev_id:str = Column(ForeignKey(Device._id), nullable=False)
    endpoint_id = Column(CHAR(24), nullable=False)
    tstamp = Column(DateTime)
    value = Column(Float(53))


def upgrade():
    logger.info("Starting upgrade...")

    bind = op.get_bind()

    NewMeasurement.__table__.create(bind)

    _create_new_measurements_based_on_old_ones(bind)

    OldMeasurement.__table__.drop(bind)

    op.rename_table(NewMeasurement.__tablename__, OldMeasurement.__tablename__)


def _create_new_measurements_based_on_old_ones(connection: sa.engine.Connection):
    query = sa.select(OldMeasurement)

    session = sa.orm.Session(connection)
    with session:
        result = session.execute(query).yield_per(1000).scalars()
        for i, old_measurement in enumerate(result):
            new_measurements = _create_new_measurement(old_measurement)
            for new_measurement in new_measurements:
                session.add(new_measurement)

            if i % 1000 == 0:
                session.flush()
                logger.info("Migrated %i measurements...", i)

        session.flush()


def _create_new_measurement(old_measurement: OldMeasurement) -> tp.Iterable[NewMeasurement]:
    device_code = old_measurement.dev.code.strip()

    assert device_code == "000061", f"{device_code=}"

    device_type = _api.DEVICE_TYPES_BY_CODE[device_code]

    room_temperature_endpoint = device_type.get_endpoint("Room temperature")
    target_temperature_endpoint = device_type.get_endpoint("Target temperature")

    if old_measurement.temperature_current:
        yield NewMeasurement(
            dev_id=old_measurement.dev_id,
            endpoint_id=room_temperature_endpoint.id,
            tstamp=old_measurement.tstamp,
            value=old_measurement.temperature_current,
        )
    elif old_measurement.temperature_target:
        yield NewMeasurement(
            dev_id=old_measurement.dev_id,
            endpoint_id=target_temperature_endpoint.id,
            tstamp=old_measurement.tstamp,
            value=old_measurement.temperature_target,
        )
    else:
        raise AssertionError("Neither room nor target temperature is set.")
```

### Error
```
(venv) >mypy --exclude venv --show-error-codes .
alembic\versions\22964e2b9c5b_accommodate_measurements_from_any_.py:148: error: Item "None" of "Optional[Device]" has no attribute "code"  [union-attr]
alembic\versions\22964e2b9c5b_accommodate_measurements_from_any_.py:148: error: Item "None" of "Union[str, None, Any]" has no attribute "strip"  [union-attr]
Found 2 errors in 1 file (checked 17 source files)
```

### Versions

- OS: Windows 10
- Python: 3.9
- SQLAlchemy: 1.4.25
- Database: N/A (PostgreSQL)
- DBAPI N/A (psycopg2)

**Comment by zzzeek** [comment] 2021-11-02 21:01
hey there -

there is be some discussion on better ways for mappings to work; this issue is first brought up in #6201, and at https://github.com/sqlalchemy/sqlalchemy2-stubs/issues/170#issuecomment-917239714 I propose a longer term solution to this problem by instead of guessing annotations based on ORM directives, we do what dataclasses and pydantic do and determine ORM directives from the annotations, so that's probably where we would go with this.

the basic thing you are observing is documented at https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html#introspection-of-columns-based-on-typeengine even though this is described in terms of columns it applies to attributes as well. Your ORM model can have None as a value for "dev", just instantiate OldModel(dev=None) and `.dev` will be None.

**Comment by zuckerruebe** [comment] 2021-11-02 21:04
Didn't know `pydantic` could do this. But, yeah, if `sqlalchemy` can do this one day that'd be beautiful.

**Comment by zzzeek** [comment] 2021-11-02 21:06
OK well dataclasses does it, I assumed pydantic was similar but I dont actually know.

the thing I refer to there is something we could drop into 2.0 or even 1.4, it mostly needs commentary.

**Comment by zzzeek** [comment] 2021-11-02 21:07
like feedback on how it works because we can't keep getting this wrong :)

**Comment by zuckerruebe** [comment] 2021-11-02 21:10
No, I think you were right, this seems to be one of the main selling points of `pydantic`. I've skipped on it for doing something very similar before and I'm wondering why now. :D

**Comment by zuckerruebe** [comment] 2021-11-02 21:12
Ah, yes, because somehow they chose not to piggy-back on `dataclass` so my IDE can then not interpret `pydantic` models. I see now they have a `PyCharm` plugin which alleviates this a bit...

**Comment by zzzeek** [comment] 2021-11-04 22:09
this is a dupe of #6201 and we should note on #6201 the new API recipe idea I have at https://github.com/sqlalchemy/sqlalchemy2-stubs/issues/170#issuecomment-917239714

**Closed by zzzeek** 2021-11-04 22:09 UTC
Labels: duplicate, question, expected behavior, mypy
