### ISSUE TITLE
Create Generated Column in MariaDB cannot specify null

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10056] opened 2023-07-03 19:29 UTC
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10055

<div type='discussions-op-text'>

<sup>Originally posted by **iamrinshibuya** July  3, 2023</sup>
Hello, when using [Computed Columns](https://docs.sqlalchemy.org/en/20/core/defaults.html#computed-columns-generated-always-as), the following code works without any changes on PostgreSQL, but it fails in MariaDB.

```python
import asyncio

from sqlalchemy import Computed, text
from sqlalchemy.orm import (
    Mapped,
    DeclarativeBase,
    mapped_column,
)
from sqlalchemy.ext.asyncio import create_async_engine

# works with this
# engine = create_async_engine('postgresql+psycopg://...')

# does not work with this
engine = create_async_engine('mariadb+asyncmy://...')

class Base(DeclarativeBase):
    pass

class Sqaure(Base):
    __tablename__ = 'square'
    id: Mapped[int] = mapped_column(primary_key=True)
    side: Mapped[int]
    area: Mapped[int] = mapped_column(Computed(text('4 * side')), index=True)

async def main():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

asyncio.run(main())
```

```
sqlalchemy.exc.ProgrammingError: (asyncmy.errors.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL, \n\tPRIMARY KEY (id)\n)' at line 4")
[SQL: 
CREATE TABLE square (
        id INTEGER NOT NULL AUTO_INCREMENT, 
        side INTEGER NOT NULL, 
        area INTEGER GENERATED ALWAYS AS (4 * side) NOT NULL, 
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

What should I do so that the table gets created in MariaDB?

Making the column nullable (`area: Mapped[int | None]`) seems to fix this, but I have the following concerns

- I find it counterproductive in my case, the generated column always has a value.
- In PostgreSQL this is a "non-nullable" / required column and I'd like to not change the behavior just to accommodate MariaDB (the code has to support both dialects)</div>

The docs of mariadb seem to indicate that the null clause is not allowed with generated always https://mariadb.com/kb/en/generated-columns/

**Comment by CaselIT** [comment] 2023-07-03 19:30
@zzzeek should this be 1.4 or just v2?

**Comment by zzzeek** [comment] 2023-07-03 20:02
v2 only, new development issue

**Comment by CaselIT** [comment] 2023-07-03 20:41
computed is actually since 1.3. I would guess this issue is also on 1.4.

**Comment by rajat315315** [comment] 2023-07-27 08:46
It works in `sqlalchemy==2.0.19` and `python==3.8.10` and MySQL version `5.7.35`

**Comment by rajat315315** [comment] 2023-07-27 09:09
@CaselIT 
Can you please try with the following:
`area: Mapped[int] = mapped_column(Computed(text('4 * side'), {"persisted": False}), index=True)`
OR
`area: Mapped[int] = mapped_column(Computed(text('4 * side'), {"persisted": True}), index=True)`

**Comment by CaselIT** [comment] 2023-07-27 09:43
That's not valid syntax, so I'm not sure what that should achieve

**Comment by rajat315315** [comment] 2023-07-27 09:58
Computed takes a parameter `persisted` and with the value True or False. I think that should solve the problem.
[Reference](https://docs.sqlalchemy.org/en/20/core/defaults.html#sqlalchemy.schema.Computed.__init__)

**Comment by CaselIT** [comment] 2023-07-27 10:04
Sure, but the whay you do that is with `Computed(..., persisted=True)`

**Comment by CaselIT** [comment] 2023-07-27 10:05
I'm also not sure if this is connected with this issue, since the issue is regarding nullable, not persisted

**Comment by rajat315315** [comment] 2023-07-27 10:39
The issue is with regards to the SQL error ..
Making column Nullable is a workaround only..
Giving `persisted=False` puts VIRTUAL before the NOT NULL term which is put by default in mysql case.

**Comment by rajat315315** [comment] 2023-07-27 11:08
Apologies, I now understand the issue..
MariaDB doesn't support NOT NULL in generated columns [Reference](https://mariadb.com/kb/en/generated-columns/#syntax)
whereas MySQL has a support for it. [Reference](https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html).
I think we have no option left but to take the `area` column as NULLABLE in MariaDB.

**Comment by indiVar0508** [comment] 2023-09-16 21:22
Hey ,

I tried to address this one in #10354 , can you check once !

**Comment by indiVar0508** [comment] 2023-10-19 17:58
This issue can be closed now?

**Comment by zzzeek** [comment] 2023-10-19 18:00
ouch, did we not put the number in the commit message ?

**Comment by zzzeek** [comment] 2023-10-19 18:02
yup I failed to catch that in review unfortunately

fixed in 5347be31c98a3627c2466f1891b7c0e80bf29ed9

**Closed by zzzeek** 2023-10-19 18:02 UTC
Labels: bug, sql, PRs (with tests!) welcome, mariadb

**Comment by CaselIT** [comment] 2023-10-19 18:51
The commit has fix(#) instaead of fix: # 😞

**Comment by indiVar0508** [comment] 2023-10-20 04:51
Ahh i see Mybad, i'll keep that in mind in future, 
also if you want i can try to look into stuff related to commit lints on gh-actions or pre-commit git-hooks ig.
i saw them on some other projects.
