### ISSUE TITLE
synonym should raise immediately for non-MapperProperty target

### ISSUE THREAD

**Issue by j-walker23** [sqlalchemy/sqlalchemy#4521] opened 2019-03-05 16:36 UTC
First, thanks for the 1.3 update. Lot's of amazing work.

After updating, my synonyms on existing AssociationProxies are failing with

`InvalidRequestError: synonym() attribute "MyModel.ass_proxy" only supports ORM mapped attributes, got ObjectAssociationProxyInstance`.

**Comment by zzzeek** [comment] 2019-03-05 17:00
Hi - 

You need to provide a complete example.  I can produce a failure but not that one.

**Comment by zzzeek** [comment] 2019-03-05 18:22
oh.  you're making a synonym of an association proxy.   synonym doesn't support that. 

Given a model:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.associationproxy import association_proxy

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", backref="a")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))

    a_data = association_proxy("a", "data")

    a_syn = synonym("a_data")

```

the expression generated by B.a_data is:

```
>>> print(B.a_data == 5)
EXISTS (SELECT 1 
FROM a, b 
WHERE a.id = b.a_id AND a.data = :data_1)

```
but even in 1.2, you can't do this for the synonym:

```
>>> print(B.a_syn == 5)
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test.py", line 28, in <module>
sqlalchemy.exc.InvalidRequestError: synonym() attribute "B.a_data" only supports ORM mapped attributes, got AssociationProxy('a', 'data')

```

so that error is now being emitted for instance-level access as well.   rename your association proxy, add a new one with your new name, or use `@property`:

```
class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))

    a_data = association_proxy("a", "data")

    @property
    def a_syn(self):
        return self.a_data

```

**Comment by zzzeek** [comment] 2019-03-05 18:22
now I did find a bug making an association proxy of a synonym and that I can fix.

**Comment by zzzeek** [comment] 2019-03-05 18:25
it was a bug that this exception is raised lazily.  it needs to raise immediately.

**Comment by zzzeek** [comment] 2019-03-05 18:32
or we need to support the whole pattern.    but that was never something we tested for previously.

**Comment by j-walker23** [comment] 2019-03-05 18:57
Oh yes, it must be something else in my code causing this.

I used the synonym on a ass proxy. But later when i used it in an abstraction level i would check `original_property` and then use the actual association proxy. So my error must be in that part.

The error being lazy was what allowed me to do this in the first place so that was actually good for me.
But i understand if you want to change that. 


A lot of my code broke because in abstraction code i was doing `isinstance(col, AssociationProxy)` which no longer works due to the new types. I have to do `col.parent.extension_type` instead of the old `col.extenstion_type`.
It's probably something around there that caused this synonym bug for me.

What should be the preferred way of checking if a column is a ass proxy in 1.3?

**Comment by j-walker23** [comment] 2019-03-05 19:06
Just to give an explanation of what i'm doing in case this use case seems weird.

In code i always just use the ass proxy, so `B.a_data` in your example.

But i have a generic key:value search control that i'm then building SA queries with.
And so I only used the synonym to allow the user to search by other names that might make more send to them than what my ass proxy is named in code.

That generic search is what was grabbing the `original_property` of a synonym, bypassing the error you correctly stated is on 1.2 as well.

**Comment by zzzeek** [comment] 2019-03-05 19:27
you can do isinstance(col, AssociationProxyInstance), this is public: https://docs.sqlalchemy.org/en/latest/orm/extensions/associationproxy.html?highlight=associationproxyinstance#sqlalchemy.ext.associationproxy.AssociationProxyInstance

**Comment by j-walker23** [comment] 2019-03-05 19:54
Ok perfect. Thank you. 

ps If I ever get rich off of a product that uses SA you are getting more then a tithing worth of donations because holy shit SA has revolutionized my python and sql life.
Plus it has ruined me for all other platforms : )

**Comment by zzzeek** [comment] 2019-03-05 19:56
> Ok perfect. Thank you.
> 
> ps If I ever get rich off of a product that uses SA you are getting more then a tithing worth of donations because holy shit SA has revolutionized my python and sql life.
> Plus it has ruined me for all other platforms : )

wow thanks!  glad it's worked out for you.    I see a lot of grief on twitter it's good to hear the other side.

**Comment by j-walker23** [comment] 2019-03-05 23:13
That's extremely sad to hear considering the power of this lib and the price. Speaking of that, are you on Patreon? Feel like i've searched before and I know you have another thing but you should if you're not.

One of my very first tweets was to you to thank you for SA after realizing its power. Probably after fully learning eager loading bc that is amazing for crud web apps. 
That's what you should be seeing on twitter.

I've used it really really heavily for three years now and this is the first bug i've ever filed. And it wasn't even a bug.

**Comment by zzzeek** [comment] 2019-03-06 14:20
I have a thing on Patreon but I don't know how to use it:

https://www.patreon.com/zzzeek

**Comment by j-walker23** [comment] 2019-03-11 23:28
Awesome thanks. It's nice to have all my pay people for content, "donations" feels wrong, in one place or i would 100% forget about them a week later. My memory pushes everything out non code related to fast : ).

**Comment by zzzeek** [comment] 2019-03-12 01:36
> Awesome thanks. It's nice to have all my pay people for content, "donations" feels wrong, in one place or i would 100% forget about them a week later. My memory pushes everything out non code related to fast : ).
> 
> Patreon for you seems to be setup on a per post. eg. for podcasts, I can pay per episode. I wanted to just set a monthly limit for you but you might have to set something up on your side first. Not sure.

wow, I was confused by that and you inspired me to look for a button and there was one!   I might actually start making money because of that thanks!

> If you're not getting anything plz let me know. My twitter is https://twitter.com/jwalkdev if you don't want me to keep blowing up your github issues.

**Comment by zzzeek** [comment] 2019-03-25 19:08
OK coming back to the code I can't reproduce any condition that is new, instance level synonym access to an assoc proxy seems to work, so I'm not sure what I was doing earlier.   if you want to share an example of exactly how you got the error in the first place that would be helpful, but until then im just going to close this.  instance level access is illustrated below and seems to work...

```

from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.associationproxy import association_proxy

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", backref="a")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))

    a_data = association_proxy("a", "data")

    a_syn = synonym("a_data")

b1 = B(a=A(data='a1'))
print(b1.a_syn)

b1.a_syn = 'foo'
```

**Closed by zzzeek** 2019-03-25 19:08 UTC
Labels: bug, orm, sqlalchemy.ext
