### ISSUE TITLE
inspect.formatannotation is not documented and should be vendored

### ISSUE THREAD

**Issue by tjohnson4** [sqlalchemy/sqlalchemy#5138] opened 2020-02-07 21:41 UTC
Python 3.7.2
sqlalchemy 1.3.13 && 1.3.11
connexion 2.6.0 && 2.3.0
Flask 1.1.1
werkzeug 0.16.0 && 0.16.1

My flask application stopped working recently by raising the error below. It appears that the inspect module has somehow been removed or modified in the python 3.7 env causing the module formatannotation to be missing. Issue is repeatable in  

```
Traceback (most recent call last):
  File "smid_service/app.py", line 1, in <module>
    from smid_service import create_app
  File "/app/smid_service/__init__.py", line 1, in <module>
    import connexion
  File "/usr/local/lib/python3.7/site-packages/connexion/__init__.py", line 3, in <module>
    import werkzeug.exceptions as exceptions  # NOQA
  File "/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py", line 220, in <module>
    from .serving import run_simple
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 48, in <module>
    from ._internal import _log
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_internal.py", line 11, in <module>
    import inspect
  File "/usr/local/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/usr/local/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "/app/smid_service/token.py", line 1, in <module>
    from sqlalchemy import create_engine
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 16, in <module>
    from .compat import binary_types
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 270, in <module>
    from inspect import formatannotation
ImportError: cannot import name 'formatannotation' from 'inspect' (/usr/local/lib/python3.7/inspect.py)
```

**Comment by zzzeek** [comment] 2020-02-07 22:40
hi there

please provide the exact Python 3.7 version, as well as os details as well as python platform (cpython?  pypy?)     this function is present in 3.7.6 however it looks like it is not documented.

**Comment by zzzeek** [comment] 2020-02-07 22:41
here it is in Python master: https://github.com/python/cpython/blob/master/Lib/inspect.py#L1194  still there

**Comment by zzzeek** [comment] 2020-02-07 22:49
i can replace this but I still need your version info since I dont know the cause of your function disappearing.

**Comment by sqla-tester** [comment] 2020-02-07 22:56
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Vendor inspect.formatannotation** https://gerrit.sqlalchemy.org/1711

**Comment by sqla-tester** [comment] 2020-02-07 22:56
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Vendor inspect.formatannotation** https://gerrit.sqlalchemy.org/1712

**Comment by tjohnson4** [comment] 2020-02-07 22:56
> hi there
> 
> please provide the exact Python 3.7 version, as well as os details as well as python platform (cpython? pypy?) this function is present in 3.7.6 however it looks like it is not documented.

Updated above 3.7.2

**Comment by zzzeek** [comment] 2020-02-07 23:02
not sure how you're getting that.  here it is in python 3.7.2:

https://github.com/python/cpython/blob/v3.7.2/Lib/inspect.py#L1192 

I notice your Python is in /usr/local/lib, are you building manually?  is this some special distribution of cPython or otherwise how is it getting there?

**Comment by zzzeek** [comment] 2020-02-07 23:05
oh.  you have an import issue in your own application:

```

File "/usr/local/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/usr/local/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "/app/smid_service/token.py", line 1, in <module>
    from sqlalchemy import create_engine
```

above, your own application has a file called /app/smid_service/token.py which is polluting your Python sys.import space.   You can't have a module called "token.py" that's not in a [package](https://docs.python.org/3/tutorial/modules.html#packages) and you will have problems until this is fixed.

**Comment by tjohnson4** [comment] 2020-02-07 23:20
Thanks, looking into now

**Closed** 2020-02-08 00:06 UTC
Labels: bug, py3k, setup
