### ISSUE TITLE
How to use delete operation with async orm?

### ISSUE THREAD

**Issue by AliMajedHA** [sqlalchemy/sqlalchemy#5627] opened 2020-10-04 06:15 UTC
We used to use synchronous  `ORM` operations using code below:

```python
obj = session.query(User).get(id)
session.delete(obj)
session.commit()
```

How should we use delete operation in asynchronous `ORM`?

Versions:
 - Python: 3.8.5
 - SQLAlchemy: 1.4

**Comment by CaselIT** [comment] 2020-10-04 07:34
Hi,

The documentation is probably the best place to start: https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html

**Comment by CaselIT** [comment] 2020-10-04 07:37
See also the examples: https://docs.sqlalchemy.org/en/14/orm/examples.html#examples-asyncio

**Comment by AliMajedHA** [comment] 2020-10-04 08:31
Thanks for the response

I have read the document and the given examples: [Insert, Update, Delete](https://docs.sqlalchemy.org/en/14/core/dml.html#sqlalchemy.sql.expression.Delete)

But what has put me in doubt is that the using given examples and defined method is more like using SQLAlchemy `Core` rather than `ORM`. In this way, delete operation has a different syntax with  our other CRU operations.

**Comment by CaselIT** [comment] 2020-10-04 08:46
I've taken a look, and I now understand your problem.

It seems that `delete` and `get` are missing from the AsyncSession.
Regarding `query` I think that currently the plan is to drop it in favor of select for 2.0, so that would not be part of the api.

**Comment by CaselIT** [comment] 2020-10-04 08:47
BTW, thanks for testing it. It's an all new parts, so feedback are very useful!

**Comment by CaselIT** [comment] 2020-10-04 08:57
As a temporary workaround you can use `session.sync_session.delete`.

**Comment by zzzeek** [comment] 2020-10-04 15:17
no changelog is needed for any of these fixes as 1.4.0beta1 is not released yet.

**Comment by zzzeek** [comment] 2020-10-04 15:21
dupe of #5628

**Closed by zzzeek** 2020-10-04 15:21 UTC
Labels: asyncio, bug

**Comment by VladislavRusakov** [comment] 2021-11-18 14:08
I know it's outdated, but I've met same problem and figured out, how to fix it.

`@app.get("/db/del/{index}", response_model=list[Weather])`
`async def delete_row(index: int, session: AsyncSession = Depends(get_session)):`

Inside function:
` row = await session.execute(select(Weather).where(Weather.id == index))`
`row = row.scalar_one()`
`await session.delete(row)`
`await session.commit()`

Idk if it is right, but it works, at least for me.

**Comment by pythops** [comment] 2022-02-05 19:22
Here is a working example: 

```python
from sqlalchemy import delete

query =  sqlalchemy.delete(MyTable).where(MyTable.id == 1234)
await db_session.execute(query)
await db.commit()

```

**Comment by fl1p3mth3b1rd** [comment] 2022-05-05 09:15
```
async with async_engine.connect() as conn:
                result = await conn.execute("your query")
```

where async_engine can be created as:

```
from sqlalchemy.ext.asyncio import create_async_engine
        engine =create_async_engine("your db uri")
```

**Comment by zoltan-fedor** [comment] 2022-09-08 17:29
Two years later `delete` is still missing from `AsyncSession` ...
"Missing" meaning silently not performing the delete.
WTF

**Comment by CaselIT** [comment] 2022-09-08 17:36
> Two years later `delete` is still missing from `AsyncSession` ... "Missing" meaning silently not performing the delete. Impressive. [sarcasm]

I'm not sure what library are you using, but delete it's in async session since 1.4.0b1, so since almost 2 years ago.

That's indeed impressive

**Comment by zzzeek** [comment] 2022-09-08 17:38
> Two years later `delete` is still missing from `AsyncSession` ... "Missing" meaning silently not performing the delete. Impressive. [sarcasm]

so Im a huge fan of sarcasm in the social world but in the issue tracker here it's not really appropriate.  mostly because it makes me want to respond with a bunch of RTFM type answers instead of just clarifying and nobody needs that.

delete is awaitable.  Check the docs: https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncSession.delete
