### ISSUE TITLE
Document `AsyncAdaptedQueue` in relation to `create_async_engine` and raise for incompatible pool classes

### ISSUE THREAD

**Issue by dybi** [sqlalchemy/sqlalchemy#8771] opened 2022-11-08 07:45 UTC
### Describe the use case

`AsyncAdaptedQueue` is not documented - neither in [Available Pool Implementations](https://docs.sqlalchemy.org/en/14/core/pooling.html#api-documentation-available-pool-implementations) nor in [Async Engine API](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#engine-api-documentation).

What is more, even in the source code docstrings there is no information about it.

The lack of thereof has lead to reproduction of [Main thread is blocked on concurrent async operations ](https://github.com/sqlalchemy/sqlalchemy/issues/5581) bug in our code.

### Databases / Backends / Drivers targeted

All.

### Example Use

SIMPLIFIED
```python
def get_engine_kwargs():
    # AsyncAdaptedQueuePool shoul be used, but docs don't mention it
    return { 'poolclass': QueuePool}

engine = create_async_engine(DATABASE_URL, echo=True, **get_engine_kwargs())
async_session = sessionmaker(
    engine, class_=AsyncSession, expire_on_commit=False, future=True,
)

async def query_in_session(param):
     session = async_session()
     try:
          results = await session.scalars(select(param))
          return results.unique().one()
     finally:
         await session.close()

async def main():
   return await asyncio.gather(query_in_session(1), query_in_session(2))

asyncio.run(main())

```

### Additional context

In the project we are introducing async `SQLAlchemy` usage - we had some helper classes that were used to build underlying `engine` and `session`s. We were reusing the existing code, particularly a method that was supplying engine kwargs to `create_engine()`. The same helper method was used to supply kwargs for `create_async_engine()` resulting in `QueuePool` being passed as `pool_class` for async engine, which led to above described bug reproduction.

**Comment by zzzeek** [comment] 2022-11-08 13:18
im not sure QueuePool would make that easy or not.   I'm not around much today so while I would initially lean towards just documenting AsyncAdaptedQueuePool , if QueuePool can do this as a one liner, then *maybe*.   I haven't looked lately

**Comment by CaselIT** [comment] 2022-11-08 13:40
I'm not sure if dialect is always required for the pool. I'll check

**Comment by lricardo** [comment] 2023-12-05 12:07
I'm grateful that this issue is still open because it provides the solution for the issue we had. 

In SQLAlchemy 2.0.23, we were using QueuePool inside a FastAPI application. Using QueuePool with high traffic volume was casually locking the event loop. After doing a few tests with Locust, I noticed that it was reproducible and happened each time the queue pool size + max_overflow was on limit. If it was locking that meant that somewhere in our configuration, the code was not entirely async. After digging, I found this thread, replaced the QueuePool with AsyncAdaptedQueuePool and... ok, no further problems!

At the least by now, if we are using Asyncio, it's probably better to use the AsyncAdaptedQueuePool. Could this be added in the documentation? Thanks in advance

**Comment by CaselIT** [comment] 2023-12-05 12:16
strange that nothing is raising an error in this case. I though there was a check that did that.

**Comment by rmorshea** [comment] 2024-02-14 21:43
This issue took us several days to resolve due to the lack of docs. I'm sure others would benefit from this being shown in a couple examples.

**Comment by zzzeek** [comment] 2024-02-14 21:59
is the issue that you saw the docs at https://docs.sqlalchemy.org/en/14/core/pooling.html#switching-pool-implementations and applied AsyncAdaptedQueuePool to asyncengine?  we should document that but also make it so create_async_engine should raise an error if QueuePool is passed

**Comment by rmorshea** [comment] 2024-02-15 00:53
We were explicitly passing `poolclass=QueuePool` so an error there would have saved us a lot of time.

**Comment by sqla-tester** [comment] 2024-02-15 02:11
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**raise for asyncio-incompatible pool classes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5168

**Comment by sqla-tester** [comment] 2024-02-15 02:11
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**raise for asyncio-incompatible pool classes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5169

**Closed** 2024-02-20 15:09 UTC
Labels: bug, connection pool, engine, asyncio, near-term release
