### ISSUE TITLE
we likely need to keep some mention of postgresql 8.2 around to have nominal redshift support

### ISSUE THREAD

**Issue by zoomequipd** [sqlalchemy/sqlalchemy#9442] opened 2023-03-07 15:30 UTC
### Describe the bug

I believe there is a regression of https://github.com/sqlalchemy/sqlalchemy/issues/5698 in 2.0.0

I get the below error after updating from 1.4.46 and have confirmed it present in 2.0.0 - 2.0.5.post1
```
UndefinedObject: unrecognized configuration parameter "standard_conforming_strings"
```

The logic added in  https://github.com/sqlalchemy/sqlalchemy/commit/415ddce1e3b429bdc1180c5b5f7750a08d226525
does not appear to be present in 2.0.0

It appears to have been removed in https://github.com/sqlalchemy/sqlalchemy/commit/db08a699489c9b0259579d7ff7fd6bf3496ca3a2

as seen in 
![Screenshot 2023-03-07 at 8 18 23 AM](https://user-images.githubusercontent.com/4827852/223449134-3003f53c-3629-4e8d-85e7-64bf80a33bd8.png)

### SQLAlchemy Version in Use

2.0.5post1

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

Redshift 1.0.46987

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
import sqlalchemy
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text

connection_string = 'postgresql+psycopg2://<redacted username>:<redacted url encoded password>@<redacted db hostname>:<redacted port>/<redacted database>'

redshift_engine = sqlalchemy.create_engine(connection_string, echo=False, pool_recycle=120, pool_pre_ping=True)

redshift_session = sessionmaker(bind=redshift_engine)

tmp_session = redshift_session()
tmp_session.query(text("SELECT * from my_schema.my_table limit 10")).all()
```

### Error

```
Traceback (most recent call last):
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: unrecognized configuration parameter "standard_conforming_strings"
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/username/Downloads/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2715, in all
    return self._iter().all()  # type: ignore
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2875, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2114, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1981, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/username/.local/share/virtualenvs/Traceback (most recent call last):
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: unrecognized configuration parameter "standard_conforming_strings"
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/username/Downloads/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2715, in all
    return self._iter().all()  # type: ignore
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2875, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2114, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1981, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
    conn = bind.connect()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3245, in connect
    return self._connection_cls(self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 916, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1912, in go
    return once_fn(*arg, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 746, in first_connect
    dialect.initialize(c)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 654, in initialize
    super().initialize(connection)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3028, in initialize
    std_string = connection.exec_driver_sql(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1772, in exec_driver_sql
    ret = self._execute_context(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) unrecognized configuration parameter "standard_conforming_strings"
[SQL: show standard_conforming_strings]
(Background on this error at: https://sqlalche.me/e/20/f405)-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
    conn = bind.connect()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3245, in connect
    return self._connection_cls(self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1255, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 916, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1912, in go
    return once_fn(*arg, **kw)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 746, in first_connect
    dialect.initialize(c)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 654, in initialize
    super().initialize(connection)
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3028, in initialize
    std_string = connection.exec_driver_sql(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1772, in exec_driver_sql
    ret = self._execute_context(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/username/.local/share/virtualenvs/project01-Z0F7Zsx7/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) unrecognized configuration parameter "standard_conforming_strings"
[SQL: show standard_conforming_strings]
(Background on this error at: https://sqlalche.me/e/20/f405)
``` 

### Additional context

Downgrading to 1.4.46 has provided a workaround

**Comment by zzzeek** [comment] 2023-03-07 15:44
@CaselIT  in db08a699489 we bumped PG support to 9 and reenabled this query however the "8.2 " thing  is also relied upon by redshift.  I'm not sure what the status of https://pypi.org/project/sqlalchemy-redshift/ is on this but they very possibly rely upon it also

**Comment by sqla-tester** [comment] 2023-03-07 15:52
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**restore nominal "<8.2" checks to assist with redshift** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4496

**Comment by zoomequipd** [comment] 2023-03-07 16:20
sorry, looks like I accidentally caused this issue to be closed, reopening.

**Comment by CaselIT** [comment] 2023-03-07 16:37
Since there is an external redshift dialect, I'm not sure why should the internal pg dialect accommodate things for it?

It's easy enough to override that logic in the external dialect.

**Comment by zoomequipd** [comment] 2023-03-07 17:17
FWIW, the external redshift dialect doesn't support SQLAlchemy 2.0.0+ 
https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/264
and currently requires the use of SQLAlchemy < 2.0.0
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sqlalchemy-redshift 0.8.12 requires SQLAlchemy<2.0.0,>=0.9.2, but you have sqlalchemy 2.0.0 which is incompatible.
```

I know this isn't really your "problem" but it might factor into any solution that depends on the external dialect.

**Comment by zzzeek** [comment] 2023-03-07 17:21
sqlalchemy-redshift needs to take this on

**Comment by matthewgdv** [comment] 2023-03-13 17:00
I'm currently looking into making this fix downstream for `sqlalchemy-redshift` but I can't really see any sane way to override this behaviour as it stands without copy-pasting several layers of upstream initialization code from `sqlalchemy` and `psycopg2`.

I was hoping we might reconsider reopening this in order to supply a method we can use as a dialect-specific override hook for the backslash escapes logic, as Federico suggested in the now-closed PR: 

https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4496/1/lib/sqlalchemy/dialects/postgresql/base.py

**Comment by CaselIT** [comment] 2023-03-13 18:36
ok, let's reopen this to support that logic

**Comment by sqla-tester** [comment] 2023-03-13 18:38
**Matt del Valle** has proposed a fix for this issue in the **main** branch:

**Add override hook PGDialect.set_backslash_escapes()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4508

**Closed** 2023-03-15 22:25 UTC
Labels: bug, wontfix / out of scope, postgresql, regression, next release

**Comment by tfrokt** [comment] 2023-03-17 04:17
@matt-del-valle-outplay  I don't think the commit [65eb057](https://github.com/sqlalchemy/sqlalchemy/commit/65eb057d0c586f2eed43ac0731822053f0f6d472) referenced by @sqlalchemy-bot would work for Redshift. Redshift does not understand `standard_conforming_strings`. To keep this compatible this should not be executed at all.

**Comment by CaselIT** [comment] 2023-03-17 07:07
The idea is to make to easy for the redshirt dialect to bypass that query. The internal postgresql dialect will keep the min supported version to 9

**Comment by matthewgdv** [comment] 2023-03-17 09:59
@tfrokt On its own this change doesn't really do anything, but together with [this PR](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/266) we can easily avoid emitting `show standard_conforming_strings`

**Comment by tfrokt** [comment] 2023-03-17 13:53
@matthewgdv that makes total sense!! Thanks for the quick replies and the good work on it both! (and all others too)

**Comment by sudoandros** [comment] 2024-12-20 01:02
Hey everyone! I didn't really understand from the latest comments, was the problem eventually solved? If so, could you please give a hint about how to connect to a Redshift DB? I've tried it just now and I'm getting the exact same error

**Comment by CaselIT** [comment] 2024-12-20 07:26
You should use the redshift dialect to connect to redshift, not the postgresql one

**Comment by sudoandros** [comment] 2024-12-20 19:11
Am I doing something wrong because I use redshift dialect and still getting the error?
The code to reproduce: 
```python
import os

from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

url = URL.create(
    drivername="redshift+psycopg2",
    host="asdf.redshift-serverless.amazonaws.com",
    port=5439,
    database="dev",
    username=os.environ["USER"],
    password=os.environ["PASSWORD"],
)


engine = create_engine(url)
engine.connect()
```

Packages installed:
```
greenlet                     3.1.1
psycopg2                     2.9.10
sqlalchemy                   2.0.36
sqlalchemy-redshift          0.7.0
typing-extensions            4.12.2
```

Do I need to create a new issue for this?

**Comment by CaselIT** [comment] 2024-12-20 20:48
i would start by updating the redshift dialect. If that's still giving issues, sure open an issue to the redshift dialect developers

**Comment by torext** [comment] 2025-04-08 08:04
@jonasddev This looks promising, but when I put all the code as written in a single module I get a circular import error. How exactly are you structuring this code of yours in modules so that it works?
