### ISSUE TITLE
ORM forgets attribute after lazy loading relationship (and emits a spurious COMMIT)

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#6233] opened 2021-04-09 13:54 UTC
**Describe the bug**
I found a bug (or 2?) with sqlalchemy 1.4.6 that happens when lazy loading a relationship.
It seems that the lazy loading will wipe an attribute on the model that I just set, and it will also emit a COMMIT statement without a reason to.
SQLAlchemy 1.3.19 instead works as expected.

**Expected behavior**
A COMMIT statement should not be issued when accessing a relationship, and the attribute should stay as set before.

**To Reproduce**
```python3
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker


Base = declarative_base()

engine = create_engine('sqlite:///:memory:', echo=True)


class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)

    important_attribute = Column(String(40), index=True, unique=True)

    bar_id = Column(Integer, ForeignKey("bar.id"))
    bar = relationship("Bar")


class Bar(Base):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)


Base.metadata.create_all(engine)
session = sessionmaker(bind=engine)()


foo = Foo()
session.add(foo)
session.commit()

foo.important_attribute = "something_important"
assert foo.important_attribute == "something_important"

print("Going to access foo.bar...")
foo.bar  # Triggers COMMIT and resets `foo.important_attribute` to None
assert foo.important_attribute == "something_important"  # AssertionError: foo.important_attribute is None

```

**Error**

```
2021-04-09 15:52:23,915 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-09 15:52:23,916 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("foo")
2021-04-09 15:52:23,916 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-09 15:52:23,917 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("foo")
2021-04-09 15:52:23,917 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-09 15:52:23,918 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("bar")
2021-04-09 15:52:23,918 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-09 15:52:23,918 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("bar")
2021-04-09 15:52:23,918 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-09 15:52:23,919 INFO sqlalchemy.engine.Engine 
CREATE TABLE bar (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2021-04-09 15:52:23,920 INFO sqlalchemy.engine.Engine [no key 0.00015s] ()
2021-04-09 15:52:23,921 INFO sqlalchemy.engine.Engine 
CREATE TABLE foo (
	id INTEGER NOT NULL, 
	important_attribute VARCHAR(40), 
	bar_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(bar_id) REFERENCES bar (id)
)


2021-04-09 15:52:23,921 INFO sqlalchemy.engine.Engine [no key 0.00014s] ()
2021-04-09 15:52:23,921 INFO sqlalchemy.engine.Engine CREATE UNIQUE INDEX ix_foo_important_attribute ON foo (important_attribute)
2021-04-09 15:52:23,921 INFO sqlalchemy.engine.Engine [no key 0.00014s] ()
2021-04-09 15:52:23,922 INFO sqlalchemy.engine.Engine COMMIT
2021-04-09 15:52:23,929 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-09 15:52:23,931 INFO sqlalchemy.engine.Engine INSERT INTO foo (important_attribute, bar_id) VALUES (?, ?)
2021-04-09 15:52:23,931 INFO sqlalchemy.engine.Engine [generated in 0.00026s] (None, None)
2021-04-09 15:52:23,931 INFO sqlalchemy.engine.Engine COMMIT
Going to access foo.bar...
2021-04-09 15:52:23,933 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-09 15:52:23,936 INFO sqlalchemy.engine.Engine SELECT foo.id AS foo_id, foo.bar_id AS foo_bar_id 
FROM foo 
WHERE foo.id = ?
2021-04-09 15:52:23,936 INFO sqlalchemy.engine.Engine [generated in 0.00023s] (1,)
2021-04-09 15:52:23,939 INFO sqlalchemy.engine.Engine UPDATE foo SET important_attribute=? WHERE foo.id = ?
2021-04-09 15:52:23,939 INFO sqlalchemy.engine.Engine [generated in 0.00021s] ('something_important', 1)
2021-04-09 15:52:23,939 INFO sqlalchemy.engine.Engine COMMIT
2021-04-09 15:52:23,939 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-09 15:52:23,940 INFO sqlalchemy.engine.Engine SELECT foo.id AS foo_id, foo.bar_id AS foo_bar_id 
FROM foo 
WHERE foo.id = ?
2021-04-09 15:52:23,940 INFO sqlalchemy.engine.Engine [cached since 0.003962s ago] (1,)
python-BaseException
Traceback (most recent call last):
  File "/Users/youtux/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/youtux/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/youtux/Library/Application Support/JetBrains/PyCharm2021.1/scratches/sqla_orm_bug.py", line 38, in <module>
    assert foo.important_attribute == "something_important"  # AssertionError: foo.important_attribute is None
AssertionError
```

**Versions.**
 - OS: macOS 11.2.1
 - Python: 3.6.12
 - SQLAlchemy: 1.4.6
 - Database: MySQL, sqlite (probably all)
 - DBAPI: mysqlclient, sqlite3

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-04-09 14:58
it's extraordinary regression day, first #6232 and now this.   1.4 has been out for five months, millions of downloads, another super basic case.    thanks for reporting!

**Comment by youtux** [comment] 2021-04-09 15:11
It must be “upgrade your dependencies Friday” :).
Thank you for your great work!

**Comment by zzzeek** [comment] 2021-04-09 15:39
the commit thing is simple.  the second part where the attribute is none is limited to legacy autocommit mode and appears to be due to #5226 , and has some overlap with things that don't work correctly in 1.3 either related to autocommit mode.    havent fully figured that part out yet.

**Comment by sqla-tester** [comment] 2021-04-09 15:57
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Dont return outer transaction for _subtrans flag** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2730

**Closed** 2021-04-09 16:36 UTC
Labels: bug, orm, regression
