### ISSUE TITLE
Support comments on SQL Server

### ISSUE THREAD

**Issue by dhirschfeld** [sqlalchemy/sqlalchemy#7844] opened 2022-03-23 10:40 UTC
### Describe the use case

It appears that support for comments was implemented in https://github.com/sqlalchemy/sqlalchemy/commit/fadb8d61babb76ef7bdbc98279096a8900c7328d, however it wasn't implemented for SQL Server - https://github.com/sqlalchemy/sqlalchemy/issues/1546#issuecomment-441906255

```python
 In[14]: engine.dialect
Out[14]: <sqlalchemy.dialects.mssql.pyodbc.MSDialect_pyodbc at 0x1db4d5289c8>

 In[15]: engine.dialect.supports_comments
Out[15]: False
```

It would be great if comments were also supported for SQL Server.

### Databases / Backends / Drivers targeted

MSSQL

### Example Use

NA

### Additional context

Just opening an issue to document and track this feature request as it took me a while to understand why the comments weren't working on my Azure SQL Database.

**Comment by DanielHall977** [comment] 2022-06-28 23:24
I'll handle this issue

**Comment by DanielHall977** [comment] 2022-06-29 17:02
Does anyone know how to test if comments are working?

I tried adding 'mssql' to https://github.com/sqlalchemy/sqlalchemy/blob/main/test/requirements.py#L169 line 171, but it had no effect on test completion.

I've looked at the postgresql test section, but didn't see any tests added for comments. See: https://github.com/sqlalchemy/sqlalchemy/commit/fadb8d61babb76ef7bdbc98279096a8900c7328d?diff=unified#diff-a695de14d9b9334a293e5b0fbd0b70ce49d101fa2f13ea2ec8e27888c6f54dca

Does anyone know how to test/verify, the above issue?

**Comment by zzzeek** [comment] 2022-06-29 17:10
looking in 5fb63bc1423e75812a24e809 it does not appear any tests are yet making use of the `constraint_comment_reflection` requirement that was added.  

you can try adding constraint comments to sqlalchemy/testing/suite/test_reflection.py -> ComponentReflectionTestExtra.test_get_check_constraints(), then doing a conditional check on the round trip:

```py
if testing.requires.constraint_comment_reflection.enabled:
    eq_(reflected , .... test data with comments ...)
else:
   eq_(reflected, ... test data without comments...)
```

you can run that test directly as

```

pytest test/dialect/test_suite.py::ComponentReflectionTestExtra::test_get_check_constraints  --db mssql --log-debug=sqlalchemy.engine -s

```

that will also log all the SQL so you can see it

**Comment by zzzeek** [comment] 2022-06-29 17:10
not sure why the button clicked closed...

**Comment by zzzeek** [comment] 2022-06-29 17:11
ahha.  github has broken shift-enter.   got it.   here i am carefully pushing "comment" with the mouse

**Comment by DanielHall977** [comment] 2022-06-29 17:59
Running that test (with no modifications to SqlAlchemy) gives me:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 145, in __init__
INTERNALERROR>     self._dbapi_connection = engine.raw_connection()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2956, in raw_connection
INTERNALERROR>     return self.pool.connect()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 384, in connect
INTERNALERROR>     return _ConnectionFairy._checkout(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 1175, in _checkout
INTERNALERROR>     fairy = _ConnectionRecord.checkout(pool)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 647, in checkout
INTERNALERROR>     rec = pool._do_get()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/impl.py", line 169, in _do_get
INTERNALERROR>     self._dec_overflow()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 148, in __exit__
INTERNALERROR>     raise exc_value.with_traceback(exc_tb)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/impl.py", line 166, in _do_get
INTERNALERROR>     return self._create_connection()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 325, in _create_connection
INTERNALERROR>     return _ConnectionRecord(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 610, in __init__
INTERNALERROR>     self.__connect()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 828, in __connect
INTERNALERROR>     pool.logger.debug("Error on connect(): %s", e)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 148, in __exit__
INTERNALERROR>     raise exc_value.with_traceback(exc_tb)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 823, in __connect
INTERNALERROR>     self.dbapi_connection = connection = pool._invoke_creator(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/create.py", line 612, in connect
INTERNALERROR>     return dialect.connect(*cargs, **cparams)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/default.py", line 539, in connect
INTERNALERROR>     return self.loaded_dbapi.connect(*cargs, **cparams)
INTERNALERROR> pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/.tox/py/lib/python3.8/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/.tox/py/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/.tox/py/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/.tox/py/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/.tox/py/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/.tox/py/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py", line 129, in pytest_sessionstart
INTERNALERROR>     asyncio._assume_async(plugin_base.post_begin)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/testing/asyncio.py", line 53, in _assume_async
INTERNALERROR>     return _util_async_run(fn, *args, **kwargs)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/concurrency.py", line 66, in _util_async_run
INTERNALERROR>     return fn(*arg, **kw)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/plugin_base.py", line 285, in post_begin
INTERNALERROR>     fn(options, file_config)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/plugin_base.py", line 432, in _engine_uri
INTERNALERROR>     cfg = provision.setup_config(
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/testing/provision.py", line 80, in setup_config
INTERNALERROR>     eng.connect().close()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2932, in connect
INTERNALERROR>     return self._connection_cls(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 147, in __init__
INTERNALERROR>     Connection._handle_dbapi_exception_noconnection(
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2110, in _handle_dbapi_exception_noconnection
INTERNALERROR>     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 145, in __init__
INTERNALERROR>     self._dbapi_connection = engine.raw_connection()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2956, in raw_connection
INTERNALERROR>     return self.pool.connect()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 384, in connect
INTERNALERROR>     return _ConnectionFairy._checkout(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 1175, in _checkout
INTERNALERROR>     fairy = _ConnectionRecord.checkout(pool)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 647, in checkout
INTERNALERROR>     rec = pool._do_get()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/impl.py", line 169, in _do_get
INTERNALERROR>     self._dec_overflow()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 148, in __exit__
INTERNALERROR>     raise exc_value.with_traceback(exc_tb)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/impl.py", line 166, in _do_get
INTERNALERROR>     return self._create_connection()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 325, in _create_connection
INTERNALERROR>     return _ConnectionRecord(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 610, in __init__
INTERNALERROR>     self.__connect()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 828, in __connect
INTERNALERROR>     pool.logger.debug("Error on connect(): %s", e)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 148, in __exit__
INTERNALERROR>     raise exc_value.with_traceback(exc_tb)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/pool/base.py", line 823, in __connect
INTERNALERROR>     self.dbapi_connection = connection = pool._invoke_creator(self)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/create.py", line 612, in connect
INTERNALERROR>     return dialect.connect(*cargs, **cparams)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/default.py", line 539, in connect
INTERNALERROR>     return self.loaded_dbapi.connect(*cargs, **cparams)
INTERNALERROR> sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")
INTERNALERROR> (Background on this error at: https://sqlalche.me/e/20/dbapi)
```

**Comment by zzzeek** [comment] 2022-06-29 18:21
do you have a working SQL Server ODBC connection set up ?    the "--db mssql" is a pre-established URL, but you should use "--dburi <your uri>" on your end.   see https://github.com/sqlalchemy/sqlalchemy/blob/main/README.unittests.rst#setting-up-databases

**Comment by CaselIT** [comment] 2022-06-29 19:01
> looking in [5fb63bc](https://github.com/sqlalchemy/sqlalchemy/commit/5fb63bc1423e75812a24e809d16731a3282c2a12) it does not appear any tests are yet making use of the `constraint_comment_reflection` requirement that was added.

there are already tests on this. The comments are added to the table and the expected object. If a dialect does not return them they are ignored from the expected object, otherwise if a dialect returns them then they need to be as expected.

**Comment by CaselIT** [comment] 2022-06-29 19:03
also regarding `constraint_comment_reflection` I think this is focused only on table comments, not on constrain comment (at least I think)

**Comment by DanielHall977** [comment] 2022-06-29 19:35
> also regarding `constraint_comment_reflection` I think this is focused only on table comments, not on constrain comment (at least I think)

I was confused at first as well. The `check_constraint` will also test the use case right? Or should I be looking at another test?

**Comment by CaselIT** [comment] 2022-06-29 19:46
It depends on what you are adding comments to. From my understanding we are talking about table comments only? In that case `constraint_comment_reflection ` should not be changed, but the other `comment_reflection` should instead be changed

I don't think mssql has any reflection of check constraints at the moment, so comment there are definitely not gonna be reflected

**Comment by DanielHall977** [comment] 2022-06-29 20:25
> It depends on what you are adding comments to. From my understanding we are talking about table comments only? In that case `constraint_comment_reflection ` should not be changed, but the other `comment_reflection` requirement should instead be updated

So what test should I be updating to for the regular comment_reflection requirements?

**Comment by CaselIT** [comment] 2022-06-29 20:27
the tests should be enabled automatically once `comment_reflection` has been updated

**Comment by DanielHall977** [comment] 2022-06-30 00:03
I'm stuck in dependency hell.

tox requires a python version >=3.7 (but <3.9)
When I upgrade my python version, certain features of my machine (like opening a terminal) stop working. To get it working again, I need to run `sudo apt-get --reinstall install python3-minimal` which resets my python version back to 3.6 (and clears out any modifications I made to get tox working (I hope))
If I'm content to let my machine be broken in certain respects and focus on tox, I still can't get an mssql database installed on my machine, I resorted to manually installing modules to make that happen. But one just won't work, 'gi' (not necessarily the last). The only solution I haven't tried is to switch to another python version... 
```
sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 12, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 67, in <module>
    from gi.repository import Gio
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```
I've even tried:  `tox -e py38-sqlite` it just hangs for me.

I'm stuck :frowning_face:

**Comment by dhirschfeld** [comment] 2022-06-30 00:25
> not sure why the button clicked closed...

https://twitter.com/mariorod1/status/1542189296240713730

**Comment by CaselIT** [comment] 2022-06-30 06:36
> tox requires a python version >=3.7 (but <3.9)

We use tox with 3.10 and also 3.11 so i'm not sure where it requires python<3.9
The main branch no longer supports python 3.6 so you cannot use it.

> I still can't get an mssql database installed on my machine

My suggestion would be to use docker or similar. Readme.unitest.rst has a series of instructions to setup a mssql db 

Regarding the different versions of python I usually use conda to menage them. When creating a virtual evn you can specify the python version to use without needing to make changes to the globally installed versions

**Comment by zzzeek** [comment] 2022-06-30 12:59
> > not sure why the button clicked closed...
> 
> https://twitter.com/mariorod1/status/1542189296240713730

amazing find how did you find that tweet?

**Comment by DanielHall977** [comment] 2022-06-30 16:00
Sorry for the confusion, this is my first time contributing to open source. And I was trying to use the system python to run the tests. But I talked to a friend and he got me squared away on virtual environments.

**Comment by zzzeek** [comment] 2022-06-30 16:30
I am thrilled.   Some years ago I walked @CaselIT through everything, and now here we are and he's doing the same for more contributors!   thanks so much for getting into it.

**Comment by DanielHall977** [comment] 2022-06-30 17:34
What does this error mean?
```
pytest test/dialect/test_suite.py::ComponentReflectionTestExtra::test_get_check_constraints  --db docker_mssql --log-debug=sqlalchemy.engine -s
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/venv/lib/python3.9/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py", line 129, in pytest_sessionstart
INTERNALERROR>     asyncio._assume_async(plugin_base.post_begin)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/testing/asyncio.py", line 53, in _assume_async
INTERNALERROR>     return _util_async_run(fn, *args, **kwargs)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/_concurrency_py3k.py", line 218, in _util_async_run
INTERNALERROR>     return loop.run_until_complete(greenlet_spawn(fn, *args, **kwargs))
INTERNALERROR>   File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
INTERNALERROR>     return future.result()
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/_concurrency_py3k.py", line 154, in greenlet_spawn
INTERNALERROR>     result = context.switch(*args, **kwargs)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/plugin_base.py", line 285, in post_begin
INTERNALERROR>     fn(options, file_config)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/plugin_base.py", line 432, in _engine_uri
INTERNALERROR>     cfg = provision.setup_config(
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/testing/provision.py", line 78, in setup_config
INTERNALERROR>     eng = engines.testing_engine(db_url, db_opts)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/testing/engines.py", line 344, in testing_engine
INTERNALERROR>     engine = create_engine(url, **options)
INTERNALERROR>   File "<string>", line 2, in create_engine
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/util/deprecations.py", line 325, in warned
INTERNALERROR>     return fn(*args, **kwargs)  # type: ignore[no-any-return]
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/engine/create.py", line 577, in create_engine
INTERNALERROR>     dbapi = dbapi_meth(**dbapi_args)
INTERNALERROR>   File "/home/dhall/dev/opensource/sqlalchemy/lib/sqlalchemy/connectors/pyodbc.py", line 58, in import_dbapi
INTERNALERROR>     return __import__("pyodbc")
INTERNALERROR> ModuleNotFoundError: No module named 'pyodbc'
```

**Comment by CaselIT** [comment] 2022-06-30 17:42
> Sorry for the confusion, this is my first time contributing to open source. And I was trying to use the system python to run the tests. But I talked to a friend and he got me squared away on virtual environments.

No problem! My advice is to avoid messing with system python since wired stuff will happen. Sadly the python dependency management is not the best, so it's always best to use virtual envs :)

Regarding the error, you are missing the pyodbc package that's required for connecting to mssql

**Comment by DanielHall977** [comment] 2022-06-30 17:45
And when I try to install it I get:
```
pip install pyodbc
Collecting pyodbc
  Using cached pyodbc-4.0.32.tar.gz (280 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pyodbc, since package 'wheel' is not installed.
Installing collected packages: pyodbc
  Running setup.py install for pyodbc ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyodbc did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running install
      running build
      running build_ext
      building 'pyodbc' extension
      creating build
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/src
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.32 -I/home/dhall/dev/opensource/sqlalchemy/venv/include -I/usr/include/python3.9 -c src/buffer.cpp -o build/temp.linux-x86_64-3.9/src/buffer.o -Wno-write-strings
      In file included from src/buffer.cpp:12:0:
      src/pyodbc.h:45:10: fatal error: Python.h: No such file or directory
       #include <Python.h>
                ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyodbc

note: This is an issue with the package mentioned above, not pip.
```
Is that an issue with using python3.9 in my virtualenv?

**Comment by DanielHall977** [comment] 2022-06-30 17:56
found solution `sudo apt install python3.9-dev`

**Comment by DanielHall977** [comment] 2022-06-30 19:47
Ok, I've found the unit test for comments:
`pytest test/dialect/test_suite.py::ComponentReflectionTest::test_get_comments  --db docker_mssql --log-debug=sqlalchemy.engine -s`
Enabled comment_reflection for mssql

But when I run 'tox' it says that all tests passed just fine. Why would that happen when the test above fails?

**Comment by CaselIT** [comment] 2022-06-30 20:10
iirc by default tox runs using sqlite, so maybe that's the reason.

In any case if you run pytest using 
```
pytest test/dialect/test_suite.py -k ComponentReflectionTest --db docker_mssql --log-debug=sqlalchemy.engine -s
```
you should be able to run most reflection tests

**Comment by DanielHall977** [comment] 2022-06-30 22:37
Ok, I have a few questions on the code. The commit (https://github.com/sqlalchemy/sqlalchemy/commit/fadb8d61babb76ef7bdbc98279096a8900c7328d) you guys sent me is missing some key details on the implementation of the comments. Take postgresql for example, the comments are stored in a special table pg_catalog.pg_description that was implemented before the comments were enabled for reflection. Now this leads me to some pressing questions, in order of increasing significance:

1. Why is pg_description it's own table instead of just an extra column?
2. Where is the information in pg_description being set? I can't find it anywhere in the code.
3. Is there anything else I will need to consider when adding a comment column/table to mssql? mssql does not currently have an existing comment column/table.

**Comment by dhirschfeld** [comment] 2022-07-01 04:36
IIUC SQL Server uses a custom `MS_Description` *"extended property"* to store comments for schemas/tables/columns.

To add a column comment you would use the [`sp_addextendedproperty`](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addextendedproperty-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16) proc with a property name of `N'MS_Description'` and level types:
```
@level0type = N'SCHEMA'
@level1type = N'TABLE'
@level2type = N'COLUMN'
```

IIUC the extended properties can be queried from the [`sys.extended_properties`](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/extended-properties-catalog-views-sys-extended-properties?redirectedfrom=MSDN&view=sql-server-ver16) table

**Comment by CaselIT** [comment] 2022-07-01 07:05
> 1. pg_description

All tables that are in the `pg_catalog` schema are system tables that are populated by postgresql when executing ddl statements. They are not set directly by user code (doing so will most likely lead to a corrupt databas). Also the pg_catalog schema os custom to postgresql, other databases will use different ways of returning that information.

**Comment by DanielHall977** [comment] 2022-07-06 16:00
Ok, where does code set the table comments?
I added: `visit_set_table_comment` to mssql/base.py, but it doesn't look like it's getting called.
How does the code set the table comments?

**Comment by DanielHall977** [comment] 2022-07-06 19:20
That was it, thank!

**Comment by DanielHall977** [comment] 2022-07-06 19:43
What is the expected behavior if schema is not specified? Is there a default schema that it goes to? Do I need to halt the program and throw an exception?

**Comment by CaselIT** [comment] 2022-07-06 19:46
I believe the dialect has a default schema accessor you can use in `dialect.default_schema_name`

**Comment by DanielHall977** [comment] 2022-07-07 16:05
Do you know how to test the column comments? I've got table comments working, but I'm not sure where the tests are for column comments. Do I need to add mssql to some other set of requirements?

**Comment by CaselIT** [comment] 2022-07-07 19:23
there is. you should probably see what the default version does:

https://github.com/sqlalchemy/sqlalchemy/blob/805a1323b973a30af99ce506dd5c5c4ab96cff0f/lib/sqlalchemy/sql/compiler.py#L5153-L5160

that uses `self.sql_compiler.render_literal_value`

**Comment by CaselIT** [comment] 2022-07-07 19:52
You can probably use `self.preparer.quote` from the compiler method

**Comment by DanielHall977** [comment] 2022-07-07 20:03
For some weird reason that one keeps asking for an ident argument, when I have the same number of args as all the other calls.

**Comment by CaselIT** [comment] 2022-07-07 20:22
strange. are you calling it from `visit_set_table_comment` as `self.prepared.quote(create.element.name)`?

**Comment by CaselIT** [comment] 2022-07-07 20:28
I don't think you need to use it in `get_table_comment`

if you require to quote something you a dialect has `self.quote()`

**Comment by DanielHall977** [comment] 2022-07-07 20:33
I submitted a pull request for this, so you can look at what I've got so far and play around with it.  https://github.com/sqlalchemy/sqlalchemy/pull/8225

**Comment by CaselIT** [comment] 2022-07-07 21:11
thanks! I'll take a look soon!

**Comment by DanielHall977** [comment] 2022-07-07 22:04
> if you require to quote something you a dialect has `self.quote()`

AttributeError: 'MSDialect_pymssql' object has no attribute 'quote'

**Comment by sqla-tester** [comment] 2022-08-08 21:47
**Daniel Hall** has proposed a fix for this issue in the **main** branch:

**Support comments on MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4016

**Closed** 2022-08-17 15:33 UTC
Labels: SQL Server, fairly easy, use case
