### ISSUE TITLE
Enumeration with " " value make reflection error

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/sqlalchemy#4701] opened 2019-05-30 10:50 UTC
If i create it with
```
ActionType = sqlalchemy.types.Enum(
    " ",
    metadata=Base.metadata, name="ActionType")
```
when i try to read them with alembic (reflection) then i get exception
 ```
File "<string>", line 8, in run_migrations
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
   self.get_context().run_migrations(**kw)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
   step.migration_fn(**kw)
 File "/hdd/work/projects/main/ekra-sql-orm-migrations/ekra_sql_orm_migrations/alembic/versions/7255ad6ccc0f_.py", line 50, in upgrade
   print(compare_metadata(mc, Base.metadata))
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 104, in compare_metadata
   migration_script = produce_migrations(context, metadata)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 134, in produce_migrations
   compare._populate_migration_script(autogen_context, migration_script)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 25, in _populate_migration_script
   _produce_net_changes(autogen_context, upgrade_ops)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 51, in _produce_net_changes
   autogen_context, upgrade_ops, schemas
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/util/langhelpers.py", line 303, in go
   fn(*arg, **kw)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 83, in _autogen_for_tables
   autogen_context,
 File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 164, in _compare_tables
   inspector.reflecttable(t, None)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 633, in reflecttable
   table_name, schema, **table.dialect_kwargs
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 372, in get_columns
   self.bind, table_name, schema, info_cache=self.info_cache, **kw
 File "<string>", line 2, in get_columns
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
   ret = fn(self, con, *args, **kw)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2850, in get_columns
   comment,
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2967, in _get_column_info
   coltype = coltype(*args, **kwargs)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1397, in __init__
   super(ENUM, self).__init__(*enums, **kw)
 File "<string>", line 2, in __init__
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 130, in warned
   return fn(*args, **kwargs)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1359, in __init__
   self._enum_init(enums, kw)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1399, in _enum_init
   length = max(len(x) for x in self.enums)
 File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1399, in <genexpr>
   length = max(len(x) for x in self.enums)
TypeError: object of type 'NoneType' has no len()
```

**Comment by zzzeek** [comment] 2019-05-30 12:49
hi there -

cannot reproduce.  Please supply complete information, including:


1. version of Postgresql in use

2. version of SQLAlchemy in use 

3. Please take the following [MCVE](http://stackoverflow.com/help/mcve) and alter it to illustrate your stack trace, thanks!

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Enum
from sqlalchemy import MetaData
from sqlalchemy import Table

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

m = MetaData()


ActionType = Enum(" ", metadata=m, name="ActionType")

t = Table("t", m, Column("x", ActionType))

m.drop_all(e)
m.create_all(e)


m2 = MetaData()

t2 = Table("t", m2, autoload_with=e)

```

**Comment by zzzeek** [comment] 2019-05-31 00:32
this works though (well breaks):

    ActionType = Enum(metadata=m, name="ActionType")

**Comment by sqla-tester** [comment] 2019-05-31 00:43
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**PostgreSQL enum with no elements returns NULL for the "label", skip this** https://gerrit.sqlalchemy.org/1293

**Comment by sqla-tester** [comment] 2019-05-31 00:43
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**PostgreSQL enum with no elements returns NULL for the "label", skip this** https://gerrit.sqlalchemy.org/1294

**Comment by mrquokka** [comment] 2019-05-31 04:02
Do i need to attach an example so far?

**Comment by zzzeek** [comment] 2019-05-31 12:02
nope I figured it out , is the code you posted at the very top not exactly what you ran for real?   the `" "` part shouldn't be there to reproduce the issue.

**Closed** 2019-05-31 12:03 UTC
Labels: bug, datatypes, postgresql, reflection
