### ISSUE TITLE
unresolvable types are silently ignored

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8888] opened 2022-11-28 14:11 UTC
this should raise, but it just ignores the attribute entirely

```py
from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy import select

class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[fake]


print(select(A))
```

**Comment by CaselIT** [comment] 2022-11-28 15:32
I noticed it when working on the future annotation branch but though it was intended

**Comment by sqla-tester** [comment] 2022-11-28 16:07
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**identify unresolvable Mapped types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4250

**Comment by zzzeek** [comment] 2022-11-28 16:30
right well not if it's inside of `Mapped[]`

**Closed** 2022-11-28 19:43 UTC
Labels: bug, orm - annotated declarative
