### ISSUE TITLE
Postgres bulk upsert  - Can't match sentinel values in result set to parameter sets

### ISSUE THREAD

**Issue by fabioaraujopt** [sqlalchemy/sqlalchemy#11063] opened 2024-02-27 16:05 UTC
### Describe the bug

`InvalidRequestError: Can't match sentinel values in result set to parameter sets; key 'f8792961-96dd-4c03-971c-cec24a43fd6e' was not found. There may be a mismatch between the datatype passed to the DBAPI driver vs. that which it returns in a result row.  Ensure the given Python value matches the expected result type *exactly*, taking care to not rely upon implicit conversions which may occur such as when using strings in place of UUID or integer values, etc. `

while making a bulk "upsert" using this generic function, this error happens in a random way, sometimes it does sometimes it does not, while upsert a fixed number of 100 entities.

```
    async def add_all(self, session: AsyncSession, records: list[T]) -> Iterable[T]:
        # Add all records to the session and flush to get their database-generated values
        session.add_all(records)
        await session.flush()

        # Use 'sid' instead of 'id' if that's the correct attribute in your model
        sids = [record.sid for record in records]

        # Ensure that the select statement also uses 'sid' if that's the column name in your database
        result = await session.execute(select(self._model_cls).where(self._model_cls.sid.in_(sids)))

        return result.scalars().all()
```

this is the stack trace

```
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 892, in _deliver_insertmanyvalues_batches
    ordered_rows = [
                   ^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 893, in <listcomp>
    rows_by_sentinel[
KeyError: '268fd7e2-2b82-4114-af86-501d0f0922b4'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/elasticapm/contrib/starlette/__init__.py", line 193, in __call__
    await self.app(scope, _request_receive or receive, wrapped_send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/magneto_api/domain/audit_middleware.py", line 79, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/magneto_api/domain/entities/controllers.py", line 136, in create_or_update_entities_bulk
    return await services.upsert_entities_bulk(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/magneto_api/domain/entities/services.py", line 250, in upsert_entities_bulk
    await uow.entities.add_all(uow.session, parsed_entities)
  File "/app/src/magneto_api/lib/repository/generic_sql.py", line 32, in add_all
    await session.flush()
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 791, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 199, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1143, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1834, in _execute_context
    return self._exec_insertmany_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2021, in _exec_insertmany_context
    for imv_batch in dialect._deliver_insertmanyvalues_batches(
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 902, in _deliver_insertmanyvalues_batches
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't match sentinel values in result set to parameter sets; key '268fd7e2-2b82-4114-af86-501d0f0922b4' was not found. There may be a mismatch between the datatype passed to the DBAPI driver vs. that which it returns in a result row.  Ensure the given Python value matches the expected result type *exactly*, taking care to not rely upon implicit conversions which may occur such as when using strings in place of UUID or integer values, etc.
```

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

postgres15

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
Run the code above, and verify that randomely this upserts fail.
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by zzzeek** [comment] 2024-02-27 18:14
hey there -

so far this is not a proper bug report as it does not indicate a. models b. sample data to reproduce, and the error you are getting is not unexpected depending on the kind of value you are doing and how you might be populating your object.   also you are on an old version of SQLAlchemy, please try 2.0.27 as an issue with async drivers and UUID values was [just fixed recently](https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-4639ec87eaf921c2112a417fd59b027a) which may be related to what you are seeing.

if the update does not solve the issue then please provide models and sample data which reproduces the issue, please see [MCVE](http://stackoverflow.com/help/mcve)

**Comment by zzzeek** [comment] 2024-03-09 18:00
no repro info, closing

**Closed by zzzeek** 2024-03-09 18:00 UTC
Labels: orm, cant reproduce, awaiting info

**Comment by espdev** [comment] 2024-03-18 20:22
@zzzeek,

We ran into the same issue with Postgres. 

SQLAlchemy version: 2.0.28
asyncpg: 0.29.0

When we are adding two or more new objects (with new ID) we are getting the same error:
```
sqlalchemy.exc.InvalidRequestError: Can't match sentinel values in result set to parameter sets; key '3fa85f64-5717-4562-b3fc-2c963f66afa6' was not found. There may be a mismatch between the datatype passed to the DBAPI driver vs. that which it returns in a result row.  Ensure the given Python value matches the expected result type *exactly*, taking care to not rely upon implicit conversions which may occur such as when using strings in place of UUID or integer values, etc. 
```

If one or more added objects already exist (updating) it works without errors.

**Comment by zzzeek** [comment] 2024-03-18 20:30
Can you please illustrate the **exact** datatype and its configuration in Python which you are using for UUID ?   Is this the third party type (in which case this is all expected)

**Comment by espdev** [comment] 2024-03-18 20:52
@zzzeek,

We use UUIDv7 from [uuid6 package](https://github.com/oittaa/uuid6-python) for auto ID:
```python
Field(default_factory=uuid7, primary_key=True)
```

`sqlmodel.sql.sqltypes.GUID()` used as column type and standard `uuid.UUID` python type in models (we are using SQLModel package).

We also try to use the requests with uuid4, uuid5 IDs - the same.

**Comment by CaselIT** [comment] 2024-03-18 20:55
ok, the issue is the same, and that's the use of `sqlmodel.sql.sqltypes.GUID()`.

It will be fixed in the next release

**Comment by fernandocamargoai** [comment] 2024-03-19 20:38
I'm having this bug happen after adding a new column with `Computed`.

This is the code:
```python

class SimpleDocument(Base):
    __tablename__ = "simple_document"

    id = Column(String, primary_key=True)
    content = Column(String, nullable=False)
    checksum = Column(
        String, Computed("encode(digest(content, 'sha1'), 'hex')", persisted=True)
    )
    
    cmetadata = sqlalchemy.Column(JSON, nullable=True)

if __name__ == "__main__":
    doc_c1 = [
            SimpleDocument(
                id=11,
                content="test",
                cmetadata={
                    "simple_doc_id": 11,
                    "company_id": "1",
                    "rival_ids": [1],
                    "supported_rival_ids": [1],
                    "date": "2021-01-01",
                    "private": False,
                    "doc_type": "test",
                },
            ),
            SimpleDocument(
                id=12,
                content="test",
                cmetadata={
                    "simple_doc_id": 12,
                    "company_id": "1",
                    "rival_ids": [2],
                    "supported_rival_ids": [2],
                    "date": "2022-01-01",
                    "private": True,
                    "doc_type": "not_test",
                },
            ),
        ]
        doc_c2 = [
            SimpleDocument(
                id=21,
                content="test",
                cmetadata={
                    "simple_doc_id": 21,
                    "company_id": "2",
                    "rival_ids": [3],
                    "supported_rival_ids": [2],
                    "date": "2022-01-01",
                    "private": True,
                    "doc_type": "not_test",
                },
            ),
        ]
        doc_c3 = [
            SimpleDocument(
                id=31,
                content="test",
                cmetadata={
                    "simple_doc_id": 31,
                    "company_id": "3",
                    "rival_ids": [4],
                    "supported_rival_ids": [1],
                    "date": "2022-01-01",
                    "private": False,
                    "doc_type": "test",
                },
            )
        ]
    
        for doc in doc_c1 + doc_c2 + doc_c3:
            db.add(doc)
        db.commit()
```

If I remove `checksum`, even without removing it from the database (Postgres), it just works.

**Comment by zzzeek** [comment] 2024-03-19 20:44
that's unfortunately a different issue

**Comment by fernandocamargoai** [comment] 2024-03-19 20:44
> that's unfortunately a different issue

Thank you, @zzzeek. I'll move it to another issue.

**Comment by zzzeek** [comment] 2024-03-19 20:48
> > that's unfortunately a different issue
> 
> Thank you, @zzzeek. I'll move it to another issue.

nono, discussion, this is a limitation in postgresql

add this to your mapping

```
    __mapper_args__ = {"eager_defaults": False}

```

this will be a bug in PG, I will get a reproducer

**Comment by fernandocamargoai** [comment] 2024-03-19 20:50
> > > that's unfortunately a different issue
> > 
> > 
> > Thank you, @zzzeek. I'll move it to another issue.
> 
> nono, discussion, this is a limitation in postgresql
> 
> add this to your mapping
> 
> ```
>     __mapper_args__ = {"eager_defaults": False}
> ```
> 
> this will be a bug in PG, I will get a reproducer

Thank you very much, @zzzeek. This solves the problem for me!

**Comment by zzzeek** [comment] 2024-03-19 20:53
oh.     no, not even that.  

here is your bug:

    id = Column(String, primary_key=True)


then your data:

        SimpleDocument(
            id=11,
      )

that is wrong, you said these were strings

"There may be a mismatch between the datatype passed to the DBAPI driver vs. that which it returns in a result row.  Ensure the given Python value matches the expected result type *exactly*"

use strings if that's the datattype

        SimpleDocument(
            id="11",
       )

no error

```py
from sqlalchemy import *
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import *
Base = declarative_base()


class SimpleDocument(Base):
    __tablename__ = "simple_document"

    id = Column(String, primary_key=True)
    content = Column(String, nullable=False)
    checksum = Column(
        String, Computed("encode(digest(content, 'sha1'), 'hex')", persisted=True)
    )

    cmetadata = Column(JSON, nullable=True)


e = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

doc_c1 = [
        SimpleDocument(
            id="11",
            content="test",
            cmetadata={
                "simple_doc_id": 11,
                "company_id": "1",
                "rival_ids": [1],
                "supported_rival_ids": [1],
                "date": "2021-01-01",
                "private": False,
                "doc_type": "test",
            },
        ),
        SimpleDocument(
            id="12",
            content="test",
            cmetadata={
                "simple_doc_id": 12,
                "company_id": "1",
                "rival_ids": [2],
                "supported_rival_ids": [2],
                "date": "2022-01-01",
                "private": True,
                "doc_type": "not_test",
            },
        ),
    ]
doc_c2 = [
        SimpleDocument(
            id="21",
            content="test",
            cmetadata={
                "simple_doc_id": 21,
                "company_id": "2",
                "rival_ids": [3],
                "supported_rival_ids": [2],
                "date": "2022-01-01",
                "private": True,
                "doc_type": "not_test",
            },
        ),
    ]
doc_c3 = [
        SimpleDocument(
            id="31",
            content="test",
            cmetadata={
                "simple_doc_id": 31,
                "company_id": "3",
                "rival_ids": [4],
                "supported_rival_ids": [1],
                "date": "2022-01-01",
                "private": False,
                "doc_type": "test",
            },
        )
    ]

s.add_all(doc_c1 + doc_c2 + doc_c3)
s.commit()
```

**Comment by CaselIT** [comment] 2024-03-19 20:57
> Do you know if it's related, @CaselIT?

yes, the same issue, see mike post

**Comment by fernandocamargoai** [comment] 2024-03-19 21:00
> oh. no, not even that.
> 
> here is your bug:
> 
> ```
> id = Column(String, primary_key=True)
> ```
> 
> then your data:
> 
> ```
>     SimpleDocument(
>         id=11,
>   )
> ```
> 
> that is wrong, you said these were strings
> 
> "There may be a mismatch between the datatype passed to the DBAPI driver vs. that which it returns in a result row. Ensure the given Python value matches the expected result type _exactly_"
> 
> use strings if that's the datattype
> 
> ```
>     SimpleDocument(
>         id="11",
>    )
> ```
> 
> no error
> 
> ```python
> from sqlalchemy import *
> from sqlalchemy.ext.hybrid import hybrid_property
> from sqlalchemy.orm import *
> Base = declarative_base()
> 
> 
> class SimpleDocument(Base):
>     __tablename__ = "simple_document"
> 
>     id = Column(String, primary_key=True)
>     content = Column(String, nullable=False)
>     checksum = Column(
>         String, Computed("encode(digest(content, 'sha1'), 'hex')", persisted=True)
>     )
> 
>     cmetadata = Column(JSON, nullable=True)
> 
> 
> e = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')
> Base.metadata.drop_all(e)
> Base.metadata.create_all(e)
> 
> s = Session(e)
> 
> doc_c1 = [
>         SimpleDocument(
>             id="11",
>             content="test",
>             cmetadata={
>                 "simple_doc_id": 11,
>                 "company_id": "1",
>                 "rival_ids": [1],
>                 "supported_rival_ids": [1],
>                 "date": "2021-01-01",
>                 "private": False,
>                 "doc_type": "test",
>             },
>         ),
>         SimpleDocument(
>             id="12",
>             content="test",
>             cmetadata={
>                 "simple_doc_id": 12,
>                 "company_id": "1",
>                 "rival_ids": [2],
>                 "supported_rival_ids": [2],
>                 "date": "2022-01-01",
>                 "private": True,
>                 "doc_type": "not_test",
>             },
>         ),
>     ]
> doc_c2 = [
>         SimpleDocument(
>             id="21",
>             content="test",
>             cmetadata={
>                 "simple_doc_id": 21,
>                 "company_id": "2",
>                 "rival_ids": [3],
>                 "supported_rival_ids": [2],
>                 "date": "2022-01-01",
>                 "private": True,
>                 "doc_type": "not_test",
>             },
>         ),
>     ]
> doc_c3 = [
>         SimpleDocument(
>             id="31",
>             content="test",
>             cmetadata={
>                 "simple_doc_id": 31,
>                 "company_id": "3",
>                 "rival_ids": [4],
>                 "supported_rival_ids": [1],
>                 "date": "2022-01-01",
>                 "private": False,
>                 "doc_type": "test",
>             },
>         )
>     ]
> 
> s.add_all(doc_c1 + doc_c2 + doc_c3)
> s.commit()
> ```

Good catch, @zzzeek. It indeed solved the problem. I guess the datatype was changed at some point and the tests weren't updated. Thank you again.
