### ISSUE TITLE
render MySQL FROM DUAL if WHERE clause and no FROM present

### ISSUE THREAD

**Issue by aneesh-joseph** [sqlalchemy/sqlalchemy#5481] opened 2020-07-28 16:43 UTC
**Describe the bug**

A row exists check like :

https://github.com/apache/airflow/blob/1.10.11/airflow/models/dagcode.py#L163-L164

```
from sqlalchemy.sql import exists
session.query(exists().where(cls.fileloc_hash == fileloc_hash))\
            .scalar()
```
works against MySQL and Postgres but fails against Microsoft SQL server  as it doesn't support an exists expression in select clause and errors out with 

```
E       sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'EXISTS'. (156) (SQLExecDirectW)")
E       [SQL: SELECT EXISTS (SELECT * 
E       FROM dag_code 
E       WHERE dag_code.fileloc_hash = ?) AS anon_1]
E       [parameters: (58425611885652217,)]
E       (Background on this error at: http://sqlalche.me/e/13/f405)
```

changing this to 

```
from sqlalchemy.sql.expression import literal
        session.query(literal(True)).filter(
            session.query(cls).filter(cls.fileloc_hash == fileloc_hash).exists()
        ).scalar()
```

works on Postgres and Microsoft SQL Server  but fails on MySQL 

```
E           ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE EXISTS (SELECT 1 \nFROM dag_code \nWHERE dag_code.fileloc_hash = 27753634201' at line 2")
E           [SQL: SELECT %s AS param_1 
E           WHERE EXISTS (SELECT 1 
E           FROM dag_code 
E           WHERE dag_code.fileloc_hash = %s)]
E           [parameters: (1, 27753634201084933)]
E           (Background on this error at: http://sqlalche.me/e/13/f405)
```

**Expected behavior**

the same exists() check works correctly across dialects 

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example. 
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22)

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: 
 - Python:
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment] 2020-07-28 20:37
hey there.

there's no SQLAlchemy bug here because query(), select(), exists() and others do not try to guess the intent of what you are doing and have no choice but to faithfully reproduce the structure you give them.    

in this case, there is an unfortunate disconnect between syntaxes for MySQL and SQL Server.  SQL Server won't allow the EXISTS in a column expression, and MySQL, while it does support EXISTS in the WHERE clause, seems to get confused when there's not a FROM clause.

for structural issues like this, the only option is to either use a conditional based on the database you're using, or to use [@compiles](https://docs.sqlalchemy.org/en/13/core/compiler.html) to create a high-level SQL construct that expresses your desired intent, in this case, "return boolean true/false if this table has rows with a particular WHERE clause".

There is a way to get MySQL to work with the WHERE clause which is to use an explicit [DUAL](https://dev.mysql.com/doc/refman/8.0/en/select.html) table, even though MySQL claims they don't require this, they are wrong, this is a case where they do need it.   I would encourage this to be reported as a MySQL bug.  but anyway, we can create a "DUAL" element that works on all backends using the recipe below.    I would favor this recipe added to the examples folder and linked from https://docs.sqlalchemy.org/en/13/core/selectable.html?highlight=exists#sqlalchemy.sql.expression.exists .

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import exists
from sqlalchemy import Integer
from sqlalchemy import literal_column
from sqlalchemy import String
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.sql import quoted_name
from sqlalchemy.sql import TableClause


class Dual(TableClause):
    def __init__(self):
        super(Dual, self).__init__(quoted_name("dual", quote=False))


@compiles(Dual)
def _visit_dual(element, compiler, **kw):
    return "(SELECT 1) AS dual"


@compiles(Dual, "mysql")
@compiles(Dual, "oracle")
def _visit_dual(element, compiler, **kw):
    return compiler.visit_table(element, **kw)


@compiles(Dual, "postgresql")
def _visit_dual(element, compiler, **kw):
    return "(SELECT true) AS dual"


Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String(50))


e = create_engine("sqlite://", echo=True)
# e = create_engine("mysql://scott:tiger@localhost/test", echo=True)
# e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
# e = create_engine(
#    "mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server",
#    echo=True,
# )

Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([A(data="some data") for i in range(3)])
s.commit()

e = exists([A.id]).where(A.data == "some data")
print(s.query(literal_column("1")).select_from(Dual()).filter(e).scalar())

```

**Comment by zzzeek** [comment] 2020-07-28 20:40
it would likely not be too controversial for sqlalchemy.dual() to exist in any case for the rare circumstance where explicit "DUAL" is needed.   The Oracle dialect automatially renders DUAL for all SELECT statements that don't have a FROM clause.  Maybe the MySQL dialect should do this also but I think users would find it confusing in most cases.

**Comment by zzzeek** [comment] 2020-07-28 20:51
found a good way to check this, https://mariadb.com/kb/en/dual/ 

> FROM DUAL could be used when you only SELECT computed values, but require a WHERE clause, perhaps to test that a script correctly handles empty resultsets:

so we can do this based on heuristic.

**Comment by sqla-tester** [comment] 2020-07-28 21:00
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Consider default FROM DUAL for MySQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2113

**Comment by sqla-tester** [comment] 2020-07-28 21:06
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Consider default FROM DUAL for MySQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2114

**Closed** 2020-07-29 18:44 UTC
Labels: mysql, use case
