### ISSUE TITLE
Keep a reference to a task then using shield

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8516] opened 2022-09-13 11:22 UTC
Keep a reference to a group of tasks on the connection pool

eg:

```python
task = asyncio.create_task(conn.close())
pool._tasks.add(task)
task.add_done_callback(pool._tasks.discard)
await asyncio.shield(task)
```

Then your connection pool can wait for `self._tasks`

Even better is using an anyio TaskGroup in your pool
Even better still is making an upstream PR that makes sure the connection is always closed when asyncpg close terminates

_Originally posted by @graingert in https://github.com/sqlalchemy/sqlalchemy/issues/8145#issuecomment-1245051716_

**Comment by zzzeek** [comment] 2022-09-13 13:31
do we need shield anymore now that we have terminate()?  at least for asyncpg

also can we milestone this please

**Comment by CaselIT** [comment] 2022-09-13 13:42
>  at least for asyncpg

well iirc we use terminate only when the fairy is closing things down after the connection is out of scope. normal operations are still on the normal close.

also even if we move to always use terminate for asyncpg I don't think it makes sense to introduce logic to conditionally skip the shield depending on the dict.

**Comment by zzzeek** [comment] 2022-09-13 15:26
normal operations dont need shield because there's no CancelledError  .    I think if the block is cancelled, and close does not proceed, the connection will ultimately go back to the pool where we can terminate it.


> 
> also even if we move to always use terminate for asyncpg I don't think it makes sense to introduce logic to conditionally skip the shield depending on the dict.

I wouldn't do that either.   But based on the quality of the other async drivers I doubt any of them are being used in serious production environments.    That is, yes lets fix the structure here , but it doesnt matter much in practice at the moment.

**Comment by CaselIT** [comment] 2022-09-13 15:59
Yes, I think the most used will probably by asyncpg and psycopg.

In hindsight maybe we could have ported the support for it to 1.4

**Comment by sqla-tester** [comment] 2022-09-13 19:28
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improved usage of ``asyncio.shield()``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4076

**Comment by sqla-tester** [comment] 2022-09-13 19:29
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Improved usage of ``asyncio.shield()``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4077

**Comment by graingert** [comment] 2022-09-14 07:35
I think that's a good improvement but you should wait for the task somewhere rather than just keeping it in a hard reference set

**Comment by CaselIT** [comment] 2022-09-14 07:50
No, since conn can be anything and not all driver have a sync version of close. For example psycopg https://www.psycopg.org/psycopg3/docs/api/connections.html#the-asyncconnection-class

**Comment by zzzeek** [comment] 2022-09-14 12:55
> I think that's a good improvement but you should wait for the task somewhere (when you close the pool) rather than just keeping it in a hard reference set

the addition of shield() in the first place, as incorrect as it was, fixed the issue for the person who was having a problem.   then the addition of terminate() fixed that same problem a second time.    we are dealing with failure mode code here and if nothing is actually reproducible,    I would almost rather remove shield completely here as this looks like a lot of pointless complexity

**Comment by CaselIT** [comment] 2022-09-14 13:01
> I would almost rather remove shield completely here as this looks like a lot of pointless complexity

In that case wouldn't #8145 be broken again for all async drivers that are not asyncpg?

**Comment by zzzeek** [comment] 2022-09-14 13:02
put another way, here's the original code:

```py
 async def __aexit__(self, type_, value, traceback):
        await self.close()
```

here's the shield code:

```py
    async def __aexit__(self, type_, value, traceback):
        await asyncio.shield(self.close())
```

are we saying that the second example is **worse** than the first?   I'd rather revert at this point.    we were originally wondering why asyncpg etc. didnt have this shield code.

**Comment by zzzeek** [comment] 2022-09-14 13:04
> > I would almost rather remove shield completely here as this looks like a lot of pointless complexity
> 
> In that case wouldn't #8145 be broken again for all async drivers that are not asyncpg?

unlikely, because those drivers likely all allow the connections to be garbage collected, and as mentioned previously, they are not production-quality drivers anyway.   

I think we need reproducing examples of any of this stuff.     The shield() code we have has been released for several months now, no issues have been reported.  if the code is incorrect, then why?

**Comment by CaselIT** [comment] 2022-09-14 13:17
Since the local scope of the function is alive until the shield if done, I agree that we don't need the global object.
We would if we where to return the shielded task.

Will update the change

**Closed** 2022-09-15 20:19 UTC
Labels: orm, sql, asyncio

**Comment by sqla-tester** [comment] 2022-09-15 22:55
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**use get_event_loop() for python 3.6** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4082
