### ISSUE TITLE
dict(row) causing TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by lindycoder** [sqlalchemy/sqlalchemy#6218] opened 2021-04-07 15:47 UTC
*DISCLAIMER:  This is a very weird bug, I don't know if SQLAlchemy is the problem, but I couldn't reproduce without it, there is a very easy workaround, but I felt like i should report this as it may hide something else.*

**Describe the bug**
Using `dict()` on an `sqlalchemy.engine.Row` object is producing `TypeError: tuple indices must be integers or slices, not str`  in a very specific setup (see To Reproduce)

**Expected behavior**
`dict(row)` should return the row as a dict.

**To Reproduce**
This Dockerfile can show the error:
```
FROM python:3-alpine

RUN apk add --no-cache g++

RUN pip install --upgrade pip && pip install greenlet

RUN apk del g++

RUN pip install sqlalchemy

RUN echo $'\
from sqlalchemy import create_engine \n\
from sqlalchemy.orm import sessionmaker \n\
\n\
session = sessionmaker(bind=create_engine("sqlite://"))() \n\
result = session.execute("select 1, 2, 3").fetchall() \n\
row = result[0] \n\
\n\
print(dict(row)) \n\
' > script.py

RUN python script.py
``` 
 Inline code is
```py
from sqlalchemy import create_engine 
from sqlalchemy.orm import sessionmaker 

session = sessionmaker(bind=create_engine("sqlite://"))() 
result = session.execute("select 1, 2, 3").fetchall() 
row = result[0] 

print(dict(row))
```

**Error**

```
Traceback (most recent call last):
  File "//script.py", line 8, in <module>
    print(dict(row))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/row.py", line 104, in __getitem__
    return self._data[key]
TypeError: tuple indices must be integers or slices, not str
```

**Versions.**
 - OS: Alpine 3.13
 - Python: 3.9.4
 - SQLAlchemy: 1.4.6
 - Database: sqlite
 - DBAPI: ?

**Additional context**

The provided Dockerfile is a shrunk down version of what we use:
- A base image with build dependencies installing all libs requiring compilation (greenlet)
- A service image that install extra libs not requiring dependencies (sqlalchemy)

**I have noticed that REMOVING or MOVING the `RUN apk del g++` AFTER the installation of SQL Alchemy will solve the problem.**

I also tried to reproduce in debian, compiling libs instead of wheels. with this Dockerfile and could **not reproduce**, so maybe it's related to Alpine OR there's something else installed in slim-buster.

```
FROM python:3-slim-buster

RUN apt-get update && apt-get install -y g++

RUN pip install --upgrade pip && pip install greenlet --no-binary :all:

RUN apt-get remove -y g++

RUN pip install sqlalchemy --no-binary :all:

RUN echo '\
from sqlalchemy import create_engine \n\
from sqlalchemy.orm import sessionmaker \n\
\n\
session = sessionmaker(bind=create_engine("sqlite://"))() \n\
result = session.execute("select 1, 2, 3").fetchall() \n\
row = result[0] \n\
\n\
print(dict(row)) \n\
' > script.py

RUN python script.py
```

**WORKAROUND**
Using `row._asdict()` will solve the problem.

**Have a nice day!** and thank you for your amazing work.

**Comment by jvanasco** [comment] 2021-04-07 15:56
I haven't been able to recreate this either, this looks related to your environment. Maybe there is something in the compile args for Python in the image? Alpine images can often be odd, and are famous for being hard to debug.

**Comment by lindycoder** [comment] 2021-04-07 15:57
You cannot recreate with the alpine dockerfile?

**Comment by jvanasco** [comment] 2021-04-07 15:59
@lindycoder I can't recreate this on any other environment - ubuntu 18.04, ubuntu 16.04, osx.

**Comment by lindycoder** [comment] 2021-04-07 16:02
@jvanasco okay i understand

The fact that NOT removing g++ might be an indication of an installation thing.  Is SQL Alchemy doing things differently if a compiler is available?

**Comment by CaselIT** [comment] 2021-04-07 16:02
It may be a bug in the python version of the library.

Can you reproduce by installing it on debian (or other) with `DISABLE_SQLALCHEMY_CEXT=1 pip install --no-binary sqlalchemy`?

**Comment by zzzeek** [comment] 2021-04-07 16:04
we should also keep in mind that ``dict(row)`` is deprecated in any case.  you can work around this now by using ``row._mapping``.

**Comment by jvanasco** [comment] 2021-04-07 16:05
> Is SQL Alchemy doing things differently if a compiler is available? 

@lindycoder There are some c-extensions.

> Can you reproduce by installing it on debian (or other) with DISABLE_SQLALCHEMY_CEXT=1 pip install --no-binary sqlalchemy?

@CaselIT What about testing on alpine with g++ and disabling cext?

**Comment by lindycoder** [comment] 2021-04-07 16:16
> we should also keep in mind that `dict(row)` is deprecated in any case. you can work around this now by using `row._mapping`.

@zzzeek  We started using this a couple weeks ago when we upgraded to a recent version of SQLAlchemy and this stopped working `dict(row.items())`.

I could work around using row._asdict() which returns _mapping :)

If this is deprecated, what is the official way of translating a row to a dict?

**Comment by CaselIT** [comment] 2021-04-07 16:17
> @CaselIT What about testing on alpine with g++ and disabling cext?

alpine will download the source distribution, then if it finds the compile it will compile the c-extensions, if it does not find the compile no c-extension is compile. the evn variable `DISABLE_SQLALCHEMY_CEXT=1` disables compiling the c-extension even if the compiler is present

**Comment by CaselIT** [comment] 2021-04-07 16:20
> I could work around using row._asdict() which returns _mapping :)

`_asdict` is the official way. The idea is that in sa 1.4+ row behaves like a named tuple with the same underscore methods https://docs.python.org/3/library/collections.html#namedtuple-factory-function-for-tuples-with-named-fields

**Comment by lindycoder** [comment] 2021-04-07 16:20
@jvanasco @CaselIT 
I **CAN** reproduce on debian AND alpine with g++ installed with DISABLE_SQLALCHEMY_CEXT=1

**Alpine**
FROM python:3-alpine

RUN apk add --no-cache g++

RUN pip install --upgrade pip && pip install greenlet

RUN DISABLE_SQLALCHEMY_CEXT=1 pip install sqlalchemy

RUN echo $'\
from sqlalchemy import create_engine \n\
from sqlalchemy.orm import sessionmaker \n\
\n\
session = sessionmaker(bind=create_engine("sqlite://"))() \n\
result = session.execute("select 1, 2, 3").fetchall() \n\
row = result[0] \n\
\n\
print(dict(row)) \n\
' > script.py

RUN python script.py
```
**Debian**
```
FROM python:3-slim-buster

RUN apt-get update && apt-get install -y g++

RUN pip install --upgrade pip && pip install greenlet --no-binary :all:

RUN DISABLE_SQLALCHEMY_CEXT=1 pip install sqlalchemy --no-binary :all:

RUN echo '\
from sqlalchemy import create_engine \n\
from sqlalchemy.orm import sessionmaker \n\
\n\
session = sessionmaker(bind=create_engine("sqlite://"))() \n\
result = session.execute("select 1, 2, 3").fetchall() \n\
row = result[0] \n\
\n\
print(dict(row)) \n\
' > script.py

RUN python script.py
```

**Comment by zzzeek** [comment] 2021-04-07 16:21
> > we should also keep in mind that `dict(row)` is deprecated in any case. you can work around this now by using `row._mapping`.
> 
> @zzzeek We started using this a couple weeks ago when we upgraded to a recent version of SQLAlchemy and this stopped working `dict(row.items())`.
> 
> I could work around using row._asdict() which returns _mapping :)
> 
> If this is deprecated, what is the official way of translating a row to a dict?

_asdict() or _mapping

https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Row._mapping

**Comment by CaselIT** [comment] 2021-04-07 16:23
@zzzeek we seem to have a bug in the documentation. `_asdict` is documented in the code but is not in the docs https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=row#sqlalchemy.engine.Row

**Comment by CaselIT** [comment] 2021-04-07 16:26
@zzzeek the python implementation should match the c ones in this case right?

**Comment by zzzeek** [comment] 2021-04-07 16:27
> @zzzeek we seem to have a bug in the documentation. `_asdict` is documented in the code but is not in the docs https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=row#sqlalchemy.engine.Row

well it's part of namedtuple so...sure it should be a method that's doc'ed

**Comment by zzzeek** [comment] 2021-04-07 16:27
> @zzzeek the python implementation should match the c ones in this case right?

you mean the behavior?  sure

**Comment by lindycoder** [comment] 2021-04-07 16:35
So I see [documentation](https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Row.keys) says `.keys()` is deprecated, which seems to be what dict() is relying on, from what i can tell.

I'm okay with closing this issue, maybe that method could spit our warnings?

**Comment by zzzeek** [comment] 2021-04-07 16:57
`dict(row)` for the legacy row should work so we should figure out the source of the issue.  if C exts have a problem then this would not be the only problem

**Comment by CaselIT** [comment] 2021-04-07 16:58
The issue in in the python code. The c code is fine, python is not

**Comment by zzzeek** [comment] 2021-04-07 17:02
oh.    OK I saw all the "Cant reproduce" and assumed it was weirder than that.

reproduces right away w/ python code!
```

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

session = sessionmaker(bind=create_engine("sqlite://"))()
result = session.execute("select 1, 2, 3").fetchall()
row = result[0]
print(dict(row))
```

**Comment by zzzeek** [comment] 2021-04-07 17:12
oh ok.  OK.  sorry.  so what's happening here is that Session.execute() is returning the future version of `Result` in all cases.     this actually was changed on purpose as session.execute() was trying to be consistent with how ORM results are returned, but at the same time I don't know if that was a good idea.      it looks like I might not have documented this very well and also the C extensions have probably been covering this up, as they don't seem to be expressing the same limitations.

This is a hard one because if the given statement has ORM entities, you get the new style row back, and it's hard for people to tell between:

    result = session.execute(select(User))

    result = session.execute(select(user_table))

the idea is that if those two returned *different* kinds of Row objects that would really confuse people.   So maybe the Python version of row should still have a fallback here, seeing that the C one seems to.

**Comment by zzzeek** [comment] 2021-04-07 17:13
there's no 2.0 deprecation warning either.   this is pretty broken

**Comment by zzzeek** [comment] 2021-04-07 17:37
pretty broken, the C BaseRow uses BaseRow_subscript_mapping as the universal ``__getitem__`` , it is not distinguishing for some reason

**Comment by sqla-tester** [comment] 2021-04-07 17:58
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Fix LegacyRow/Row index access** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2721

**Comment by zzzeek** [comment] 2021-04-07 17:59
alright well i have somethign to work on for 1.4.7

**Closed** 2021-04-08 21:23 UTC
Labels: bug, engine, regression

**Comment by VijethKashyapTR** [comment] 2022-09-03 18:03
I am facing the exact issue today with 1.4.2 version. IN AWS environment sqlalchemy deployed in AWS **Lambda** itself works fine if I unpack the CursorResult like {**row}

```
query = f"SELECT * FROM mytable WHERE entity_guid IN {entity_guids}"
results = session.execute(query)
for result in results:
print(results)
final.append({**result})
return final
```

 But same thing fails if I deploy sqlaldhemy 1.4.2(same version) in **Layers** instead of Lambda directly. Is there any fix for this?

**Comment by CaselIT** [comment] 2022-09-03 18:50
> Is there any fix for this?

Have you tried updating sqlalchemy? 1.4.2 is quite old, and early versions of the 1.4 series had a few bugs that were fixed in later releases

**Comment by VijethKashyapTR** [comment] 2022-09-04 07:41
> > Is there any fix for this?
> 
> 
> 
> Have you tried updating sqlalchemy? 1.4.2 is quite old, and early versions of the 1.4 series had a few bugs that were fixed in later releases 

I'll try to update to 1.4.7 and retry, thank you!

**Comment by CaselIT** [comment] 2022-09-04 08:07
Any reason for not using the las version on the 1.4 sereis?

**Comment by jvanasco** [comment] 2022-09-04 18:06
For context on @CaselIT’s comment, 1.4.40 is the latest version in the 1.4 series.

**Comment by VijethKashyapTR** [comment] 2022-09-05 07:01
> Any reason for not using the las version on the 1.4 sereis?

Nothing particularly, will update it, thanks

**Comment by m00dawg** [comment] 2023-02-11 18:57
Old issue, I apologize, but I just encountered this in a very surprising way wherein I tried to deploy my app to my webserver and it broke in horrible ways due to this error on the 2.0 branch. Reverting to 1.4 fixes this but I'm not sure what the proper fix should be? Is there an example of changes that need to be done between 1.4 and 2.0?

**Comment by lelit** [comment] 2023-02-11 20:38
Maybe [_asdict()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Row._asdict) helps?

I'd suggest reading the excellent migration notes, and in particular the [Result](https://docs.sqlalchemy.org/en/20/changelog/migration_14.html#new-result-object) section. There you can find an [alternative](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.mappings) to the above.
