### ISSUE TITLE
memory leak with engine.core and numpy

### ISSUE THREAD

**Issue by robochat** [sqlalchemy/sqlalchemy#7875] opened 2022-03-30 18:20 UTC
### Describe the bug

I have a long running process that periodically requests data from a postgresql database and converts to the results to a numpy array for analysis. I see the process leaking memory on each coercion of the results to a numpy array.

In my real process after a couple of days it can be using 9 GB of RAM and after a week it crashes the server. The previous version (python2.7) uses less than 200MB even after running for weeks but that version used psycopg2 directly. I could go back to doing that but I wanted to use sqlalchemy across the codebase by default and I'd also like to understand why this isn't working properly.

While creating the test case, I found that the same issue occurs with a sqlite in memory database. I also saw the same issue on my laptop and my server (both using sqlalchemy v.1.4.32 and v1.4.23)

### To Reproduce

```python
import sqlalchemy as sql
import numpy as np
import time

dburl = 'sqlite://'
engine = sql.create_engine(dburl, echo=False)

meta = sql.MetaData()

tbl = sql.Table('test_table',meta,
            sql.Column('a',sql.Integer,primary_key=True),
            sql.Column('b',sql.Integer),
            )

meta.create_all(engine)

#fill table
with engine.connect() as conn:
    conn.execute(tbl.insert(),
                 [{'b': i} for i in range(200)]
                 )

#test

while True:
    with engine.connect() as conn:
        query = sql.text("SELECT a, b FROM test_table ORDER BY a LIMIT 200")
        results = conn.execute(query)
        rows = results.fetchall()
        data = np.array(rows)
        
        #fixes that didn't work
        del rows
        results.close()
        del data

        time.sleep(0.1)
```

### Error

Resident memory usage is up to 358MB in just a few minutes and there's no sign of stabilisation.
after a couple of minutes
```
PID    USER  PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                              
1952762 aaa  20   0  762204 186264  16188 S   5.7   0.9   0:09.77 python3
```
a bit later
```
PID    USER  PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
1952762 aaa  20   0  934200 358092  16188 S   5.6   1.8   0:21.20 python3                                                                                                                                                              
```

### Versions

- OS: Linux (CentOS)
- Python: 3.6.8
- SQLAlchemy: 1.4.32, 1.4.23
- Database: Postgresql (v12.9 64bit)
- DBAPI: psycopg2

**Comment by zzzeek** [comment] 2022-03-30 18:34
hi there -

memory holds completely steady for me when i run the test case.  additionally, if there is some leak it seems more likely this would be related to numpy. have you reported to them?  also what happens in your local reproduction case if you replace "data = np.array(rows)" with "data = rows" ?   is there any leak when you remove numpy from the script?    that would also indicate numpy as the source of the leak.

**Comment by zzzeek** [comment] 2022-03-30 18:43
OK, the issue can be reproduced if I compile with SQLAlchemy's C extensions.  Why numpy is having a problem is not clear.  What is clear is that if I consume the results first into a list of dictionaries, there's no problem, and of course if I dont use numpy, there's no problem.

so this still seems to be some issue in numpy and should still be reported to them.    As a workaround, convert to a list of dicts first:

```py
        rows = results.fetchall()
        data = [dict(r) for r in rows]
        data = np.array(data)
```

The C extensions in SQLAlchemy are replaced with cython code in 2.0 and the approach is entirely different.

**Comment by CaselIT** [comment] 2022-03-30 18:45
> The C extensions in SQLAlchemy are replaced with cython code in 2.0 and the approach is entirely different.

Does it reproduce also on v2 with cython?

**Comment by zzzeek** [comment] 2022-03-30 18:46
nope, cython is of course fine.

I dont know how we would diagnose this because if you've ever looked at numpy's source you'd...well....you'll see.  forget it

**Comment by zzzeek** [comment] 2022-03-30 18:54
it looks like numpy.array() is calling iter() and len() on each row.  but if i make a program that calls these methods without using a numpy array, there's no leak.

**Comment by zzzeek** [comment] 2022-03-30 18:59
yeah im not finding any method that inherently leaks and this seems like something numpy is doing, it's extremely weird about datatypes.    just convert to dict/ tuple first, i.e. `data = np.array([tuple(x) for x in rows])` or `data = np.array([dict(x) for x in rows])`

**Comment by zzzeek** [comment] 2022-03-30 19:06
reproduces in SQLAlchemy 1.3 also.  so this is old stuff

**Comment by zzzeek** [comment] 2022-03-30 19:08
here's a little bit on numpy: https://numpy.org/devdocs/reference/c-api/data_memory.html#configurable-memory-routines-in-numpy-nep-49   they have a very elaborate C / memory implementation that's all custom.    it would appear to be incompatible with our C extensions.

**Comment by CaselIT** [comment] 2022-03-30 19:11
I leaning on wontfix, since this is no longer relevant for v2 and it seems to be more on numpy side that on sqlalchemy

**Comment by zzzeek** [comment] 2022-03-30 19:19
frustrating because im sure there's some silly thing that would tell numpy to treat our objects differently, since cython is able to do it

**Comment by CaselIT** [comment] 2022-03-30 19:20
I don't know anyone on the numpy team that could help. Maybe ask for help on twitter?

**Comment by zzzeek** [comment] 2022-03-30 20:55
im not too optimistic about getting any help from numpy, i dont even know who maintains it

**Comment by robochat** [comment] 2022-03-30 20:58
Thank you for the rapid response and for the workaround which does fix my issue. I will post my issue to numpy's github and see what they say.

**Comment by vytas7** [comment] 2022-03-30 21:01
Maybe @njsmith can provide insights on `numpy`

**Comment by robochat** [comment] 2022-03-30 21:13
Well, @zzzeek couldn't reproduce the memory leak when using SQLALchemy withouth the C extensions.

**Comment by CaselIT** [comment] 2022-03-30 21:14
> So, does this happen only when instantiating an ndarray from a SQLAlchemy extension data type written in C?

yes, v2 replaced it with cython, and that does not seem to have an issue. same if the python only version is used.
for reference the c-code of the row is here https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4/lib/sqlalchemy/cextension/resultproxy.c

**Comment by vytas7** [comment] 2022-03-30 21:29
Could it be that you "untrack" it from cyclic reference detection: https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4/lib/sqlalchemy/cextension/resultproxy.c#L275, as well as implement a custom traverse, which should work if all of `->parent`, `->row`, `->keymap` go out of scope when you `DECREF` them in the destructor, but if anything is holding a reference to them, they won't, and they wouldn't be any longer discoverable either?

And somehow `ndarray` manages to grab a reference while other stuff doesn't... or it's getting too late here and I'm just misunderstanding how it works :zzz:

**Comment by zzzeek** [comment] 2022-03-30 22:15
sounds like you know way more than me, once we did the cython stuff i was like hooray, no more C code.    the Row stuff is very old, I've updated it but not changed the basic form.   I have fixed lots of refcounting issues over the years but for this one I'd need to see it happen in isolation.

**Comment by seberg** [comment] 2022-03-30 22:47
Just to note (coming from NumPy), I am very sure that the issue is leaking the error message string when you do:

```
rows[0].__array__
```
(and similar).  NumPy will try such attributes and clear the error.  The C-code needs to DECREF the string.  Although, using `PyErr_Format` is probably more convenient than getting the reference count right manually.

**Comment by vytas7** [comment] 2022-03-31 07:21
> sounds like you know way more than me, once we did the cython stuff i was like hooray, no more C code.

Not sure about knowing more, I guessed it wrong after all. In any case I wholeheartedly agree that people should just write Cython instead of wrangling those `DECREF`s & `INCREF`s manually :smiling_imp:

**Comment by zzzeek** [comment] 2022-04-22 14:19
we of course welcome PRs that can fix this for 1.4, please reopen if someone has one, but otherwise we will just proceed to 2.0 which fixes this.

**Comment by zzzeek** [comment] 2022-04-22 14:22
> Just to note (coming from NumPy), I am very sure that the issue is leaking the error message string when you do:
> 
> ```
> rows[0].__array__
> ```
> 
> (and similar). NumPy will try such attributes and clear the error. The C-code needs to DECREF the string. Although, using `PyErr_Format` is probably more convenient than getting the reference count right manually.
> 
> EDIT: OK, You are already using `Formt`, so I change my suggestion to using `%S` and removing the unnecessary call to `PyUnicode_AsASCIIString(name);`. So what is leaked, seems just that `bytes` version of the name, you can also just `DECREF` that after formatting the error.

oh, this is a suggestion to fix. will try now

**Comment by zzzeek** [comment] 2022-04-22 14:24
that was the bug.  Thanks numpy developer @seberg !

**Comment by sqla-tester** [comment] 2022-04-22 14:31
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**fix memory leak in resultproxy.c** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3807

**Comment by zzzeek** [comment] 2022-04-25 22:06
the commit referenced this issue as "Fixes:" and it didn't close.  not sure why

**Closed by zzzeek** 2022-04-25 22:06 UTC
Labels: cextensions, next release

**Comment by CaselIT** [comment] 2022-04-25 22:33
It's not it main (since there was no bug there), so the issue will not be closed automatically
