### ISSUE TITLE
Session and SessionTransaction ref cycle

### ISSUE THREAD

**Issue by carsonip** [sqlalchemy/sqlalchemy#5074] opened 2020-01-02 10:05 UTC
SQLAlchemy version: 1.3

objgraph:
![sessiontransaction](https://user-images.githubusercontent.com/9133397/71661583-ac238580-2d89-11ea-8e6b-dfeaab1e4596.png)

MCVE in CycleTest:
```
diff --git a/test/aaa_profiling/test_memusage.py b/test/aaa_profiling/test_memusage.py
index be825151d..8867f8447 100644
--- a/test/aaa_profiling/test_memusage.py
+++ b/test/aaa_profiling/test_memusage.py
@@ -1396,3 +1396,14 @@ class CycleTest(_fixtures.FixtureTest):
             visit_binary_product(visit, expr)
 
         go()
+
+    def test_session_transaction(self):
+        User, Address = self.classes("User", "Address")
+        configure_mappers()
+
+        @assert_cycles()
+        def go():
+            s = Session()
+            s.query(User).exists()
+
+        go()

```

Session creates SessionTransaction which has a ref to Session.

This ref cycle is particularly problematic because gc spills weakref WeakValueDictionary.remove all over the call stacks randomly. The WeakValueDictionary is created in `orm.session`
```
_sessions = weakref.WeakValueDictionary()
```

I have no idea how to fix this yet, but this issue is quite critical in my opinion. Thanks!

**Comment by carsonip** [comment] 2020-01-02 14:36
A new SessionTransaction is started when Session.close() is called: (orm/session.py:595)
```
        if self._parent is None:
            if not self.session.autocommit:
                self.session.begin()
```

Although the old SessionTransaction.session = None (orm/session.py:598), a new cycle is created again.

If we are not fixing this, do we have a way to avoid this cycle in application code?

**Comment by zzzeek** [comment] 2020-01-02 15:40
I see that you mentioned the issue of weakref.refs being cleaned previously but I'm not understanding the problem right now.  are you suggesting that WeakValueDictionary simply should not be used because the simple fact that weakrefs point to things that are removed is a performance issue ?   can you show the reproduction case ?

**Comment by zzzeek** [comment] 2020-01-02 15:40
trying the test now.

**Comment by carsonip** [comment] 2020-01-02 15:45
> I see that you mentioned the issue of weakref.refs being cleaned previously but I'm not understanding the problem right now. are you suggesting that WeakValueDictionary simply should not be used because the simple fact that weakrefs point to things that are removed is a performance issue ? can you show the reproduction case ?

They are designed to be cleaned. There is no performance problem. The problem I am facing is that they are not being cleaned when Session is closed, but only during gc because Session has a ref cycle. And due to the fact that gc may happen any time (especially when many objects are allocated), it messes up the call stack, showing random WeakValueDictionary.remove at the top of any call stacks.

**Comment by zzzeek** [comment] 2020-01-02 15:45
here's the fix:
```

diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index 3c58b4260..b23fca57a 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -1317,6 +1317,8 @@ class Session(_SessionClassMethods):
             for transaction in self.transaction._iterate_self_and_parents():
                 transaction.close(invalidate)
 
+        self.transaction = None  # remove cycles
+
     def expunge_all(self):
         """Remove all object instances from this ``Session``.
 

```

and here's the test:

```
    def test_session_transaction(self):
        @assert_cycles()
        def go():
            s = Session()
            s.close()

        go()

```

is there a reason s.close() would not be called on a Session before it is to be discarded?

**Comment by carsonip** [comment] 2020-01-02 15:47
> here's the fix:
> 
> ```
> 
> diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
> index 3c58b4260..b23fca57a 100644
> --- a/lib/sqlalchemy/orm/session.py
> +++ b/lib/sqlalchemy/orm/session.py
> @@ -1317,6 +1317,8 @@ class Session(_SessionClassMethods):
>              for transaction in self.transaction._iterate_self_and_parents():
>                  transaction.close(invalidate)
>  
> +        self.transaction = None  # remove cycles
> +
>      def expunge_all(self):
>          """Remove all object instances from this ``Session``.
>  
> ```
> 
> and here's the test:
> 
> ```
>     def test_session_transaction(self):
>         @assert_cycles()
>         def go():
>             s = Session()
>             s.close()
> 
>         go()
> ```
> 
> is there a reason s.close() would not be called on a Session before it is to be discarded?

I do call s.close() in finally, so there is no problem. But I have tried to do self.transaction = None. It fails some tests in the sqlalchemy test suite.

**Comment by zzzeek** [comment] 2020-01-02 15:55
oh ok, if the new transaction replaced itself then that would happen, let's see

**Comment by carsonip** [comment] 2020-01-02 15:58
`self.transaction = None` would fix this issue and I feel like it is the right fix. But I just don't have enough understanding to fix the tests. :(
Not sure if there are better fixes.

**Comment by zzzeek** [comment] 2020-01-02 16:06
Ok right there's the "autobegin" thing that has to be adjusted here.

**Comment by zzzeek** [comment] 2020-01-02 16:16
I can adjust this but I don't think it's appropriate for 1.3 because it is a change in documented behavior.   "If this session were created with ``autocommit=False``, a new   transaction is immediately begun."  that has to change

**Comment by zzzeek** [comment] 2020-01-02 16:17
so in your application, make your own:

```
def close_session(sess):
   sess.close()
   sess.transaction = None

```
in 1.4 you won't need the above but it will also be harmless

**Comment by carsonip** [comment] 2020-01-02 16:25
Looks good. That's reasonable. Thanks!

**Comment by zzzeek** [comment] 2020-01-02 16:32
OK since I'm doing that lets see if i should make "autobegin" entirely in this new place, e.g. when connection first needed.    it is always better to do something just one way rather than two ways.

**Comment by zzzeek** [comment] 2020-01-02 17:44
not at all surprisingly this is doable but WAY more complicated to go all the way with it, but if we don't go all the way it will have bugs (that is, the Session needs to behave identically after a .close() as before a .close(), so there shouldn't be a .close()-specific state).   Also, this change was coming anyway as part of #4646 where we are going to add an explicit "autobegin" state.

**Comment by sqla-tester** [comment] 2020-01-02 17:53
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement explicit autobegin step for Session** https://gerrit.sqlalchemy.org/1650

**Comment by carsonip** [comment] 2020-01-03 03:59
> so in your application, make your own:
> 
> ```
> def close_session(sess):
>    sess.close()
>    sess.transaction = None
> ```
> 
> in 1.4 you won't need the above but it will also be harmless

I can confirm that adding the `s.transaction = None` breaks the ref cycle and gets rid of (most of) the random `weakref.remove` in call stacks that shows up in my profiling tools. e.g. `weakref.remove` that shows up in func calls that don't use weakref are now gone.

**Comment by carsonip** [comment] 2020-01-03 04:13
That said, it is not completely eliminated. Just that `weakref.remove` took 80% time of a function call that does not use weakref and now it takes ~20%. In some cases it goes from 20% to <5%. Usually functions that allocate many objects are affected. I'll keep digging.

**Comment by zzzeek** [comment] 2020-01-03 16:17
> That said, it is not completely eliminated. Just that `weakref.remove` took 80% time of a function call that does not use weakref and now it takes ~20%. In some cases it goes from 20% to <5%. Usually functions that allocate many objects are affected. I'll keep digging.

can you share a cProfile file for that ?

**Comment by carsonip** [comment] 2020-01-03 16:24
> can you share a cProfile file for that ?

I forgot to note that I found another bug, this time in my own application, that does the same thing. The `weakref.remove` is quite insignificant at the moment. I'll let you know if I find anything that is related to SQLAlchemy. This issue can be closed if the fix for master is merged.

**Closed** 2020-01-03 22:38 UTC
Labels: bug, orm, performance
