### ISSUE TITLE
using SQLAlchemy produces a warning in engine/default.py regarding select() use

### ISSUE THREAD

**Issue by eukreign** [sqlalchemy/sqlalchemy#5295] opened 2020-04-30 19:06 UTC
**Describe the bug**
Using SQLAlchemy produces a warning in `engine/default.py` regarding `select()`.

**Expected behavior**
SQLAlchemy should be internally consistent and not produce warnings on itself.

**To Reproduce**
```py
Python 3.7.5 (default, Oct 15 2019, 21:38:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import warnings
>>> warnings.simplefilter("default")
>>> from sqlalchemy import create_engine
>>> create_engine('sqlite:///:memory:').connect()
sqlalchemy/lib/sqlalchemy/engine/default.py:382: RemovedIn20Warning: The select() function in SQLAlchemy 2.0 will accept a series of columns / tables and other entities only, passed positionally. For forwards compatibility, use the sqlalchemy.future.select() construct. (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  expression.select([test]).compile(dialect=self)
```

**Error**
```
sqlalchemy/lib/sqlalchemy/engine/default.py:382: RemovedIn20Warning: The select() function in SQLAlchemy 2.0 will accept a series of columns / tables and other entities only, passed positionally. For forwards compatibility, use the sqlalchemy.future.select() construct. (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  expression.select([test]).compile(dialect=self)
```

**Versions.**
 - OS: Ubuntu
 - Python: Python 3.7
 - SQLAlchemy: master
 - Database: SQLite
 - DBAPI:

**Comment by CaselIT** [comment] 2020-04-30 19:34
This is probably not the only warning of this type in the current state of master, so I'm not sure if it makes sense to just fix this one.

Is there a particular reason that makes you use master, instead of the 1.3.x series?

**Comment by CaselIT** [comment] 2020-04-30 19:37
Please note that you can ignore them using `warnings.filterwarnings("ignore", category=sa_exc.RemovedIn20Warning)`

**Comment by zzzeek** [comment] 2020-04-30 19:46
we have #5284 for this right now, I dont think internals should have to use future.select() explicitly, just the new calling style is best.  there are a lot of internals in reflection etc. that use select().

**Comment by zzzeek** [comment] 2020-05-02 16:23
this is a dupe of 5284.

**Closed by zzzeek** 2020-05-02 16:23 UTC
Labels: awaiting info, question, use case
