### ISSUE TITLE
bulk_save_objects() w/ return defaults writes incorrect identity key

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11332] opened 2024-04-29 12:18 UTC
```py
from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy import inspect
from sqlalchemy import String
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str] =  mapped_column(String(10))


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

a1a, a2 = A(data='d1'), A(data='d2')
s.bulk_save_objects([a1a, a2], return_defaults=True)
s.commit()

a1b = s.get(A, 1)

assert inspect(a1a).key == inspect(a1b).key

```

**Comment by zzzeek** [comment] 2024-04-29 14:04
i added comments on the gerrit, we do those and it will show up here

**Comment by sqla-tester** [comment] 2024-04-29 19:58
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix issue in bulk_save_objects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5284

**Comment by sqla-tester** [comment] 2024-04-29 19:58
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix issue in bulk_save_objects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5285

**Closed** 2024-04-30 16:15 UTC
Labels: bug, orm, near-term release

**Comment by rubinghv** [comment] 2024-05-30 11:21
I recently had a regression where `bulk_save_objects()` was no longer able to handle adding two linked ORM objects. I.e. College object which has a relationship with Students. Previously when I added a bunch of College objects, each of which contained the students parameter which was a list of Student objects, no issues occurred and it added both successfully to respective tables linked by a foreign key. Now with nothing changing on my end, it only adds the College(s) and produces no error. I checked and changing nothing, it does work correctly with session.add(). 

Is there any chance that could be caused by this fix? It's the only change I could easily find that might explain the difference in behavior. Could this be because of changed defaults?

If not I don't think this is necessarily worth debugging further, just wanted to check

**Comment by CaselIT** [comment] 2024-05-30 11:37
This looks unlikely, since no behaviour has changed here, it's only a bug fix.

Do you know what version of sqlalchemy worked?

**Comment by rubinghv** [comment] 2024-05-30 16:40
I'll try to make some time next few days to make you a minimal example and see if I can reproduce

**Comment by CaselIT** [comment] 2024-05-30 17:37
My question was mainly if you had an sqlalchemy version that worked and one that didn't, to help pinpoint the possible change.

But if you can create an example then great (create a new issue with it though so it's better tracked)
