### ISSUE TITLE
engine object - wrong password and host for CONNECTION_STRING

### ISSUE THREAD

**Issue by bjornamr** [sqlalchemy/sqlalchemy#6911] opened 2021-08-20 09:05 UTC
### Describe the bug

When connecting to the database, we use a connection string. What happens is when using an at ("@") inside the password, the db_engine object gets wrong password and host. This worked on the sqlalchemy version 1.4.9

Going into debug-mode and looking at the db_engine object below, I can see that the password has been split on the first at sign ("@"). What should actually happen is not splitting the password, but splitting on the last at sign in the string before the connection string.

TLDR:
- First part of password with @ is used as password. 
- Second part of password after @ is then part of the host string.

![image](https://user-images.githubusercontent.com/6339551/130208354-246d6829-fc15-4bac-b5b8-0e3d06886c56.png)

@bjornamr and  @falkon353

### To Reproduce

```python
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine, Column, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

CONNECTION_STRING = "mssql+pymssql://username:firstpartpass@lastpartpass@localhost:1433/dev"

class User(Base):
    __tablename__ = "user"

    ssid = Column(String(256), primary_key=True, index=True)
    Name = Column(String(256))


db_engine = create_engine(CONNECTION_STRING)
db_session = sessionmaker(bind=db_engine)
Base.metadata.create_all(bind=db_engine)
```

### Error

Exception has occurred: OperationalError
(pymssql._pymssql.OperationalError) (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (YARge@CHN-CL-DEVSQL.MCHP-MAIN.COM)\n')
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

The above exception was the direct cause of the following exception:

  File "password_error.py", line 19, in <module>
    Base.metadata.create_all(bind=db_engine)

### Versions

- OS: Windows 10
- Python: 3.8
- SQLAlchemy: 1.4.22 
- Database: MS SQL 2019
- DBAPI: pymssql version: 2.2.1

**Comment by CaselIT** [comment] 2021-08-20 09:18
Hi,

This is a duplicate of #6574, #6567, #6568, #6688

This is the expected behaviour. See #6568 (comment)

**Closed by CaselIT** 2021-08-20 09:18 UTC
Labels: requires triage
