### ISSUE TITLE
literal compile in 1.3.16+

### ISSUE THREAD

**Issue by hyperknot** [sqlalchemy/sqlalchemy#5859] opened 2021-01-23 01:05 UTC
Before 1.3.16 I've used the following helper classes instead of the native versions, to allow me to look at the queries for development purposes: (PGDate and PGTime were identical)

```
import sqlalchemy as sa

class PGDateTime(sa.TypeDecorator):
    impl = sa.DateTime

    def process_literal_param(self, value, dialect):
        return f"'{value}'"
```

In my understanding of 1.3.16 ([changelog](https://docs.sqlalchemy.org/en/14/changelog/changelog_13.html#change-d388c44ba6f010e81ba29941ce191863)) and issue: https://github.com/sqlalchemy/sqlalchemy/issues/5052, they mean I could remove these classes from everywhere and do a search & replace to use native SQLAlchemy versions. 

I've run the search & replace on the codebase and it seems everything is working, however one test is failing. This is the snippet for it.

```
table = sa.Table(
    'testing_table',
    sa.MetaData(),
    sa.Column('datetime_col', sa.DateTime),
)

time_only = table.c.datetime_col.cast(sa.Time)

filters = [
    time_only >= sa.cast('03:00', sa.Time)
]  # NotImplementedError: Don't know how to literal-quote value '03:00'

filters = [time_only >= '03:00']  # works

compiled = str(
    sa.and_(*filters).compile(dialect=sapg.dialect(), compile_kwargs={"literal_binds": True})
)

print(compiled)
```

This test was using `sa.cast` before, and now it only works without that cast.

Is this as expected? Am I doing anything wrong if I remove that cast in 1.3.16+?

**Comment by zzzeek** [comment] 2021-01-23 01:25
hey there -

the compiler in #5052 seems to only apply to the default "string" compiler, not the PostgreSQL compiler (looks like the changelog says as much).   So if you send the PostgreSQL compiler a value that you say is a Time datatype, which is what the cast() is doing there, then you get a compile error if you use the PG compiler, and you get `CAST(testing_table.datetime_col AS TIME) >= CAST('03:00' AS TIME)` if you don't specify a compiler.

the version without using cast() is not actually telling it that "03:00" is a time type, it's in fact a string so it just does the stringify.

you can add another level to keep this as a string like this:

```
    time_only >= sa.cast(sa.literal('03:00'), sa.Time)

    CAST(testing_table.datetime_col AS TIME WITHOUT TIME ZONE) >= CAST('03:00' AS TIME WITHOUT TIME ZONE)
```

**Comment by hyperknot** [comment] 2021-01-23 22:25
Thanks, with `sa.literal` it works perfectly.

> The compiler in #5052 seems to only apply to the default "string" compiler, not the PostgreSQL compiler

I see, so this basically mean that I need to revert the whole change and keep using my previous custom types.

I did a bit of testing: in <1.3.16 both the standard compiler and the PG compiler gave a `Don't know how to literal-quote value datetime....` exception. In 1.3.16+ only the PG compiler gives this exception, the standard one does not.

But I might be missing the point of #5052 then. What is the point of using the standard compiler for debugging? Who uses it?

**Comment by zzzeek** [comment] 2021-01-23 23:18
> Thanks, with `sa.literal` it works perfectly.
> 
> > The compiler in #5052 seems to only apply to the default "string" compiler, not the PostgreSQL compiler
> 
> I see, so this basically mean that I need to revert the whole change and keep using my previous custom types.

if you are compiling with the PostgreSQL compiler then yes since we made an explicit choice to not implement literal representations for all datatypes on all backends, although in #5052 I seem to be finding it more work that everyone keeps asking for it vs. having to maintain it.


> 
> I did a bit of testing: in <1.3.16 both the standard compiler and the PG compiler gave a `Don't know how to literal-quote value datetime....` exception. In 1.3.16+ only the PG compiler gives this exception, the standard one does not.
> 
> But I might be missing the point of #5052 then. What is the point of using the standard compiler for debugging? Who uses it?

it looks like #5052 is still opened and seeks to cover more backends.

**Comment by hyperknot** [comment] 2021-01-23 23:33
I don't know about other user's use-cases, but wouldn't 98% of the users be covered if DateTime, Date and Time would be covered? A quick Google search is telling me that it's mostly the 3 dates which most people encounter.

Which I think is quite logical: as types get more advanced, they are always DB specific like like JSONB, ARRAY, etc. which is already covered.

**Comment by zzzeek** [comment] 2021-01-24 01:30
again, the issue is still opened.   care to work on a PR ?

**Comment by hyperknot** [comment] 2021-01-24 15:32
Did the core of the fix here: https://github.com/sqlalchemy/sqlalchemy/pull/5869

If it's good I'll add the tests but it's not trivial how to modify the existing one.

**Comment by zzzeek** [comment] 2021-02-03 23:25
the work here is issue #5052 , closing this.

**Closed by zzzeek** 2021-02-03 23:25 UTC
Labels: question
