### ISSUE TITLE
asyncpg connections not returned to pool if task is cancelled

### ISSUE THREAD

**Issue by gboor** [sqlalchemy/sqlalchemy#6652] opened 2021-06-18 09:41 UTC
**Describe the bug**
Using postgresql+asyncpg, I noticed a web app eventually runs out of connections and crashes. It turns out asyncpg connections are not returned to the pool when a task is cancelled.

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```pyimport logging
import asyncio

from asyncio import current_task

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker


engine = create_async_engine('postgresql+asyncpg://your/db', pool_timeout=30, pool_recycle=1800,
                             pool_size=20, max_overflow=-1, future=True)
async_session_factory = sessionmaker(engine, class_=AsyncSession)

logging.basicConfig(level=logging.INFO)
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)
logging.getLogger('sqlalchemy.pool').setLevel(logging.DEBUG)


async def get_and_return():
    async with AsyncSession(engine) as session:
        await session.execute('SELECT 1')


async def get_and_cancel():
    async with AsyncSession(engine) as session:
        await session.execute('SELECT 1')
        current_task().cancel()


async def main():
    for x in range(20):
        try:
            await get_and_return()
            logging.info(engine.pool.status())
            await get_and_cancel()
            logging.info(engine.pool.status())
        except asyncio.exceptions.CancelledError:
            pass


asyncio.run(main())
```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

Correct behaviour from `get_and_return`
```
DEBUG:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:Created new connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001815DF55DC0>
INFO:sqlalchemy.engine.Engine:select version()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:select current_schema()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:show standard_conforming_strings
INFO:sqlalchemy.engine.Engine:[raw sql] ()
DEBUG:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001815DF55DC0> checked out from pool
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT 1
INFO:sqlalchemy.engine.Engine:[generated in 0.00011s] ()
INFO:sqlalchemy.engine.Engine:ROLLBACK
DEBUG:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001815DF55DC0> being returned to pool
DEBUG:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001815DF55DC0> rollback-on-return
INFO:root:Pool size: 20  Connections in pool: 1 Current Overflow: -19 Current Checked out connections: 0
```

Incorrect behaviour from `get_and_cancel`
```
DEBUG:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:Connection <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_connection object at 0x000001815DF55DC0> checked out from pool
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT 1
INFO:sqlalchemy.engine.Engine:[cached since 0.0375s ago] ()
INFO:sqlalchemy.engine.Engine:ROLLBACK
...
INFO:root:Pool size: 20  Connections in pool: 1 Current Overflow: -18 Current Checked out connections: 1
```

As you can see, the ROLLBACK triggers, but the connection is not returned to the pool and 1 connection remains checked out. After running the full loop of 20 tries, 20 connections are checked out and not doing anything.

**Versions.**
 - OS: Windows 10, also tested in Alpine container
 - Python: 3.9.2
 - SQLAlchemy: 1.4.18
 - Database: Postgres 11
 - DBAPI: asyncpg 0.21.0

**Comment by zzzeek** [comment] 2021-06-18 13:00
hi there  -

I'm not deeply familiar with the real world scenarios by which CancelledError occurs but the conditions being created here also occur if you use the NullPool, which does not pool any connection:

```python
from sqlalchemy.pool import NullPool


engine = create_async_engine(
    "postgresql+asyncpg://scott:tiger@localhost/test",
    future=True,
    poolclass=NullPool,
)
```

that pool class is literally just connect() / close().   so I don't know what options we have here if the task is completely cancelled and GC does not seem to be closing out connections.

The asyncpg connections here are no longer referenced in any way that SQLAlchemy has access to, and they should be garbage collected.  Some initial attempts to trace out exactly what happens in this test case seem to indicate there's no point at which SQLAlchemy could intercept these connections to .close() them, we have a garbage collection hook on them and even that is not getting called.

I have a feeling you could make this program with asyncpg directly pretty easily and im not sure why asyncpg doesn't close out connections that should be garbage collected.     their docs give no guidance: https://magicstack.github.io/asyncpg/current/search.html?q=cancellederror&check_keywords=yes&area=default

**Comment by zzzeek** [comment] 2021-06-18 13:14
so far, wihtin the "finally:" of the block, the asyncpg connection itself can be "closed", which seems to let asyncpg let go of it, but we still are not given any opportunity to do any pool cleanup.   this happens in a plain vanilla asyncio program as well

```python
import asyncio
from asyncio import current_task

from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import NullPool


engine = create_async_engine(
    "postgresql+asyncpg://scott:tiger@localhost/test",
    future=True,
    poolclass=NullPool,
)

async def get_and_cancel():
    conn = await engine.connect()
    try:
        await conn.exec_driver_sql("SELECT 1")
        current_task().cancel()
    finally:

        print("we can close the asyncpg connection directly")
        asyncpg_conn = (await conn.get_raw_connection()).connection._connection
        print("and we get here, and we can close it out")
        await asyncpg_conn.close()

        print("but we dont get here, which is where the above is supposed to happen")
        await conn.close()

async def main():
    while True:
        try:
            await get_and_cancel()
        except asyncio.exceptions.CancelledError:
            pass


asyncio.run(main())
```


plain demo:

```python
import asyncio

from asyncio import current_task
import asyncpg


async def get_and_cancel():
    conn = await asyncpg.connect(user="scott", password="tiger", host="localhost", database="test")
    try:
        result = await conn.fetch("SELECT 1")
        current_task().cancel()
    finally:
        # we get here, and this seems to change the state of asyncpg
        # so that the error is not raised
        await conn.close()

        # but we never get here
        import pdb
        pdb.set_trace()


async def main():
    while True:
        try:
            await get_and_cancel()
        except asyncio.exceptions.CancelledError:
            pass


asyncio.run(main())
```

**Comment by zzzeek** [comment] 2021-06-18 13:19
related issue but this was fixed: https://github.com/MagicStack/asyncpg/issues/464

**Comment by zzzeek** [comment] 2021-06-18 13:25
here we are, this also throws the error, using asycnpg only, we are closing the connection, but because we have to emit a ROLLBACK (or do anything with an await whatsoever), we are blocked:

```python
import asyncio

from asyncio import current_task
import asyncpg


async def get_and_cancel():
    conn = await asyncpg.connect(
        user="scott", password="tiger", host="localhost", database="test"
    )
    try:
        result = await conn.fetch("SELECT 1")
        current_task().cancel()
    finally:
        await conn.fetch("ROLLBACK")
        await conn.close()


async def main():
    while True:
        try:
            await get_and_cancel()
        except asyncio.exceptions.CancelledError:
            pass


asyncio.run(main())
```

**Comment by zzzeek** [comment] 2021-06-18 13:36
i've added #772 as a demo and maybe they can tell us what we should do in this kind of case.

**Comment by sqla-tester** [comment] 2021-06-18 21:44
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**ensure greenlet_spawn propagates BaseException** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2876

**Comment by zzzeek** [comment] 2021-06-18 21:46
figured out that the greenlet spawn was not allowing us to handle BaseException fully.    This issue still has things I don't understand very well (why the asyncpg connections are not garbage collected, why it is so hard to get cancel() to do something predictable in a unit test) but this seems to be what's needed to make sure our invalidation code handles invalidating the connection.

**Closed** 2021-06-19 04:11 UTC
Labels: bug, connection pool, external driver issues

**Comment by zzzeek** [comment] 2021-06-21 19:28
hey @gboor trying to gauge impact here what is the scenario under which your web application experiences "cancel"?  What web framework / app server / etc are you using ?

**Comment by gboor** [comment] 2021-06-22 06:48
@zzzeek I use it with aiohttp to serve a very simple REST API. aiohttp cancels the task if the client disconnects for whatever reason... so it doesn't happen often, but it does happen.

**Comment by zzzeek** [comment] 2021-06-22 12:49
> @zzzeek I use it with aiohttp to serve a very simple REST API. aiohttp cancels the task if the client disconnects for whatever reason... so it doesn't happen often, but it does happen.

@CaselIT ^^^

**Comment by CaselIT** [comment] 2021-06-22 13:34
Interesting. I'll need to look into it a bit. Maybe it's something that does aiohttp, and not in asgi. but I may be wrong.

**Comment by CaselIT** [comment] 2021-06-22 15:20
> Maybe it's something that does aiohttp, and not in asgi

that seem to be the case. aiohttp does not support asgi (ref https://github.com/aio-libs/aiohttp/issues/2902), so it seems it's behaviour is different in this case

**Comment by psychomelet** [comment] 2021-12-30 14:02
@zzzeek we have similar connection leak in our servers and wonder what's the status of this issue, is the bug still existed?

**Comment by zzzeek** [comment] 2021-12-30 15:15
asyncpg's fix at https://github.com/MagicStack/asyncpg/issues/772 should have fixed most of this.  on our end we can only lose all references to the connection if we are not able to do any awaits.

**Comment by camlee** [comment] 2022-06-13 23:43
I think I'm experiencing connections leak and not be closed because of this. Investigating, I think the problem is that during a cancellation, you need to shield any cleanup operations: https://docs.python.org/3/library/asyncio-task.html#shielding-from-cancellation

Without this, doing `await ...` might not actually run `...` because this yields to the event loop and it's currently trying to cancel things, not run more things.

So in your example code, it should be something like this:

```python
    finally:

        # We need to shield our cleanup from cancellation:
        await asyncio.shield(asyncpg_conn.close())
        await asyncio.shield(conn.close())
```


Here's my specifics in case in helps. Using [anyio](https://anyio.readthedocs.io/en/stable/) here, with the default asyncio implementation, but the amazing [trio](https://trio.readthedocs.io/en/stable/)-like structure.

```python
import anyio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.sql import text

async def main():
    engine = create_async_engine(
        url,
        echo=True,
        connect_args={"timeout": 5}
        )

    async def sleep_in_db():
        print(engine.pool.status()) # 0 connections
        async with engine.connect() as connection:
            print(engine.pool.status()) # 1 connections
            while True:
                await connection.execute(text("select now();"))
                await anyio.sleep(1)

    async with anyio.create_task_group() as db_tasks:
        db_tasks.start_soon(sleep_in_db)

        await anyio.sleep(2.5)

        db_tasks.cancel_scope.cancel() # Will raise a CancelledError under the hood


    print(engine.pool.status()) # 1 connection????

    await engine.dispose()

anyio.run(main)
```

And I get this warning printed to console:
```
The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7f1cf4760660>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
sys:1: SAWarning: The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7f1cf4760660>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
```

I'm running:
* OS: Ubuntu on WSL2 in Windows 10
* Python: 3.10.4
* SQLAlchemy: 1.4.37
* Database: Postgres 14
* DBAPI: asyncpg 0.25.0

I can fix this in my code by patching AsyncConnection's `__aexit__` method (https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/ext/asyncio/engine.py#L700) to add a shield:

```python
class PatchedAsyncConnection(AsyncConnection):
    async def __aexit__(self, type_, value, traceback):
        with anyio.open_cancel_scope(shield=True):
            await self.close()
```

Or by not using the context manager and manually opening and closing the connection (again, with a shield):

```python
    async def sleep_in_db():
        connection = await engine.connect()
        try:
            while True:
                await connection.execute(text("select now();"))
                await anyio.sleep(1)
        finally:
            with anyio.open_cancel_scope(shield=True):
                await connection.close()
```

**Comment by CaselIT** [comment] 2022-06-14 09:57
Could you open a new issue since this is closed

**Comment by camlee** [comment] 2022-06-16 21:00
New issue opened: https://github.com/sqlalchemy/sqlalchemy/issues/8145
