### ISSUE TITLE
Error when calling inspector.get_columns() for MS SQL with 1.3.0

### ISSUE THREAD

**Issue by daveisfera** [sqlalchemy/sqlalchemy#4525] opened 2019-03-05 21:20 UTC
A `TypeError` happens when calling `inspector.get_columns()` using an MS SQL engine with 1.3.0. Here's the traceback:

```
for c in inspector.get_columns(table_name, schema_name):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 372, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mssql/base.py", line 2084, in wrap
    **kw
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mssql/base.py", line 2095, in _switch_db
    return fn(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mssql/base.py", line 2533, in get_columns
    coltype = coltype(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'scale'
```

**Comment by zzzeek** [comment] 2019-03-06 00:47
please indicate the CREATE TABLE statement or what datatype this is, thanks

**Comment by zzzeek** [comment] 2019-03-06 00:50
yah sorry can't reproduce please include complete MCVE / CREATE TABLE

```
from sqlalchemy import create_engine
from sqlalchemy import inspect

e = create_engine("mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server", echo=True)

insp = inspect(e)

from sqlalchemy import *
m = MetaData()
t = Table('t', m, Column('q', Integer), Column('t', Float(5)))

m.drop_all(e)
m.create_all(e)

print(insp.get_columns('t'))
```

**Comment by daveisfera** [comment] 2019-03-06 05:41
Here's the definition of the table and I'll look into seeing if I can make a small reproducer for this:
```
create table [freshly picked]
(
  Billing_Address1                   text,
  Billing_Address2                   text,
  Billing_City                       text,
  Billing_Country                    text,
  Billing_First_Name                 text,
  Billing_Last_Name                  text,
  Billing_Name                       text,
  Billing_Phone                      float,
  Billing_Province                   text,
  Billing_Zip                        int,
  [Cancel Reason]                    text,
  [Cancelled Time]                   text,
  [Cancelled Time Zone]              text,
  [Closed Time]                      text,
  [Closed Time Zone]                 text,
  Color                              text,
  createdFPMonth                     text,
  createdFPQuarter                   float,
  createdFPYear                      int,
  createdLPMonth                     text,
  createdLPQuarter                   float,
  createdLPYear                      int,
  createdMonth                       text,
  createdQuarter                     float,
  createdQuarterNoYear               int,
  Created_at                         text,
  [Created_at Standard Day of Month] text,
  [Created_at Standard Day of Week]  text,
  [Created_at Standard Hour]         text,
  [Created_at Standard Month]        text,
  [Created_at Standard Year]         text,
  [Created_at Time Zone]             text,
  [Created_at Week of Year]          int,
  Currency                           text,
  custTenure                         int,
  Discount_Amount                    int,
  Discount_Code                      text,
  Email                              text,
  Financial_Status                   text,
  firstColor                         text,
  firstExist                         text,
  firstPDate                         text,
  firstProdType                      text,
  firstSize                          text,
  fPurch                             text,
  Fulfilled_at                       text,
  [Fulfillment At Time Zone]         text,
  Fulfillment_Status                 text,
  geometry                           text,
  Id                                 float,
  [Item Names]                       text,
  [key]                              text,
  lastPDate                          text,
  lPurch                             text,
  maxPurchases                       int,
  maxTenure                          int,
  Name                               text,
  Note_Attributes                    text,
  orderQuantity                      int,
  payment                            text,
  [Payment Card Number]              text,
  [Payment Card Type]                text,
  [Processed Time]                   text,
  [Processed Time Zone]              text,
  Product_Type                       text,
  purchaseIntervalDays               int,
  purchaseNumber                     int,
  q1Total                            int,
  q2Total                            int,
  q3Total                            int,
  q4Total                            int,
  qAfterFirst                        int,
  Reference                          text,
  [Referring Site]                   text,
  [Refund Products]                  text,
  [Refund Reason]                    text,
  [Refund Tax]                       int,
  Refunded_Amount                    int,
  refundIntervalDays                 text,
  refundNumber                       text,
  [Shipment Status]                  text,
  Shipping                           int,
  [Shipping Description]             text,
  Shipping_Address1                  text,
  Shipping_Address2                  text,
  Shipping_City                      text,
  Shipping_Country                   text,
  Shipping_First_Name                text,
  Shipping_Last_Name                 text,
  Shipping_Name                      text,
  Shipping_Phone                     float,
  Shipping_Province                  text,
  Size                               text,
  Source                             text,
  stMonth                            text,
  stYear                             text,
  Subtotal                           int,
  Tags                               text,
  Taxes                              int,
  Total                              int,
  [Tracking Company]                 text,
  [Tracking Number]                  text,
  [Updated Time]                     text,
  [Updated Time Zone]                text,
  voidIntervalDays                   text,
  voidNumber                         text
)
```

**Comment by zzzeek** [comment] 2019-03-06 13:21
that reproduces, thanks, you're good

**Comment by sqla-tester** [comment] 2019-03-06 14:06
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure scale param not sent to float types** https://gerrit.sqlalchemy.org/1158

**Closed** 2019-03-06 15:47 UTC
Labels: SQL Server, bug, reflection, regression

**Comment by daveisfera** [comment] 2019-03-06 22:35
Thanks for the quick turn around on this. Is there an estimate when 1.3.1 will be released with this fix?

**Comment by zzzeek** [comment] 2019-03-06 22:59
there's already two dupe complaints on this one so likely this week

**Comment by daveisfera** [comment] 2019-03-09 00:44
Any update on an ETA for the 1.3.1 release with this fix?

**Comment by fiveddd** [comment] 2019-03-11 10:01
> Any update on an ETA for the 1.3.1 release with this fix?

for me, yes!

**Comment by dave-nm** [comment] 2019-03-11 16:17
It's been released and is working well. Thanks again for the quick turnaround on this
