### ISSUE TITLE
mysql / postgresql on dupe constructs assume top level statement

### ISSUE THREAD

**Issue by dwt** [sqlalchemy/sqlalchemy#5656] opened 2020-10-19 11:25 UTC
**Describe the bug**
When building an optimised highscore using triggers I've got an explosion in the compiler, when trying to compile an upsert statement. Precisely an exception here:
```
  File "…/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1400, in visit_on_duplicate_key_update
    cols = self.statement.table.c
AttributeError: 'MySQLCompiler_mysqldb' object has no attribute 'statement'
```

**Expected behavior**
Compilation should work. I've found a workaround, by setting the `.statement` variable manually before the call. I was expecting this workaround not being neccessary.

**To Reproduce**
See reproduction in attachment [reproduction.py.zip](https://github.com/sqlalchemy/sqlalchemy/files/5401377/reproduction.py.zip). It will need access to a mysql instance. Sorry for the length.

Please pay special attention to the variable `expose_bug` which disables the workaround I have found and exposes the issue.

**Error**

```
Traceback (most recent call last):
  File "./reproduction.py", line 315, in <module>
    Score.__table__.create()
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 925, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 854, in visit_table
    _is_metadata_operation=_is_metadata_operation,
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "./reproduction.py", line 152, in create_after_all_dependencies
    CreateTrigger(self)(*args, **kwargs)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 256, in __call__
    return bind.execute(self.against(target))
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1066, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 325, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 355, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/ext/compiler.py", line 441, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/ext/compiler.py", line 486, in __call__
    return fn(element, compiler, **kw)
  File "./reproduction.py", line 199, in visit_create_trigger_mysql
    compiled_query = sql_compiler.process(element.trigger.query, literal_binds=True)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 355, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 2515, in visit_insert
    insert_stmt._post_values_clause, **kw
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 355, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "….virtualenvs/yeepa/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1400, in visit_on_duplicate_key_update
    cols = self.statement.table.c
AttributeError: 'MySQLCompiler_mysqldb' object has no attribute 'statement'
```

**Versions.**
 - OS: MacOS 10.15.7
 - Python: 2.7.16
 - SQLAlchemy: 1.3.20
 - Database: MariaDB 10.5.6
 - DBAPI: PyMySQL 0.10.1

**Comment by zzzeek** [comment] 2020-10-19 12:40
hey there.    a tip on MCVEs, you have a reproduction case there, and it works, that's great!   that showed me where the problem is.  But i had to do a lot of work first.    For example, I don't have zope installed, and in fact your program has no need to register a session with zope.  it creates a Session(), but this also is not even used in the example program.   you should make sure you remove *all* of these things that aren't needed to reproduce the bug.

Below MCVE is a reasonable minimal reproduction case.

```
#!/usr/bin/env python

import sqlalchemy as sqla
import sqlalchemy
from sqlalchemy import literal_column
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.mysql import insert as mysql_insert
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.schema import Column
from sqlalchemy.schema import DDLElement
from sqlalchemy.types import Integer


class Trigger(object):
    def __init__(self, name, target, query):
        self.name = name
        self.target = target
        self.query = query


class CreateTrigger(DDLElement):
    def __init__(self, trigger):
        self.trigger = trigger


@compiles(CreateTrigger, "mysql")
def visit_create_trigger_mysql(element, compiler, **kw):
    sql_compiler = compiler.sql_compiler
    compiled_query = sql_compiler.process(
        element.trigger.query, literal_binds=True
    )

    return """
        CREATE OR REPLACE TRIGGER %(name)s ON %(target_table_name)s
            FOR EACH ROW
                %(query)s
            """ % dict(
        name=element.trigger.name,
        target_table_name=element.trigger.target.name,
        query=compiled_query,
    )


into_table = Table(
    "t",
    MetaData(),
    Column("user_id", Integer, primary_key=True),
    Column("total", Integer),
)
insert = mysql_insert(into_table).from_select(
    [into_table.c.user_id, into_table.c.total],
    sqla.select([literal_column("NEW.user_id"), literal_column("NEW.value")]),
)
upsert = insert.on_duplicate_key_update(
    total=insert.inserted.total + into_table.c.total
)


trg = Trigger("trg", into_table, upsert)

print(CreateTrigger(trg).compile(dialect=mysql.dialect()))

```


the on dupe elements make the assumption the compiler has a statement, which in the case of running it within a trigger that's at the DDL level, they don't.   so best that they no longer rely upon this assumption.

**Comment by zzzeek** [comment] 2020-10-19 12:42
patch for MySQL, however this also needs postgresql and needs tests that these constructs don't rely upon .statement:

```
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index 3e6c676ab..e1e833408 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1461,6 +1461,8 @@ class MySQLCompiler(compiler.SQLCompiler):
         return self._render_json_extract_from_binary(binary, operator, **kw)
 
     def visit_on_duplicate_key_update(self, on_duplicate, **kw):
+        orig_statement = self.stack[-1]['selectable']
+
         if on_duplicate._parameter_ordering:
             parameter_ordering = [
                 coercions.expect(roles.DMLColumnRole, key)
@@ -1468,14 +1470,14 @@ class MySQLCompiler(compiler.SQLCompiler):
             ]
             ordered_keys = set(parameter_ordering)
             cols = [
-                self.statement.table.c[key]
+                orig_statement.table.c[key]
                 for key in parameter_ordering
-                if key in self.statement.table.c
+                if key in orig_statement.table.c
             ] + [
-                c for c in self.statement.table.c if c.key not in ordered_keys
+                c for c in orig_statement.table.c if c.key not in ordered_keys
             ]
         else:
-            cols = self.statement.table.c
+            cols = orig_statement.table.c
 
         clauses = []
         # traverses through all table columns to preserve table column order
@@ -1520,7 +1522,7 @@ class MySQLCompiler(compiler.SQLCompiler):
                 "Additional column names not matching "
                 "any column keys in table '%s': %s"
                 % (
-                    self.statement.table.name,
+                    orig_statement.table.name,
                     (", ".join("'%s'" % c for c in non_matching)),
                 )
             )

```

**Comment by dwt** [comment] 2020-10-19 12:47
Sorry for the lengthy reproduction, I had already spent about two hours reducing that out of my application and was, to be hones, running out of steam a bit. I will invest more effort into the reduction next time!

**Comment by zzzeek** [comment] 2020-10-19 12:49
I use flake8 linters in my editor which help a lot with identifying things that aren't used.    so yes it took me only 5 minutes to reduce your case further, sorry you were tired out :)

**Comment by sqla-tester** [comment] 2020-10-19 14:20
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure no compiler visit method tries to access .statement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2314

**Comment by sqla-tester** [comment] 2020-10-19 14:23
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Ensure no compiler visit method tries to access .statement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2315

**Closed** 2020-10-19 17:58 UTC
Labels: bug, mysql, postgresql
