### ISSUE TITLE
warn when running session.execute(Query)

### ISSUE THREAD

**Issue by wmolicki** [sqlalchemy/sqlalchemy#6284] opened 2021-04-15 15:17 UTC
**Describe the bug**
Generated SQL with substituted params contains NULL instead of values added at query time with "with_expression". This happens when using session.query(DeclarativeModel), using select(DeclarativeModel) seems to be fine.

Generated SQL without param substitution is the same, but results differ - seems it happens after variables are substituted

**Expected behavior**
I read through the changelog for 1.4 and haven't found anything that can be related to this behaviour. If it's not a bug it seems like an undocumented change.

**To Reproduce**
Run the below code on 1.3.12 and 1.4.7, observe `NULL as anon_1` added instead of `company_name` in the result for 1.4.7. 

```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import *

Base = declarative_base()


class User(Base):
    __tablename__ = "user"

    id = Column(Integer, primary_key=True)
    name = Column(String)

    company_name = query_expression()


e = create_engine("postgresql://localhost/test", echo=False)

Base.metadata.drop_all(e)
Base.metadata.create_all(e)
session = Session(e)

session.add(User(id=1, name='bogdan'))
session.commit()

q = session.query(
    User
).options(
    with_expression(
        User.company_name, literal('github').label('company_name')
    ),
)

result = session.execute(q)

if hasattr(result, 'raw'):
    cursor = result.raw.cursor
else:
    cursor = result.cursor

print(cursor.query.decode())


```

**Error**

```
# result on 1.4.7
# SELECT NULL AS anon_1, "user".id AS user_id, "user".name AS user_name
# FROM "user"

# result on 1.3.12
# SELECT 'github' AS company_name, "user".id AS user_id, "user".name AS user_name
# FROM "user"
```

**Versions.**
 - OS: macOS big sur
 - Python: 3.9.2
 - SQLAlchemy: 1.4.7
 - Database: postgresql 9.6
 - DBAPI: psycopg2

**Additional context**
We bumped our SQLAlchemy version from 1.3 to 1.4, couple of tests testing code that  is using query_expression stopped working - was trying to narrow it down because our code is quite complex, managed to find the discrepancy in generated SQL (example code above).

**Comment by zzzeek** [comment] 2021-04-15 16:11
hey there -

the issue is that you're using an unusual and not currently defined pattern to invoke this query, and also repurposing with_expression() in a way that was also not part of its current usage contract:

   q = session.query(...)
   result = session.execute(q)

I would not expect ORM loader options to take effect for such a query in 1.3, but it seems you're relying upon the fact that query() would add the column in any case before running in this way.

The behavior of session.execute() with ORM-enabled SELECT statements [has changed in 1.4](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#orm-query-is-internally-unified-with-select-update-delete-2-0-style-execution-available).  So if we run your thing in 1.3, the result looks like:

```
(Pdb) result.fetchall()
[('github', 1, 'bogdan')]
```

if we run in 1.4, the result is:

```
(Pdb) result.fetchall()
[(<__main__.User object at 0x7fe7a3626220>,)]
```

so already, things are very different here.   

The Session should be doing something more "defined" here, like a warning, or an error, or "just working" most likely, to get the option to take effect in 1.4 looks like:

    result = session.execute(q.statement)

but that still gives you a User object in a row, not a row with plain columns.

The error it's supposed to raise is in fact this:

     sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: <sqlalchemy.orm.query.Query object at 0x7f437344e970>

*anyway*, what you want here is 1. core-style execution against your 2. ORM-enabled query.  it will work if you do it like this:

    result = session.connection().execute(q.statement)

note above that this is still not the "main purpose" of with_expression().  if you want a certain expression in a Core select you just ask for it, that is, the "legit" way to write your query would be:

    stmt = select(User.id, User.name, literal("github").label("company_name"))
    result = session.execute(stmt)

**Comment by zzzeek** [comment] 2021-04-15 18:02
Try out 1.4.8, because what is happening there is that your first query will not include "company_name", so the attribute is unloaded, then on the next query, you specified it so it gets loaded.   The reason this isnt working in 1.4.7 is due to part of #6259 , where I identified that the query_expression was being rendered as NULL every time.

But also, if you want that query_expr to load guaranteed, you would best be using [populate existing](https://docs.sqlalchemy.org/en/14/orm/queryguide.html#populate-existing).

**Comment by wmolicki** [comment] 2021-04-15 18:10
Great, thanks for the fix and excellent suggestion!

**Comment by sqla-tester** [comment] 2021-10-01 20:16
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Warn when trying to execute a query object with a session.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3123

**Comment by CaselIT** [comment] 2021-10-01 20:16
I've added a deprecation but maybe we could just go with ` sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: <sqlalchemy.orm.query.Query object at 0x7f437344e970>`?

**Closed** 2021-10-04 22:10 UTC
Labels: bug, orm, regression
