### ISSUE TITLE
Does yield_per work with MySQL?

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#4786] opened 2019-07-29 14:37 UTC
According to the documentation of [`Query.yield_per()`](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.yield_per), 

> It [the Query.yield_per() method] is potentially compatible with “select in” eager loading, provided the database driver supports multiple, independent cursors (pysqlite and psycopg2 are known to work, MySQL and SQL Server ODBC drivers do not).

But at the same time I find this entry in the [SQLAlchemy 1.1.4 changelog](https://docs.sqlalchemy.org/en/13/changelog/changelog_11.html?highlight=stream_results#change-fb6164299483dd0c583b66267722821a):
> [mysql] [feature] Added support for server side cursors to the mysqlclient and pymysql dialects. This feature is available via the Connection.execution_options.stream_results flag as well as the server_side_cursors=True dialect argument in the same way that it has been for psycopg2 on PostgreSQL. Pull request courtesy Roman Podoliaka.

I also tried locally the yield_per in combination with `selectin` loading, and it seems to work fine with the [mysqlclient](https://github.com/PyMySQL/mysqlclient-python) driver.

Is it just an out-of-date documentation the first one?

**Comment by zzzeek** [comment] 2019-07-29 14:44
sure.

**Comment by zzzeek** [comment] 2019-07-29 14:45
I would just take out that note from the first doc.

**Comment by vimiPonyai** [comment] 2020-01-16 13:37
i am facing a problem using mysql 5.7.0 and using yield_per.

_mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

**Comment by zzzeek** [comment] 2020-01-16 14:54
> i am facing a problem using mysql 5.7.0 and using yield_per.
> 
> _mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

hi there -

there's nothing I can do with your issue as it lacks any kind of detail.    Please review the bug reporting guidelines at https://www.sqlalchemy.org/participate.html#bugs, thanks.

**Comment by zzzeek** [comment] 2020-01-17 15:16
Some discussion on #5102 where we are trying to get to the bottom of whether or not MySQL drivers support multiple independent cursors while yield_per is in progress.

**Comment by zzzeek** [comment] 2020-01-17 15:20
I'm able to reproduce the issue on #5102 , which suggests that MySQL doesn't support yield_per in a useful way.   So now I need to evaluate your claim that "selectinloading" works, because how is that possible.

**Comment by zzzeek** [comment] 2020-01-17 15:26
OK, I can't get selectinload to work either.  Using MySQLclient 1.4.4:

```
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
[SQL: SELECT b.a_id AS b_a_id, b.id AS b_id, b.data AS b_data 
FROM b 
WHERE b.a_id IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ORDER BY b.a_id]
[parameters: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)]

```

using pymysql, it does something arguably worse, just warns you that it's losing your data:

```
/home/classic/.venv3/lib/python3.7/site-packages/pymysql/connections.py:756: UserWarning: Previous unbuffered result was left incomplete
  warnings.warn("Previous unbuffered result was left incomplete")

```

so the documentation noted above is correct; MySQL does not support multiple, independent cursors.

**Comment by zzzeek** [comment] 2020-01-17 15:28
also shame on zzzeek-from-the-past not testing this claim  :)

**Comment by zzzeek** [comment] 2020-01-17 16:05
so @youtux I have a feeling you may not have tested "selectinloading" enough to show it trying to use multiple cursors at once, like perhaps too small a result set?   My own test with selectinload shows it failing for both mysqlclient and pymysql, test case is below.   Since the doc is still correct, closing this.

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import selectinload
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String(10))
    bs = relationship("B")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String(10))


e = create_engine("mysql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add_all(
    [A(id=i, bs=[B(id=i * 10 + j) for j in range(10)]) for i in range(1, 50)]
)
s.commit()

for row in s.query(A).yield_per(10).options(selectinload(A.bs)).all():
    pass

```

output:

```
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
[SQL: SELECT b.a_id AS b_a_id, b.id AS b_id, b.data AS b_data 
FROM b 
WHERE b.a_id IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ORDER BY b.a_id]
[parameters: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)]

```

**Closed by zzzeek** 2020-01-17 16:05 UTC
Labels: documentation

**Comment by youtux** [comment] 2020-01-20 08:41
> so @youtux I have a feeling you may not have tested "selectinloading" enough to show it trying to use multiple cursors at once, like perhaps too small a result set?

Indeed, the tests I made were on a too small result set, that never actually used multiple server cursors at the same time.

**Comment by harit-h** [comment] 2020-07-24 13:22
Hello,

I am facing the same issue when using `yield_per()`. I see the following stacktrace
```
/root/.local/lib/python3.6/site-packages/pymysql/connections.py:1077: UserWarning: Previous unbuffered result was left incomplete
  warnings.warn("Previous unbuffered result was left incomplete")
```

Is there a better way to stream the results, than to fetch all of them (30k+ in my case)
@zzzeek, do you have any recommendations? 

Thank you

**Comment by zzzeek** [comment] 2020-07-25 20:05
typically a windowing approach is used like that illustrated at https://github.com/sqlalchemy/sqlalchemy/wiki/RangeQuery-and-WindowedRangeQuery .   MySQL 8.0 seems to support window functions now so you could do that approach also, as stated in that wiki entry.
