### ISSUE TITLE
Reflection with AsyncEngine

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/sqlalchemy#6490] opened 2021-05-14 18:28 UTC
Is there currently a way to use reflection with an `AsyncEngine`?

e.g. something like

```python
import asyncio
from sqlalchemy import text, select, MetaData
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine
from sqlalchemy.ext.automap import automap_base

async def main():

    eng = create_async_engine(
        "postgresql+asyncpg://..."
    )

    meta = MetaData()
    base = automap_base(metadata=meta)

    await base.prepare(
        eng,
        reflect=True,
        schema="public",
    )
    # sqlalchemy.exc.NoInspectionAvailable: 
    #   No inspection system is available for
    #   object of type <class 'sqlalchemy.ext.asyncio.engine.AsyncEngine'>


(
    asyncio
    .get_event_loop()
    .run_until_complete(main())
)
```

**Comment by CaselIT** [comment] 2021-05-14 18:55
Hi,

currently there is no direct support for inspection. You would need to use run_sync for that.
Closing since this is a duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/6121

**Closed by CaselIT** 2021-05-14 18:55 UTC
Labels: asyncio, question
