### ISSUE TITLE
Incorrect type annotation for postgres multirange  types

### ISSUE THREAD

**Issue by uriyyo** [sqlalchemy/sqlalchemy#9736] opened 2023-05-03 11:45 UTC
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

Incorrect type annotation for postgres multirange types.

It produces `Range[Range[Range[T]]]` instead of `Range[Range[T]]`

### To Reproduce

```python
from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import DATEMULTIRANGE

stmt = select(func.datemultirange().cast(DATEMULTIRANGE))

reveal_type(stmt)
```

### Error

```py
note: Revealed type is "sqlalchemy.sql.selectable.Select[Tuple[sqlalchemy.dialects.postgresql.ranges.Range[sqlalchemy.dialects.postgresql.ranges.Range[sqlalchemy.dialects.postgresql.ranges.Range[datetime.date]]]]]"
``` 

### Versions

- OS: any
- Python: 3.11
- SQLAlchemy: 2.0.12
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.2.0

**Comment by TallJimbo** [comment] 2023-11-08 20:11
Just ran into this, and the problem is that the [`AbstractRange`](https://github.com/sqlalchemy/sqlalchemy/blob/4da59c6f534371d8c76cd728e8a459018e9112b6/lib/sqlalchemy/dialects/postgresql/ranges.py#L710) base class is defined with the element type of the range as its generic parameter, but its derived classes pass `Range[<something>]` as that generic parameter, starting [here](https://github.com/sqlalchemy/sqlalchemy/blob/4da59c6f534371d8c76cd728e8a459018e9112b6/lib/sqlalchemy/dialects/postgresql/ranges.py#L859).  Replacing `Range[<something>]` with `<something>` in all of those base class expressions should fix it.

**Comment by CaselIT** [comment] 2023-11-08 23:34
Seems likely. A PR would speed up the resolution of the issue

**Comment by sqla-tester** [comment] 2023-11-14 21:19
**Jim Bosch** has proposed a fix for this issue in the **main** branch:

**Fix typing generics in PostgreSQL range types.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4971

**Comment by sqla-tester** [comment] 2024-01-24 20:56
**Jim Bosch** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix typing generics in PostgreSQL range types.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5119

**Closed** 2024-02-07 19:49 UTC
Labels: bug, postgresql, PRs (with tests!) welcome, typing
