### ISSUE TITLE
we added the name ".registry" to declarative classes and that...can cause conflicts!  

### ISSUE THREAD

**Issue by CTingy** [sqlalchemy/sqlalchemy#6054] opened 2021-03-16 04:13 UTC
**Describe the bug**
After upgrade to sqlalchemy 1.4. An AttributeError will raise when I try to import some model classes.

```py
class JoinedTableInheritanceMixin:
    model = Column(...)
    @declared_attr
    def __mapper_args__(cls):
        return {'polymorphic_identity': cls.__tablename__, 'polymorphic_on': cls.model, 'with_polymorphic': '*'}

class MyModel(Base, JoinedTableInheritanceMixin):
   pass
```
```py
from mypkg.modules.base.models.rule import MyModel
```

**Error**
```
/Users/tingyun.chan/.pyenv/versions/ixt/lib/python3.7/site-packages/sqlalchemy/sql/coercions.py:300: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  "implicitly coercing SELECT object to scalar subquery; "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tingyun.chan/Workspace/ixt/mygkg/__init__.py", line 5, in <module>
    from .core.commands import cli
  File "/Users/tingyun.chan/Workspace/ixt/mygkg/core/commands.py", line 15, in <module>
    from .database.data_importer import DataImporter
  File "/Users/tingyun.chan/Workspace/ixt/mygkg/core/database/data_importer.py", line 21, in <module>
    from mygkg.modules.base.models.data import Data
  File "/Users/tingyun.chan/Workspace/ixt/mygkg/modules/base/models/__init__.py", line 1, in <module>
    from . import activity_log, attachment, bank, country, data, locale, mail, message, notification, \
  File "/Users/tingyun.chan/Workspace/ixt/mygkg/modules/base/models/rule.py", line 18, in <module>
    class MyModel(Base, JoinedTableInheritanceMixin):
  File "/Users/tingyun.chan/.pyenv/versions/ixt/lib/python3.7/site-packages/sqlalchemy/orm/decl_api.py", line 60, in __init__
    _as_declarative(cls.registry, cls, cls.__dict__)
  File "/Users/tingyun.chan/.pyenv/versions/ixt/lib/python3.7/site-packages/sqlalchemy/orm/decl_base.py", line 125, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/Users/tingyun.chan/.pyenv/versions/ixt/lib/python3.7/site-packages/sqlalchemy/orm/decl_base.py", line 176, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/Users/tingyun.chan/.pyenv/versions/ixt/lib/python3.7/site-packages/sqlalchemy/orm/decl_base.py", line 290, in __init__
    super(_ClassScanMapperConfig, self).__init__(registry, cls_)
  File "/Users/tingyun.chan/.pyenv/versions/ixt/lib/python3.7/site-packages/sqlalchemy/orm/decl_base.py", line 189, in __init__
    init_method=registry.constructor,
AttributeError: 'dict' object has no attribute 'constructor'
```

**Versions.**
 - OS: MacOS Big Sur version 11.0.1
 - Python: 3.7.2
 - SQLAlchemy: 1.4
 - Database: Postgresql & Oracle & MSSQL (we use these 3 kinds of DBs, all of them would raise AttributeError)
 - DBAPI: cx-Oracle==8.0.1, psycopg2-binary==2.8.6, pymssql==2.1.4

Thanks

**Comment by zzzeek** [comment] 2021-03-16 13:20
hey there -

your code fragment does not provide enough context to know what the problem is. Please provide a proper [MCVE](http://stackoverflow.com/help/mcve).  To assist in this, please use the example below, modify the code as given to illustrate the failure.  thanks!


```python
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import configure_mappers

Base = declarative_base()


class JoinedTableInheritanceMixin:
    model = Column(String)

    @declared_attr
    def __mapper_args__(cls):
        return {
            "polymorphic_identity": cls.__tablename__,
            "polymorphic_on": cls.model,
            "with_polymorphic": "*",
        }


class MyModel(Base, JoinedTableInheritanceMixin):
    __tablename__ = "mymodel"

    id = Column(Integer, primary_key=True)


class MySubModel(MyModel, JoinedTableInheritanceMixin):
    __tablename__ = "mysubmodel"

    id = Column(ForeignKey("mymodel.id"), primary_key=True)


configure_mappers()
```

**Comment by CTingy** [comment] 2021-03-16 14:02
Thank you for your prompt reply.
Your example works well on my side. And I found only a part of all my model classes can raise this exception.
I'm not quite sure about the root cause. If I find something about it, I'll post here.

**Comment by CTingy** [comment] 2021-03-16 14:35
Soooory, this is a stupid question. I haven't noticed that version 1.4 uses 'registry' in model class.
We have many model classes have attributes called 'registry' to store values.

**Comment by zzzeek** [comment] 2021-03-16 18:17
OK that is a problem!   we might need to change our assumptions here because yes, this name "registry" got added and....yeah.   let me take a look at how this may be adjustable.

**Comment by sqla-tester** [comment] 2021-03-16 19:08
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Early-assign Base.registry to a private name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2635

**Closed** 2021-03-16 20:39 UTC
Labels: bug, orm, regression
