### ISSUE TITLE
Model hash functions are unnecessarily called during certain ORM operations

### ISSUE THREAD

**Issue by jamespfennell** [sqlalchemy/sqlalchemy#5304] opened 2020-05-03 19:43 UTC
**Describe the bug**

When I perform certain ORM relationship operations, the hash functions of my SQLAlchemy models are unnecessarily called. 

The hash functions are only called because of internal implementation details of the data structure `sqlalchemy.util._collections.IdentitySet`. The implementation can be easily changed with no outward change in behavior to avoid calling the hash of the models. I would like to make the changes and submit a PR if you are open to it!

These invocations are concerning to me and hence I'm filling a "bug" here for the following reason. In my project, I define custom `__eq__` and `__hash__` functions for use in my test suites. These functions are customized to my project, and may not return the right answers in all cases - for example, my `__eq__` doesn't inspect relationships. I am concerned that SQLAlchemy makes certain assumptions about the behavior of `__eq__` and `__hash__`, and that I may introduce bugs by overriding them because I break these assumptions.

**Expected behavior**

If SQLAlchemy needs to or finds it convenient to call `__eq__` and `__hash__` that's fine, but it should be avoided if possible.

**To Reproduce**

```py
from sqlalchemy import Column, Integer, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class Parent(Base):
    __tablename__ = "parent"

    pk = Column(Integer, primary_key=True)
    children = relationship("Child", back_populates="parent")


class Child(Base):
    __tablename__ = "child"

    pk = Column(Integer, primary_key=True)
    parent_pk = Column(Integer, ForeignKey("parent.pk"), index=True)

    parent = relationship("Parent", back_populates="children")

    def __hash__(self):
        raise NotImplementedError


if __name__ == "__main__":
    parent = Parent()
    parent.children = [Child(), Child()]  # Raises NotImplementedError
```

**Error**

```
Traceback (most recent call last):
  File "sandbox/sqlalchemy_collections.py", line 29, in <module>
    parent.children = [
  File "/Users/james/Projects/new-realtimerail/.pyenv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 271, in __set__
    self.impl.set(
  File "/Users/james/Projects/new-realtimerail/.pyenv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1335, in set
    collections.bulk_replace(
  File "/Users/james/Projects/new-realtimerail/.pyenv/lib/python3.8/site-packages/sqlalchemy/orm/collections.py", line 790, in bulk_replace
    constants = existing_idset.intersection(values or ())
  File "/Users/james/Projects/new-realtimerail/.pyenv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 615, in intersection
    result._members.update(self._working_set(members).intersection(other))
  File "sandbox/sqlalchemy_collections.py", line 23, in __hash__
    raise NotImplementedError
NotImplementedError
```

**Versions.**
 - OS: MacOS Mojave 10.14.6
 - Python: 3.8.0
 - SQLAlchemy: 1.3.16
 - Database: N/A
 - DBAPI: N/A

**Additional context**

I will post a technical description of the problem and a proposed solution as a comment.

**Comment by jamespfennell** [comment] 2020-05-03 19:44
The technical problem can be seen in `IdentitySet.intersection`, though the problem exists in a few other methods of `IdentitySet` too. Here's what the method looks like. (I have replaced the reference to the class variable `self._working_set` with its class value `set`.)
```py
def intersection(self, iterable):
    result = type(self)()
    members = self._member_id_tuples()
    other = _iter_id(iterable)
    result._members.update(set(members).intersection(other))
    return result
```
The problem is that tuples of the form `(id(model), model)` are placed into two regular Python sets and then the intersection taken. Putting the tuple in the set requires calculating the hash of the model. However clearly calculating the hash is redundant: if the hashes of the models are different then necessarily these are two different instances, and then the ids will be different, and so the hash of the tuple is different already.

I would propose replacing this implementation with something like this:
```py
def intersection(self, iterable):
    result = type(self)()
    member_ids = set(self._members.keys()) # this is the set of id(v) for all v in the IdentitySet
    other = _iter_id(iterable)
    result._members.update(
        (other_id, other_element)
        for other_id, other_element in other
        if other_id in member_ids
    )
    return result
```
As said above, I would be very happy to do this for all affected methods, write tests, and submit a PR.

**Comment by zzzeek** [comment] 2020-05-04 00:04
so for many years, like 12 years type many, we've always had this policy that the ORM is never dependent on the `__hash__()` of a mapped object.  That's why there are all the identityset things going on.    But in fact I'm not sure I realized that we are actually still *calling* upon `__hash__()` , I sort of thought we weren't, but it looks like IdentitySet etc. have been using a set of tuples internally since they were first implemented.

ideally there would be another test object in test/base/test_utils.py where __hash__ is just None so that it raises.  For some reason I thought that was already present, but apparently it's not.

I'm not too confident that removing the use of set() against tuples isn't going to cause some regressions so let me see why it's like that.

**Comment by sqla-tester** [comment] 2020-05-04 00:33
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't apply sets or similar to objects in IdentitySet** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1939

**Comment by zzzeek** [comment] 2020-05-04 00:37
Feel free to review the gerrit linked above.   there are some things I had to keep in mind  here, namely the implementation is trying to support an ordered dictionary backend, and we are still supporting Python 2.7 where things like dict comprehensions are not necessarily ordered.

**Comment by sqla-tester** [comment] 2020-05-04 00:37
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Don't apply sets or similar to objects in IdentitySet** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1940

**Comment by jamespfennell** [comment] 2020-05-04 01:29
Nice! Code changes look good to me. Thanks! This makes me feel easier about my overrides of `__eq__` and `__hash__`.

**Closed** 2020-05-04 17:10 UTC
Labels: bug, orm, performance
