### ISSUE TITLE
Inconsistency JSON results among PostgreSQL drivers

### ISSUE THREAD

**Issue by fantix** [sqlalchemy/sqlalchemy#5584] opened 2020-09-15 05:40 UTC
**Describe the bug**

By default, different PostgreSQL drivers may return different Python types for JSON(B) values. For example of the same JSON dict, psycopg2 returns `dict` while asyncpg returns `str`. SQLAlchemy should eliminate the difference and return consistent results. The issue is, the asyncpg dialect/driver cannot parse JSON into dict if the SA type is unspecified (executing raw SQL for example), please see below.

**To Reproduce**

```py
import asyncio

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import create_async_engine


async def main():
    e = sa.create_engine("postgresql+psycopg2:///", future=True)
    ae = create_async_engine("postgresql+asyncpg:///")

    for json_type in [sa.JSON, JSONB]:
        print(json_type.__visit_name__)

        # create test tables
        metadata = sa.MetaData()
        users = sa.Table("users", metadata, sa.Column("profile", json_type))
        metadata.create_all(e)

        queries = [
            ("clause", sa.select([users.c.profile])),
            ("text  ", sa.text("SELECT profile FROM users")),
        ]

        with e.connect() as conn:
            conn.execute(users.insert().values(profile=dict(a=1, b=2)))
            for exec_type, obj in queries:
                print("sync ", exec_type, type(conn.scalar(obj)).__name__)
            conn.execute(users.delete())

        async with ae.connect() as conn:
            await conn.execute(users.insert().values(profile=dict(a=1, b=2)))
            for exec_type, obj in queries:
                print("async", exec_type, type(await conn.scalar(obj)).__name__)
            await conn.execute(users.delete())

        metadata.drop_all(e)


asyncio.run(main())
```

**Expected results**

```
JSON
sync  clause dict
sync  text   dict
async clause dict
async text   dict
JSONB
sync  clause dict
sync  text   dict
async clause dict
async text   dict
```

**Actual results**

```
JSON
sync  clause dict
sync  text   dict
async clause dict
async text   str
JSONB
sync  clause dict
sync  text   dict
async clause dict
async text   str
```

**Versions.**
 - OS: Darwin Kernel Version 19.5.0
 - Python: Python 3.8.2
 - SQLAlchemy: 1.4.0b1 @ 4d17fe4063adef50c1d529993e0b047f503940e2
 - Database: PostgreSQL 12.4
 - DBAPI: asyncpg 0.21.0, psycopg2 2.8.5 (dt dec pq3 ext lo64)

**Additional context**

I have 2 candidate solutions:

1. Override `NullType.result_processor()`. This is simpler but slightly hacky:

```patch
diff --git a/lib/sqlalchemy/dialects/postgresql/asyncpg.py b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
index 780e23844..a62db1a5e 100644
--- a/lib/sqlalchemy/dialects/postgresql/asyncpg.py
+++ b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
@@ -70,6 +70,9 @@ try:
 except ImportError:
     _python_UUID = None

+JSON_COLTYPE = 114
+JSONB_COLTYPE = 3802
+

 class AsyncpgTime(sqltypes.Time):
     def get_dbapi_type(self, dbapi):
@@ -218,6 +221,15 @@ class AsyncpgOID(OID):
         return dbapi.INTEGER


+class AsyncpgNullType(sqltypes.NullType):
+    def result_processor(self, dialect, coltype):
+        if coltype == JSON_COLTYPE:
+            return json.JSON().result_processor(dialect, coltype)
+        if coltype == JSONB_COLTYPE:
+            return json.JSONB().result_processor(dialect, coltype)
+        return super().result_processor(dialect, coltype)
+
+
 class PGExecutionContext_asyncpg(PGExecutionContext):
     def pre_exec(self):
         if self.isddl:
@@ -720,6 +732,7 @@ class PGDialect_asyncpg(PGDialect):
             sqltypes.Enum: AsyncPgEnum,
             OID: AsyncpgOID,
             REGCLASS: AsyncpgREGCLASS,
+            sqltypes.NullType: AsyncpgNullType,
         },
     )

```

(This was the solution in GINO, see python-gino/gino#305, python-gino/gino#403)

2. Use asyncpg-native `set_type_codec()`. This is more consistent with psycopg2 impl but longer. Moreover, it revealed another issue, please see TODO below:

```patch
diff --git a/lib/sqlalchemy/dialects/postgresql/asyncpg.py b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
index 780e23844..330e71732 100644
--- a/lib/sqlalchemy/dialects/postgresql/asyncpg.py
+++ b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
@@ -41,6 +41,7 @@ in conjunction with :func:`_sa.craete_engine`::
 import collections
 import decimal
 import itertools
+import json as json_lib
 import re

 from . import json
@@ -123,11 +124,17 @@ class AsyncpgJSON(json.JSON):
     def get_dbapi_type(self, dbapi):
         return dbapi.JSON

+    def result_processor(self, dialect, coltype):
+        return None
+

 class AsyncpgJSONB(json.JSONB):
     def get_dbapi_type(self, dbapi):
         return dbapi.JSONB

+    def result_processor(self, dialect, coltype):
+        return None
+

 class AsyncpgJSONIndexType(sqltypes.JSON.JSONIndexType):
     def get_dbapi_type(self, dbapi):
@@ -500,6 +507,7 @@ class AsyncAdapt_asyncpg_connection:

         """

+        # TODO: this causes failure in future set_type_codec() below
         await self._connection.set_type_codec(
             "char",
             schema="pg_catalog",
@@ -508,6 +516,24 @@ class AsyncAdapt_asyncpg_connection:
             format="text",
         )

+    def setup_json_handlers(self, serializer, deserializer):
+        self.await_(
+            self._connection.set_type_codec(
+                "json",
+                encoder=serializer,
+                decoder=deserializer,
+                schema="pg_catalog",
+            )
+        )
+        self.await_(
+            self._connection.set_type_codec(
+                "jsonb",
+                encoder=serializer,
+                decoder=deserializer,
+                schema="pg_catalog",
+            )
+        )
+
     def _handle_exception(self, error):
         if not isinstance(error, AsyncAdapt_asyncpg_dbapi.Error):
             exception_mapping = self.dbapi._asyncpg_error_translate
@@ -796,5 +822,34 @@ class PGDialect_asyncpg(PGDialect):
                 e, self.dbapi.InterfaceError
             ) and "connection is closed" in str(e)

+    def on_connect(self):
+        fns = []
+        if self.isolation_level is not None:
+
+            def on_connect(conn):
+                self.set_isolation_level(conn, self.isolation_level)
+
+            fns.append(on_connect)
+
+        if self.dbapi:
+
+            def on_connect(conn):
+                conn.setup_json_handlers(
+                    lambda x: x,
+                    self._json_deserializer or json_lib.loads,
+                )
+
+            fns.append(on_connect)
+
+        if fns:
+
+            def on_connect(conn):
+                for fn in fns:
+                    fn(conn)
+
+            return on_connect
+        else:
+            return None
+

 dialect = PGDialect_asyncpg
```

**Have a nice day!**

**Comment by zzzeek** [comment] 2020-09-15 12:16
we generally don't try to change the DBAPI's behavior for string statements unless there is something very simple that can be done at the driver level.  The same behavior will illustrate itself against a MySQL backend for example.   The SQLAlchemy typing module itself never gets involved with a non-typed Core statement.

For the DBAPI behavior, since the pep-249 DBAPI is in SQLAlchemy's dialect, these handlers should be set up as in the patch below, but it doesn't work.   first off I have to move the "char" handler, which makes no sense, and then if the json handlers are correctly installed your test case still returns a string for that row, even if I remove the "char" handler completely.     I dont see any difference to the "connection" object how the approach you have above is any different.

 
```
diff --git a/lib/sqlalchemy/dialects/postgresql/asyncpg.py b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
index 780e23844..2f23c3832 100644
--- a/lib/sqlalchemy/dialects/postgresql/asyncpg.py
+++ b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
@@ -42,6 +42,7 @@ import collections
 import decimal
 import itertools
 import re
+import json as _py_json
 
 from . import json
 from .base import _DECIMAL_TYPES
@@ -467,13 +468,17 @@ class AsyncAdapt_asyncpg_connection:
         "isolation_level",
         "readonly",
         "deferrable",
+        "json_encoder",
+        "json_decoder",
         "_transaction",
         "_started",
     )
 
     await_ = staticmethod(await_only)
 
-    def __init__(self, dbapi, connection):
+    def __init__(
+        self, dbapi, connection, json_encoder=None, json_decoder=None
+    ):
         self.dbapi = dbapi
         self._connection = connection
         self.isolation_level = "read_committed"
@@ -481,6 +486,8 @@ class AsyncAdapt_asyncpg_connection:
         self.deferrable = False
         self._transaction = None
         self._started = False
+        self.json_encoder = json_encoder or _py_json.dumps
+        self.json_decoder = json_decoder or _py_json.loads
         self.await_(self._setup_type_codecs())
 
     async def _setup_type_codecs(self):
@@ -500,6 +507,22 @@ class AsyncAdapt_asyncpg_connection:
 
         """
 
+        # these are accepted, but the row still comes back as a string.
+        await self._connection.set_type_codec(
+            "json",
+            encoder=self.json_encoder,
+            decoder=self.json_decoder,
+            schema="pg_catalog",
+        )
+        await self._connection.set_type_codec(
+            "jsonb",
+            encoder=self.json_encoder,
+            decoder=self.json_decoder,
+            schema="pg_catalog",
+        )
+
+        # if this is first, then it raises the error.  that doesnt
+        # make any sense
         await self._connection.set_type_codec(
             "char",
             schema="pg_catalog",

```

**Comment by zzzeek** [comment] 2020-09-15 12:24
oh now I got a working version, but I have no idea why.    OH, I think it was double-encoding the JSON, ha, OK.  Here's a working patch

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/asyncpg.py b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
index 780e23844..cd5828960 100644
--- a/lib/sqlalchemy/dialects/postgresql/asyncpg.py
+++ b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
@@ -42,6 +42,7 @@ import collections
 import decimal
 import itertools
 import re
+import json as _py_json
 
 from . import json
 from .base import _DECIMAL_TYPES
@@ -123,11 +124,17 @@ class AsyncpgJSON(json.JSON):
     def get_dbapi_type(self, dbapi):
         return dbapi.JSON
 
+    def result_processor(self, dialect, coltype):
+        return None
+
 
 class AsyncpgJSONB(json.JSONB):
     def get_dbapi_type(self, dbapi):
         return dbapi.JSONB
 
+    def result_processor(self, dialect, coltype):
+        return None
+
 
 class AsyncpgJSONIndexType(sqltypes.JSON.JSONIndexType):
     def get_dbapi_type(self, dbapi):
@@ -467,13 +474,17 @@ class AsyncAdapt_asyncpg_connection:
         "isolation_level",
         "readonly",
         "deferrable",
+        "json_encoder",
+        "json_decoder",
         "_transaction",
         "_started",
     )
 
     await_ = staticmethod(await_only)
 
-    def __init__(self, dbapi, connection):
+    def __init__(
+        self, dbapi, connection
+    ):
         self.dbapi = dbapi
         self._connection = connection
         self.isolation_level = "read_committed"
@@ -500,6 +511,21 @@ class AsyncAdapt_asyncpg_connection:
 
         """
 
+        await self._connection.set_type_codec(
+            "json",
+            encoder=lambda value: value,
+            decoder=_py_json.loads,
+            schema="pg_catalog",
+        )
+        await self._connection.set_type_codec(
+            "jsonb",
+            encoder=lambda value: value,
+            decoder=_py_json.loads,
+            schema="pg_catalog",
+        )
+
+        # if this is first, then it raises the error.  that doesnt
+        # make any sense
         await self._connection.set_type_codec(
             "char",
             schema="pg_catalog",

```

**Comment by zzzeek** [comment] 2020-09-15 12:25
JSON's coming back as json without SQLAlchemy Core typing involved is not supported across the board so this can have conditional tests in tests/dialect/postgresql/test_types.py -> JSONTest , may or may not work for pg8000 also.

**Comment by fantix** [comment] 2020-09-15 22:05
>        # if this is first, then it raises the error.  that doesn't
>        # make any sense

I believe it's because of this:

https://github.com/MagicStack/asyncpg/blob/2bac166c1ba098b9ebdfca3dc5b8264ae850213c/asyncpg/introspection.py#L137-L158
```python
TYPE_BY_NAME = '''\
SELECT
    t.oid,
    t.typelem     AS elemtype,
    t.typtype     AS kind
FROM
    pg_catalog.pg_type AS t
    INNER JOIN pg_catalog.pg_namespace ns ON (ns.oid = t.typnamespace)
WHERE
    t.typname = $1 AND ns.nspname = $2
'''


# 'b' for a base type, 'd' for a domain, 'e' for enum.
SCALAR_TYPE_KINDS = (b'b', b'd', b'e')


def is_scalar_type(typeinfo) -> bool:
    return (
        typeinfo['kind'] in SCALAR_TYPE_KINDS and
        not typeinfo['elemtype']
    )
```

Where `pg_catalog.pg_type.typtype` has type `"char"` (double-quoted, oid 18), and it is converted to a string by our custom codec, thus `is_scalar_type()` check failed and raised an error (`'b' not in (b'b', b'd', b'e')`).

I think this may break other asyncpg introspection queries, so I created another issue report: #5586

**Comment by CaselIT** [comment] 2020-09-20 19:29
>may or may not work for pg8000 also

pg8000 seems to return dict for json types

**Comment by sqla-tester** [comment] 2020-09-20 20:02
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add reflection for Identity columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2248

**Comment by CaselIT** [comment] 2020-09-20 20:09
I've changed a bit Mike's patch to allow the user to customize the json decoder used. 

https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2248/6/lib/sqlalchemy/dialects/postgresql/asyncpg.py

**Comment by CaselIT** [comment] 2020-09-20 22:25
I've had to add a workaround for arrays of json, since asyncpg does not accept ['null'] as valid input for a type JSON[] when `set_type_codec` is used.

Updated in patch 7

https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2248/7/lib/sqlalchemy/dialects/postgresql/asyncpg.py

**Comment by sqla-tester** [comment] 2020-09-21 18:36
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve Asyncpg json handling** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2252

**Comment by CaselIT** [comment] 2020-09-21 19:08
I've created a new patch with only the change to asyncpg. See here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2252

@fantix if you could take a look it would be great. I'm not sure if the problem with array of json(b) is due to a bug in how sqlalchemy handles it, or it's on asyncpg side. The other dialects we test, psycopg and pg8000 seem to work.

**Comment by CaselIT** [comment] 2020-09-22 19:19
I think that there is actually bug on asyncpg. I've opened the issue https://github.com/MagicStack/asyncpg/issues/623

**Closed** 2020-09-24 02:19 UTC
Labels: datatypes, postgresql, use case

**Comment by fantix** [comment] 2020-09-24 21:45
Thank you for the fix! I can confirm it's working as expected now.

**Comment by CaselIT** [comment] 2020-09-24 21:50
Great. I did add also in db tests for equality to ensure that json null are nor transformed to sql null.

I believe that the asyncpg handling of the json type codec we used could be improved, if it ever support only settings the decoder. Currently the text mode cannot be used since it has bug in some cases.

**Comment by fantix** [comment] 2020-09-25 02:57
> I did add also in db tests for equality to ensure that json null are nor transformed to sql null.

👍 

> Currently the text mode cannot be used since it has bugs in some cases.

Hopefully fixed in https://github.com/MagicStack/asyncpg/pull/627

**Comment by CaselIT** [comment] 2020-09-25 06:23
Thanks for looking into this

**Comment by FeeeeK** [comment] 2023-09-26 16:43
Hi, came across this issue while looking for a solution to my problem. Do I understand correctly that sqlalchemy does not guarantee that the result of a select from a json field will be deserialized? Because I am facing this problem now in 2.0 with asyncpg

**Comment by CaselIT** [comment] 2023-09-26 17:23
as far as I know this should work correctly, if the datatypes are correct in the query.

if you have a reproducible issue please open a new issue or discussion if it's more a question like thing

**Comment by zzzeek** [comment] 2023-09-26 17:55
> Hi, came across this issue while looking for a solution to my problem. Do I understand correctly that sqlalchemy does not guarantee that the result of a select from a json field will be deserialized? Because I am facing this problem now in 2.0 with asyncpg

this issue is has been resolved for almost exactly three years.   JSON datatypes are fully supported by all PostgreSQL dialects in SQLAlchemy, which will deserialize if used correctly.

**Comment by FeeeeK** [comment] 2023-09-26 19:21
Sorry, false alarm, for some reason my coworker decided to store json as an already serialized string inside a json field, so sqlalchemy was working right and giving back str...
