### ISSUE TITLE
accommodate for @ in database portion even if user:pass is present

### ISSUE THREAD

**Issue by Tosi123** [sqlalchemy/sqlalchemy#6482] opened 2021-05-14 01:31 UTC
**Versions**
 - OS: CentOS 7
 - Python: 3.6.8
 - SQLAlchemy: 1.4.15
 - Database: Mysql
 - DBAPI: pymysql

When creating_engine, if the password contains special characters, I understand that it is URL Encoding

DB Test
IP : 1.1.1.1
PORT: 3306
ID: test
PW: test
DB Name: test@test

question
1. What should I do if there are special characters in DB Name?
DB Name does not appear to be doing separate decoding
```
742 tokens = components["database"].split("?", 2)
743 components["database"] = tokens[0]
```

Parsing error on regular expression below when @ is entered in DB Name

re.compile('\n (?P<name>[\\w\\+]+)://\n (?:\n (?P<username>[^:/]*)\n (?::(?P<password>.*))?\n @)?\n (?:\n (?:\n , re.VERBOSE)
{'name': 'mysql+pymysql', 'username': 'test', 'password': 'test@1.1.1.1:3306/test', 'ipv6host': None, 'ipv4host': 'test', 'port': None, 'database': None}

**Comment by zzzeek** [comment] 2021-05-14 02:57
no solution right now other than [programmatic construction of the URL object](https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=url#sqlalchemy.engine.URL.create):

    from sqlalchemy.engine import URL
    url = URL.create("mysql", username="user", password="pw", host="host", database="my@database")
    engine = create_engine(url)

**Comment by zzzeek** [comment] 2021-05-24 15:03
we already support @ in the database portion, but it was only tested with a file-only URL.

**Comment by sqla-tester** [comment] 2021-05-24 15:25
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**URL parsing fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2838

**Closed** 2021-05-24 18:16 UTC
Labels: engine, fairly easy, use case

**Comment by BuSHari** [comment] 2021-05-31 06:50
> **Mike Bayer** has proposed a fix for this issue in the **master** branch:
> 
> **URL parsing fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2838

That fix broke our connection when i use '@' in our password string, we wanted to avoid using urlib parse quote.
Anyway to revert that fix?

**Comment by CaselIT** [comment] 2021-05-31 08:50
I think the new behaviour is the correct one, since previously it would result in the wrong parsing of the url.
As documented, special characters in the password field should be quoted, so I would suggest quoting the password.

**Comment by dwt** [comment] 2021-05-31 16:12
Out of interest, how do I do that in a connection url like this? We configure our app via a config.ini file with 

```
sqlalchemy.url = mysql+pymysql://username:pass@pass@staging.example.org/staging?charset=utf8mb4&ssl_ca=/etc/pki/sntl-ca.crt
```

Right now the host is parsed as pass@staging.example.org - which of course doesn't work.

**Comment by dwt** [comment] 2021-05-31 16:16
Got it - url escaping is the answer. So `@` becomes `%40`

**Comment by CaselIT** [comment] 2021-05-31 16:50
The classic [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding) should work

**Comment by erfannariman** [comment] 2021-06-01 16:26
> > **Mike Bayer** has proposed a fix for this issue in the **master** branch:
> > **URL parsing fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2838
> 
> That fix broke our engine connection when we use '@' in our password string, we wanted to avoid using urlib parse quote.
> Anyway to revert that fix?

Could you explain what is wrong with using`urllib.parse.quote_plus`? We implemented that as a solution.

**Comment by jvanasco** [comment] 2021-06-01 22:44
> Could you explain what is wrong with usingurllib.parse.quote_plus? We implemented that as a solution.

@erfannariman I can't speak for the person who posted the comment, but the typical complaints against using `quote_plus` I have seen are:

i) wanting to avoid code that correctly parses a `sqlalchemy.url`, properly escapes the components, then reconstructs the `sqlalchemy.url`
ii) wanting to avoid code/configuration that accepts components of a `sqlalchemy.url`, properly escapes them, then constructs a full `sqlalchemy.url`

The OP may have other reasons, but the most typical ones I have seen are avoiding the workload you already invested in.

**Comment by BuSHari** [comment] 2021-06-02 06:33
> > > **Mike Bayer** has proposed a fix for this issue in the **master** branch:
> > > **URL parsing fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2838
> > 
> > 
> > That fix broke our engine connection when we use '@' in our password string, we wanted to avoid using urlib parse quote.
> > Anyway to revert that fix?
> 
> Could you explain what is wrong with using`urllib.parse.quote_plus`? We implemented that as a solution.

When i use an external config file that contain the url connection.

for the fix in: https://github.com/sqlalchemy/sqlalchemy/blob/84d36fd975fd58f5670571ae2dc83a2b53534cdd/lib/sqlalchemy/engine/url.py#L700

we can use this regex for the password:
```python
    pattern = re.compile(
        r"""
            (?P<name>[\w\+]+)://
            (?:
                (?P<username>[^:/]*)
                (?::(?P<password>.*))?
            @)?
            (?:
                (?:
                    \[(?P<ipv6host>[^/\?]+)\] |
                    (?P<ipv4host>[^/:\?]+)
                )?
                (?::(?P<port>[^/\?]*))?
            )?
            (?:/(?P<database>[^\?]*))?
            (?:\?(?P<query>.*))?
            """,
        re.X,
    )
```

**Comment by CaselIT** [comment] 2021-06-02 06:51
I think that the regexp you suggested  would reopen this issue, since it would consider as password everything up to the @ in the db name.
The password has always required escaping of special characters, and is documented as requiring it. The fact that the previous version accepted @ was an implementation detail, so the current behaviour is working as intended and as documented.

If you use an external file to pass the url you can escape it in the external file manually.

**Comment by jaraqueffdc** [comment] 2021-06-02 11:15
I agree with reopening this. Our tools starting failing since yesterday leaving the team with nothing available in production and we tracked down the issue up to here. Our user password ends with @U and that 2 characters are being added to the hostname making the connection impossible.

**Comment by zzzeek** [comment] 2021-06-02 12:26
> I agree with reopening this. Our tools starting failing since yesterday leaving the team with nothing available in production and we tracked down the issue up to here. Our user password ends with @U and that 2 characters are being added to the hostname making the connection impossible.

Unfortunately you will need to escape the password in your application, or pin the sqlalchemy version in use, as the @ sign in the URL indicates the start of the hostname .

**Comment by jaraqueffdc** [comment] 2021-06-02 13:43
> Unfortunately you will need to escape the password in your application, or pin the sqlalchemy version in use, as the @ sign in the URL indicates the start of the hostname .

Can you confirm that using `URL.create` (which I was not aware it existed) will take care of all these ambiguities? If that is the case using this is perfectly fine with us and will solve our issue. That object can be passed then to `create_engine` and it should work fine, right?

**Comment by zzzeek** [comment] 2021-06-02 14:28
> > Unfortunately you will need to escape the password in your application, or pin the sqlalchemy version in use, as the @ sign in the URL indicates the start of the hostname .
> 
> Can you confirm that using `URL.create` (which I was not aware it existed) will take care of all these ambiguities? If that is the case using this is perfectly fine with us and will solve our issue. That object can be passed then to `create_engine` and it should work fine, right?

sure, URL.create() is new in 1.4 and supersedes the previous approach of using the ``__init__()`` method to create URL objects.   This receives each element individually in it's literal form so there is no parsing or unescaping involved.

**Comment by Lyndon-prequel** [comment] 2025-05-12 20:34
Recently ran into this issue too.  To make it easier for others to figure out if they're affected, I created a common reliability enumeration (CRE). You can preview the rule [here](https://play.prequel.dev/?data=EwBmFYFoQFm8AqwDMAuG5XgGwDoCMKG2AWgAQCiASlQPJVkDOAjgDYCGrAxgBYCmAWwCeuPgDsA5gEsxfXACN2jORUky%2BZAMIB7AK6sAJmTHaALmQAO7AE7Ky1gGZd8AdmQAOMgFUqAGTIO1toCTKbWMhJkAOQW2oymEtZ8LKyoAPRpusrWqFYAAoyMAO7a1gZ5BvKiAB7sAhasclzBWDDIwGnClVEAUAjW7Fx8ilwA1mQAFAJx5klDYuZcnKxkHPEAlKg9ZGQAYlKNZABEuKdHADSr6mSnuJcyN6fbO2Ti0rJkALxkXEnspnwAPpvdQTI6xeKJZJsdKZbK5dgFYqlcqVGp1BpNFrgNodLryI7rZ77Q4nU4pTi8QRCNIg2RpX58f5yCxCC5XD63e5iH5-AHAtSyZ47AZSOx8apcXAAQWsEl0AnEpgo1iC1jBOn0RhM5istg0jmcbk8Pn8gWCoXCkmiAFJGFEjmQbWRdNZWESKdx%2BMIalLZfLFQsVWrUFo9IZjGZLDY7IbXB5vH4AkEQvErZEYjMoSlYVk%2BDl8oUSmUKlUJRjGrhmgJWu1OkJukA&rule=E4VwNgpgzgXAUAWgAQGNgXkrSCWATGJAYQCUBRBAJgAZKBWBa6gZmrmySggDcJgcALgE9CldtgGDIhAMoBFADIBBMCgAWEALZDU6AIYCIAfQgA7AOY5TEJADM9OMFCQB3DaaQAHPVCguA9sB4qP6mAg6mzlCeECg4emCoanrAeiiGwM5gOADWNgAC4lgoBhDmgSJIgZoInsD%2BAEaQmkVIeiACaoGEAAroAI4gEGCteNBoOJ6SoYQAPkitWMjyyqoa2m2entkl05FIIFBW5kgABmgQpSYWVhAAFACUp0iaejr2jkgC-iGm1ulfH56JB4Ax6Bo%2BGw4WxfDQHLjAUx6TQ2QJeHx%2BQLBFChcJWKIxOIJJIpNIZZx3CAAOnMVIANGd8qcGacYMyzgB6dmnADEpweVKQABUNFwSal0nxnJpDgIkA0bABVEgKBBmHFjYJuMy4UwoMAgTW62E2UHhCFinF-WJ7TgCfgWQUAMQcBvQgKQ6v8YxNmiQkD0eGc33RmWOnuA9UyVWAupxkZtuggYzC8UShz05mprRKhwwSHmiyQy0JafFZKlxrN4MhSZTkgSFKgIHUbWcpyZD1%2Bth2cpcgjUSHQCN4wWVCnLkujeeCIbG2U0gnhfF1tn8DK6UAEDL0pmCnkCAkFAEkYSBrHrvcmGSsVOotDpF0cwnw6hABMG4Vb-ratw7zAyAZ4OGIYfJAwTtJ0ZiSLsOChDGLwJGuwAomOJDHlAVKtOE5iwEWyBQP0YAJPe2j4d2ODmCAqR7OR3i%2BAEQTkdRODkeMeieMc5HfjacGmOROSmP4LimAgOC%2BEMrSLpI5gGHxczkeOaqXj60SxGW6iklOzhWMuiLItAbR7uiDFYs42oeFaf4tpIFgmr8P58Xa-5YRwSxIE6aIQAAHsi2wQAy6DbGkNgds8-adGcACkAAs1DcmyrgDtFzBKNyXJJZFpxRZQTrsu%2BKCuW5yAqBkSKSLwYBCAyeb2cB6R8SkQgIFuQiQGcFxXGYljWHc45Up1hh3FSI0PE8mx1P4aSDiGejcP4%2BCIaYIDEn%2B4ZesBjrkTIECorYtg4ESiR4P4KCwEgagCAIniwByHInWdVKEcRawPlSgTmByZgcjQHLxhAX03NYmGXZoYA8uxnEWC1pYJAgmkSuSLUtmoCA%2BC1lGRGJon0ZiQRQK06C2Hw6rQJgxUXVdN0wHdlidCADQDf4mgcs9JHrEIrNEezD4cuJzbQAA-P0AC8xEKmAUWpTllCxdQADUOUAByBPL-hQcA8sI1AOUAJzy1Y8u44xeAy-L5GXddt33admFs692jvcAn3fb9-2Az10BUqD4OQ8cMPqXDCMVpkyPqGjUAY%2BYWNWLUGImwTHAcdsh1yaEeFucWSBIiihD26RQhFlgvBhjMSAADxIJQVLUFSrBF78eLWMAAByBmEMnrQ4Jo3jpLIfDcIdNhbikAggJ4diutREBdz3ZIyP9hAAGxSYIlFp6YC%2BBPmYgcEFh7nQAjIf4gouE1bk1gORWAQXgDEMIwcPghB0AAQgAmmQEKcSAcgyIqlAlAAC9-BCjICQAQh8ABqrRkhQDUIQZgAAtAAsuYMgmgFDMG4Iqd%2B789wQAABK2EVAAEWAKQqBpgyBChILrNQAApCAio6DAGYN5WwUBX5yAOgAcSXonbAWZTCEBPlgUA0hWhcAEJfbAPBoKyI4FAfw1EUD5guFSMA-haT5w5kWV4Ah1CKOwMgdAWZvKEAAORUgAFS6Lej5QqShnYgBRGEMgkZujEBUWAYIQk5TeEyDYYAtgUCHwAOzMCVkgccdh6h%2BjWo6GxligA) or run it against your logs [here](https://github.com/prequel-dev/preq).
