### ISSUE TITLE
override  join_transaction_mode if engine_connect leaves the transaction open

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#11163] opened 2024-03-15 15:19 UTC
### Describe the bug

I'm migrating our codebase to SQLAlchemy 2.0. After enabling `future=True`, I observed that sessions were being rolled back when `session.commit()` is called.

I've minimised the problem to an example that reproduces on SQLAlchemy 1.4 and 2.0.

### SQLAlchemy Version in Use

1.4.52, 2.0.28

### DBAPI (i.e. the database driver)

appears to be any but psycopg2 and whatever sqlite:// uses by default

### Database Vendor and Major Version

PostgreSQL 12, 14

### Python Version

3.10

### Operating system

Linux, macOS

### To Reproduce

```python
from sqlalchemy import Column, Integer, MetaData, Table, create_engine, event, text
from sqlalchemy.orm import Session

metadata = MetaData()

foo = Table("foo", metadata, Column("id", Integer, primary_key=True))

engine = create_engine("sqlite:///:memory:", echo=True, future=True)

foo.create(bind=engine)


@event.listens_for(engine, "engine_connect")
def on_engine_connect(connection, branch):
    """If this event handler executes any SQL, the later session.commit()
    emits ROLLBACK instead of COMMIT.
    """
    connection.execute(text("SELECT 42"))


session = Session(bind=engine, future=True)
session.execute(foo.insert())
session.commit()  # Does not commit!
```

### Error

The log output below shows a `ROLLBACK` instead of the expected `COMMIT`.

```
2024-03-15 15:43:27,688 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-15 15:43:27,689 INFO sqlalchemy.engine.Engine 
CREATE TABLE foo (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2024-03-15 15:43:27,689 INFO sqlalchemy.engine.Engine [no key 0.00015s] ()
2024-03-15 15:43:27,690 INFO sqlalchemy.engine.Engine COMMIT
2024-03-15 15:43:27,691 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-15 15:43:27,691 INFO sqlalchemy.engine.Engine SELECT 42
2024-03-15 15:43:27,691 INFO sqlalchemy.engine.Engine [generated in 0.00018s] ()
2024-03-15 15:43:27,692 INFO sqlalchemy.engine.Engine INSERT INTO foo DEFAULT VALUES
2024-03-15 15:43:27,692 INFO sqlalchemy.engine.Engine [generated in 0.00009s] ()
2024-03-15 15:43:27,692 INFO sqlalchemy.engine.Engine ROLLBACK
``` 

### Additional context

I think I understand that the transaction changes in SQLAlchemy 2 is the cause. I was able to change our code to use a different event instead so I don't need a solution, but I feel like this interaction is extremely non-obvious and maybe the events need documentation about managing transactions which may affect the session.

**Comment by zzzeek** [comment] 2024-03-15 15:24
the Session's handling of a connection is determined by the [join_transaction_mode](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.params.join_transaction_mode) setting, which defaults to `"conditional_savepoint"`.  This means if the `Session` is handed a `Connection` that's already in a transaction, it assumes you are controlling that transaction externally.

So to have the `Session` not use that mode here, options are either make sure `Connection` is not in a transaction:

```py
@event.listens_for(engine, "engine_connect")
def on_engine_connect(connection, branch):
    """If this event handler executes any SQL, the later session.commit()
    emits ROLLBACK instead of COMMIT.
    """
    connection.execute(text("SELECT 42"))
    connection.rollback()

```

or set join transaction to control_fully:

```
session = Session(bind=engine, future=True, join_transaction_mode="control_fully")
session.execute(foo.insert())
session.commit()
```

im not sure where would be the best place to add a note for this.

**Comment by RazerM** [comment] 2024-03-15 15:32
I did try both of the snippets you show when sussing out it was the SQLAlchemy 2 transaction changes. It's worth noting that `join_transaction_mode`'s docs say "when a given bind is a Connection" — the bind here is an engine.

**Comment by zzzeek** [comment] 2024-03-15 15:35
overall I think we need a note on "engine_connect" that starting a transaction inside the event changes the expected behavior of the engine if that transaction is left open

**Comment by sqla-tester** [comment] 2024-03-15 18:15
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve docs wrt transactions and event with session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5228

**Comment by sqla-tester** [comment] 2024-03-18 20:29
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Improve docs wrt transactions and event with session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5231

**Closed** 2024-06-28 16:29 UTC
Labels: orm

**Comment by Cheaterman** [comment] 2024-08-05 20:13
Hi! This is a pretty neat feature, however the warning breaks my CI because I use -Werror on pytest and I run my tests in nested transactions to allow easy rollback on test failure. I tried to use warnings.filterwarnings() to filter it out, but no success yet.

**Comment by zzzeek** [comment] 2024-08-05 20:23
this would be specific to how you are getting the warning, adjust your engine_connect event handler and/or change the join_transaction mode

**Comment by Cheaterman** [comment] 2024-08-05 20:38
Hi @zzzeek and thanks a lot for your very quick answer! Sadly we aren't using engine_connect event (at least not directly, but we use Flask-SQLAlchemy which might?). `join_transaction` mode change sounds like a good idea, although I'm curious why warnings.filterwarning() didn't work :-)

**Comment by zzzeek** [comment] 2024-08-05 20:42
well that would be a bug in flask-sqlalchemy then, I'd report it there, however, seems like we might need to understand how you are getting this warning just to be sure.

@CaselIT the warning seems to be causing problems

**Comment by CaselIT** [comment] 2024-08-05 20:50
> @CaselIT the warning seems to be causing problems

well the jury is still out here. Let's see if it's doing its job or if there is a case that wasn't considered

@Cheaterman can you create a reproducing example? without it there isn't much to work on this side

**Comment by Cheaterman** [comment] 2024-08-05 21:02
Hi @CaselIT and thanks for your answer!

Sadly I currently don't have a lot of time to make a MCVE, but at least here's the relevant Pytest fixture that should help easily trigger the bug:

```py
@pytest.fixture(scope='session')
def db(app: Flask) -> collections.abc.Generator[SQLAlchemy, None, None]:
    with app.app_context():
        engine = db_.engine
        session = db_.session

        with engine.connect() as connection:
            transaction = connection.begin()
            engine.connect, connect = (  # type: ignore
                lambda: connection,
                engine.connect,
            )
            connection.close, close = (  # type: ignore
                lambda: None,
                connection.close,
            )
            session.commit, commit = (  # type: ignore
                session.flush,
                session.commit,
            )
            flask_migrate.upgrade()
            yield db_
            transaction.rollback()
            engine.connect = connect  # type: ignore
            connection.close = close  # type: ignore
            session.commit = commit  # type: ignore
```

**Comment by CaselIT** [comment] 2024-08-05 21:18
that's not a bug, it's what the warning was added for. you are providing a connection that is in a transaction, ant the warning is telling you to that the session will not normally do what you expect. In this case it's fine since that's what you want in the test.

to silence the warning set `join_transaction_mode = "rollback_only"`

**Comment by zzzeek** [comment] 2024-08-05 21:19
that code would be much better if you didnt use monkeypatching

see https://docs.sqlalchemy.org/en/20/orm/session_transaction.html#joining-a-session-into-an-external-transaction-such-as-for-test-suites and https://alembic.sqlalchemy.org/en/latest/cookbook.html#sharing-a-connection-across-one-or-more-programmatic-migration-commands for ORM/alembic patterns to inject a connection that's already in a transaction into an application

**Comment by Cheaterman** [comment] 2024-08-05 23:18
Hi again and thanks for all the great advice!

I managed to make it work this way:
```py
@pytest.fixture(scope='session')
def db(app: Flask) -> collections.abc.Generator[SQLAlchemy, None, None]:
    with app.app_context():
        engine = db_.engine
        connection = engine.connect()
        transaction = connection.begin()
        # pylint: disable=protected-access
        db_.session = db_._make_scoped_session({
            'bind': transaction,
            'join_transaction_mode': 'create_savepoint',
        })
        db_.session.commit = db_.session.flush  # type: ignore
        flask_migrate.upgrade()
        try:
            yield db_
        finally:
            transaction.rollback()
```

However this doesn't entirely get rid of the monkey patching since committing seems to close the transaction... Suggestions welcome :-) otherwise this at least works so the issue is more or less solved!

**Comment by CaselIT** [comment] 2024-08-06 06:16
Don't oass the transaction as bind, pass the connection. That will make this like `        db_.session.commit = db_.session.flush  # type: ignore` superfluous

**Comment by Cheaterman** [comment] 2024-08-07 12:24
Hi @CaselIT and thanks again for your answer! Unfortunately that's what I tried at first, but I get the following failure:
```
FAILED tests/test_contact.py::test_at_least_one_id - sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Please complete the context manager before emitting further commands.
ERROR tests/test_contact.py::test_at_least_one_id - sqlalchemy.exc.ResourceClosedError: This transaction is closed
```

**Comment by CaselIT** [comment] 2024-08-07 16:35
Without an example there isn't much to go on.

See https://github.com/sqlalchemy/sqlalchemy/issues/11163#issuecomment-2269938518 for the supported way of doing this
