### ISSUE TITLE
failure mode is premature for INSERT that returns NULL when using server generated PKs, regression from 1.3

### ISSUE THREAD

**Issue by akeeman** [sqlalchemy/sqlalchemy#7594] opened 2022-01-21 14:01 UTC
### Describe the bug

When a pg before insert trigger causes an insert to be skipped (i.e. returns NULL instead of a record) there is no returning record. If a table has a primary key with server default (e.g. auto increment), and no value is set for that column then an exception will be thrown when the record insert is persisted.

From the 1.4 branch:
In the following snipped `primary_key` will be `None`. Therefore `zip` will raise a `TypeError` ("'NoneType' object is not iterable").
https://github.com/sqlalchemy/sqlalchemy/blob/ab42b0e3d98386c8a13edea3206ef43f018de3b6/lib/sqlalchemy/orm/persistence.py#L1227-L1236

From the 1.3 branch:
In 1.3 this is not a problem, as the code will not run.
https://github.com/sqlalchemy/sqlalchemy/blob/57f324deaf261400d67b07eda114ebc744d47763/lib/sqlalchemy/orm/persistence.py#L1139-L1150

### To Reproduce

```python
from sqlalchemy import DDL, Column, Integer, event
from sqlalchemy.engine import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()

# the trigger function that always skips the insert itself
fn_ddl = DDL(
    """\
CREATE OR REPLACE FUNCTION the_trigger()
RETURNS TRIGGER AS $the_trigger$
BEGIN
RETURN NULL;
END;
$the_trigger$ LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
PARALLEL SAFE
COST 1;
"""
)
event.listen(Base.metadata, "before_create", fn_ddl)

# the entity with a pk col that has a server default value
# (auto incrementing id)
class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)


# run the trigger function before insert
trig_ddl = DDL(
    """\
CREATE TRIGGER a_trigger BEFORE INSERT
ON a
FOR EACH ROW EXECUTE PROCEDURE
the_trigger();
"""
)
event.listen(A.__table__, "after_create")

# perform an insert action
dsn = "postgresql://user:password@localhost:5432/test"
engine = create_engine(dsn, echo=True)
Base.metadata.create_all(engine)
session = Session(engine)
try:
    session.add(A())
    session.commit()
finally:
    session.close()
```

### Error

```
/path/to/venv/bin/python /path/to/file.py
2022-01-21 14:36:44,934 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-01-21 14:36:44,934 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-01-21 14:36:44,935 INFO sqlalchemy.engine.Engine select current_schema()
2022-01-21 14:36:44,935 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-01-21 14:36:44,936 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-01-21 14:36:44,936 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-01-21 14:36:44,938 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-01-21 14:36:44,938 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-01-21 14:36:44,938 INFO sqlalchemy.engine.Engine [generated in 0.00019s] {'name': 'a'}
2022-01-21 14:36:44,940 INFO sqlalchemy.engine.Engine CREATE OR REPLACE FUNCTION the_trigger()
RETURNS TRIGGER AS $the_trigger$
BEGIN
RETURN NULL;
END;
$the_trigger$ LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
PARALLEL SAFE
COST 1;

2022-01-21 14:36:44,940 INFO sqlalchemy.engine.Engine [no key 0.00011s] {}
2022-01-21 14:36:44,943 INFO sqlalchemy.engine.Engine COMMIT
2022-01-21 14:36:44,948 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-01-21 14:36:44,950 INFO sqlalchemy.engine.Engine INSERT INTO a (value) VALUES (%(value)s) RETURNING a.id
2022-01-21 14:36:44,950 INFO sqlalchemy.engine.Engine [generated in 0.00022s] {'value': 'foo'}
2022-01-21 14:36:44,952 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/path/to/file.py", line 52, in <module>
    session.commit()
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/path/to/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1228, in _emit_insert_statements
    for pk, col in zip(
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1
```

### Versions

- OS: linux (applicable to any)
- Python: 3.8.10 (applicable to any)
- SQLAlchemy: 1.4.31 (applicable to 1.4.x)
- Database: postgresql 12.3 (applicable to any)
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg (applicable to any)

**Comment by zzzeek** [comment] 2022-01-21 14:51
hey there-

the above code will raise an exception in 1.3 also, just the more correct one.   Is the bug reported here that the correct error message is not raised and it fails ahead of time?  we can fix that part.    it's not clear if you're saying the issue is that an exception is raised at all and you want this case to be supported, which it isnt.

**Comment by sqla-tester** [comment] 2022-01-21 15:28
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Skip PK returned as None for RETURNING, server side default** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3553

**Comment by sqla-tester** [comment] 2022-01-21 15:29
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**Skip PK returned as None for RETURNING, server side default** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3554

**Comment by zzzeek** [comment] 2022-01-21 18:51
I actually think this needs to raise a new exception, because in the case that we inserted many rows at once, we need to stop way sooner.   So the behavior you're looking for, we can't do that at all, unless you can be more specific what it is you're actually trying to do as the test program you put up returns an error in any case.  I'm guessing you're actually using the bulk insert stuff.  supporting that can be a separate issue, that's never been supported.

**Closed** 2022-01-22 14:33 UTC
Labels: bug, orm, unit of work
