### ISSUE TITLE
Broken joinedload with `pyodbc mssql` dialect with offset=0

### ISSUE THREAD

**Issue by gbmarc1** [sqlalchemy/sqlalchemy#6163] opened 2021-03-30 18:06 UTC
**Describe the bug**

I have the following query that works in sqlalchemy<1.4.0 both in the mssql dialect and the sqlite dialect. Since 1.4.0, mssql generated query is broken. SQLite is fine. The query is broken specifically in `mssql` when `offset==0`.

```py

offset = 0
limit = None
project_id = 1

target_paths = (
    session.query(TargetPathDb)
    .options(joinedload("target_path_links"), joinedload("tags"))
    .filter(TargetPathDb.project_id == project_id)
    .order_by(TargetPathDb.id)
    .offset(offset)
    .limit(limit)
    .all()
)
```

**Expected behavior**
Should work even when `offset==0`.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

**Error**

```
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. (102) (SQLExecDirectW)")
[SQL: 
SELECT anon_1.target_path_target_path_id AS anon_1_target_path_target_path_id, 
  anon_1.target_path_caption AS anon_1_target_path_caption, 
  anon_1.target_path_description AS anon_1_target_path_description, 
  anon_1.target_path_created AS anon_1_target_path_created, 
  anon_1.target_path_expired AS anon_1_target_path_expired, 
  anon_1.target_path_project_id AS anon_1_target_path_project_id, 
  target_path_tag_1.target_path_tag_id AS target_path_tag_1_target_path_tag_id,
  target_path_tag_1.target_path_id AS target_path_tag_1_target_path_id, 
  target_path_tag_1.[key] AS target_path_tag_1_key,
  target_path_tag_1.value AS target_path_tag_1_value,
  target_path_link_1.target_path_link_id AS target_path_link_1_target_path_link_id, 
  target_path_link_1.target_path_id AS target_path_link_1_target_path_id, 
  target_path_link_1.graph_target_edge_id AS target_path_link_1_graph_target_edge_id
FROM (
  SELECT target_path.target_path_id AS target_path_target_path_id, 
    target_path.caption AS target_path_caption, 
    target_path.description AS target_path_description,
    target_path.created AS target_path_created, target_path.expired AS target_path_expired, 
    target_path.project_id AS target_path_project_id
  FROM target_path WHERE target_path.project_id = ? OFFSET ? ROWS
) AS anon_1
LEFT OUTER JOIN target_path_tag AS target_path_tag_1 ON anon_1.target_path_target_path_id = target_path_tag_1.target_path_id 
LEFT OUTER JOIN target_path_link AS target_path_link_1 ON anon_1.target_path_target_path_id = target_path_link_1.target_path_id 
ORDER BY anon_1.target_path_target_path_id, target_path_link_1.target_path_link_id
]
[parameters: (1, 0)]

```

**Versions.**
 - OS: ubuntu 20.04
 - Python: >3.7
 - SQLAlchemy:   >1.4.0
 - Database: mssql 
 - DBAPI: pyodbc

Should the db dialect replace the offset by `None` when it is 0?

**Have a nice day!**

**Comment by CaselIT** [comment] 2021-03-30 18:57
Hi,

The correct query in that case is to remove the offset? or there is a different word to be used?
Do you by any change have also the query produced in 1.3?

**Comment by CaselIT** [comment] 2021-03-30 18:59
Other question.

Is the inner query fine by it's own?
```sql
SELECT target_path.target_path_id AS target_path_target_path_id, 
    target_path.caption AS target_path_caption, 
    target_path.description AS target_path_description,
    target_path.created AS target_path_created, target_path.expired AS target_path_expired, 
    target_path.project_id AS target_path_project_id
  FROM target_path WHERE target_path.project_id = ? OFFSET ? ROWS
```

**Comment by gbmarc1** [comment] 2021-03-30 19:34
> ```sql
> SELECT target_path.target_path_id AS target_path_target_path_id, 
>     target_path.caption AS target_path_caption, 
>     target_path.description AS target_path_description,
>     target_path.created AS target_path_created, target_path.expired AS target_path_expired, 
>     target_path.project_id AS target_path_project_id
>   FROM target_path WHERE target_path.project_id = 42 OFFSET 0 ROWS
> ```

This is the query that is invalid. I get the following error message.

Msg 102, Level 15, State 1, Line 6
Incorrect syntax near 'OFFSET'.

**Comment by gbmarc1** [comment] 2021-03-30 20:01
Generate by 1.3 if offset>0

```
SELECT anon_1.target_path_id,
	anon_1.caption,
	anon_1.description,
	anon_1.created,
	anon_1.expired,
	anon_1.project_id,
	target_path_tag_1.target_path_tag_id,
	target_path_tag_1.target_path_id,
	target_path_tag_1.[key],
	target_path_tag_1.value,
	target_path_link_1.target_path_link_id,
	target_path_link_1.target_path_id,
	target_path_link_1.graph_target_edge_id
FROM (
	SELECT anon_2.target_path_id AS target_path_id,
		anon_2.caption AS caption,
		anon_2.description AS description,
		anon_2.created AS created,
		anon_2.expired AS expired,
		anon_2.project_id AS project_id
	FROM (
		SELECT target_path.target_path_id AS target_path_id,
		target_path.caption AS caption,
		target_path.description AS description,
		target_path.created AS created,
		target_path.expired AS expired,
		target_path.project_id AS project_id,
		ROW_NUMBER() 
		OVER (
			ORDER BY target_path.target_path_id) AS mssql_rn FROM target_path
			WHERE target_path.project_id = ?
		) AS anon_2
		WHERE mssql_rn > ?
) AS anon_1 
LEFT OUTER JOIN target_path_tag AS target_path_tag_1 ON anon_1.target_path_id = target_path_tag_1.target_path_id 
LEFT OUTER JOIN target_path_link AS target_path_link_1 ON anon_1.target_path_id = target_path_link_1.target_path_id 
ORDER BY anon_1.target_path_id, target_path_link_1.target_path_link_id
```
By 1.4:
```
SELECT anon_1.target_path_id,
	anon_1.caption,
	anon_1.description,
	anon_1.created,
	anon_1.expired,
	anon_1.project_id,
	target_path_tag_1.target_path_tag_id,
	target_path_tag_1.target_path_id AS target_path_id_1,
	target_path_tag_1.[key],
	target_path_tag_1.value,
	target_path_link_1.target_path_link_id,
	target_path_link_1.target_path_id AS target_path_id_2,
	target_path_link_1.graph_target_edge_id
FROM (
	SELECT target_path.target_path_id AS target_path_id,
	target_path.caption AS caption,
	target_path.description AS description,
	target_path.created AS created,
	target_path.expired AS expired,
	target_path.project_id AS project_id
	FROM target_path
	WHERE target_path.project_id = ?
	ORDER BY target_path.target_path_id OFFSET ? ROWS
) AS anon_1 
LEFT OUTER JOIN target_path_tag AS target_path_tag_1 ON anon_1.target_path_id = target_path_tag_1.target_path_id 
LEFT OUTER JOIN target_path_link AS target_path_link_1 ON anon_1.target_path_id = target_path_link_1.target_path_id 
ORDER BY anon_1.target_path_id, target_path_link_1.target_path_link_id
```

Note that if I replace ? by `0` or by `1` in the query of `1.4` it works. Note that the `ORDER BY` is not present in the query generated by sqlalchemy>=1.4.0 which yields an invalid query.
I believe it would be more efficient to use the query for `offset=None` instead of the current query (OFFSET=1) for `offset=0`. It yields the same result.

**Comment by gbmarc1** [comment] 2021-03-30 20:04
offset=None for 1.4
```
SELECT target_path.target_path_id,
target_path.caption,
target_path.description,
target_path.created,
target_path.expired,
target_path.project_id,
target_path_tag_1.target_path_tag_id,
target_path_tag_1.target_path_id AS target_path_id_1,
target_path_tag_1.[key],
target_path_tag_1.value,
target_path_link_1.target_path_link_id,
target_path_link_1.target_path_id AS target_path_id_2,
target_path_link_1.graph_target_edge_id
FROM target_path 
LEFT OUTER JOIN target_path_tag AS target_path_tag_1 ON target_path.target_path_id = target_path_tag_1.target_path_id 
LEFT OUTER JOIN target_path_link AS target_path_link_1 ON target_path.target_path_id = target_path_link_1.target_path_id
WHERE target_path.project_id = ? ORDER BY target_path.target_path_id, target_path_link_1.target_path_link_id
```

**Comment by gbmarc1** [comment] 2021-03-30 20:08
> Thanks for the test.
> I think the bug is that the order by is removed when offset 0. I would guess we are using an `if offset` instead of `if offset is not None`.
> 
> Support for fetch/offset is new in 1.4 so thanks for taking the time to provide some examples.
> 
> Just to confirm, this query is correct:
> 
> ```sql
> SELECT target_path.target_path_id AS target_path_id,
> 	target_path.caption AS caption,
> 	target_path.description AS description,
> 	target_path.created AS created,
> 	target_path.expired AS expired,
> 	target_path.project_id AS project_id
> 	FROM target_path
> 	WHERE target_path.project_id = 42
> 	ORDER BY target_path.target_path_id OFFSET 0 ROWS
> ```

Yes the query is indeed correct.

**Comment by gbmarc1** [comment] 2021-03-30 20:21
I just found that there is an odd behaviour. It seems there is a cache somewhere. So depending on the order of the query, it can work of not. So,

Scenario 1:
1. offset=0  -> invalid query
2. offset=1 -> invalid query

Scenario 2:
1. offset=1 -> valid query
2. offset=0 -> valid query

Are the queries cached somewhere?

**Comment by CaselIT** [comment] 2021-03-30 20:29
> I believe it would be more efficient to use the query for offset=None instead of the current query (OFFSET=1) for offset=0. It yields the same result.

while I agree, in general in sqlalchemy we try to do what the user specifies: so we will try to honor `.offset(0)` if it was specified by the user, since in some cases omitting it may not be the desired outcome.
You can omit it by simply doing `offset(offset if offset else None)`

> I just found that there is an odd behaviour. It seems there is a cache somewhere. So depending on the order of the query, it can work or not. So,

yes, there is a query cache in sqlalchemy 1.4, so if the first query is invalid subsequent ones will also be. you can disable it for now.
see https://docs.sqlalchemy.org/en/14/core/connections.html#sql-caching but I would use `offset(offset if offset else None)` until this is fixed

**Comment by sqla-tester** [comment] 2021-03-30 21:15
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fixed MSSQL ``offset=0`` regression in subquery** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2694

**Closed** 2021-04-01 14:33 UTC
Labels: SQL Server, bug, regression, sql
