### ISSUE TITLE
SqlAlchemy wrongly passes on args instead of *args to python logger

### ISSUE THREAD

**Issue by pcotteadvestis** [sqlalchemy/sqlalchemy#5951] opened 2021-02-17 08:40 UTC
**Describe the bug**

In file sqlalchemy/log.py in method log() :

```py
def log(self, level, msg, *args, **kwargs):
        """Delegate a log call to the underlying logger.

        The level here is determined by the echo
        flag as well as that of the underlying logger, and
        logger._log() is called directly.

        """

        # inline the logic from isEnabledFor(),
        # getEffectiveLevel(), to avoid overhead.

        if self.logger.manager.disable >= level:
            return

        selected_level = self._echo_map[self.echo]
        if selected_level == logging.NOTSET:
            selected_level = self.logger.getEffectiveLevel()

        if level >= selected_level:
            self.logger._log(level, msg, args, **kwargs)   <------
```

I believe the very last line here should be
```py
self.logger._log(level, msg, *args, **kwargs)
```
(with the * before args)

Indeed, if not, an attempt to overload python's logger could fail when *args is empty, for instead of passing no arguments to self.logger._log the last line will pass an empty tuple, which will not be converted to string while formatting, ending up with 

**Error**

```
...
CRITICAL in logger - 02/17 09:18:46   File "/home/pcotte/Documents/venvs/AdUtils/lib/python3.8/site-packages/sqlalchemy/log.py", line 110, in info
CRITICAL in logger - 02/17 09:18:46     self.log(logging.INFO, msg, *args, **kwargs)
CRITICAL in logger - 02/17 09:18:46   File "/home/pcotte/Documents/venvs/AdUtils/lib/python3.8/site-packages/sqlalchemy/log.py", line 156, in log
CRITICAL in logger - 02/17 09:18:46     self.logger._log(level, msg, args, **kwargs)
CRITICAL in logger - 02/17 09:18:46   File "/home/pcotte/Documents/git/AdUtils/adutils/python/logger.py", line 250, in _log
CRITICAL in logger - 02/17 09:18:46     logger.log(level, _msg, *args, **kwargs)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 1508, in log
CRITICAL in logger - 02/17 09:18:46     self._log(level, msg, args, **kwargs)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 1585, in _log
CRITICAL in logger - 02/17 09:18:46     self.handle(record)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 1595, in handle
CRITICAL in logger - 02/17 09:18:46     self.callHandlers(record)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
CRITICAL in logger - 02/17 09:18:46     hdlr.handle(record)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
CRITICAL in logger - 02/17 09:18:46     self.emit(record)
CRITICAL in logger - 02/17 09:18:46   File "/home/pcotte/Documents/venvs/AdUtils/lib/python3.8/site-packages/google/cloud/logging/handlers/handlers.py", line 108, in emit
CRITICAL in logger - 02/17 09:18:46     message = super(CloudLoggingHandler, self).format(record)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
CRITICAL in logger - 02/17 09:18:46     return fmt.format(record)
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
CRITICAL in logger - 02/17 09:18:46     record.message = record.getMessage()
CRITICAL in logger - 02/17 09:18:46   File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
CRITICAL in logger - 02/17 09:18:46     msg = msg % self.args
CRITICAL in logger - 02/17 09:18:46 TypeError: not all arguments converted during string formatting
CRITICAL in logger - 02/17 09:18:46 
```

**Versions.**
 - OS: Ubuntu 18
 - Python: 3.8
 - SQLAlchemy: 1.3.23

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-02-17 16:27
> I believe the very last line here should be
> 
> ```python
> self.logger._log(level, msg, *args, **kwargs)
> ```
> 
> (with the * before args)
> 
> Indeed, if not, an attempt to overload python's logger could fail when *args is empty, for instead of passing no arguments to self.logger._log the last line will pass an empty tuple, which will not be converted to string while formatting, ending up with

Hey there -

you would best show this by demonstrating an [MCVE](http://stackoverflow.com/help/mcve).   The code is in fact correct:

```python

from sqlalchemy import create_engine
import logging

logging.basicConfig()


e = create_engine("sqlite://", echo="debug")

e.logger.info("%s %s", "hi", "there")
```
output:

```
$ python test3.py 
2021-02-17 11:22:06,857 INFO sqlalchemy.engine.base.Engine hi there
INFO:sqlalchemy.engine.base.Engine:hi there

```

now apply the "fix":

```diff
diff --git a/lib/sqlalchemy/log.py b/lib/sqlalchemy/log.py
index f103aeb86..7e6139c9a 100644
--- a/lib/sqlalchemy/log.py
+++ b/lib/sqlalchemy/log.py
@@ -153,7 +153,7 @@ class InstanceLogger(object):
             selected_level = self.logger.getEffectiveLevel()
 
         if level >= selected_level:
-            self.logger._log(level, msg, args, **kwargs)
+            self.logger._log(level, msg, *args, **kwargs)
 
     def isEnabledFor(self, level):
         """Is this logger enabled for level 'level'?"""

```

now run it, the program fails:

```
$ python test3.py 
--- Logging error ---
Traceback (most recent call last):
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "test3.py", line 9, in <module>
    e.logger.info("%s %s", "hi", "there")
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/log.py", line 110, in info
    self.log(logging.INFO, msg, *args, **kwargs)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/log.py", line 156, in log
    self.logger._log(level, msg, *args, **kwargs)
Message: '%s %s'
Arguments: hi
--- Logging error ---
Traceback (most recent call last):
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/python-3.8.3/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "test3.py", line 9, in <module>
    e.logger.info("%s %s", "hi", "there")
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/log.py", line 110, in info
    self.log(logging.INFO, msg, *args, **kwargs)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/log.py", line 156, in log
    self.logger._log(level, msg, *args, **kwargs)
Message: '%s %s'
Arguments: hi

```

The API being called is here: https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1585   .  args is not used with a star here.



> 
> **Error**
> 
> ```
> ...
> CRITICAL in logger - 02/17 09:18:46   File "/home/pcotte/Documents/venvs/AdUtils/lib/python3.8/site-packages/sqlalchemy/log.py", line 110, in info

Your error looks like you are passing more arguments than there are position holders in the string, but there's no way to tell without an [MCVE](http://stackoverflow.com/help/mcve).

**Comment by zzzeek** [comment] 2021-02-17 18:01
looks like the problem is likely in some internal logging library:

 File "/home/pcotte/Documents/git/AdUtils/adutils/python/logger.py", line 250, in _log
CRITICAL in logger - 02/17 09:18:46     logger.log(level, _msg, *args, **kwargs)

make sure your custom handler implements [Logger._log](https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1585) correctly, closing.

**Closed by zzzeek** 2021-02-17 18:01 UTC
Labels: cant reproduce, question
