### ISSUE TITLE
session is None when object is from cache

### ISSUE THREAD

**Issue by Rogalek** [sqlalchemy/sqlalchemy#6426] opened 2021-05-04 09:14 UTC
Hey,

After upgrading to a new version of sqlalchemy (from 1.3+ to 1.4+) I get an error for an object which I get from the cache. I am using dogpile.cache as my cache.

```
src/coma/models/event.py:762: in __json__
    in self.event_subtopics.all()]
/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2699: in all
    return self._iter().all()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.orm.dynamic.AppenderQuery object at 0x7feaba46b6d0>

    def _iter(self):
        # new style execution.
        params = self._params
    
        statement = self._statement_20()
>       result = self.session.execute(
            statement,
            params,
            execution_options={"_sa_orm_load_options": self.load_options},
        )
E       AttributeError: 'NoneType' object has no attribute 'execute'

/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py:2834: AttributeError

```

I have two models, which have a relationship.
```
class Topic(Base):
    __tablename__ = 'topics'

    id = Column(Integer, primary_key=True)
    name = Column(Unicode(length=256), nullable=False)
    sort = Column(Integer, nullable=True)

    def __init__(self, *args, **kwargs):
        self.name = kwargs.pop('name')
        self.sort = kwargs.pop('sort')

    def __json__(self, **kwargs):
        _json = super(Topic, self).__json__(**kwargs)
        subtopics = [i.__json__() for i in self.subtopics.all()]
        _json["subtopics"] = subtopics
        _json["sort"] = self.sort
        return _json


class Subtopic(Base):
    __tablename__ = 'subtopics'

    id = Column(Integer, primary_key=True)
    name = Column(Unicode(length=256), nullable=False)
    sort = Column(Integer, nullable=True)
    topic_id = Column(
        Integer, ForeignKey('topics.id', ondelete='cascade'),
        index=True, nullable=False)

    topic = relationship(
        "Topic", backref=backref("subtopics", lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        self.name = kwargs.pop('name')
        self.sort = kwargs.pop('sort')
        self.topic_id = kwargs.pop('topic_id')

    def __json__(self, **kwargs):
        _json = super(Subtopic, self).__json__(**kwargs)
        _json["sort"] = self.sort
        _json["topic_id"] = self.topic_id
        return _json
```

When I am calling my function `_json_` on cached objects I am getting the above error.
```
@region_1month.cache_on_arguments()
def all_topics():
    return session.query(Topic)\
        .order_by(Topic.sort.asc()).all()

topics = all_topics()
b = [topic.__json__() for topic in topics]
```

Thank you for your help.

**Versions**
 - OS: Ubuntu 20.04
 - Python: 3.8.0
 - SQLAlchemy: 1.4.13
 - dogpile.cache: 1.0.2
 - Database: postgres

**Comment by zzzeek** [comment] 2021-05-04 13:52
it looks like it is caching the "dynamic" appenderquery object.   that's not really supposed to be part of the object's state so im not sure how that's happening.


something seems to be going wrong but also I wonder why not use your `__json__()` method **inside** the cached function?  it's vastly simpler and cheaper to cache the json rather than the objects themselves.

**Comment by zzzeek** [comment] 2021-05-04 14:34
reproduces easy enough, no clue why yet

```python

import pickle

from sqlalchemy import Column, String
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import backref
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class Topic(Base):
    __tablename__ = "topics"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    sort = Column(Integer, nullable=True)


class Subtopic(Base):
    __tablename__ = "subtopics"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    sort = Column(Integer, nullable=True)
    topic_id = Column(
        Integer,
        ForeignKey("topics.id", ondelete="cascade"),
        index=True,
        nullable=False,
    )

    topic = relationship("Topic", backref=backref("subtopics", lazy="dynamic"))


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

session = Session(e)
session.add(
    Topic(
        name="t",
        sort=1,
        subtopics=[Subtopic(name="s1", sort=2), Subtopic(name="s2", sort=3)],
    )
)
session.commit()
session.close()


def all_topics():
    return session.query(Topic).order_by(Topic.sort.asc()).all()


# topics = all_topics()
tps = pickle.dumps(all_topics())
topics = pickle.loads(tps)
for t in topics:
    #    breakpoint()
    t.subtopics.all()

```

**Comment by zzzeek** [comment] 2021-05-04 14:37
oh.    well the objects you're un-caching aren't persistent, so the dynamic loader can't work.  in 1.3 it silently fails, which is also strange.    works if you re-add:

```python
tps = pickle.dumps(all_topics())
topics = pickle.loads(tps)
for t in topics:
    session.add(t)
    t.subtopics.all()

```

looks like legacy behavior in 1.3 is detached object, dynamic loader returns empty list, OK

```python
t = session.query(Topic).first()
session.expunge(t)
t.subtopics.all()

```

**Comment by zzzeek** [comment] 2021-05-04 14:43
so this is going to warn, because you shouldn't be calling upon `t.subtopics` when the object is detached, you should fix that.

**Comment by sqla-tester** [comment] 2021-05-04 15:25
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Restore detached object logic for dynamic, but warn** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2802

**Closed** 2021-05-04 17:36 UTC
Labels: bug, orm, regression
