### ISSUE TITLE
Eager loader overrides expired object that has been modified

### ISSUE THREAD

**Issue by ic4f** [sqlalchemy/sqlalchemy#6326] opened 2021-04-20 04:32 UTC
**Describe the bug**
This happens under 1.4.*, under very specific conditions:
- Setup: 
  - parent, child; parent has a `children` relationship which is ***eagerly loaded***
  - use ***classical mapping*** (declarative does *not* exhibit this behavior)
  - use ***`autocommit=True`***
- Steps:
  - add parent and child, flush
  - update child
  - access `parent.children`: this will override the previous update to child

I assume this is related to [this behavioral change in 1.4](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#eager-loaders-emit-during-unexpire-operations). Is this correct?

**Expected behavior**
Accessing `parent.children` should not override the value of `child.foo` (as happens under declarative mapping, and under 1.3.*).

**To Reproduce**

```python
from sqlalchemy import (
    create_engine,
    inspect,
    Column,
    ForeignKey,
    Integer,
    MetaData,
    Table,
)
from sqlalchemy.orm import (
    mapper,
    relation,
    sessionmaker,
)

metadata = MetaData()

class Parent:
    pass

class Child:
    pass

Parent.table = Table(
    'parent', metadata,
    Column('id', Integer, primary_key=True))

Child.table = Table(
    'child', metadata,
    Column('id', Integer, primary_key=True),
    Column('foo', Integer),
    Column('parent_id', Integer, ForeignKey('parent.id')),
)

mapper(Parent, Parent.table, properties=dict(
    children=relation(Child, backref='parent', lazy=False)))

mapper(Child, Child.table)

def run(session):
    p = Parent()
    c = Child()
    p.children.append(c)
    session.add(p)
    session.flush()

    c.foo = 42
    assert c.foo == 42
    assert c in session.dirty
    p.children
    assert c.foo == 42  # not anymore! Assertion error raised here.

engine = create_engine('sqlite:///:memory:', echo=True)
metadata.create_all(engine)

Session = sessionmaker(autoflush=False, autocommit=True, bind=engine)
session = Session()
run(session)
session.close()
```

**Error**
The error is verified by the last assert statement (`assert c.foo == 42`). Here's selected inspection data:
```python
# BEFORE accessing `parent.children`:
(Pdb) session.dirty
IdentitySet([<__main__.Child object at 0x7f4c221c32b0>])

(Pdb) inspect(parent).__dict__
 'expired': True,
 'expired_attributes': {'children', 'id'},

(Pdb) inspect(child).__dict__
 'committed_state': {'foo': symbol('NO_VALUE')},
 'expired': True,
 'expired_attributes': {'parent_id', 'parent', 'foo', 'id'},
 'modified': True,

(Pdb) child.__dict__
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f4c221c3280>, 'foo': 42}


# ISSUE STATEMENT `parent.children`:
(Pdb) parent.children
2021-04-19 23:49:13,384 INFO sqlalchemy.engine.Engine SELECT parent.id AS parent_id, child_1.id AS child_1_id, child_1.foo AS child_1_foo, child_1.parent_id AS child_1_parent_id 
FROM parent LEFT OUTER JOIN child AS child_1 ON parent.id = child_1.parent_id 
WHERE parent.id = ?
2021-04-19 23:49:13,384 INFO sqlalchemy.engine.Engine [generated in 0.00017s] (1,)
[<__main__.Child object at 0x7f4c221c32b0>]


# AFTER accessing `parent.children`:
(Pdb) session.dirty
IdentitySet([])

(Pdb) inspect(parent).__dict__
 'expired': False,
 'expired_attributes': set(),

(Pdb) pp inspect(child).__dict__
 'expired': False,
 'expired_attributes': set(),
  'modified': False,

(Pdb) child.__dict__
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f4c221c3280>,
 'foo': None,
 'id': 1,
 'parent_id': 1}
```
**Notable differences between classical and declarative**
Under declarative, before accessing `parent.children`:
- `foo` is not in `inspect(child).expired_attributes`
- `child` is not in `session.dirty`

**Versions.**
OS: Ubuntu 20.04.1 LTS
Python: 3.8.5
SQLAlchemy: 1.4.* (last tested under 1.4.9)
Database: SQLite (first observed under PostgreSQL)
DBAPI: default for SQLite, psycopg2 for PostgreSQL

**Comment by zzzeek** [comment] 2021-04-20 12:29
hey there -

have not tried this yet but immediately, you have a session with autocommit=True but not expire_on_commit=False.  This means every flush will **expire** everything in the session and is very unlikely to be useful.  this is likely the reason you are seeing something being overwritten.   The unexpire of an object now [emits eager loaders](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#eager-loaders-emit-during-unexpire-operations) so this looks similar to something I saw a few days ago.

I will try to actually run your example later and figure out the exact mechanics of what's happening, but it's very likely the two things above are involved.  

autocommit=True is going to be removed from SQLAlchemy within a year, so it might be worthwhile to modernize your application before even moving to 1.4 if setting expire_on_commit=False is not an option.

**Comment by zzzeek** [comment] 2021-04-20 15:23
OK bug has nothing to do with those things, this is additional regression due to #1763 , test case:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", lazy="joined")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e, autoflush=False)

b1 = B()
a1 = A(bs=[b1])
s.add(a1)
s.flush()

s.expire(a1)
b1.data = 'foo'

a1.bs
assert b1.data == 'foo'


```

refresh sets up populate_existing which is corrupting eagerly loaded elements, needs to be scaled back.

**Comment by sqla-tester** [comment] 2021-04-20 15:33
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Narrow refresh populate_existing to just refresh_state** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2762

**Comment by zzzeek** [comment] 2021-04-20 15:35
i will probably release 1.4.10 today thanks for reporting.   in your example, "Parent" gets expired due to session.flush() committing the transaction.

**Comment by ic4f** [comment] 2021-04-20 15:42
Thanks for the fast response! Yes, I assumed the eager loaders change was contributing to this (one key difference I noticed is that, unlike 1.3, which expired column-oriented attributes, 1.4 also expired *all relationship() attributes*. Manually removing the offending relationship attribute key from `expired_attributes` would prevent that relationship from eager loading on attribute access).

> autocommit=True is going to be removed from SQLAlchemy within a year, so it might be worthwhile to modernize your application before even moving to 1.4 if setting expire_on_commit=False is not an option.

Oh yes, we are modernizing and `autocommit=True` will go away. Thank you for the suggestion - our initial intent was to update that incrementally (on dev, not production), but now that you mention it, I suppose we may do this before even merging into dev. Thanks!

**Closed** 2021-04-20 17:01 UTC
Labels: bug, orm, regression
