### ISSUE TITLE
Postgres: add support for reflection of expression-based indexes

### ISSUE THREAD

**Issue by immerrr** [sqlalchemy/sqlalchemy#7442] opened 2021-12-12 09:14 UTC
### Describe the use case

We are using SQLAlchemy to work with Postgres DB that has full-text indexes (`to_tsvector` and so on), and whenever those need a change it is unfortunate that alembic is unable to generate the automated diff. One reason for that is that `postgres` dialect currently does not support reflecting expression-based indexes.

It is possible to live without autogenerated migrations, but we had cases when a schema change has been missed or a typo in the index expression slipped by.

### Databases / Backends / Drivers targeted

Postgres (any drivers)

### Example Use

Create table with an expression-based index

```sql
create table t123123 (x varchar, y varchar);
create index t123123idx_xlowery on t123123 ((x || lower(y)));
```

Reflect the index from the live table:
```python
import sqlalchemy as sa
engine = sa.create_engine('postgresql://scott:tiger@172.17.0.1:5432/test')
meta = sa.MetaData()
user_table = sa.Table('t123123', meta)
insp = sa.inspect(engine)
insp.reflect_table(user_table, None)

# Current implementation will fail on the next line, because t123123idx_xlowery index is not reflected
xlowery_idx = [i for i in user_table.indexes if i.name == 't123123idx_xlowery'][0]
print(str(sa.schema.CreateIndex(xlowery_idx).compile()))
# CREATE INDEX t123123idx_xlowery ON t123123 (CAST(x AS TEXT) || lower(CAST(y AS TEXT)))
```

### Additional context

Adding `pg_get_expr(ix.indexprs, ix.indrelid)` to the list of index metadata requested in  `sa.dialects.postgres.base.PGDialect.get_indexes` should be straightforward. Also, there are parsers for Postgres code (https://github.com/pganalyze/libpg_query and derivatives) that should make the process of converting Postgres code into SA expression objects easier.

**Comment by CaselIT** [comment] 2021-12-12 10:18
Hi,

We are currently re-writing the reflection logic for postgresql to allow multiple table reflection at once. See #4379 and the current wip at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3167

I've had a quick look at the PR and I'm not sure if parsing the returned value is something that's we should get into, since it seems to be a potential cause of hard to debug regressions.
What's the drawback of just keeping the text expression (I mean the value returned by `pg_get_expr`)?

**Comment by zzzeek** [comment] 2021-12-12 16:10
> 
> I've had a quick look at the PR and I'm not sure if parsing the returned value is something that's we should get into, since it seems to be a potential cause of hard to debug regressions. 

agree, I see that a SQL parser dependency was introduced there, that's not something we can do.   Any reflected SQL expressions should be placed as is into a text() construct the same way we do for CHECK constraints.

the concept of parsing SQL into SQLAlchemy Core expressions is certainly worthwhile for someone to look into if there were interest but that would need to be a third party library, not something we can get into on this end.

**Comment by immerrr** [comment] 2021-12-12 18:36
The original idea was to keep it as text without adding dependencies, but turns out it is not easy to separate multiple value expressions from `indexprs` field. They come as `pg_node_type` and i was unable to find a way to convert to an array-like: it is either converting the tree to string and parsing it as a parenthetical construct, or doing `pg_get_expr` and doing syntax-aware splitting by comma. Syntax-aware here means that commas that separate function args or those inside string literals should be ignored.

**Comment by zzzeek** [comment] 2021-12-12 19:06
I'd need to see what the query results look like and see if there's another way we can figure out the split between expressions.

**Comment by zzzeek** [comment] 2021-12-12 19:10
I would think there's a way to split the node tree form first, then pass that to pg_get_expr(), something like that.

i would also consider alternate forms of representing the index elements if PG gives us absolutely no way to split the expressions.    like "postgresql_index_expressions=text('...')" even.

**Comment by immerrr** [comment] 2021-12-12 19:56
Here's an example

```
-- for
create index t123123idx_lowerxlowery on t123123 (lower(x), (x || lower(y)));

-- result
indexprs        | ({FUNCEXPR :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 55} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}) :location 49} {OPEXPR :opno 654 :opfuncid 1258 :opresulttype 25 :opretset false :opcollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 60} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1} {FUNCEXPR :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 2 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 2 :location 71} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}) :location 65}) :location 62})
index_expr_text | lower((x)::text), ((x)::text || lower((y)::text))

```

`indexprs` is a bit long, but is basically a sequence of
`({FUNCEXPR ...} {OPEXPR ...})`
with two elements:
```
{FUNCEXPR
 :funcid 870
 :funcresulttype 25
 :funcretset false
 :funcvariadic false
 :funcformat 0
 :funccollid 100
 :inputcollid 100
 :args (
   {RELABELTYPE
    :arg {VAR
          :varno 1
          :varattno 1
          :vartype 1043
          :vartypmod -1
          :varcollid 100
          :varlevelsup 0
          :varnosyn 1
          :varattnosyn 1
          :location 55}
    :resulttype 25
    :resulttypmod -1
    :resultcollid 100
    :relabelformat 2
    :location -1}
 )
 :location 49}
```
and 
```
{OPEXPR
 :opno 654
 :opfuncid 1258
 :opresulttype 25
 :opretset false
 :opcollid 100
 :inputcollid 100
 :args (
   {RELABELTYPE
    :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 60}
    :resulttype 25
    :resulttypmod -1
    :resultcollid 100
    :relabelformat 2
    :location -1}
   {FUNCEXPR
    :funcid 870
    :funcresulttype 25
    :funcretset false
    :funcvariadic false
    :funcformat 0
    :funccollid 100
    :inputcollid 100
    :args (
      {RELABELTYPE
       :arg {VAR :varno 1 :varattno 2 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 2 :location 71}
       :resulttype 25
       :resulttypmod -1
       :resultcollid 100
       :relabelformat 2
       :location -1}
    )
    :location 65}
 )
 :location 62}
```

**Comment by immerrr** [comment] 2021-12-12 20:07
And here's an example with a string constant containing a comma:
```
create index t123123idx_lowerxbarlowery on t123123 ((lower(x) || 'foo, bar'), (x || lower(y)));
```

```
indexprs        | ({OPEXPR :opno 654 :opfuncid 1258 :opresulttype 25 :opretset false :opcollid 100 :inputcollid 100 :args ({FUNCEXPR :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 59} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}) :location 53} {CONST :consttype 25 :consttypmod -1 :constcollid 100 :constlen -1 :constbyval false :constisnull false :location 65 :constvalue 12 [ 48 0 0 0 102 111 111 44 32 98 97 114 ]}) :location 62} {OPEXPR :opno 654 :opfuncid 1258 :opresulttype 25 :opretset false :opcollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 79} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1} {FUNCEXPR :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 2 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 2 :location 90} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}) :location 84}) :location 81})
index_expr_text | (lower((x)::text) || 'foo, bar'::text), ((x)::text || lower((y)::text))
```

Slightly more readable variant of the node tree is below:
```
({OPEXPR
  :opno 654 :opfuncid 1258 :opresulttype 25 :opretset false :opcollid 100 :inputcollid 100
  :args ({FUNCEXPR
          :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100
          :args ({RELABELTYPE
                  :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 59}
                  :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1})
          :location 53}
         {CONST :consttype 25 :consttypmod -1 :constcollid 100 :constlen -1 :constbyval false :constisnull false :location 65
                :constvalue 12 [ 48 0 0 0 102 111 111 44 32 98 97 114 ]})
  :location 62}
 {OPEXPR
  :opno 654 :opfuncid 1258 :opresulttype 25 :opretset false :opcollid 100 :inputcollid 100
  :args ({RELABELTYPE
          :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 79}
          :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}
         {FUNCEXPR
          :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100
          :args ({RELABELTYPE
                  :arg {VAR :varno 1 :varattno 2 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 2 :location 90}
                  :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1})
          :location 84}) :location 81})
```

**Comment by immerrr** [comment] 2021-12-12 20:09
It is not impossible to parse these ASTs :point_up: , but there's a lot of implementation details there (functions and types are referenced by ids), and looks like Postgres does not let the user pass convert an arbitrary string to a `pg_node_tree` because of [a security restriction](https://www.postgresql.org/message-id/20595.1347653162%40sss.pgh.pa.us).

**Comment by zzzeek** [comment] 2021-12-12 20:15
OK so you wanted to get indexprs into an ARRAY, if that were possible then we could call the expr() function on each element right?  there really should be a way for that to happen.   i really dont want to parse anything on the python side here that can't be done with a simple regex

**Comment by immerrr** [comment] 2021-12-12 20:17
> i would also consider alternate forms of representing the index elements if PG gives us absolutely no way to split the expressions. like "postgresql_index_expressions=text('...')" even.

Interesting, but may be problematic because expressions and bare columns are returned in different ways, e.g.
```
create index t123123idx_xlowerxylowery on t123123 (x, lower(x), y, lower(y));
```

and here's what postgres returns:
```
relname         | t123123idx_xlowerxylowery
indisunique     | False
indexprs        | ({FUNCEXPR :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 1 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location 60} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}) :location 54} {FUNCEXPR :funcid 870 :funcresulttype 25 :funcretset false :funcvariadic false :funcformat 0 :funccollid 100 :inputcollid 100 :args ({RELABELTYPE :arg {VAR :varno 1 :varattno 2 :vartype 1043 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 2 :location 73} :resulttype 25 :resulttypmod -1 :resultcollid 100 :relabelformat 2 :location -1}) :location 67})
index_expr_text | lower((x)::text), lower((y)::text)
conrelid        | <null>
indkey          | 1 0 2 0
indoption       | 0 0 0 0
reloptions      | <null>
amname          | btree
pg_get_expr     | <null>
indnkeyatts     | 4
```

and `indkey` value of `1 0 2 0` means:
- take attribute by index `1` from the table
- take one element of `indexprs`
- take attribute by index `2` from the table
- take one element of `indexprs`

**Comment by zzzeek** [comment] 2021-12-12 20:21
parsing commas from index_expr_text is a matter of counting parenthesis, right?   what's the case where it's more complex than that ?

**Comment by zzzeek** [comment] 2021-12-12 20:22
parenthesis and possible quoted values.    symbols w/ () and '' is a simpler parsing problem than all of SQL.

**Comment by immerrr** [comment] 2021-12-12 20:25
> parsing commas from index_expr_text is a matter of counting parenthesis, right? what's the case where it's more complex than that ?

yeah, more or less. counting parenthesis and handling some escapes in string literals
```sql
select 
  'this string literal contains a backslash \\ and an apostrophe '' (alternative spelling: \')'
  'this string literal contains a backslash followed by an apostrophe: \\\' and continues afterwards'
```

**Comment by CaselIT** [comment] 2021-12-12 21:53
It seems that ` pg_get_indexdef ` format things a bit differently.
For example for `create index foo_idx on foo(lower(a), (a || lower(b)));`
- pg_get_expr returns `lower(a), (a || lower(b))`
- pg_get_indexdef  is instead `CREATE INDEX foo_idx ON public.foo USING btree (lower(a), ((a || lower(b))))`

it does not seem more or less useful for our task, you fyi.

Also maybe we could ask if the have suggestion on the pg mailing like?

**Comment by immerrr** [comment] 2021-12-14 10:42
`pg_get_indexdef` may work with the `postgresql_index_expressions=text('...')` idea as it returns columns interleaved with expressions without any extra parsing:
```
scott@172:test> select pg_get_indexdef('t123123idx_xlowerxylowery'::regclass, 0, true)
+------------------------------------------------------------------------------------------------------+
| pg_get_indexdef                                                                                      |
|------------------------------------------------------------------------------------------------------|
| CREATE INDEX t123123idx_xlowerxylowery ON t123123 USING btree (x, lower(x::text), y, lower(y::text)) |
+------------------------------------------------------------------------------------------------------+
```

**Comment by CaselIT** [comment] 2021-12-14 12:13
That's an option.

Sadly `pg_node_tree` does not seem an array like, so you cannot do `indexprs[0]` to get the first element of the index.
I'll try to ask in the pg mailing list if there is a way of doing that.

**Comment by zzzeek** [comment] 2021-12-14 12:59
I think a general routine to parse a line of generic code with quotes, commas, parenthesis into tokens is not too difficult to achieve within 20 lines or so that can be cythonized, we have a use for it already in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3369

**Comment by CaselIT** [comment] 2021-12-14 22:25
that's probably also an option

**Comment by aidos** [comment] 2022-01-16 23:34
I've just been looking into this myself. I noticed that when you describe the index in psql they give you each column name. After a little more digging it looks like you can extract as an array easily enough:

```
  ARRAY(
      SELECT pg_get_indexdef(ix.indexrelid, k + 1, true)
      FROM generate_subscripts(ix.indkey, 1) as k
      ORDER BY k
    ) as indkey_names,
```

I've got a more hairy case I'll need to support (`postgresql_ops`, `postgresql_using`, and I'm hoping to bend things from the outside to make it work for materialized views), but hopefully using this array technique we can get the expression support working for a start.

So the query from the PR becomes something like this:

```
SELECT
    t.oid,
    i.relname as relname,
    ix.indisunique,
    --ix.indexprs,
    pg_get_expr(ix.indexprs, ix.indrelid) as index_expr_text,
    ARRAY(
      SELECT pg_get_indexdef(ix.indexrelid, k + 1, true)
      FROM generate_subscripts(ix.indkey, 1) as k
      ORDER BY k
    ) as indkey_names,
    c.conrelid,
    attnames.attnames,
    ix.indkey::varchar as column_indexes,
    ix.indoption::varchar as column_options,
    i.reloptions,
    am.amname as access_method,
    pg_get_expr(ix.indpred, ix.indrelid),
    ix.indnkeyatts as indnkeyatts
FROM
    pg_class t
          join pg_index ix on t.oid = ix.indrelid
          join pg_class i on i.oid = ix.indexrelid
          cross join lateral (
             select array_agg(a.attname) as attnames
             from unnest(ix.indkey) as t1(one_indkey)
             left outer join pg_attribute a on (
               t.oid = a.attrelid
               and a.attnum = t1.one_indkey
             )
          ) as attnames
          left outer join
              pg_constraint c
              on (ix.indrelid = c.conrelid and
                  ix.indexrelid = c.conindid and
                  c.contype in ('p', 'u', 'x'))
          left outer join
              pg_am am
              on i.relam = am.oid
WHERE
    t.relkind IN ('r', 'v', 'f', 'm', 'p')
    and ix.indisprimary = 'f'
    and t.oid = :table_oid
ORDER BY
    t.relname,
    i.relname
```

**Comment by aidos** [comment] 2022-01-17 18:34
Great! I took a look at the multi reflection code - all looked simple enough to follow. If it wanted to hack on this, what’s the best place to branch from?

Also, I’ve been through the alembic autogen and it looks like there’s a bit more to be added there (eg, _make_index isn’t honouring all the properties like postgresql_using etc, and the signature comparison code is equally lossy).

Again, none of it looks too onerous, but there’s probably a discussion to be had around comparing the reflected text version of the index vs the one from local metadata as I’m not 100% sue of the best approach. There’s an extreme angle where you treat the sql string of the index create operation as the whole signature, but I’ll assume that’s frowned upon.

**Comment by CaselIT** [comment] 2022-01-17 20:12
> Great! I took a look at the multi reflection code - all looked simple enough to follow. If it wanted to hack on this, what’s the best place to branch from?

In brief the wordflow with gerrit would be to checkout the current patch and create a new commit on top of it. It takes a bit getting used to it, The easiest way is probably to check this python utility package https://pypi.org/project/git-review/

**Comment by CaselIT** [comment] 2022-06-21 19:11
sorry for the delay, multi reflection was merged last week. I'll take another look at this in the coming weeks to have this for v2.

**Comment by CaselIT** [comment] 2022-06-29 19:41
@zzzeek how should be the expression "columns" reflected? should they be inserted into `column_names` as normal columns?
Then how should they be distinguished compared to normal columns? 

Here there are various option, probably the most backward compatible could be to have a companion `column_is_exp: NotRequired[List[bool]]` that indicates if the i-th element in `column_names` is an expression or not. (`include_columns` would get a similar companion list)

Another alternative is to return a `sa.text` instance for expression "columns", but it seems strange.

Other options are less backward compatible. Probably the best option if starting from scratch would be to make `column_names` a list of 
```py
class ColumnSpec(TypeDict):
  text: str
  is_expression: bool
```
but this seems like a quite big change that will likely break some downstream usage. then again this is for v2 so maybe it's ok?

**Comment by zzzeek** [comment] 2022-06-30 13:24
I think the expressions should be in a totally separate field because they would be interpreted in an entirely different way, this would be basically equivalent to how `Index` itself does it, it has a list of "columns" and also a list of "expressions".    The list of "expressions" can include plain columns as well, meaning, the "expressions" list becomes the ultimate list of "things that are indexed".    

There can also be a flag like "uses_expressions" so that a program that is interpreting reflected indexes will know to look in the "expressions" collection.

**Comment by CaselIT** [comment] 2022-06-30 19:06
Ok so some options
```py
# create table foo(a int, b int, c text, d text);
# create index foo_1 on foo(a, b) include (d);
# create index foo_2 on foo(abs(a), c, upper(d)) include (b);

# version 1, using a flag list to indicate if column_names are expressions or not
[
    {
        "name": "foo_1",
        "column_names": ["a", "b"],
        "unique": False,
        "include_columns": ["d"],
    },
    {
        "name": "foo_2",
        "column_names": ["abs(a)", "c", "upper(d)"],
        "column_is_exp": [True, False, True],
        "unique": False,
        "include_columns": ["b"],
    },
]
# version 2, use a list of dict
[
    {
        "name": "foo_1",
        "column_names": [
            {"text": "a", "column": True},
            {"text": "b", "column": True},
        ],
        "unique": False,
        "include_columns": ["d"],
    },
    {
        "name": "foo_2",
        "column_names": [
            {"text": "abs(a)", "column": False},
            {"text": "c", "column": True},
            {"text": "upper(d)", "column": False},
        ],
        "unique": False,
        "include_columns": ["b"],
    },
]
# version 3a, use an expression list with expressions and columns
[
    {
        "name": "foo_1",
        "column_names": ["a", "b"],
        "unique": False,
        "include_columns": ["d"],
    },
    {
        "name": "foo_2",
        "column_names": [None, "c", None],
        "expression": ["abs(a)", "c", "upper(d)"],
        "unique": False,
        "include_columns": ["b"],
    },
]
# version 3b, use an expression list with only expressions
[
    {
        "name": "foo_1",
        "column_names": ["a", "b"],
        "unique": False,
        "include_columns": ["d"],
    },
    {
        "name": "foo_2",
        "column_names": [None, "c", None],
        "expression": ["abs(a)", None, "upper(d)"],
        "unique": False,
        "include_columns": ["b"],
    },
]
```
I like version 1 or version 3a best. You mike prefer version 3a right?

Also I've checked whatever postgresql supports expression in included columns and it does not (it errors with `ERROR: expressions are not supported in included columns`).
This makes sense since include is only used in case of index only scans, so it's safe to assume other db would behave similarly. Given this no change is required to include

**Comment by zzzeek** [comment] 2022-07-01 16:12
I would only go with 3a or 3b.    I don't like SQL expressions under "column_names" because that's not a descriptive name.

also I would call it "expressions", plural

**Comment by sqla-tester** [comment] 2022-07-02 21:49
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Reflect expression-based indexes on PostgreSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3969

**Closed** 2022-07-28 18:19 UTC
Labels: postgresql, reflection, use case

**Comment by immerrr** [comment] 2022-07-28 19:55
Great stuff! @CaselIT thank you so much :pray:

**Comment by CaselIT** [comment] 2022-07-28 19:55
Thank you for the support!
