### ISSUE TITLE
Incorrect behavior in guessing unspecified (null) parent key for SQLite

### ISSUE THREAD

**Issue by acbart** [sqlalchemy/sqlalchemy#4810] opened 2019-08-18 16:07 UTC
I apologize in advance if I am incorrect about this, but I've been researching for the past hour and I think I've found a bug in the way that SQLAlchemy tries to get foreign keys from a SQLite database. Basically, if a foreign key was defined without an explicit parent key, then the existing implementation will use the child key instead:

https://github.com/sqlalchemy/sqlalchemy/blob/d1948bc69bd0d26fbff77d7525ef899a2a9a580d/lib/sqlalchemy/dialects/sqlite/base.py#L1757-L1758

https://github.com/sqlalchemy/sqlalchemy/blob/d1948bc69bd0d26fbff77d7525ef899a2a9a580d/lib/sqlalchemy/dialects/sqlite/base.py#L1827-L1828

However, this is at odds with what SQLite describes in their [ForeignKey docs](https://www.sqlite.org/foreignkeys.html#fk_indexes). If I understand them correctly, a null parent key should map automatically to the primary key of the parent table:

> The block above uses a shorthand form to create the foreign key constraint. Attaching a "REFERENCES parent-table" clause to a column definition creates a foreign key constraint that maps the column to the primary key of parent-table.

Now, ideally the schema wouldn't be missing the parent key, but that's apparently what SQLAlchemy did when it was generating my SQLite database. I had the following declarative table:

```python
class Assignment(Base):
    owner_id = Column(Integer(), ForeignKey('user.id'))
```

The DDL for the actual DB is:

```sql
CREATE TABLE "assignment"
(
	id INTEGER not null
		primary key,
        ...
	owner_id INTEGER
		references user,
        ...
)
```

And those are referring to a `User` table who's primary key is defined as `id`. Effectively, when it gets my foreign keys using the function linked above, it decides that the parent must be `User.owner_id` - instead of the correct `User.id`.

This situation hit me pretty hard when I was trying to run Flask-Migrate (so really Alembic) auto-generate on my models, and it was getting very confused about how to read my existing models with regards to the sqlite database. I'm not sure of more specifics on all this stuff, and I hope I can probably avoid using auto-generate for now, but this is something of a problem for me long term.

**Comment by zzzeek** [comment] 2019-08-18 16:43
hi there -

so the second part of your question is where I get what we are talking about most immediately.  SQlite is not storing the semantic meaning of "REFERENCES table", that is, it implicitlyrefers to the primary key , and at some point whoever wrote this code (could have been me but this code is many years old) made this odd assumption that we would link to "lcol" which seems wrong.

so what we do is make a test.   then we have the bug, then we can fix.  Here's the test:
```

diff --git a/test/dialect/test_sqlite.py b/test/dialect/test_sqlite.py
index 755fd6c29..fe2ecc7d3 100644
--- a/test/dialect/test_sqlite.py
+++ b/test/dialect/test_sqlite.py
@@ -1770,10 +1770,21 @@ class ConstraintReflectionTest(fixtures.TestBase):
                 ")"
             )
 
+            conn.execute(
+                "CREATE TABLE implicit_referred (pk integer primary key)"
+            )
+            # no column given
+            conn.execute(
+                "CREATE TABLE implicit_referrer "
+                "(id integer REFERENCES implicit_referred)"
+            )
+
     @classmethod
     def teardown_class(cls):
         with testing.db.begin() as conn:
             for name in [
+                "implicit_referrer",
+                "implicit_referred",
                 "m",
                 "main.l",
                 "k",
@@ -1892,6 +1903,23 @@ class ConstraintReflectionTest(fixtures.TestBase):
             ],
         )
 
+    def test_foreign_key_implicit_parent(self):
+        inspector = Inspector(testing.db)
+        fks = inspector.get_foreign_keys("implicit_referrer")
+        eq_(
+            fks,
+            [
+                {
+                    "name": None,
+                    "constrained_columns": ["id"],
+                    "referred_schema": None,
+                    "referred_table": "implicit_referred",
+                    "referred_columns": ["pk"],
+                    "options": {},
+                }
+            ],
+        )
+
     def test_unnamed_inline_foreign_key(self):
         inspector = Inspector(testing.db)
         fks = inspector.get_foreign_keys("e")

```

**Comment by zzzeek** [comment] 2019-08-18 16:43
how

**Comment by zzzeek** [comment] 2019-08-18 16:44
sorry my mouse slipped.  i will re-post my answer with all the text

**Comment by zzzeek** [comment] 2019-08-18 16:55
hi there -

so the second part of your question is where I get what we are talking about most immediately.  SQlite is not storing the semantic meaning of "REFERENCES table", that is, it implicitly refers to the primary key , and at some point whoever wrote this code (could have been me but this code is many years old) made this odd assumption that we would link to "lcol" which seems wrong.

so what we do is make a test.   then we have the bug, then we can fix.  Here's the test:

```diff

diff --git a/test/dialect/test_sqlite.py b/test/dialect/test_sqlite.py
index 755fd6c29..fe2ecc7d3 100644
--- a/test/dialect/test_sqlite.py
+++ b/test/dialect/test_sqlite.py
@@ -1770,10 +1770,21 @@ class ConstraintReflectionTest(fixtures.TestBase):
                 ")"
             )
 
+            conn.execute(
+                "CREATE TABLE implicit_referred (pk integer primary key)"
+            )
+            # no column given
+            conn.execute(
+                "CREATE TABLE implicit_referrer "
+                "(id integer REFERENCES implicit_referred)"
+            )
+
     @classmethod
     def teardown_class(cls):
         with testing.db.begin() as conn:
             for name in [
+                "implicit_referrer",
+                "implicit_referred",
                 "m",
                 "main.l",
                 "k",
@@ -1892,6 +1903,23 @@ class ConstraintReflectionTest(fixtures.TestBase):
             ],
         )
 
+    def test_foreign_key_implicit_parent(self):
+        inspector = Inspector(testing.db)
+        fks = inspector.get_foreign_keys("implicit_referrer")
+        eq_(
+            fks,
+            [
+                {
+                    "name": None,
+                    "constrained_columns": ["id"],
+                    "referred_schema": None,
+                    "referred_table": "implicit_referred",
+                    "referred_columns": ["pk"],
+                    "options": {},
+                }
+            ],
+        )
+
     def test_unnamed_inline_foreign_key(self):
         inspector = Inspector(testing.db)
         fks = inspector.get_foreign_keys("e")

```

how did I make that test?   I first created the table with REFERENCES
implicit_referred(pk),  then got the assertion to pass, then I took out the
(pk) part and confirmed the assertion failed.  so now we have a failing test
and we have to figure out how to get that "pk" back. unfortunately it looks
like we have to go out and reflect the other table's PKs, which is silly that
SQLite would make us do this, but at least SQLite is extremely fast so
shouldn't be an issue:

```diff
diff --git a/lib/sqlalchemy/dialects/sqlite/base.py b/lib/sqlalchemy/dialects/sqlite/base.py
index 9a0455a9d..cfe3197ed 100644
--- a/lib/sqlalchemy/dialects/sqlite/base.py
+++ b/lib/sqlalchemy/dialects/sqlite/base.py
@@ -1755,7 +1755,8 @@ class SQLiteDialect(default.DefaultDialect):
             (numerical_id, rtbl, lcol, rcol) = (row[0], row[2], row[3], row[4])
 
             if rcol is None:
-                rcol = lcol
+                referred_pk = self.get_pk_constraint(connection, rtbl, schema=schema)
+                rcol = referred_pk['constrained_columns'][0]
 
             if self._broken_fk_pragma_quotes:
                 rtbl = re.sub(r"^[\"\[`\']|[\"\]`\']$", "", rtbl)
```

that will fix this case but doesn't cover the case for a composite primary key.
  The patch  I will push up will accommodate for that case also as it has to
not hardcode that zero in  there.  thanks for the bug report.

**Comment by acbart** [comment] 2019-08-18 17:07
Wow, that was an impressively fast response. Thanks for the thorough debug and patch!

**Comment by sqla-tester** [comment] 2019-08-18 17:07
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Reflect PK of referred table if referred columns not present** https://gerrit.sqlalchemy.org/1422

**Comment by sqla-tester** [comment] 2019-08-18 17:07
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Reflect PK of referred table if referred columns not present** https://gerrit.sqlalchemy.org/1423

**Comment by zzzeek** [comment] 2019-08-18 17:14
> Wow, that was an impressively fast response. Thanks for the thorough debug and patch!

it's not that hard of an issue and also is a little embarrassing because that's been that way for at least ten years, I like to get these right out the door quick

**Closed** 2019-08-19 04:41 UTC
Labels: bug, sqlite
