### ISSUE TITLE
Support sequences for MariaDB

### ISSUE THREAD

**Issue by chaitut715** [sqlalchemy/sqlalchemy#4976] opened 2019-11-12 10:42 UTC
MariaDB added [sequence support from 10.3](https://mariadb.com/kb/en/library/sequences/). Would be great if sqlalchemy enables sequence support for MariaDB.

**Comment by zzzeek** [comment] 2019-11-12 14:14
Sure, do you have the availability to work on a pull request?

**Comment by gordthompson** [comment] 2019-11-17 00:23
Hi Mike. I made a branch from the current master (1acc675), pointed it at a MariaDB 10.4.8 server (using PyMySQL), and poked it until I got all tests to pass for

py.test -k SequenceTest --db mysql

Then I tried running the full tox test but it wouldn't fly on my Linux box because it couldn't install mysqlclient.

So I just did a `py.test -n4 --db mysql` on my branch (710fd4c) and I got 7 failures.

[mariadb-710fd4c.txt](https://github.com/sqlalchemy/sqlalchemy/files/3854907/mariadb-710fd4c.txt)

For comparison, I did that same test on the current master (1acc675) and I got 4 of those failures (3 of which are "AssertionError: Unexpected success"), so they're not due to the changes I made, they're presumably due to the tests being run against MariaDB instead of MySQL.

[mariadb-1acc675.txt](https://github.com/sqlalchemy/sqlalchemy/files/3854913/mariadb-1acc675.txt)

That leaves the other 3 failures that seem to be the result of simply enabling sequences in the MySQL dialect. However, I'm not sure if the problem is with the code or with the tests because they are part of the older test setup (not the suite).

[the-other-three.txt](https://github.com/sqlalchemy/sqlalchemy/files/3854914/the-other-three.txt)

Feel free to have a look at 710fd4c and let me know how to proceed.

**Comment by zzzeek** [comment] 2019-11-17 15:10
wow thanks!   this is amazing you're a regular contributor !!    Yeah I didn't mention on here what the particular knobs would be to make sequences work for this version of mariadb and they might be a little bit different from previous examples of sequence-supporting databases because this is such a narrow use case.

**Comment by gordthompson** [comment] 2019-11-17 16:06
It was pretty straightforward since I had examples for Oracle, Firebird, and PostgreSQL. I could steal the bits that most closely matched what MariaDB expected once the failing tests told me where to start looking.

BTW, we can disregard the 4 failures I mentioned in "mariadb-1acc675.txt". I just tried again on an Xubuntu 19.04 VM using tox, and those failures did not occur. They must have been due to the fact that I was using MariaDB from Xampp on my main 18.04 box.

I did get "the other three" failures under 19.04. (6 failures actually, because tox reported each one twice: once for `mysql+mysqldb` and again for `mysql+pymysql`.)

**Comment by gordthompson** [comment] 2019-11-19 18:25
Just curious how these changes might affect Continuous Integration testing. If those tests for the "mysql" dialect were run against MariaDB 10.3+ then it would be no problem, but if you're currently testing against MySQL then I can appreciate that you might not want to alter your set too much just for this one little feature.

**Comment by zzzeek** [comment] 2019-11-19 19:52
yup so that is what the "requirements.py" system gives us.   There's already a requirement called "sequences" that only lets a test run if the current database connection supports sequences.     This req can be at the class level using `__requires__ = 'sequences',` or on a specific test using `@testing.requires.sequences`.  See lib/sqlalchemy/testing/suite/test_sequence.py to see this.      To see an example of a req that only works for newer MariaDB and not MySQL, see test/requirements.py -> ctes.

**Comment by gordthompson** [comment] 2019-11-20 02:29
Sounds good. But, with an unconditional `supports_sequences` declaration

https://github.com/gordthompson/sqlalchemy/blob/943ffbe056f65189d747ac3db93c71f7ddde2cef/lib/sqlalchemy/dialects/mysql/base.py#L2161

in dialects/mysql/base.py (for the MySQLDialect class) I get a whole boatload (>25) of errors when I run the tox tests against MySQL 5.7.28 because MySQL doesn't do sequences.

If I comment out that line and fire up tox again I still get 3 failures

```
[gw3] [ 58%] FAILED test/orm/test_query.py::SessionBindTest::test_sql_expr_bundle_cte_from_entity 
[gw3] [ 58%] FAILED test/orm/test_query.py::SessionBindTest::test_sql_expr_cte_from_entity 
[gw1] [ 83%] FAILED test/orm/inheritance/test_single.py::SingleInheritanceTest::test_select_from_subquery 
```

so it seems like a big first step would be to have a way to conditionally set `supports_sequences` depending on the actual back-end we are using.

**Comment by zzzeek** [comment] 2019-11-20 15:44
yep, that's part of it, MySQL and MariaDB by and large do *not* support sequences, so this flag should be set to false.  only set it to true inside of the initialize() method after checking for  MariaDB + Mariadb version >= 10.3.  https://github.com/gordthompson/sqlalchemy/blob/943ffbe056f65189d747ac3db93c71f7ddde2cef/lib/sqlalchemy/dialects/mysql/base.py#L2457

**Comment by gordthompson** [comment] 2019-11-20 16:27
Okay, thanks. I'll dig into that.

Question regarding `test_inserted_pk_no_returning` (the second of "the other three" test failures):

The comment at the beginning of the [test](https://github.com/sqlalchemy/sqlalchemy/blob/3ceb87da1a66f455444e69ba25ac18ea26d8751e/test/sql/test_defaults.py#L1340) is

```
"""test inserted_primary_key contains [None] when
pk_col=next_value(), implicit returning is not used."""
```

Under MariaDB `r.inserted_primary_key` is not returning `None`, it is returning the next value in the sequence (3, in this case). Is that behaviour really incorrect, or is it just not what the test expects? IOW, which needs fixing: the test, or the code it is testing?

**Comment by zzzeek** [comment] 2019-11-20 18:40
in that test, the SQL should look something like this:

    INSERT INTO table (x) VALUES (nextval(my_seq))

what's the mechanism by which the new sequence value would be in inserted_primary_key ?    the MySQL dialect typically relies upon the "cursor.lastrowid" attribute which IIUC is linked only to the AUTO_INCREMENT feature.   However, this is new ground so maybe it's not (or maybe that's not the SQL being emitted, in which case that's the fix here).

**Comment by gordthompson** [comment] 2019-11-20 19:57
Yes, for `test_inserted_pk_no_returning` the SQL being emitted to MariaDB is

```sql
INSERT INTO t (x) VALUES (nextval(my_sequence))
```

However, this may be related to the [test_cursor_execute](https://github.com/sqlalchemy/sqlalchemy/blob/d933ddd503a1ca0a7c562c51c503139c541e707e/test/engine/test_execute.py#L1746) failure (the third of "the other three"). The failure under MariaDB is

```
    assert "INSERT" in canary[1][0]
IndexError: list index out of range
```

When I run the test under PostgreSQL, `canary` looks like this:

```
<class 'list'>: 
[
    (
        "select nextval('t_id_seq')", 
        <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x088387C0>
    ), 
    (
        'INSERT INTO t (x) VALUES (%(x)s)', 
        <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x088387C0>
    )
]
```

whereas under MariaDB, `canary` looks like this:

```
<class 'list'>: 
[
    (
        'INSERT INTO t (x) VALUES (nextval(t_id_seq))', 
        <sqlalchemy.dialects.mysql.mysqldb.MySQLExecutionContext_mysqldb object at 0x7f222427cb90>
    )
]
```

So it looks like that test is expecting things to happen "the PostgreSQL way", while MariaDB is able to get the job done with a single statement.

**Comment by zzzeek** [comment] 2019-11-20 22:13
right except....it's probably not.

in this area, you're looking at a lot of stuff that I first wrote in about 2005 or so, before RETURNING was generally available and when I was specifically targeting PG + Oracle, the latter of which has no "auto" version of a sequence.    I don't think anyone besides me has ever dug into this stuff, so kudos for hanging on.

So the original way INSERT with a sequence worked, was:

```
SELECT nextval(seq)

< fetch id >

INSERT INTO TABLE (...) VALUES (<the id we fetched>)
```

the reason it's separate is because there was no good way to otherwise know what the value of the sequence was.  it's explicitly fetched beforehand.   now there are in fact functions on most databases that are something like "SELECT LAST_ID" or something like that, but I was not as familiar with those so I didn't code to that early on.   

at the same time, the use case for the "inline" INSERT was added, which was where we didn't need the new PK and wanted to save a round trip:
 
`INSERT INTO TABLE (...) VALUES (nextval(seq))`

what determines these behaviors are other flags on the dialect:

```
    supports_sequences = True
    sequences_optional = True
    preexecute_autoincrement_sequences = True
    postfetch_lastrowid = False

```

Then, RETURNING became available, and then I had to factor even more flags into this whole thing.   

Generally if you look in the file crud.py, there is an enormous drill down of rules used to generate INSERT statements.  I can't follow that code without re-familiarizing with it.  it's because of all of these combinations on how databases generate integer primary keys.  SQLAlchemy wanted to support them all and it wanted it to be 100% transparent.   it's one of the major intricacies of the whole library and I virtually never get any bug reports about any of it either.

now the bad news is we have yet to have a dialect that supports sequences *and* a cursor.lastrowid thing at the same time.    so we might have to figure something out with this, that is, figure out a conditional per-statement, if a statement is using autoincrement / lastrowid or sequences, or adjust these tests, or etc.

this is also why I don't really see why sequences are useful for MariaDB in general.  The sequence is kind of this generic anywhere-you-need-an-integer thing, but in practice *nobody* needs sequences for anything except integer primary keys, and if you are doing tricks like adjusting the value of the sequence or the step or whatever, you're doing it wrong anyway.     this is why I sort of said "sure someone can implement this, whatever" but I don't really see why this case is that important unless someone wants to use sequences for something that they shouldn't be, that is, generation of some real data value and not an arbitrary unique value.

that said, getting the dialect tests and everything to support this all-new "PK generation" scheme, as well as if you were to gain knowledge on how this system works, would be extremely valuable.   so I would welcome your continued involvement, I just want to state up front that getting this to work might not be that simple :).

**Comment by gordthompson** [comment] 2019-11-21 00:17
I'd say given that we're only getting 3 failures out of 11_000+ tests and those failures are edge cases for a feature that will likely not see a whole lot of use under MariaDB we should just tweak the tests to PASS or SKIP so CI won't fail.

My first thought was to just ignore them, thinking that you were probably running CI tests against a couple of versions of MySQL (e.g., latest GA, somewhat recent, and oldest officially supported). However, based on what I see at

https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=cext,db=mysql,pyv=py37/3349/console

it looks like you're testing against 5.6.44.MySQL, 10.2.9.MariaDB, 10.3.9.MariaDB, 8.0.16.MySQL, and 5.7.26.MySQL. With 10.3.x.MariaDB in the mix we can't just "look the other way".

If you're okay with it I can look into ways to get those three tests to simply not fail with the current code.

**Comment by zzzeek** [comment] 2019-11-21 00:42
this is a pretty critical area so if you can put it in a PR I can try to review and see the best way for this to work in, given that im not sure how to work this in :).

**Comment by sqla-tester** [comment] 2019-11-21 14:43
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add sequence support for MariaDB 10.3+.** https://gerrit.sqlalchemy.org/1585

**Comment by zzzeek** [comment] 2019-11-26 18:00
great work!!!! so excellent to just have this in!!

**Closed** 2019-11-26 18:00 UTC
Labels: fairly easy, motivated volunteers requested, use case
