### ISSUE TITLE
mssql+pyodbc throws error in version 1.4.16+: "Data source name not found and no default driver specified"

### ISSUE THREAD

**Issue by stephenfuqua** [sqlalchemy/sqlalchemy#6727] opened 2021-07-07 15:02 UTC
**Describe the bug**
When executing a query using mssql+pyodbc driver, the following error occurs if using SQLAlchemy version 1.4.16 or newer with pyodbc 4.0.31:

```
sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
```

**To Reproduce**

Install dependencies pyodbc (tested on latest, 4.0.31) and SQLAlchemy 1.4.16 or newer.

```py
from sqlalchemy import create_engine

connection_string = "mssql+pyodbc://localhost/master?driver=ODBC+Driver+17+for+SQL+Server?Trusted_Connection=yes"

engine = create_engine(connection_string)
engine.execute("select 1 as result")
```

**Error**

```
Traceback (most recent call last):
  File "...\sqlalchemy\engine\base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "...\sqlalchemy\pool\base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "...\sqlalchemy\pool\base.py", line 761, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "...\sqlalchemy\pool\base.py", line 419, in checkout
    rec = pool._do_get()
  File "...\sqlalchemy\pool\impl.py", line 145, in _do_get
    self._dec_overflow()
  File "...\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "...\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "...\sqlalchemy\pool\impl.py", line 142, in _do_get
    return self._create_connection()
  File "...\sqlalchemy\pool\base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "...\sqlalchemy\pool\base.py", line 362, in __init__
    self.__connect()
  File "...\sqlalchemy\pool\base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "...\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "...\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "...\sqlalchemy\pool\base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "...\sqlalchemy\engine\create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "...\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\example.py", line 6, in <module>
    engine.execute("select 1 as result")
  File "<string>", line 2, in execute
  File "...\sqlalchemy\util\deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "...\sqlalchemy\engine\base.py", line 3107, in execute
    connection = self.connect(close_with_result=True)
  File "...\sqlalchemy\engine\base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "...\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "...\sqlalchemy\engine\base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "...\sqlalchemy\engine\base.py", line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "...\sqlalchemy\engine\base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "...\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "...\sqlalchemy\engine\base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "...\sqlalchemy\pool\base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "...\sqlalchemy\pool\base.py", line 761, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "...\sqlalchemy\pool\base.py", line 419, in checkout
    rec = pool._do_get()
  File "...\sqlalchemy\pool\impl.py", line 145, in _do_get
    self._dec_overflow()
  File "...\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "...\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "...\sqlalchemy\pool\impl.py", line 142, in _do_get
    return self._create_connection()
  File "...\sqlalchemy\pool\base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "...\sqlalchemy\pool\base.py", line 362, in __init__
    self.__connect()
  File "...\sqlalchemy\pool\base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "...\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "...\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "...\sqlalchemy\pool\base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "...\sqlalchemy\engine\create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "...\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/14/rvf5)
```

**Versions.**
 - OS: Windows 10
 - Python: 3.9.4
 - SQLAlchemy: 1.4.16+
 - Database: SQL Server 2017
 - DBAPI: pyodbc

**Additional context**

The link http://sqlalche.me/e/14/rvf5 points out that this is a problem in the DBAPI driver, and that page suggests it is not a SQL Alchemy error. However, the problem is resolved by simply downgrading SQLAlchemy to 1.4.15 and keeping the same pyodbc driver. Perhaps the connection string is not being passed into pyodbc correctly.

**Comment by CaselIT** [comment] 2021-07-07 15:09
Hi,

This is an exact duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/6723

The connection url `mssql+pyodbc://localhost/master?driver=ODBC+Driver+17+for+SQL+Server?Trusted_Connection=yes` in invalid since it contains two `?`. Replace the second one with `&`

**Comment by zzzeek** [comment] 2021-07-07 15:09
remove the double question marks -

just yesterday, same issue: #6723  and previously:  #6601

I'm still trying to understand why so many people seem to have URLs with two question marks in them?  how did you write this URL ?  was there a tutorial or document that showed two question marks?

**Closed** 2021-07-07 15:09 UTC
Labels: SQL Server, duplicate, expected behavior

**Comment by stephenfuqua** [comment] 2021-07-07 15:35
Well, that is rather obvious now that you point it out. Apologies for submitting again - I didn't think to look at closed issues, since the "problem" only appeared in a recent patch release.

**Comment by zzzeek** [comment] 2021-07-07 19:28
not to worry, just weird to see this happening so much.

**Comment by spotnuru83** [comment] 2024-11-16 05:00
is there any resolution for this, I am still getting this error

**Comment by brodrigz** [comment] 2025-05-26 17:49
still a problem in latest ver
