### ISSUE TITLE
Use an empty query instead of SELECT 1 for pre_ping test

### ISSUE THREAD

**Issue by anayrat** [sqlalchemy/sqlalchemy#8491] opened 2022-09-05 13:58 UTC
### Describe the use case

Hello,

SQLa send a "SELECT 1" to perform a connection test as pre_ping.
Defined in : https://github.com/sqlalchemy/sqlalchemy/blob/1ea3c783b6ceaf488e34f15c3ce97eabbc3ab4d3/lib/sqlalchemy/engine/default.py#L632-L633

Instead of "SELECT 1", we may use an empty query by sending only ";". This avoids Postgres planner.
It has been done in activerecord : 
https://github.com/rails/rails/pull/42368

Same optimization exist in golang https://github.com/jackc/pgx/blob/3ab89419216bcaf306c930ce291ef2b63000ba08/conn.go#L360-L363

### Databases / Backends / Drivers targeted

Postgres (any version)

### Example Use

I am not pythonist, but the goal is to send ";" instead of "select 1".

### Additional context

Gitlab issue with benchmark https://gitlab.com/gitlab-org/gitlab/-/issues/220055#note_463405732

**Comment by zzzeek** [comment] 2022-09-05 14:09
feel free to send a PR , local to the PostgreSQL dialects, thanks!

**Comment by anayrat** [comment] 2022-09-05 14:44
As I said, I am not pythonist. The idea is to send ";" instead of "select 1". At least for Postgres (I don't know how other RDBMS behave).

**Comment by anayrat** [comment] 2022-09-05 14:48
I suppose, we may change this line https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/_psycopg_common.py#L188

**Comment by CaselIT** [comment] 2022-09-05 15:16
I don't think pyscopg2 supports this:
```
ProgrammingError: (psycopg2.ProgrammingError) can't execute an empty query
```
this is when trying to execute `conn.exec_driver_sql(';')`

Also I'm not sure the impact would be measurable, since I would guess that the network latency is a greater than the time used by pg to execute `select 1`.
Running `conn.exec_driver_sql('select 1').all()` in localhost gives me a time of `74 µs ± 2.49 µs` that considering it's python it quite fast

**Comment by CaselIT** [comment] 2022-09-05 15:25
> Running `conn.exec_driver_sql('select 1').all()` in localhost gives me a time of `74 µs ± 2.49 µs` that considering it's python it quite fast

for comparison this is comparable to running `redis.ping()` on localhost on my pc

**Comment by zzzeek** [comment] 2022-09-05 16:21
> As I said, I am not pythonist. The idea is to send ";" instead of "select 1". At least for Postgres (I don't know how other RDBMS behave).

are you...actually using SQLAlchemy?  or is this from some kind of code search you're doing ?

**Comment by zzzeek** [comment] 2022-09-05 16:45
do you have developers writing Python applications with SQLAlchemy in your organization?  getting them involved would help

**Comment by zzzeek** [comment] 2022-09-05 16:47
like, this issue likely needs to be done [at the driver level](https://stackoverflow.com/questions/1281875/making-sure-that-psycopg2-database-connection-alive) since "select 1" is currently what psycopg2 (and probably all the others) currently supports

**Comment by CaselIT** [comment] 2022-09-05 16:50
Also note that sqlalchemy does not emit `select 1` by default, that's an option enabled with the pool pre_ping engine option

**Comment by zzzeek** [comment] 2022-09-05 16:53
also...wouldnt the database server be caching the query plan for this query?

**Comment by CaselIT** [comment] 2022-09-05 21:47
> also...wouldnt the database server be caching the query plan for this query?

seems not. IIRC pg does not have a cache of plans, only for prepared statements.

**Comment by CaselIT** [comment] 2022-09-09 16:16
Ok I've tested how the driver behave:
```py
import sqlalchemy as sa
import sqlalchemy.ext.asyncio as saa
import asyncio

query = ';'

def go(name:str):
    engine = sa.create_engine(f'postgresql+{name}://mamba:mamba-password@localhost:5432/test')
    with engine.connect() as conn:
        try:
            conn.exec_driver_sql(query)
        except Exception as e:
            print(name, 'error!', str(e).replace('\n', ''))
        else:
            print(name, 'ok!')
    engine.dispose()

go('psycopg2')
go('psycopg')
go('pg8000')

async def ago(name: str):
    engine = saa.create_async_engine(f'postgresql+{name}://mamba:mamba-password@localhost:5432/test')
    async with engine.connect() as conn:
        try:
            await conn.exec_driver_sql(query)
        except Exception as e:
            print(name, 'error!', e)
        else:
            print(name, 'ok!')
    await engine.dispose()

# asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
asyncio.run(ago('asyncpg'))
asyncio.run(ago('psycopg'))
```
result is
```
psycopg2 error! (psycopg2.ProgrammingError) can't execute an empty query[SQL: ;](Background on this error at: https://sqlalche.me/e/20/f405)
psycopg ok!
pg8000 ok!
asyncpg error! expected string or bytes-like object
psycopg ok!
```

so 2 out of 4 (psycopg have both sync and async)

@zzzeek how do you want to proceed?

**Comment by zzzeek** [comment] 2022-09-09 17:03
im fine changing the ping query for those specific backends, that's fine.  this is a one-liner per dialect kind of thing.      

would be nice to get from asyncpg / psycopg2 what the best way to ping is.

**Comment by CaselIT** [comment] 2022-09-09 17:19
should we ping the developer here?

**Comment by zzzeek** [comment] 2022-09-09 19:04
yeah I'd want to

**Comment by CaselIT** [comment] 2022-09-09 19:13
Hi @elprans @dvarrazzo, sorry for the ping.

We got a request to avoid sending `select 1` to postgresql when pinging the connection to check if it's alive or not, since that query incurs in planning costs. It seems that an alternative is to just sent `;` and it's been done by other libraries. 

Trying to execute `;` in an error in asyncpg and on psycopg2 (the new psycopg seems happy to use `;'`) as seen in the example https://github.com/sqlalchemy/sqlalchemy/issues/8491#issuecomment-1242178726.

What's the best way to ping the db when using this driver?

**Comment by dvarrazzo** [comment] 2022-09-09 20:06
You can prepare the `SELECT 1` if the planning cost is on your mind. The `;` must be parsed, maybe it won't be planned, but it can't be prepared, so I don't know if it's a win.

In psycopg 3 [there is a test](https://github.com/psycopg/psycopg/blob/68bec0bf0fe8ed5792a76c5d843cb235049e9181/tests/test_cursor.py#L162-L168) that verifies that handling empty queries doesn't regress, so there should be no regression there. The test suggests that an empty string works as well. I'm not planning to adding such support to psycopg2.

**Comment by anayrat** [comment] 2022-09-09 20:07
(Prepare prevent to use transaction pooling with pgbouncer for example.)

**Comment by CaselIT** [comment] 2022-09-09 20:48
> You can prepare the `SELECT 1` if the planning cost is on your mind. The `;` must be parsed, maybe it won't be planned, but it can't be prepared, so I don't know if it's a win.
> 
> In psycopg 3 [there is a test](https://github.com/psycopg/psycopg/blob/68bec0bf0fe8ed5792a76c5d843cb235049e9181/tests/test_cursor.py#L162-L168) that verifies that handling empty queries doesn't regress, so there should be no regression there. The test suggests that an empty string works as well. I'm not planning to adding such support to psycopg2.

thanks for the clarification. I think we can switch to `;` or empty string for psycog 3.
for psycopg2 it's probably safer to leave as is

**Comment by zzzeek** [comment] 2022-09-09 20:49
> 
> In psycopg 3 [there is a test](https://github.com/psycopg/psycopg/blob/68bec0bf0fe8ed5792a76c5d843cb235049e9181/tests/test_cursor.py#L162-L168) that verifies that handling empty queries doesn't regress, so there should be no regression there. The test suggests that an empty string works as well. I'm not planning to adding such support to psycopg2.

@dvarrazzo so per @anayrat 's issue , that the "SELECT 1" is creating a large planning cost, and given that PREPARE is still local to a specific database connection (so PREPARE would need to be per-connection at the very least) as well as that I can concur it breaks with pgbouncer's transaction pooling, there's no way to send an inexpensive ping with psycopg2.   Like even a method called "ping()" or something like that (MySQL drivers have this).   No less than [Tom Lane recommends the empty query approach](https://www.postgresql.org/message-id/7581.1124310348%40sss.pgh.pa.us).

from my end, I'm just the middle person here, we can implement the cheaper form of ping for those drivers that accept it.

**Comment by sqla-tester** [comment] 2022-09-13 19:48
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Use ``;`` instead of ``select 1`` to ping PostgreSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4078

**Closed** 2022-09-15 20:19 UTC
Labels: postgresql, PRs welcome, use case
