### ISSUE TITLE
Regression on 1.3.16 when fetching table schema for SQL Server

### ISSUE THREAD

**Issue by latkinsa** [sqlalchemy/sqlalchemy#5255] opened 2020-04-15 19:16 UTC
This issue is happening on CentOS Linux release 7.7.1908, it does not happen on a recent MacOS.

When fetching table columns (schema) from MS SQL Server using core, the following error is raised:
````
File "<string>", line 2, in __new__
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 507, in __new__
    metadata._remove_table(name, schema)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 502, in __new__
    table._init(name, metadata, *args, **kw)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 596, in _init
    resolve_fks=resolve_fks,
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 620, in _autoload
    _extend_on=_extend_on,
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1624, in run_callable
    return callable_(self, *args, **kwargs)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 467, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 661, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 388, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2185, in wrap
    **kw
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2200, in _switch_db
    return fn(*arg, **kw)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2606, in get_columns
    c = connection.execute(s)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/applications/inrem/VENV/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [FreeTDS][SQL Server]Unicode data in a Unicode-only collation or ntext data cannot be sent to clients using DB-Library (such as ISQL) or ODBC version 3.7 or earlier. (4004) (SQLExecDirectW)')
[SQL: SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME], sys.computed_columns.definition, sys.computed_columns.is_persisted 
FROM [INFORMATION_SCHEMA].[COLUMNS] LEFT OUTER JOIN sys.computed_columns ON sys.computed_columns.object_id = object_id(concat([INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], ?, [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME])) AND [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME] = sys.computed_columns.name 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION]]
[parameters: ('.', 'MemberRegistration', '_Core')]
(Background on this error at: http://sqlalche.me/e/f405)
````
Python 3.6.8

Reverting back to version 1.3.15 fixes the error.

**Comment by CaselIT** [comment] 2020-04-15 19:31
Could you provide an example of the python script that causes the problem?

The problem seems to come from the reflection of computed columns

**Comment by CaselIT** [comment] 2020-04-15 19:39
I think that the problem is on this line:
the `.` is not casted like the other fields
https://github.com/sqlalchemy/sqlalchemy/blob/06ba82a9c74885d1c5d8da7d138a869d83167cae/lib/sqlalchemy/dialects/mssql/base.py#L2581

**Comment by latkinsa** [comment] 2020-04-15 19:39
```
from sqlalchemy import *
...
  self.engine = create_engine(config.sql_engine_url(), echo=False, pool_pre_ping=True)
  self.connection = self.engine.connect()
  self.metadata = MetaData(schema='_Core')
  for t in ('MemberRegistration', 'UpdateLog'):
    self.cores[t.lower()] = Table(
        t, self.metadata, autoload_with=self.connection)
    # ^^^ error
...
```

**Comment by CaselIT** [comment] 2020-04-15 19:45
The problems seems caused by mssql version < 2005. The pipeline only test version 2016 I think.

Could you try if this patch works in your system?
```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index 43f3aeb04..b8a4f8243 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2673,7 +2673,9 @@ class MSDialect(default.DefaultDialect):
             )
             table_fullname = "%s.%s" % (owner, tablename)
             concat = func.concat(
-                columns.c.table_schema, ".", columns.c.table_name
+                columns.c.table_schema,
+                sql.cast(".", ischema.CoerceUnicode),
+                columns.c.table_name,
             )
             join_on = computed_cols.c.object_id == func.object_id(concat)
         else:
```

**Comment by CaselIT** [comment] 2020-04-15 19:52
I've changed `sql.cast` to `sql.literal` since cast produces two casts (that works, but this way only one is produced)

**Comment by latkinsa** [comment] 2020-04-15 20:02
well, it is on line # 2581 in my copy of code base. I changed as you suggested, no difference: still the same error.

**Comment by CaselIT** [comment] 2020-04-15 20:07
Sorry, I was on master when I copied that diff.

On which version of mssql are you using and which version of the dbpai are you using?
You mentioned that on mac you do not have this problem. Which version of dbapi are you using there?

**Comment by latkinsa** [comment] 2020-04-15 20:20
MS SQL Server 2017.
TDS 4.2 on Linux, TDS 7.4 on macOS. Ops are somehow unwilling to upgrade TDS on these systems :-(

**Comment by CaselIT** [comment] 2020-04-15 21:31
I've managed to test using tds version 4.2 and the problem was in the returned definition column.

This time this diff should fix it
```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index 6e2b2f94c..e0e4af763 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2592,12 +2592,10 @@ class MSDialect(default.DefaultDialect):
             join_on, columns.c.column_name == computed_cols.c.name
         )
         join = columns.join(computed_cols, onclause=join_on, isouter=True)
+        # Cast is required by tds_version 4.2
+        computed_definition = sql.cast(computed_cols.c.definition, TEXT)
         s = sql.select(
-            [
-                columns,
-                computed_cols.c.definition,
-                computed_cols.c.is_persisted,
-            ],
+            [columns, computed_definition, computed_cols.c.is_persisted],
             whereclause,
             from_obj=join,
             order_by=[columns.c.ordinal_position],
@@ -2618,7 +2616,7 @@ class MSDialect(default.DefaultDialect):
             numericscale = row[columns.c.numeric_scale]
             default = row[columns.c.column_default]
             collation = row[columns.c.collation_name]
-            definition = row[computed_cols.c.definition]
+            definition = row[computed_definition]
             is_persisted = row[computed_cols.c.is_persisted]

             coltype = self.ischema_names.get(type_, None)
```

**Comment by latkinsa** [comment] 2020-04-15 21:51
yep, this latest patch fixes it

**Comment by CaselIT** [comment] 2020-04-15 22:12
Great, I'll propose a patch tomorrow, so that next version should be fixes.

Thanks for bearing with me and testing the patches 👍

**Comment by zzzeek** [comment] 2020-04-15 22:51
I wonder why this one column has this issue ?  there is a CoerceUnicode datatype in information_schema but it currently doesn't CAST for the actual selected column as that hasn't been a problem.   is there something unique about this column?

**Comment by CaselIT** [comment] 2020-04-15 23:09
It the only text one that comes from the `sys` schema. They all should be of type nvarchar, but maybe the information schema does not return unocode?

You can forse the old tsd version by adding `?tsd_version=4.2` at the end of a pymssql connection string

**Comment by gordthompson** [comment] 2020-04-16 16:33
> The pipeline only test version 2016 I think.

Currently just 2017.

**Comment by CaselIT** [comment] 2020-04-16 17:05
This problems seems to be connected with the tds version, since I was able to reproduce on version 2019. It affects only tds 4.2. Version 7+ do not have it

**Comment by gordthompson** [comment] 2020-04-16 17:21
TDS version 4.2 is *ancient*. IIRC it pre-dates SQL Server 2000.

**Comment by zzzeek** [comment] 2020-04-16 17:34
IMO we should not have to support TDS 4.2 these days, and in fact pymssql is not supported anyway, @latkinsa can you get clarification on having to use an obsolete TDS version with a much newer SQL server version?

**Comment by latkinsa** [comment] 2020-04-16 18:17
well, not sure why we are running on TDS 4 - it is a part of the standard linux image on our platform, may be nobody bothered to upgrade this since the beginning. I'll raise this question with our ops.

**Comment by CaselIT** [comment] 2020-04-16 19:18
> I wonder why this one column has this issue ? there is a CoerceUnicode datatype in information_schema but it currently doesn't CAST for the actual selected column as that hasn't been a problem. is there something unique about this column?

I've done some experiments and cannot find any meaningful reason.

Using the following query on different sample queries results in
```sql
SELECT name, system_type_name, is_nullable, max_length, collation_name FROM sys.dm_exec_describe_first_result_set(@query, NULL, 0)
```
|query|name| system_type_name| is_nullable |max_length |collation_name|
|--|--|--|--|--|--|
|`SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] FROM [INFORMATION_SCHEMA].[COLUMNS]`|TABLE_SCHEMA| nvarchar(128)| 1 |256 |Latin1_General_100_CI_AS_KS_WS_SC|
|`SELECT sys.computed_columns.definition from sys.computed_columns`|definition| nvarchar(max)| 1 |-1 |SQL_Latin1_General_CP1_CI_AS|
|`SELECT CAST(sys.computed_columns.definition AS TEXT) as cast from sys.computed_columns`|cast| text| 1 |-1 |SQL_Latin1_General_CP1_CI_AS|

The only meaningful difference is that `definition` is unlimited. 

I've tried changing the fix from `CAST(sys.computed_columns.definition AS  TEXT)` to `CAST(sys.computed_columns.definition AS  NVARCHAR(128))` and it continues to work.
So I guess that tds 4 does not supports `NVARCHAR(max)`

**Comment by gordthompson** [comment] 2020-04-16 19:22
> So I guess that tds 4 does not supports NVARCHAR(max)

Exactly. nvarchar(max) [was introduced in SQL Server 2005](https://stackoverflow.com/a/39790739/2144390).

**Comment by CaselIT** [comment] 2020-04-16 19:26
So should I use text or nvarchar(4000) in this case (Unicode in sqlalchemy) in the fix?

**Comment by gordthompson** [comment] 2020-04-16 19:32
Definitely not [N]TEXT. That's been deprecated since [N]VARCHAR(MAX) became a thing.

**Comment by CaselIT** [comment] 2020-04-16 20:55
I was thinking of adding a check for the protocol version, but it needs the permission `VIEW SERVER STATE` since it needs to select from `sys.dm_exec_connections`
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-connections-transact-sql

I'm not sure how common is this permission.

**Comment by sqla-tester** [comment] 2020-04-16 21:01
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix regression when reflecting tables in MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1894

**Comment by sqla-tester** [comment] 2020-04-22 15:09
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix regression when reflecting tables in MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1912

**Closed** 2020-04-22 21:23 UTC
Labels: SQL Server, bug, reflection, regression

**Comment by ztane** [comment] 2020-04-23 08:41
Funnily reinstalled pymssql again *just* now after not touching it for 9 months, and I am using it for *only* sqlacodegen, and ran into this. just came here and seeing it fixed, thanks, will now update the requirement as `sqlalchemy>=1.13.15,!=1.13.16`.

**Comment by zzzeek** [comment] 2020-04-23 13:55
@ztane are you also using a very old TDS version in your freetds.conf ?   just so I know what's the reason you are stuck on that older version ?

**Comment by CaselIT** [comment] 2020-04-23 14:03
@zzzeek if that's the case, maybe we should also test against pymssql configured with `?tds_version=4.2`?

**Comment by zzzeek** [comment] 2020-04-23 14:15
we don't test against pymssql at all now because it is unmaintained, it was too time consuming to continue chasing down breakages in it.

**Comment by CaselIT** [comment] 2020-04-23 14:22
I guess there should be a way to specify the tds version even in py_odbc.
It should be possible specifying the `/?odbc_connect=` option

**Comment by zzzeek** [comment] 2020-04-23 14:30
my vague handwavy understanding of "TDS" is that explicit exposure to things like "TDS version" is a thing when you're using freetds, which could include the ODBC drivers, but this is all obsolete now.   Microsoft has ODBC drivers for linux which is what we test with now and they work way better than any of the FreeTDS stuff ever did.  there is of course a lot of "TDS" buried in it (just ran a strings on libmsodbcsql-13.1.so.9.2 to confirm) but it's all history that is no longer a thing to worry about.    I may be totally way off on this but I think nobody has to be using FreeTDS anymore for SQL Server.    "free and open" doesn't matter much because you're already using SQL Server.

**Comment by gordthompson** [comment] 2020-04-23 14:35
FreeTDS was crucial before MS released ODBC Driver for Linux. It's still useful for cases where MS doesn't (yet) support a particular flavour of Linux. It was a pain point for Alpine users for a while, but MS supports that platform now.

Also re: "why are you (still) using 4.2?" - Some official repos dish out *way old* version of FreeTDS where the default TDS procotol is 4.x. IIRC, Ubuntu 16.04 is (was) one of them.
