### ISSUE TITLE
DatabaseError: (cx_Oracle.DatabaseError) ORA-01219: database not open: queries allowed on fixed tables/views only

### ISSUE THREAD

**Issue by Prokhozhijj** [sqlalchemy/sqlalchemy#8744] opened 2022-10-31 14:58 UTC
### Describe the bug

I am trying to query Oracle standby database which is in mount mode (not opened). And when querying the database I am getting

```
DatabaseError: (cx_Oracle.DatabaseError) ORA-01219: database not open: queries allowed on fixed tables/views only
[SQL: select value from nls_session_parameters where parameter = 'NLS_NUMERIC_CHARACTERS']
(Background on this error at: https://sqlalche.me/e/14/4xp6)
 
```

### To Reproduce

```python
DIALECT = 'oracle'
SQL_DRIVER = 'cx_oracle'
USERNAME = 'sys' #enter your username
PASSWORD = 'syspassword' #enter your password
CONN_STR='tns_alias'
ENGINE_PATH_WIN_AUTH = DIALECT + '+' + SQL_DRIVER + '://' + USERNAME + ':' + PASSWORD +'@' + CONN_STR + '?mode='+str(cx_Oracle.SYSDBA) + '&encoding=UTF-8&nencoding=UTF-8'

import pandas as pd
from sqlalchemy.engine import create_engine
conn = create_engine(ENGINE_PATH_WIN_AUTH)
pd.read_sql("select instance_name from v$instance", con=conn)
```

### Error

```
<skipped>

File c:\python38\lib\site-packages\sqlalchemy\dialects\oracle\cx_oracle.py:1038, in OracleDialect_cx_oracle.initialize(self, connection)
   1035 if self._is_oracle_8:
   1036     self.supports_unicode_binds = False
-> 1038 self._detect_decimal_char(connection)

File c:\python38\lib\site-packages\sqlalchemy\dialects\oracle\cx_oracle.py:1107, in OracleDialect_cx_oracle._detect_decimal_char(self, connection)
   1100 def _detect_decimal_char(self, connection):
   1101     # we have the option to change this setting upon connect,
   1102     # or just look at what it is upon connect and convert.
   1103     # to minimize the chance of interference with changes to
   1104     # NLS_TERRITORY or formatting behavior of the DB, we opt
   1105     # to just look at it
-> 1107     self._decimal_char = connection.exec_driver_sql(
   1108         "select value from nls_session_parameters "
   1109         "where parameter = 'NLS_NUMERIC_CHARACTERS'"
   1110     ).scalar()[0]
   1111     if self._decimal_char != ".":
   1112         _detect_decimal = self._detect_decimal

<skipped>

DatabaseError: (cx_Oracle.DatabaseError) ORA-01219: database not open: queries allowed on fixed tables/views only
[SQL: select value from nls_session_parameters where parameter = 'NLS_NUMERIC_CHARACTERS']
(Background on this error at: https://sqlalche.me/e/14/4xp6)

```

### Versions

- OS: MS Windows 10
- Python: 3.8
- SQLAlchemy: 1.4.42
- Database: Oracle 12.2
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): cx_oracle

### Additional context

Use dynamic view gv$nls_parameters instead of nls_sessions_parameters when trying to set decimal separator. It will work with not opened (but mounted) database as well.

**Comment by zzzeek** [comment] 2022-10-31 15:51
cc @anthony-tuininga , are you familiar with "mount mode"?    There are views "v$" and "gv$" and I dont see any guidance on which to use when.

**Comment by Prokhozhijj** [comment] 2022-10-31 16:01
Any Oracle database can be in several states (modes):

- not mounted - no Oracle instance exists, the database is not available for any query;

- mounted - Oracle instance exists but data files are still not opened for user's access, the database is available for querying dynamic views only by sys user (mode=sysdba);

- opened - the database is available for all users.

Dynamic views are views with v$, gv$ prefix in their names. They exist in memory only.

**Comment by zzzeek** [comment] 2022-10-31 16:22
why is "nls_session_parameters" present ?  it's also a view ?

**Comment by zzzeek** [comment] 2022-10-31 16:28
note we have three other queries that use a "v$" view.  if "v$" is also not available, need to know that

**Comment by zzzeek** [comment] 2022-10-31 16:56
so why gv?  do we need to change our v queries also ?

**Comment by Prokhozhijj** [comment] 2022-10-31 17:00
> so why gv? do we need to change our v queries also ?

gv$ - is for a cluster database. It is better to use them for more versatility, they exist in single instance database as well.

For single instance database you use v$ views usually (but may use gv$ views as well, they show the same result for single instance database).

For RAC (cluster, multi instance) database you use gv$ views, because they are related to the whole database (not for specific db instance which is running on specific cluster mode).

**Comment by Prokhozhijj** [comment] 2022-10-31 17:29
> Do you propose moving all "v$" access to "gv$" ?

Actually it depends on what info do you need: cluster related or specific instance related. For my case I believe it is safe to use gv$ view. For others - I don't know. 

> do you know when "gv" was introduced?

As far as RAC (real application cluster) become available in Oracle 9, the answer is in Oracle 9. But it needs to be verified, I am not 100% sure, sorry.

**Comment by anthony-tuininga** [comment] 2022-10-31 17:37
Note that gv$ views are identical to v$ views with the exception of one additional column: `INST_ID`. I am told that in a RAC environment that querying gv$ views will return *multiple* rows -- which is probably not what you are interested in! I am asking internally about this specific parameter and what the best approach would be.

One question would be: why are you using a database that is mounted but not opened? Since only the v$ and gv$ views are available, its not like you can do much with it at that point that would benefit from SQLAlchemy? Or am I missing something?

**Comment by Prokhozhijj** [comment] 2022-10-31 17:45
> Note that gv$ views are identical to v$ views

Actually not all v$ are identical to gv$ views if we are talking about cluster database. For example, v$session view may return different result than gv$session view.

> why are you using a database that is mounted but not opened?

We have a lot of physical standby databases. And we need to keep records of them.
Also there is specific instance like +ASM. It is also works in not open mode.

**Comment by zzzeek** [comment] 2022-10-31 17:52
SQLAlchemy is concerned about the database that it is immediately connected towards. So it seems like for this particular query we'd want to stick with using v$nls_session_parameters.

**Comment by Prokhozhijj** [comment] 2022-10-31 17:57
Sorry. Just checked out ASM instance. v$nls_session_parameters won't work with it. But v$nls_parameters will work correctly.

**Comment by Prokhozhijj** [comment] 2022-10-31 18:04
Sorry one more time. It seems `v$nls_session_parameters` also DON'T work with physical standby db as well. So the only approach is to use `v$nls_parameters`. Not sure, if that is acceptable for SQLAlchemy in its current state. I mean why Oracle doesn't do those actions you do?

**Comment by anthony-tuininga** [comment] 2022-10-31 18:07
There is no view `v$nls_session_parameters` as no session has been established yet. There is only `v$nls_parameters`, as you noted. I am asking internally what the best approach would be for this scenario and will get back to you.

**Comment by Prokhozhijj** [comment] 2022-10-31 18:15
> There is no view v$nls_session_parameters as no session has been established yet.

Just in case. There are sessions as far as I connected to the database already.

```
SQL> select open_mode from v$database;

OPEN_MODE
--------------------
MOUNTED
```
```
SQL> select count(1) from v$session where username='SYS';

  COUNT(1)
----------
         2
```

> Note as well that the v$ and gv$ views are only available to SYSDBA by default -- so they cannot be used by default. 

I connect to standby db as "SYSDBA" because it is not possible to do that as regular user. For the primary db you may always grant "select any dictionary" privilege to specific user, so, no problem with v$, gv$ views in that case.

**Comment by Prokhozhijj** [comment] 2022-10-31 18:27
> I am asking internally what the best approach would be for this scenario and will get back to you.

Probably the best approach would be to check db mode before querying `nls_session_parameters` views. If the database is in "open" mode you use static view. If it is in "mounted" mode - you use `v$nls_parameters` view.

**Comment by Prokhozhijj** [comment] 2022-10-31 18:36
Following scenarios are possible:
1. Regular user connects to primary database which is in open mode.
2. SYSDBA user connects to standby database which is in mounted mode.
3. SYSDBA user connects to ASM instance for which `v$database` view is not available but `v$nls_parameters` view is. Possible connection string is:
`(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host_name)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=+ASM1)(UR=A)))`

**Comment by sqla-tester** [comment] 2022-10-31 19:10
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**query from v$nls_session_parameters** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4170

**Comment by sqla-tester** [comment] 2022-10-31 19:11
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**query from v$nls_session_parameters** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4171

**Comment by zzzeek** [comment] 2022-10-31 19:11
welp that's not working

```
(cx_Oracle.DatabaseError) ORA-00942: table or view does not exist
INTERNALERROR> [SQL: select value from v$nls_session_parameters where parameter = 'NLS_NUMERIC_CHARACTERS']
```

**Comment by zzzeek** [comment] 2022-10-31 19:13
nor is ``gv$nls_session_parameters``.

so this is not a simple fix, as it will require additional database introspection and I also can't test it fully.

**Comment by zzzeek** [comment] 2022-10-31 19:14
oh v$nls_parameters, let's try that

**Comment by Prokhozhijj** [comment] 2022-10-31 19:23
Mike,

Like your colleague said,  you can't just replace one view with another. I mean you will fix with such approach only my issue. But you may break functionality for other users.

I believe correct algorithm would be like below:
1. Check instance name (see above how to do that). If it contains '+ASM', use `v$nls_parameters`.
2. If instance name is not like '+ASM%', then check `open_mode` in `v$database`. If `open_mode` is "MOUNTED", then use `v$nls_parameters`.
3. Otherwise use `nls_session_parameters`.

**Comment by anthony-tuininga** [comment] 2022-10-31 19:30
The problem is that v$ views are only available to SYSDBA (unless explicitly granted) -- so you can't assume that everyone is going to connect as SYSDBA or be explicitly granted access to those views -- so probably best to try accessing `nls_session_parameters` first and then, if that fails, access `v$nls_parameters`. If I hear anything more useful internally I'll let you know!

**Comment by Prokhozhijj** [comment] 2022-10-31 19:33
Anthony,

Completely agree. Because of that I proposed my algorithm (see above please). You need to check which instance you are connecting to. And then act properly.

**Comment by anthony-tuininga** [comment] 2022-10-31 19:37
The problem is that v$instance is *also* only available to SYSDBA -- so you can't use that. You could use this:

```sql
select sys_context('userenv', 'instance_name') from dual;
```

I'm not sure when sys_context() was added, though.

**Comment by Prokhozhijj** [comment] 2022-10-31 19:52
> The problem is that v$instance is also only available to SYSDBA

Yes, you are right. I am constantly forgetting that. Sorry.

It looks ability to check `instance_name` was added in Oracle 10. And it works for +ASM instance and for standby db.

**Comment by zzzeek** [comment] 2022-10-31 22:56
OK so just so we all know what this is used for, there are a few generally unusual cases involving some nested subquery tests where, at least in the past, we were not able to get Oracle to maintain the type of a numeric value between integer and decimal, so in these very edge cases, we have an output type handler that sets it as STRING, and we look for a decimal point (a period) in the string.   This then doesn't work if someone has a locale that uses commas instead of periods.  So years ago when this was all done, we just check this parameter to see if we should be looking for a decimal point character other than a period.

Overall, it seems unlikely that the NLS_NUMERIC_CHARACTERS value would differ between v$nls_parameters and nls_session_parameters, nor is it that common that we even have this case where we need it come up.

But @anthony-tuininga reminds me of that same issue we keep slipping up on which is that the query against v$nls_parameters will fail if the login doesnt have SYSDBA, so yes it seems like we're going to have to do a fallback thing again where:

1. we look in nls_session_parameters
2. if exception is thrown, we'll look in v$nls_parameters
3. if exception is thrown, we just use a period for the decimal character, and likely emit a warning that we might have trouble parsing a numeric in some rare cases.
4. I should go and review the cases where this whole thing even comes up as the entire use case might not even be applicable anymore.

**Comment by anthony-tuininga** [comment] 2022-11-01 00:15
Note that since cx_Oracle 6, the value of NLS_NUMERIC_CHARACTERS does not affect how numbers are returned from the database. The only time that NLS_NUMERIC_CHARACTERS comes into play is when fetching a character representation of a number (such as is done by to_char()). cx_Oracle and the thick mode of python-oracledb also use this value when using an output type handler to specify that strings should be returned for numeric values in the database. Thin mode, however, does not use this value. For this reason I would recommend against its use and would suggest using Python code in an `outconverter` function instead -- if that is desirable. This is noted in the [documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/globalization.html#thin-mode-locale-aware-number-and-date-conversions). If you have questions, let me know!

**Comment by zzzeek** [comment] 2022-11-01 00:21
let me show you the query.... :)

**Comment by zzzeek** [comment] 2022-11-01 01:40
OK what we use it for is cases where the user has requested that a decimal value comes back as Python Decimal and not float, and we don't want any loss of precision.  so we have to parse the string.  It also seems to come into play with some cases prior to cx oracle 6, so we could in theory drop those.

**Comment by Prokhozhijj** [comment] 2022-11-01 04:01
Just in case. Just checked out. +ASM instance appeared in Oracle 10. And ability to check `instance_name` with `sys_context() ` also appeared in Oracle 10. So, for Oracle 8 or Oracle 9 you dont't have to check instance name, only `open_mode` in `v$database`. Maybe this info will be useful.

**Comment by anthony-tuininga** [comment] 2022-11-01 04:25
> OK what we use it for is cases where the user has requested that a decimal value comes back as Python Decimal and not float, and we don't want any loss of precision. so we have to parse the string. It also seems to come into play with some cases prior to cx oracle 6, so we could in theory drop those.

Starting with cx_Oracle 6, numbers are parsed from the internal decimal representation when being converted to string or decimal.Decimal -- bypassing the requirement for NLS_NUMERIC_CHARACTERS. So as long as you don't need support for cx_Oracle 5 I don't think you need to concern yourself with that value. If you have questions about that, you can point me to the relevant code in SQLAlchemy and I can take a closer look.

**Comment by zzzeek** [comment] 2022-11-01 12:50
OK this is the issue we have where we resort to string parsing.

these two queries:

    SELECT 5.66 FROM DUAL

    SELECT 1 FROM DUAL

Both return no information in the outputtype handler as to if these values are integers or numerics:

```
print(f"{default_type}, {precision}, {scale}")
```

illustrates:

```
<cx_Oracle.DbType DB_TYPE_NUMBER>, 0, -127
<cx_Oracle.DbType DB_TYPE_NUMBER>, 0, -127
```

Therefore when we get the above pattern in ouputtypehandler, we set the handler to STRING and use our own function that looks for the decimal point, because we'd like to get *either* `Decimal` or `int` based on if the decimal point is present or not.

it looks like cx_Oracle is doing this but it's returning `float` and `int`.   Is there an outputtypehandler we can use that will turn `float` into `Decimal`, but retain the `int` value?

**Comment by zzzeek** [comment] 2022-11-01 18:23
> Yes, if the preferred numeric type is integer, then if the number is an integer it will be returned as such, otherwise it will be returned as a float. There is no current way to have the float exchanged for a decimal value instead. You will indeed have to check the string for the decimal point.

wow I am doing something correctly

> 
> You can avoid checking the value of NLS_NUMERIC_CHARACTERS, however. You can simply execute this script:
> 
> ```python
> def output_type_handler(cursor, name, default_type, size, precision, scale):
>     if default_type == oracledb.DB_TYPE_NUMBER:
>         return cursor.var(str, arraysize=cursor.arraysize)
> 
> cursor.outputtypehandler = output_type_handler
> cursor.execute("select 3 / 2 from dual")
> ```
> 
> You can then examine the output. The second last character of the output will be the decimal point seprator -- whatever that has been set to. And you can then replace it with a period, if necessary, before passing it on to decimal.Decimal().

veeerry clever.   OK, I'll try to do that.

there's no undocumented ORACLE_DISABLE_UGLY_FRACTIONS mode, I am assuming!  :)


> Of course, if someone can run the SQL statement `alter session set nls_numeric_characters='XY'` the value can change. 

Yes we don't support people doing anything like that, we just need to do upfront checks for how the connection is set up.   Not surprisingly we had actual users in Germany who encountered decimal issue when we started parsing the string assuming a dot. :).  There's no way a USian like me would have ever guessed that issue would occur.

> Note that thin mode pays no attention to the value of NLS_NUMERIC_CHARACTERS. It will always return the period as the decimal point in string representations of the number. Only thick mode (and cx_Oracle) pay attention to this value.

oh!   So...then I really *have* to use your method then.     and even more "oh!" it looks like our test for this part of things is marked as "fail" for oracledb thin client already!   cc @CaselIT   so we can fix all of that here.  OK

**Comment by anthony-tuininga** [comment] 2022-11-01 19:24
> > Yes, if the preferred numeric type is integer, then if the number is an integer it will be returned as such, otherwise it will be returned as a float. There is no current way to have the float exchanged for a decimal value instead. You will indeed have to check the string for the decimal point.

> wow I am doing something correctly (edit: not quite! dang)

To be clear, you need an output type handler to specify that you want integers returned, like this:

```python
def output_type_handler(cursor, name, default_type, size, precision, scale):
    if default_type == oracledb.DB_TYPE_NUMBER:
        return cursor.var(int, arraysize=cursor.arraysize)
```

This sets the preferred numeric type as integer and then only numbers with decimal points will be returned as floats.

> there's no undocumented ORACLE_DISABLE_UGLY_FRACTIONS mode, I am assuming! :)

No such thing. :-)

Looks like you have a path forward that can solve the OP issue as well as the failing test case for thin mode of python-oracledb. Win, win! :-)

**Comment by zzzeek** [comment] 2022-11-01 19:45
Yes I have a repaired version going through.  Oracledb was actually working as we didn't treat the decimal character as "absolute", the test was just checking what it detects, so I've adjusted that to assert we get what's expected for both drivers.

**Comment by zzzeek** [comment] 2022-11-01 21:04
on one of my CI machines, OracleDB is returning a string like:

"01.1"

whereas other machines return:

"1.1"

any idea on that?  I will adjust for the leading zeroes but that's strange.

**Comment by anthony-tuininga** [comment] 2022-11-01 21:32
Issue corrected.

**Comment by CaselIT** [comment] 2022-11-02 09:30
> oh! So...then I really _have_ to use your method then. and even more "oh!" it looks like our test for this part of things is marked as "fail" for oracledb thin client already! cc @CaselIT so we can fix all of that here. OK

it was marked as fails since thin mode does not use nls variables, and the test was testing that part in particular.

**Closed** 2022-11-02 16:57 UTC
Labels: awaiting info, use case

**Comment by CaselIT** [comment] 2022-11-02 20:49
> 766d329f83cd7a2f65114cf5a628087bbfef151c

well that's one way of solving this problem :)
