### ISSUE TITLE
Connection using mssql+pyodbc with create_engine on version major than 1.4.15 fails

### ISSUE THREAD

**Issue by lgonzalezsa** [sqlalchemy/sqlalchemy#8028] opened 2022-05-17 02:34 UTC
### Describe the bug

Stuck to sqlalchemy version 1.4.15 due to connection string error with logic timeout expired.

```
OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
If I use any version bigger than 1.4.15 fails, already reviewed pyodbc, but if I downgrade the sqlalchemy package to 1.4.15 everything `works.`

### To Reproduce

```python
In my case, creating a connection string with any version bigger than 1.4.15 and the password contains symbol @, the create_engine returns something like this:

Engine(mssql+pyodbc://the_user:***@naly@sis2@FQDN:PORT/tempdb?driver=ODBC+Driver+for+SQL+Server)
```

### Error

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3256, in Engine._wrap_pool_connect(self, fn, connection)
   3255 try:
-> 3256     return fn()
   3257 except dialect.dbapi.Error as e:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:310, in Pool.connect(self)
    303 """Return a DBAPI connection from the pool.
    304 
    305 The connection is instrumented such that when its
   (...)
    308 
    309 """
--> 310 return _ConnectionFairy._checkout(self)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:868, in _ConnectionFairy._checkout(cls, pool, threadconns, fairy)
    867 if not fairy:
--> 868     fairy = _ConnectionRecord.checkout(pool)
    870     fairy._pool = pool

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:476, in _ConnectionRecord.checkout(cls, pool)
    474 @classmethod
    475 def checkout(cls, pool):
--> 476     rec = pool._do_get()
    477     try:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:146, in QueuePool._do_get(self)
    145         with util.safe_reraise():
--> 146             self._dec_overflow()
    147 else:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:143, in QueuePool._do_get(self)
    142 try:
--> 143     return self._create_connection()
    144 except:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:256, in Pool._create_connection(self)
    254 """Called by subclasses to create a new ConnectionRecord."""
--> 256 return _ConnectionRecord(self)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:371, in _ConnectionRecord.__init__(self, pool, connect)
    370 if connect:
--> 371     self.__connect()
    372 self.finalize_callback = deque()

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:666, in _ConnectionRecord.__connect(self)
    665     with util.safe_reraise():
--> 666         pool.logger.debug("Error on connect(): %s", e)
    667 else:
    668     # in SQLAlchemy 1.4 the first_connect event is not used by
    669     # the engine, so this will usually not be set

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:661, in _ConnectionRecord.__connect(self)
    660 self.starttime = time.time()
--> 661 self.dbapi_connection = connection = pool._invoke_creator(self)
    662 pool.logger.debug("Created new connection %r", connection)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/create.py:590, in create_engine.<locals>.connect(connection_record)
    589             return connection
--> 590 return dialect.connect(*cargs, **cparams)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/default.py:597, in DefaultDialect.connect(self, *cargs, **cparams)
    595 def connect(self, *cargs, **cparams):
    596     # inherits the docstring from interfaces.Dialect.connect
--> 597     return self.dbapi.connect(*cargs, **cparams)

OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
Input In [21], in <cell line: 1>()
----> 1 with dev_engine.begin() as connection:
      2     PH.to_sql('#tttest1_no_closing_conn',connection, if_exists='replace')

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3038, in Engine.begin(self, close_with_result)
   3036     conn = self.connect()
   3037 else:
-> 3038     conn = self.connect(close_with_result=close_with_result)
   3039 try:
   3040     trans = conn.begin()

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3210, in Engine.connect(self, close_with_result)
   3195 def connect(self, close_with_result=False):
   3196     """Return a new :class:`_engine.Connection` object.
   3197 
   3198     The :class:`_engine.Connection` object is a facade that uses a DBAPI
   (...)
   3207 
   3208     """
-> 3210     return self._connection_cls(self, close_with_result=close_with_result)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:96, in Connection.__init__(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events, _allow_revalidate)
     91     self._has_events = _branch_from._has_events
     92 else:
     93     self._dbapi_connection = (
     94         connection
     95         if connection is not None
---> 96         else engine.raw_connection()
     97     )
     99     self._transaction = self._nested_transaction = None
    100     self.__savepoint_seq = 0

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3289, in Engine.raw_connection(self, _connection)
   3267 def raw_connection(self, _connection=None):
   3268     """Return a "raw" DBAPI connection from the connection pool.
   3269 
   3270     The returned object is a proxied version of the DBAPI
   (...)
   3287 
   3288     """
-> 3289     return self._wrap_pool_connect(self.pool.connect, _connection)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3259, in Engine._wrap_pool_connect(self, fn, connection)
   3257 except dialect.dbapi.Error as e:
   3258     if connection is None:
-> 3259         Connection._handle_dbapi_exception_noconnection(
   3260             e, dialect, self
   3261         )
   3262     else:
   3263         util.raise_(
   3264             sys.exc_info()[1], with_traceback=sys.exc_info()[2]
   3265         )

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:2106, in Connection._handle_dbapi_exception_noconnection(cls, e, dialect, engine)
   2104     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2105 elif should_wrap:
-> 2106     util.raise_(
   2107         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2108     )
   2109 else:
   2110     util.raise_(exc_info[1], with_traceback=exc_info[2])

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3256, in Engine._wrap_pool_connect(self, fn, connection)
   3254 dialect = self.dialect
   3255 try:
-> 3256     return fn()
   3257 except dialect.dbapi.Error as e:
   3258     if connection is None:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:310, in Pool.connect(self)
    302 def connect(self):
    303     """Return a DBAPI connection from the pool.
    304 
    305     The connection is instrumented such that when its
   (...)
    308 
    309     """
--> 310     return _ConnectionFairy._checkout(self)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:868, in _ConnectionFairy._checkout(cls, pool, threadconns, fairy)
    865 @classmethod
    866 def _checkout(cls, pool, threadconns=None, fairy=None):
    867     if not fairy:
--> 868         fairy = _ConnectionRecord.checkout(pool)
    870         fairy._pool = pool
    871         fairy._counter = 0

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:476, in _ConnectionRecord.checkout(cls, pool)
    474 @classmethod
    475 def checkout(cls, pool):
--> 476     rec = pool._do_get()
    477     try:
    478         dbapi_connection = rec.get_connection()

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:146, in QueuePool._do_get(self)
    144     except:
    145         with util.safe_reraise():
--> 146             self._dec_overflow()
    147 else:
    148     return self._do_get()

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     68     self._exc_info = None  # remove potential circular references
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:
     75     if not compat.py3k and self._exc_info and self._exc_info[1]:
     76         # emulate Py3K's behavior of telling us when an exception
     77         # occurs in an exception handler.

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:143, in QueuePool._do_get(self)
    141 if self._inc_overflow():
    142     try:
--> 143         return self._create_connection()
    144     except:
    145         with util.safe_reraise():

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:256, in Pool._create_connection(self)
    253 def _create_connection(self):
    254     """Called by subclasses to create a new ConnectionRecord."""
--> 256     return _ConnectionRecord(self)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:371, in _ConnectionRecord.__init__(self, pool, connect)
    369 self.__pool = pool
    370 if connect:
--> 371     self.__connect()
    372 self.finalize_callback = deque()

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:666, in _ConnectionRecord.__connect(self)
    664 except Exception as e:
    665     with util.safe_reraise():
--> 666         pool.logger.debug("Error on connect(): %s", e)
    667 else:
    668     # in SQLAlchemy 1.4 the first_connect event is not used by
    669     # the engine, so this will usually not be set
    670     if pool.dispatch.first_connect:

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     68     self._exc_info = None  # remove potential circular references
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:
     75     if not compat.py3k and self._exc_info and self._exc_info[1]:
     76         # emulate Py3K's behavior of telling us when an exception
     77         # occurs in an exception handler.

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/pool/base.py:661, in _ConnectionRecord.__connect(self)
    659 try:
    660     self.starttime = time.time()
--> 661     self.dbapi_connection = connection = pool._invoke_creator(self)
    662     pool.logger.debug("Created new connection %r", connection)
    663     self.fresh = True

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/create.py:590, in create_engine.<locals>.connect(connection_record)
    588         if connection is not None:
    589             return connection
--> 590 return dialect.connect(*cargs, **cparams)

File /opt/conda/envs/test_dev/lib/python3.9/site-packages/sqlalchemy/engine/default.py:597, in DefaultDialect.connect(self, *cargs, **cparams)
    595 def connect(self, *cargs, **cparams):
    596     # inherits the docstring from interfaces.Dialect.connect
--> 597     return self.dbapi.connect(*cargs, **cparams)

OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/14/e3q8)
``` 

### Versions

- OS: openSUSE Leap 15.3
- Python: 3.9.12
- SQLAlchemy: 1.4.32
- Database: MS SQL 2016
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

**Comment by zzzeek** [comment] 2022-05-17 02:53
dupe of #6574, #6567, #6568

URL escape @ signs in passwords as documented to resolve 

see docs at https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=password#database-urls

**Closed by zzzeek** 2022-05-17 02:53 UTC
Labels: duplicate, SQL Server, expected behavior
