### ISSUE TITLE
SHOW VARIABLES is inefficient and slow (and contended on MySQL 8.0), and @@variable reads should be used instead

### ISSUE THREAD

**Issue by midom** [sqlalchemy/sqlalchemy#7518] opened 2021-12-30 19:34 UTC
### Describe the bug

SQL Alchemy is running various [SHOW VARIABLES](https://github.com/sqlalchemy/sqlalchemy/blob/54875c21601eaca01e3217d5b22fab6f6cf50992/lib/sqlalchemy/dialects/mysql/base.py#L3083) commands, which has multiple problems:

* In general, server-side implementation is much less efficient than fetching variables directly using syntax like `SELECT @@variable` - taking milliseconds of CPU time, instead of being somewhat instant.
* There's severe mutex contention in newer MySQL versions (8.0.*), because this command acquires plugin lock inside MySQL, therefore only hundreds of connections/s can be established. 
* There are multiple queries being done for different variables, instead of single SELECT @var1, @var2, @var3 query, which would eliminate multiple roundtrips when talking to remote database server.

I recognize this code has been around 2006, and over that time the SHOW VARIABLES performance was regressing at various paces, but currently it is reaching a point where it may be a cause of SQLAlchemy-based system outages. 

### To Reproduce

```python
have many clients connecting to MySQL
```

### Error

timeouts, proxy markdowns, whatever else

### Versions

- OS: any
- Python: any
- SQLAlchemy: any, since 2006
- Database: mysql8
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mysqlclient

**Comment by zzzeek** [comment] 2021-12-30 19:39
hey there -

not sure what the issue is here, these SHOW VARIABLES queries are emitted exactly once per engine, and as engines are created only once per application, this is referring to an amount of time spent that is probably less than what the application spends just importing modules.

Are you using an antipattern such as running create_engine() for every connection?  these SHOW VARIABLES commands would be the least of the issues if so.

**Comment by zzzeek** [comment] 2021-12-30 19:41
> but currently it is reaching a point where it may be a cause of SQLAlchemy-based system outages.

unless your database is hung completely, in which case no SQL query is going to work, there is no way imaginable that the small set of SHOW VARIABLES commands emitted on startup would in any way be involved with an outage.

**Comment by zzzeek** [comment] 2021-12-30 19:45
> There's severe mutex contention in newer MySQL versions (8.0.*), because this command acquires plugin lock inside MySQL, therefore only hundreds of connections/s can be established.

can you provide background on this mutex contention?   again, this would refer to hundreds of individual python processes being created per second, is this like a remote commandline client that end users are running against a remote MySQL database type of thing?

**Comment by zzzeek** [comment] 2021-12-30 19:48
just to note, these are the SHOW VARIABLES commands , there are only three if you include "SHOW COLLATION", and they run exactly once per create_engine() call:

```
"SHOW VARIABLES LIKE 'lower_case_table_names'"
"SHOW VARIABLES LIKE 'sql_mode'"
"SHOW COLLATION"
```

**Comment by midom** [comment] 2021-12-30 19:58
> can you provide background on this mutex contention? again, this would refer to hundreds of individual python processes being created per second, is this like a remote commandline client that end users are running against a remote MySQL database type of thing?

[this is the mutex](https://github.com/mysql/mysql-server/blob/3290a66c89eb1625a7058e0ef732432b6952b435/storage/perfschema/pfs_variable.cc#L199) one slams into when running SHOW VARIABLES

we may have hundreds (or thousands) of individual python processes created, and as generally one can take tens of thousands of new connections a second, this SHOW VARIABLES use reduces new connection performance by 100x.

**Comment by midom** [comment] 2021-12-30 19:59
(on our side clients are coming from a system called "dataswarm", and as the name implies, it is a swarm of clients!)

**Comment by zzzeek** [comment] 2021-12-30 20:00
> (on our side clients are coming from a system called "dataswarm", and as the name implies, it is a swarm of clients!)

OK that was my question!  great.  PRs welcome to move these SHOW VARIABLES calls into SELECT @@variable, this is likely supported by all currently suppored MySQLs.

**Comment by zzzeek** [comment] 2021-12-30 20:01
also how do we confirm `SELECT @@variable` is guaranteed to not have such mutexing on all mysql / mariadb platforms ?

**Comment by midom** [comment] 2021-12-30 20:03
the mutex in question is guarding new variables being added or removed by plugins - but these are server internal variables and don't need any plugin locking to access them, as there's no override functionality. 

Also, connectors like Connector/J, Rust, etc - all use the @@global.blah and @@session.blah syntax, and are not hitting these issues - so it would be noticed if those paths were expensive. 
I reviewed the clients that are hitting our DB fleet and it is just SQLAlchemy doing this.

**Comment by CaselIT** [comment] 2021-12-30 20:18
> just to note, these are the SHOW VARIABLES commands , there are only three if you include "SHOW COLLATION", and they run exactly once per create_engine() call:
> 
> ```
> "SHOW VARIABLES LIKE 'lower_case_table_names'"
> "SHOW VARIABLES LIKE 'sql_mode'"
> "SHOW COLLATION"
> ```
> 
> 
> 
> 

What would be the syntax to use to replace these queries?

**Comment by midom** [comment] 2021-12-30 20:21
SHOW COLLATION lists all collations and does not have the mutex problem, but one can do simply:
`select @@lower_case_table_names, @@sql_mode, @@collation_connection`
Not sure you want to read the full list of all collations all the time, but if you need it, you can keep the 'SHOW COLLATION' around.

**Comment by zzzeek** [comment] 2021-12-30 20:53
this would be much more trivial to implement as two separate "SELECT @@variable" calls, in the same structure that's present now.  there's no mutex, so there should be no issue?

**Comment by midom** [comment] 2021-12-30 20:56
I understand the triviality of the separate @@variable selects. Our clients are very special snowflakes as we operate a multi-datacenter environment and they do cross the ocean here and there, hence reducing the number of roundtrips is always a welcome development, so I was trying to sneak in that optimization too :-D 

From the server-side perspective, all we need is the "SHOW VARIABLES" to go away.

**Comment by zzzeek** [comment] 2021-12-30 20:56
in fact it's likely not that hard to pickle the dialect element of an engine for this purpose.

**Comment by zzzeek** [comment] 2021-12-30 21:00
merging them together looks like:

``diff
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index 5be0574954..8d11525e61 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -2669,9 +2669,8 @@ class MySQLDialect(default.DefaultDialect):
 
     def initialize(self, connection):
         self._connection_charset = self._detect_charset(connection)
-        self._detect_sql_mode(connection)
+        self._detect_casing_and_sql_mode(connection)
         self._detect_ansiquotes(connection)
-        self._detect_casing(connection)
         if self._server_ansiquotes:
             # if ansiquotes == True, build a new IdentifierPreparer
             # with the new setting
```

however, I just noticed that we are using a DBAPI level function to get the charset:

```py
    def _detect_charset(self, connection):
        """Sniff out the character set in use for connection results."""

        try:
            # note: the SQL here would be
            # "SHOW VARIABLES LIKE 'character_set%%'"
            cset_name = connection.connection.character_set_name
        except AttributeError:
            util.warn(
                "No 'character_set_name' can be detected with "
                "this MySQL-Python version; "
                "please upgrade to a recent version of MySQL-Python.  "
                "Assuming latin1."
            )
            return "latin1"
        else:
            return cset_name()
```

what query is mysqlclient emitting for that?    again we'd prefer to use the DBAPIs function for this.

**Comment by zzzeek** [comment] 2021-12-30 21:03
mysqlclient is doing this API call: https://dev.mysql.com/doc/c-api/8.0/en/mysql-character-set-name.html   we would hope mysql 8 implements this without any mutexing

**Comment by sqla-tester** [comment] 2021-12-30 22:33
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Imrpove MySQL/MariaDB dialect initialization.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3445

**Comment by CaselIT** [comment] 2021-12-30 22:37
@midom a review of the linked gerrit would be appreciated. Thanks!

**Comment by midom** [comment] 2022-01-03 22:59
looks fine!

**Comment by zzzeek** [comment] 2022-02-04 02:17
this has caused a regression for users reading from old MySQL versions older than 5.6.  I think it should be fixed

**Comment by sqla-tester** [comment] 2022-02-04 02:58
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fall back to SHOW VARIABLES for MySQL < 5.6** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3572

**Comment by sqla-tester** [comment] 2022-02-04 02:58
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**fall back to SHOW VARIABLES for MySQL < 5.6** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3573

**Closed** 2022-02-04 20:38 UTC
Labels: mysql, easy, engine, performance
