### ISSUE TITLE
SQLAlchemyError._message() forces exception message to unicode() inapproprately in py2k 

### ISSUE THREAD

**Issue by piotr-dobrogost** [sqlalchemy/sqlalchemy#4429] opened 2019-01-08 12:00 UTC
In rel_1_3_0b1 `SQLAlchemyError._message()` [looks](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_0b1/lib/sqlalchemy/exc.py#L39-L45) like this:

```python
    def _message(self):
        # get string representation just like Exception.__str__(self),
        # but also support if the string has non-ascii chars
        if len(self.args) == 1:
            return compat.text_type(self.args[0])
        else:
            return compat.text_type(self.args)
```
With Python 2 `compat.text_type` is `unicode` and as the default encoding in Python 2 is `ascii` if `self.args[0]` contains non-ascii chars the result will be `UnicodeDecodeError: 'ascii' codec can't decode byte … in position …: ordinal not in range(128)`. This is not in line with the comment stating that non-ascii chars are supported.

**Comment by zzzeek** [comment] 2019-01-08 20:58
in #4430 (can we make these just one issue since they are closely related?)  you said "Looking at implementation of __str()__ in StatementError class it seems there is nothing which would prevent using unicode format string instead of str one when constructing return value thus resolving the issue." which seems like a proposal for a fix.

it would make things easier for me if you could either show me a complete test case showing a problem to resolve or could propose how you see the code being fixed.   the former is more generally useful since I can also make that the test.

**Comment by zzzeek** [comment] 2019-01-08 21:05
See here is what I mean:

```
# coding: utf-8

from sqlalchemy import exc

message = u"méil"

def illustrate_plain_python():
    obj = Exception(message)
    try:
        print(obj)
    except Exception as e:
        print("illustate plain raised: %s" % e)

def illustrate_sqlalchemy_exc():
    obj = exc.SQLAlchemyError(message)
    try:
        print(obj)
    except Exception as e:
        print("illustate sqlalchemy exception raised: %s" % e)


illustrate_plain_python()
illustrate_sqlalchemy_exc()
```

run in Python 2:

```
illustate plain raised: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
illustate sqlalchemy exception raised: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

```

behavior is identical.  Where's the bug that's specific to SQLAlchemy ?    the comment inside of private message _message() is not particularly useful but that's a private method anyway.

**Comment by zzzeek** [comment] 2019-01-09 14:17
just for issues of management i want to keep this all on #4430 so we can figure out what the canonical approach is for this.

**Comment by marc1n** [comment] 2019-01-10 12:03
The illustration for this problem is the code

```python
# coding: utf-8

from sqlalchemy import exc

message = "méil"

def illustrate_plain_python():
    obj = Exception(message)
    try:
        print(obj)
    except Exception as e:
        print("illustate plain raised: %s" % e)

def illustrate_sqlalchemy_exc():
    obj = exc.SQLAlchemyError(message)
    try:
        print(obj)
    except Exception as e:
        print("illustate sqlalchemy exception raised: %s" % e)


illustrate_plain_python()
illustrate_sqlalchemy_exc()
```

run in Python 2:
```
méil
illustate sqlalchemy exception raised: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by zzzeek** [comment] 2019-01-10 15:41
the case that @mekk gave me for https://github.com/sqlalchemy/sqlalchemy/issues/4430#issuecomment-452649543 is not reproducing here, maybe because this is oracle express or something:
```

$ NLS_LANG="POLISH_POLAND.AL32UTF8" python
Python 3.7.0 (default, Jun 28 2018, 10:59:55) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> cx_Oracle.connect(user="nobody", password="nopass", dsn="127.0.0.1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-12541: TNS:no listener

```

is there another setting I can change to get it to spit out non-american messages?   I'd like to see if i can even get the test suite to run like that.

**Comment by zzzeek** [comment] 2019-01-10 16:16
OK here is major scientific discovery number one:

```
#! coding: utf-8

raise Exception(u"select méil FROM dual")

```

```
~/.venv2/bin/python2 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    raise Exception(u"select méil FROM dual")
Exception: <exception str() failed>

```

wow!   you can't put a u'' in a Python 2 exception with non-ascii chars (I'm assuming this is based on my platform settings)!  

so the choices are:

1. pass through bytestrings direclty

2. convert to a u'' but use ascii with errors="replace"

so...#1 is a bigger change, but that passes the characters right through.   #2 is a much safer change but you'd get ugly looking error messages.

**Comment by zzzeek** [comment] 2019-01-10 16:19
this is the simplest change:

```
    def _message(self):

        if len(self.args) == 1:
            msg = self.args[0]
        else:
            msg = self.args

        return msg

```

so...why isnt that what it is?   so I need to look in the history because I'm 99% sure that text_type() is there because someone reported a bug about 8 years ago

**Comment by zzzeek** [comment] 2019-01-10 16:26
mind blown, not a bug report, not eight years old, just a 1.2 regression in 064f82986c, no tests to see that it broke.    

I prefer very much if folks can just show me the code that's "not working" up front, that can save a lot of time, thanks!

**Comment by marc1n** [comment] 2019-01-10 16:56
I don't really know if `exc.SQLAlchemyError` with unicode message is anywhere raised by sqlalchemy. 

But it seems that `SQLAlchemyError.__str__` should returns `str` and `SQLAlchemyError.__unicode__` should return `unicode` in both cases:  `exc.SQLAlchemyError("non_ascii_bytes: ą")` and `exc.SQLAlchemyError(u"non_ascii_unicode: ą")`.

**Comment by sqla-tester** [comment] 2019-01-10 17:05
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Leave bytestring exception messages as bytestrings** https://gerrit.sqlalchemy.org/1087

**Comment by sqla-tester** [comment] 2019-01-10 17:05
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Leave bytestring exception messages as bytestrings** https://gerrit.sqlalchemy.org/1088

**Comment by zzzeek** [comment] 2019-01-10 17:06
I think `__unicode__` should probably come out, Python Exception doesn't have it

**Comment by marc1n** [comment] 2019-01-10 17:10
> OK here is major scientific discovery number one:
> wow! you can't put a u'' in a Python 2 exception with non-ascii chars (I'm assuming this is based on my platform settings)!

I think this is not problem with exception object but in printing such exception - print statement calls `str` on printed object. `Exception.__str__` returns `str(self.args[0])` or `str(self.args)` depending on len(args). Another suprising fact is that `raise Exception(u"méil", u"méil")` works!

> so the choices are:
> 
>     1. pass through bytestrings direclty
>     2. convert to a u'' but use ascii with errors="replace"

Maybe 3: convert to a u'' but use **utf-8** with errors="replace".

**Comment by zzzeek** [comment] 2019-01-10 17:15
I believe 3 is what pymysql and mysqlclient do, however psycopg2 and cx_oracle are sending through plain bytes, and on my terminal, that works fine because even though my Python is doing ascii, my console can understand the utf-8 characters my tests are getting.  someone in Poland will have a terminal that can print those characters.  So this is really the old school, pre-unicode Python 2 of working and apparently thats how it was working here up until version 1.2 when I arbitrarily changed it, that was a mistake.

**Comment by zzzeek** [comment] 2019-01-10 17:17
@marc1n if you can confirm this makes your local case work, this is basically reverting the unicode part of 064f829 .   

```diff
--- a/lib/sqlalchemy/exc.py
+++ b/lib/sqlalchemy/exc.py
@@ -13,8 +13,6 @@ raised as a result of DBAPI exceptions are all subclasses of
 
 """
 
-from .util import compat
-
 
 class SQLAlchemyError(Exception):
     """Generic error class."""
@@ -40,9 +38,9 @@ class SQLAlchemyError(Exception):
         # get string representation just like Exception.__str__(self),
         # but also support if the string has non-ascii chars
         if len(self.args) == 1:
-            return compat.text_type(self.args[0])
+            return self.args[0]
         else:
-            return compat.text_type(self.args)
+            return self.args
 
     def __str__(self):
         message = self._message()
@@ -52,9 +50,6 @@ class SQLAlchemyError(Exception):
 
         return message
 
-    def __unicode__(self):
-        return self.__str__()
-
 
 class ArgumentError(SQLAlchemyError):
     """Raised when an invalid or conflicting function argument is supplied.

```

**Comment by Mekk** [comment] 2019-01-10 18:32
To reproduce my case you must install „true” Oracle client, Express doesn't have localized error messages, so produces English messages.
Regarding errors="replace": give Russian or Chinese variation of the error a try ;-)

**Comment by Mekk** [comment] 2019-01-10 18:35
On machine which reproduces the problem:
```
$ ls $ORACLE_HOME/nls/mesg/
lxeus.msb   lxlahu.msb   lxlaru.msb   lxltdk.msb  lxltn.msb    lxltus.msb   lxtei.msb    lxtesf.msb
lxeus.msg   lxlai.msb    lxlasf.msb   lxltd.msb   lxltpl.msb   lxltzhs.msb  lxteiw.msb   lxtesk.msb
lxius.msb   lxlaiw.msb   lxlask.msb   lxltel.msb  lxltptb.msb  lxltzht.msb  lxteja.msb   lxtes.msb
lxius.msg   lxlaja.msb   lxlas.msb    lxlte.msb   lxltpt.msb   lxtear.msb   lxteko.msb   lxteth.msb
lxlaar.msb  lxlako.msb   lxlath.msb   lxltf.msb   lxltro.msb   lxtecs.msb   lxtenl.msb   lxtetr.msb
lxlacs.msb  lxlanl.msb   lxlatr.msb   lxlthu.msb  lxltru.msb   lxtedk.msb   lxten.msb    lxteus.msb
lxladk.msb  lxlan.msb    lxlaus.msb   lxlti.msb   lxltsf.msb   lxted.msb    lxtepl.msb   lxtezhs.msb
lxlad.msb   lxlapl.msb   lxlazhs.msb  lxltiw.msb  lxltsk.msb   lxteel.msb   lxteptb.msb  lxtezht.msb
lxlael.msb  lxlaptb.msb  lxlazht.msb  lxltja.msb  lxlts.msb    lxtee.msb    lxtept.msb
lxlae.msb   lxlapt.msb   lxltar.msb   lxltko.msb  lxltth.msb   lxtef.msb    lxtero.msb
lxlaf.msb   lxlaro.msb   lxltcs.msb   lxltnl.msb  lxlttr.msb   lxtehu.msb   lxteru.msb
```
On machine with Express, which does not, I have:
```
$ ls $ORACLE_HOME/nls/mesg/
lxeus.msb  lxlaja.msb   lxlaus.msb   lxltja.msb   lxltus.msb   lxteja.msb   lxteus.msb
lxius.msb  lxlaptb.msb  lxlazhs.msb  lxltptb.msb  lxltzhs.msb  lxteptb.msb  lxtezhs.msb
```
(so looks like mayhaps one could try Chinese or Portugal to reproduce problem on Express)

**Comment by Mekk** [comment] 2019-01-10 18:42
I managed to reproduce my case on Oracle Express. Try

NLS_LANG="SIMPLIFIED CHINESE_CHINA.ZHS16GBK"

This gives:

>>> str(e)
'(cx_Oracle.DatabaseError) ORA-12541: TNS: \xce\xde\xbc\xe0\xcc\xfd\xb3\xcc\xd0\xf2\n'
>>> unicode(e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 42: ordinal not in range(128)

**Comment by Mekk** [comment] 2019-01-10 18:53
So to summarize, the following testcase illustrates the problem even on Express:
```
NLS_LANG="SIMPLIFIED CHINESE_CHINA.ZHS16GBK"
```
and then
```
import sqlalchemy
try:
    sqlalchemy.create_engine("oracle://nobody:nopass@127.0.0.1").connect()
.except Exception as err:
     x = unicode(err)
```

**Comment by zzzeek** [comment] 2019-01-10 18:53
> I managed to reproduce my case on Oracle Express. Try
> 
> ```
> NLS_LANG="SIMPLIFIED CHINESE_CHINA.ZHS16GBK"
> ```
> 
> This gives:
> 
> ```
> >>> str(e)
> '(cx_Oracle.DatabaseError) ORA-12541: TNS: \xce\xde\xbc\xe0\xcc\xfd\xb3\xcc\xd0\xf2\n'
> >>> unicode(e)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 42: ordinal not in range(128)
> ```

yes that reproduces.  so with master Py2K, I get:

    sqlalchemy.exc.DatabaseError: <exception str() failed>

with my patch Py2K, I get:

    sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-12541: TNS: �޼������� (Background on this error at: http://sqlalche.me/e/4xp6)

ugly, but I get the exact same thing with plain cx_Oracle:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    cx_Oracle.connect(user="nobody", password="nobody", dsn="127.0.0.1")
cx_Oracle.DatabaseError: ORA-12541: TNS: �޼�������

```
in py3k, everything works because unicode objects are passed to py3k by cx_Oracle so Python can render the exception in my platform's correct enoding:

    sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-12541: TNS: 无监听程序 (Background on this error at: http://sqlalche.me/e/4xp6)

**Comment by Mekk** [comment] 2019-01-10 18:55
Yes, in py3 there is no problem, everything is unicode, I tested it earlier on on my cases also on full Oracle.

**Comment by marc1n** [comment] 2019-01-10 20:35
> @marc1n if you can confirm this makes your local case work, this is basically reverting the unicode part of [064f829](https://github.com/sqlalchemy/sqlalchemy/commit/064f82986ca3573b124fc88518e99d3d43874b61) .

The `__str__` is OK now. I think about removing `_message` completely, because not it looks like `Exception.__str__` implementation. Than `self._message()` call could be replaced to `super(SQLAlchemyError, self).__str__()`.

Could you consider keeping `__unicode__` with better implementation?
We often log with unicode messages (`logging.error(u'Exception: %s', exc)`) so it will be useful.

Sample implementation:

```python
class SQLAlchemyError(Exception):
  encoding = 'utf-8'

  def __unicode__(self):
    text_str = str(self)
    try:
      return text_str.decode(self.encoding)
    except UnicodeDecodeError:
      return repr(text_str)[1:-1].decode()
```

**Comment by piotr-dobrogost** [comment] 2019-01-10 21:02
> wow! you can't put a u'' in a Python 2 exception with non-ascii chars

This was raised on 2008-03-31 as issue [Error when printing an exception containing a Unicode string](https://bugs.python.org/issue2517) with Python and according to Benjamin Peterson it's because [*Python encodes it's error messages as ASCII by default*](https://bugs.python.org/issue2517#msg64771)

**Comment by zzzeek** [comment] 2019-01-10 21:51
> > @marc1n if you can confirm this makes your local case work, this is basically reverting the unicode part of [064f829](https://github.com/sqlalchemy/sqlalchemy/commit/064f82986ca3573b124fc88518e99d3d43874b61) .
> 
> The `__str__` is OK now. I think about removing `_message` completely, because it looks now like `Exception.__str__` implementation. Than `self._message()` call could be replaced to `super(SQLAlchemyError, self).__str__()`.
> 
> Could you consider keeping `__unicode__` with better implementation?
> We often log with unicode messages (`logging.error(u'Exception: %s', exc)`) so it will be useful.
> 
> Sample implementation:
> 
> ```python
> class SQLAlchemyError(Exception):
>   encoding = 'utf-8'
> 
>   def __unicode__(self):
>     text_str = str(self)
>     try:
>       return text_str.decode(self.encoding)
>     except UnicodeDecodeError:
>       return repr(text_str)[1:-1].decode()
> ```

the only problem is how can i assume utf-8 like that?   It's not always clear what encoding the database is sending messages with.    Being able to guess that, or passing through the "encoding" that might have been sent to create_engine() (which is not a commonly used parameter) would be more complicated than the fix I'm trying to get out for this issue right now.

**Comment by zzzeek** [comment] 2019-01-10 22:04
I can go with:

    return self.args[0].decode('utf-8', 'backslashreplace')

for the "wants unicode in py2k" case for now

**Comment by zzzeek** [comment] 2019-01-10 22:24
looks like backslashreplace is kind of broken on py2k so I see why you're doing it that way

**Comment by marc1n** [comment] 2019-01-10 22:51
Having `SQLAlchemyError.encoding` class attribute we can change it in our application (yeah, globally, but it is better that nothing). And (in the future) sqlalchemy could set `exc.encoding` before raising an exception when it knows an encoding of  message (ex. from engine or connection object).

**Comment by zzzeek** [comment] 2019-01-10 23:08
> Having `SQLAlchemyError.encoding` class attribute we can change it in our application (yeah, globally, but it's better than nothing). And (in the future) sqlalchemy could set `exc.encoding` before raising an exception when it knows the encoding of a message (ex. from engine or connection object).

I've got `__unicode__` in there now for you but adding an .encoding is way out of scope for this fix, that's a feature add, and that would have to be from the engine's encoding, plus tests, etc.  I need to get this fix through ASAP.     You can propose a ticket for "custom exception encoding under py2k" but py2k has only a year left of upstream support so I'm not sure how worthwhile that is.

**Comment by zzzeek** [comment] 2019-01-10 23:12
When the engine spins up DBAPIError, the dialect is there, so we would need to add another parameter to the DBAPIError / SQLAlhcemyError constructor for "encoding" and then DBAPIError.instance() can pass that in.  but again this is a feature add I'd rather leave for 1.3 however feel free to work on a pull request with tests.

**Comment by Mekk** [comment] 2019-01-10 23:22
My chinese example looks ugly because I randomly picked some chinese encoding. With
```
NLS_LANG="SIMPLIFIED CHINESE_CHINA.UTF8"
```
it looks well on utf-8 terminal:
```
>>> print(str(y))
(cx_Oracle.DatabaseError) ORA-12541: TNS: 无监听程序

>>> print(unicode(y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 42: ordinal not in range(128)
```
so probably this is friendlier way to write this test.

**Closed** 2019-01-11 03:43 UTC
Labels: bug, engine

**Comment by marc1n** [comment] 2019-01-11 23:55
Thank you @zzzeek for your great work!

**Comment by piotr-dobrogost** [comment] 2019-01-14 10:35
Thank you @zzzeek !
