### ISSUE TITLE
enum checkfirst does not consult schema translate map

### ISSUE THREAD

**Issue by robertmuil** [sqlalchemy/sqlalchemy#5520] opened 2020-08-18 23:11 UTC
**Describe the bug**
If the `schema_translation_map` is used with the engine, to support multiple schemas at runtime, then the use of an Enum within the ORM paradigm will generate a `type <name> already exists`.

Setting the `create_type` of the ENUM to False will allow it to succeed but **only if used in a single column**. I suspect there might be two bugs here:
1. that the `create_type=False` of an ENUM is not being properly honoured
2. that the check for existence of a type is not working in the case of a schema_translation_map

**Expected behavior**
Expect the enum to be created **once, and once only** with a `CREATE TYPE` statement.
Instead, multiple of these statements are issued, causing postgres to complain that it already exists.

**To Reproduce**

```py
import enum
from sqlalchemy.exc import ProgrammingError
from sqlalchemy.schema import CreateSchema, DropSchema
from sqlalchemy import Column, Integer, String, create_engine, Sequence
from sqlalchemy.engine import Connection
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.dialects.postgresql import ENUM

DB_URL = 'postgres://<user>:<password>@<host>/<database>'

class Mood(enum.Enum):
    sad = 1
    ok = 2
    happy = 3

engine = create_engine(DB_URL, echo=True)

schema_name = 'minimal_failing_example'

engine.execute(CreateSchema(schema_name))

Base = declarative_base()

mood_enum = ENUM(Mood, schema=Base.metadata.schema)
# 2nd alternative:
# mood_enum = ENUM(Mood, schema=Base.metadata.schema), create_type=False)

class Person(Base):
    __tablename__ = 'person'
    id = Column(Integer, Sequence('pid_seq'), primary_key=True)
    name = Column(String, nullable=False)
    dominant_mood = Column(mood_enum, nullable=True)
    #2nd alternative:
    # current_mood = Column(mood_enum, nullable=True)

conn: Connection = engine.connect().execution_options(schema_translate_map={None: schema_name})

try:
    Base.metadata.create_all(bind=conn)
except ProgrammingError as ex:
    engine.execute(DropSchema(schema_name, cascade=True))
    raise ex
```

**Error**

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateObject: type "mood" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robert_muil/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_9.py", line 51, in <module>
    raise ex
  File "/Users/robert_muil/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_9.py", line 48, in <module>
    Base.metadata.create_all(bind=conn)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4546, in create_all
    bind._run_visitor(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1657, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
    self.traverse_single(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 811, in visit_table
    table.dispatch.before_create(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 645, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1575, in _on_table_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1510, in create
    bind.execute(CreateEnumType(self))
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/anaconda3/envs/datacat/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) type "mood" already exists

[SQL: CREATE TYPE minimal_failing_example.mood AS ENUM ('sad', 'ok', 'happy')]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: `MacOS Catalina 10.15.6`
 - Python: `3.8`
 - SQLAlchemy: `1.3.18`
 - Database: `PostgreSQL 12.3`
 - DBAPI: `org.postgresql:postgresql:RELEASE 42.2.5`

**Additional context**

Regardless of the actual issue, I think that the following code, from lines 1565-1572 in `base.py` are incorrect:
```py
        if (
            checkfirst
            or (
                not self.metadata
                and not kw.get("_is_metadata_operation", False)
            )
            and not self._check_for_name_in_memos(checkfirst, kw)
        ):
```
This conditional will evaluate true even if the check for name comes back True (which it always will when `create_type=False`. I believe there are brackets missing and that it should read:
```py
        if (
             ( checkfirst
                or (
                    not self.metadata
                    and not kw.get("_is_metadata_operation", False)
                )
            )
            and not self._check_for_name_in_memos(checkfirst, kw)
        ):
```

**Comment by abensrhir** [comment] 2020-08-19 01:02
Replacing `Base.metadata.create_all(bind=conn)` with `Base.metadata.create_all(bind=engine)` will solve your problem

**Comment by zzzeek** [comment] 2020-08-19 02:18
hiya -

Here, it seems the issue is simply that schema translate map is not taken into account when DDL checks for the presence of it, here's a much more minimal test case:

```
from sqlalchemy import *
import enum
from sqlalchemy.dialects.postgresql import ENUM

metadata = MetaData()
class Mood(enum.Enum):
    sad = 1
    ok = 2
    happy = 3

mood_enum = ENUM(Mood)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

with e.connect().execution_options(schema_translate_map={None: "test_schema"}) as conn:
    mood_enum.create(conn, checkfirst=True)
    mood_enum.create(conn, checkfirst=True)

```

this patch against 1.3 fixes that bug, it would be helpful if you could evaluate this.  Note that enums with schema translate map were not working at all until version 1.3.14 of SQLAlchemy released in the past few months with #5158. 

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/base.py b/lib/sqlalchemy/dialects/postgresql/base.py
index 4ad6cb11c..261558075 100644
--- a/lib/sqlalchemy/dialects/postgresql/base.py
+++ b/lib/sqlalchemy/dialects/postgresql/base.py
@@ -1502,8 +1502,12 @@ class ENUM(sqltypes.NativeForEmulated, sqltypes.Enum):
         if not bind.dialect.supports_native_enum:
             return
 
+        effective_schema = bind.schema_for_object(self)
+        if effective_schema:
+            bind.dialect.validate_identifier(effective_schema)
+
         if not checkfirst or not bind.dialect.has_type(
-            bind, self.name, schema=self.schema
+            bind, self.name, schema=effective_schema
         ):
             bind.execute(CreateEnumType(self))
 
@@ -1525,8 +1529,12 @@ class ENUM(sqltypes.NativeForEmulated, sqltypes.Enum):
         if not bind.dialect.supports_native_enum:
             return
 
+        effective_schema = bind.schema_for_object(self)
+        if effective_schema:
+            bind.dialect.validate_identifier(effective_schema)
+
         if not checkfirst or bind.dialect.has_type(
-            bind, self.name, schema=self.schema
+            bind, self.name, schema=effective_schema
         ):
             bind.execute(DropEnumType(self))
 

```

for create_type not working I can't reproduce an issue, below the flag allows the script to succeed and if you take it out, it predictably fails.   I would need a very minimal MCVE that shows exactly create_type=False failing in the way that you mention.

```
import enum

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import Sequence
from sqlalchemy import String
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.engine import Connection
from sqlalchemy.ext.declarative import declarative_base

DB_URL = 'postgres://scott:tiger@localhost/test'

class Mood(enum.Enum):
    sad = 1
    ok = 2
    happy = 3

engine = create_engine(DB_URL, echo=True)

Base = declarative_base()

class Person(Base):
    __tablename__ = 'person'
    id = Column(Integer, Sequence('pid_seq'), primary_key=True)
    name = Column(String, nullable=False)
    dominant_mood = Column(ENUM(Mood, create_type=False), nullable=True)
    current_mood = Column(ENUM(Mood, create_type=False), nullable=True)

conn: Connection = engine.connect()


Base.metadata.drop_all(bind=conn)

ENUM(Mood).create(conn)

# does not attempt to recreate MOOD
Base.metadata.create_all(bind=conn, checkfirst=False)


```

**Comment by sqla-tester** [comment] 2020-08-19 02:54
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement DDL visitor for PG ENUM with schema translate support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2163

**Comment by sqla-tester** [comment] 2020-08-19 02:54
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Implement DDL visitor for PG ENUM with schema translate support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2164

**Comment by zzzeek** [comment] 2020-08-19 03:25
> 
> Regardless of the actual issue, I think that the following code, from lines 1565-1572 in `base.py` are incorrect:
> 
> ```python
>         if (
>             checkfirst
>             or (
>                 not self.metadata
>                 and not kw.get("_is_metadata_operation", False)
>             )
>             and not self._check_for_name_in_memos(checkfirst, kw)
>         ):
> ```
> 
> This conditional will evaluate true even if the check for name comes back True (which it always will when `create_type=False`. I believe there are brackets missing and that it should read:

I'll grant the intent of that code is difficult to understand and I think it does need an adjustment, but not for the reason you mention.  If create_type is False then self._check_for_name_in_memos(checkfirst, kw) comes out as True and the conditonal negates it, which means it will unconditionally **not** attempt the .create().     there's a test which validates this:

```

    @testing.provide_metadata
    def test_disable_create(self):
        metadata = self.metadata

        e1 = postgresql.ENUM(
            "one", "two", "three", name="myenum", create_type=False
        )

        t1 = Table("e1", metadata, Column("c1", e1))
        # table can be created separately
        # without conflict
        e1.create(bind=testing.db)
        t1.create(testing.db)
        t1.drop(testing.db)
        e1.drop(bind=testing.db)

```

above, t1.create() defaults checkfirst to False.   So if the create_type=False weren't working, the code would fail.  indeed if I take out the check_for_name_in_memos that test fails.

that said,  there might be a secondary goal of that code which is to prevent it from checking many times under one DDL run and that seems like it fails due to the way the conditional is written.

However, beyond that there are no tests that fail on that conditional whether it is written either way.    if the conditional above is wrong then the main bug is that there is no test that fails as a result of it, so writing a failing test is the first step.    in this case it's that a test must actually exercise that it isnt' needlessly checking multitple times for the type.

**Comment by zzzeek** [comment] 2020-08-19 03:41
I've added this test which confirms the conditional needs repair, without the change you suggest there are needless queries for "SELECT EXISTS..." which is the one checking for the enum:
```

    @testing.provide_metadata
    def test_dont_keep_checking(self, connection):
        metadata = self.metadata

        e1 = postgresql.ENUM("one", "two", "three", name="myenum")

        t = Table(
            "t", metadata, Column("a", e1), Column("b", e1), Column("c", e1)
        )

        with self.sql_execution_asserter(connection) as asserter:
            metadata.create_all(connection)

        from sqlalchemy.testing.assertsql import CursorSQL, RegexSQL

        asserter.assert_(
            RegexSQL(
                "select relname from pg_class c join pg_namespace.*",
                dialect="postgresql",
            ),
            RegexSQL(r".*SELECT EXISTS ", dialect="postgresql"),
            CursorSQL("CREATE TYPE myenum AS ENUM ('one', 'two', 'three')"),
            CursorSQL(
                "\nCREATE TABLE t "
                "(\n\ta myenum, \n\tb myenum, \n\tc myenum\n)\n\n"
            ),
        )

        with self.sql_execution_asserter(connection) as asserter:
            metadata.drop_all(connection)

        from sqlalchemy.testing.assertsql import CursorSQL, RegexSQL

        asserter.assert_(
            RegexSQL(
                "select relname from pg_class c join pg_namespace.*",
                dialect="postgresql",
            ),
            RegexSQL("DROP TABLE t"),
            RegexSQL(r".*SELECT EXISTS ", dialect="postgresql"),
            CursorSQL("DROP TYPE myenum"),
        )

```

**Comment by robertmuil** [comment] 2020-08-19 09:47
@zzzeek this is awesome - thank you for such a quick and comprehensive response.
I will try to test your patch and let you know. In the meantime I found a workaround was to pass the schema name directly to the `ENUM` - this led to the existence check working as expected, and it only issuing the `CREATE TYPE` once. However, that feels a bit kludgy.

Separately, @abensrhir pointed out to me that we can pass the schema to the declarative base like so (we can't bind to the engine, because in our case we need to change the schema on the fly):

    Base = declarative_base(metadata=MetaData(schema=schema_name))

Also, am working through the logic you describe for the conditional test.
Perhaps we should split this out into a separate issue?

**Comment by robertmuil** [comment] 2020-08-19 10:08
@zzzeek regarding the `create_type` behaviour I'm questioning, I've extracted the conditional code and mocked the context to demonstrate the conditional not behaving as I expect it to. In the following, I expect it NOT to issue the CREATE TYPE, because `create_type==False`.
```py
checkfirst = True
create_type = False
metadata = 'something'
kw = {'_is_metadata_operation': False}

def _check_for_name_in_memos(a, b):
    print(' -- checking for name -- ')
    if create_type:
        return True
    else:
        return False

if (checkfirst
    or (
        not metadata
        and not kw.get("_is_metadata_operation", False)
    )
    and not _check_for_name_in_memos(checkfirst, kw)
):
    print('CREATE TYPE')
else:
    print('no create type issued')
```
This code will hit the `CREATE TYPE` path.
If I add the brackets as I mentioned above, it does not.
I'm not sure why your example is not triggering the issue - I notice you've specified `checkfirst=False`... perhaps that bypasses this code path somehow?

**Comment by zzzeek** [comment] 2020-08-19 14:35
yes I think the code as it is now was not an "issue" because it does not under functional testing receive inputs that happen to produce a bad result.  except that it emits needless EXISTS queries, which is definitely a bug, so I've bundled the two fixes together in the above gerrit that is in CI.

There does not seem to be a need to break out into separate issues at the moment, we have too many patches and issues and these are extremely inter-related, they're better together for now as they are small.

**Closed** 2020-08-19 17:38 UTC
Labels: bug, postgresql
