### ISSUE TITLE
MSSQL Overflow Error on Floats in JSON

### ISSUE THREAD

**Issue by atellier** [sqlalchemy/sqlalchemy#5788] opened 2020-12-19 22:08 UTC
**Describe the bug**
When a `Column` is declared as JSON and a field contains a numeric value with more precision that `Decimal(10, 6)`, Microsoft SQL Sever fails with an `Overflow Error`

**Expected behavior**
1. Create the corresponding database on MSSQL, and populate with example:
```sql
CREATE TABLE dbo.test (
    id int NOT NULL,
    value varchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
    CONSTRAINT PK_test_id PRIMARY KEY (id)
);
GO

INSERT INTO dbo.test VALUES (1, '{"test": {"value": 1234567.89}}');
GO
```

2. Assuming we have `Session` established, run the following code:
```py
from sqlalchemy import Column, JSON, select, Integer
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Test(Base):
    __tablename__ = "test"
    __table_args__ = {"schema": "dbo"}

    id = Column(Integer, primary_key=True)
    value = Column(JSON, nullable=False)

session = ...
session.execute(select(Test.value[("test", "value")].as_float())).scalars().all()
```

**Error**

```
pyodbc.Error: ('HY019', '[HY019] [FreeTDS][SQL Server]Arithmetic overflow error converting nvarchar to data type numeric. (8115) (SQLExecDirectW)')
```

**Versions.**
 - OS: OSX
 - Python: 3.8
 - SQLAlchemy: 1.4.01b
 - Database: MSSQL 2017
 - DBAPI: pyodbc

**Additional context**
The issue is caused by the cast on that line: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2118/19/lib/sqlalchemy/dialects/mssql/base.py#2045

Using `FLOAT` instead of `DECIMAL(10, 6)` fixes the issue at the expense of some conversion and potential loss of precision - but it does not cause an error.

Note: Having a `as_numeric(p,s)` in the JSON implementation would be nice. So that we could generate a cast as `FLOAT` or as `DECIMAL(p, s)` depending on what `as_xxxx` as used.

**Thanks!**

**Comment by gordthompson** [comment] 2020-12-19 22:14
Caused by copying from the mysql dialect here:

https://github.com/sqlalchemy/sqlalchemy/blob/a8f51f3c11f3cb2e344732cf3abb371f03ed30d8/lib/sqlalchemy/dialects/mysql/base.py#L1460

**Comment by zzzeek** [comment] 2020-12-19 22:17
so the accessor is currently called as_float() so it seems like it certainly should be casting to FLOAT for that, and luckily we are in betas for SQL Server's feature so we can just change it.  @gordthompson was the DECIMAL(10, 6) to get tests to pass or can we just change that?

also as_numeric(p, s) is nice as well, I wonder why that wasn't added, can do this for 1.4 too.

**Comment by zzzeek** [comment] 2020-12-19 22:18
ah mysql.  does mysql have a bug w/ the above?

**Comment by gordthompson** [comment] 2020-12-19 22:19
> 
> 
> ah mysql. does mysql have a bug w/ the above?

@zzzeek - I'll have a look.

**Comment by gordthompson** [comment] 2020-12-19 22:32
Repro code does not fail for `mysql+mysqldb://`. SQL generated is

```
2020-12-19 15:29:29,892 INFO sqlalchemy.engine.Engine SELECT CASE JSON_EXTRACT(test.value, %s) WHEN 'null' THEN NULL ELSE CAST(JSON_EXTRACT(test.value, %s) AS DECIMAL(10, 6)) END AS anon_1 
FROM test
2020-12-19 15:29:29,893 INFO sqlalchemy.engine.Engine [generated in 0.00166s] ('$."test"."value"', '$."test"."value"')
```

**Comment by gordthompson** [comment] 2020-12-19 22:36
… however, if I look at the actual value returned I see that it just failed silently:

``` python
result = (
    session.execute(select(Test.value[("test", "value")].as_float()))
    .scalars()
    .all()
)
print(result)  # [9999.999999]
```

**Comment by gordthompson** [comment] 2020-12-20 15:28
This seems to fix the issue for mysql, although it does not address the arbitrary `DECIMAL(10, 6)` issue:

```
Index: lib/sqlalchemy/dialects/mysql/base.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
--- a/lib/sqlalchemy/dialects/mysql/base.py	(revision a8f51f3c11f3cb2e344732cf3abb371f03ed30d8)
+++ b/lib/sqlalchemy/dialects/mysql/base.py	(date 1608477837491)
@@ -1456,13 +1456,22 @@
             )
         elif binary.type._type_affinity is sqltypes.Numeric:
             # FLOAT / REAL not added in MySQL til 8.0.17
-            type_expression = (
-                "ELSE CAST(JSON_EXTRACT(%s, %s) AS DECIMAL(10, 6))"
-                % (
-                    self.process(binary.left, **kw),
-                    self.process(binary.right, **kw),
-                )
-            )
+            if isinstance(binary.type, sqltypes.Float):
+                type_expression = (
+                    "ELSE CAST(JSON_EXTRACT(%s, %s) AS FLOAT)"
+                    % (
+                        self.process(binary.left, **kw),
+                        self.process(binary.right, **kw),
+                    )
+                )
+            else:
+                type_expression = (
+                    "ELSE CAST(JSON_EXTRACT(%s, %s) AS DECIMAL(10, 6))"
+                    % (
+                        self.process(binary.left, **kw),
+                        self.process(binary.right, **kw),
+                    )
+                )
         elif binary.type._type_affinity is sqltypes.Boolean:
             # the NULL handling is particularly weird with boolean, so
             # explicitly return true/false constants
```

**Comment by gordthompson** [comment] 2020-12-20 16:02
Here's a patch that fixes the `as_float()` issue and implements `as_numeric()`. Am I on the right track here?

```
Index: lib/sqlalchemy/sql/sqltypes.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
--- a/lib/sqlalchemy/sql/sqltypes.py	(revision a8f51f3c11f3cb2e344732cf3abb371f03ed30d8)
+++ b/lib/sqlalchemy/sql/sqltypes.py	(date 1608479631572)
@@ -2467,9 +2467,24 @@
             .. versionadded:: 1.3.11
 
             """
-            # note there's no Numeric or Decimal support here yet
             return self._binary_w_type(Float(), "as_float")
 
+        def as_numeric(self, precision, scale):
+            """Cast an indexed value as numeric/decimal.
+
+            e.g.::
+
+                stmt = select(
+                    mytable.c.json_column['some_data'].as_numeric(4, 2)
+                ).where(
+                    mytable.c.json_column['some_data'].as_numeric(4, 2) == Decimal('29.75')
+                )
+
+            .. versionadded:: 1.4
+
+            """
+            return self._binary_w_type(Numeric(precision, scale), "as_float")
+
         def as_json(self):
             """Cast an indexed value as JSON.
 
Index: lib/sqlalchemy/dialects/mysql/base.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
--- a/lib/sqlalchemy/dialects/mysql/base.py	(revision a8f51f3c11f3cb2e344732cf3abb371f03ed30d8)
+++ b/lib/sqlalchemy/dialects/mysql/base.py	(date 1608479888351)
@@ -1456,12 +1456,13 @@
             )
         elif binary.type._type_affinity is sqltypes.Numeric:
             # FLOAT / REAL not added in MySQL til 8.0.17
-            type_expression = (
-                "ELSE CAST(JSON_EXTRACT(%s, %s) AS DECIMAL(10, 6))"
-                % (
-                    self.process(binary.left, **kw),
-                    self.process(binary.right, **kw),
-                )
+            type_expression = "ELSE CAST(JSON_EXTRACT(%s, %s) AS %s)" % (
+                self.process(binary.left, **kw),
+                self.process(binary.right, **kw),
+                "FLOAT"
+                if isinstance(binary.type, sqltypes.Float)
+                else "DECIMAL(%s, %s)"
+                % (binary.type.precision, binary.type.scale),
             )
         elif binary.type._type_affinity is sqltypes.Boolean:
             # the NULL handling is particularly weird with boolean, so
```

**Comment by gordthompson** [comment] 2020-12-20 16:09
What seems odd to me is that

https://github.com/sqlalchemy/sqlalchemy/blob/a8f51f3c11f3cb2e344732cf3abb371f03ed30d8/lib/sqlalchemy/sql/sqltypes.py#L2471

produces an object whose `.type` is `sqltypes.Float` but whose `.type._type_affinity` is `sqltypes.Numeric`.

**Comment by zzzeek** [comment] 2020-12-20 16:13
What seems to work best on most MySQL / MariaDB versions is this:


```
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index 911c0d522..95a2040f0 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1457,7 +1457,7 @@ class MySQLCompiler(compiler.SQLCompiler):
         elif binary.type._type_affinity is sqltypes.Numeric:
             # FLOAT / REAL not added in MySQL til 8.0.17
             type_expression = (
-                "ELSE CAST(JSON_EXTRACT(%s, %s) AS DECIMAL(10, 6))"
+                "ELSE JSON_EXTRACT(%s, %s)+0.0"
                 % (
                     self.process(binary.left, **kw),
                     self.process(binary.right, **kw),

```

however it does lose precision on MySQL 5.7 for the given test value "1234567.89".

it seems obvious that to support precision decimals in json we need `as_numeric(s, p)`.

**Comment by sqla-tester** [comment] 2020-12-20 17:18
**Mike Bayer** referenced this issue:

**poc for as numeric** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2427

**Comment by zzzeek** [comment] 2020-12-20 17:18
hey gord -

the above gerrit is a short POC for as_numeric().

**Comment by sqla-tester** [comment] 2020-12-20 17:20
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix issues with JSON and float/numeric** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2428

**Comment by gordthompson** [comment] 2020-12-20 17:26
@zzzeek - I didn't see your change before submitting mine. I'll reconcile the two shortly.

**Comment by atellier** [comment] 2020-12-20 17:31
Thanks for the awesomely quick turn-around!

BTW there appears a slight difference between `DECIMAL` and `NUMERIC`, at least in MSSQL: https://sqlrob.com/2018/01/22/decimal-vs-numeric/ and https://learnsql.com/blog/understanding-numerical-data-types-sql/

> There is a small difference between NUMERIC(p,s) and DECIMAL(p,s) SQL numeric data type. NUMERIC determines the exact precision and scale. DECIMAL specifies only the exact scale; the precision is equal or greater than what is specified by the coder. DECIMAL columns can have a larger-than-specified precision if this is more convenient or efficient for the database system.
> 
> In other words, DECIMAL gives you some leeway.

Just mentioning that as the fix uses `DECIMAL` and the function is `as_numeric()` and that may not be the intended cast.

Thanks!

**Comment by gordthompson** [comment] 2020-12-20 19:09
@atellier - Thanks for the clarification.

@zzzeek - Should we keep casting to `DECIMAL` and call the method `as_decimal()`? Or keep the method as `as_numeric()` and cast to `NUMERIC`? Or perhaps do both?

**Comment by gordthompson** [comment] 2020-12-20 19:17
… personally, I always use `DECIMAL`.

**Comment by zzzeek** [comment] 2020-12-20 19:26
I think here we are looking for precision + scale because we are looking to get a numeric value out of structured results for which we would assume these things are known.    numeric/decimal is not as much of a database agnostic-decision we can make right now.   folks can always use cast() manually when they want certain kinds of data on certain kinds of platforms .

**Comment by sqla-tester** [comment] 2020-12-21 00:16
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix issues with JSON and float/numeric** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2428

**Closed** 2020-12-22 13:49 UTC
Labels: SQL Server, bug, datatypes, mysql, use case
