### ISSUE TITLE
Commit two or more objects with `LargeBinary` column throws `sqlalchemy.exc.DBAPIError`

### ISSUE THREAD

**Issue by Rubikoid** [sqlalchemy/sqlalchemy#9739] opened 2023-05-03 23:06 UTC
### Describe the bug

I have model with `LargeBinary` column (which represented in python type `bytes`)

When I commit only one instance of model, everything works ok.

When I commit two or more instances, I get `sqlalchemy.exc.DBAPIError` exception.

But! when I commit two or more instances, and instead of bytes, I pass to `LargeBinary` field `str` instead of `bytes`, everything works ok.

### SQLAlchemy Version in Use

2.0.12

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

postgres:14

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import asyncio

from sqlalchemy import LargeBinary, MetaData
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

async_engine = create_async_engine(
    "postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/dev",
    pool_pre_ping=True,
    echo=True,
)

AsyncSessionLocal = async_sessionmaker(
    bind=async_engine,
)


class Base(DeclarativeBase):
    __abstract__ = True
    metadata = MetaData()


class Test(Base):
    __tablename__ = "tests"

    id: Mapped[int] = mapped_column(
        autoincrement=True,
        nullable=False,
        unique=True,
        primary_key=True,
    )
    "id"

    s: Mapped[str] = mapped_column()
    "str data"

    data: Mapped[bytes] = mapped_column(LargeBinary)
    "binary data"


async def main():
    async with async_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    content = [
        Test(
            s="test_text1",
            data=b"test_bin1",
        ),
    ]

    async with AsyncSessionLocal() as session:
        for t in content:
            session.add(t)
        await session.commit()  # no errors

    content = [
        Test(
            s="test_text1",
            data="test_bin1",
        ),
        Test(
            s="test_text2",
            data="test_bin2",
        ),
    ]

    async with AsyncSessionLocal() as session:
        for t in content:
            session.add(t)
        await session.commit()  # no errors

    content = [
        Test(
            s="test_text1",
            data=b"test_bin1",
        ),
        Test(
            s="test_text2",
            data=b"test_bin2",
        ),
    ]

    async with AsyncSessionLocal() as session:
        for t in content:
            session.add(t)

        try:
            await session.commit()
        except Exception as ex:
            await session.rollback()
            raise  # exception
            # print(repr(ex))


if __name__ == "__main__":
    asyncio.run(main())

```

### Error

```
2023-05-04 02:12:34,257 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-05-04 02:12:34,257 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-05-04 02:12:34,258 INFO sqlalchemy.engine.Engine select current_schema()
2023-05-04 02:12:34,258 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-05-04 02:12:34,259 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-05-04 02:12:34,259 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-05-04 02:12:34,260 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-04 02:12:34,262 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR    
2023-05-04 02:12:34,262 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ('tests', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2023-05-04 02:12:34,264 INFO sqlalchemy.engine.Engine
DROP TABLE tests
2023-05-04 02:12:34,264 INFO sqlalchemy.engine.Engine [no key 0.00007s] ()
2023-05-04 02:12:34,266 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR    
2023-05-04 02:12:34,266 INFO sqlalchemy.engine.Engine [cached since 0.003511s ago] ('tests', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2023-05-04 02:12:34,267 INFO sqlalchemy.engine.Engine
CREATE TABLE tests (
        id SERIAL NOT NULL,
        s VARCHAR NOT NULL,
        data BYTEA NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (id)
)


2023-05-04 02:12:34,267 INFO sqlalchemy.engine.Engine [no key 0.00007s] ()
2023-05-04 02:12:34,274 INFO sqlalchemy.engine.Engine COMMIT
2023-05-04 02:12:34,277 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-04 02:12:34,278 INFO sqlalchemy.engine.Engine INSERT INTO tests (s, data) VALUES ($1::VARCHAR, $2) RETURNING tests.id
2023-05-04 02:12:34,278 INFO sqlalchemy.engine.Engine [generated in 0.00011s] ('test_text1', b'test_bin1')
2023-05-04 02:12:34,279 INFO sqlalchemy.engine.Engine COMMIT
2023-05-04 02:12:34,281 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-04 02:12:34,282 INFO sqlalchemy.engine.Engine INSERT INTO tests (s, data) SELECT p0::VARCHAR, p1::BYTEA FROM (VALUES ($1::VARCHAR, $2, 0), ($3::VARCHAR, $4, 1)) AS imp_sen(p0, p1, sen_counter) ORDER BY sen_counter RETURNING tests.id, tests.id AS id__1
2023-05-04 02:12:34,282 INFO sqlalchemy.engine.Engine [generated in 0.00005s (insertmanyvalues) 1/1 (ordered)] ('test_text1', 'test_bin1', 'test_text2', 'test_bin2')
2023-05-04 02:12:34,283 INFO sqlalchemy.engine.Engine COMMIT
2023-05-04 02:12:34,285 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-05-04 02:12:34,285 INFO sqlalchemy.engine.Engine INSERT INTO tests (s, data) SELECT p0::VARCHAR, p1::BYTEA FROM (VALUES ($1::VARCHAR, $2, 0), ($3::VARCHAR, $4, 1)) AS imp_sen(p0, p1, sen_counter) ORDER BY sen_counter RETURNING tests.id, tests.id AS id__1
2023-05-04 02:12:34,285 INFO sqlalchemy.engine.Engine [cached since 0.003569s ago (insertmanyvalues) 1/1 (ordered)] ('test_text1', b'test_bin1', 'test_text2', b'test_bin2')
2023-05-04 02:12:34,286 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "asyncpg/protocol/prepared_stmt.pyx", line 168, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg/protocol/codecs/base.pyx", line 206, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg/protocol/codecs/base.pyx", line 111, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg/pgproto/./codecs/text.pyx", line 29, in asyncpg.pgproto.pgproto.text_encode
  File "asyncpg/pgproto/./codecs/text.pyx", line 12, in asyncpg.pgproto.pgproto.as_pg_string_and_size
TypeError: expected str, got bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 525, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $2: b'test_bin1' (expected str, got bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2108, in _exec_insertmany_context
    dialect.do_execute(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in execute
    self._adapt_connection.await_(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 537, in _prepare_and_execute
    self._handle_exception(error)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 487, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 776, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $2: b'test_bin1' (expected str, got bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mre.py", line 98, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "mre.py", line 90, in main
    await session.commit()
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 835, in commit
    await greenlet_spawn(self.sync_session.commit)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1905, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1220, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1195, in _prepare_impl
    self.session.flush()
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4153, in flush
    self._flush(objects)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4289, in _flush
    with util.safe_reraise():
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4250, in _flush
    flush_context.execute()
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1133, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
           ^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1836, in _execute_context
    return self._exec_insertmany_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2116, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2108, in _exec_insertmany_context
    dialect.do_execute(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in execute
    self._adapt_connection.await_(
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 537, in _prepare_and_execute
    self._handle_exception(error)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 487, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File ".venv_l/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 776, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $2: b'test_bin1' (expected str, got bytes)
[SQL: INSERT INTO tests (s, data) SELECT p0::VARCHAR, p1::BYTEA FROM (VALUES ($1::VARCHAR, $2, 0), ($3::VARCHAR, $4, 1)) AS imp_sen(p0, p1, sen_counter) ORDER BY sen_counter RETURNING tests.id, tests.id AS id__1]
[parameters: ('test_text1', b'test_bin1', 'test_text2', b'test_bin2')]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
```

**Comment by zzzeek** [comment] 2023-05-04 02:19
this is another regression due to #9618.

The part of your test where you are inserting plain strings is not supposed to work, those aren't binary values:

```py
   content = [
        Test(
            s="test_text1",
            data="test_bin1",
        ),
        Test(
            s="test_text2",
            data="test_bin2",
        ),
    ]

    async with AsyncSessionLocal() as session:
        for t in content:
            session.add(t)
        await session.commit()  # no errors
```

the patch to add for reference is below

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/asyncpg.py b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
index c879205e4a..88ae5ecef2 100644
--- a/lib/sqlalchemy/dialects/postgresql/asyncpg.py
+++ b/lib/sqlalchemy/dialects/postgresql/asyncpg.py
@@ -191,7 +191,7 @@ from ...sql import sqltypes
 from ...util.concurrency import asyncio
 from ...util.concurrency import await_fallback
 from ...util.concurrency import await_only
-
+from .types import  BYTEA
 if TYPE_CHECKING:
     from typing import Iterable
 
@@ -212,6 +212,10 @@ class AsyncpgTime(sqltypes.Time):
     render_bind_cast = True
 
 
+class AsyncpgByteA(BYTEA):
+    render_bind_cast = True
+
+
 class AsyncpgDate(sqltypes.Date):
     render_bind_cast = True
 
@@ -986,6 +990,7 @@ class PGDialect_asyncpg(PGDialect):
             sqltypes.Numeric: AsyncpgNumeric,
             sqltypes.Float: AsyncpgFloat,
             sqltypes.JSON: AsyncpgJSON,
+            sqltypes.LargeBinary: AsyncpgByteA,
             json.JSONB: AsyncpgJSONB,
             sqltypes.JSON.JSONPathType: AsyncpgJSONPathType,
             sqltypes.JSON.JSONIndexType: AsyncpgJSONIndexType,

```

**Comment by sqla-tester** [comment] 2023-05-04 02:36
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add bind casts for BYTEA on asyncpg** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4598

**Closed** 2023-05-09 14:31 UTC
Labels: bug, postgresql, regression, near-term release
