### ISSUE TITLE
turn off implicit uniquing of rows; add unique() result method; require unique() if joinedload/contains_eager of collection is present

### ISSUE THREAD

**Issue by giovannipizzi** [sqlalchemy/sqlalchemy#4395] opened 2018-12-03 18:19 UTC
Currently, let's assume I write a query like the following
```python
q = session.query(Customer).join(Sales, Customer.id==Sales.customer_id).filter(Customer.id==1).all()
```
under the assumption, e.g., that Customer 1 has 5 sales. 
Now, `q.count()` would return 5, as also SQL would do if I run the corresponding SQL query.

However, `q.all()` will only return a list of 1 Customer, as it deduplicates results - this is done here:
https://github.com/sqlalchemy/sqlalchemy/blob/a0d1030096af8f6cdd2e2fb7668224ade2d87c8f/lib/sqlalchemy/orm/loading.py#L88-L89
where `filtered is defined a few lines above from `query._has_mapper_entities`
https://github.com/sqlalchemy/sqlalchemy/blob/a0d1030096af8f6cdd2e2fb7668224ade2d87c8f/lib/sqlalchemy/orm/loading.py#L38

The suggested solution, see e.g. 
https://github.com/sqlalchemy/sqlalchemy/issues/4143#issuecomment-441939735, is apparently to run instead 
```python
q = session.query(Customer.id).join(Sales, Customer.id==Sales.customer_id).filter(Customer.id==1).all()
```
that indeed would return `[1,1,1,1,1]` (as I would expect from a SQL point of view).

I imagine this is to make life easier for some users, but actually we need (aiidateam/aiida_core#1600) a way to get the SQL behaviour without deduplication, i.e. a list of 5 Customer entities (we could hack the query and do `q._has_mapper_entities = False`, but this clearly looks like the wrong thing to do) 

Is there a proper way to get the 5 results (i.e. not do a 'distinct') already?
Or would it be possible to add an official, documented method on the query that we can call to internally set `q._has_mapper_entities` to false? So we can rely on it and not on internal functionality of sqlalchemy that might change in the future.

**Comment by zzzeek** [comment] 2018-12-03 19:48
So I think for long term, that is, when we are doing a release that can make a *big* change to things, this whole "dedupe" thing maybe should be scaled back, because people often hate it.

the main reason it's there is to help joined eager loading, which in early SQLAlchemy versions was a major theme of the whole system, however now it's much less so; in any case, the Query knows if it has joined eager loads set up for collections, which is the official case where this needs to happen, so it can be conditional based on that.

the other reason it's there, and this still might be something that would screw people up if we turned it off, is when they are doing things with the objects in an iterator and they assume deduplication, like:

```python
  for item in s.query(Item).join(...).union(...):   # e.g. make it likely to get dupe rows
        send_email(item)   # e.g. something you really don't want to do twice :)
```

anyway, I just added a note to my "document of things for when we make a *big* change", what the API will be to turn deduping **on**, and it also has an option to turn deduping off when you have joined eager loads against collections set up.  So the API will be:

   s.query(Item).dedupe_rows(False)

That is, in the "*big* change", folks will be writing ".dedupe_rows()"  when they are looking to have deduplication turned on.    

For now you are safe setting that _has_mapper_entities flag since the dedupe logic is its only use.

**Comment by zzzeek** [comment] 2020-02-21 17:43
this will be hopefully present in the 1.4->2.0 future compatibility layer discussed at https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#sqlalchemy-1-x-to-2-0-transition

summary:

1. deduping of rows is no longer done by the ORM, the rows will come back from the cursor, be filtered so that they contain ORM objects rather than individual columns as they are now, and delivered.  in the 2.0 architecture, this occurs within the scope of the new result object.

2. the result object itself will have a feature unique(), that enables straight uniquing of rows in a similar manner as it does now in ORM, but it will be available for any result set.

3.  when an ORM query is compiled, if it contains any joinedload() or contains_eager() of **collections** (not many-to-one or one-to-one), it will be required that .unique() is called on the result before iterating.  an error will be raised otherwise; this is because the uniquing is needed in order to get the expected objects back when joined eager loading of collections is used.    this will prevent confusion over the uniquing not occurring for a joined eager load collection result.

4. so the unique() call has to be explicit, otherwise, we'd be switching it on and off based on whether or not joined eager loading is used implicitly, and these options are not supposed to ever change the top level results, so this will prevent confusion in the other direction.

5. it is expected that selectinload() will be used much more often for collection eager loading and possibly subqueryload().

6. it would be nice to figure out a way to get selectinload() to support composite primary keys on more platforms.

**Comment by sqla-tester** [comment] 2020-05-01 20:11
**Mike Bayer** referenced this issue:

**Propose Result as immediate replacement for ResultProxy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1911

**Comment by sqla-tester** [comment] 2020-05-02 15:22
**Mike Bayer** referenced this issue:

**Integrate new Result into ORM query** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1920

**Comment by zzzeek** [comment] 2020-06-05 14:35
so as of bbf6448 , this is there, and then as of 6930dfc032c3f9f474e71ab the new 2.0-style exposure of this API is present, see below.   however, it's not well documented and not part of the ORM tutorial or anything like that.   this feature is part of the "2.0 transition" layer so it's TBD how we will document these features.

Short answer though is that right now the Session.execute() method gives you the new Result object without any uniquing pre-applied to it.   it seems like adding a Query.get_result() method of some kind might be a good idea as well.     If you check out master right now, you can do this:


```
    q = session.query(Customer).join(Sales, Customer.id==Sales.customer_id).filter(Customer.id==1)

   result = session.execute(q)

   list(result)  # not uniqued


```

now what's awkward above is, we just did session.query(), why are we doing session.execute(query) then (this is what Query does internally now).   so maybe we add get_result() to smooth that part over.

the actual 2.0 style is that you dont use Query at all, you use select(), this also is in 1.4 master right now:

```
    # this is right now, however this might be 
    # from sqlalchemy import select soon because they are mostly
    # the same object
    from sqlalchemy.future import select

    q = select(Customer).join(Sales, Customer.id==Sales.customer_id).filter(Customer.id==1)

   result = session.execute(q)

   list(result)  # not uniqued


```

above I just changed "session.query()" to "select()".   they are unified now.

**Comment by zzzeek** [comment] 2020-06-05 14:36
thinking about criteria to close this issue, I think it should be:

1. add Query.get_results()

2. add a warning if the query has joined collection results and unique() is not called.

**Comment by sqla-tester** [comment] 2020-09-21 21:32
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Raise if unique() not applied to 2.0 joined eager load results** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2253

**Closed** 2020-09-22 01:54 UTC
Labels: feature, orm, result fetching API improvements

**Comment by nicolas-chaulet** [comment] 2022-06-10 22:11
Just reading through this, I am using sqlalchemy v1.4 and  I had a query with a few eager loading in "selectin" mode that used to return unique rows but stopped after changing the primary key constraint on one of the child tables. Applying `unique()` to the result solves the issue but that's probably not the expected behaviour. I tried to replicate on simple data structures without success...

**Comment by OddBlueDog** [comment] 2022-12-31 16:14
@nicolas-chaulet Do you have any `lazy='joined'` directly on the models / mapping (rather than in .optoins(joinedload(...))? Like this: https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#configuring-loader-strategies-at-mapping-time

**Comment by nicolas-chaulet** [comment] 2023-01-03 15:48
Yes I do. I actually have both, some relationship loading strategies are defined one the model, others in the query itself via options
