### ISSUE TITLE
issue with mssql func.STRING_AGG

### ISSUE THREAD

**Issue by nico525** [sqlalchemy/sqlalchemy#5507] opened 2020-08-12 06:52 UTC
Hi,
I have a very complex model resulting from various various joins of raw database tables. One of them is a joined sub-select containing MSSQL built in STRING_AGG function as shown here

```
team_b = sql.select([func.STRING_AGG(team_d.c.team_name, ', ').within_group(team_d.c.team_name).label('teams'), team_b.c.p_key])\
    .select_from(sql.join(team_b, team_d))\
    .group_by(team_b.c.p_key)\
    .alias()

p_d = sql.outerjoin(p, v_d).outerjoin(team_b, (team_b.c.p_key == p_d.c.p_key))
```
p_d is passed in as __table__ for my model

```
@dataclass
class P(BaseModel):
    __table__ = p_d

    p_id:int = column_property(p.c.p_id, v_d.c.p_id)
    v_id:int = column_property(v_d.c.v_id)
    teams:str = column_property(team_b.c.teams)
```

running a query against this object returns in an error that at first seems to be driver related:
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'STRING_AGG' is not a recognized built-in function name. (104162) (SQLExecDirectW)")

but running the query directly on the database works fine and even more strange is that the following works, too:
`session.execute(text(str(self.session.query(codegenClass).statement.compile(dialect=mssql.dialect(), compile_kwargs={"literal_binds": True}))))
`

**Comment by zzzeek** [comment] 2020-08-12 14:24
hi -

can you please add the actual, complete SQL statement and parameters that fails?  your complete stack trace will show this as well as if you apply echo=True to your create_engine().

**Comment by nico525** [comment] 2020-08-12 15:18
obviously the information provided is masked, but the original query is similar to the following one:
```
SELECT dbo.p_d.p_id AS p_id, dbo.v_d.v_id AS v_id, anon2.teams AS teams
FROM dbo.p_d
LEFT OUTER JOIN dbo.[v_d] ON dbo.v_d.p_id = dbo.p_d.p_id
LEFT OUTER JOIN (
	SELECT STRING_AGG(dbo.team_d.team_name, N', ') WITHIN GROUP (ORDER BY dbo.team_b.portfolio_key) AS teams, dbo.team_b.p_key AS p_key
	FROM dbo.team_b JOIN dbo.team_d ON dbo.team_d.team_key = dbo.team_b.team_key GROUP BY dbo.team_d.p_key
) AS anon_2 ON anon_2.p_key = dbo.p_d.p_key
```


As I said, having to execute the query manually works fine, too so its really interesting that it doesn't when querying through the mapped class

**Comment by zzzeek** [comment] 2020-08-12 15:25
can you try sending `', '` as bytes:

```
    func.STRING_AGG(team_d.c.team_name, b', ')
```

or perhaps like this:

```
    from sqlalchemy import type_coerce

    func.STRING_AGG(team_d.c.team_name, type_coerce(', ', String))

```

**Comment by nico525** [comment] 2020-08-12 16:00
Both still result in the same issue.

**Comment by zzzeek** [comment] 2020-08-12 16:21
I would have thought the reason it can't find the function is because of the datatypes being passed.  

do you see the "N" here:

    SELECT STRING_AGG(dbo.team_d.team_name, N', ')

is that "N" in the raw query you have which works correctly?  

next thing to try, is like this:

    from sqlalchemy import literal_column
    func.STRING_AGG(team_d.c.team_name, literal_column(", "))

im not saying this is the solution we are just trying to narrow down what's happening here.

**Comment by zzzeek** [comment] 2020-08-12 16:21
cc @gordthompson

**Comment by nico525** [comment] 2020-08-13 05:59
a few updates:
- type_coerce utilizes a query parameter. This parameter does not have the N', '
- b', ' puts in the following parameter: bytearray(b', ')
- literal_column(", ") produces a wrong query without parameter: ...STRING_AGG(dbo.team_d.team_name, , ) WITHIN GROUP...
- literl_column("', '") produces a good query without parameter: ...STRING_AGG(agi.portfolio_management_team_d.team_name, ', ') WITHIN GROUP...

yet, none of them is producing any results - all run into the same error type. For development purposes I moved over to utilizing func.MAX without the ".within_group()". That is working fine, too.
It must be somehow related to how sqlalchemy sends the query to the connection. Maybe it's worth mentioning that I passed a pyodbc connection into the engine via:
`db_engine = create_engine("mssql+pyodbc://", creator=lambda: cnxn, echo=True)`

**Comment by zzzeek** [comment] 2020-08-13 13:15
usually we suspect things like, the database youre talking to is not the one you think you are, kind of thing.   but you are getting a SQL Server error message so that's definitely SQL Server.

STRING_AGG seems to be SQL Server 17, is there an older version of SQL Server in the mix ?   seems to be the diagnosis here for example: https://stackoverflow.com/questions/40923080/string-agg-is-not-a-recognized-built-in-function-name  for SQL Server 16

**Comment by nico525** [comment] 2020-08-13 13:25
Actually, it is querying against an Azure Synapse (dwh) service. But again, running the query directly works fine, also when executing the query string via
`text(str(self.session.query(codegenClass).statement.compile(dialect=mssql.dialect(), compile_kwargs={"literal_binds": True})))`

**Comment by gordthompson** [comment] 2020-08-13 13:38
It's not a straight-up varchar/nvarchar issue; there is a specific error for that:

``` python
team = sa.Table("team", sa.MetaData(), autoload_with=engine)
print(team.c.city.type)  # VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS"
with engine.connect() as conn:
    result = conn.execute(
        select(
            team.c.prov, sa.func.STRING_AGG(team.c.city, ",").label("cities")
        ).group_by(team.c.prov)
    ).fetchall()
    """console output:
    [ODBC Driver 17 for SQL Server][SQL Server]
    Argument data type nvarchar is invalid for argument 2 of 
    string_agg function.
    """
```

**Comment by gordthompson** [comment] 2020-08-13 16:28
For the record, a fix for the above snippet is to use `literal_column`:

``` python
team = sa.Table("team", sa.MetaData(), autoload_with=engine)
print(team.c.city.type)  # VARCHAR(20) COLLATE "SQL_Latin1_General_CP1_CI_AS"
with engine.connect() as conn:
    result = conn.execute(
        select(
            team.c.prov,
            sa.func.STRING_AGG(team.c.city, sa.literal_column("','")).label(
                "cities"
            ),
        ).group_by(team.c.prov)
    ).fetchall()
    print(result)
    """console output:
    [('AB', 'Calgary,Edmonton'), ('ON', 'Toronto')]
    """
```

**Comment by nico525** [comment] 2020-08-13 16:40
this is not working for me @gordthompson 
putting the whole STRING_AGG() WITHIN GROUP() into a literal column is also not working. could this be related to the driver? I am using ODBC Driver 17 for SQL Server

**Comment by gordthompson** [comment] 2020-08-13 16:59
That's what I am using too: msodbcsql17.dll, version 17.05.0001

**Comment by nico525** [comment] 2020-08-13 17:19
ah, it's probably working for you, because you are executing the query directly via conn.execute. If i do a session.execute from the raw statement, i get no error, too.
However, I cannot get the ResultProxy back casted to my model which is why I would like to query from the object: session.query(p).all()

**Comment by zzzeek** [comment] 2020-08-13 18:02
hey there.

I see you are using a `@dataclass`.

Are you using that with `mapper()` ?   Those..... won't really work correctly at the moment.     We have a patch in the works to support mapper() with `@dataclass` in https://github.com/sqlalchemy/sqlalchemy/issues/5027 .   it's not going to be in a production release anytime soon, though.

**Comment by nico525** [comment] 2020-08-13 19:19
actually, i already removed the `@dataclass` so that is not the root cause. I have created a view on the database creating the string_agg for me to deal with the issue in the meantime...

this is certainly a bug in the mapper. @gordthompson can you try putting a mapped class on top and query that via `session.query()` like I do?

**Comment by gordthompson** [comment] 2020-08-13 22:33
@nico525 - Is this what you had in mind? It works for me ....

``` python
engine = sa.create_engine(connection_uri, echo=False,)

Base = declarative_base()


class Team(Base):
    __tablename__ = "team"
    prov = sa.Column(sa.String(2), primary_key=True)
    city = sa.Column(sa.String(20), primary_key=True)
    team_name = sa.Column(sa.String(20))

    def __repr__(self):
        return f"<Task(prov='{self.prov}', city='{self.city}')>"


Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

result = (
    session.query(
        Team.prov,
        sa.func.STRING_AGG(Team.city, sa.literal_column("','"))
        .within_group(Team.city)
        .label("cities"),
    )
    .group_by(Team.prov)
    .all()
)
print(result)
"""console output:
[('AB', 'Calgary,Edmonton'), ('ON', 'Toronto')]
"""
```

**Comment by nico525** [comment] 2020-08-14 07:06
I nailed the issue down to having multiple outerjoin. My original p_d is actually looking different:
```
p_d = sql.outerjoin(p, v_d)\
    .outerjoin(team_b, (team_b.c.p_key == p_d.c.p_key))\
    .outerjoin(other_table, (v_d.v_id == other_table.c.v_id))\
    .outerjoin(other_table2, (v_d.v_id == other_table2.c.v_id))
    .outerjoin(other_table_sub, (other_table_sub.c.v_sub_id == other_table2.c.v_sub_id) & (other_table_sub.c.system=='TEST'))
```
I see no pattern in the outerjoin issue. I can add some tables, but sooner or later when adding the fully joined table, I run into the mentioned issue

**Comment by gordthompson** [comment] 2020-08-14 12:08
Is it possible for you to post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that will reproduce the issue?

**Comment by nico525** [comment] 2020-08-17 20:07
I will try to create one, but that might take a while

**Comment by zzzeek** [comment] 2020-09-10 18:12
so I'd like to close this if nothing more is happening, if you've managed to work around the issue that';s good though we would be curious to see a reproduction case if you can provide one.  reopen if so,thanks!

**Closed by zzzeek** 2020-09-10 18:12 UTC
Labels: SQL Server, question
