### ISSUE TITLE
IndexError: tuple index out of range with python3.6 and SQlAlchemy 1.4.45

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [sqlalchemy/sqlalchemy#8969] opened 2022-12-12 09:04 UTC
### Describe the bug

Getting exception while trying below code - 

```
        with op.batch_alter_table("<table_name>") as batch_op:

            batch_op.create_check_constraint(
                "ck_ssl_mode",
                "ssl_mode IN ('allow', 'prefer', 'require', 'disable', \
                'verify-ca', 'verify-full')"
            )
```

### To Reproduce

```python
with op.batch_alter_table("<table_name>") as batch_op:

            batch_op.create_check_constraint(
                "ck_ssl_mode",
                "ssl_mode IN ('allow', 'prefer', 'require', 'disable', \
                'verify-ca', 'verify-full')"
            )
```

### Error

```
File "/usr/pgadmin4/web/migrations/versions/09d53fca90c7_.py", line 55, in upgrade
    'verify-ca', 'verify-full')"
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/alembic/operations/base.py", line 374, in batch_alter_table
    impl.flush()
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/alembic/operations/batch.py", line 125, in flush
    **self.reflect_kwargs
  File "<string>", line 2, in __new__
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 694, in _init
    resolve_fks=resolve_fks,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 729, in _autoload
    _extend_on=_extend_on,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 804, in reflect_table
    reflection_options,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 998, in _reflect_fk
    **reflection_options
  File "<string>", line 2, in __new__
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 694, in _init
    resolve_fks=resolve_fks,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 729, in _autoload
    _extend_on=_extend_on,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 804, in reflect_table
    reflection_options,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 998, in _reflect_fk
    **reflection_options
  File "<string>", line 2, in __new__
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 694, in _init
    resolve_fks=resolve_fks,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 729, in _autoload
    _extend_on=_extend_on,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 824, in reflect_table
    reflection_options,
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 1095, in _reflect_unique_constraints
    constraints = self.get_unique_constraints(table_name, schema)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 632, in get_unique_constraints
    conn, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_unique_constraints
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2410, in get_unique_constraints
    **kw
  File "<string>", line 2, in get_indexes
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2521, in get_indexes
    if row[4]:
IndexError: tuple index out of range
``` 

### Versions

- OS: Centos7
- Python: 3.6.
- SQLAlchemy: 1.4.45
- Database: Sqlite3
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg

**Comment by CaselIT** [comment] 2022-12-12 09:42
Hi,

Is `sqlite2` correct, as in sqlite version 2.xx?

While unfortunate, I don't think it's supported by sqlalchemy since a long time, so you should pin the sqlalchemy version.

Sadly this is what happens when we accept backports of new features #8804

**Comment by yogeshmahajan-1903** [comment] 2022-12-12 10:08
Hi,

We are using SQLite version 3.32.3.

**Comment by CaselIT** [comment] 2022-12-12 13:04
ok, this definitely seems a regression, since 3.32.3 is very much supported. I'll update the labels.

**Comment by CaselIT** [comment] 2022-12-12 13:07
the issue seems to be the index_list pragma, apparently the added the 5th column recenrly

**Comment by zzzeek** [comment] 2022-12-12 22:44
every time I have to do this with sqlite I just get annoyed how people keep calling this project so incredibly well done.  not one mention of anything about this change in their full one page changelog: https://www.sqlite.org/changes.html

**Comment by zzzeek** [comment] 2022-12-12 22:47
> Hi,
> 
> We are using SQLite version 3.32.3.

an install of Python 3.6 on centos7 installs 3.7.17 unless you are doing a custom build.  I can reproduce the problem on centos7:

```py
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'
```

**Comment by CaselIT** [comment] 2022-12-12 22:49
ok so the issue is sqlite 3.8 added partial indexes, so previously `index_list` it would have 4 cols, not 5

@yogeshmahajan-1903 can you confirm that you are using sqlite3 `3.32.3`?

**Comment by CaselIT** [comment] 2022-12-12 22:51
@zzzeek we can add a workaround for 1.4 and raise the min supported version in 2? (aka keel like this but update the min supported version to be 3.8.+

**Comment by sqla-tester** [comment] 2022-12-12 23:06
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**check index_list pragma for number of columns returned** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4299

**Comment by sqla-tester** [comment] 2022-12-12 23:06
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**check index_list pragma for number of columns returned** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4300

**Comment by zzzeek** [comment] 2022-12-12 23:06
I think older sqlite's will solve themselves in 2.0 as centos also has python 3.6 only unless you are building

**Comment by yogeshmahajan-1903** [comment] 2022-12-13 05:33
> ok so the issue is sqlite 3.8 added partial indexes, so previously `index_list` it would have 4 cols, not 5
> 
> @yogeshmahajan-1903 can you confirm that you are using sqlite3 `3.32.3`?

Sorry my bad. 3.32.3 is used with python 3.9.
**Version used with python 3.6 is 3.7.17 on cents 7**
```
(venv) [root@localhost pgadmin]# sqlite3 ./pgadmin4.db 
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select sqlite_version();
3.7.17
sqlite> 
```

**Closed** 2022-12-14 13:29 UTC
Labels: bug, sqlite, reflection, regression, next release
