### ISSUE TITLE
Add support for sqlite's INSERT ... ON CONFLICT ...

### ISSUE THREAD

**Issue by DrPyser** [sqlalchemy/sqlalchemy#4709] opened 2019-06-03 16:39 UTC
https://sqlite.org/lang_UPSERT.html

SQLite recent versions ( since 3.24.0 (2018-06-04) ) supports upserts statements through the same syntax as postgresql, `INSERT ... ON CONFLICT ... DO ... `.

That would be a great addition to the sqlite dialect support.

Thanks for the great work!

**Comment by zzzeek** [comment] 2019-06-03 16:47
yup, see #4010

**Comment by zzzeek** [comment] 2019-06-03 16:47
closing this as this is a dupe of #4010

**Comment by DrPyser** [comment] 2019-06-03 16:48
Oh, sorry, thought that was only for the "insert or replace" functionality.

**Closed by zzzeek** 2019-06-03 16:47 UTC
Labels: duplicate

**Comment by zzzeek** [comment] 2019-06-03 16:54
geez, they have both, let me sort it out

**Comment by zzzeek** [comment] 2019-06-03 17:03
when taht issue was created apparently SQLite didnt have ON CONFLICT yet.  but that is all anybody wants AFAIK.
