### ISSUE TITLE
Some slashes are lost when data is inserted into `bytea` column in Postgres DB

### ISSUE THREAD

**Issue by yyibin** [sqlalchemy/sqlalchemy#5479] opened 2020-07-28 00:49 UTC
Some slashes are lost when data is inserted into column that has `bytea` type in Postgres DB. 

For example, if the data is `C:\\\\test.txt`, the data saved to the DB looks like `C:\\test.txt`.

**Expected behavior**
Slashes shouldn't be lost.

**To Reproduce**
The following code inserts data into `servers` table.

The `servers` table looks like
```
# \d servers;
Table "<pg_schema_name>.servers"
 Column | Type  | Collation | Nullable | Default 
--------+-------+-----------+----------+---------
 id     | uuid  |           | not null | 
 config | bytea |           | not null | 
Indexes:
    "servers_pkey" PRIMARY KEY, btree (id)
```

```py
from sqlalchemy import sql as sqlalchemy_sql, create_engine
from sqlalchemy.orm.session import Session

uri = "postgresql://root:postgres@postgres:5432/<db_name>?client_encoding=utf8"
col_names = set(['config', 'id'])
table = "servers"
t = sqlalchemy_sql.table(table, *(sqlalchemy_sql.column(c) for c in col_names))

engine = create_engine(uri)
session = Session(bind=engine)
session.execute("SET search_path TO <pg_schema_name>;")
t.bind = session.get_bind()

values = [{'config': 'C:\\\\test.txt', 'id': 'f8768281-de43-4812-b6ca-c03181e97c83'}]
statement = t.insert(values=values)

foo = session.execute(statement)
session.execute('COMMIT;')
```

**Error**

No error stack. 

When the data is retrieved, some slashes are lost.

```
res = session.execute('select * from servers;')
for r in res:
    test = r

>>> test
(UUID('f8768281-de43-4812-b6ca-c03181e97c83'), <read-only buffer for 0x7f55175d1c90, size 11, offset 0 at 0x7f55166c9130>)
>>> str(test[1])
'C:\\test.txt'
```

**Versions.**
 - OS: python:2.7.14-alpine3.4 (base docker image)
 - Python: 2.7
 - SQLAlchemy: 1.3.18
 - Database: Postgres

**More context**
Slashes are not lost if the column type is `varchar`.

Tried the same insertion code with the following table and slashes are not lost:
```
# \d users;
      Table "<pg_schema_name>.auth_servers"
    Column    |          Type          | Collation | Nullable | Default 
--------------+------------------------+-----------+----------+---------
 id           | uuid                   |           | not null | 
 name         | character varying(128) |           | not null | 
```
```
>>> uri = "postgresql://root:postgres@postgres:5432/<db_name>?client_encoding=utf8"
>>> col_names = set(['name', 'id'])
>>> table = "users"
>>> t = sqlalchemy_sql.table(table, *(sqlalchemy_sql.column(c) for c in col_names))
>>> 
>>> engine = create_engine(uri)
>>> session = Session(bind=engine)
>>> session.execute("SET search_path TO <pg_schema_name>;")
<sqlalchemy.engine.result.ResultProxy object at 0x7f5516687890>
>>> t.bind = session.get_bind()
>>> 
>>> values = [{'name': 'C:\\\\test.txt', 'id': 'f8768281-de43-4812-b6ca-c03181e97c81'}]
>>> statement = t.insert(values=values)
>>> 
>>> foo = session.execute(statement)
>>> session.execute('COMMIT;')
<sqlalchemy.engine.result.ResultProxy object at 0x7f55166c90d0>
>>> 
>>> bar = session.execute('select * from users;')
>>> 
>>> for r in res:
...     test = r
... 
>>> r
(UUID('f8768281-de43-4812-b6ca-c03181e97c81'), u'C:\\\\test.txt')

```

**Comment by zzzeek** [comment] 2020-07-28 01:35
hi there -

can't reproduce.  complete MCVE below (note you didn't share your table defs).  Additionally if you are having an issue like this it would reside in the version of psycopg2 you're using as SQLAlchemy doesn't do anything with BYTEA except pass it to your driver.

Also when using backslashes it's a good idea to use r'' strings to avoid confusion with escaping backslashes.

below is python 2.7.18 and psycopg2  2.8.4.




```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.dialects.postgresql import BYTEA
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm.session import Session

uri = "postgresql://scott:tiger@localhost/test?client_encoding=utf8"

m = MetaData()

t = Table("t", m, Column("name", UUID()), Column("data", BYTEA))

engine = create_engine(uri)
m.drop_all(engine)
m.create_all(engine)

session = Session(bind=engine)

data_value = "C:\\\\test.txt"

values = [{"data": data_value, "name": "f8768281-de43-4812-b6ca-c03181e97c83"}]
statement = t.insert(values=values)

foo = session.execute(statement)
session.commit()


bar = session.execute("select * from t")

row = bar.fetchone()

assert str(row[1]) == data_value

```

**Comment by CaselIT** [comment] 2020-07-29 20:17
I think that the problems is because of the use of `table` and `column` without specifying the type.
I've updated the example mike
```py
from sqlalchemy import column
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import MetaData
from sqlalchemy import table
from sqlalchemy import Table
from sqlalchemy.dialects.postgresql import BYTEA
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm.session import Session

uri = "postgresql://scott:tiger@localhost/test?client_encoding=utf8"

m = MetaData()

t = Table("t", m, Column("name", UUID()), Column("data", BYTEA))

engine = create_engine(uri)
m.drop_all(engine)
m.create_all(engine)

session = Session(bind=engine)

data_value = "C:\\\\test.txt"

values = [{"data": data_value, "name": "f8768281-de43-4812-b6ca-c03181e97c83"}]
# define lowercase table and columns
t = table('t', column('name'), column('data'))

statement = t.insert(values=values)

foo = session.execute(statement)
session.commit()


bar = session.execute("select * from t")

row = bar.fetchone()

assert str(row[1]) != data_value
print(str(row[1]), data_value, str(row[1]) == data_value)
```

The solution is to specify the type when defining the `columns`

**Comment by zzzeek** [comment] 2020-07-30 00:05
oh right, the original example just used table(column(..)) , that won't work either.     DBAPI requires that a binary value be sent using dbapi.binary():  https://www.python.org/dev/peps/pep-0249/#binary   in Python 2, there is otherwise no way to distinguish between string and bytes.

**Comment by yyibin** [comment] 2020-07-30 18:00
Thanks for the replies. I am using psycopg2 2.8.4 as well.

I was able to make it work after replacing
```
t = sqlalchemy_sql.table(table, *(sqlalchemy_sql.column(c) for c in col_names))
```
with
```
t = sqlalchemy_sql.table("servers", Column("id", UUID()), Column("config", BYTEA))
```

I was also able to fix the issue by wrapping up the binary string with `psycopg2.Binary` so that the driver knows it's a binary string and knows how to escape the string properly.

**Comment by CaselIT** [comment] 2020-07-31 07:23
Closing this. Feel free to reopen if you encounter other issues

**Closed by CaselIT** 2020-07-31 07:23 UTC
Labels: question
