### ISSUE TITLE
New PG Range.__eq__() should not raise an exception comparing with a non-Range value

### ISSUE THREAD

**Issue by lelit** [sqlalchemy/sqlalchemy#8984] opened 2022-12-14 20:17 UTC
### Describe the bug

As written, the method [Range.__eq__()](https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_0b4/lib/sqlalchemy/dialects/postgresql/ranges.py#L287) declares its argument as `other: Any`, but it really expects another instance of the same class, otherwise it raises an exception.

### To Reproduce

```python
>>> from sqlalchemy.dialects.postgresql import Range
>>> r = Range(1,10)
>>> r == None
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lele/wip/sqlalchemy/lib/sqlalchemy/dialects/postgresql/ranges.py", line 294, in __eq__
    elif self.empty != other.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
``` 

### Versions

- OS: any
- Python: any
- SQLAlchemy: 2.0.0b4+
- Database: irrilevant
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): irrilevant

### Additional context

@CaselIT suggested to return `NotImplemented`, that seems the right thing to do accordingly to the [documentation](https://docs.python.org/3/library/constants.html#NotImplemented).

**Comment by lelit** [comment] 2022-12-15 17:02
Mike, do I do something wrong when creating the PR linked to an issue, that impedes the automatic close of the latter? Or is it a manual process anyway?

**Comment by zzzeek** [comment] 2022-12-15 17:06
the commit itself has the issue number, which on github will close the issue, provided it's in the main branch which is the case here.   the PR being closed here, as opposed to "merged", doesn't look as nice, but that's per the current PR <-> gerrit design and should not impact the issue getting closed automatically.

**Comment by lelit** [comment] 2022-12-15 17:10
Ah, ok, so IIUC it gets closed only once you merge it into next beta...

**Comment by CaselIT** [comment] 2022-12-15 17:31
I think the issue is that `Closes #id` is not understood by github. You need to use `Fixes: #id`

**Comment by CaselIT** [comment] 2022-12-15 17:33
no sorry, my mistake. This issue is not closed because it's missing the "closes / fixes #issue-id" . 

The commit message is
```
Fix equality comparison between a PG Range and a different class inst…

…ance

This fixes issue https://github.com/sqlalchemy/sqlalchemy/issues/8984, making the method `Range.__eq__` return `NotImplemented` when the argument is an instance of a different class.

Closes: https://github.com/sqlalchemy/sqlalchemy/pull/8985
Pull-request: https://github.com/sqlalchemy/sqlalchemy/pull/8985
Pull-request-sha: https://github.com/sqlalchemy/sqlalchemy/commit/b8f601f038a2203af02a99ab190ebbc1c489549a

Change-Id: Iaf0b651a22a9f346c8f18b3a53e3339bf61bb33f
```

it should be
```
Fix equality comparison between a PG Range and a different class inst…

…ance

This fixes issue https://github.com/sqlalchemy/sqlalchemy/issues/8984, making the method `Range.__eq__` return `NotImplemented` when the argument is an instance of a different class.

Fixes: #8984
Closes: https://github.com/sqlalchemy/sqlalchemy/pull/8985
Pull-request: https://github.com/sqlalchemy/sqlalchemy/pull/8985
Pull-request-sha: https://github.com/sqlalchemy/sqlalchemy/commit/b8f601f038a2203af02a99ab190ebbc1c489549a

Change-Id: Iaf0b651a22a9f346c8f18b3a53e3339bf61bb33f
```

**Comment by zzzeek** [comment] 2022-12-15 18:00
oh missed that.  then yes that was a mistake :)

**Comment by lelit** [comment] 2022-12-15 18:17
Thanks&sorry, hopefully I won't repeat the mistake! :-)

**Comment by CaselIT** [comment] 2022-12-15 18:39
No problem!

**Closed by CaselIT** 2022-12-15 18:39 UTC
Labels: bug, postgresql
