### ISSUE TITLE
`restore_load_context` flag doesn't propagate to subclasses

### ISSUE THREAD

**Issue by HeyBillFinn** [sqlalchemy/sqlalchemy#5737] opened 2020-12-01 20:03 UTC
**Describe the bug**

When listing for "load" instance events, `restore_load_context` flag doesn't seem to propagate to subclasses.

**Expected behavior**

The `restore_load_context` flag would also apply to event listeners created on subclasses of the parent class.

**To Reproduce**

```py
import sqlalchemy
from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    MetaData,
    String,
    create_engine,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, relationship

Base = declarative_base()


@sqlalchemy.event.listens_for(
    Base, "load", propagate=True, restore_load_context=True
)
def on_load_1(target, context):
    target.on_load()


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)

    def on_load(self):
        pass


class Foo(Base):
    __tablename__ = "foos"
    __mapper_args__ = {"polymorphic_on": "type"}

    id = Column(Integer, primary_key=True)
    type = Column(String, nullable=False)

    def on_load(self):
        pass


class SubFoo(Foo):
    __tablename__ = "foos_sub"
    __mapper_args__ = {"polymorphic_identity": "USER"}

    id = Column(Integer, ForeignKey("foos.id"), primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    user = relationship("User")

    def on_load(self):
        print(self.user.id)


# @sqlalchemy.event.listens_for(SubFoo, "load", restore_load_context=True)
# def on_load_2(target, context):
#     print("on load!")
#     target.on_load()


engine = create_engine("sqlite://")
metadata = MetaData()
with engine.begin() as connection:
    metadata = Base.metadata
    metadata.drop_all(connection)
    metadata.create_all(connection)

session = Session(bind=engine)

user = User()
sub_foo = SubFoo(user=user)
session.add_all([user, sub_foo])
session.commit()
session.close()

session.query(Foo).all()
```

**Error**

```
1
/home/vagrant/local/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py:349: SAWarning: Loading context for <SubFoo at 0x7f8aa86e4390> has changed within a load/refresh handler, suggesting a row refresh operation took place. If this event handler is expected to be emitting row refresh operations within an existing load or refresh operation, set restore_load_context=True when establishing the listener to ensure the context remains unchanged when the event handler completes.
  "handler completes." % (state_str(state),)
```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 2.7
 - SQLAlchemy: 1.3.20
 - Database: sqlite
 - DBAPI: none (?)

**Additional context**

Replacing the "load" event listener on the base class with a load event listener on the specific class fixes the warning.

I couldn't immediately understand why this isn't working. In `InstanceEvents._listen`, it looks like we're creating a single `wrap` function that should be used and propagated to all subclasses:

https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_20/lib/sqlalchemy/orm/events.py#L205-L237

**Have a nice day!**

You, too!

**Comment by zzzeek** [comment] 2020-12-01 20:51
here's the fix

```
diff --git a/lib/sqlalchemy/orm/events.py b/lib/sqlalchemy/orm/events.py
index a0e100a81..6e00c53c3 100644
--- a/lib/sqlalchemy/orm/events.py
+++ b/lib/sqlalchemy/orm/events.py
@@ -550,7 +550,7 @@ class _EventsHold(event.RefCollection):
                 collection = target.all_holds[target.class_] = {}
 
             event.registry._stored_in_collection(event_key, target)
-            collection[event_key._key] = (event_key, raw, propagate, retval)
+            collection[event_key._key] = (event_key, raw, propagate, retval, kw)
 
             if propagate:
                 stack = list(target.class_.__subclasses__())
@@ -577,7 +577,7 @@ class _EventsHold(event.RefCollection):
         for subclass in class_.__mro__:
             if subclass in cls.all_holds:
                 collection = cls.all_holds[subclass]
-                for event_key, raw, propagate, retval in collection.values():
+                for event_key, raw, propagate, retval, kw in collection.values():
                     if propagate or subclass is class_:
                         # since we can't be sure in what order different
                         # classes in a hierarchy are triggered with
@@ -585,7 +585,7 @@ class _EventsHold(event.RefCollection):
                         # assignment, instead of using the generic propagate
                         # flag.
                         event_key.with_dispatch_target(subject).listen(
-                            raw=raw, propagate=False, retval=retval
+                            raw=raw, propagate=False, retval=retval, **kw
                         )

```

**Comment by zzzeek** [comment] 2020-12-01 20:54
basically if you apply your event handler *after* all the classes are mapped, that works around the issue for now.  the issue is for classes that are not yet mapped when the event handler is applied.

**Comment by sqla-tester** [comment] 2020-12-01 21:06
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Pass along other keyword args in _EventsHold.populate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2389

**Comment by sqla-tester** [comment] 2020-12-01 21:06
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Pass along other keyword args in _EventsHold.populate** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2390

**Closed** 2020-12-01 21:44 UTC
Labels: bug, events, orm
