### ISSUE TITLE
Issues with typings + DeclarativeBase

### ISSUE THREAD

**Issue by ramarivera** [sqlalchemy/sqlalchemy#8645] opened 2022-10-16 18:14 UTC
### Describe the bug

I wanted to create a base class, so I was following this: https://docs.sqlalchemy.org/en/20/orm/declarative_mixins.html#augmenting-the-base

### To Reproduce

Litearlly copied the code block, but it doesn't work.
I tried reinstalling my whole venv from scratch, using pyenv and poetry, resintalled everything I could from scratch, deleted all caches.

I also tried using `classmethod` but that only clears a pylint warning

### Error

N/A

### Versions

- OS: Win 11
- Python: 3.10.7
- SQLAlchemy:  Latest beta
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

### Additional context

![image](https://user-images.githubusercontent.com/7547875/196051218-6aadeff4-02fc-4cd8-a996-79d8b8d4eaa9.png)

```py
from sqlalchemy import ForeignKey
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    declared_attr,
    mapped_column,
    relationship,
)

class Base(DeclarativeBase):
    """define a series of common elements that may be applied to mapped
    classes using this class as a base class."""

    @declared_attr.directive
    def __tablename__(cls) -> str:
        return cls.__name__.lower()

    __table_args__ = {"mysql_engine": "InnoDB"}
    __mapper_args__ = {"eager_defaults": True}

    id: Mapped[int] = mapped_column(primary_key=True)


class HasLogRecord:
    """mark classes that have a many-to-one relationship to the
    ``LogRecord`` class."""

    log_record_id: Mapped[int] = mapped_column(ForeignKey("logrecord.id"))

    @declared_attr
    def log_record(self) -> Mapped["LogRecord"]:
        return relationship("LogRecord")


class LogRecord(Base):
    log_info: Mapped[str]


class MyModel(HasLogRecord, Base):
    name: Mapped[str]

```

**Comment by ramarivera** [comment] 2022-10-16 21:24
Well, after 3 hours, I remove vs code, installed vs code insiders, did a full disk search for virtual envs, deleted everything, deleted my whole vs code sync....

Now, it feels much faster, and I do not see so many weird paths on Python logs... 

However this still doesn't work :(

**Comment by CaselIT** [comment] 2022-10-16 21:47
Hi,

thanks for reporting. 

I'm not sure if this is an error on out part or a bug in pylance.
To reproduce:
```py
from typing import Any, ClassVar

class Foo:
    Bar: ClassVar[Any]

class Baz(Foo):
    @classmethod
    def Bar(cls):
        return 42
```

**Comment by CaselIT** [comment] 2022-10-16 21:52
It seems that a classmethod is not considered a ClassVar by pylance.
using as type information `ClassVar[Any] | classmethod[Any]` seems to work.

Not sure if it's expected or not.

**Comment by CaselIT** [comment] 2022-10-16 21:57
The `ClassVar[Any] | classmethod[Any]` is not liked by mypy, that will error with
```
test1.py:50: error: Invalid type: ClassVar nested inside other type  [misc]
test1.py:55: error: Signature of "Bar" incompatible with supertype "Foo"  [override]
```

**Comment by ramarivera** [comment] 2022-10-16 22:04
Also I found this issue on Pylance https://github.com/microsoft/pylance-release/issues/2129.

**Comment by CaselIT** [comment] 2022-10-16 22:07
it does not seem relevant since that's probably using 1.4 where the types were very different

**Comment by CaselIT** [comment] 2022-10-16 22:10
I've opened an issue in pylance, since I don't know the answer here and pyright, mypy and pylance each have a different opinion

**Comment by ramarivera** [comment] 2022-10-16 22:12
Thanks. Since it seems to be a type issue (I practically pasted the code from the docs), do you know any way to omit thst overload warning only?

**Comment by ramarivera** [comment] 2022-10-16 22:16
Seems like I could do this in the meantime: https://github.com/microsoft/pyright/blob/main/docs/configuration.md

**Comment by CaselIT** [comment] 2022-10-16 22:17
Sure, just placr `# type: ignore` on the line where you are defining the tablename

**Comment by ramarivera** [comment] 2022-10-16 22:22
Or this:

```
[tool.pyright]
reportIncompatibleVariableOverride = false
````

**Comment by zzzeek** [comment] 2022-10-16 22:51
yeah id go with that.  we will likely have to document these. pyright has a lot of opinions that are not exactly easy to work with.

**Comment by CaselIT** [comment] 2022-10-18 16:28
in this issue we could probably also add `__table_args__` and `__mapper_args__`
Is there a way to tell python that an attribute may not exists? like `NotRequired` or something?

ref https://github.com/sqlalchemy/sqlalchemy/discussions/8650#discussioncomment-3907861

**Comment by zzzeek** [comment] 2022-10-18 16:37
that might have been the issue.    pep-484 is not very good with this style of configuration

**Comment by CaselIT** [comment] 2022-10-18 16:49
I guess we could set them if they are missing when the class is mapped?

**Comment by CaselIT** [comment] 2022-10-18 17:23
I mean that since there is not really a way to indicate that an attribute is there but could not we could set those attributes if they are not present in the class when that's mapped by the orm

**Comment by zzzeek** [comment] 2022-10-18 17:30
you mean populate blank attributes on DeclarativeBase?   I suppose.   but yeah they'd ahve to be there.

Because DeclarativeBase is new, we can do new things like this, so sure.

**Comment by CaselIT** [comment] 2022-10-18 18:19
let's try

**Comment by sqla-tester** [comment] 2022-10-18 19:09
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve typing of DeclarativeBase** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4137

**Closed** 2022-10-20 13:21 UTC
Labels: bug, typing, orm - annotated declarative, type checker issue
