### ISSUE TITLE
(psycopg2.InterfaceError) cursor already closed

### ISSUE THREAD

**Issue by mam8cc** [sqlalchemy/sqlalchemy#5258] opened 2020-04-16 21:45 UTC
We are experiencing behavior strikingly similar to https://github.com/sqlalchemy/sqlalchemy/issues/4841.

```
Traceback (most recent call last):
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1211, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1161, in _fetchall_impl
    return self.cursor.fetchall()
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/esapi/env/lib/python3.6/site-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/esapi/env/lib/python3.6/site-packages/ddtrace/contrib/flask/helpers.py", line 20, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/opt/esapi/env/lib/python3.6/site-packages/ddtrace/contrib/flask/patch.py", line 478, in _traced_request
    return wrapped(*args, **kwargs)
  File "/opt/esapi/env/lib/python3.6/site-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/opt/esapi/env/lib/python3.6/site-packages/ddtrace/contrib/flask/wrappers.py", line 23, in trace_func
    return wrapped(*args, **kwargs)
  File "/opt/esapi/app/app/__init__.py", line 155, in set_user
    db_token = session.query(UserAuthToken).filter(UserAuthToken.token == raw_token).first()
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    util.raise_from_cause(err)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 77, in instances
    fetch = cursor.fetchall()
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1216, in fetchall
    e, None, None, self.cursor, self.context
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1211, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1161, in _fetchall_impl
    return self.cursor.fetchall()
sqlalchemy.exc.InterfaceError: (psycopg2.InterfaceError) cursor already closed
(Background on this error at: http://sqlalche.me/e/rvf5)
```

Our application is a Flask app running in a threaded `gunicorn` environment.  Our database is `postgres-9.6`.  We are also running PGBouncer between the application and the database.

This problem occured when we switched from using process based workers in gunicorn to thread based workers in gunicorn.  We have attempted to use `pre_ping=True` to verify the connection before use.  This appears to primarly impact the first SQL query emitted by a request but doesn't seem related to the first request of a thread.  At this time we are unable to reproduce the issue consistently and would like some input on how we could more reliably reproduce the error.

Since you asked in the referenced report for the SQL, this is the query it is running:
```
SELECT * FROM user_auth_tokens WHERE token = 'XXXX-XXXX-XXXX-XXXX'
```

**Comment by mam8cc** [comment] 2020-04-16 21:49
We have also tried to do verbose pool logging but it is hard to correlate the pool events with the request and error that occurred, however we do have this:

```
Apr 15 20:31:01 equipmentshare-api-6dd966858d-sxk7s equipmentshare-api ERROR sqlalchemy.pool.impl.QueuePool Exception during reset or similar  
Apr 15 20:31:01 equipmentshare-api-6dd966858d-sxk7s equipmentshare-api Traceback (most recent call last):
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 733, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/opt/esapi/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 531, in do_rollback
    dbapi_connection.rollback()
  File "/opt/esapi/env/lib/python3.6/site-packages/ddtrace/contrib/dbapi/__init__.py", line 189, in rollback
    return self._trace_method(self.__wrapped__.rollback, span_name, {}, *args, **kwargs)
  File "/opt/esapi/env/lib/python3.6/site-packages/ddtrace/contrib/dbapi/__init__.py", line 174, in _trace_method
    return method(*args, **kwargs)  
```

**Comment by CaselIT** [comment] 2020-04-16 22:03
Sounds like the session is shared by multiple thread.
I think you could try `scoped_session` for a thread local session? https://docs.sqlalchemy.org/en/13/orm/contextual.html

**Comment by mam8cc** [comment] 2020-04-16 22:54
We are using scoped session already, unfrotunately.

```
engine = create_engine(
        context.config.db_uri,
        connect_args={'application_name': context.application_name},
        echo_pool='debug'
    )

session = scoped_session(sessionmaker(bind=engine))
```

**Comment by zzzeek** [comment] 2020-04-17 00:06
IIUC gunicorn is using greenlets, not threads ?   that would be a very important distinction.

**Comment by mam8cc** [comment] 2020-04-17 01:28
We are using the `gthread` worker type in gunicorn.  This is not my wheel house but based on [this comment](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/gthread.py#L7) it seems like `gthread` workers use

**Comment by zzzeek** [comment] 2020-04-17 13:59
see if the issue goes away when you reduce to just one thread, or if it decreases in occurence when using fewer threads.  this would all suggest a mis-organization of engines / sessions in the source code which is causing some kind of situation that is confusing the state of the psycopg2 connection.

Are you using server-side cursors?  that might make this more likely.   as it stands I can't reproduce any issue on this end working with raw psycopg2 cursors and threads.

over at https://stackoverflow.com/questions/35651586/psycopg2-cursor-already-closed it is suggested that cursor already closed is some side effect of the connection being disconnected, but I can't reproduce that here and also you'd want to see if there is an exception in your logs stating that the connection overall got disconnected.

**Comment by CaselIT** [comment] 2020-04-17 14:48
Not sure if maybe it's the connection pool that is causing problems if there are many threads an not enough connections? I'm not familiar with the default QueuePool implementation so I'm not sure if this case could happen, but maybe it's worth trying the NullPool just to exclude it?

**Comment by zzzeek** [comment] 2020-04-17 15:07
that wouldn't impact anything, the QueuePool blocks when it's out of connections.  it doesn't start sharing already-checked out connections, that would be pretty broken.

**Comment by CaselIT** [comment] 2020-04-17 15:14
That's what I figured.

**Comment by zzzeek** [comment] 2020-04-23 15:53
please reopen if you are able to provide a reproducing example script.

**Closed by zzzeek** 2020-04-23 15:53 UTC
Labels: question

**Comment by vstokarev** [comment] 2023-02-27 21:47
@mam8cc Have you found a solution? I'm having the exact same issue.
I was seeing the following error when I tried using regular session:
```
File /home/worker/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py, line 754, in _connection_for_bind
    if self.session.twophase and self._parent is None:
AttributeError: 'NoneType' object has no attribute 'twophase'
```

And when I switched to scoped session I started getting `cursor already closed` error.

**Comment by CaselIT** [comment] 2023-02-27 21:50
You seem to be sharing the same session in multiple threads/tasks. Session does not support concurrent execution

**Comment by vstokarev** [comment] 2023-02-27 23:02
> You seem to be sharing the same session in multiple threads/tasks. Session does not support concurrent execution

But I don't do any threads management. Just like the author of this issue I use `gunicorn` and occasionally get `cursor already closed` issue. I noticed that usually it happens when two queries land almost at the same time (when there's less that 0.1 sec between them) - the second request fails. So I'd probably agree that it has something to do with threads and that's why I thought that scoped session would help, but apparently it's not enough and I'm not sure what to do next. Found [this](https://www.reddit.com/r/django/comments/102fpyu/cursor_already_closed/) thread on Reddit saying that the issue might be in gunicorn, but also wanted to check if the author was able to find a solution.

**Comment by zzzeek** [comment] 2023-02-27 23:15
> > You seem to be sharing the same session in multiple threads/tasks. Session does not support concurrent execution
> 
> But I don't do any threads management.  Just like the author of this issue I use `gunicorn` and occasionally get `cursor already closed` issue. I noticed that usually it happens when two queries land almost at the same time (when there's less that 0.1 sec between them) - the second request fails. So I'd probably agree that it has something to do with threads 

so you're using concurrency.   when your web framework makes a "request", use a Session that is pinned to that request and is not accessible by code that isn't running in that request.

the reason people have trouble with scoped_session() is because none of these servers use real "threads", they are using various kinds of event-based execution which is not correctly integrated with threading.local().

**Comment by vstokarev** [comment] 2023-02-28 00:48
@zzzeek Honestly it took me a while to wrap my head around what you've said, but eventually your hint about pinning a session to a request was a key to a solution (I think). Once I started storing sessions (my app sometimes needs to have multiple connections) in Flask application context I could not reproduce the issue anymore. Hopefully it is solved now, thank you very much for the hint!
