### ISSUE TITLE
Incorrect interference between "not_" and "any_"

### ISSUE THREAD

**Issue by amaslyaev** [sqlalchemy/sqlalchemy#10817] opened 2024-01-02 12:42 UTC
### Describe the bug

The statement `not_(some_value == any_(some_array))` is being compiled into `some_value != any_(some_array)`. That is wrong.

### SQLAlchemy Version in Use

2.0.24

### DBAPI (i.e. the database driver)

all

### Database Vendor and Major Version

all

### Python Version

all

### Operating system

all

### To Reproduce

```python
from sqlalchemy import not_, any_

print("Got:", not_("a" == any_(["a", "b", "c"])))
print("Expected: NOT (:param_1 = ANY (:param_2))")
```

### Error

```
Got: :param_1 != ANY (:param_2)
Expected: NOT (:param_1 = ANY (:param_2))
``` 

### Additional context

The true equivalent for this statement with eliminated "NOT" is `some_value != all_(some_array)`:
```sql
SELECT
	NOT ('a' = ANY(ARRAY['a', 'b', 'c'])) AS expected,
	'a' != ANY(ARRAY['a', 'b', 'c']) AS got,
	'a' != ALL(ARRAY['a', 'b', 'c']) AS equivalent
```
Returns: `false | true | false`

**Comment by CaselIT** [comment] 2024-01-02 14:07
Hi,

This is likely a duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/6612

**Comment by CaselIT** [comment] 2024-01-02 14:10
On second though maybe not. I guess `all`/`any` should disable expression simplification cc @zzzeek

**Comment by zzzeek** [comment] 2024-01-02 14:27
in my comment at https://github.com/sqlalchemy/sqlalchemy/issues/6612#issuecomment-858788266 i claimed " we do something like this right now for array.any()" but so far I'm not reproducing that.  maybe PG compiler only...

**Comment by zzzeek** [comment] 2024-01-02 15:18
this is a mess.  There's an older version of any/all without the underscore that *does* work, and is tested, however the way it works is not very good internally either.

```
from sqlalchemy import not_, any_
from sqlalchemy.dialects.postgresql import array


val = array(["a", "b", "c"])

print(not_("a" == any_(val)))


print(not_(val.any("a")))


```

output

```
:param_1 != ANY (ARRAY[%(param_2)s, %(param_3)s, %(param_4)s])
NOT (ARRAY[%(param_1)s] = ANY (ARRAY[%(param_2)s, %(param_3)s, %(param_4)s]))

```

**Comment by CaselIT** [comment] 2024-01-02 15:42
`array.any` was probably made to work like that since it's otherwise broken

**Comment by sqla-tester** [comment] 2024-01-02 16:16
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**WIP: refactor any_ / all_** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5058

**Comment by zzzeek** [comment] 2024-01-02 16:19
I had a few things that were working but I have too much going on right now to focus on it

**Comment by zzzeek** [comment] 2024-01-02 16:19
so that's the tests, need to fix for the NULL case also

**Comment by sqla-tester** [comment] 2024-01-02 17:49
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**refactor any_ / all_** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5061

**Comment by sqla-tester** [comment] 2024-01-02 18:05
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**allow literals for function arguments** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5062

**Comment by sqla-tester** [comment] 2024-01-02 18:05
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**allow literals for function arguments** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5063

**Closed** 2024-01-02 23:48 UTC
Labels: bug, postgresql, sql

**Comment by amaslyaev** [comment] 2024-01-03 15:30
Guys, you are fantastic. Thanks a lot!
