### ISSUE TITLE
query.join is ignoring Table objects as targets

### ISSUE THREAD

**Issue by scnerd** [sqlalchemy/sqlalchemy#6003] opened 2021-03-05 17:03 UTC
**Describe the bug**
A regular inner join is compiled as a cartesian join.

**Expected behavior**
This should produce a regular left-outer join between tables 1 and 2, and an (inner) join between tables 1 and 3. This works properly in version 1.3.23. The error observed above was seen in 1.4.0b2.

**To Reproduce**

Using version 1.4.0b2,

```
query = (
    session
    .query(<columns from table1>) 
    .outerjoin(table3, <table1 and table3 join condition>)
    .join(table2, <table1 and table2 join condition>)
    .filter(<some more conditions>)
)
```

**Error**

```
.../sqlalchemy/sql/compiler.py:357: SAWarning: SELECT statement has a cartesian product between FROM element(s) "TABLE1" and FROM element "TABLE2".  Apply join condition(s) between each element to resolve.
    util.warn(message)
```

Note that the warning warns about the table joined using ``.join`` and not the table joined in the ``.outerjoin``.

The warning is not a mistake, in the final results we really do see the result of a cartesian join instead of a proper inner join.

**Versions.**
 - OS: Ubuntu (recent, not sure the exact version)
 - Python: 3.9
 - SQLAlchemy: 1.4.0b2
 - Database: MSSQL
 - DBAPI: FreeTDS

**Additional context**
Works properly in 1.3.23

**Have a nice day!**

**Comment by zzzeek** [comment] 2021-03-05 18:43
we are on 1.4.0b3 now and #5924 fixed an issue in the cartesian product logic, can you just check 1.4.0b3 still has the issue, thanks.

**Comment by zzzeek** [comment] 2021-03-05 18:49
can't reproduce on either 1.4.0b2 or b3, here is the MCVE:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

class C(Base):

    __tablename__ = 'c'

    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)


s.query(A).outerjoin(C, C.a_id==A.id).join(B, B.a_id == A.id).filter(B.data == 'foo').all()


```

output:

```
SELECT a.id AS a_id, a.data AS a_data 
FROM a LEFT OUTER JOIN c ON c.a_id = a.id JOIN b ON b.a_id = a.id 
WHERE b.data = ?

```
on 1.3, SQL is identical:

```
SELECT a.id AS a_id, a.data AS a_data 
FROM a LEFT OUTER JOIN c ON c.a_id = a.id JOIN b ON b.a_id = a.id 
WHERE b.data = ?
```



> A regular inner join is compiled as a cartesian join. 
> The warning is not a mistake, in the final results we really do see the result of a cartesian join instead of a proper inner join.

OK so the warning is not the problem, it's the SQL .  The above test case produces the same SQL on 1.4 and 1.3.   I really need to see complete [MCVE](http://stackoverflow.com/help/mcve), thanks

**Comment by scnerd** [comment] 2021-03-05 18:54
I can confirm that this error persists in 1.4.0b3, I'll create a MCVE in a minute...

**Comment by scnerd** [comment] 2021-03-05 19:10
It appears that the critical factor is that the tables are reflected out of the database rather than being defined in Python using the ORM:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

class C(Base):

    __tablename__ = 'c'

    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

# This one looks correct
s.query(A).outerjoin(C, C.a_id == A.id).join(B, B.a_id == A.id).filter(B.data == 'foo').all()


A = Table("a", Base.metadata, autoload=True)
B = Table("b", Base.metadata, autoload=True)
C = Table("c", Base.metadata, autoload=True)

# This one produces a cartesian join...
s.query(A).outerjoin(C, C.c.a_id == A.c.id).join(B, B.c.a_id == A.c.id).filter(B.c.data == 'foo').all()
```

The first query looks as expected:

```
SELECT a.id AS a_id, a.data AS a_data 
FROM a LEFT OUTER JOIN c ON c.a_id = a.id JOIN b ON b.a_id = a.id 
WHERE b.data = ?
```

The second query gets converted into a Cartesian join:

```
SELECT a.id, a.data 
FROM a, b 
WHERE b.data = ?
```

```
.../sqlalchemy/sql/compiler.py:362: SAWarning: SELECT statement has a cartesian product between FROM element(s) "b" and FROM element "a".  Apply join condition(s) between each element to resolve.
  util.warn(message)
```

**Comment by zzzeek** [comment] 2021-03-05 20:15
OK this just join() not picking up at all, look at the query:

```
SELECT a.id, a.data 
FROM a, b 
WHERE b.data = ?

```

**Comment by zzzeek** [comment] 2021-03-05 21:06
thanks for finding this, is not hard to fix but there was something missing that was kind of a big deal in terms of 1.4's Core/ORM rearchitecture.

**Comment by sqla-tester** [comment] 2021-03-05 21:06
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure all Query statements compile w/ orm, fix test harness** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2621

**Closed** 2021-03-07 16:32 UTC
Labels: bug, orm, regression
