### ISSUE TITLE
[BUG] Mssql pyodbc datetime with timezone fail to convert at insertion

### ISSUE THREAD

**Issue by gbmarc1** [sqlalchemy/sqlalchemy#6366] opened 2021-04-26 21:46 UTC
Datetime with **time zone** fail to be converted at insertion.

Regression introduced in 1.4.10 for MSSQL with pyodbc dialect (works in sqlite). It works perfectly fine in 1.4.9.

**Expected behavior**
UTC should be converted properly

**To Reproduce**
```py
class Project(Base):
    """
    Simple table describing projects.
    """

    __tablename__ = "project"

    id = Column("project_id", Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=False)
    created = Column(DateTime, nullable=False)
    modified = Column(DateTime, nullable=False)

session.add(Project(name="name", description="desc", created=datetime.now(tz=pytz.timezone("utc")), modified=datetime.now(tz=pytz.timezone("utc"))))
session.commit()
```

**Error**

```
**{PendingRollbackError}This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pyodbc.DataError) ('22007', '[22007] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)')
[SQL: INSERT INTO project (name, description, created, modified, expired, progress, error, status) OUTPUT inserted.project_id VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('name', 'desc', '2021-04-26 21:35:09.051839 +00:00', '2021-04-26 21:35:09.051861 +00:00', None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)**
```

This works perfectly fine:
```py

session.add(Project(name="name", description="desc", created=datetime.now(), modified=datetime.now()))
session.commit()

```

**Versions.**
 - OS:
 - Python:b 3.8
 - SQLAlchemy: >=1.4.10
 - Database: MSSQL
 - DBAPI: pyodbc

**Comment by zzzeek** [comment] 2021-04-26 22:50
this is from #6306 which I kind of figured would cause a regression, but I thought it would be that people were using timezone=True on their `DateTime` type, which fortunately is not what you're doing here.

**Comment by zzzeek** [comment] 2021-04-26 23:06
note UTC isnt being "converted" here, it's just being dropped.

also there seems to be a loss of microseconds precision using the driver.

**Comment by gbmarc1** [comment] 2021-04-26 23:13
> there seems to be a loss of microseconds precision using the driver.

Yes that is ok. Always been like that with pyodbc

**Comment by sqla-tester** [comment] 2021-04-26 23:17
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Pass all datetime values to pyodbc for timezone-naive column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2779

**Closed** 2021-04-27 02:03 UTC
Labels: SQL Server, bug, regression
