### ISSUE TITLE
SQLAlchemy relationship is returning None unless it is explicitly assigned to a var (i.e. the contents of nested join is read)

### ISSUE THREAD

**Issue by aidangannon** [sqlalchemy/sqlalchemy#8625] opened 2022-10-12 18:06 UTC
### Describe the bug

When the following query is performed it intermittently returns None for the children property 'values':
```py
first = self._data_manager.session \
            .query(self._model) \
            .filter(self._model.auth_user_id == auth_user_id) \
            .first()
```

I am using an imperative mapping approach here:

```py
# tables
brand_table = Table('brand', Base.metadata,
                    Column('id', String(length=36), primary_key=True),
                    Column('created', DateTime),
                    Column('auth_user_id', String(length=64)),
                    Column('brand_name', String(length=120)),
                    Column('brand_description', String(length=500)),
                    Column('header_image', String(length=360)),
                    Column('insta_handle', String(length=30)),
                    Column('website', String(length=120)),
                    Column('logo', String(length=360)))

value_table = Table('value', Base.metadata,
                    Column('id', String(length=36), primary_key=True),
                    Column('created', DateTime),
                    Column('value', Enum(ValueEnum)),
                    Column('entity_id', String(length=64)))

# mappings
sqlalchemy.orm.mapper(Value, value_table)
        sqlalchemy.orm.mapper(Brand, brand_table, properties={
            'values': orm.relationship(Value,
                                       foreign_keys=value_table.c.entity_id,
                                       primaryjoin=brand_table.c.id == value_table.c.entity_id)
        })

# models
@dataclass(unsafe_hash=True)
class Value(DataModel):
    value: ValueEnum = None


@dataclass(unsafe_hash=True)
class Brand(DataModel):
    brand_name: str = None
    brand_description: str = None
    website: str = None
    logo: str = None
    header_image: str = None
    insta_handle: str = None
    values: list[Value] = field(default_factory=list)
    auth_user_id: str = None
```

When I return the result of the query in a request

### To Reproduce

```python
Query:

first = self._data_manager.session \
            .query(self._model) \
            .filter(self._model.auth_user_id == auth_user_id) \
            .first()
```
Custom Mapping to response view:
```
    def __map_brand_to_brand_view(to: Union[BrandRequestDto, BrandResponseDto], _from: Brand):
        new_values = []
        for value in _from.values:
            new_values.append(value.value)
        to.values = new_values
```

### Error

Exception:
```
'NoneType' object is not iterable
``` 

Raw SQL Logs from MySQL:
appears to be doing as 2 queries but on the same thread id -> 26:
```
SELECT brand.id AS brand_id, brand.created AS brand_created, brand.auth_user_id AS brand_auth_user_id, brand.brand_name AS brand_brand_name, brand.brand_description AS brand_brand_description, brand.header_image AS brand_header_image, brand.categories AS brand_categories, brand.insta_handle AS brand_insta_handle, brand.website AS brand_website, brand.logo AS brand_logo 
FROM brand

SELECT value.id AS value_id, value.created AS value_created, value.value AS value_value, value.entity_id AS value_entity_id 
FROM value 
WHERE 'e6f99f40-f587-4879-83b2-5113503fb52f' = value.entity_id
```

Result after query (as you can see, **NO 'values'** field is present ??)

`[('_sa_instance_state', <sqlalchemy.orm.state.InstanceState object at 0x000001FE178F7B50>), ('auth_user_id', 'facebook_10222916817286727'), ('brand_description', 'implement virtual markets'), ('insta_handle', 'brand'), ('website', 'http://placeimg.com/640/480'), ('id', '4efa343e-15fc-498b-9a60-b05a73da1aa9'), ('created', datetime.datetime(2022, 10, 12, 18, 40, 41)), ('brand_name', 'Dach LLC'), ('header_image', None), ('logo', None)])`

The **REALLY WEIRD** thing is, when I debug it and step over it slowly, it does return values, SUPER weird...

`[('_sa_instance_state', <sqlalchemy.orm.state.InstanceState object at 0x000001EA782F6430>), ('id', '4efa343e-15fc-498b-9a60-b05a73da1aa9'), ('created', datetime.datetime(2022, 10, 12, 18, 40, 41)), ('brand_name', 'Dach LLC'), ('header_image', None), ('website', 'http://placeimg.com/640/480'), ('logo', None), ('auth_user_id', 'facebook_10222916817286727'), ('brand_description', 'implement virtual markets'), ('insta_handle', 'brand'), ('values', [Value(id='144e9d36-8152-4547-81ed-0357c06fb3e0', created=datetime.datetime(2022, 10, 12, 18, 40, 41), value='ValueEnum.VALUE9'), Value(id='2776c868-2c24-4e7e-8168-2b27d8f9cf77', created=datetime.datetime(2022, 10, 12, 18, 40, 41), value='ValueEnum.VALUE7'), Value(id='b9751111-0823-42e9-9673-ab008e1da33d', created=datetime.datetime(2022, 10, 12, 18, 40, 41), value='ValueEnum.VALUE8')])])
`

### Versions

- OS: Windows 10
- Python: 3.9
- SQLAlchemy: 1.4.41
- Database: MySQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymysql

**Comment by CaselIT** [comment] 2022-10-12 19:22
Hi

> Result after query (as you can see, NO 'values' field is present ??)

that's expected since there is no loader specified in the relationship, so it'd using the default lazy load https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html?highlight=lazy+load#lazy-loading

I can't otherwise reproduce. I've completed the above script that's not runnable on its own. Try reproducing the error with the given script. I've used sqlite here, but there should not be any difference in with mysql

```py
# tables
from dataclasses import dataclass, field
from datetime import datetime
from sqlalchemy import orm, create_engine
from sqlalchemy.orm.decl_api import declarative_base
from sqlalchemy.sql.schema import Column, Table
from sqlalchemy.sql.sqltypes import DateTime, Enum, String


Base = declarative_base()

brand_table = Table(
    "brand",
    Base.metadata,
    Column("id", String(length=36), primary_key=True),
    Column("created", DateTime),
    Column("auth_user_id", String(length=64)),
    Column("brand_name", String(length=120)),
    Column("brand_description", String(length=500)),
    Column("header_image", String(length=360)),
    Column("insta_handle", String(length=30)),
    Column("website", String(length=120)),
    Column("logo", String(length=360)),
)

value_table = Table(
    "value",
    Base.metadata,
    Column("id", String(length=36), primary_key=True),
    Column("created", DateTime),
    Column("value", String(100)),
    Column("entity_id", String(length=64)),
)


@dataclass(unsafe_hash=True)
class DataModel:
    id: str
    created: datetime = None


# models
@dataclass(unsafe_hash=True)
class Value(DataModel):
    value: str = None


@dataclass(unsafe_hash=True)
class Brand(DataModel):
    brand_name: str = None
    brand_description: str = None
    website: str = None
    logo: str = None
    header_image: str = None
    insta_handle: str = None
    values: list[Value] = field(default_factory=list)
    auth_user_id: str = None


# mappings
Base.registry.map_imperatively(Value, value_table)
Base.registry.map_imperatively(
    Brand,
    brand_table,
    properties={
        "values": orm.relationship(
            Value,
            foreign_keys=value_table.c.entity_id,
            primaryjoin=brand_table.c.id == value_table.c.entity_id,
        )
    },
)

engine = create_engine("sqlite:///")
Base.metadata.create_all(engine)
with orm.Session(engine) as s:
    s.add(
        Brand(
            id="foo", auth_user_id="foo", values=[Value(id="a"), Value(id="b")]
        )
    )
    s.add(Brand(id="bar", auth_user_id="bar"))
    s.commit()

for aui in ("foo", "bar"):
    with orm.Session(engine) as s:
        first = s.query(Brand).filter(Brand.auth_user_id == aui).first()
        new_values = []
        for value in first.values:
            new_values.append(value)
        print(aui, new_values)
```

**Comment by zzzeek** [comment] 2022-10-12 19:55
first thing - the original query calls first() but has no ORDER BY.   the order of the SELECT statement is not guaranteed, not sure if that's coming into play.

second thing.   without a stack trace we can't confirm that it's in fact "from_.values" that is None.   Seems extremely unlikely because SQLAlchemy never puts None for a collection.  You also can't assign it to None.  so I would hypothesize that the "not iterable None type" is something else in your program.

**Comment by aidangannon** [comment] 2022-10-13 16:52
@zzzeek I may have been misleading, the output  from the mapping is None, then it returns an error basically because there is some post-controller middleware that formats my Enum values to strings from enums :).

Turns out the really weird error was occurring was when I was debugging it, it was reading the whole graph (aka lazy loading it all) as confirmed by my two separate SELECT queries. Rather setting the lazy='joined' in my relationship resolved the issue, as I was intending to do a join query in the first place. Thank you @CaselIT.

This can be closed :) sorry for taking up time :)

**Closed** 2022-10-13 16:54 UTC
Labels: orm, cant reproduce, awaiting info

**Comment by aidangannon** [comment] 2022-10-13 16:58
Just curious, why is it doing two separate selects as a default, would join not be the default since the relationship specifies a join condition ? @zzzeek

**Comment by CaselIT** [comment] 2022-10-13 17:02
the first part of this article has some information regarding the behaviour https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html

in short it's not always a given that a relationship should be loaded in all cases. also using a join is not the best option in case of multiple levels of relationships
