### ISSUE TITLE
TypeDecorator on PostgreSQL range type is passed `bool` from comparison operator.

### ISSUE THREAD

**Issue by TallJimbo** [sqlalchemy/sqlalchemy#5476] opened 2020-07-26 16:41 UTC
**Describe the bug**
When defining a `TypeDecorator` based on `dialects.postgresql.ranges.INT8RANGE` (or any other range, I think), `process_result_value` is called with the result of calling the `overlaps` method (or other comparisons) from `dialects.postgresql.ranges.RangeComparison.comparison_factory`, even though that returns `bool` rather than a range type.

[Docs](https://docs.sqlalchemy.org/en/13/core/custom_types.html#redefining-and-creating-new-operators) suggest that operators that return `bool` should be marked by passing `is_comparison` to `Operators.op`, which is indeed missing (e.g. https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/ranges.py#L58), and I _suspect_ that explains what I'm seeing.

**Expected behavior**
Calling `overlaps` or other `bool`-returning comparison methods in a query should bypass the `TypeDecorator`'s result processing.

**To Reproduce**
I am happy to provide a minimal example upon request, but would prefer to spend that time writing an actual test in a PR instead, if I can first get confirmation here that my diagnosis is correct.

**Versions.**
 - OS: Linux (Mint 20.0)
 - Python: 3.7
 - SQLAlchemy: 1.3.17 (_if_ my diagnosis is correct, the problem is present on master as well)
 - Database: PostgreSQL
 - DBAPI: psycopg2 2.8.5

**Comment by zzzeek** [comment] 2020-07-26 17:08
I'm not sure offhand, so feel free to write a PR that includes just the tests you want to write which illustrate the expected behavior and how it fails.   your description of what goes wrong itself requires that I read the source code to understand why its wrong so usually I like to see a test case that illustrates the actual use case you are trying to do and how *that* part is failing, then I can start looking at the appropriate spots with some context.  I've never actually used the range types and they were contributed by others many years ago.

once you do that I'll run those tests and start looking at what should be happening here.

**Comment by zzzeek** [comment] 2020-07-26 20:48
ah yes, now I see what you are referring towards.   a boolean operator for range returns a SQL expression that is of type Boolean, not <whatever type>, so yes, that's correct.    because the range types don't have any result processor normally this did not produce any effect.

**Comment by sqla-tester** [comment] 2020-07-26 20:57
**Jim Bosch** has proposed a fix for this issue in the **master** branch:

**Ensure is_comparison passed for PG RANGE op() methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2107

**Comment by sqla-tester** [comment] 2020-07-26 20:57
**Jim Bosch** has proposed a fix for this issue in the **rel_1_3** branch:

**Ensure is_comparison passed for PG RANGE op() methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2108

**Closed** 2020-07-29 16:49 UTC
Labels: bug, datatypes, postgresql
