### ISSUE TITLE
TypeError in query offset with expression inside and first() method

### ISSUE THREAD

**Issue by artslob** [sqlalchemy/sqlalchemy#4803] opened 2019-08-11 10:34 UTC
How to reproduce:
1. Run postgres database in docker:
```bash
docker run --rm --name pg -e POSTGRES_PASSWORD=pass -p 15432:5432 postgres:11.5
```
2. Create new virtual environment for python3.6 and install required packages:
```bash
python3.6 -m venv ~/.virtualenvs/sqlalchemy-bug-report
source ~/.virtualenvs/sqlalchemy-bug-report/bin/activate
pip install psycopg2-binary==2.8.3 sqlalchemy==1.3.6
```
3. Create script with name `main.py`:
```python
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import func

engine = create_engine('postgresql+psycopg2://postgres:pass@localhost:15432/postgres', echo=True)
Base = declarative_base()


class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    name = Column(String)

    def __str__(self):
        return f"user: (id={self.id}, name='{self.name}')"

    def __repr__(self):
        return self.__str__()


Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)


def main():
    session = Session()
    session.query(User).delete()
    session.add_all(User(id=i, name=f'user {i}') for i in range(1, 16))
    session.commit()
    query = session.query(User).offset(func.floor(func.random() * session.query(func.count(User.id)))).limit(1)
    print(good(query))
    print(bad(query))


def good(query):
    return query.all()


def bad(query):
    return query.first()


if __name__ == '__main__':
    main()

```

_What it does_: creates table `users`, make some insert into it, then main part - it creates query to select random row from this table. It achive it by using random offset and limit 1. Basically like in [this](https://stackoverflow.com/a/33583008) stackoverflow answer.

4. Run script: `python3 main.py`.
5. Locally I get this log:
```
/home/artslob/.virtualenvs/sqlalchemy-bug-report/bin/python /home/artslob/projects/python/sqlalchemy-bug-report/main.py
2019-08-11 12:57:29,715 INFO sqlalchemy.engine.base.Engine select version()
2019-08-11 12:57:29,716 INFO sqlalchemy.engine.base.Engine {}
2019-08-11 12:57:29,717 INFO sqlalchemy.engine.base.Engine select current_schema()
2019-08-11 12:57:29,717 INFO sqlalchemy.engine.base.Engine {}
2019-08-11 12:57:29,718 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-11 12:57:29,718 INFO sqlalchemy.engine.base.Engine {}
2019-08-11 12:57:29,719 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-11 12:57:29,719 INFO sqlalchemy.engine.base.Engine {}
2019-08-11 12:57:29,720 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2019-08-11 12:57:29,720 INFO sqlalchemy.engine.base.Engine {}
2019-08-11 12:57:29,721 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2019-08-11 12:57:29,721 INFO sqlalchemy.engine.base.Engine {'name': 'users'}
2019-08-11 12:57:29,724 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-08-11 12:57:29,724 INFO sqlalchemy.engine.base.Engine DELETE FROM users
2019-08-11 12:57:29,724 INFO sqlalchemy.engine.base.Engine {}
2019-08-11 12:57:29,727 INFO sqlalchemy.engine.base.Engine INSERT INTO users (id, name) VALUES (%(id)s, %(name)s)
2019-08-11 12:57:29,727 INFO sqlalchemy.engine.base.Engine ({'id': 1, 'name': 'user 1'}, {'id': 2, 'name': 'user 2'}, {'id': 3, 'name': 'user 3'}, {'id': 4, 'name': 'user 4'}, {'id': 5, 'name': 'user 5'}, {'id': 6, 'name': 'user 6'}, {'id': 7, 'name': 'user 7'}, {'id': 8, 'name': 'user 8'}  ... displaying 10 of 15 total bound parameter sets ...  {'id': 14, 'name': 'user 14'}, {'id': 15, 'name': 'user 15'})
2019-08-11 12:57:29,731 INFO sqlalchemy.engine.base.Engine COMMIT
2019-08-11 12:57:29,736 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-08-11 12:57:29,737 INFO sqlalchemy.engine.base.Engine SELECT users.id AS users_id, users.name AS users_name 
FROM users 
 LIMIT %(param_1)s OFFSET floor(random() * (SELECT count(users.id) AS count_1 
FROM users))
2019-08-11 12:57:29,737 INFO sqlalchemy.engine.base.Engine {'param_1': 1}
[user: (id=15, name='user 15')]
Traceback (most recent call last):
  File "/home/artslob/projects/python/sqlalchemy-bug-report/main.py", line 46, in <module>
    main()
  File "/home/artslob/projects/python/sqlalchemy-bug-report/main.py", line 34, in main
    print(bad(query))
  File "/home/artslob/projects/python/sqlalchemy-bug-report/main.py", line 42, in bad
    return query.first()
  File "/home/artslob/.virtualenvs/sqlalchemy-bug-report/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3228, in first
    ret = list(self[0:1])
  File "/home/artslob/.virtualenvs/sqlalchemy-bug-report/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3014, in __getitem__
    res = self.slice(start, stop)
  File "<string>", line 2, in slice
  File "/home/artslob/.virtualenvs/sqlalchemy-bug-report/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/home/artslob/.virtualenvs/sqlalchemy-bug-report/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3057, in slice
    self._offset = (self._offset or 0) + start
  File "/home/artslob/.virtualenvs/sqlalchemy-bug-report/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 516, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

Process finished with exit code 1
```

**Problem**: same query works with `all()` method, but not with `first()`.

_My thougths why its happening_: magic method `__bool__()` of `ClauseElement` from `sqlalchemy/sql/elements.py` raises exceptions when called. Its done to prevent programmers from constructiong sql queries using python `and` and `or` keywords, because they can not be overloaded like operators. Code in `sqlalchemy/orm/query.py` check for existence of offset or makes it by default to 0. But `self._offset or 0` implicitly calls method `__bool__()` of `ClauseElement`, so it raises exception. Link to [changelog](https://docs.sqlalchemy.org/en/13/changelog/migration_06.html#an-important-expression-language-gotcha). But when compiling `all()` this code does not executes.

_My thoughts how to fix_: rewrite `self._offset or 0` to something that use check `is None`:
```python
self._offset = (0 if self._offset is None else self._offset) + start
```

**Comment by zzzeek** [comment] 2019-08-11 14:40
hi there -

thanks for the great amount of effort in reporting this issue.  For future reference, we have access to Postgresql databases, as well as MySQL, Oracle, SQL Server so there's no need to illustrate container setups.   Additionally, if you show the code that makes the error, and the stack trace, that's all we need to provide for a fix, provided the issue is in fact a bug.

in this case, the code you've identified is a sort of one-line conditional that is common in many programming languages, but in Python once the ternary conditional was introduced, they became unnecessary, as the ternary operator ("foo if bar else bat") makes the intent much more clear.  In SQLAlchemy, most "return x or y" types of operations should be replaced with real ternaries and as you've observed, places where clause objects are checked need to be compared against None.  In this case, allowing a SQL expression for "offset" was a relatively late feature add, and additionally usage of "first()" did not expect that limit/offset would already be applied to the query.

the reproducer for this issue is three lines:

```
>>> from sqlalchemy.orm import Session
>>> from sqlalchemy import column
>>> Session().query(column('foo')).offset(column('bar')).first()

```

**Comment by sqla-tester** [comment] 2019-08-11 14:55
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use ternary when running conditional with Query._offset** https://gerrit.sqlalchemy.org/1403

**Comment by sqla-tester** [comment] 2019-08-11 14:56
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use ternary when running conditional with Query._offset** https://gerrit.sqlalchemy.org/1404

**Closed** 2019-08-12 02:01 UTC
Labels: bug, orm

**Comment by sqla-tester** [comment] 2019-08-14 14:35
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Turn on backend for new tests added for #4803** https://gerrit.sqlalchemy.org/1415

**Comment by sqla-tester** [comment] 2019-08-14 14:49
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Turn on backend for new tests added for #4803** https://gerrit.sqlalchemy.org/1416
