### ISSUE TITLE
Missing join-loaded relations for polymorphic models

### ISSUE THREAD

**Issue by davidparsson** [sqlalchemy/sqlalchemy#5129] opened 2020-01-31 12:37 UTC
We have found what seems to be a bug in SQLAlchemy's `lazy="joined"` loading. It is present in the last stable public version, `1.3.13`.

There are a few conditions that together may cause a Parent to miss some related Children when loaded:

- The Parent is polymorphic
- The Parent has join-loaded Children
- The Parent is loaded from a Grand Parent
- The Parent has an attribute that is accessed in `InstanceEvents.load()`

Below is a reproducible, probably minimal but not so small example:
```python
import enum

import sqlalchemy
from sqlalchemy import Column
from sqlalchemy import Enum
from sqlalchemy import event
from sqlalchemy import Float
from sqlalchemy import ForeignKey
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class DefaultBase(Base):
    id = Column(Integer, primary_key=True, autoincrement=True)

    __abstract__ = True

    def __repr__(self):
        return f"<{self.__class__.__name__} id={self.id}>"


class GrandParent(DefaultBase):
    parent_id = Column(Integer, ForeignKey("parent.id"))
    parent = relationship("Parent")

    __tablename__ = "grand_parent"


class ParentType(enum.Enum):
    TYPE_A = "Type A"


class Parent(DefaultBase):
    parent_type = Column(Enum(ParentType, name="parent_type"))
    children = relationship("Child", lazy="joined")

    __tablename__ = "parent"
    __mapper_args__ = {"polymorphic_on": parent_type}


class ParentA(Parent):
    id = Column(Integer, ForeignKey(Parent.id), primary_key=True)
    some_float = Column(Float())  # This value will be loaded in on_load

    __tablename__ = "parent_a"
    __mapper_args__ = {"polymorphic_identity": ParentType.TYPE_A}


class Child(DefaultBase):
    parent_id = Column(Integer, ForeignKey(Parent.id))

    __tablename__ = "child"


@event.listens_for(ParentA, "load", propagate=True)
def on_load(instance, context):
    instance_state = inspect(instance)
    _ = instance_state.attrs["some_float"].value  # Reading a value is required


def main():
    session = setup_database_and_session()

    children = [Child(), Child()]
    parent = ParentA(children=children)
    grand_parent = GrandParent(parent=parent)

    session.add(grand_parent)
    session.commit()
    session.expunge_all()

    grand_parent = session.query(GrandParent).one()
    parent = grand_parent.parent  # Fetching from grand_parent is required
    before = parent.children.copy()  # [<Child id=1>] # Incorrect!

    session.rollback()

    after = parent.children.copy()  # [<Child id=1>, <Child id=2>] # Correct!

    assert before == after, f"{before} != {after}"


def setup_database_and_session():
    engine = sqlalchemy.create_engine("sqlite://")
    session_maker = sqlalchemy.orm.sessionmaker(bind=engine)
    session = session_maker()
    Base.metadata.create_all(engine)
    return session


if __name__ == "__main__":
    main()
```

The example fails with the following assertion error:
```
AssertionError: [<Child id=1>] != [<Child id=1>, <Child id=2>]
```

It seems `lazy="subquery"` also has similar issues, but not identical, and while we have observed issues we have not fully reproduced them.

**Comment by zzzeek** [comment] 2020-01-31 16:18
your access of an unloaded attribute inside the event hook triggers a row-refresh operation on the object, which removes it from the current loading context such that eager loaders that were in progress now ignore the object.

I've devised a way that this scenario may be resolved, while it also being an "opt in" behavior, so that I don't need to worry about this causing any regressions for anyone else so that I can release this in the 1.3.x series.    in 1.3.14, the test case above will emit a warning suggesting to use the restore_load_context flag.  It also has a bunch of new documentation for the three events which are impacted by this issue.  Originally I thought I was going to have to document this all as caveats but fortunately for those applications that use a pattern like this, they will now get a warning alerting them that it's happening, and will also provide a resolution that hopefully doesn't have any other side effects (it certainly shouldn't).

Right now you can affect the same effect as the restore_load_context flag like this:


```
@event.listens_for(ParentA, "load", propagate=True)
def on_load(instance, context):
    instance_state = inspect(instance)
    restore_runid = instance_state.runid
    _ = instance_state.attrs["some_float"].value  # Reading a value is required
    instance_state.runid = restore_runid

```

**Comment by zzzeek** [comment] 2020-01-31 16:19
also fully perfect test case, thanks very much for taking the time to do a very good job on this.

**Comment by zzzeek** [comment] 2020-01-31 16:21
note I can't reproduce an issue with subqueryload.   if you can see if the above mitigation also fixes that case for you, that would help a lot.    there's a chance there still could be some other state change that impacts subqueryload or selectinload.

**Comment by sqla-tester** [comment] 2020-01-31 16:39
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Warn for runid changing in load events; add restore_load_context flag** https://gerrit.sqlalchemy.org/1699

**Comment by sqla-tester** [comment] 2020-01-31 16:39
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Warn for runid changing in load events; add restore_load_context flag** https://gerrit.sqlalchemy.org/1700

**Closed** 2020-01-31 20:01 UTC
Labels: events, orm, use case

**Comment by davidparsson** [comment] 2020-01-31 21:10
This is brilliant! I was not expecting such a quick response, and with both a fix and a workaround. Thank you! 🏆

I'll keep an eye out for the subquery issue.

**Comment by davidparsson** [comment] 2020-02-03 08:43
I was mistaken, we have not seen any issues related to `lazy="subquery"`.

Thanks again for an exceptional library with exceptional support! 🍰
