### ISSUE TITLE
Use psycopg2 execute_values() instead of execute_batch()

### ISSUE THREAD

**Issue by ydinari** [sqlalchemy/sqlalchemy#4623] opened 2019-04-23 07:54 UTC
Hi,
When working with psycopg2 and setting flag use_batch_mode, a call to psycopg2.extras.execute_batch() is used instead of cursor.executemany(). But there's a faster function - [psycopg2.extras.execute_values()](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.execute_values).
execute_batch works by concatenating single insert statements (using ';') and sending them together to the server.
execute_values works by creating a single insert statement with multiple tuples, which is much faster
(for both the page_size parameter determines the number of rows that will be inserted in each call to the database).
In my case I saw a 40% improvement using execute_values().

**Comment by zzzeek** [comment] 2019-04-23 19:39
hi there- 

you can use the SQL behavior present in execute_values() yourself by using [insert.values()](https://docs.sqlalchemy.org/en/13/core/dml.html?highlight=insert%20values#sqlalchemy.sql.expression.Insert.values).

We don't use psycopg2 `execute_values()` because it requires dramatic changes to the string contents of the `INSERT` construct as well as requires that a "template" be composed.  These are things that are possible but are complicated to implement and test; whereas "execute_batch()" was a simple drop-in.

I will welcome efforts to implement this feature fully including complete unit tests however I have no plans to work on this feature myself.

**Comment by zzzeek** [comment] 2019-04-23 19:42
i will leave off "wontfix" for the moment if I can get a sense of how much volunteer motivation there is for this feature.  It would require extensive new changes within the psycopg2 ExecutionContext code.

**Comment by ydinari** [comment] 2019-04-29 08:49
Hi,
insert.values() doesn't really help me since I have a declarative model with the commit() done automatically and I don't won't to change that and write all the insert code myself.
The change to the SQL insert statement is not so great actually: you just need to replace the placeholders string with a single '%s', and that placeholders string is exactly what you need to pass as the 'template' argument to execute_values().
I'd be happy to help implement this if you give me some pointers as to where in the code this should happen, and if that would prove to be a reasonable sized task.
Thanks!

**Comment by zzzeek** [comment] 2019-04-29 13:55
> Hi,
> insert.values() doesn't really help me since I have a declarative model with the commit() done automatically 

yes, I know, support for the feature you are requesting is not unreasonable


> The change to the SQL insert statement is not so great actually: you just need to replace the placeholders string with a single '%s', and that placeholders string is exactly what you need to pass as the 'template' argument to execute_values().

Setting aside the discussion of whether or not the development effort is significant for this, I don't personally have the development time to work on this in the near future as it is something that motivated volunteers can be contributing towards, it's not a bug preventing things from working, and there are higher priority items that require my attention.   That is, I agree, this is well within the scope of what folks other than myself could be working on.


> I'd be happy to help implement this if you give me some pointers as to where in the code this should happen, and if that would prove to be a reasonable sized task.

The center of where things go on for this feature will be here: 

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L747

however the complexity is that you now must add additional logic that can detect whether or not an INSERT statement is being used, and to then write the INSERT appropriately.  There are two strategies that can be employed.

The first is the "regex" approach, and for this version you'd want to be working at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L506 and you'd work inside a method called "pre_exec()", you'd want to look at the "self.isinsert" flag that is on the execution context, and then do the rewriting of "self.statement".      This would accommodate for INSERT statements that were compiled.  

The second approach is probably better, and is to address it at the compiler level.     In the psycopg2 compiler at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L532, you'd add a visit_insert() method which reconfigures how the INSERT statement is generated, based on looking at "self.dialect.use_batch_mode" which itself may also need to change as I prefer new features like this are "opt in", that is, only users that select the new enhancement get the new behavior.

another decision to be made is if we are using execute_values(), for which statements does this apply, such as, if the user passes a plain string INSERT statement, are we trying to detect that as well and rewrite?  To get at INSERT statements hand-written by the user, you'd need to perform more regex checks on the string statement after detecting that this statement was not compiled.   This is error prone and difficult to test as you have no idea what formatting or other syntaxes may be present in the string SQL that can interfere with the regex and can break a previously working application.    I'd say this is out of scope.  

So when we use execute_values() for specific INSERT statements,  do all the other DML statements still get invoked via execute_batch() ?     That is, does "use_batch_mode=True" or "use_batch_mode='insertvalues'" really indicate that we at once are using *both* batch modes at once, depending on if the statement is a compiled INSERT (where we can rewrite it accurately and efficiently in the compiler and use execute_values()) or any other statement (string INSERT, UPDATE, etc) in which case we use execute_batch().  Probably.

For tests you'd be looking at https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/postgresql/test_dialect.py#L154 where we would need to add some more tests and it would be good if we could get some mock tests in there, e.g. you mock.patch("psycopg2.extras.execute_values") and verify that the correct arguments are being passed.

**Comment by ydinari** [comment] 2019-05-01 15:02
Hi,
Been looking at overriding PGCompiler_psycopg2.visit_insert(). Changing the sql string seems simple enough. The bigger problem is that psycopg2.execute_values() need the template parameter, and this might entail that a bunch of methods will need to receive and pass that extra parameter.
I'm wondering if that can be avoided, for example by having the template as an extra field of PGCompiler_psycopg2, and then do_executemany() will receive the context instead of the statement string. Since the context contains both the statement and the compiled object, it will be possible to extract it and call execute_values().
If there's some simpler solution I'd love to hear it :)
Thanks

**Comment by ydinari** [comment] 2019-05-01 15:10
Another option would be to change the parameters to batch inserts from dictionaries to tuples, then you don't need to pass the template parameter to execute_values(). I don't know if that change would be simpler or not.

**Comment by zzzeek** [comment] 2019-05-02 16:41
I think accumulating this template string as the compilation process proceeds sounds like a reasonable approach.    as you may have noticed when you get into do_executemany(), you have there access to the ExecutionContext which then has access to the Compiled object.  so all the context should be available.     Once this is worked up into a patch with passing tests we can see the best way to organize things.

**Comment by zzzeek** [comment] 2019-06-12 23:12
Hi just had a lot of thoughts on this and they are for me to look at later, so they might not make much sense to others.

So here is the big thing with this feature, is that it's not as much the "VALUES () ()" part as it is getting the RETURNING part, and getting the ORM to use that.   Right now all of the "inserted_primary_key" logic in Core, whether or not it uses RETURNING, is fixed on the notion that we are getting a primary key back for just *one* row.     since "VALUES () ()" and RETURNING together return a result set of multiple rows, we can actually get PKs and column defaults back en masse, and the ORM would need an entirely new block of logic to do that, because right now the "executemany" side of it is not getting back new PK values at all.

so if we want the ORM to use this, right now it can either have a whole block for "uses VALUES () () plus uses RETURNING", which I think is too much in the ORM, or Core needs a whole new way to do executemany() where RETURNING might actually be usable, which means API features like result.inserted_primary_key, result.returned_defaults have to be rethought that they support muttiple rows.   I think this should be looked at because the "one execute per INSERT" thing really kills performance.

We also already have the notion of insert() statements not being compiled into a string until the data is present; that's the point of the "keys" that are passed to the compiler.   In this case, getting multi-VALUES going might be a product of not just "keys" but "number of rows", although for query caching, adding the "VALUES () () ()" after the fact within the execute phase might still be the way to go.

**Comment by zzzeek** [comment] 2019-06-12 23:13
I think also I might want to do the string replacement in SQLAlchemy instead of using PG's feature, because then it can work for other backends too

**Comment by zzzeek** [comment] 2019-06-13 13:55
> So what I understand from the last two posts is that this feature is going to be implemented differently than we previously thought.

mmmm I used the word "might", just had some thoughts, that's all.    After a nights sleep, using psycopg2's hook seems more appealing again since MySQL's driver might already be doing this "VALUES" optimization internally.

I think the main thing I thought of above, is that we should be able to get at RETURNING, that's all.    not sure if psycopg2's feature allows for that (it probably should).

> I was actually going to start working on this, but now I think we need to re-discuss how this should be implemented.
> Here are a couple of things to consider that popped up in my mind:
> 
>     1. If creating the query string with parameter replacement on sqlaclchemy side, there's a paging issue that also need to be handled. In psycopg2, whether you use execute_batch() or execute_values() there's a page-size parameter (that defaults to 100) that determine how many rows will be in each request to the database.

that's great, because I was worrying about that last night as well.   It looks like we're on the default of 100 which I assume is kind of low for a lot of use cases.


> 
>     2. We need to implement the logic for values conversion from python to sql (and I guess this is per database type)
>        Tell me how you want to proceed. I think the investment is worth while in terms of the performance gain, and also ease of use (RETURNING multiple values is good, without it need to write code to pre-fetch keys etc. if you want to avoid multiple single insert operations invoked from sqlalchemy side).

at the moment my main concern is revisiting old SQLAlchemy APIs like .inserted_primary_key and .returned_defaults, and what happens to these if we just did an executemany() that can return a whole result set of RETURNING values.     There's the obvious way which is, add ".multi_inserted_primary_key" and ".multi_returned_defaults" which seems kind of crappy to me.   

However, the RETURNING side of this can likely be added after the fact, if you wanted to work on implementing psycopg2's execute_values() feature here without RETURNING yet being addressed.

it looks like psycopg2's method even supports returning results with fetch=True.   This is looking very winning to me.    I think getting it in there is a good start, it's then rethinking the Core Result/Dialect/ExecutionContext thing so that the RETURNING results can be integrated without it looking like it was taped on the outside.

**Comment by zzzeek** [comment] 2019-06-13 14:01
all of this stuff here: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L1121 assumes a single row for an INSERT.  with RETURNING, we can have a lot of rows.   the code changes here aren't hard (if self.executemany: ..etc ..) , it's just adding even more attributes to ResultProxy is making me sad but i don't know theres any other way to express this API.   Looking at how the ORM would want to call upon the multiple primary key / default result sets is likely the best place to start.

**Comment by ydinari** [comment] 2019-06-17 11:23
So we go back to previous implementation plan as first phase, without touching returning issue, correct?

**Comment by zzzeek** [comment] 2019-06-17 13:49
I can't guarantee anything 100% but I think implementing psycopg2's feature here without adding "returning" hooks is likely a good start, yes

**Comment by ydinari** [comment] 2019-07-15 11:47
Hi,
I implemented the feature and want to submit it for review. However I don't have access rights to create branches in the repo. How should I proceed?

**Comment by zzzeek** [comment] 2019-07-15 12:57
hi -

you would create a github pull request against your own repository which is forked from this one.   https://help.github.com/en/articles/creating-a-pull-request

**Comment by ydinari** [comment] 2019-07-15 13:39
OK. And should it be based on master or rel_1_3?

**Comment by zzzeek** [comment] 2019-07-15 14:01
always on master, also we need to have tests, if you dont have them yet, put up what you have and we can talk about it.

**Comment by ydinari** [comment] 2019-07-15 14:06
I based it on rel_1_3, so I'll delete it and reopen based on master

**Comment by sqla-tester** [comment] 2019-07-15 17:57
**Yuval Dinari** has proposed a fix for this issue in the **master** branch:

**Enable use of psycopg2.execute_values()** https://gerrit.sqlalchemy.org/1355

**Comment by ydinari** [comment] 2019-07-17 15:17
Hi,
Check my latest commits. PEP8 seems satisfied, and added fallback to execute_batch for non insert queries.
Also, how do I generate the html documentation, to check how the documentation I added looks like?

**Comment by zzzeek** [comment] 2019-07-17 15:48
hi -


my apologies that I am very backlogged right now and I am not able to give this much attention until I can get to it, you can generate the docs in doc/build.   install the requirements from doc/build/requirements.txt as well as sphinx, then do "make html".

Here's what it looks like with a virtualenv, should run on any unix-like environment as is:

```
[classic@photon2 sqlalchemy]$ cd doc/build/
[classic@photon2 build]$ virtualenv .venv

    # ... output

[classic@photon2 build]$ source .venv/bin/activate
(.venv) [classic@photon2 build]$ pip install -r requirements.txt 

   # ... output

(.venv) [classic@photon2 build]$ make html
sphinx-build -b html -d output/doctrees  -v . output/html
Running Sphinx v1.8.2

    # ... wait several minutes

Build finished. The HTML pages are in output/html.

then browse in output/html/index.html

```

**Comment by ydinari** [comment] 2019-07-18 10:21
Hi, check out last commits:
* Increased the page_size parameter for execute_values(). It turns out that this does more for improving performance than using execute_values() instead of execute_batch(). execute_values() is still faster, check out these [results](https://drive.google.com/open?id=171BthMttmjimhGRhqCUqVkU9Qn_1ExoD) of inserts operations from a single transaction.
* Fixed documentation

**Comment by sqla-tester** [comment] 2019-08-12 21:26
**Yuval Dinari** has proposed a fix for this issue in the **rel_1_3** branch:

**Add new executemany_mode, support for psycopg2.extras.execute_values()** https://gerrit.sqlalchemy.org/1413

**Comment by zzzeek** [comment] 2019-08-17 01:57
we have to take another pass at this as my regexp approach was a little rushed and has bypassed some apparent cases where a generated INSERT has newlines.

**Comment by sqla-tester** [comment] 2019-08-17 03:00
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Revise psycopg2 execute_values approach** https://gerrit.sqlalchemy.org/1419

**Comment by sqla-tester** [comment] 2019-08-17 03:00
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Revise psycopg2 execute_values approach** https://gerrit.sqlalchemy.org/1420

**Closed** 2019-08-18 20:37 UTC
Labels: motivated volunteers requested, performance, postgresql, sql
