### ISSUE TITLE
update the allow_unmapped error message to be less confusing with dataclasses; consider adding InitVar to whitelist

### ISSUE THREAD

**Issue by garyvdm** [sqlalchemy/sqlalchemy#8973] opened 2022-12-12 15:49 UTC
### Describe the use case

Dataclasses allow for [Init-only variables](https://docs.python.org/3/library/dataclasses.html#init-only-variables) by type hinting using `InitVar`.  This allows for adding `__init__` arguments, that are not stored in the dataclass. These are typically used by `__post_init__` methods.

Sqlalchemy should should allow one to use `InitVar` by simply ignore these fields, as it does with `ClassVar`

It would be useful where one would want to simplify initialization of sqlalchemy dataclass orm objects.

### Databases / Backends / Drivers targeted

All

### Example Use

    @dataclass
    class Identity:
        display_name: str
        user_id: str
        principals: List[str] = field(default_factory=list)

    @reg.mapped_as_dataclass()
    class AuditLog:
        __tablename__ = "audit_log"
        alid: Mapped[int] = mapped_column(primary_key=True, init=False)
        action: Mapped[str] = mapped_column()
        timestamp: Mapped[datetime] = mapped_column(default_factory=datetime.now)
        data: Mapped[Dict] = mapped_column(JSONB, default_factory=dict)

        user_id: Mapped[str] = mapped_column(default_factory=None)
        identity: InitVar[Identity] = field(default=None)

        def __post_init__(self, identity: Identity):
            if identity:
                self.user_id = identity.user_id

    identity = Identity(display_name="John Smith", user_id="john")
    audit_log = AuditLog(identity=identity, action="delete_object")

**Comment by zzzeek** [comment] 2022-12-12 17:45
Hi -

can you illustrate what's not working? See mcve below

```py
from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from dataclasses import InitVar
from datetime import datetime
from typing import Dict
from typing import List
from typing import Optional

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import registry


reg = registry()

@dataclass
class Identity:
    display_name: str
    user_id: str
    principals: List[str] = field(default_factory=list)

@reg.mapped_as_dataclass()
class AuditLog:
    __tablename__ = "audit_log"
    alid: Mapped[int] = mapped_column(primary_key=True, init=False)
    action: Mapped[str] = mapped_column()
    timestamp: Mapped[datetime] = mapped_column(default_factory=datetime.now)
    data: Mapped[Dict] = mapped_column(JSONB, default_factory=dict)

    user_id: Mapped[Optional[str]] = mapped_column(default=None)
    identity: InitVar[Optional[Identity]] = field(default=None)

    def __post_init__(self, identity: Optional[Identity]):
        if identity:
            self.user_id = identity.user_id

identity = Identity(display_name="John Smith", user_id="john")
audit_log = AuditLog(identity=identity, action="delete_object")

assert audit_log.user_id == "john"

```

**Comment by zzzeek** [comment] 2022-12-12 23:07
for the moment this seems to work as requested, we allow field() objects to be added to the dataclass and we send them along to the dataclass constructor (we can't just ignore them)

reopen if you have a bug

**Comment by garyvdm** [comment] 2022-12-13 08:03
Apologies. This does work. 

I went back to see where I went wrong. In my real code, instead of ` = field(default=None)` I had just ` = None`.  (Sorry for not actually running my example code).

Then I got this error, and the error message lead me to believe this was not supported.
```
% pytest bpm/tests/test_db_model.py
ImportError while loading conftest '/home/gary/dev/bpm-ng/python/bpm/tests/conftest.py'.
bpm/tests/conftest.py:13: in <module>
    from bpm import db_model
bpm/db_model.py:221: in <module>
    class AuditLog:
ve/lib64/python3.9/site-packages/sqlalchemy/orm/decl_api.py:1366: in decorate
    _as_declarative(self, cls, cls.__dict__)
ve/lib64/python3.9/site-packages/sqlalchemy/orm/decl_base.py:209: in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
ve/lib64/python3.9/site-packages/sqlalchemy/orm/decl_base.py:290: in setup_mapping
    return _ClassScanMapperConfig(
ve/lib64/python3.9/site-packages/sqlalchemy/orm/decl_base.py:525: in __init__
    self._scan_attributes()
ve/lib64/python3.9/site-packages/sqlalchemy/orm/decl_base.py:968: in _scan_attributes
    generated_obj = self._collect_annotation(
ve/lib64/python3.9/site-packages/sqlalchemy/orm/decl_base.py:1105: in _collect_annotation
    extracted = _extract_mapped_subtype(
ve/lib64/python3.9/site-packages/sqlalchemy/orm/util.py:2175: in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
E   sqlalchemy.exc.ArgumentError: Type annotation for "AuditLog.identity" can't be correctly 
interpreted for Annotated Declarative Table form.  ORM annotations should normally make 
use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container 
for the actual type, which indicates the intent that the attribute is mapped. Class variables 
that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated 
Declarative to disregard legacy annotations which don't use Mapped[] to pass, set 
"__allow_unmapped__ = True" on the class or a superclass this class. (Background on this 
error at: https://sqlalche.me/e/20/zlpr)
```


Happy for the bug to be closed.

**Comment by CaselIT** [comment] 2022-12-13 09:22
So you mean you used `identity: InitVar[Optional[Identity]] = None`?

**Comment by garyvdm** [comment] 2022-12-13 12:39
> So you mean you used identity: InitVar[Optional[Identity]] = None?

Correct. Here is a mcve that reproduces: 

    from dataclasses import dataclass
    from dataclasses import field
    from dataclasses import InitVar
    from datetime import datetime
    from typing import List
    from typing import Optional

    from sqlalchemy.orm import Mapped
    from sqlalchemy.orm import mapped_column
    from sqlalchemy.orm import registry


    reg = registry()


    @dataclass
    class Identity:
        display_name: str
        user_id: str
        principals: List[str] = field(default_factory=list)


    @reg.mapped_as_dataclass()
    class AuditLog:
        __tablename__ = "audit_log"
        alid: Mapped[int] = mapped_column(primary_key=True, init=False)
        action: Mapped[str] = mapped_column()
        timestamp: Mapped[datetime] = mapped_column(default_factory=datetime.now)

        user_id: Mapped[Optional[str]] = mapped_column(default=None)
        identity: InitVar[Optional[Identity]] = None

        def __post_init__(self, identity: Optional[Identity]):
            if identity:
                self.user_id = identity.user_id


    identity = Identity(display_name="John Smith", user_id="john")
    audit_log = AuditLog(identity=identity, action="delete_object")

    assert audit_log.user_id == "john"

**Comment by zzzeek** [comment] 2022-12-13 13:49
hey thanks for that.  

this is still expected behavior, though i guess the ask is that "InitVar" be added to the whitelist.   Take a look at what the message says, and from there we can solve the problem by adding `__allow_unmapped__` as mentioned:

```py
@reg.mapped_as_dataclass()
class AuditLog:
    __allow_unmapped__ = True
    __tablename__ = "audit_log"
    alid: Mapped[int] = mapped_column(primary_key=True, init=False)
    action: Mapped[str] = mapped_column()
    timestamp: Mapped[datetime] = mapped_column(default_factory=datetime.now)

    user_id: Mapped[Optional[str]] = mapped_column(default=None)
    identity: InitVar[Optional[Identity]] = None

    def __post_init__(self, identity: Optional[Identity]):
        if identity:
            self.user_id = identity.user_id

```


This is tested as a use case for dataclasses at https://github.com/sqlalchemy/sqlalchemy/blob/e0eea374c2df82f879d69b99ba2230c743bbae27/test/orm/declarative/test_dc_transforms.py#L387 .  the goal is to prevent attributes that are ambiguous for their intent to pass silently.

**Comment by CaselIT** [comment] 2022-12-13 17:50
strange that with `field` it works correctly but without it does not. The same error should be raised, since from sqlalchemy point of view `identity: InitVar[Optional[Identity]] = None` and `identity: InitVar[Optional[Identity]] = field(default=None)` should both be unmapped, no?

**Comment by zzzeek** [comment] 2022-12-13 18:33
the purpose of "allow_unmapped" is to allow legacy mypy mappings where annotations are present to work, like those we see at https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-20-step-six .    at the moment, it's also needed for a dataclass if you have fields that don't clearly state on the right side if they are classlevel, or specific to dataclasses.      There's logic that checks for ClassVar.  here it would be expanded to support InitVar also.

**Comment by CaselIT** [comment] 2022-12-14 08:56
> There's logic that checks for ClassVar. here it would be expanded to support InitVar also.

I think it would make sense. I'll try looking at it to check if we can make it account also for InitVar

**Comment by zzzeek** [comment] 2022-12-18 20:09
I think the best fix here is that if dataclass mappings are used, we just allow_unmapped, and not require that this attribute is set.   the attribute here can remain for "legacy" cases, but someone doing a new dataclass mapping, it won't be legacy by definition.

**Comment by sqla-tester** [comment] 2022-12-18 20:39
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove __allow_unmapped__ requirement from dataclasses** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4312

**Closed** 2022-12-19 20:28 UTC
Labels: use case, dataclasses, orm - annotated declarative
