### ISSUE TITLE
Flaky Bug with field change history

### ISSUE THREAD

**Issue by jamesjjq** [sqlalchemy/sqlalchemy#4466] opened 2019-01-24 19:04 UTC
Hi, 

I have been having issues with a field change that is not recognized by sqlalchemy. 
What I am doing is basically:
```
obj = MODEL.query.filter_by(**kwargs).one_or_none()
if obj is None:
   ...
else:
  logger.info(f'pre-update object: {obj.__dict__}')
  obj.update(**attrs) # this basically calls setattr(obj, key, value) on each pair of key values
  logger.info(f'post-update object: {obj.__dict__}')
  attr_dict = inspect(obj).attrs
  logger.info(f'field: {field}, history_change: {attr_dict[field].history}, '
                     f'history_changed: {attr_dict[field].history.has_changes()}')
```
and what I am seeing in the logs is the value of the field i am interested in did change, but the final log like looks something like:
```
field: field, history_change: History(added=(), unchanged=[new_value], deleted=()), history_changed: False
```
What's more frustrating is that this seems to be a flaky issue that happens maybe 1 in 100 times (the other 99 times change is recognized correctly) so I haven't been able to replicate this issue on my console. 

Is there anything that i can look at/print out in the logs in order figure out what the issue is? I am using flask-sqlalchemy 2.3.2, sqlalchemy 1.12.16, python 3.6, and the instance on which the bug occurs is a docker image running on AWS ECS. Happy to provide any other information.

Thank you for looking at this and thank you for making this amazing ORM package!

**Comment by zzzeek** [comment] 2019-01-24 21:32
hi there -

when it's "1 in 100" then the issue is either specific to the data, or has someting to do with concurrent / race conditions.    It seems likely that you are seeing an attribute not being changed from what its original value was:
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

a1, a2 = A(id=1, data="data 1"), A(id=2, data="data 2")
s.add_all([a1, a2])
s.flush()

a1.data = "data 1 modified"
a2.data = "data 2"

print(inspect(a1).attrs.data.history)
print(inspect(a2).attrs.data.history)

```

```
History(added=['data 1 modified'], unchanged=(), deleted=['data 1'])
History(added=(), unchanged=['data 2'], deleted=())

```

**Comment by jamesjjq** [comment] 2019-01-24 23:49
Hi, thanks for the quick response! 
I also printed out obj.__dict__ from before and after the attribute update, so I know that the "status" attribute value definitely did change.  Are you saying that the likely cause is that another process updated the "status" attribute of this attribute while I was updating its attributes?
would that other change have to be committed/flushed using the same session object?

If I turn on the "sqlalchemy.engine" logger to INFO, would that catch all the commits/flushes being made?

**Comment by zzzeek** [comment] 2019-01-25 00:02
unless you are doing some elaborate sharing of these objects among threads then no I don't expect other threads changed the value, and if it was changes coming from the database (e.g. other processes), you'd still see the new value in "added" even if when it goes to the DB it turns out to be the same value.

INFO logging as well as echo=True on your engine shows you all SQL and parameters being emitted, yes.

**Comment by jamesjjq** [comment] 2019-01-25 00:39
Right, that's what I was getting confused about, different threads should be using different sessions so even if other threads are modifying the database the change to the attribute should still be recognized.

I did just tried calling flush() after making the updating the attributes and the new value is no longer seen as "added". 

so is there some kind of autoflush going on beneath the surface? (I know there is the autoflush option that triggers whenever a query is made, but there is no query being made between the time i update the attribute and the time i check for changes) Should i try turning off autoflush?

is there a way to see if the current changes has been flushed, or just turn on logging whenever a flush happens (turning on all logs would product huge amount of logs and I want to avoid that if possible)? 

Thanks so much for all your help!!!

**Comment by zzzeek** [comment] 2019-01-25 03:03
> Right, that's what I was getting confused about, different threads should be using different sessions so even if other threads are modifying the database the change to the attribute should still be recognized.
> 
> I did just tried calling flush() after updating the attributes and the new value is no longer seen as "added".
> 
> so is there some kind of autoflush going on beneath the surface? (I know there is the autoflush option that triggers whenever a query is made, but there is no query being made between the time i update the attribute and the time i check for changes) Should i try turning off autoflush?

autoflush is only when it runs Query, however Query is used whenever an unloaded attribute on your object has to be loaded, so if you do something like "print(myobject.foo)", and "foo" isn't loaded, you could have autoflush happen there.   so yes try using "with sesssion.no_autoflush" for the important block.

> 
> is there a way to see if the current changes has been flushed, or just turn on logging whenever a flush happens (turning on all logs would product huge amount of logs and I want to avoid that if possible)?

you can intercept flushes using the event hooks like before_flush() and after_flush() which are documented at https://docs.sqlalchemy.org/en/latest/orm/session_events.html

> 
> Thanks so much for all your help!!!

**Comment by zzzeek** [comment] 2019-01-30 16:00
seems like we're OK on this one, closing for now.

**Closed by zzzeek** 2019-01-30 16:00 UTC
Labels: orm, question
