### ISSUE TITLE
_get_constraint_data hanging with unicode table names

### ISSUE THREAD

**Issue by funseiki** [sqlalchemy/sqlalchemy#4486] opened 2019-02-06 23:36 UTC
This is in reference to the following questions:
https://groups.google.com/forum/#!topic/sqlalchemy/l1ttIRVSMac
https://stackoverflow.com/questions/50927998/sqlalchemy-oracle-get-constraint-data-method-hanging-with-unicode-table-names

Problem:
The _get_constraint_data takes a long time (100+ seconds, depending on a variety of factors) to return results for the Oracle dialect.

Cause:
It appears as though the 'info_cache' dict that populates the variables for the _get_constraint_data query is always using unicode characters. Whether this is occurring in SqlAlchemy or cx_Oracle code is unclear. What is clear is that Oracle processes the query slower because of this.

Potential Workaround:
After speaking with the db admin for our Oracle server, he suggested replacing the "all_" tables with their "user_" alternatives (perhaps when just having an owner defined?). 

Here's what my version of dialects/oracle/base.py -- _get_constraint_data looks like:
```python
 @reflection.cache
def _get_constraint_data(self, connection, table_name, schema=None,
                         dblink='', **kw):

    params = {'table_name': table_name}

    text = (
        "SELECT"
        "\nac.constraint_name,"  # 0
        "\nac.constraint_type,"  # 1
        "\nloc.column_name AS local_column,"  # 2
        "\nrem.table_name AS remote_table,"  # 3
        "\nrem.column_name AS remote_column,"  # 4
        "\nrem.owner AS remote_owner,"  # 5
        "\nloc.position as loc_pos,"  # 6
        "\nrem.position as rem_pos,"  # 7
        "\nac.search_condition,"  # 8
        "\nac.delete_rule"  # 9
        "\nFROM user_constraints%(dblink)s ac," # Change starts here
        "\nuser_cons_columns%(dblink)s loc,"  #
        "\nuser_cons_columns%(dblink)s rem" # Change ends here
        "\nWHERE ac.table_name = :table_name"
        "\nAND ac.constraint_type IN ('R','P', 'U', 'C')"
    )

    if schema is not None:
        params['owner'] = schema
        text += "\nAND ac.owner = :owner"

    text += (
        "\nAND ac.owner = loc.owner"
        "\nAND ac.constraint_name = loc.constraint_name"
        "\nAND ac.r_owner = rem.owner(+)"
        "\nAND ac.r_constraint_name = rem.constraint_name(+)"
        "\nAND (rem.position IS NULL or loc.position=rem.position)"
        "\nORDER BY ac.constraint_name, loc.position"
    )

    text = text % {'dblink': dblink}
    rp = connection.execute(sql.text(text), **params)
    constraint_data = rp.fetchall()
    return constraint_data
```

**Comment by zzzeek** [comment] 2019-02-07 00:17
changing it to "user_" is faster because....there are less rows?

**Comment by zzzeek** [comment] 2019-02-07 00:19
specifically, the issue is that....your all_constraints.table_name matching to the given table name is slow?   Can you provide an EXPLAIN for both queries please?    Changing this query is not really an option because we support reflection of any table.    So the best approach here is to figure out why your database has a problem.

**Comment by zzzeek** [comment] 2019-02-07 00:25
can you perhaps try this simple patch, since you seem to be claiming it's the unicode matching causing the issue:

```diff

diff --git a/lib/sqlalchemy/dialects/oracle/base.py b/lib/sqlalchemy/dialects/oracle/base.py
index 95a6c1d21e..b49b29829c 100644
--- a/lib/sqlalchemy/dialects/oracle/base.py
+++ b/lib/sqlalchemy/dialects/oracle/base.py
@@ -1696,13 +1696,13 @@ class OracleDialect(default.DefaultDialect):
             "\nFROM all_constraints%(dblink)s ac,"
             "\nall_cons_columns%(dblink)s loc,"
             "\nall_cons_columns%(dblink)s rem"
-            "\nWHERE ac.table_name = :table_name"
+            "\nWHERE ac.table_name = CAST(:table_name AS VARCHAR2(20))"
             "\nAND ac.constraint_type IN ('R','P', 'U', 'C')"
         )
 
         if schema is not None:
             params["owner"] = schema
-            text += "\nAND ac.owner = :owner"
+            text += "\nAND ac.owner = CAST(:owner AS VARCHAR2(20))"
 
         text += (
             "\nAND ac.owner = loc.owner"

```

**Comment by funseiki** [comment] 2019-02-07 03:59
Using "user_" tables is still faster, but likely due to there being fewer rows as you mentioned.
The query you provided does speed things up significantly, though. I'm down to about 30 seconds with your suggestion.

**Comment by zzzeek** [comment] 2019-02-07 23:11
how many rows do you have in that view ?    I can commit the VARCHAR cast which has the effect of converting to non-unicode first, so indexing with those columns can take place.

**Comment by funseiki** [comment] 2019-02-13 03:56
all_constraints: ~11k
all_cons_columns: ~14k

user_constraints: ~400
user_cons_columns: ~400

**Comment by zzzeek** [comment] 2019-02-13 16:52
I haven't dealt with Oracle EXPLAIN PLAN output in a very long time and it's a bit inconvenient, can you see if moving the "all_*" into subqueries so they act more like views helps anything?   all of the reflection code works against the "ALL_*" views so we can't just change those to "USER_".

```
	SELECT
	ac.constraint_name,
	ac.constraint_type,
	loc.column_name AS local_column,
	rem.table_name AS remote_table,
	rem.column_name AS remote_column,
	rem.owner AS remote_owner,
	loc.position as loc_pos,
	rem.position as rem_pos,
	ac.search_condition,
	ac.delete_rule
	FROM 
		(SELECT * FROM all_constraints WHERE owner = 'scott') ac,
		(SELECT * FROM all_cons_columns WHERE owner = 'scott') loc,
		(SELECT * FROM all_cons_columns WHERE owner = 'scott') rem
	WHERE ac.table_name = :table_name
	AND ac.constraint_type IN ('R','P', 'U', 'C')
	AND ac.constraint_name = loc.constraint_name
	AND ac.r_constraint_name = rem.constraint_name(+)
	AND (rem.position IS NULL or loc.position=rem.position)
	ORDER BY ac.constraint_name, loc.position

```

**Comment by sqla-tester** [comment] 2021-08-18 15:02
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**CAST Oracle table_name, owner, others to VARCHAR(128)** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3008

**Closed** 2021-08-19 15:52 UTC
Labels: bug, oracle, performance
