### ISSUE TITLE
Unconsumed column name when column actually exists and is correct case

### ISSUE THREAD

**Issue by rjsears** [sqlalchemy/sqlalchemy#5245] opened 2020-04-10 18:56 UTC
def update_sqalchemy_zone_config(table_name, zone_name, field_name, field_value):
        metadata = MetaData(bind=None)
        table = Table(table_name, metadata, autoload=True, autoload_with=engine)
        stmt = table.update().where(table.c.name == zone_name).values(field_name = field_value)  

`update_sqlachemy_zone_config('zones', 'zone1', 'enabled', False)`

results in:

`sqlalchemy.exc.CompileError: Unconsumed column names: field_name`

However, if I change **field_name** to **enabled** (my field name) it works:
**from:** 
`stmt = table.update().where(table.c.name == zone_name).values(field_name = field_value)`
**to:** 
`stmt = table.update().where(table.c.name == zone_name).values(enabled = field_value)`

MYSQL 8.0.19
Linux Ubuntu 18.04.3 LTS

There is only one table in my database and it is called zones and only one column in that table is called enabled.

**print(table.c.keys())**
`['name', 'zone_number', 'description', 'gpio', 'enabled']`

**from sqlalchemy.schema import CreateTable
print(CreateTable(table).compile(engine)**
 
    CREATE TABLE zones (
	    name VARCHAR(15) COLLATE utf8_unicode_ci NOT NULL, 
	    zone_number TINYINT NOT NULL, 
	    description VARCHAR(40) COLLATE utf8_unicode_ci NOT NULL, 
	    gpio TINYINT(1) NOT NULL, 
	    enabled TINYINT(1) NOT NULL, 
	    PRIMARY KEY (zone_number)
    )DEFAULT CHARSET=utf8 ENGINE=InnoDB COLLATE utf8_unicode_ci

**Comment by CaselIT** [comment] 2020-04-10 19:04
A python method with this signature `values(field_name = field_value)` will pass a this dict:
`{'field_name': field_value}`

You need to use `values(**{field_name : field_value})`

**Comment by rjsears** [comment] 2020-04-10 19:25
@CaselIT Is this a result of SQAlchemy .values()?

**Comment by CaselIT** [comment] 2020-04-10 19:48
No, that is the default python behavior

```py
def fn(**kw):
  print(kw)

fn(field_name=42)
```

will print `{'field_name': 42}`

Note that `values` also accepts a dict, so you can use `values({field_name : field_value})` directly.

> I copied it from here: https://docs.sqlalchemy.org/en/13/core/dml.html

The problem is that your table does not have a column called `field_name`, so you cannot set a value to a `field_name` column.

**Comment by rjsears** [comment] 2020-04-10 20:39
Ah... I think I missed this (**dialect_kw) in the docs and I assumed name was a variable and that threw me off. 

Thanks again for the help!!

**Comment by CaselIT** [comment] 2020-04-10 20:45
You're welcome. I'll close this. 
Feel free to reopen it if you have other problems

**Closed by CaselIT** 2020-04-10 20:45 UTC
Labels: question
